### ISSUE TITLE
Changes to Public Comment page

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/tdm-calculator#1001]
### Overview
When the TDM calculator is sent to the Planning Commission, the Public Comment page needs to have a heading changes and some text added so that we are still taking feedback on the calculator but also directing people to the city clerk's office to give public comment

### Action Items
- [x] Draft new text
- [x] Draft header changes
- [x] Create mock-up
- [x] Update disclaimer to inform users that we are still taking feedback on the calculator but also directing people to the city clerk's office to give public comment
- [ ] Get sign off from stakeholders
- [ ] Create issue for development and decide if we are going to develop it and hold on the dev server for the publication date.

**Comment by cduong5** [comment]
![After v 1](https://user-images.githubusercontent.com/82553907/147169383-a166e470-5631-4a2c-a206-d9a2de4642fa.png)

**Comment by cduong5** [comment]
Mockup here: https://www.figma.com/file/nD9QK56Mzq7xNSaSUoeGx0/TDM-Calculator?node-id=5209%3A18404

**Comment by KPHowley** [comment]
@cduong5  - i will make sure we get  this link from LADOT when we next meet

**Comment by ExperimentsInHonesty** [comment]
Emily's rewrite for the form
To submit a public comment on the proposed TDM Program (Council File 15-0719-S19), use the City Clerk’s comment form.
“Council File 15-0719-S19” link to https://cityclerk.lacity.org/lacityclerkconnect/index.cfm?fa=ccfi.viewrecord&cfnumber=15-0719-S19
“comment form” link to https://cityclerk.lacity.org/publiccomment/?cfnumber=15-0719-S19

**Comment by cduong5** [comment]
![After v 2](https://user-images.githubusercontent.com/82553907/149258518-32fdc500-82de-4b05-89ef-5737289d3915.png)
Updated the description and added the external links

**Comment by KPHowley** [comment]
Created Follow up issue #1072

**Comment by KPHowley** [comment]
Need to create front end issue and add to icebox as Dependency on Milestone change

**Comment by KPHowley** [comment]
Created follow up Issue #1072

**Comment by ExperimentsInHonesty** [comment]
https://tdmdev.azurewebsites.net/publiccomment
https://tdm.ladot.lacity.org/publiccomment
