### ISSUE TITLE
Page 2 Language Edits

### ISSUE THREAD

**Issue by awikstrom-ladot** [hackforla/tdm-calculator#1009]
The following edits for page 2 of the TDM Calculator.

- [x] : 1For residential, change the three habitable room options as follows: "Units with less than 3 habitable rooms" "Units with 3 habitable rooms" "Units with more than 3 habitable rooms"
- [x] 2: Change affordable housing tooltip to read "All units in the Project (exclusive of manager’s units) are covenanted affordable dwelling units."
- [ ] 3: Move "Industrial / Manufacturing" from the "Office / Business" use to the Warehousing category, and retitle Warehousing category to "Warehousing / Industrial"
- [x] 4: Under "Employment / Office" switch the order of "Other Institutional" and "Government Institution"
- [x] 5: Change "Special Uses" category name to "Arena / Stadium / Theater" 
- [x] 6: Remove convalescent use from the medical uses, as it is exempt from TDM

@Dsomers74 @KPHowley @entrotech

**Comment by entrotech** [comment]
For Item #3, there is no specification called "Industrial / Manufacturing" but there is one called "Office, Business, Manufacturing, Industrial". Is the intent to move the existing "Office, Business, Manufacturing, Industrial" under Industrial / Warehousing, or to split it into two different specifications, one for "Office and Business" under "Employment/Office" and add another specification called "Industrial / Manufacturing" under "Warehousing / Industrial".

Assuming the latter:

- Is the parking formula the same for the Industrial / Manufacturing spec as for the "Office and Business", i.e., 2 spaces per 1000 sf?
- For the project level calculation, is Industrial/Manufacturing considered a Warehouse land use, so we add to if the warehouse sq ft, and the project level will be zero until this subtotal exceeds 250,000 sq ft?

**Comment by entrotech** [comment]
I went ahead and implemented #3 by leaving the Office/Business input under the Employment/Office section and creating a new input for Industrial/Manufacturing, but there are a few implications:
The Industrial/Manufacturing input is now considered a Warehousing/Industrial Land Use. this means that the Project Level calculation for Industrial/Manufacturing will result in a Project Level of 0 until the size is at least 250,000 sq ft (a pretty large Industrial facility), but calculates the parking as 2 spaces per 1000 sq ft, so an Industrial/Manufacturing project starts at 500 spaces - which seems a bit strange.  Maybe this is right,  but maybe we need to adjust the parking multiplier.

**Comment by Dsomers74** [comment]
Hi John,
You are correct to recategorize Industrial/Manufacturing under Industrial /
Warehousing and the parking requirement is 2 per 1,000 sq ft for those
uses.

It's also correct that the manufacturing / industrial uses begin at 250K
for Level 3, with those uses under the 250K threshold qualifying as Level
0. Your conclusion is also salient that we are missing out on some
important uses under the 250K and we intend on revising this to include
lower scale manufacturing / industrial uses in the TDM Compliance levels in
our revised recommendations. However, your changes now reflect the existing
proposal and we will recommend another revision when we settle on the
thresholds prior to our Commission date.

Thanks, David
