### ISSUE TITLE
Update wording and display on Bonus package desciption page

### ISSUE THREAD

**Issue by KPHowley** [hackforla/tdm-calculator#1023]
### Overview
We need to update the display and wording on this page to be more clear and reflect one bonus point being asse

### Action Items

- [ ]  move "Selecting the package will earn one additional bonus point." in the grey box and Bold
- [x] Take bonus points out of boxes showing total points
- [x] Add a separate display box underneath the two bonus boxes that shows one point being added. 
- [x] Update subtitle to be:
"All LEVEL 1 projects qualify for a bonus package. By selecting any bonus package you will receive one additional point. "

**Comment by entrotech** [comment]
Isn't this issue obsolete, since wwe are getting rid of the separate Bonus Package page entirely?
