### ISSUE TITLE
Update final summary page with dropdown design to show mulitple AIN's

### ISSUE THREAD

**Issue by KPHowley** [hackforla/tdm-calculator#1024]
### Overview
We have a new system allowing for multiple AINS and have updated the design for the final summary page to show this. 

### Action Items

- [ ] Add drop down box on side of AIN display
- [ ] Allow for three AINs to be displayed in a line and then hidden afterwards
- [x] Normal state will only display one line
- [x] AINs displayed in same order as from the Create Projects page

### Resources/Instructions

![Frame 9](https://user-images.githubusercontent.com/82553907/143803684-c546a3fa-40cc-49f9-a9c8-74bc09553403.png)

Mockup for AIN/APN summary page. The section will display three AIN/APN numbers at a time by default before it expands.

See mockup here: https://www.figma.com/file/nD9QK56Mzq7xNSaSUoeGx0/TDM-Calculator?node-id=5517%3A19644
See prototype here: https://www.figma.com/proto/nD9QK56Mzq7xNSaSUoeGx0/TDM-Calculator?node-id=5517%3A19591&scaling=min-zoom&page-id=4189%3A15774&starting-point-node-id=5517%3A19580&show-proto-sidebar=1
_Originally posted by @cduong5 in https://github.com/hackforla/tdm-calculator/issues/988#issuecomment-981257060_

**Comment by cduong5** [comment]
@KPHowley Looks good! Don't have additional action items to add.

**Comment by ExperimentsInHonesty** [comment]
@fyliu Please provide update
1. Progress: "What is the current status of your project? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"
5. Pictures (if necessary): "Add any pictures that will help illustrate what you are working on."

**Comment by fyliu** [comment]
There's no progress yet. I just claimed this issue. ETA is next week but after the next team meeting 3/16.

**Comment by fyliu** [comment]
Clarification needed: Do we want to have 3 AINs per line or is that the max AINs per line?
See this screenshot where 3 AINs don't fit on a single line. This is before adding the chevron icon on the right
![2022-03-15 22 51 18 localhost 6cf8c926125d](https://user-images.githubusercontent.com/1160105/158525335-b837aa76-e05a-4f15-8d3f-df1653735352.png)

**Comment by fyliu** [comment]
1. Progress - 
2. Blockers - 
3. Availability - 
4. ETA -

**Comment by fyliu** [comment]
I unassigned myself since @poorvarathore05 is the one working on the issue.

**Comment by fyliu** [comment]
Here's the branch with my work in progress code changes. Feel free to add and remove anything I did, or even create a new branch to start fresh. https://github.com/hackforla/tdm-calculator/tree/1024-summary-ain

**Comment by fyliu** [comment]
At the meeting, we decided to keep it at 3 AINs per line since that was what the stakeholder asked for. I personally feel that it's easier to implement than a fully responsive component.

**Comment by entrotech** [comment]
@seenaiype @poorvarathore05 @fyliu @KPHowley 

IMO, the drop-down feature isn't necessary or desirable, and I'd rather just see it appear as shown in the "dropped-down" view on page 2 of the prototype. My reasons are:
1. It's an extra click to see all of the AINs, and showing all of them doesn't really take that much vertical space.
2. If we put a bit of effort into formatting the page for attractive printing, I think we'd want to show all the AINs, even if there are many.
3. Having multiple AINS doesn't seem to be that common, and LADOT suggests that a limit of 10 would be ok, which would only be 4 lines - if there are 3/line. (Though I also don't think we should place an artificial limit on the max number of AINS.)
4. The display would be cleaner without the drop-down arrow.
5. Least importantly, the coding would be much easier to do with a simple flexbox.

I'd be interested in others' opinions.

**Comment by Biuwa** [comment]
@poorvarathore05 Is this completed or pushed to Dev?

**Comment by fyliu** [comment]
Closing since the work is done.
