### ISSUE TITLE
Update your information to be posted on the Hack for LA website

### ISSUE THREAD

**Issue by KPHowley** [hackforla/tdm-calculator#1028]
### Overview

We need to update the Hack for LA website with information on the team. Please provide the following information on the linked issue. 

### Action Items

- [ ] add your information to the following text as a comment on this page :

Update:
Name: 
GitHub handle:
Role (as you would propose it be displayed):
SLACK ID:

- [x] fyliu
- [x] seenaiype
- [x] jahpe777
- [x] nclairesays
- [x] KPHowley
- [x] Jane4925
- [x] cduong5
- [x] Shaeeka 

Product management: 
- [ ] Once everyone is done, let Bonnie know to update this as comment on: https://github.com/hackforla/website/issues/2576

**Comment by seenaiype** [comment]
Name: Seena Iype
GitHub handle: seenaiype
Role (as you would propose it be displayed): Product Manager
SLACK ID: Seena Iype / U024C8A6H29

_** let me know if I am missing or misstated anything._

**Comment by Jane4925** [comment]
Name: Jane He
GitHub handle: Jane4925
Role (as you would propose it be displayed): UX Research Lead
SLACK ID: @Jane He / U01RDSRT46R

**Comment by cduong5** [comment]
Name: Cathy Duong
GitHub handle: cduong5
Role (as you would propose it be displayed): UI/UX Designer
SLACK ID: Cathy Duong / U028TU0981M

**Comment by fyliu** [comment]
Name: Fang Liu
GitHub handle: fyliu
Role (as you would propose it be displayed): Fullstack Developer
SLACK ID: @Fang / UCE01B4AX

**Comment by jahpe777** [comment]
Name: James Higgs
GitHub handle: jahpe777
Role (as you would propose it be displayed): Frontend Developer
SLACK ID: James Higgs / U015ZGMK171

**Comment by jarmitageux** [comment]
Name: Jill Armitage
GitHub handle: jarmitageux
Role (as you would propose it be displayed): UX Researcher
SLACK ID: Jill Armitage / U02HPUSATL2

**Comment by KPHowley** [comment]
Name: Shaeeka Salauddin
GitHub handle: Shaeeka
Role: UI Design Lead 
SLACK ID: @Shaeeka Salauddin | U028C3EGDDE

**Comment by pmeda12** [comment]
Name: Pranav Meda
GitHub handle: pmeda12
Role (as you would propose it be displayed): UX Researcher
SLACK ID: Pranav Meda / U02KCGML5JB

**Comment by Biuwa** [comment]
#975

**Comment by ExperimentsInHonesty** [comment]
### Gather info for the following people (and anyone else who neededs to be added
Ebi
Syria
Renee

- Name: Pranav Meda
   - GitHub handle: pmeda12
   - Role (as you would propose it be displayed): UX Researcher
   - SLACK ID: Pranav Meda / U02KCGML5JB
- Name: Jill Armitage
  - GitHub handle: jarmitageux
  - Role (as you would propose it be displayed): UX Researcher 
  - SLACK ID: Jill Armitage / U02HPUSATL2
- Name: James Higgs
  - GitHub handle: jahpe777
  - Role (as you would propose it be displayed): Frontend Developer
  - SLACK ID: James Higgs / U015ZGMK171
- Name: Jane He
   - GitHub handle: Jane4925
   - Role (as you would propose it be displayed): UX Research Lead
   - SLACK ID: Jane He / U01RDSRT46R

### Remove
- Vivek Jha
- Kevin Howley
- Claire Nguyen
- Kevin Shih

**Comment by Biuwa** [comment]
## Do an update to the hack for LA website
[Review and update the project profile card for TDM](https://github.com/hackforla/website/issues/new?assignees=&labels=P-Feature%3A+Project+Info+and+Page%2C+role%3A+back+end%2FdevOps%2C+role%3A+front+end%2C+Size%3A+Small%2C+size%3A+0.5pt%2C+time+sensitive&template=project-profile-card-review-and-update.yml&title=Update+Project+Profile%3A+%5BProject+Name%5D) @ExperimentsInHonesty 

Name: Anousha Shadrach
GitHub Handle: Noushie
Role: UX Designer
Slack Member ID: U045EHW8NDA

Name: Moji Momoh
GitHub Handle: mojimoh
Role: Product Manager
Slack Member ID: D04HDM7DM18

Name: Jamie Stroh 
GitHub Handle: jamiedesignedit
Role: UX Designer
Slack Member ID" U0437F939MF

Name: Briel Kobak 
GitHub Handle: bkobak33
Role: UX Researcher 
Slack Member ID: U03QTE177K7

Name: Sarah Chee 
GitHub Handle:  cheesarah
Role: UX Researcher
Slack Member ID: U03SFBUAK26
