### ISSUE TITLE
Make Template from Audited Documents Part 2: determine and make necessary changes

### ISSUE THREAD

**Issue by Jane4925** [hackforla/tdm-calculator#1029]
### Overview
Read through all need-to-be-templated documents, think about possible changes, and edit/comment on changes in the documents.
- Section 3: Pranav
- Section 4: Jill
- Rest sections: Jane

### Action Items

For each document:
- [x] Refer to [Draft][TEMPLATE] documents in audit spreadsheet column H or corresponding section folder
- [x] Read through the document, think about 
  - [x] Contents that can be turned in to template format
  - [ ] Possible changes to make that reflect our current features and cover issues from last test
- [x] If there is anything in the document worth updating
  1. Select the content -> go to "Format" -> hoover over to "Text" -> choose "Strikethrough" -> add your edits following strikethrough text
  2. Select the content -> righthand side choose "Add comment" / right click choose "Comment"
- [x] If edits/comments are made to the document, update audit spreadsheet column J with "Yes", else "No"
- [ ] Review and discuss the edits/comments as a team and make changes

### Resources/Instructions

1. Check [wiki page](https://github.com/hackforla/tdm-calculator/wiki/(Pilot-Page)-Usability-Testing) for descriptions of each document and corresponding section/subsection numbers 
2. Refer to items in [Needs Template Audit](https://docs.google.com/spreadsheets/d/1u0vfSqVFrSuMMAsEvgZNUfIfjNXdzqJ9VurNV1oGpeU/edit#gid=406666523)
3. Ask Jane in the comment/slack if you need help/support/work-along sessions

**Comment by pmeda12** [comment]
I have finished making the templates. Jane, please provide feedback when you can.

**Comment by jarmitageux** [comment]
In Tool Set Up [https://github.com/hackforla/tdm-calculator/wiki/(Pilot-Page)-Usability-Testing] looks like we're considering renewal of Otter.ai for testing transcription. 

Could we look at Dovetail [https://dovetailapp.com/] as alternate tool option? It has been recommended to me for quickly grabbing video clips, voice transcription with in-line theming, etc which could save tons of time and produce assets to show stakeholders. Could we check cost/features compared to Otter.ai tool?

**Comment by jarmitageux** [comment]
@Jane4925 In the research folder, I see the File named Template audit from Q1 activity and the Sheet named Needs Template Audit, but there are no items listed for my section (4). Do you have the previous sheet we reviewed last Saturday with the notes re: reason to update?

**Comment by Jane4925** [comment]
@jarmitageux oops, I checked something yesterday and forgot to change the filter back to "yes". It should work now, reload and see if it is back to normal

**Comment by jarmitageux** [comment]
@Jane4925 Thanks so much! That fixed it.

**Comment by jarmitageux** [comment]
I'd like to discuss file titles. I think the titles used in column C of the template audit spreadsheet are more clear than the current document titles and file names.

**Comment by jarmitageux** [comment]
Recommend updating wiki - Interview Materials, Tools Set Up: Zapier to add: 
Zapier : used to do the automated posting to our slack channel when someone chooses a time in Calendly

**Comment by jarmitageux** [comment]
RE: TDM Calculator Usability Testing Discussion Guide

- How do I get to the Bonus Package page? Image and section needs updating pending page review.
- Made edits primarily attempting to avoid leading questions and jargon.
- Are UXRs supposed to be tracking time to complete tasks? If so, should we add a row for that for each task?
- How are UXRs advised/preferred to enter notes/observations? In rows or columns? To prepare for analysis, it might help to make this clear on the form and in our training.

**Comment by jarmitageux** [comment]
I just reviewed and updated the Testing Discussion Guide (see comment above). I should have time to revisit the UXR Team Lead and Researchers Documentation (rows 31-32) files later tonight. Then I'll move on to the Training Guide.

**Comment by Jane4925** [comment]
> @Jane4925 RE: TDM Calculator Usability Testing Discussion Guide [Draft] [TEMPLATE]
> 
> Ready for your review.
> 
> * How do I get to the Bonus Package page? Image and section needs updating pending page review.
> * Made edits primarily attempting to avoid leading questions and jargon.
> * Are UXRs supposed to be tracking time to complete tasks? If so, should we add a row for that for each task?
> * How are UXRs advised/preferred to enter notes/observations? In rows or columns? To prepare for analysis, it might help to make this clear on the form and in our training.
> * I'm not sure what functions have been changed on the tdm calculator since the last test round. Do you think having interviewees use the site as instructed to enter their projects will reveal issues with new features without specifically identifying them in the testing guide? It seems this might be the case. Please let me know if there are other updates you'd like me to make to the guide, or if we should review together with your knowledge of site iterations.

@jarmitageux 1）You can reference a sample project to get to the Bonus package page. I believe that minor changes are under development, so no worry to update the page now. Instead, just annotate [insert bonus package page image].  2) UXRs should track approximate time that interviewees spend on each page. Adding a row to remind UXRs could be helpful to remind UXRs; make sure that it's clear for UXRs to understand the specific row is only for them but not the interviewees. 3) UXRs should make notes in the column where it said "Note." Feel free to brainstorm better ways for UXRs to enter notes and for us to analyze later on. 4) we will talk to the team about the new features to finalize the guide along the way. This template is more general so other rounds of testing can be modified based on it. Think about where are the questions that can potentially become a placeholder to update questions to revalidate old features and where are the spaces to add questions for new features.

**Comment by Jane4925** [comment]
@pmeda12 I finished reviewing your sections. Could you check my comments and edits inside the docs and try to revise a bit (wording, tone, etc.)?

**Comment by pmeda12** [comment]
> 

Hi Jane, I will look at your comments as soon as I can!

**Comment by jarmitageux** [comment]
FYI - I was looking to see if rows were hidden in this [worksheet](https://docs.google.com/spreadsheets/d/1SEd8uPOwOmEMdsDR_pylZ2tiByopzPrmlqB5Y4Ka4xc/edit#gid=2003118427) and it showed as being an updated version. No changes were made.

**Comment by jarmitageux** [comment]
> > @Jane4925 RE: TDM Calculator Usability Testing Discussion Guide [Draft] [TEMPLATE]
> > Ready for your review.
> > 
> > * How do I get to the Bonus Package page? Image and section needs updating pending page review.
> > * Made edits primarily attempting to avoid leading questions and jargon.
> > * Are UXRs supposed to be tracking time to complete tasks? If so, should we add a row for that for each task?
> > * How are UXRs advised/preferred to enter notes/observations? In rows or columns? To prepare for analysis, it might help to make this clear on the form and in our training.
> > * I'm not sure what functions have been changed on the tdm calculator since the last test round. Do you think having interviewees use the site as instructed to enter their projects will reveal issues with new features without specifically identifying them in the testing guide? It seems this might be the case. Please let me know if there are other updates you'd like me to make to the guide, or if we should review together with your knowledge of site iterations.
> 
> @jarmitageux 1）You can reference a sample project to get to the Bonus package page. I believe that minor changes are under development, so no worry to update the images now. Instead, just annotate [insert bonus package page image]. 2) UXRs should track approximate time that interviewees spend on each page. Adding a row to remind UXRs could be helpful to remind UXRs; make sure that it's clear for UXRs to understand the specific row is only for them but not the interviewees. 3) UXRs should make notes in the column where it said "Note." Feel free to brainstorm better ways for UXRs to enter notes and for us to analyze later on. 4) we will talk to the team about the new features to finalize the guide for second round of testing along the way. This template is more general so other rounds of testing can be modified based on it. Think about where are the questions that can potentially become a placeholder to update questions to revalidate old features and where are the spaces to add questions for new features.

@Jane4925 Thanks for these replies!
1) Done - Bonus Package image placeholder
2) I added time tracking fields/open to other ideas. It would be good to test it to see if it's clear and usable for UXRs.
3) TBD - I looked at the testing [results worksheet](https://docs.google.com/spreadsheets/d/1SEd8uPOwOmEMdsDR_pylZ2tiByopzPrmlqB5Y4Ka4xc/edit#gid=2003118427) from last round to see what analysis we are preparing for and I'm still thinking about what might work well.

**Comment by jarmitageux** [comment]
@Jane4925 RE: TDM Usability Testing - Researchers Documentation [Draft] [TEMPLATE]

Ready for your review.

1. Suggested a new page title.
2. Is tdm-ux slack channel still active, or correct reference, or should it be updated to tdm-calculator?
3. I was confused by the reference to the landing page in instruction 3.c. Does this just refer to the page opened by the link in the worksheet? I want to make sure it's not confused with a landing page for the TDM Calculator site. Does it seem clear?
4. I would recommend adding instructions for the UXR to guide the interviewee through sharing their screen and accessing the sample project etc, but I need help outlining this because I haven't done this on Zoom.
5. Are our current files going to remain the same links for the testing? If so, I'll link them now. Otherwise, the Additional Info links will need updating once all the files are finalized.

**Comment by pmeda12** [comment]
@Jane4925 I have reviewed your comments and replied to a few of them, and accepted the changes that you proposed. Overall, I agree with everything you said.

**Comment by pmeda12** [comment]
@Jane4925 Just finished reviewing the documents assigned to @jarmitageux. I added a few comments / edits where I felt it was needed. Overall, I think Jill did an amazing job with synthesizing information and clarifying instructions in these documents. There were a few parts that I think can be further clarified that I can discuss in our meeting today at 4pm.

**Comment by jarmitageux** [comment]
@Jane4925 RE: TDM Calculator UXR Onboarding [Draft] [TEMPLATE]

Ready for your review. I had several questions about process, redundancies, and ordering that I posted as notes in slides. These might need more work.

**Comment by jarmitageux** [comment]
> @Jane4925 RE: TDM Usability Testing - Researchers Documentation [Draft] [TEMPLATE]
> 
> Ready for your review.
> 
>     1. Suggested a new page title.
> 
>     2. Is tdm-ux slack channel still active, or correct reference, or should it be updated to tdm-calculator?
> 
>     3. I was confused by the reference to the landing page in instruction 3.c. Does this just refer to the page opened by the link in the worksheet? I want to make sure it's not confused with a landing page for the TDM Calculator site. Does it seem clear?
> 
>     4. I would recommend adding instructions for the UXR to guide the interviewee through sharing their screen and accessing the sample project etc, but I need help outlining this because I haven't done this on Zoom.
> 
>     5. Are our current files going to remain the same links for the testing? If so, I'll link them now. Otherwise, the Additional Info links will need updating once all the files are finalized.

Reviewed and updated, added checklists and process phase titles to [UXR Responsibilities](https://docs.google.com/document/d/10ZAF86mN0F0E2K-Q7BY1e4pZ4pVESXitakD0XsSE2XQ/edit#) Also added new content and comments that need review.

**Comment by Jane4925** [comment]
Weekly format for updating issues
1. Progress: finished reviewing Discussion Guide, working on the revising other docs
2. Blockers: need to confirm some details with LADOT and PMs
3. Availability: actively working on it everyday :)
4. ETA: late Jan or early Feb

**Comment by pmeda12** [comment]
UXR Notes from Team meeting:

- Reach out to Pts from previous round of user testing to see if they want to participate in this second round of testing
- Intention is to include a section in qualitative analysis report that describes the unique perspectives of repeat participants. - We can ask what they thought was changed / improved since they last saw it. This may help us learn what changes were most apparent and what may need to be emphasized

**Comment by pmeda12** [comment]
Progress: Reviewed Discussion Guide and Onboarding slide deck
Blockers: need to confirm edit suggestions with Jane (mostly just deleting or moving slides)
Availability: trying to work on it at least a little bit a day!
ETA: Late Jan.

**Comment by jarmitageux** [comment]
@Jane4925 @pmeda12 
Reviewed Discussion Guide. I was afraid to finalize without a record of notes, so I created a new document: [Copy of... [Template]. ](https://docs.google.com/spreadsheets/d/1R0i1zqdsbdOVCGSd54nud0UFhLjOepjuNq-JZi8tb4s/edit#gid=469452671) Hopefully didn't just create a big mess. 
Done: 
- Re-worded from statements to questions to resolve noted cta issues on Introduction tab
- Re-ordered content re: if they're using their project or our sample project to try to simplify flow
- Moved login information to testing section per notes
- Accepted changes: removed striked text and all colored text changed to black
- Fixed cell formatting/merged cells/wrapping
- Resolve time check content
- Entered all Pranav's most recent comments (1/22/22) not already resolved by copy/paste because I forgot to copy the file including comments 
Purple text = newly added, Comments = not yet resolved

To do: 
- Review comments, 
- remove column notes for resolved issues, 
- review new changes (purple text), 
- review and finalize closing tab content

**Comment by Jane4925** [comment]
Progress: 1) Finalizing documentations for UXR team and UXR volunteers 2) Polishing Discussion Guide and Volunteers Training slide deck
Blockers: Havn't finish reviewing improved and new features since user testing 1
Availability: trying to work on it at least a little bit everyday and Sat team meeting
ETA: Late Jan ~ Early Feb

**Comment by jarmitageux** [comment]
I renamed the User Testing Discussion Guide to keep us all editing the same file. Please make all reviews, comments, edits to: TDM Calculator Usability Testing Discussion Guide [TEMPLATE]-Current Active

**Comment by jarmitageux** [comment]
Progress: 90% done finalizing recruitment and testing assets, 75% done finalizing UXR training assets

Blockers: 
- Pending LADOT approval on participant recruitment email content (target date Feb. 7th)
- In progress - formatting participant survey in challenging ArcGIS survey software (target date for LADOT survey approval Feb. 7-12th)
- finalizing TDM Calculator design for this round of testing will prompt final testing assets updates

Availability: daily progress, Sat team meetings

ETA: Start recruitment for UXR volunteers and testing participants by 3rd week Feb, start testing early March

**Comment by Jane4925** [comment]
Action items as of 2/5 meeting:
- [ ] Update your Feb 21-25th 9-5 PST [availability](https://www.when2meet.com/?14440400-K2Llw) to the best you can 
- Jill
   - [ ] Update Discussion Guide according to what we have discussed today
   - [ ] Review recordings from testing 1, focus on and summarize responses for tab 4 profession question
      - [Recording folder](https://drive.google.com/drive/u/0/folders/1FZ5gMMxZbo5K4PZapZ2I3EU0Q4SyBP6j)
- Pranav
   - [ ] Update UXRs Interest Form Template according to what we have discussed today, questions + logos
      - Refer to logos used in this [presentation slide 16](https://docs.google.com/presentation/d/1djX48CJLJtw0ObDLN9cpVhJEIVsN4dplc4pe_wciUQY/edit#slide=id.p14), include HfLA logo for sure (LADOT logo pending discussion)
   - [ ] Update Usability Test Scheduling Email Template to include reminder for people to know they will need a desktop/laptop in order to participate

**Comment by pmeda12** [comment]
Progress: Updated Usability test scheduling email template to include reminder to have laptop/desktop
Blockers: No major blockers
ETA: Will complete HfLA logo for google form survey within next few days

**Comment by Jane4925** [comment]
Progress: 1) Upgraded Zoom account 2) Discussion Guide and Volunteers Training slide deck 95% completed 3) Approved Volunteer recruitment form 
Blockers: 1) Haven't finish reviewing improved and new features since user testing 1 2) Feedback is received from stakeholder, but updates haven't been made yet
Availability: trying to work on it at least a little bit everyday and Sat team meeting
ETA: Aiming 100% Discussion Guide and Volunteers Training slide deck completion this Sat 02/19

**Comment by pmeda12** [comment]
Progress: Finished consolidating last few slides of training slide deck, reviewed stakeholder comments on email templates and survey questions

Blockers: None

Availability: at least a little every day

ETA: Tasks are done, pending further comments from stakeholders (LADOT)

**Comment by jarmitageux** [comment]
@Jane4925 Review of last closing questions from round 1 testing:

Only 2 or 16 participants were asked those last 4 questions. Not asked because the sessions had run long, participant annoyed by too many questions, or tech glitches. 

I didn’t save the answer, but my impression was that the question about concerns in the permitting process could be helpful. 

I’m not sure I know enough about the use case for these answers to know if these are helpful, so here are the answers to the occupation and team questions.

Can you tell me more about your occupation?
1 - Yes, I am a transportation planner. I work for a company called co a and the Culver City Office. And so we do a lot. 
2 - Yes, I work with a transportation consultancy and I assist one of the transportation management organizations go Glendale. So we work with employers and property managers to give our transit information and I also work with some of the other rail projects.

Can you tell me about your team?
1 - So we have a small office, there's about 11 of us. But it's comprised of a designer and you know, planners, engineers. And so planners, yeah, work on transportation studies, you know, parking traffic stuff.
2 - We're three people and our main work is to be in. We're like the bridge between the city and the employers and property managers in Glendale.

**Comment by ExperimentsInHonesty** [comment]
@Jane4925 we met with the stakeholders on 2022-02-22 

There was a question
In 2021, were the majority of your projects in the permit process (check box):
Commercial
Residential
Mixed-use
Institutional
Government
Other

Suggest adding the following questions
Have you ever worked on projects in any of the following categories? (Choose all that apply)
[insert list of all project use cases]

**Comment by pmeda12** [comment]
> @Jane4925 we met with the stakeholders on 2022-02-22
> 
> There was a question In 2021, were the majority of your projects in the permit process (check box): Commercial Residential Mixed-use Institutional Government Other
> 
> Suggest adding the following questions Have you ever worked on projects in any of the following categories? (Choose all that apply) [insert list of all project use cases]

Consider this done.

**Comment by Jane4925** [comment]
Reopen if necessary
