### ISSUE TITLE
Apply Authorization rules to client routes

### ISSUE THREAD

**Issue by KPHowley** [hackforla/tdm-calculator#1033]
A user can edit the URL in his/her browser to navigate to any page.  If they navigate to a page for which they are not granted access, the center area of the page is blank. The desired behavior is that they should be redirected to the login page. Then, if they successfully log in, they should be taken to the page they were trying to navigate to via the original URL.

Here is what this looks like if the user is not logged in and attempts to navigate to the role page (for editing other users' permissions):

![image](https://user-images.githubusercontent.com/9939032/152651419-8fb010e3-3886-4ef9-8277-54e108edc751.png)

Note that no information is exposed, because the Web API server rejects the request to the server for information, so this is not a security problem. Also, there are no menu items or other links in the application that would allow a user to navigate to a page for which they do not have access, but there at least a few ways for them to end up at a restricted URL:

- They can type the restricted URL directly into the browser's address bar, or
- If someone was previously logged in to the application and accessing the restricted page, then logged out, the current browser user could potentially use the browser back button to go navigate backwards in the browser history to navigate to the restricted page.

**Comment by entrotech** [comment]
Made some progress on this this week, but have more to do.

Expected ETC: 1/26/22

**Comment by entrotech** [comment]
I was able to get the protected client route working. However, taking the user directly to the login page might be confusing, so when they attempt to access the restricted page, I take them to a static page that displays some information about what happened, and suggests that they choose another feature in the application or log in with an account that has the requisite privileges.

![image](https://user-images.githubusercontent.com/9939032/152651864-d94beb96-237e-4cac-b1a2-9527f68962f9.png)

Currently, the only restricted page is roles (which requires Security Admin role) and admin (which requires Admin role, but isn't currently used at all).

We should probably discuss this implementation and possibly create a follow-up issue to adjust this implementation as needed.
