### ISSUE TITLE
Figure out and document steps with ArcGIS survey 

### ISSUE THREAD

**Issue by Jane4925** [hackforla/tdm-calculator#1035]
### Overview
Sort and clean our ArcGIS space for second round of usability testing, also document the specific steps for survey creation, distribution, and result exportation.

### Action Items
For Bonnie:
- [x] Leave the tutorial link for ArcGIS in the comment

For Jane:
- [x] Go through the tutorial
- [x] Sort out the actual survey that was distributed in the first round of usability testing 
   - [ ] Hide the private info from being public access in previous survey result
   - [x] Download the raw survey result and import to Shared Drive for possible need for making templates
   - [ ] Try to replicate the analysis for raw survey result and document as much as possible
- [x] Create pilot/template survey on ArcGIS for second round of usability testing and document the steps
   - [x] Organize it in specific folder
   - [x] Make sure the access is able to be shared with public but hiding personal info from data fields

### Resources/Instructions
Link to [ArcGIS survey hub](https://lahubcom.maps.arcgis.com/sharing/rest/oauth2/authorize?client_id=arcgisonline&display=default&response_type=token&state=%7B%22portalUrl%22%3A%22https%3A%2F%2Flahubcom.maps.arcgis.com%22%2C%22returnUrl%22%3A%22https%3A%2F%2Flahubcom.maps.arcgis.com%2Fhome%2Fcontent.html%3Fview%3Dtable%26sortOrder%3Ddesc%26sortField%3Dmodified%26folder%3Dtdmux_lahubcom%23content%22%2C%22useLandingPage%22%3Afalse%2C%22clientId%22%3A%22arcgisonline%22%7D&expiration=20160&locale=en-us&redirect_uri=https%3A%2F%2Flahubcom.maps.arcgis.com%2Fhome%2Faccountswitcher-callback.html&force_login=false&hideCancel=true&showSignupOption=true&canHandleCrossOrgSignIn=true&signuptype=esri&redirectToUserOrgUrl=true)

**Comment by ExperimentsInHonesty** [comment]
Tutorials 

https://learn.arcgis.com/en/paths/access-data-results-from-survey123/
https://www.youtube.com/watch?v=cZ1CH3p8Nmo
https://learn.arcgis.com/en/paths/take-your-surveys-further/

**Comment by Jane4925** [comment]
Weekly format for updating issues  
    1. Progress: Found the old survey from user testing 1, created the new survey for user testing 2
    2. Blockers: still learning how to hide some fields in the survey 
    3. Availability: working on it actively
    4. ETA: ~1/25? before stakeholder meeting OR 1/29

**Comment by Jane4925** [comment]
Progress: Went through the flow of the survey for user testing 2, testing if private field hiding is working
Blockers: Waiting for feedbacks about survey question from stakeholders to revise
Availability: 1 or 2 hrs per week 
ETA: ~1/29 to 2/2 if testing goes well

**Comment by Jane4925** [comment]
Progress: Editing survey for user testing2 and Documenting steps 
Blockers: Waiting for feedback from stakeholders on a couple docs (still coming in...) and final approval  
Availability: trying to work on it at least a little bit a day!
ETA: stakeholder meeting on 02/22, which will decide the final approval

**Comment by Jane4925** [comment]
Progress: implement feedback from stakeholder for survey questions 
Blockers: not really...expect for my procrastination lol 
Availability: trying to work on it at least a little bit a day!
ETA: stakeholder meeting on 02/22, which will decide on final approval
