### ISSUE TITLE
Implement new accordion design replacing tooltips on calculation/2 and calculation/5

### ISSUE THREAD

**Issue by KPHowley** [hackforla/tdm-calculator#1036]
### Overview
The information displayed through tool tips currently on calculation /2 and /5 will now be displayed via accordion drop downs. we need to implement this new design and make some related changes 

### Action 

- [x] replace tool tips on calculation/2 with accordions
- [x] replace tool tips on calculation/5 with accordions
- [x] #1046
- [x] replace highlighting on clickable lines with bold text and underlines on words 
- [x] remove box notifying users about tool tips at the top of calculation/5
- [x] make accordion default to stay open until the "x" in the corner is clicked. Clicking on the words should also close the container. 
- [x] Review changes with UI team 

### Resources/Instructions

<img width="789" alt="146294117-1eb29af7-c629-4b5a-bea7-0e1172b99949" src="https://user-images.githubusercontent.com/49739276/147179537-b4a6f5bc-5b7e-4c5b-8b07-19a06fa0e577.png">

Prototype Link: https://www.figma.com/proto/nD9QK56Mzq7xNSaSUoeGx0/TDM-Calculator?node-id=4961%3A17[…]width&page-id=4107%3A13052&starting-point-node-id=4898%3A17350

Figma ToolTip Page Link: https://www.figma.com/file/nD9QK56Mzq7xNSaSUoeGx0/TDM-Calculator?node-id=4898%3A17350

**Comment by jahpe777** [comment]
@KPHowley it seems that calculation/4 is actually calculation/5.

Also, for "remove box notifying users about tool tips at the top of calcualtion/4", shouldn't we keep the box for the tooltips within the sidebar?

**Comment by KPHowley** [comment]
@jahpe777 - yes it is calculation/5 which is page 4/5!

we should continue with removing the box as we found it was not actually adding to the user experience in testing, and not clarifying tooltips in the way we intended.

**Comment by ExperimentsInHonesty** [comment]
@jahpe777 Please provide update
1. Progress
2. Blockers
3. Availability
4. ETA

**Comment by jahpe777** [comment]
@KPHowley @ExperimentsInHonesty 

1. Working on clickable event for new "tooltips"
2. Currently stuck on assigning ID to each tooltip
3. Low availability
4. Few more weeks

**Comment by jahpe777** [comment]
Finalized accordion "tooltips" 
Pending review from UI team

**Comment by KPHowley** [comment]
@jahpe777  - if you will be able to make it tonight we can review this on your local before we accept the pull requset

**Comment by jahpe777** [comment]
Updated accordion descriptions widths to be compatible with Safari and Firefox browsers.

**Comment by seenaiype** [comment]
Reviewed with LADOT - 02/08

- [ ] for Bike share row remove the blue highlight
- [ ] For the accordion for bike share, add the links to the correct page (bike share location and bike share map)
- [ ] For external links add the icon that shows its going to an external website (https://fontawesome.com/v5/icons/external-link-alt?s=solid)
- [ ] For the AIN/APN accordion, move the external link to the accordion - Text that could be used for AIN/APN - Los Angeles County Assessor Property Assessment Information System
