### ISSUE TITLE
Review Timeline Slidedeck and update Design

### ISSUE THREAD

**Issue by KPHowley** [hackforla/tdm-calculator#1041]
### Overview
We need to do a design review of our timeline, to make sure it is in line with our design standards, and able to be shared to the public. 

### Action Items

- [ ] Review Slide deck and and update design  
- [ ] Create re usable slide for Presentations that can be updated to show where currently are on the timeline
- [ ] Create Timeline image/document that can be used online on our websites and shared publicly. 

### Resources/Instructions
- [TDM Timeline Slides](https://docs.google.com/presentation/d/1Co35UxoPZkD6W26tdB5MK47otd22Bcjs/edit?usp=sharing&ouid=117075938410621694782&rtpof=true&sd=true)

**Comment by ExperimentsInHonesty** [comment]
We decided not to keep this up, we just use a google sheet
