### ISSUE TITLE
Design for exemptions

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/tdm-calculator#1042]
### Overview
We need to have a link on the site for people whose project is exempt for them to self assess.

### Action Items
- [ ] Mock up various locations for "Your project may be except from TDM regulations" or some other text

### Resources/Instructions
See exceptions section 3: https://planning.lacity.org/odocument/1dc924ce-b94a-403b-afe0-17ba33b3dbe1/Draft_TDM_Ordinance.pdf

**Comment by KPHowley** [comment]
This is potentially addressed in #875  - will discuss at stakeholder meetinng

**Comment by ExperimentsInHonesty** [comment]
At stakeholder meeting, David agreed with us putting the following

Check LAMC Section 12.26 J.3(b)(3) of the Draft Revised TDM Ordinance

**Comment by KPHowley** [comment]
@Shaeeka   - this is going to be an update to the checklist design.  #875
