### ISSUE TITLE
Recruit new Developers

### ISSUE THREAD

**Issue by KPHowley** [hackforla/tdm-calculator#1043]
### Overview

We need to recruit new developers at the next on boarding session. 

### Action Items

- [x] Put post for new front and back end developers on opening board
- [x]  Save post for future use 

### Resources/Instructions

**Comment by ExperimentsInHonesty** [comment]
Current post for front end

![image](https://user-images.githubusercontent.com/37763229/161393864-7a6de0b4-afb7-4bb2-8c30-31fb836cd9ff.png)

**Project Name**: TDM calculator

**Volunteer Opportunity**: Front End Developer
We are finalizing our website for launch and are looking for front end developers to work through final tasks and iterate on feedback before public launch (Oct 2023). 

Our Tech stack includes: 
Languages: JavaScript, TSQL, SCSS, HTML, Shell, CSS, Dockerfile.
Technologies: React, Express, Node.js, Microsoft SQL Server, Docker, Azure App Service, Figma

**Duration**: 6-7 months 

**Meeting times**: Wednesday 7pm PST

**Who to communicate your interest to**
- Slack channel link: [#tdm-calculator](https://hackforla.slack.com/archives/CKY65G266)
- Slack name of person to contact in the channel - Ebi, Moji or John Darragh

**Resources:**
[Learn more about TDM Calculator](https://www.hackforla.org/projects/tdm-calculator)
[Dev Portal](https://tdmdev.azurewebsites.net/calculation/1)


```
![image](https://user-images.githubusercontent.com/37763229/161393864-7a6de0b4-afb7-4bb2-8c30-31fb836cd9ff.png)

**Project Name**: TDM calculator

**Volunteer Opportunity**: Front End Developer
We are finalizing our website for launch and are looking for front end developers to work through final tasks and iterate on feedback before public launch (Oct 2023). 

Our Tech stack includes: 
Languages: JavaScript, TSQL, SCSS, HTML, Shell, CSS, Dockerfile.
Technologies: React, Express, Node.js, Microsoft SQL Server, Docker, Azure App Service, Figma

**Duration**: 6-7 months 

**Meeting times**: Wednesday 7pm PST

**Who to communicate your interest to**
- Slack channel link: [#tdm-calculator](https://hackforla.slack.com/archives/CKY65G266)
- Slack name of person to contact in the channel - Ebi, Moji or John Darragh

**Resources:**
[Learn more about TDM Calculator](https://www.hackforla.org/projects/tdm-calculator)
[Dev Portal](https://tdmdev.azurewebsites.net/calculation/1)

```
