### ISSUE TITLE
Relabel 'TDM MEASURES SELECTED' to 'TDM STRATEGIES SELECTED' in the menu cart

### ISSUE THREAD

**Issue by Dsomers74** [hackforla/tdm-calculator#1050]
### Overview
TDM Strategies are the consistent term we use in all of our program guidance. Should use consistent terms for program legibility. 

### Action Items
Relabel 'TDM MEASURES SELECTED' to 'TDM STRATEGIES SELECTED' in the menu cart

### Resources/Instructions
<img width="378" alt="Screen Shot" src="https://user-images.githubusercontent.com/31966100/151082186-dfde8a60-08c5-47f8-8b60-73d732fbb008.png">

**Comment by jahpe777** [comment]
Noticed that it also shows "TDM MEASURES SELECTED" on the project summary page. Went ahead and updated this as well. 
![Screen Shot 2022-02-01 at 12 59 31 PM](https://user-images.githubusercontent.com/40730303/152050960-a73b7dce-f1e4-4dc7-a04a-d327a1d83554.png)

 #1050
