### ISSUE TITLE
Line space reduced for some rows after the accordion-style tooltips were implemented

### ISSUE THREAD

**Issue by seenaiype** [hackforla/tdm-calculator#1060]
### Overview
With the introduction of the accordion, some of the line gaps have changed. 

### Action Items
- [x] Fix the line gap inside the Bicycle Facilities section
- [x] Fix the line gap inside the Car Sharing section
- [x] Confirm if there is any other section that has this issues

### Resources/Instructions
![image](https://user-images.githubusercontent.com/20568596/152275917-8d5f9d7b-f543-42eb-a90e-42a578a77a4f.png)

**Comment by Adityakr123** [comment]
hi ma'am actually I am new to open source contributions please tell me where is the location of this file I can't find it .
one more thing maam do we need to reduce the gap between bike share station and bike share membership .
And similar for all?

**Comment by seenaiype** [comment]
Also, you can enroll onto their on-boarding sessions happens biweekly.

https://www.meetup.com/hackforla/events/pxkmhsydcdbtb/
