### ISSUE TITLE
Cursor Effect Design - Ease of Access

### ISSUE THREAD

**Issue by dposada90** [hackforla/tdm-calculator#1061]
### Overview
We need to be able to tell when the cursor is hovering over a live link, field, or white space by designing appropriate hover effects.

### Action Items

- [ ] Define UX of hover effects for various UI elements with test cases
- [ ] Develop CSS for requisite hover effects in DEV & promote to TEST (if applicable)
- [ ] Test effects in TEST environment and promote (if applicable)
- [ ] Review effects in PRE environment and promote to PROD (or propose for PROD) 

### Resources/Instructions
[Cursor Hover Accessibility Resource](https://www.ibm.com/able/toolkit/design/ux/pointer/)

**Comment by entrotech** [comment]
Part of Issue #1223 ?

**Comment by Biuwa** [comment]
> Part of Issue #1223 ?

Yes @entrotech

**Comment by ExperimentsInHonesty** [comment]
outdated
