### ISSUE TITLE
User Testing 2: Determine how sample projects should be assigned to testing participants

### ISSUE THREAD

**Issue by Jane4925** [hackforla/tdm-calculator#1065]
### Overview
Determine how sample projects are assigned to testing participants

### Action Items
- [x] Confirm how it worked for user testing 1 with @KPHowley 
   - [x] How project types are labeled and grouped?
      - The confusion is that, we have 5 user groups being labeled by numbers, but we then have 6 project types being grouped into project type A-E and test case 1-5.
   - [x] Was the sample project randomly assigned to each participant?
- [x] Ask LADOT/LACP's opinion/suggestion on assignment
   - [x] Is fine to randomly assign?
   - [x] Will it be better to first assign the sample project based off the participants' responses from user survey questions?
      - Then randomly assign for participant who has no responses for those questions
   - [x] Any other suggestions?

### Resources/Instructions
- [User groups and buckets](https://docs.google.com/document/d/13ct5rS3FsQQpMBQ_minqDklFLcXCWffGlZ2XePKe3c8/edit)
- [User survey response from testing 1](https://docs.google.com/spreadsheets/d/1V-TczYvrI6dBqcrJXCn3rOqKPJ56eCsQrALZmXtN-30/edit#gid=0)
- [Session table from testing 1: look at their user group and project type](https://docs.google.com/spreadsheets/d/12gRid6DQ_7fK5-sNUM2L7L5mY4wYC52Pi70A60eDqVI/edit)
- [Discussion guide from testing 1: look at project info tab](https://docs.google.com/spreadsheets/d/1kndkqEZsFldaV0sNWyHwO3cgnUnX2XYjGX5V8OtrXww/edit#gid=1705581645)

**Comment by KPHowley** [comment]
@Jane4925 - I'm fairly certain we took into account the survey information when assigning sample projects,primarily to give more complicated sample projects to users who would have more understanding of them. 

 As for naming I feel we can adjust to whatever naming makes most sense to you, but varying whether we use letters or numbers would be ideal in my opinion to avoid confusion.

**Comment by Jane4925** [comment]
Will stay the same method of assignment as user testing 1 for user testing 2. But we do need a new issue to sort out if there are 2 sample projects for each type...
