### ISSUE TITLE
Implement Bonus Package information to accordians on Calculation/4

### ISSUE THREAD

**Issue by KPHowley** [hackforla/tdm-calculator#1071]
### Overview

We have a new design for showing the bonus package information on the site that we will need to implement.  Dependency to issue #1137  

### Action Items

- [x] Eliminate conditional page /4 for users qualifying for bonus packages
- [x] add bonus package information as tool tips to the bonus package section
- [x] rename bonus package sections and information to match design
- [x] change color of header on bonus package to match design
- [x] add box to top of Page /4 with "you qualify for bonus package to earn 1 extra point"
- [x] Make only one bonus point awarded even when both packages are checked. 
- [x] Review changes with UI/UX
- [ ] revise wording on the bonus package tooltip to say:
 'Small development projects (Program Level 1) are eligible for one or more TDM packages that allow the fulfillment of the minimum 15-point target. A bonus point is awarded for a package that is made up of strategies that work together to reinforce their effectiveness in reducing drive-alone trips.
Bonus Packages may not be ideal for all projects but are a way to provide easy compliance and implementation for small projects'.

### Resources/Instructions

[Prototype Figma Link](https://www.figma.com/proto/nD9QK56Mzq7xNSaSUoeGx0/TDM-Calculator?page-id=5293%3A18692&node-id=5444%3A19449&viewport=241%2C48%2C0.25&scaling=min-zoom&starting-point-node-id=5444%3A19449&show-proto-sidebar=1)
![image](https://user-images.githubusercontent.com/88021166/150646752-82436262-9f48-4562-a835-156f5b0524de.png)
![image](https://user-images.githubusercontent.com/88021166/150646776-90af5d88-8813-4d5a-9cd4-27abf35cf650.png)
![image](https://user-images.githubusercontent.com/88021166/150646807-43b15f6f-2866-4532-96a4-b3753388b80d.png)
![image](https://user-images.githubusercontent.com/88021166/150646822-be2573e8-e12a-42fa-b466-816a1cb156e8.png)

**Comment by Shaeeka** [comment]
Sharing the [figma link](https://www.figma.com/file/nD9QK56Mzq7xNSaSUoeGx0/TDM-Calculator?node-id=5516%3A19574) of the design

**Comment by entrotech** [comment]
Here is what the following PR implements:

Residential Only, Project Level 1:
![image](https://user-images.githubusercontent.com/9939032/158706461-293eccad-aa98-446a-92cd-156409f5c3e5.png)

Same project, accordion expanded:
![image](https://user-images.githubusercontent.com/9939032/158706404-745e2940-cafd-439d-94cf-c6ed90069126.png)

School Only, Project Level 1:
![image](https://user-images.githubusercontent.com/9939032/158706626-450c9db6-a4a7-4d6f-82ed-8fa9f72bb96d.png)

Same project, accordion expanded:
![image](https://user-images.githubusercontent.com/9939032/158706704-400260b2-cfc0-41a0-b671-2bdc958c18dc.png)

School + Residential:
![image](https://user-images.githubusercontent.com/9939032/158706789-6c619170-71e9-4e60-a647-d91135862173.png)

School + Residential, both tooltips expanded (Zoomed out to show relevant content):
![image](https://user-images.githubusercontent.com/9939032/158706932-e04b2ad7-dc32-4171-a679-c2e465a1f300.png)

School + Residential, Project Level 2 - no Package info shown:
![image](https://user-images.githubusercontent.com/9939032/158707061-85efaef4-8fd8-4344-9b61-b2d416a5b974.png)

**Comment by Shaeeka** [comment]
@entrotech just noticed that the text is not centered within the frame, the spacing is uneven. 

![image](https://user-images.githubusercontent.com/88021166/158754753-d926e6cb-a9c9-459a-b379-414644e1c931.png)

**Comment by entrotech** [comment]
Made adjustments:

- Fixed vertical spacing within tooltipr @Shaeeka comment above.
- Per comments in last night's meeting, modified border of Package message box on strategies page to have no border, just a drop shadow around where border would be.
- Added drop shadow to text within same message box to make it look like message box on the Summary Page.

**Comment by KPHowley** [comment]
reviewing wording on:

"
There are many TDM strategies choices and most involve making long-term commitments in meeting program compliance. Small development projects (defined as Program Level 1 that provide no more than the parking baseline), are provided one or more TDM packages that allow fulfillment of the minimum 15 point target from a pre-selected menu. A point incentive is provided for the packages made up of strategies that work together to reinforce their effectiveness in reducing drive-alone trips. Each strategy selected on its own does not result in the required minimum point target but several selected together will. Each package can be unselected and individual strategies that will work best to both achieve the TDM program goal and your specific development objectives should be chosen.
"

**Comment by KPHowley** [comment]
![Screen Shot 2022-03-19 at 10 21 01 AM](https://user-images.githubusercontent.com/49739276/159131534-29403566-ac98-4142-9048-e83d6e55cbc0.png)

**Comment by Biuwa** [comment]
Reviewed wording:

'Small development projects (Program Level 1) are eligible for one or more TDM packages that allow the fulfillment of the minimum 15-point target. A bonus point is awarded for a package that is made up of strategies that work together to reinforce their effectiveness in reducing drive-alone trips. 

Bonus Packages may not be ideal for all projects but are a way to provide easy compliance and implementation for small projects.'

**Comment by KPHowley** [comment]
This needs to either be updated with the revised wording as a es action item and reopened, or we need to create a separate issue from this.

**Comment by KPHowley** [comment]
@Biuwa and @SMR9220  - Can you guys just update this issue as well?

Thanks
