### ISSUE TITLE
Delete "Select strategies to earn TDM points" and ? icon from calculation/4

### ISSUE THREAD

**Issue by KPHowley** [hackforla/tdm-calculator#1073]
### Overview

This message at the top of calculation/4 is no longer needed or applicable and needs to be removed. 

### Action Items

- [x] remove text from top (This Action removed later - See comment by JD on 4/12/22)
- [x] remove ? from top

**Comment by KPHowley** [comment]
This was closed and addressed when implementing the new accordians.

**Comment by seenaiype** [comment]
@entrotech , as discussed, lets confirm if this issue is completed.. if not, lets re-open this one

**Comment by KPHowley** [comment]
@entrotech  - We actually want to roll this back. I closed this because James had addressed this, however the title is actually incorrect: 
We want to keep "Select strategies to earn TDM points" and just delete the ? icon from calculation/5

I believe this change was just to the sub header, Select strategies to earn TDM points and we want to add that back in, but make sure it is properly spaced along with the new bonus package info

**Comment by entrotech** [comment]
Kevin did not really want the subtitle text removed from the page, so I put it back.
