### ISSUE TITLE
User Testing 2 Overview (edits continue)

### ISSUE THREAD

**Issue by Jane4925** [hackforla/tdm-calculator#1084]
### Overview
Steps, timelines (ideal setting, subject to change), materials, and documentation for user testing round 2 recruitment. 

### Action Items
- [x] 1 - Prerequisites
  - [ ] Test Plan
  - [x] Tools
- [x] 2 - Preparation
  - [x] User Survey #1035 
  - [x] Session Table
- [x] 3 - Recruitment #1089 
  - [x] Participants
  - [ ] UXR volunteers
- [x] 4- Interview Logistics
  - [x] Discussion Guide
  - [x] Instruction Pages
- [x] 5 - Results #1150 
- [ ] 6 - Additional Resources
- [ ] Documentation

### Resources/Instructions
- [Template folder ](https://drive.google.com/drive/folders/1cANLImaVwMcOosJvwc1cGKrB5gJaxs7N?usp=sharing)

**Comment by pmeda12** [comment]
Tasks Completed: Update C.U.T Guide (Usability testing guide for volunteers), Create contact spreadsheet for training session attendees (in the fourth template folder), Update presenter notes to detail individual duties. See below for more details.

Training deck: https://docs.google.com/presentation/d/1VUTxh5eR0PHUAhaU8ZgNlsnrj_qmaBXcv9IUmfR0aTs/edit#slide=id.gd5a5cac577_0_0 

Slide 20:
- Include instructions for Jill to show her Zoom background 

Slide 21:
- Describe who will be answering questions on EasyRetro and who will be numbering questions and answers (subject to change)
- Sample question to use during EasyRetro demonstration

Slide 47: 
- Include instruction to allow trainees to leave the Zoom early if desired

**Comment by Jane4925** [comment]
Progress: making journey map and starting documentation
Blockers: n/a
Availability: try to work on it for a bit everyday 
ETA: 5/21 or 5/25

**Comment by ExperimentsInHonesty** [comment]
@Jane4925 
Please provide update
1. Progress: "What is the current status of your project? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"
5. Pictures (if necessary): "Add any pictures that will help illustrate what you are working on."

**Comment by mojimoh** [comment]
@Jane4925, Please provide update by Wednesday
1. Progress: "What is the current status of your project? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"
5. Pictures (if necessary): "Add any pictures that will help illustrate what you are working on."

**Comment by Jane4925** [comment]
1. Progress: Slowly picking it back up 
2. Blockers: Available Time
3. Availability: hopefully at least2hrs
4. ETA: End of Feb

**Comment by mojimoh** [comment]
Please provide update
1. Progress: "What is the current status of your project? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"
5. Pictures (if necessary): "Add any pictures that will help illustrate what you are working on."

**Comment by mojimoh** [comment]
@Jane4925 @pmeda12 
Please provide update
1. Progress: "What is the current status of your project? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"
5. Pictures (if necessary): "Add any pictures that will help illustrate what you are working on."

**Comment by Jane4925** [comment]
Progress: restructure wiki page for documentation 
Blockers: wiki page is getting long 
Availability: 4-6 hrs this week
ETA: end of March or mid April

**Comment by Biuwa** [comment]
@Jane4925 Please provide an update. Is mid-April still attainable?

Progress: "What is the current status of your project? What have you completed and what is left to do?"
Blockers: "Difficulties or errors encountered."
Availability: "How much time will you have this week to work on this issue?"
ETA: "When do you expect this issue to be completed?"
Pictures (if necessary): "Add any pictures that will help illustrate what you are working on.

**Comment by Biuwa** [comment]
@Jane4925 Please provide an update. we are way past 'your ETA'

Progress: "What is the current status of your project? What have you completed and what is left to do?"
Blockers: "Difficulties or errors encountered."
Availability: "How much time will you have this week to work on this issue?"
ETA: "When do you expect this issue to be completed?"
Pictures (if necessary): "Add any pictures that will help illustrate what you are working on.

**Comment by Jane4925** [comment]
@Biuwa I will be working on this issue with Abby and Melissa as they are both co-leads on the team. I will also discuss granting them the edit access to wiki page when meeting with Bonnie.
