### ISSUE TITLE
User Testing 2: Recruitment

### ISSUE THREAD

**Issue by Jane4925** [hackforla/tdm-calculator#1089]
### Overview
Steps and materials needed for user testing round 2. 

### Action Items
- [ ] 3 - Recruitment
  - [ ] Participants
    - [x] Outreach Email
      - [x] Phase 1 : [March 16 - 22] within contacts provided by LADOT
         - [x] MailChimp Settings
            - [x] Import round2 contact sheet
            - [x] LADOT title and signature
            - [x] LADOT email domain verification
          - [x] Sent on March 16th: [TDM Calculator Usability Testing Round 2 Outreach Email](https://us1.admin.mailchimp.com/campaigns/edit?id=8802685)
      - [ ] Phase 2: [April ?] outside of LADOT's provided contacts - PENDING APPROVAL 
        - [ ] Double check with LADOT if it is alright in stakeholder meeting
        - [ ] Draft outreach message (refer to [paragraph](https://github.com/hackforla/tdm-calculator/issues/888#issuecomment-1073051837) here)
    - [x] Interview Invitation: sent on March 22nd 
    - [x] Interview Scheduling: plan to start on March 24th
  - [x] UXR volunteers (PENDING)
    - [x] Interest Form
    - [ ] Training Invitation
      - [ ] **FOR BONNIE**: spread the word on Slack (PENDING as of the week of 03/21)
        - [ ] :sunglasses: We need UX researchers to conduct usability interviews for the TDM Calculator Project :fire: Sign up today for our upcoming training sessions here: https://forms.gle/bsRkNzEYEcvLSpLe6  :car::dash: 
  
### Resources/Instructions
- [MailChimp test email](https://github.com/hackforla/tdm-calculator/issues/1089#issuecomment-1068286923)
- [Participant recruitment phase 1 status](https://github.com/hackforla/tdm-calculator/issues/1089#issuecomment-1073556148)

**Comment by Jane4925** [comment]
<img width="1745" alt="Screen Shot 2022-03-15 at 10 48 50 AM" src="https://user-images.githubusercontent.com/64346009/158441653-669de324-ed41-4710-8770-9ee644a55ae3.png">
<img width="1640" alt="Screen Shot 2022-03-15 at 10 49 26 AM" src="https://user-images.githubusercontent.com/64346009/158441665-bf358fe0-47f6-4735-bf56-e3acdef6d6ff.png">

**Comment by ExperimentsInHonesty** [comment]
@Dsomers74 let us know if this text is ok?

**Comment by Jane4925** [comment]
Participant recruitment phase 1 status as of 03/21/2022:
- According to MailChimp report - 88 opened the email, 21 clicked the links inside email
- Responses from user survey - 8 submitted, 7 expressed interest in doing interview

**Comment by KPHowley** [comment]
@Jane4925 - would love an update on this to see if we are closing or keep working on it @jarmitageux @pmeda12

**Comment by Jane4925** [comment]
reopen/refer to later if recruitment phase 2 is decided
