### ISSUE TITLE
Add TDM Strategies Packages

### ISSUE THREAD

**Issue by entrotech** [hackforla/tdm-calculator#109]
May be better to enter rule as a Package Bonus where they earn bonus points for implementing certain combinations of other strategies, like we do for the bike bonus? This is instead of somehow disabling the component strategies when a package is chosen.

**Comment by entrotech** [comment]
Need to confirm with Rosemary that the implementation works for her.  Each package only adds one point above what the individual startegies would count.

**Comment by nicholaspung** [comment]
Line 18 of [rosemary requirements](https://drive.google.com/open?id=1F03uD-yk9aPuKoc6YuRyCI_kvZRCORwn)

**Comment by ExperimentsInHonesty** [comment]
Closed without pull request because it was a database change.  Change made by @entrotech
