### ISSUE TITLE
Threshold Changes

### ISSUE THREAD

**Issue by awikstrom-ladot** [hackforla/tdm-calculator#1096]
@KPHowley @entrotech @Dsomers74 

Hi all,
I'm submitting the following threshold changes for the calculator:

- Increase residential threshold in Level 1 from 16 units to 25 units
- Increase threshold for 100% Affordable Housing projects in Level 1 from 16 units to 50 units (i.e. 100% affordable projects of 49 or fewer units no longer need to follow TDM)
- Decrease hotel/motel threshold in Level 1 from 50 rooms to 25 rooms
- Add warehouse and industrial thresholds for level 1 (25k sf to under 100k sf) and level 2 (100k sf to under 250k sf)

Let me know if you have any questions

**Comment by KPHowley** [comment]
@awikstrom-ladot @Dsomers74  - Is there a document of this chart we can have for our reference.
