### ISSUE TITLE
TDM Strategy Changes

### ISSUE THREAD

**Issue by awikstrom-ladot** [hackforla/tdm-calculator#1097]
@entrotech @KPHowley @Dsomers74 

Here are some changes to make to the following TDM Strategies

- Bike Share Memberships will not use Gold/Silver/Bronze ranking, and instead will earn applicants 5 points.
- Access Improvement: Applicants can earn 4 points if, at minimum, the project provides access to an adjacent bike path or multiuse path
- Reduced Parking Supply: Assign point values to the following scheme: 
2 Points - reduces 10% - 24% of the parking spaces available relative to the parking baseline.
4 Points - reduces 25%-49% of the parking spaces available relative to the parking baseline.
8 Points - reduces 50%-89% of the parking spaces available relative to the parking baseline.
12 Points - reduces 90%-100% of the parking spaces available relative to the parking baseline. 
- Retitle Shared Mobility: Existing Provider to Shared Mobility: Service Membership

**Comment by entrotech** [comment]
@awikstrom-ladot @Dsomers74 @KPHowley
