### ISSUE TITLE
Create Agenda July 30 2019

### ISSUE THREAD

**Issue by Rankazze** [hackforla/tdm-calculator#11]
### Overview
Gather all items team members want to propose for this weeks' agenda.

### Action Items
Add comment to this issue with your proposed agenda item. if item warrants an issue of its own please start a [new issue](https://github.com/hackforla/tdm-calculator/issues)

**Comment by Rankazze** [comment]
![Capture](https://user-images.githubusercontent.com/50686892/61925677-3554a780-af22-11e9-8294-5edd861dad78.PNG)
Finalize list of questions for Rosemary in a google sheet

**Comment by KPHowley** [comment]
My suggestions for tonight's agenda: 
- Quickly identify the issues we want to prioritize
- Finalize roles for members
- Make subgroups if necessary 
- Have each member take an issue, and make sure we're all on the same page about it.
