### ISSUE TITLE
Add Saving Function

### ISSUE THREAD

**Issue by entrotech** [hackforla/tdm-calculator#111]
### Overview
Allow a user to save a calculation.
Though we could allow users to save a calculation to a file or something, it would be better if users could register and login, then save calculations with a project name, address, maybe a version number and a calculation name (in case they want to save different ways of satisfying the requirements, etc.)

### Dependancies
#71 
#45 
#44

**Comment by ExperimentsInHonesty** [comment]
Line 20 of [rosemary requirements ](https://drive.google.com/open?id=1F03uD-yk9aPuKoc6YuRyCI_kvZRCORwn)

Closed by pull request made by John
