### ISSUE TITLE
Update Strategies per January 2022 Program Guidelines

### ISSUE THREAD

**Issue by entrotech** [hackforla/tdm-calculator#1115]
### Overview
LADOT has been revising the TDM Program Guidelines. Upon reviewing this document, here is a list of the differences between the strategy descriptions in the document vs. what's currently implemented in the application. Assuming the TDM Program Guidelines are the definitive requirement, we need to update the TDM strategy implementation to agree with the document referenced below. 

Need to start by reviewing the list below before implementing the changes. We should also come up with a way of communicating changes to the document to the development team for implementation in the application in the future.

In the document, there are several notes in the descriptions that are designated with asterisks, but we use that in the application to denote required fields - for now, I translated these by enclosing such comment in square brackets, but we need to decide how to represent them.  **Questions for LADOT about implementation are in ALL CAPS.**

### Action Items
**Modify the tooltip text for Bike Share Memberships to:**
Offer bike share membership passes to employees and/or residents in accordance with available pass options(applicable for locations within 0.25 miles from an existing or planned bike share station - <a href="https://bikeshare.metro.net/stations/">Bike Share Location Map</a>).

[LADOT shall pre-approve the selection of this TDM Strategy to verify that the project is within an eligible location.]

**Change Car Share Membership tooltip to:**
Offer an annual car share membership, not including trip fees (through a third-party car share service operator) for at least 50% of residents or employees (applicable for locations within 0.25 miles of an existing service area). If the applicant selects [BlueLA]() as the provider, the TDM point total from this measure is 4 points. 

[LADOT shall pre-approve the partnership. Eligible projects must be located within 0.25 miles of existing [BlueLA ]()vehicle spaces.]

**Change tooltip for Private Car Share Fleet to:**
Provide a car share fleet available to all building occupants. Minimum of 2 cars per project site.

**Change tooltip for Electric Vehicle Bonus to:**
Provide 100% electric vehicle fleet or membership to electric vehicle car share program for a bonus point.

**Move Electric Vehicle Bonus after Car Sharing bonus,** since the Electric Vehicle Bonus does not count toward the Car  Sharing bonus.

**Change Guaranteed Return Trip Strategy tooltip to:**
Provide at least six monthly taxi or Transportation Network Companies (TNC) fare vouchers or reimbursements for at least 50% of employees who travel by non-drive alone trips.

**Change HOV tooltip to:**
Provide free, reserved HOV parking spaces (carpool, vanpool, etc.). Should be closer to the building entrance than other non-HOV parking spaces (excluding ADA stalls). Minimum 2 parking spaces.

**Change Mandatory Trip Reduction Program tooltip to:**
Deploy an employee-focused travel behavior change program that targets individual attitudes, goals, and travel behaviors, educating participants on the impacts of travel choices and opportunities to alter their habits. The program typically includes a coordinated ride-sharing, vanpool and/or carpooling program, requires a program coordinator, and includes program monitoring, reporting and evaluation. A minimum of 50% of all employees on site should be eligible for the trip reduction program. May not be combined with (Information 3 or 4). 

**Change tooltip for the Encouragement Program "Education, Marketing and Outreach Program to:**
Offer new employees and residents a packet of materials and/or provide personal consultation detailing sustainable (non-drive alone) travel options. These materials or consultations must be available on an ongoing basis and/or on permanent online channels. Packet must include the distribution of one Metro TAP card preloaded with a day pass or equivalent value, to each employee or residential unit. 

**Change the tooltip for the Encouragement Program "Voluntary Travel Behavior Change Program" to:**
A multi-faceted program involving two-way communication campaigns and travel feedback that actively engages participants to target individual attitudes, goals, and travel behaviors to alter their travel choices and habits. Program must include the distribution of one Metro TAP card preloaded with a day pass or equivalent value, to each employee or residential unit. Selection of this strategy requires a coordinator to manage the program, and ensure communication is available to all regular occupants of a site with a special focus on new occupants and/or employees. Must include participation from 20% of the project site’s tenants/users to qualify for this TDM strategy. This strategy pairs well with a TMO.

**Change the Mixed-Use tooltip to:**
Projects that are mixed-use and provide no more than 85% of floor area for a single land use.

**Change the Mobility Management tooltip to:**
Funds capital expansion, operations, and maintenance for existing sustainable mobility programs (Metro Bike Share, carshare, etc.). 

**Change Pricing and Unbundling Parking tooltip to:**
Pricing of parking encourages sustainable modes of travel (non-drive alone) and can be accomplished in several ways. Property managers and homeowner associations can unbundle the price of parking from rents or sale of units.  The parking cost is set by the project applicant and paid by the vehicle owners/drivers

**Change the Reduced Parking Supply tooltip to (THE APPLICATION DOES NOT HAVE A GLOSSARY):** 
Reduction in parking supply below the generalized citywide parking baseline (See Glossary), using parking reduction mechanisms, including, but not limited to, TOC, Density Bonus, Bicycle Parking ordinance, locating in an Enterprise Zone or Specific Plan area, or compliance with zoning regulations that require less parking than the generalized citywide parking baseline. Points are also awarded for projects providing a reduced supply of parking as allowed by an approved variance.

**Change the Telecommute tooltip to:**
Offer employees a telecommute option for at least 1 day a week, which would allow employees to work from home rather than commute to the office. This telecommute option must be available to at least 50% of employees assigned to the project site. 

**Change TelevisIts tooltip to:**
Offer visitors virtual visitation options including telehealth, virtual meetings, remote learning, and conferencing. 

** Neighborhood Shuttles/Microtransit Service: (HOW CAN WE CHANGE TOOLTIPS AND CHOICE DESCRIPTIONS TO MATCH DOCUMENT?)** 
The current tooltip and choices are worded much differently than in Table 15 of the document.

**Change tooltip for Transit Passes to:** 
Provide all employees/**residential** units transit subsidies. Points awarded vary based on the amount of transit subsidy provided per employee or residential unit.
Also need to review the drop-down choice wording for clarity.

**Improve Transit Service: Change name to Improve Transit Service from Improved Transit Service.**

**Improve Transit Service: Add the following to the existing tooltip:** 
[LADOT shall pre-approve the selection of this TDM Strategy to ensure the availability of qualifying transit service that serves the property. ]  

**Change tooltip for the "Join a TMO" strategy to:**
Join an existing TMO. 

[LADOT shall pre-approve the selection of this TDM Strategy to verify the availability of a qualifying TMO that could serve the property. For a reference of criteria that is considered in pre-qualifying a TMO, see Appendix E: Transportation Management Organization (TMO) Certification Guidelines. ]

Change the toolitp for the Crate a new TMO strategy to:
Create a new TMO in an area where there is not already an existing TMO service. Should a project select to start a new TMO, the project must not be within an existing TMO service area and commit to a two- year membership to be awarded points.

[LADOT shall pre-approve the selection of this TDM Strategy to verify the feasibility of establishing a TMO that could serve the property. For a reference of criteria that is considered in pre-qualifying a TMO, see Appendix E: Transportation Management Organization (TMO) Certification Guidelines.]

**User-defined strategies: change name from User-Defined Strategy? (MAYBE THIS IS UNINTENTIONAL?)**

**User-defined strategies: Change tooltip to (THE APPLICATION DOES NOT HAVE AN APPENDIX C):**
Implement a strategy in coordination with LADOT that does not appear in Appendix C. 

[Consult LADOT before submitting a TDM Plan. User-defined strategies must have approval from LADOT before the TDM Plan is accepted.} 

### Resources/Instructions
https://docs.google.com/document/d/1MMSekrB-CvsaTDnAjzrr2G46UTo-vuit/edit?usp=sharing&ouid=106171381835153184500&rtpof=true&sd=true

**Comment by KPHowley** [comment]
LADOT Needs to review line descriptions in all dropdowns. this needs to be 75 characters maximum and worded clearly.

**Comment by ExperimentsInHonesty** [comment]
Out of date
