### ISSUE TITLE
Update encouragement Program tooltip no.3

### ISSUE THREAD

**Issue by SMR9220** [hackforla/tdm-calculator#1124]
### Overview
Encouragement Program tooltip no.3 states “Mandatory Trip Reduction Program strategy” as “Required Trip Reduction Program strategy”

### Action Items

- [x] Change wording from "Required" to "Mandatory"

### Resources/Instructions
<img width="895" alt="Mandatory wording correction" src="https://user-images.githubusercontent.com/69442669/164915639-5913f3a0-8f66-45ce-991f-ecb91eb065db.png">

**Comment by SMR9220** [comment]
For some reason, I cannot add labels or any other tags. Please advise. -Syria Martin-Rathan

**Comment by SMR9220** [comment]
@jahpe777 can you please take a look at this issue, thank you.

**Comment by jahpe777** [comment]
#1124 Updated Encouragement Program tooltip no.3
