### ISSUE TITLE
Generalized parking baseline for each unique project type

### ISSUE THREAD

**Issue by SMR9220** [hackforla/tdm-calculator#1126]
### Overview

We need to address the concern the users raised about Citywide Parking Baseline so that the calculations reflect or take account into the special/older areas/zones that specific projects locate at. 

### User concern summary
How can a generalized parking baseline on page 3 determine the point target for a specific project? For example, a project locates at old redevelopment plan areas (i.e. there are different downtown zones - mentioned by participant) and those zones have different requirements. 

### Action Items
- [ ] add to stakeholder meeting to discuss what happens if the citywide baseline being used by the calculator is  higher than the community parking requirements

### Proposed text

Your development may be in an area that has a lower requirement than the provided baseline, so the calculator does not penalize you. If your development is in an area that has a higher requirement than the provided baseline (contact [whomever], note that in the notes field on the first page)

### Placement of text
Add the message (via tooltip for Citywide Parking Baseline on page 3) 

![image](https://user-images.githubusercontent.com/37763229/215296671-548b2d43-2490-463d-9400-456abb3bdc5e.png)

**Comment by SMR9220** [comment]
Will get more details for solution clarification, and then finalize.
For some reason, I cannot add labels or any other tags. Please advise. -Syria Martin-Rathan

**Comment by Biuwa** [comment]
Is this stakeholders' or team's decision to make @SMR9220?

**Comment by SMR9220** [comment]
> Is this stakeholders' or team's decision to make @SMR9220?

Teams decision. The wording and/or potential solutions has yet to be determined.

**Comment by ExperimentsInHonesty** [comment]
@Jane4925 I rewrote the issue.  Some items are missing, please review and improve so that we can prioritize this

**Comment by Biuwa** [comment]
@Jane4925 Reminder to please review this issue.

**Comment by Biuwa** [comment]
@Jane4925 please review this issue

**Comment by Biuwa** [comment]
- add to #975

**Comment by Jane4925** [comment]
My recollection is that we talked about this with stakeholder before, and they weren't planning on revising the Ordinance again back then.

**Comment by Biuwa** [comment]
- #975

**Comment by Biuwa** [comment]
**2023 STAKEHOLDERS MEETING NOTES:**
Emily: Less likely to run into this issue, becoming less of a potential problem. Ways to resolve: 
1. There are relief mechanisms in the policy/ordinance. 
2. Write guidance in the implementation guide for the TDM ordinance.
No FAQ update is expected at this time. Hack for LA will bring it back to this space if it comes up in user testing.
