### ISSUE TITLE
Affordable Housing Level Percentage

### ISSUE THREAD

**Issue by Biuwa** [hackforla/tdm-calculator#1130]
### Overview
We need to change how the affordable housing checkbox on page 2 works with the drop-down on page 4 in order to
-  fix a bug that let's have two different selections for affordable housing and inadvertently lower your project level below what your project is eligible for
- make it clearer for users

### Details
Users are confused about how the housing level percentage is calculated as it appears on Page 2 and also on Page 4.  While we were reviewing that we also found a hack that would let people have lower project level, which would later force an audit during the plan review.

### Action Items
- [ ] Explain problem
- [ ] Suggest Solutions
- [ ] present to stakeholders
- [ ] add their decision to the issue
- [ ] make issue for dev or make more mockups if any other options are presented and choosen  during stakeholder meting

### Zoom Recording Timestamp
https://drive.google.com/file/d/1YGTHGvwxlSP77rjnrtzcN12rL6JEa-WC/view?usp=sharing
00:01:17-00:15:00

**Comment by ExperimentsInHonesty** [comment]
Note about changing the control from a check box to mirroring the control on page 4 (drop down select), including the prompt and the tool tip.

Mirror the whole item (name, dropdown and tooltip), but don't show the points earned in  the left panel and circle until page 4 (just like the bike parking).

**Comment by Biuwa** [comment]
#975

**Comment by ExperimentsInHonesty** [comment]
## How the 100% affordable housing choice is currently working in the calculator
![image](https://user-images.githubusercontent.com/37763229/212496247-782f021e-1231-4ebd-85d7-f215684bff7c.png)
![image](https://user-images.githubusercontent.com/37763229/212496273-66db17d6-96b9-4eca-aaa6-988df253f83f.png)

## Choices for fixing it
![image](https://user-images.githubusercontent.com/37763229/212496330-0d4a1e33-4483-450b-86ab-587079c5503e.png)
![image](https://user-images.githubusercontent.com/37763229/212496342-f11b9d3c-f826-4bf6-bab6-682d2e3aedea.png)

**Comment by Biuwa** [comment]
we will keep the check box on page 2 and when users arrive on page 4, it automatically selects '100% affordable' from the dropdown options. It will also show a warning if they try to change it on either page 2 or page 4 to anything that will increase the project level.

John will decide to make it a generic message if any change is made to the project level by changing the drop-down selection or checkbox.

**Comment by ExperimentsInHonesty** [comment]
Move this to released when new issue is made
