### ISSUE TITLE
Modify User Defined Strategy Tooltip

### ISSUE THREAD

**Issue by Biuwa** [hackforla/tdm-calculator#1133]
### Overview
Users need information and instructions on User Defined Strategy as there is no information or instruction on how to use it,

### Action Items
- [x] Remind Stakeholders to provide the instructional content for the tooltip
![tdm](https://user-images.githubusercontent.com/98936028/166138346-88e792d0-64c8-4857-8f1c-ae02efc149b6.png)

### Resources/Instructions
- Stakeholders agreed to provide a beefed-up tooltip that will elucidate the strategy more
- implementation guidelines will also help provide information and explanations on how to use the strategy
https://drive.google.com/file/d/1YGTHGvwxlSP77rjnrtzcN12rL6JEa-WC/view?usp=sharing
Timestamp: 34:24

**Comment by ExperimentsInHonesty** [comment]
Emailed stakeholder 2022-11-15 after meeting
User Defined Strategy Tooltip
https://github.com/hackforla/tdm-calculator/issues/1133
As previously discussed ([2022-04-19 deck](https://docs.google.com/presentation/d/1eJUkNHqGcUCF1lumfpFrQ4ma4-ePh5tUFN1gjUu_W9Y/edit#slide=id.g124f74f2c7a_3_8) | [video](https://drive.google.com/file/d/1YGTHGvwxlSP77rjnrtzcN12rL6JEa-WC/view?usp=sharing) 34:24), we need a tooltip that explains why, how and when to use User Defined Strategy.

LADOT & LACP will update the [Tooltip language](https://docs.google.com/document/d/1QHQ-C6OY8L_F-rKcTIw30BnC2iuAHWqK1CDMRvtSps4/edit?usp=sharing)

**Comment by mojimoh** [comment]
### Notes from 2023-01-10 meeting with stakeholder
- Alexander will post into the document today.  Emily and Alexander will review before they let us know its ready.

**Comment by Biuwa** [comment]
[Tooltip language](https://docs.google.com/document/d/1QHQ-C6OY8L_F-rKcTIw30BnC2iuAHWqK1CDMRvtSps4/edit?usp=sharing) has been updated.

"Customized strategy that does not fit within available listed strategies. Applicants must provide justification from studies or academic literature that the proposed strategy is in line with the TDM Program’s goals. This strategy requires pre-approval from LADOT and an Alternative Compliance approval from LA City Planning. To achieve pre-approval, applicants must share details of how the strategy works, past examples of this strategy’s use in development projects, if available, and estimated number of single-occupant vehicle trips reduced if implemented. Email ladot.tdm@lacity.org to submit the proposed strategy plan to a TDM planner"

**Comment by ExperimentsInHonesty** [comment]
@mojimoh or @Biuwa please make a new issue for development to make this change.  Use the same milestone as this issue.

**Comment by awikstrom-ladot** [comment]
@entrotech @ExperimentsInHonesty Emily and I revised this tooltip with the following text: 
Customized, project-specific strategy that is distinct from any strategies available in the TDM strategy menu. A User-Defined Strategy requires pre-approval from LADOT and an Alternative Compliance approval (discretionary entitlement) from LA City Planning. Applicants must provide justification from studies or academic literature that the proposed strategy is in line with the TDM Program’s goals. The application must include details of how the strategy works, past examples of the strategy’s use in development projects, if available, and estimated number of single-occupant vehicle trips reduced if implemented.
