### ISSUE TITLE
Misrepresentation of the cost of Transit Passes

### ISSUE THREAD

**Issue by Biuwa** [hackforla/tdm-calculator#1135]
### Overview
Users are worried broad ranges of percentages misrepresent the cost of Transit Passes

### Action Items
- [ ] Reduce the range sizes and increase the number of range selections to fairly adjust earned points. These ranges must align with Metro's guidelines. Waiting on stakeholder
- [ ] Add a tooltip that explains how each gradiation was selected.

### Resources/Instructions
5/3/2022 Slide deck, slide no.5:
https://docs.google.com/presentation/d/1L-jjtspbw7Re_rNgncN0QRciu7iyxFicbGCSoMLzNbk/edit#slide=id.g126b7371ae7_1_8

<img width="964" alt="slide 5 ss" src="https://user-images.githubusercontent.com/69442669/167525835-c9720ce4-ce5d-4b4d-955d-c524cd8fe040.png">

### Zoom Recording Timestamp:
00:00:10 - 00:02:15
https://drive.google.com/file/d/1eTkhtTLAsi5fJPOqUSCOB0k78pg-06oq/view

**Comment by ExperimentsInHonesty** [comment]
Summary of meeting with stakeholder (when original recording was made) was that they would pass on the concern from users and that this could change in the future, but they had no guidance to change it now.

A later meeting (before city council meetings) and they said it had not changed and was not going to currently.

**Comment by Biuwa** [comment]
The tooltip will not be updated by LADOT or LACP at this time. If it comes up in future testing, we can revisit it. 
Add a note to our testing, directing the user to discuss the issue directly with LADOT.


 

@Jane In future user testing, please keep an eye out for this issue. If anyone is willing to discuss it further, HFLA will schedule a meeting with LADOT.
