### ISSUE TITLE
Detailed information on shared parking

### ISSUE THREAD

**Issue by Biuwa** [hackforla/tdm-calculator#1136]
### Overview
Users wonder about details for Shared Parking and want more descriptive information in the tooltip regarding how parking is assumed to be shared

### Action Items
Stakeholders would like to further clarify this issue on their end before proceeding.

### Resources/Instructions
5/3/2022 Slide deck, slide no.6:
https://docs.google.com/presentation/d/1L-jjtspbw7Re_rNgncN0QRciu7iyxFicbGCSoMLzNbk/edit#slide=id.g126b7371ae7_1_61

### Zoom Recording Timestamp
00:04:45
https://drive.google.com/file/d/1eTkhtTLAsi5fJPOqUSCOB0k78pg-06oq/view

**Comment by ExperimentsInHonesty** [comment]
Emily  says change it to reflect regulation

> Share parking among different land uses or properties. A notarized agreement among tenants or property owners is required to receive points.

**Comment by ExperimentsInHonesty** [comment]
Next step is dev makes issue for this change

**Comment by entrotech** [comment]
This design issue is closed - corresponding development issue is #1224
