### ISSUE TITLE
Bonus package confusion

### ISSUE THREAD

**Issue by Biuwa** [hackforla/tdm-calculator#1137]
### Overview
Initially, users were confused with Bonus Package and they want attention brought to it when they first land on the page (wordings, tooltips, design, etc.). After briefly  discussing this issue during the 5/3/22 meeting, stakeholders raised concern regarding bonus point package eligibility on whole.

### Action Items
- [x] Determine if the bonus package will be exclusive to level 1 projects (that do not require any addition parking) which require a total of 15 points.
- [x] If the bonus package will be exclusive to level 1 projects, insert the message, "You qualify for a bonus package that will meet/fulfill your total target of 15 points." 
- [x] Edit tooltip to make it more concise

### Resources/Instructions
5/3/2022 Slide deck, slide no.7:
https://docs.google.com/presentation/d/1L-jjtspbw7Re_rNgncN0QRciu7iyxFicbGCSoMLzNbk/edit#slide=id.g126b7371ae7_1_114

Tooltip adjustments google doc:
https://docs.google.com/document/d/1hgU9RycByzn6XDOTmqqS4qcCrLF7yCh2F6prcZEHL4o/edit

### Zoom Recording Timestamp

00:07:00
https://drive.google.com/file/d/1eTkhtTLAsi5fJPOqUSCOB0k78pg-06oq/view
<img width="955" alt="issue 1138" src="https://user-images.githubusercontent.com/69442669/167974574-fdd40f0a-4940-4ba4-8850-e8b11e644460.png">

**Comment by KPHowley** [comment]
comments from 5/3:

Potentially add:
- More information to the box at the top of the page mentioning the 14 + 1 points
- Include the bonus package in the table in the tooltip.
- Change the "possible" points to 15 or 14+1
- add the stratagies in the package to the package title.

**Comment by entrotech** [comment]
@KPHowley Need more clarification on exactly what the tooltip should say, and whether the package is available for projects with target points = 15 (i.e, < 110% of baseline) or just to projects that are less than or equal to 100% of baseline.

**Comment by SMR9220** [comment]
As per Emily's input during the May 3rd stakeholder meeting, "overparking" is defined as any number of spaces up to 110, for a level one project having 100 dwelling units. Based on this, Is it safe to assume that only level 1 projects with 0-110% parking are eligible for this bonus package?

**Comment by entrotech** [comment]
@KPHowley @SMR9220 Need to verify that this Issue is consistent with the implementation of Issue #1163 and #1145, which are completed.

**Comment by Biuwa** [comment]
@KPHowley @SMR9220 Please respond to this, I created a discussion topic for this on the deck, and I want to be sure it belongs there

**Comment by SMR9220** [comment]
#1192 created for development
