### ISSUE TITLE
Differences between TDM and VMT Calculator

### ISSUE THREAD

**Issue by Biuwa** [hackforla/tdm-calculator#1138]
### Overview
We need to review the user concerns about the differences between the VMT & TDM to determine if there are any actionable items.

### Users concern
Users note differences between TDM Calculator and VMT Calculator, and they want strategies and descriptions aligned more closely with VMT Calculator to prevent potential confusion 

### Action Items
- [x] Identify the specific quotes to review with the stakeholders
- [x] Add them to the deck
- [ ] identify if there are any changes, and if there are, make an issue.

### Resources/Instructions
[5/3/2022 Slide deck, slide no.8](https://docs.google.com/presentation/d/1L-jjtspbw7Re_rNgncN0QRciu7iyxFicbGCSoMLzNbk/edit#slide=id.g126b7371ae7_1_166)

### Zoom Recording Timestamp:

00:23:45
https://drive.google.com/file/d/1eTkhtTLAsi5fJPOqUSCOB0k78pg-06oq/view

**Comment by ExperimentsInHonesty** [comment]
I think we may have grouped together some concerns in a way that seemed similar to us, but are actually separate issues.  Please find each of the concerns a user had (that you were covered by this issue), and document exactly what they said, so we can get LADOT/LACP to address each one on its merits.

Here is the info from the slides

### Quote 1: 
> I know there's a tie in with the city's vehicle miles traveled (VMT) calculator but the land uses don't necessarily match up. Like, the different options for retail and restaurant, for example, we're not necessarily interested in the number of habitable rooms, we're just more interested in number of dwelling units.

Answer 1. Dwellings and Habitable rooms are different number and asked for different reasons.  So there is no change to the VMT or TDM or this concern

### Quote 2: 

> The TDM strategies on the VMT calculator don't necessarily correlate with this TDM calculator. For example[...] maybe the city will be updating [strategy section]. [...]For example, like for the transit passes here, it says order new subsidizing. Our project will be subsidizing a certain amount to all residents and employees. But the way it's done between the VMT and this calculator is different. [...] I think there just needs to be more correlation between the two”

### Quote 3: 

> It seems like the information [the client] [has] for this project is derived from the entries they made to the VMT calculator as part of their proposal preparation. So [clients] are missing any documentation in their project files of information that TDM is asking for that VMT did not already ask for.

**Comment by ExperimentsInHonesty** [comment]
Add this to the slide and get an answer
### Quote 2: 

> The TDM strategies on the VMT calculator don't necessarily correlate with this TDM calculator. For example[...] maybe the city will be updating [strategy section]. [...]For example, like for the transit passes here, it says order new subsidizing. Our project will be subsidizing a certain amount to all residents and employees. But the way it's done between the VMT and this calculator is different. [...] I think there just needs to be more correlation between the two”
