### ISSUE TITLE
Project submission visualization

### ISSUE THREAD

**Issue by Biuwa** [hackforla/tdm-calculator#1139]
### Overview
Users are anxious about how much this tool determines final approval and want to add visualization of project submission and approval steps on the summary page

### Action Items
No action required. As per 5/3/22 stakeholder meeting, "...I don't think it's something the calculator needs right now."

### Resources/Instructions
5/3/2022 Slide deck, slide no.9:
https://docs.google.com/presentation/d/1L-jjtspbw7Re_rNgncN0QRciu7iyxFicbGCSoMLzNbk/edit#slide=id.g126b7371ae7_1_218

### Zoom Recording Timestamp

00:31:15
https://drive.google.com/file/d/1eTkhtTLAsi5fJPOqUSCOB0k78pg-06oq/view

**Comment by KPHowley** [comment]
Meeting from 5/3: 

Planning/Ladot is taking this as feedback but has no concrete proposals.
