### ISSUE TITLE
Additional functions after project submission

### ISSUE THREAD

**Issue by Biuwa** [hackforla/tdm-calculator#1140]
### Overview
Users wonder what can be done with the information after submission, add prompt to print, save as pdf, send via email, contacts for questions

### Action Items
- [x] #1313 - interim
- [ ] Mock up page 5 (separate to above) with a download PDF button (could be called print button - design decides)
- [ ] Mock up what PDF should like 

### Resources/Instructions
5/3/2022 Slide deck, slide no.10:
https://docs.google.com/presentation/d/1L-jjtspbw7Re_rNgncN0QRciu7iyxFicbGCSoMLzNbk/edit#slide=id.g126b7371ae7_1_270

###Zoom Recording Timestamp

00:36:10
https://drive.google.com/file/d/1eTkhtTLAsi5fJPOqUSCOB0k78pg-06oq/view | 

Video Transcription
[Video Transcription](https://docs.google.com/document/d/1W3p604ZOqW1B-Jpe65tiPuSBa7JhBV5IU6hG6u00SfQ/edit?usp=sharing)

**Comment by KPHowley** [comment]
Meeting from 5/3: 

Potentially add print button
Want to add disclaimer that submitting will come later on final page

**Comment by Biuwa** [comment]
LADOT and LACP TDM have it on their agenda tomorrow 2022-11-16 concerning #1263.

A follow-up email was sent to Xander, and this will be discussed in the next meeting on 2022-11-29

**Comment by Biuwa** [comment]
- add to #975

**Comment by Biuwa** [comment]
- #1313 and #1314 is the design issue that clarifies this issue
