### ISSUE TITLE
Standard address format

### ISSUE THREAD

**Issue by Biuwa** [hackforla/tdm-calculator#1141]
### Overview
Users wonder why both AIN# and address are required and what is a standard address format? 
Provide clarification inside the tooltip

### Action Items
- [x] Add a tooltip to the address field that says: 'Address can be a single address or range of addresses used for project identification'
- [x] Add a tooltip to the AIN/APN field that says: 'AIN/APN must include all the parcels in the project site'
- [ ] release dependency on #1219 once this issue is completed.

### Resources/Instructions
Planning address format: https://planning.lacity.org/odocument/3d913582-d6e7-4375-90e8-3e276b9c28bb/Department%20of%20City%20Planning%20Application

5/3/2022 Slide deck, slide no.11:
https://docs.google.com/presentation/d/1L-jjtspbw7Re_rNgncN0QRciu7iyxFicbGCSoMLzNbk/edit#slide=id.g126b7371ae7_1_322

###Zoom Recording Timestamp

00:42:10
https://drive.google.com/file/d/1eTkhtTLAsi5fJPOqUSCOB0k78pg-06oq/view

<img width="1440" alt="slide 11 address" src="https://user-images.githubusercontent.com/69442669/168428100-d7f6edd0-f6d2-4e9a-a0f1-78a8447a5549.png">
0

**Comment by KPHowley** [comment]
Can add tool tip to address saying it's for identification purposes only. 

Planning address format:
https://planning.lacity.org/odocument/3d913582-d6e7-4375-90e8-3e276b9c28bb/Department%20of%20City%20Planning%20Application

**Comment by SMR9220** [comment]
Could we add greyed out text in the text field that prompts users to input address information in a specific format? Example:  "street, city, state, zip code"

**Comment by ExperimentsInHonesty** [comment]
Email says use this wording:

> Address can be a single address or range of addresses used for project identification
> AIN/APN must include all the parcels in the project site

**Comment by entrotech** [comment]
The AIN/APN already had a tooltip, so I prepended the suggested wording to the existing tooltip:

<div>AIN(s) must include all the parcels in the project site.
  </div>
  <div>You may  look up your Assessor&apos;s Identification number on the 
	<a href="http://maps.assessor.lacounty.gov" target="_blank" rel="noopener noreferrer">
	Los Angeles County Property Assessment Information System</a> portal.
</div>

**Comment by ExperimentsInHonesty** [comment]
The wording that emily provided for address says
> Address can be a single address or range of addresses used for project identification

What is says in the tooltip is 
> Address can be a single address or range of addresses used for the project

so it's missing the word `identification` at the end of the sentence

**Comment by ExperimentsInHonesty** [comment]
This issue is closed because we added wording to all the items on the first page via issue #1218
