### ISSUE TITLE
Users want more categories on page 2

### ISSUE THREAD

**Issue by Biuwa** [hackforla/tdm-calculator#1142]
### Overview
Users hope there are more options to choose from on Page 2, they want more categories Included or expand more options under each category

### Action Items
- [x]  On the bottom of page 2, as per stakeholder approval, add text:
     "If your project’s land use is not listed above, please check LAMC Section 12.26 J.3(c) of the [Draft Revised TDM Ordinance](https://planning.lacity.org/odocument/1dc924ce-b94a-403b-afe0-17ba33b3dbe1/Draft_TDM_Ordinance.pdf) for applicability and exemption details."
- [ ] #1181

### Resources/Instructions
5/3/2022 Slide deck, slide no.11:
https://docs.google.com/presentation/d/1L-jjtspbw7Re_rNgncN0QRciu7iyxFicbGCSoMLzNbk/edit#slide=id.g126b7371ae7_1_378

### Zoom Recording Timestamp
00:50:45
https://drive.google.com/file/d/1eTkhtTLAsi5fJPOqUSCOB0k78pg-06oq/view

<img width="1440" alt="slide 12 quote 2" src="https://user-images.githubusercontent.com/69442669/168428638-b727a377-3933-4deb-ab63-f720b491a370.png"
<img width="499" alt="Checkbox" src="https://user-images.githubusercontent.com/69442669/172015895-968220c4-542c-425a-a971-7633edcb0ba2.png">
>

**Comment by KPHowley** [comment]
solution: add a text telling users if their use type is not listed it may be exempt.

**Comment by KPHowley** [comment]
Ask LADOT if there is a resource for what the definition of each specification type. if users are stillunclear where can they go to ask....

**Comment by KPHowley** [comment]
"If your Land use is not listed above please check LAMC Section 12.26 J.3(b)(3) of the[ Draft Revised TDM Ordinance](https://planning.lacity.org/odocument/1dc924ce-b94a-403b-afe0-17ba33b3dbe1/Draft_TDM_Ordinance.pdf) for exemption details."

**Comment by SMR9220** [comment]
#1193 created by developer.

**Comment by SMR9220** [comment]
The language changes suggested by Emily and Xander include subheadings, which will change the current format of the "Residential" portion on page 2 of the application. Renee will create mock ups for potential design ideas that include the subheaders. Please refer to [this document](https://docs.google.com/document/d/1mrSniJGLqQ-pxqes9hR0rQoFp7619PElCo_zMCCvOQk/edit#) bookmark #5 for further clarification.

**Comment by entrotech** [comment]
@SMR9220  Can we close this?  I think the language change described above was superceded by a different issue to just be "Condominium Units".
