### ISSUE TITLE
Project level 0 prompt confusion

### ISSUE THREAD

**Issue by Biuwa** [hackforla/tdm-calculator#1143]
### Overview
Users do not know what to do with Project Level 0. they want clear instructions added to the current prompt

### Action Items
- [x] As per stakeholder approval, change text on this page to:
      _FIRST PARAGRAPH_ "Based on the information you provided, the Transportation Demand Management (TDM) Ordinance **may** not apply to your project due to its smaller size. Please check LAMC Section 12.26 J.3(c) of the [Draft Revised TDM Ordinance](https://planning.lacity.org/odocument/1dc924ce-b94a-403b-afe0-17ba33b3dbe1/Draft_TDM_Ordinance.pdf) for applicability and exemption details.
     _SECOND PARAGRAPH_ "Final determination of the TDM Ordinance applicability will be made by the Department of Building and Safety upon review of your project application."

- [x] #1216

### Resources/Instructions

Solution to question 1 - Refer to the exemptions for clarification.
Solution to question 2 - n/a
Solution to question 3 - After submission to project planning, the user will be notified if changes are necessary. 

5/3/2022 Slide deck, slide no.13:
https://docs.google.com/presentation/d/1L-jjtspbw7Re_rNgncN0QRciu7iyxFicbGCSoMLzNbk/edit#slide=id.g126b7371ae7_1_385

### Zoom Recording Timestamp
00:58:00
https://drive.google.com/file/d/1eTkhtTLAsi5fJPOqUSCOB0k78pg-06oq/vie
<img width="1042" alt="Project Level 0" src="https://user-images.githubusercontent.com/69442669/172013925-51bc3852-51ac-40fe-8063-93ea21fa57bb.png">
<img width="499" alt="Checkbox" src="https://user-images.githubusercontent.com/69442669/172013927-ee908ca7-9b95-4440-8519-d090aa3f2192.png">
w

**Comment by KPHowley** [comment]
meeting notes 5/3

Take of bold on "may"
add second paragraph:   "Check LAMC Section 12.26 J.3 of the Draft Revised TDM Ordinance for project thresholds and exemption details" 
Final paragraph change to " Final determination… will be made by the Department of Building and Safety and LADOT upon review…"

**Comment by SMR9220** [comment]
Unsure how the text "Final paragraph change to " Final determination… will be made by the Department of Building and Safety and LADOT upon review…" and "Review this code section of the revised ordinance for project thresholds and exemption details." should be combined for addition to the page. Please advise.

**Comment by SMR9220** [comment]
#1194 created by developers

**Comment by SMR9220** [comment]
The current Draft Revised TDM Ordinance link should be updated to the following URL:
https://planning.lacity.org/odocument/bb9114b3-29e3-423f-8b91-027afb242e63/Revised_DRAFT_TDMOrdinance_June2022.pdf

The wording of the display text should not change, only the link it goes to.
