### ISSUE TITLE
Sort out the two Figma files

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/tdm-calculator#1144]
### Overview
We need to have just one Figma file so that there is no confusion about which is the source of truth.  

### Action Items
- [ ] Go through both the old and new Figma files, we can delete anything (from the old) that is in the new.  
- [ ] Then annotate the first page of the old Figma file to have a link to the new one and that the old one is deprecated, in case anyone comes to it accidentally.
- [ ] Investigate documents from other teams , work with the UI/UX COP
- [ ] determine best origination system
- [ ] rename and organize pages
- [ ] create a single page or easy way to identify current versions 

### Resources/Instructions
[figma new](https://www.figma.com/file/nD9QK56Mzq7xNSaSUoeGx0/TDM-Calculator?node-id=4041%3A12650)
[figma old](https://www.figma.com/file/qNgPc5lttpf0SWSwkbbWyT/TDM-Calculator?node-id=2534%3A1)
Sample documents from other projects:
https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website

https://www.figma.com/file/BJL6ZHfjrxVhU8jvD9gB3P/HomeUniteUs-Everything-Figma?node-id=1%3A934

### Related Issues
- #537

**Comment by Biuwa** [comment]
@Reneedesigns please discuss this with your team.

**Comment by mojimoh** [comment]
Please provide an update before Wednesday
1. Progress: "What is the current status of your project? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"
5. Pictures (if necessary): "Add any pictures that will help illustrate what you are working on."

**Comment by Biuwa** [comment]
@Noushie I know files have already been sorted out and you are currently down to one Figma file. Can this be considered complete, are there any current blockers?

**Comment by Noushie** [comment]
> considered 

Nope! This issue can be closed.
