### ISSUE TITLE
Redesign the "target points circle" on the sidebar.

### ISSUE THREAD

**Issue by SMR9220** [hackforla/tdm-calculator#1151]
### Overview
Point area needs to be more visible for users.

### Action Items
- [x] Make the "target points" circle larger or more visible

### Resources/Instructions
<img width="385" alt="Screen Shot 2022-05-28 at 12 43 44 PM" src="https://user-images.githubusercontent.com/69442669/170834804-7fb28a55-e529-42fc-848b-e0503bd4122f.png">

**Comment by Reneedesigns** [comment]
Enlarged progress circle

![enlarged progress circle](https://user-images.githubusercontent.com/99779174/173195763-89bb6f60-200d-4861-96e7-ccc42b97cea4.png)

**Comment by entrotech** [comment]
Point sizes of text aren't exact in Figma, so I just eyeballed the sizing and spacing of the text and labels.

**Comment by entrotech** [comment]
Here is what the final implementation looks like. The Target Points circle isn't quite as large as Renee's design, but may be close enough:

![image](https://user-images.githubusercontent.com/9939032/196005228-48bea39b-5784-4f6e-a8be-e6046ecf6fc6.png)

**Comment by ExperimentsInHonesty** [comment]
I don't think the increased size was fully achieved.  Here is a screenshot from the current production environment

![Image](https://github.com/user-attachments/assets/66ebe380-824f-4b0d-b242-fccae94aac0c)
