### ISSUE TITLE
Users could not find Checklist once closed

### ISSUE THREAD

**Issue by SMR9220** [hackforla/tdm-calculator#1157]
### Overview
Users need to be able to find the checklist once it is closed.

### Action Items
-  [ ] Provide a clickthrough orientation of where to find things upon landing, similar to the popovers used for new product releases.

OR

- [x] Put checklist in a top level navigation help drop down.   add animation showing the checklist shrinking to the corner

### Resources/Instructions
Some users were worried that the checklist may not have what they needed to use the calculator, but they proceeded anyway. They could not find the checklist after it was closed.

**Comment by jahpe777** [comment]
Fixed issue of Checklist Modal not showing up initially on every page. All Checklist links within Footer should work on every page now.

**Comment by jahpe777** [comment]
Added animation for closing the Checklist modal so that the user will have a visual to where the Checklist button is if they want to see it again.

**Comment by Biuwa** [comment]
https://user-images.githubusercontent.com/98936028/183279098-741379a3-ab74-4746-82da-e04039036cb2.mov

**Comment by ExperimentsInHonesty** [comment]
showed it to stakeholders, we agree it should be a little slower.

**Comment by Biuwa** [comment]
@jahpe777 During today's meeting, stakeholders sought to slow down the checklist closing animation as the speed was too fast.

**Comment by jahpe777** [comment]
slowed down speed of animation from 1000ms to 1500ms

**Comment by Biuwa** [comment]
Slowed down checklist closing Animation 

https://user-images.githubusercontent.com/98936028/185002128-3917adba-aec4-401d-a5b2-47c3d6c81ce1.mov
