### ISSUE TITLE
User are uncertain what to put in "Project Description" text box

### ISSUE THREAD

**Issue by SMR9220** [hackforla/tdm-calculator#1158]
### Overview
Users are uncertain about what to put in the "Project Description" text box

### Action Items
- [ ] Add a tooltip that says:  'As described in your Planning or Building Permit application materials'

### Resources/Instructions
Users felt this could be many pages long and confused about what the information in this field will be used for.

**Comment by ExperimentsInHonesty** [comment]
Emily says it should say: 

> As described in your Planning or Building Permit application materials
