### ISSUE TITLE
Users did not notice that some fields were NOT required

### ISSUE THREAD

**Issue by SMR9220** [hackforla/tdm-calculator#1159]
### Overview
Users approached this as an official form, wanting to comply and complete every field. 

### Action Items
- [ ] Separate required and non-required fields by heading text. This heading could double as solution to communicating reason AIN and address are required, eg., "Create Project ID" (subtext: Required ...) followed by "Your Project Details" (subtext: Information for your internal team's project) (Changed to using placeholder text instead - see comments below. Created development issue #1225 for this.)
- [ ] Update Alternative # tooltip to "This information is for personal use only."  Development Issue #1185

### Resources/Instructions
In reviewing the page, they did notice the red asterix and red box indicated a required field, but it was unclear to them that the other fields were NOT required.
<img width="1380" alt="alt number tooltip" src="https://user-images.githubusercontent.com/69442669/172017156-2bb675a2-26ab-49d7-8dda-97c4a5ba9c4d.png">

**Comment by entrotech** [comment]
Create Development Issue #1185 for implementation

**Comment by entrotech** [comment]
Need an approved UI/UX design before we can implement Item #1

**Comment by Reneedesigns** [comment]
created 3 options for possible design  @SMR9220 @Biuwa 

- Opt 1...placeholders with "required" and "optional" in appropriate boxes
- Opt 2...placeholders of only the "required" boxes
- Opt 3...groupings of required and optional titles with some separation between those two section


![opt 1](https://user-images.githubusercontent.com/99779174/179315151-6d25da12-ef2c-4f1c-ba0e-fa51e2310b18.png)
s
![opt 2](https://user-images.githubusercontent.com/99779174/179315166-116aacf8-865c-4f0d-a5f6-558bb2238315.png)
![opt 3](https://user-images.githubusercontent.com/99779174/179315180-9f093138-205b-4dd1-b90b-43d5d64f61b3.png)

**Comment by SMR9220** [comment]
Stakeholders preferred Option 1, as per 2022-07-26 meeting.

**Comment by Biuwa** [comment]
Stakeholders went with this option:
![unnamed](https://user-images.githubusercontent.com/98936028/181128899-559acd47-ca6b-4aa6-a082-83ac285129b4.png)

**Comment by entrotech** [comment]
Created development issue #1225 for this.
