### ISSUE TITLE
Change Shared Parking Tooltip

### ISSUE THREAD

**Issue by awikstrom-ladot** [hackforla/tdm-calculator#1168]
Change Shared Parking strategy's tooltip from "Share parking among different land uses or tenants within a mixed use development. Covenant or MOU agreement among tenants required to receive points." to "Share parking among different land uses or properties. Covenant or MOU agreement among tenants required to receive points."

@entrotech @ExperimentsInHonesty @KPHowley @Dsomers74

**Comment by Dsomers74** [comment]
Just a slight revision from @awikstrom-ladot request: Change Shared Parking strategy's tooltip from "Share parking among different land uses or tenants within a mixed use development. Covenant or MOU agreement among tenants required to receive points." to "Share parking among different land uses or properties. A notarized agreement among tenants or property owners is required to receive points."

**Comment by Biuwa** [comment]
@jahpe777 please look into this

**Comment by jahpe777** [comment]
#1168 updated shared parking tooltip
