### ISSUE TITLE
Users had difficulty reading greyed out text

### ISSUE THREAD

**Issue by SMR9220** [hackforla/tdm-calculator#1172]
### Overview
Some users found it difficult to read the greyed out text, making them feel anxious about what was being eliminated from their options.

### Action Items
- [x] Change the opacity of greyed out text to .6

### Resources/Instructions
Page 4 of the TDM tool

![hack opacity issue](https://user-images.githubusercontent.com/69442669/171766733-84301223-4fb6-42f0-ba41-fb63762d2efc.jpg)

**Comment by jahpe777** [comment]
#1172 updated opacity of rulestrategy and tooltip description
