### ISSUE TITLE
Users didn't notice tooltips

### ISSUE THREAD

**Issue by SMR9220** [hackforla/tdm-calculator#1179]
### Dependency
- [x] #1218

### Overview
Many users completed the page without noticing that more information was available by clicking on the text. Even when they saw the underline appear, they still didn't click there. It wasn't a clear indication to them that if they clicked they could reveal the tooltip. 

### Action Items

- [x] Change cursor into a pointer while hovering over options that have tooltips.
- [x] #1223

**Comment by ExperimentsInHonesty** [comment]
this did not get mocked up in time for our last stakeholder meeting, so it won't be implemented until we have mockups signed off by them and its after July 24th (when john returns).

**Comment by Reneedesigns** [comment]
- Added blue line under TDM Strategies
- Text and line turn to a "hyperlink" blue when hovered over
- Arrow pointer turns to hand pointer 

![blue underline](https://user-images.githubusercontent.com/99779174/178089691-d92916ed-83c4-4776-8c73-86ab3ae102ad.PNG)

Figma Prototype "V7 blue underline flow"
https://www.figma.com/proto/nD9QK56Mzq7xNSaSUoeGx0/TDM-Calculator?node-id=4107%3A13052&scaling=min-zoom&starting-point-node-id=6454%3A24432&show-proto-sidebar=1

**Comment by Biuwa** [comment]
Emily said to add 'Try hovering over a term you want more information on. If the words become underlined and bold, you can click for a description. Hovering over a green question mark will also provide more information' to help users notice the tooltips more efficiently.

**Comment by ExperimentsInHonesty** [comment]
Get design to mock up the following text in a box underneath the items on page 1 (project setup)

> Try hovering over a term you want more information on. If the words become underlined and bold, you can click for a description. Hovering over a green question mark will also provide more information

Identify which items on the page, do not have tooltips or planned tool tips, so that we can write some draft language for each, for LACP/LADOT to review.

**Comment by lexycatipon98** [comment]
- Added options of gray or blue textbox with bolded font 

<img width="618" alt="Screen Shot 2022-07-25 at 7 34 20 PM" src="https://user-images.githubusercontent.com/107448816/180910627-18d7aae4-0255-41cd-a0ec-33e524f4171a.png">
<img width="593" alt="Screen Shot 2022-07-25 at 7 34 01 PM" src="https://user-images.githubusercontent.com/107448816/180910630-34ed7544-dfaf-426b-9dd4-04ee6945cca1.png">

 @SMR9220 @Biuwa

**Comment by ExperimentsInHonesty** [comment]
They choose bold light blue

**Comment by Biuwa** [comment]
![image](https://user-images.githubusercontent.com/98936028/181130280-5fca7880-a06b-48ac-829b-f6fe014ebe56.jpeg)

**Comment by ExperimentsInHonesty** [comment]
Link to the figma page
Here is the text for the box and the tool tips for each item on page one that is missing a tool tip
https://docs.google.com/document/d/1CNWYzg_le3b_ncj7_ZeP3YUZumWfbkQ_FKtWUJr9IHU/edit

**Comment by entrotech** [comment]
Issue #1223 covers development of both Action items for this Project Management Issue.

**Comment by ExperimentsInHonesty** [comment]
please add the tool tips that are missing, see above.
