### ISSUE TITLE
Change wording from "Number of Condominiums - Units" to " Number of Condominiums - Rental Units"

### ISSUE THREAD

**Issue by KPHowley** [hackforla/tdm-calculator#1181]
### Overview
We need to clarify Rental unit information vs for sale unit information required for the users so that they know what to enter under Residential, page 2

### Action Items
- [x] Discuss at stakeholder meeting 
- [x] Create Proposed Text that aligns with stakeholder feedback
- [x] Send document to stakeholder with proposed text
- [x] get stakeholder sign-off
- [x] Create issue for dev to implement

### Resources and Instructions
- [Presentation where we talked about the problem the user experienced ](https://docs.google.com/presentation/d/1L-jjtspbw7Re_rNgncN0QRciu7iyxFicbGCSoMLzNbk/edit#slide=id.g126b7371ae7_1_378), quote 2
- [Video recording ](https://drive.google.com/file/d/1eTkhtTLAsi5fJPOqUSCOB0k78pg-06oq/view)from this time timestamp: 54:50
- Related Issue Link: #1142

<details>
<summary>Screenshot of Current Text</summary>

![image](https://user-images.githubusercontent.com/37763229/173204291-65acd37f-9602-4566-aea2-65d966011f97.png)
</details>

<details>
<summary>Proposed Text</summary>

Rental Units with less than 3 habitable rooms
Rental Units with 3 habitable rooms
Rental Units with more than 3 habitable rooms
Number of Condominiums - Units
Does this project qualify as 100% Affordable Housing?
</details>

**Comment by entrotech** [comment]
@KPHowley @SMR9220 @Reneedesigns This doesn't sound right to me.  I believe the number entered should represent all the units in the condo complex, regardless of whether they are rented or owned.  I added this to the document of wording to be reviewed by Zander et. al.

**Comment by ExperimentsInHonesty** [comment]
![image](https://user-images.githubusercontent.com/37763229/177430516-48976d08-3d1e-41d6-86a4-9677b2793070.png)
