### ISSUE TITLE
Change Bonus Package Tooltip Contents

### ISSUE THREAD

**Issue by entrotech** [hackforla/tdm-calculator#1192]
### Overview
Change Bonus Package Tooltip Contents to this:

![image](https://user-images.githubusercontent.com/9939032/174170609-85daf6ce-54c7-41b2-8646-7fa2f064a1bd.png)

(Note that there is no text before the table now.)

### Action Items
- [x] Make change to the Tooltip for the Residential or Employment Package strategy.
- [x] Make the same change to the wording for the School Package (but the table contents are different for the school package.

### Resources/Instructions
The contents for both tooltips can be found in the PackageTooltips.js file. 
To see the Residential or Employment Package strategy, you will need to enter data for a Level 1 Project.
To see the School Package strategy you will need to enter inputs for a small (Level 1) school project.

**Comment by ExperimentsInHonesty** [comment]
This is the text that Emily has approved

> Level 1 projects that provide no more than 110% of the Citywide Parking Baseline may be eligible for this optional bonus package. Because the strategies in a Bonus Package work together to reinforce their effectiveness in reducing drive-alone trips, projects that select a Bonus Package are awarded one additional bonus point, for a total of 15 earned points. Bonus Packages may not be ideal for all projects but are a way to provide easy compliance and implementation for small projects.
