### ISSUE TITLE
Change the wording of the footnote on the Checklist

### ISSUE THREAD

**Issue by entrotech** [hackforla/tdm-calculator#1193]
### Overview
Change the wording of the footnote on the Checklist.

### Action Items
- [ ] Change the wording of the footnote (circled on the screenshot below to:
``` If your project’s land use is not listed above, please check LAMC Section 12.26 J.3(c) of the  Draft Revised TDM Ordinance for applicability and exemption details.```
- [ ] Make sure to still have "Draft Revised TDM Ordinance" as a link that points to the current URL.

### Resources/Instructions
![image](https://user-images.githubusercontent.com/9939032/174172233-44a8e667-b0a9-44c1-9b8b-f8a9f27d0578.png)

**Comment by ExperimentsInHonesty** [comment]
This is the new wording from Emily

> If your project’s land use is not listed above, please check LAMC Section 12.26 J.3(c) of the [Draft TDM Ordinance](https://planning.lacity.org/odocument/1dc924ce-b94a-403b-afe0-17ba33b3dbe1/Draft_TDM_Ordinance.pdf) for applicability and exemption details.

Still waiting for the new draft ordinance link.  Must have by wed.
