### ISSUE TITLE
Draft Tooltips for page 1 for Stakeholder review

### ISSUE THREAD

**Issue by Biuwa** [hackforla/tdm-calculator#1218]
### Overview
We need to draft language and get it signed off on by Stakeholder, so that we can implement changes to reduce user confusion about what we are asking for on page 1

### Action Items
- [x] present language to stakeholders at next meeting

### Resources/Instructions
- Related Issue #1158

**Comment by ExperimentsInHonesty** [comment]
- Project Name
  - The project name should be the way that you refer to the project in conversation
- Building Permit #
 - Building Permits are not required to use the TDM calculator.  If you already have a building permit and can provide it here, it may help reduce staff time when reviewing your materials
- LADOT Case #
  - You may not yet have a LADOT Case #, if you do have it, providing it here, it may help reduce staff time when reviewing your materials
- City Planning Case #
-  You may not yet have a City Planning Case #, if you do have it, providing it here, it may help reduce staff time when reviewing your materials

**Comment by ExperimentsInHonesty** [comment]
- Development issue https://github.com/hackforla/tdm-calculator/issues/1226
