### ISSUE TITLE
Improve discoverability of tooltips

### ISSUE THREAD

**Issue by entrotech** [hackforla/tdm-calculator#1223]
## Overview
Since users sometimes don't notice the tooltips for the various fields on the Wizard pages, we want to make some changes to help the users discover the tooltips.

## Actions
- [x] Change the cursor to a pointer when the user hovers over a rule label that is a tooltip on all Wizard Pages.
- [x] Add the box and text as shown in the screenshot below, which only shows up on the first page of the Wizard.

## Resources

![image](https://user-images.githubusercontent.com/9939032/181391188-fa645cb7-9d84-42e8-908c-9cfcb102fbc6.png)

Here is a link to the Figma file page with the mockup: https://docs.google.com/document/d/1CNWYzg_le3b_ncj7_ZeP3YUZumWfbkQ_FKtWUJr9IHU/edit

**Comment by jahpe777** [comment]
Created new component, DiscoverTooltips, and inserted it within ProjectDescriptions

**Comment by entrotech** [comment]
There is a problem with the message box overlapping other page elements on device widths less than about 1200 pixels:

![image](https://user-images.githubusercontent.com/9939032/183701025-c0faebc8-ae6c-4ee5-9819-fc84ca90628a.png)

I realize the app is not really designed to work on narrow devices, but 1200 pixels is a pretty large minimum width for desktop devices.

**Comment by jahpe777** [comment]
Corrected the width issue.
