### ISSUE TITLE
Changes to Page 1 Tooltips

### ISSUE THREAD

**Issue by entrotech** [hackforla/tdm-calculator#1226]
### Overview
Change tooltips for selected fields on Page 1 of Wizard per the Google doc in the Resources below

### Action Items
- [ ] Change tooltips
- [ ] release dependency on #1219 

### Resources/Instructions
(https://docs.google.com/document/d/1CNWYzg_le3b_ncj7_ZeP3YUZumWfbkQ_FKtWUJr9IHU/edit)

**Comment by ExperimentsInHonesty** [comment]
Here is the new wording to use, signed off by Emily
- Project Name
  - The project name should be the way that you refer to the project in conversation.
- Building Permit #
   - If you already have a Building Permit # and can provide it here, it may help reduce staff time when reviewing your materials.
- LADOT Case #
  - If you already have a LADOT Case # and can provide it here, it may help reduce staff time when reviewing your materials.
- City Planning Case #
   - If you already have a Planning Case # and can provide it here, it may help reduce staff time when reviewing your materials.
