### ISSUE TITLE
Create Favicon

### ISSUE THREAD

**Issue by Biuwa** [hackforla/tdm-calculator#1233]
Emily and Alexander said to use the favicon from ladot.lacity.org

https://ladot.lacity.org/sites/default/files/sotvmlfn_400x400.jpg

_Originally posted by @ExperimentsInHonesty in https://github.com/hackforla/tdm-calculator/issues/985#issuecomment-1169372182_

**Comment by entrotech** [comment]
Duplicate of issue #985
