### ISSUE TITLE
Add glossary link to footer on "About" page

### ISSUE THREAD

**Issue by SMR9220** [hackforla/tdm-calculator#1240]
### Overview

We need to mock up adding Glossary links to the Calculator site so that we can get signoff by stakeholder

### Additional info
- This is the design issue for #877 

### Action Items
- [x] Add glossary link to footer, right next to the checklist
- [x] Add glossary link to the additional resources section of the About page
- [ ] Add glossary link to the FAQ page

### Resources/Instructions
Here is the link for the glossary:
https://planning.lacity.org/odocument/c3c9b320-4431-49ff-99d2-15b479c06074/Revised_DRAFT_TDMProgramGuidelines_June2022.pdf/#page=48

**Comment by ExperimentsInHonesty** [comment]
@Reneedesigns 

### Story 1
As a user, I want to be able to lookup a word in the calculator that I don't understand, by clicking on a glossary link, without loosing my place.

#### Details that inform the design choices
The about page is inaccessible when you are in the calculator.  If you are not logged in, you will get the following message when you try to click on the About link. 
![image](https://user-images.githubusercontent.com/37763229/187041453-44bfa87f-9fef-4635-acfb-e866a6fb4c13.png)
So users have to be able to click on the item in the footer, like they can with the checklist.

### Story 2
As a user, I expect to see links to all the City's documents related to TDM all one place.

#### Details
Currently, the about page is where all the city document links are and they are going to remain there.  So a glossary link will need to be added there.

### Story 3
As a user, I want to see a question/answer in the FAQ that says
Q: How can I find out what a term in the Calculator means?
A: Some of the items in the calculator have extra information available.  
Method 1: Try hovering over a term you want more information on. If the words become underlined and bold, you can click for a description. Hovering over a green question mark will also provide more information. 
Method 2: Check out the [Glossary]() which is linked in our footer on every page.

**Comment by Reneedesigns** [comment]
Glossary added to three areas: footer, About page "Additional Resources", and FAQ page as a question @SMR9220 @Biuwa 

https://www.figma.com/file/nD9QK56Mzq7xNSaSUoeGx0/TDM-Calculator?node-id=6814%3A24520



![Glossary added to footer](https://user-images.githubusercontent.com/99779174/187813290-fa23b645-b10c-41de-af35-b6d1c8945a6b.png)




![Glossary added to About resources](https://user-images.githubusercontent.com/99779174/187813317-bd309a7a-37d6-47ec-9115-fce7dab7ac1e.png)



![Glossary on FAQ](https://user-images.githubusercontent.com/99779174/187813330-183ee958-695f-496e-8460-5d6beb8e8743.png)

**Comment by ExperimentsInHonesty** [comment]
Alexander said locations are fine.  Language for question is fine

**Comment by Biuwa** [comment]
@Reneedesigns 
Please make this correction in the FAQ Question where the glossary is linked:

'Check out the TDM Program Guidelines PDF glossary, which is linked in the footer on every page'

**Comment by ExperimentsInHonesty** [comment]
This design for adding Glossary has been accepted by the stakeholder and now need to have a dev issue created

**Comment by Biuwa** [comment]
During the meeting today it was decided that the glossary will link to Page 48 of the [Program Guidelines](https://planning.lacity.org/odocument/c3c9b320-4431-49ff-99d2-15b479c06074/Revised_DRAFT_TDMProgramGuidelines_June2022.pdf)

**Comment by ExperimentsInHonesty** [comment]
The glossary is currently only showing on the dev site 2023-01-28
