### ISSUE TITLE
Create FAQ Content

### ISSUE THREAD

**Issue by Biuwa** [hackforla/tdm-calculator#1241]
### Overview
Come up with questions that will be included in the FAQ screen

### Action Items
- [x] UX research team draft up common questions from user testing
- [x] Review the draft with Bonnie and PM team and make revisions
- [x] Review the draft with stakeholders and get feedback

### Resources/Instructions
- [User testing 2 issue tracker](https://docs.google.com/spreadsheets/d/1SWcf55uRkXV41uCMTp7VLelAslf6rQCGeyCYXfGzbBU/edit?usp=sharing)

**Comment by bkobak33** [comment]
Initial draft of FAQ page drafted by UX Research Team: https://docs.google.com/document/d/1M6ejOzg07wTAz8Y1FXckq6e6NUAz36HKyGRJDn3DBms/edit#heading=h.fpzuqsb8fyps

**Comment by Biuwa** [comment]
**From Jill-9/30/2022** _*Comments from the Google Doc_
I reviewed our consolidated FAQ questions and found that most of them are already answered on well-crafted and well-organized content on the LACP and LADOT websites. 

I propose that it’s better to link to their information, so there’s one place for updates to be made, reducing the burden of re-creating content and managing separate content in multiple locations. 

To this end, I created the Answers to your TDM Questions section and highlighted the content areas most asked about (and stressed out about, feeling uncertain that they didn’t have the answers or know where to find them) during user testing. I chose to use this user perspective as a guide to constrain the list of items bulleted rather than including an exhaustive list, which I feel might overwhelm About page visitors and make it harder for them to find the information they are most likely to be seeking.

I reviewed our list of FAQs, derived from user questions during the user testing process. 
I removed all questions that are already answered in LADOT/LACP links. 
I included the remaining questions in the FAQ section below - all need review by and most need answering by LACP/LADOT.
In this process, I found myself visiting the TDM Calculator with fresh eyes and identifying key information users would need in order to understand the information the calculator provides. Based on this, I created an essential intro guide below of key terms and features in the TDM Calculator in a Getting Started section. 
The “What is the TDM Calculator?” content is from our current About page, so it has been approved.
I tried to use existing content throughout as much as possible to avoid having to re-create content for new review and approval. For example, all of the points and levels info comes from either the lacity.org info or from our existing tooltips. If it’s helpful, I could use a font color for any content that is new (such as the Welcome to the TDM Calculator section).
I removed some of the previous About page content, in an effort to both streamline the content (eg, avoid repeating content already included elsewhere in the About page) and to meet the needs of the users.
I ran out of brain space, so it still needs to be cleaned, but hopefully it provides a helpful organization and approach to content (with almost no burden on reviewing new content). Admittedly there’s some burden on creating new content for the FAQ section unless that can be referenced in additional links or copy/paste from existing answers.

**Comment by Biuwa** [comment]
**Comment from Jill-Sept 30th on the Google Doc**
The name of this linked [document](https://planning.lacity.org/odocument/c3c9b320-4431-49ff-99d2-15b479c06074/Revised_DRAFT_TDMProgramGuidelines_June2022.pdf) is "Transportation Demand Management (TDM) Program Guidelines". When titling things or creating labels, I try to think of the user experience and what will be most clear and helpful to them in identifying what they will find under the link label. To me, the name of the document provides a clearer understanding of what they will find here than the current link label. Was there a reason the link label was chosen to be different than the document name?

**Comment by Biuwa** [comment]
Xander and Emily will be emailed a draft of the FAQ for their review, and we will revisit this issue in the next two meetings to determine whether there have been any updates.

**Comment by SMR9220** [comment]
https://helpx.adobe.com/acrobat/kb/link-html-pdf-page-acrobat.html

This link will help correct the deep linking issue.

**Comment by Biuwa** [comment]
Stakeholders have edited the [TDM FAQ Draft](https://docs.google.com/document/d/1M6ejOzg07wTAz8Y1FXckq6e6NUAz36HKyGRJDn3DBms/edit?usp=sharingt)

**Comment by ExperimentsInHonesty** [comment]
Hey Development team, this content for the FAQ has been collected.  Please make a development issue.  Link it here.  Move this issue to the Done column.

**Comment by ExperimentsInHonesty** [comment]
Alexander will look to see if any links inside the calculator that go to someplace other than LADOT but still inside a city website, need to have an icon indicating external link (similar to about page) .  See website faq for questions https://tdmdev.azurewebsites.net/faqs

See image for which are the related questions
![screencapture-tdmdev-azurewebsites-net-faqs-2022-11-29-16_17_19](https://user-images.githubusercontent.com/37763229/204677065-d12deaf8-6950-4d24-8579-da05d4515d69.png)


https://www.w3.org/WAI/standards-guidelines/wcag/

**Comment by ExperimentsInHonesty** [comment]
Emily shared this link https://planning.lacity.org/resources/open-data which has a link to another city site (the open data portal)  and it does not have the external link icon.
