### ISSUE TITLE
Electric Vehicle Bonus/Electric Transit Vehicle Bonus are selectable at all times

### ISSUE THREAD

**Issue by awikstrom-ladot** [hackforla/tdm-calculator#1243]
### Overview
On pg 4 of the application, if no Car Share strategies have been selected, "Electrical Vehicle Bonus" should be greyed out.

Also, further down on this page, if no Neighborhood Shuttle/Microtransit Service strategies have been selected, "Electrical Transit Vehicle Bonus" should be greyed out.

### Action Items
- [x] If no Car Share strategies have been selected, make "Electrical Vehicle Bonus" text greyed out and unselectable.

- [x] If no Neighborhood Shuttle/Microtransit Service strategies have been selected, make "Electrical Transit Vehicle Bonus" text greyed out and unselectable.
 
### Text Added by Stakeholder on 2022-09-16 Alexander
The EV-related bonuses in Car Share and Transit are currently selectable at all times, which is incorrect. EV Bonus for Car Share should only be selectable if an applicant selects one of the other Car Share strategies. The EV Bonus for Transit should only be selectable if the applicant has selected Neighborhood Shuttle/Microtransit Service.

@entrotech @Dsomers74 @ExperimentsInHonesty 

![EVB](https://user-images.githubusercontent.com/69442669/192912763-5ff861f9-c2ea-486e-8607-3f580ab30d8e.png)
![ETVB](https://user-images.githubusercontent.com/69442669/192912772-f361ea7d-6e73-4bc7-9979-476e8f89661a.png)

**Comment by SMR9220** [comment]
@jahpe777 can you please review this issue, thank you.

**Comment by ExperimentsInHonesty** [comment]
Electrical Vehicle Bonus will be available only if one or more of the following options have been selected:
- Car share parking 
- Car Share Memberships
- Private Car Share Fleet

Care Share bonus is working as expected (it's auto if you choose two or more of the above options).

**Comment by ExperimentsInHonesty** [comment]
Electric Transit Vehicle Bonus should be grayed out and not selectable unless the user has chosen one of the options in the Neighborhood Shuttles/Microtransit Service drop down.

**Comment by jahpe777** [comment]
Updated Electric Vehicle Bonus/Electric Transit Vehicle Bonus #1243
