### ISSUE TITLE
Greyed out enablement text 

### ISSUE THREAD

**Issue by SMR9220** [hackforla/tdm-calculator#1251]
### Action Items
create mock ups for additional text to be added to pre existing tooltips, for strategies that are greyed out 

### Resources/Instructions
[Tooltip edits for greyed out text](https://docs.google.com/document/d/1ctMRX48Q5PHh-5B5WtO3AoLHwNjxwmVOP3W2_ymQYi4/edit)

**Comment by Noushie** [comment]
@SMR9220 @Biuwa

**MOCKUP 1 (SELECTED TO SHOW STAKEHOLDERS AS OF 10/26 MEETING)**

Grey Tool Tip Fix V1.1: User Tooltip Warning Message

**CHANGES MADE**

- Added warning/informational text w/ icon to disabled tooltip

 **MENTIONS**

- According to development (John), to avoid any changes in logic, warning message would be better phrased as "This cannot be selected unless 'Bike Share Station' has been selected" 
 
![Grey Tool Tip Fix V1](https://user-images.githubusercontent.com/115515867/198770161-02195faf-7c31-41a2-8fdf-4bd0d7064ad4.png)

**Comment by Noushie** [comment]
**MOCKUP 2** 

Grey Tooltip Fix V1.2: User Tooltip Warning Message + Highlighted Hover

**CHANGES MADE**

- Added warning/informational text w/ icon to disabled tooltip (same as version 1.1)
- Added highlighted hover of disabled row (to grab user attention)

**MENTIONS**

According to development (John), to avoid any changes in logic, warning message would be better phrased as "This cannot be selected unless 'Bike Share Station' has been selected"

![Grey Tool Tip Fix V1 1](https://user-images.githubusercontent.com/115515867/198777517-3bc4e58d-4b7b-4c1c-9246-946849c04802.png)

**Comment by Noushie** [comment]
**MOCKUP 3** 

Grey Tooltip Fix V2.1: Clickable Information Icon

**CHANGES MADE**

- Added clickable conditional information icon (i.e., only present when text is disabled) to tell user why the option is disabled

**MENTIONS**

Development (John) mentioned they'd rather have the message exist regardless of text being enabled/disabled

![Grey Tool Tip Fix V2](https://user-images.githubusercontent.com/115515867/198780956-6f256307-1bce-409b-b12a-9cc9a6c35cec.png)

**Comment by Noushie** [comment]
**MOCKUP 4**

Grey Tooltip Fix V2.1: Hover Information Icon

**CHANGES MADE**

- Same as version 2.1 (information icon with a side tooltip), but changing user interaction from clicking to hovering over information icon

**MENTIONS**

Development (John) mentioned they'd rather have the message exist regardless of text being enabled/disabled


![Grey Tool Tip Fix V2 1](https://user-images.githubusercontent.com/115515867/198782425-2b0979cf-cb82-419d-941b-68e4fd4c38cf.png)

**Comment by Biuwa** [comment]
All of the edits are available in [Tooltip edits for greyed out text](https://docs.google.com/document/d/1ctMRX48Q5PHh-5B5WtO3AoLHwNjxwmVOP3W2_ymQYi4/edit)
