### ISSUE TITLE
Change AIN# placeholder text after entering a number

### ISSUE THREAD

**Issue by SMR9220** [hackforla/tdm-calculator#1259]
### Overview
After user inputs an AIN number and presses enter to go to the next field, the AIN number textbox still has the "required" placeholder text in it.  See bottom of this comment for a related keyboard input issue.

### Action Items
- [ ] Have the required text change to optional when there is one or more values provided by user in the field.

### Resources/Instructions
Video showing the AIN# placeholder text

https://user-images.githubusercontent.com/92768513/199648225-d665e7d6-6387-427a-9303-ebdf1faf8830.mov

### Related Issues 
- #1110 Keyboard input into text box (this is one of the behaviors that need to be fixed).

**Comment by jarmitageux** [comment]
Here is a video showing the issue.

https://user-images.githubusercontent.com/92768513/199648225-d665e7d6-6387-427a-9303-ebdf1faf8830.mov

**Comment by mojimoh** [comment]
@Jonathanko52, Please provide update before Wednesday:
1. Progress: "What is the current status of your project? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"
5. Pictures (if necessary): "Add any pictures that will help illustrate what you are working on."

**Comment by mojimoh** [comment]
@Jonathanko52 
Please provide update
1. Progress: "What is the current status of your project? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"
5. Pictures (if necessary): "Add any pictures that will help illustrate what you are working on."

**Comment by Jonathanko52** [comment]
Progress: Code complete. Attempting to push changes onto github
Blockers: Authentications issues with Github. Trying to determine if support is necessary, or purely a local issue.
Availability: Open today to resolve the issue.
ETA: Can be resolved by next meeting.
Pictures (if necessary):
