### ISSUE TITLE
Update the User-Facing FAQ Page Implementation to include categories

### ISSUE THREAD

**Issue by entrotech** [hackforla/tdm-calculator#1261]
### Overview
Update the User-Facing FAQ Page Design to include categories

### Action Items
- [x] Decide on, and implement the required database changes. Normally, I would create a separate table FaqCategory and add a foreign key from the Faq table to the FaqCategory table, However, with the way the administration screen for FAQs is intended to work, it might be easier to represent categories as rows in the Faq table with a type of "Header" (vs "Question" for the normal Faqs). Should discuss the options with @entrotech before implementing.
- [x] Modify the screen functionality to incorporate the categories as headers
- [x] Try to match the wireframes provided by Renee under the Resources section.

### Resources/Instructions
Mockup-User Facing FAQ w/categories
https://www.figma.com/file/nD9QK56Mzq7xNSaSUoeGx0/TDM-Calculator?node-id=7089%3A24872

**Comment by Reneedesigns** [comment]
Screenshots: Selected screens per 11/2 team meeting
Categories within banner with questions collapsed and some answers expanded

Figma link to screens
https://www.figma.com/file/nD9QK56Mzq7xNSaSUoeGx0/TDM-Calculator?node-id=7089%3A24872


https://www.figma.com/file/nD9QK56Mzq7xNSaSUoeGx0/TDM-Calculator?node-id=7089%3A24872

https://www.figma.com/file/nD9QK56Mzq7xNSaSUoeGx0/TDM-Calculator?node-id=7089%3A24872

@entrotech @jahpe777  @Biuwa @syria

**Comment by jahpe777** [comment]
Updated the User-Facing FAQ Page Implementation to include categories #1261
