### ISSUE TITLE
Developer II needs access to City's Azure Account

### ISSUE THREAD

**Issue by entrotech** [hackforla/tdm-calculator#1268]
### Overview
At this time, only John Darragh has access to the City's Azure Account for deploying / debugging the deployment of the application to the UAT and Production environments.  In case John is not available, we need to have at least one other person who can support deployment, and James is the developer we are training for this.  Accordingly, he needs to have access to the city Azure account.

### Action Items
- [ ] Create an account for James in Azure
- [ ] Grant him the same access rights that John (should) have.
- [ ] In particular, he requires that his personal IP address be granted direct access to the production and UAT databases.

**Comment by ExperimentsInHonesty** [comment]
### Notes from 2023-01-10 meeting with stakeholder
Alexander is still working out who is the best contact. & Lon will be back in office

**Comment by ExperimentsInHonesty** [comment]
### Notes from 2023-01-10 meeting with stakeholder
- Alexander will follow up with Lon to try to get [TDMApp@lacity.org](mailto:TDMApp@lacity.org) email for the technical email of the project

**Comment by Biuwa** [comment]
01-24-23: Alexander found out [ladot.tdm@lacity.org](mailto:ladot.tdm@lacity.org) and this is a shared email with Alexander or someone else on the team who will have access to answer questions.  We will use 1password to secure the email and be able to do 2FA if required.

**Comment by Biuwa** [comment]
Alexander - added the password to the vault and set up 2 factor authentication

**Comment by Biuwa** [comment]
We are trying to get Jacob Rhodes' access
