### ISSUE TITLE
Create Accessible and Reusable Modal Dialog Component and Refactor Existing Dialogs to Use It

### ISSUE THREAD

**Issue by entrotech** [hackforla/tdm-calculator#1282]
### Overview
We need to use a common dialog component for implementing modal dialogs in the application in order to reduce duplicate code and ensure consistency in the look and feel of the various dialogs. Currently, there are several modal dialogs in the application, each of them implemented independently, with differing behavior and styles.

### Action Items
- [ ] Create the common dialog component.  The behavior should be:
  - Auto-focus on the first focusable body element when the modal is opened.
  - Trap focus on the modal so that it doesn't leave the modal elements until the modal is closed.
  - The Escape key should close the modal without taking any action.
  - The Enter key should have standard behavior (i.e., if a button has focus, clicking the button)
  - Standardize the appearance of the Header's close button.
- [ ] Use it to replace the Project Delete dialog
- [ ] Replace the "Leave the Project Wizard" Dialog, 
- [ ] Replace the Delete FAQ dialog, 

### Resources/Instructions
See https://medium.com/@seif_ghezala/how-to-create-an-accessible-react-modal-5b87e6a27503 for a good implementation.

Examples:
Checklist Modal Dialog:
![image](https://user-images.githubusercontent.com/9939032/205175629-db191b8e-9a1a-4e8b-b225-e1362ed15f31.png)

Leave the project Wizard Dialog:
![image](https://user-images.githubusercontent.com/9939032/205175826-4d778f92-9ceb-4fc9-8e4e-d0bf11492ec4.png)

Delete Project Dialog:
![image](https://user-images.githubusercontent.com/9939032/205175995-cd07c83e-afc9-4c71-8143-050264fb7663.png)

Terms and Conditions Dialog
![image](https://user-images.githubusercontent.com/9939032/205176164-7ad21d2e-9531-4cd9-9439-286251489854.png)

**Comment by Biuwa** [comment]
@Jonathanko52

Please provide update

Progress: "What is the current status of your project? What have you completed and what is left to do?"
Blockers: "Difficulties or errors encountered."
Availability: "How much time will you have this week to work on this issue?"
ETA: "When do you expect this issue to be completed?"
Pictures (if necessary): "Add any pictures that will help illustrate what you are working on."

**Comment by Jonathanko52** [comment]
Progress: Two of eight modals replaced on my local repository. 
Blockers: I'd like to run my current plans for how functions/icons/other data in modals should be stored in the app
Availability: Limited in the coming weeks. I can probably reply to slack messages.
ETA: Two weeks.
Pictures (if necessary):

**Comment by Jonathanko52** [comment]
Progress: Four of eight modals replaced on my local repository. Modals have been modified to take in functions and open/close state as props from parent components.
Blockers: None.
Availability: Limited in the coming weeks. I can probably reply to slack messages.
ETA: Two weeks.
Pictures (if necessary):

**Comment by Biuwa** [comment]
@Jonathanko52 Please provide an update.

**Comment by Jonathanko52** [comment]
Progress: Added the ability for Modal to take components as props, which is used for some other modals in the project that have extensive text. Now working on The last two Modals, duplicate and delete project.
Blockers: None.
Availability: Limited in the coming weeks. I can probably reply to slack messages.
ETA: One week
Pictures (if necessary):

**Comment by Jonathanko52** [comment]
Progress: "Duplicate" modal now able to make duplicates. I still have to add the ability to change titles. That aside, that leaves the "Delete" Modal
Blockers: None.
Availability: Weekdays.
ETA: End of week
Pictures (if necessary):

**Comment by Jonathanko52** [comment]
Progress: Inapplicable, Navconfirm, DeleteProject, Duplicate, Terms and Conditions, and Checklist Modals replaced. Trap focus to Modal function added.
Blockers: None.
Availability: Weekdays.
ETA: Code complete. Ready for testing/review.
Pictures (if necessary):

**Comment by Jonathanko52** [comment]
Progress: Code cleanup. Enter now standardized to activate in-focus item. Colors added for delete, duplicate, and terms and conditions buttons
Blockers: None.
Availability: Weekdays.
ETA: 
Pictures (if necessary):

**Comment by Biuwa** [comment]
@entrotech - Please review
