### ISSUE TITLE
Notification warning box for deselecting inapplicable strategies after project specification changes

### ISSUE THREAD

**Issue by Biuwa** [hackforla/tdm-calculator#1289]
### Overview
We need a design of what the notification warning box will look like for de-selecting inapplicable strategies as soon as they become inapplicable due to changes made on pages 2 and 3.

### Action Items
- [x] Design Mockups warning the users about strategy changes after making changes to project specifications on Pages 1-3
- [x] Stakeholders review the tooltip

### Resources/Instructions
-#1265
-#1284
-#1285

**Comment by Biuwa** [comment]
Emily and Alexander want the following wording for the warning message:

'If you change your project specifications, any TDM Strategies that you have selected will be removed if they are no longer applicable'

**Comment by Biuwa** [comment]
John suggested this warning message for the box:

"Due to changes made to the project specifications, one or more TDM strategies are no longer applicable and have been automatically de-selected."

**Comment by Noushie** [comment]
Mockup 1 (12/20):

@Biuwa 

![image](https://user-images.githubusercontent.com/115515867/209065587-6b0430f8-fa89-40b9-a716-9ea70123a018.png)


- Drive attention to users as a warning with the same format as our current warning box

- Have the pop-up with the warning icon and no way to close out except for the 'Okay, I understand" and I went with our core green, as it is associated with agreeing/yes

- I think a descriptive title would be helpful here, just to ensure users know why the pop-up is coming up

- I didn't come up with a bunch of other ideas to limit changes from the original warning box but I was also thinking it could be just the sentence + CTA button (i.e., "I understand," "okay, I understand," etc.)

Potential idea:
I was also thinking of maybe having a timed interaction where the CTA is disabled for maybe 5 seconds, which prompts users to read before clicking anything -> not sure from a dev perspective though

**Comment by Noushie** [comment]
**Mockup 2 (12/20):**

- Having the CTA gray might also be less distracting (maybe users won't be drawn automatically to select it and may be more likely to read the full message)

- I also removed the titling to show how it would appear with only the message (which I noticed it's not as clear as to what the pop-up is for - but that's only my observation)

![image](https://user-images.githubusercontent.com/115515867/209065634-d7e96b1d-739c-47cf-98a4-1d9f4f799dc1.png)

**Comment by Noushie** [comment]
[Link to Figma File - Found under #1289 Notification Warning](https://www.figma.com/file/nD9QK56Mzq7xNSaSUoeGx0/TDM-Calculator?node-id=3331%3A11985&t=a5GWBVZjNF5wYa4H-1)

**Comment by Biuwa** [comment]
Mockup 2 was chosen by the team.

**Comment by Biuwa** [comment]
@Noushie a dropdown shadow should be added to the warning box so it is consistent with the other warning boxes

**Comment by Biuwa** [comment]
https://user-images.githubusercontent.com/98936028/216880190-ac7aa66e-06a6-44e0-acfd-4cf642de6b04.mov
