### ISSUE TITLE
Package Bonus: Bug: Display partially hidden

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/tdm-calculator#1296]
### Overview
We need to fix the display being cut off when using bonus packages so that people can see the points, and which package applies, as well as access the tooltip (if any)

### Action Items
- [x] Replicate the error
- [x] decide next steps

### Resources/Instructions
https://tdmdev.azurewebsites.net/
Browser: Chrome Version 108.0.5359.125 (Official Build) (64-bit)

#### Example of problem
![image](https://user-images.githubusercontent.com/37763229/211581784-a4eba642-6e19-4a93-8010-9a4cc821fdb7.png)

#### To replicate, use these selections
![image](https://user-images.githubusercontent.com/37763229/211582208-90534386-c1f2-4239-a9d9-f5f15a48066e.png)

![image](https://user-images.githubusercontent.com/37763229/211582124-b09a0796-e1e7-458b-b0f2-9aa3b83136a1.png)

**Comment by entrotech** [comment]
@ExperimentsInHonesty I am not able to replicate this problem in dev or production.  With the parameters you entered, it would be a Level 2 project, for which packages are not applicable, and the entire Package Bonus section should not appear on the Strategies page at all. This is what happens for me in both environments. 

If your screen shot is from a recent version of the app, there might be an edge case of some sort involving jumping back and forth between pages that leaves part of the Package Bonus section visible. If the above screen shot included the sidepanel, we would be able to see what the Project Level is and the strategies selected, which might help reproduce the issue.

**Comment by entrotech** [comment]
The issue was that the conditional logic for hiding the package Bonus Section did not account for Level 1 Projects that were not eligible for Package Bonuses because the provided parking exceeded 110% of baseline.
