### ISSUE TITLE
Light Mode UPDATE

### ISSUE THREAD

**Issue by Noushie** [hackforla/tdm-calculator#1302]

**Comment by mojimoh** [comment]
@Noushie Please fill out the necessary indicated at the top of this issue


>  ### Dependencies
> ANY ISSUE NUMBERS THAT ARE BLOCKERS OR OTHER REASONS WHY THIS WOULD LIVE IN THE ICEBOX
> 
> ### Overview
> WE NEED TO DO X FOR Y REASON
> 
> ### Action Items
> A STEP BY STEP LIST OF ALL THE TASK ITEMS THAT YOU CAN THINK OF NOW EXAMPLES INCLUDE: Research, reporting, etc.
> 
> ### Resources/Instructions
> REPLACE THIS TEXT -If there is a website which has documentation that helps with this issue provide the link(s) here.
