### ISSUE TITLE
Implement a Warning Box when User Deletes FAQ

### ISSUE THREAD

**Issue by entrotech** [hackforla/tdm-calculator#1304]
### Overview

- Dependency on Dev Issue #1305 since there is nowhere to put this dialog until the delete function is implemented.
- Implementation of Issue #1279. When the user elects to delete a question, show them a modal confirmation dialog that warns them that the question will be deleted permanently, as shown in the wireframe on Issue #1279.

### Action Items
- [ ] Implement.

**Comment by ExperimentsInHonesty** [comment]
- This has been addressed in #1305
