### ISSUE TITLE
Design Mockup: Adding temporary text to pg 5

### ISSUE THREAD

**Issue by mojimoh** [hackforla/tdm-calculator#1313]
### Overview
We need a temporary language added to the calculation summary page until we create a download/print feature.

### Action Items

- [ ] Create a mockup of pg 5 that displays the following: "The ordinances behind this TDM calculator are still in public comment. No submission is possible at this time."

### Resources/Instructions
N/A

**Comment by Noushie** [comment]
@jamiedesignedit is completing this:

We also wanted to mention that we are making some typography/box style edits (which we will annotate), just so this page better matches up to the rest of the website pages (as we spoke about this before in a meeting from a couple weeks ago). 

I can create another issue for this, but we are hoping dev can also make the cosmetic changes simultaneously!

**Comment by jamiedesignedit** [comment]
Made updates to existing pg. 5, including adding the message "The ordinances behind this TDM calculator are still in public comment. No submission is possible at this time."  I also made typography updates according to our new design system and worked on the visual hierarchy.  

Will present two option for feedback at our next meeting, one red filled in box and one red outline.

<img width="989" alt="Screenshot 2023-02-06 at 7 21 06 PM" src="https://user-images.githubusercontent.com/114036754/217140867-992fd5f5-e313-424f-86ec-1488b88480a4.png">

**Comment by mojimoh** [comment]
@jamiedesignedit the PMs decided on option 2, because as mentioned the language is placed where the user might go to find a submit button and the fill-in for the target points is not optimal for printing. 
@entrotech please advise when this can be implemented

**Comment by IMHieuVo** [comment]
@jamiedesignedit I created a page in the Dev Hand-Off section for the Dev Team. They requested notes for the changes between the original and the new design so I dropped in the Original wireframe and added some notes on the side. Feel free to add additional notes. 

@entrotech The Figma file location: 
[](https://www.figma.com/file/nD9QK56Mzq7xNSaSUoeGx0/TDM-Calculator?node-id=4041%3A12651)
