### ISSUE TITLE
Design Mockup: TDM Calculation Summary Print out

### ISSUE THREAD

**Issue by mojimoh** [hackforla/tdm-calculator#1314]
### Overview
We need to create the button and PDF output for printing/downloading the TDM Calculation Summary

### Action Items

- [x] Create a mockup of a download button for the TDM calculation summary page
- [x] Create a mockup of PDF of the TDM calculation summary results

### Resources/Instructions
[Figma](https://www.figma.com/file/nD9QK56Mzq7xNSaSUoeGx0/TDM-Calculator?t=zXTqXwyu8zAgi1aK-0)
[LADOT Style guide](https://drive.google.com/file/d/1SDdPrNUxcw6tnaLWcZ1CpoOn4raKSGkY/view)
- See #1140 for additional context

**Comment by mojimoh** [comment]
@edela0015 and @IMHieuVo 
Please provide update
1. Progress: "What is the current status of your project? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"
5. Pictures (if necessary): "Add any pictures that will help illustrate what you are working on."

**Comment by edela0015** [comment]
Progress: Action Item 1 complete.


Blockers: Take into account buttons present in logged in accounts (save progress button)
Availability: weekend
ETA: Next meeting

**Comment by edela0015** [comment]
Link to progress: 

https://www.figma.com/file/nD9QK56Mzq7xNSaSUoeGx0/TDM-Calculator?node-id=8402%3A18257&t=4dXAKqxUprOYhGkX-0

**Comment by IMHieuVo** [comment]
Progress: Mockups have been revised.
Blockers: During the meeting, it was noted that Guest Users do not have a "Save Project" option while an Account User does. The design team decided to have the Navigational Buttons and the Action Buttons on the same lines.
Availability: 1-2 hours on weekdays prior to the team meeting on Wednesday 3/1.

Link to Figma: https://www.figma.com/file/nD9QK56Mzq7xNSaSUoeGx0/TDM-Calculator?node-id=8474%3A18548&t=WUDUb0l4J8oqbDOx-1

**1. Screenshot of an Account User screen with the "save project" button**.
![Screenshot 01](https://user-images.githubusercontent.com/117132709/221447033-29c386b2-9d31-4a90-863b-8508f9f409ac.png)

**2. Mockup of Guest User screen with the Download Summary button**.
![CP Page- Guest User](https://user-images.githubusercontent.com/117132709/221446960-e2804148-7d81-4d39-897f-9f0f416949d1.png)

**3. Mockup of an Account User screen with the Download Summary button and Save Project button**.
![CP Page- Account User](https://user-images.githubusercontent.com/117132709/221446979-b7939121-c8b5-451d-bcdf-c7fda21bfdba.png)

4. **Mockup of a single-page PDF summary**.
![PDF Printout Single Page](https://user-images.githubusercontent.com/117132709/221446936-6a55f750-53ed-4ca1-a1bb-a82c5c808d06.png)


**5. Mockup of a double-page PDF summary**.
![PDF Printout Double Page (1 of 2)](https://user-images.githubusercontent.com/117132709/221446916-5a889d46-52e0-45d8-a09e-43993f174082.png)
![PDF Printout Double Page (2 of 2)](https://user-images.githubusercontent.com/117132709/221446908-750db286-fbc5-4ddd-835f-cf44ed6db292.png)

**Comment by mojimoh** [comment]
PM Feedback on PDF Mockups:
- Could you consider how the information could be displayed if there were no development limitations?
  - Can the PDF design more effectively communicate the summary information from the TDM calculator onto an 8.5" x 11" sheet of paper?   
  - Ie in the single page mock-up provided there are 4 times that information about parking is presented, could there be a better way to display the information since it results in the repeat of information?
 - for the project level, can that be elevated to the top to where the Point Summary is located?

**Comment by IMHieuVo** [comment]
My understanding of the print-to-pdf function is that it prints the selected website information onto the 8.5" x 11" PDF. To mockup a PDF that is different from the website or not within development limitations is a misrepresentation and I would advise against showing that to the stakeholders. If the summary information is not clear, we will need technical guidance from someone that uses TDM on how best to organize it. 

Perhaps the previous mockup is confusing. I've updated the mockup:
- On the server, the information on the sidebar (Project Level and Earned-Target bubble) is printed above the summary. Perhaps we take the Project Level from the sidebar instead of moving it from the project detail.
- The repeated information were placeholders, I have updated it be actual headings.

![PDF Printout Double Page (1 of 2)](https://user-images.githubusercontent.com/117132709/222097137-989a9951-4c47-4163-a307-5ec520c0c32c.png)
![PDF Printout Double Page (2 of 2)](https://user-images.githubusercontent.com/117132709/222097154-10013b1f-43a0-495b-8677-92157f978630.png)

**Comment by ExperimentsInHonesty** [comment]
![image](https://user-images.githubusercontent.com/37763229/222922832-17f2cc2c-44c0-401a-8c26-f84dbcf05e04.png)

**Comment by IMHieuVo** [comment]
Per Bonnie's markup, I have revised the PDF printout (using placeholder information). I've also applied the same markup just to see what it would look like.

Figma Link: https://www.figma.com/file/nD9QK56Mzq7xNSaSUoeGx0/TDM-Calculator?node-id=8695%3A19122&t=m6boBcK4K5PuUGL4-1

PDF Printout Page 1
![PDF Printout Double Page V3 (1 of 2)](https://user-images.githubusercontent.com/117132709/225426963-297c28f3-adea-4a31-b957-ee8acfaf1421.png)

PDF Printout Page 2
![PDF Printout Double Page V3 (2 of 2)](https://user-images.githubusercontent.com/117132709/225427053-3a0294ad-7842-49bd-aaf2-c2899b90c3df.png)

Website Page in the same ordering
![CP Page- Account User - 23 03 15](https://user-images.githubusercontent.com/117132709/225427114-7b45a3b2-8e11-4c2f-94d7-98a3edeba902.png)

**Comment by Biuwa** [comment]
@IMHieuVo On the Dev site, we have several test cases saved. We wanted you to use one of them.

**Comment by IMHieuVo** [comment]
@Biuwa Please clarify.

1. Is the Dev site you're referring to https://tdmdev.azurewebsites.net/ ?
2. The login for the website above
   - AndyD: It looks like it is only used for testing.
   - Admin User: Does not work.
   - Security Admin: Does not work.
3. The 1Password I signed up for has nothing shared with me.

**Comment by ExperimentsInHonesty** [comment]
Document requirements see the [Header and Footer requirements](https://docs.google.com/document/d/1qtt8OVI1Fj27u5MHVSrg6QbNHYKYKaeQamGxvgqiYBo/edit#) document for details

**Comment by Biuwa** [comment]
> 1. Is the Dev site you're referring to https://tdmdev.azurewebsites.net/ ? Yes it is
> 2. The login for the website above
>    
>    * AndyD: It looks like it is only used for testing.
>    * Admin User: Does not work.
>    * Security Admin: Does not work.
> 3. The 1Password I signed up for has nothing shared with me: I'll be sharing the login deets with you on slack, 

Meanwhile, Bonnie left a comment above with a detailed Doc of how the header and footer of the mockup should look and we ought to ad the LADOT logo to the page as well

**Comment by IMHieuVo** [comment]
@ExperimentsInHonesty @Biuwa 

Please grant access to the Header and Foot requirements when you have the chance.

**Comment by IMHieuVo** [comment]
@ExperimentsInHonesty @Biuwa

Here are the revised Website and PDF Printout mockup with the Case Study information.
Figma Link: https://www.figma.com/file/nD9QK56Mzq7xNSaSUoeGx0/TDM-Calculator?node-id=8743%3A19461&t=MbHVDJBf6heEYVYj-1 

Test Case 1 - Website
![Test Case 1 - Website](https://user-images.githubusercontent.com/117132709/226831997-590425c3-ba2f-43fa-8722-5c86131bc89a.png)

Test Case 1 - PDF Printout
![Test Case 1 - PDF Printout](https://user-images.githubusercontent.com/117132709/226832007-f68ddf6f-3882-4e07-879e-a139126f4ed8.png)

Test Case 2 - Website
![Test Case 2 - Website](https://user-images.githubusercontent.com/117132709/226832015-00ef47e4-3842-416f-a7eb-afd3884f9303.png)

Test Case 2 - PDF Printout
![Test Case 2 - PDF Printout](https://user-images.githubusercontent.com/117132709/226832030-f9fb6679-ffe8-4949-8a2a-4680cf64f53b.png)

Test Case 3 - Website
![Test Case 3 - Website](https://user-images.githubusercontent.com/117132709/226832046-d73709a4-1ca0-4e58-9238-706f8bcc2552.png)

Test Case 3 - PDF Printout
![Test Case 3 - PDF Printout](https://user-images.githubusercontent.com/117132709/226832063-3a8a52cd-9f4e-4236-9b35-bcc25e94685d.png)

Test Case 4 - Website
![Test Case 4 - Website](https://user-images.githubusercontent.com/117132709/226832083-6b683cc4-77cf-4673-9e8d-3d194d64f98b.png)

Test Case 4 - PDF Printout
![Test Case 4 - PDF Printout](https://user-images.githubusercontent.com/117132709/226832131-5cf89041-9f2e-4689-b513-6ae8e7ec19ca.png)

Test Case 5 - Website
![Test Case 5 - Website](https://user-images.githubusercontent.com/117132709/226832137-359a343a-4b8c-41bc-aa09-02ba47faae2c.png)

Test Case 5 - PDF Printout
![Test Case 5 - PDF Printout](https://user-images.githubusercontent.com/117132709/226832154-c9eea07c-b23a-45bb-871d-a0270c21047c.png)

Test Case 6 - Website
![Test Case 6 - Website](https://user-images.githubusercontent.com/117132709/226832639-a2d06922-4d94-47a9-93cf-eb12175fe8ad.png)

Test Case 6 - PDF Printout
![Test Case 6 - PDF Printout](https://user-images.githubusercontent.com/117132709/226832663-70ecaebd-de2d-4d64-8808-4fbbe3f98e94.png)

**Comment by ExperimentsInHonesty** [comment]
We need to ask the stakeholders what they want in terms of log and header on the documents.  There does not seem to be a lot of consistency throughout their docs.  See the following

## Headers
### [Proposed Ordinances and Initiatives](https://planning.lacity.org/odocument/c3c9b320-4431-49ff-99d2-15b479c06074/Revised_DRAFT_TDMProgramGuidelines_June2022.pdf)
<details>
<summary>Different First page</summary>

![image](https://user-images.githubusercontent.com/37763229/227732429-015df55b-b506-4da7-99f5-318fb9b599c7.png)

</details>
<details>
<summary>Top of every other page</summary>

![image](https://user-images.githubusercontent.com/37763229/227732476-7a0c02d8-33a4-4a25-a673-5822415b2529.png)

</details>

[Fact Sheet - English (January 2021)](https://planning.lacity.org/odocument/d7e3780b-3155-44a4-98cf-0fd673a6612b/TDM-FactSheet_English.pdf)
<details>
<summary>Different First page</summary>

![image](https://user-images.githubusercontent.com/37763229/227732560-d2d9c62e-bce6-4013-b751-c87c6087f81d.png)
</details>
<details>
<summary>Top of every other page</summary>

![image](https://user-images.githubusercontent.com/37763229/227732604-f03be5dc-1d20-4487-918b-1cee5b0e7ba4.png)


</details>


## Footers

**Comment by ExperimentsInHonesty** [comment]
Potential Footer could be

Date last saved: 2023-03-04                
Date Last Printed: 2023-03-21
<hr>
Los Angeles Department of Transportation | tdm.ladot.lacity.org | LADOT.TDN@lacity.org                 Page 1 of 2

**Comment by ExperimentsInHonesty** [comment]
Footer option 2

Date last saved: 2023-03-04&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;     Date Last Printed: 2023-03-21
<hr>
Los Angeles Department of Transportation | tdm.ladot.lacity.org | LADOT.TDN@lacity.org                 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Page 1 of 2

**Comment by ExperimentsInHonesty** [comment]
# Create new issue to
```
### Overview
We need to know what Header Footer design options have been used in public facing PDFs that LADOT and LACP have produced in the past, so that we can help our stakeholders choose which already approved design to use for the Summary PDF.

### Action Items
- [ ] Gather screenshots of Headers and Footers across LADOT and LACP
   - [ ] Search the [LADOT website on Google for PDFs](https://www.google.com/search?q=site%3Ahttps%3A%2F%2Fladot.lacity.org+pdf&oq=site%3Ahttps%3A%2F%2Fladot.lacity.org+pdf&aqs=chrome..69i57j69i58.7574j0j4&sourceid=chrome&ie=UTF-8#ip=1)
   - [ ] Search the [LACP website on Google for PDFs](https://www.google.com/search?q=site%3Ahttps%3A%2F%2Fplanning.lacity.org%2F+pdf&ei=EDEfZJ-YFNTgkPIP45-DuAI&ved=0ahUKEwif4J2Tz_f9AhVUMEQIHePPACcQ4dUDCBA&uact=5&oq=site%3Ahttps%3A%2F%2Fplanning.lacity.org%2F+pdf&gs_lcp=Cgxnd3Mtd2l6LXNlcnAQA0oECEEYAVDA-AFYwPgBYPSPAmgCcAB4AIABL4gBVJIBATKYAQCgAQKgAQHAAQE&sclient=gws-wiz-serp)
- [ ] Adding them to a new Figma page
- [ ] Summarize findings by creating slide deck pages for our 2xMonthly stakeholder meetings.

### Resources
- [Template slide deck](https://docs.google.com/presentation/d/1g9EZKIKhOGT7pimf9TQjEjK_PbnHg8ZbeB054GNZUrw/edit?usp=sharing)
- [LADOT Style guide](https://drive.google.com/file/d/1SDdPrNUxcw6tnaLWcZ1CpoOn4raKSGkY/view)
```

**Comment by ExperimentsInHonesty** [comment]
Potential Header
![image](https://user-images.githubusercontent.com/37763229/227734596-d7e76675-18e5-4f36-8352-a5f124e111a7.png) | TDM Calculation Summary

**Comment by ExperimentsInHonesty** [comment]
- [ ] Use this base format
<img src="https://user-images.githubusercontent.com/117132709/227092235-72819490-b714-47c0-98b4-4d2c0c4996ea.png" width=300px alt="Test Case 1 - PDF Printout">
- [ ] Change out header to use LOGO | Title
- [ ] Change out footer to use Footer 1
- [ ] Make a copy, and use footer 2

**Comment by IMHieuVo** [comment]
@Biuwa 

Prinout has been updated to use the Logo header and the (2) different types of footer.
Figma File: https://www.figma.com/file/nD9QK56Mzq7xNSaSUoeGx0/TDM-Calculator?node-id=4586%3A16931&t=Lc6upoZ5CG8p3try-1 

With Foot Type 1
![Test Case 1 - Footer Type 1](https://user-images.githubusercontent.com/117132709/229042615-26e68153-d287-4712-baf5-8eaafbbfe4ce.png)

With Footer Type 2
![Test Case 1 - Footer Type 2](https://user-images.githubusercontent.com/117132709/229042677-c5b98937-cd82-48ae-86a0-955e3d089fe4.png)

**Comment by ExperimentsInHonesty** [comment]
@Noushie I made a typo, and then you made the design mockups I asked for, and it included my typo.  Please revise the mockups  
changing TDN to TDM
`LADOT.TDN@lacity.org`
to
`LADOT.TDM@lacity.org`

Also, please change the title.  I am sorry I was not clear with my change before.  I just meant for you to change the layout of the title, not the font size.  Please make the title of the page larger and bolder, like you had it before.  Something like this
![image](https://user-images.githubusercontent.com/37763229/229309862-5d246800-fe74-4e34-b9f4-2de8d2b65f79.png)



@Biuwa, after she makes the new mockups I will replace the images on slides 8 and 9

**Comment by Biuwa** [comment]
> @Noushie I made a typo, and then you made the design mockups I asked for, and it included my typo. Please revise the mockups changing TDN to TDM `LADOT.TDN@lacity.org` to `LADOT.TDM@lacity.org`
> 
> Also, please change the title. I am sorry I was not clear with my change before. I just meant for you to change the layout of the title, not the font size. Please make the title of the page larger and bolder, like you had it before. Something like this ![image](https://user-images.githubusercontent.com/37763229/229309862-5d246800-fe74-4e34-b9f4-2de8d2b65f79.png)
> 
> @Biuwa, after she makes the new mockups I will replace the images on slides 8 and 9

@IMHieuVo, please review the above comment and make corrections. Thank you.

**Comment by IMHieuVo** [comment]
@Biuwa 

Updated.

Type 1:
![Test Case 1 - Footer Type 1](https://user-images.githubusercontent.com/117132709/229337267-b5d845f7-9631-4222-8e1d-eb183e2a9a90.png)


Type 2:
![Test Case 1 - Footer Type 2](https://user-images.githubusercontent.com/117132709/229337272-284b7399-a263-48be-b422-f332dbf2dd9a.png)

**Comment by Biuwa** [comment]
@IMHieuVo 

Feedback from Stakeholders' meeting: 2023-04-04.
- [ ] Change page title from `TDM Calculation Summary` to `TDM Calculator Project Summary`
- [ ] Increase the font to take the entire width of the page
- [ ] Change `Results for Projects` to `Project Name`
Footer Option:
- [ ] Stakeholders' preferred the Type 1 footer option and want a timestamp added beside the date in a 24hr clock format (00:00:00) Pacific Time.
- [ ] Change `Date last printed` to `Date Printed`

**Comment by IMHieuVo** [comment]
@Biuwa 

Below is the mockup per the stakeholder's comments. 
Figma file: https://www.figma.com/file/nD9QK56Mzq7xNSaSUoeGx0/TDM-Calculator?node-id=4586%3A16931&t=fYW63sgj4E9ItZsx-1

Version 1 has time labeled as PDT. 
![Test Case 1 - PDT](https://user-images.githubusercontent.com/117132709/231081665-e566df65-07a9-4bd6-98ea-15ea68433fcc.png)

Version 2 has time labeled as Pacific Time.
![Test Case 1 - Pacific Time](https://user-images.githubusercontent.com/117132709/231081676-c7ad2b43-860b-4ea5-aa86-d8ab8e7762d8.png)

**Comment by Biuwa** [comment]
@IMHieuVo - Please change the title to TDM `Calculator` Project Summary

and the PDT time format to `PT`

**Comment by IMHieuVo** [comment]
@Biuwa 

The revised mockup is below:
- updated title to : TDM Calculator Project Summary
- time format to be PT

![Test Case 1 - PT](https://user-images.githubusercontent.com/117132709/232658363-2bfa973c-4866-4b17-8b2a-3f56f7becda1.png)

**Comment by Biuwa** [comment]
@IMHieuVo 

### Feedback from Stakeholders' meeting: 2023-04-18

They preferred the Pacific Time option.

![image](https://user-images.githubusercontent.com/98936028/233152620-0b4c715f-6e82-4edc-a664-ea5833a61149.png)

**Comment by entrotech** [comment]
@Biuwa This can be closed, if Issue #1363 adequately describes the desired changes.

**Comment by Biuwa** [comment]
**2023-06-13 Stakeholders Meeting feedback:**

Change the `DOWNLOAD SUMMARY` button to `PRINT SUMMARY`


<img width="1710" alt="Screenshot 2023-06-14 at 8 31 42 PM" src="https://github.com/hackforla/tdm-calculator/assets/98936028/9aa27b75-a8e2-44be-8b0d-d0f31a390181">

**Comment by jahpe777** [comment]
@Biuwa this update will be carried out within issue #1363
