### ISSUE TITLE
Implement Changes to Summary Page

### ISSUE THREAD

**Issue by Jonathanko52** [hackforla/tdm-calculator#1329]
### Overview
- Implement changes to summary page described in issue #1313
- Use option 2 [here](https://github.com/hackforla/tdm-calculator/issues/1313)

### Action Items

- [x] Confer with Jamie on what changes are being made.
- [x] 1. Action 1
- [x] 2. Action 2
- [x] 3. Action 3

### Resources/Instructions
Figma[ link](URL)
Issue [Link](url)

**Comment by mojimoh** [comment]
@Jonathanko52 
Please provide update
1. Progress: "What is the current status of your project? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"
5. Pictures (if necessary): "Add any pictures that will help illustrate what you are working on."

**Comment by Jonathanko52** [comment]
1. Progress: Changes are completed on my machine. Having issues committing. Will work with Jon to resolve this.
2. Blockers:  Issues with committing code:

  .husky/pre-commit: line 4: lerna: command not found
  husky - pre-commit hook exited with code 127 (error)
  husky - command not found in PATH=/usr/local/git/libexec/git-core:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/share/dotnet:~/.dotnet/tools
3.Availability:  6pm Wednesday. 
4. ETA: Compeleted by next meeting 3/8
Pictures (if necessary): "Add any pictures that will help illustrate what you are working on."

**Comment by Jonathanko52** [comment]
"Typography" issues are turning out problematic. Font families defined in the Figma don't seem to match up with the CSS. i.e. Headers in the figma appear to be have changed to "Calibri" in the new figma model, but actually entering that value appears to produce drastically different results

Image from TDM

<img width="563" alt="Screen Shot 2023-03-08 at 9 14 05 PM" src="https://user-images.githubusercontent.com/30099154/223927176-37ad396b-5414-4870-9cfa-25933eda8e3a.png">

From Figma:
<img width="678" alt="Screen Shot 2023-03-08 at 9 12 08 PM" src="https://user-images.githubusercontent.com/30099154/223927204-20d1d32f-30d7-47be-bd08-ed1430196512.png">


There seems to be issues with the Font Weight and Family
