### ISSUE TITLE
Bug: If Checklist has been dismissed, it still "flashes" for a second before disappearing

### ISSUE THREAD

**Issue by entrotech** [hackforla/tdm-calculator#1332]
### Overview
The checklist should be shown the first time that a user visits the site. After they dismiss it, it should not be shown on subsequent visits to the site until the user selects the checklist link in the footer. Currently, when the user re-visits the site, the checklist will show for a few seconds before being hidden - this is what we want stop.

### Action Items
- [x] fix

**Comment by mojimoh** [comment]
@jahpe777 
Please provide update
1. Progress: "What is the current status of your project? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"
5. Pictures (if necessary): "Add any pictures that will help illustrate what you are working on."

**Comment by jahpe777** [comment]
Fixed checklist rendered after dismissed
