### ISSUE TITLE
Tooltip Changes

### ISSUE THREAD

**Issue by Biuwa** [hackforla/tdm-calculator#1336]
### Overview
We need to edit the Affordable Housing Tooltips to include new language from the stakeholders.

### Action Items
- [x] Remove "20% of" preceding the 1st option in the drop-down [20% of State Density Bonus]
- [x] Revise the 1st definition of the tooltip to say “N/A: Projects that do not meet any of the criteria below”
- [x] Change the wording of the 2nd definition of tooltip to say “State Density Bonus: Projects that receive at least 20% of California’s Density Bonus and provide a minimum of:”

### Resources/Instructions
<img width="764" alt="Screenshot 2023-03-08 at 1 13 11 PM" src="https://user-images.githubusercontent.com/98936028/223795802-dc28d816-76b1-4b5e-815d-57f091fd2b40.png">

<img width="923" alt="Screenshot 2023-03-08 at 1 10 21 PM" src="https://user-images.githubusercontent.com/98936028/223795263-146b4c25-74d4-4749-b647-a3786fb5bc8b.png">

**Comment by jahpe777** [comment]
Updated Affordable Housing Tooltips
