### ISSUE TITLE
User Testing for Reset Button

### ISSUE THREAD

**Issue by Biuwa** [hackforla/tdm-calculator#1344]
### Dependency
- Issue to finish documenting the last round of user research
### Overview
we need to conduct User Testing (dog fooding) that will make users focus mainly on the interaction with the reset button.

### Action Items
- [x] Create Research Plan
   - [x] Get Research Plan approved by PMs
- [x] Create Questions for the user testing
   - [x] Run proposed User Testing questions by PMs
- [x] User Test 
   - [x] Conduct UXR Team Training
   - [x] Recruit Interviewees 
   - [x] Schedule Interviews
   - [x] Conduct Interviews
- [x] Data Analysis
   - [x] FigJam 
- [x] Provide Feedback
   - [x] Create Presentation of findings for Stakeholders
- [x] [Wiki Documentation](https://github.com/hackforla/tdm-calculator/wiki/Reset-Button-Usability-Test)
   -  Reference [wiki documentation doc](https://docs.google.com/document/d/1fnRrC00xQ5Fm3aO5ShbAsWvBXXuO6vTQHDdyW4OyTDg/edit) in drive
   - [ ] release dependency on #898 

### Resources/Instructions
- #898

**Comment by Jane4925** [comment]
Can I have an expected timeline for this? When do we expect it to be done by?

**Comment by Jane4925** [comment]
Points to consider during testing:
1. location of the buttons
2. any confusion between reset project vs. reset page
3. any comments about the UI
4. is it the warning box clear?
5. is it helpful at all?
6. is it necessary to have it also be on the first page?

**Comment by pmeda12** [comment]
Please refer to the first section for ideas on User testing questions and tasks.

https://docs.google.com/document/d/12LrxKiI232L1sKVrawf9YT89h0-f79yZL6Iyzthcmnc/edit

**Comment by pmeda12** [comment]
@Biuwa Please refer to the first section for ideas on User testing questions and tasks.

https://docs.google.com/document/d/12LrxKiI232L1sKVrawf9YT89h0-f79yZL6Iyzthcmnc/edit

**Comment by ExperimentsInHonesty** [comment]
@pmeda12 Please add a level label

**Comment by Jane4925** [comment]
@Biuwa Need to review the issue and project timeline with Bonnie again to make sure if this issue should be continued or closed.

**Comment by abbyrivard** [comment]
@Biuwa Update on Issue:
- UXR team has created [Research Plan](https://docs.google.com/document/d/12GB3YQfh6cy9ynXriRNNwWAMQ8PTpkHfc8J4qPBXMO0/edit) and was approved by Bonnie at PM meeting 02/01/24. 
- UXR team is finalizing script and migrating interview questions to formal [RP004: Dogfooding Script](https://docs.google.com/spreadsheets/d/1BDUu0Bfvi0LeVTwF_Yy2p2ZTtw6y0e27qfILaSRcuk4/edit#gid=613097829). Once completed, will meet with PMs for the final okay to proceed with testing.

**Comment by melissaperry09** [comment]
Update on issue: 

- UXR team is conducting a run-through of the script/interview process during the week of 4/3-4/10 to train each UXR
- Team leads are using the training sessions to identify any areas of the script that need adjustment

**Comment by melissaperry09** [comment]
@Parisajf update on issue:

Progress: Usability testing sessions were completed at the end of June before the break. Team leads have distributed FigJam training materials, so all researchers understand how to use the platform for collaborative data analysis. 
Blockers: Need further clarification on what FJ board to use. 
Availability: UXR team will discuss data analysis next steps at team meeting on 8/14 and then devote at least 5 hours of individual and collaborative work to data analysis this week and next week. 
ETA: We plan to have data analysis completed over the next 2 weeks. 
Pictures or links* (if necessary): N/A

**Comment by melissaperry09** [comment]
Progress: Research team has analyzed usability testing data by creating an affinity map using FigJam. Team leads are currently working on a rough draft of slides to present findings to the stakeholder. 
Blockers: Need to create a template using previous iterations of usability testing presentations. 
Availability: UXR team will devote at least 5 hours of individual and collaborative work on the slides this week. 
ETA: We plan to have slides finalized by the September 12 stakeholder prep meeting. 
Pictures or links* (if necessary): N/A

**Comment by abbyrivard** [comment]
**Received Feedback from Stakeholder:**
Regarding our suggestions on the warning message, terminology, consistency and location of buttons. Below is the prioritization and responses from the stakeholder for each topic:
- Warning message: must have
- Terminology: should have
- Consistency: Slightly lower priority (could have)
- Location: keep buttons where they are, no changes please

**Comment by abbyrivard** [comment]
**Received Feedback from Stakeholder:**
Regarding our suggestions on the warning message, terminology, consistency and location of buttons. Below is the prioritization and responses from the stakeholder for each topic:
- Warning message: must have
- Terminology: should have
- Consistency: Slightly lower priority (could have)
- Location: keep buttons where they are, no changes please

PMs are creating necessary issues associated with this feedback
