### ISSUE TITLE
Create Agenda for TDM Caculator Team & Stakeholder meeting 1/3/20

### ISSUE THREAD

**Issue by KPHowley** [hackforla/tdm-calculator#136]
Create an Agenda for the for the meeting with the the TDM calculator and Rosemary. 
Key things to go over:
- Current UI design
- UI implementation
- Calculation rules

**Comment by KPHowley** [comment]
Google Doc Of Agenda:
https://docs.google.com/document/d/1ko2qouV1xEgVoRTr0rFIHIYMXyYeaxbTLE4YiGMoaJ8/edit?folder=1rIyyumOj10jiyaB6x5plAO55ccWJ_eta

**Comment by entrotech** [comment]
Meeting is over.
