### ISSUE TITLE
Implement Changes to the Feedback Form

### ISSUE THREAD

**Issue by entrotech** [hackforla/tdm-calculator#1367]
### Overview
- Some changes to the Feedback Form are required per the direction from Issue #148

### Action Items
- [ ] For registered users who are logged on, add a multil-select drop-down list that allows the user to indicate one or more calculations to reference.  The URLs for the selected project will be appended to the body of the email as a list of links that open the corresponding projects
- [ ] Are there other changes that should be made to the form?

**Comment by shanesween** [comment]
@entrotech I have a few questions re: this implementation

- Do we want to simply list the project name in the dropdown list?
- What do we want the URLs of the projects to point to when they are added to the body of the email? The calculation URL page 5?
