### ISSUE TITLE
Implement Warning Dialog for Affordable housing strategy change

### ISSUE THREAD

**Issue by entrotech** [hackforla/tdm-calculator#1368]
### Overview
For the "edge case described in the referenced design issue, implement a modal warning dialog box which warns the user of the consequences of selecting a different option for affordable housing. If they cancel, the do not accept the strategy selection change.

### Action Items
- [ ] Wire up the dialog that aborts the change if the dialog is closed.
- [ ] Set up the dialog to use our "standard" modal dialog component, and make the design look like the wireframe referenced below.

### Resources/Instructions
- For wireframe, see Design Issue #1354

**Comment by Biuwa** [comment]
@jahpe777 Please provide an update. 

Progress: "What is the current status of your project? What have you completed, and what is left to do?"
Blockers: "Difficulties or errors encountered."
Availability: "How much time will you have this week to work on this issue?"
ETA: "When do you expect this issue to be completed?"
Pictures (if necessary): "Add pictures that will help illustrate what you are working on.

**Comment by entrotech** [comment]
- Closed by PR #1813
