### ISSUE TITLE
Design Mockup: Create screens for Admin accounts

### ISSUE THREAD

**Issue by Biuwa** [hackforla/tdm-calculator#1370]
### Overview
we need to create screens that will show different options for admin/LADOT accounts

### Action Items
- [ ] Create a hide button
- [ ] Create a download all project CSV button
- [ ] Create a download a single project CSV button
- [ ] Create a share project link button

### Resources/Instructions
- #1357

**Comment by Noushie** [comment]
@Biuwa - Can we have John post the current version of the admin account screen (screenshots), that way we can use those as a basis for the new designs?

**Comment by Biuwa** [comment]
The current version of the 'My Projects' page from an admin account?

<img width="1707" alt="Screenshot 2023-05-31 at 9 43 27 PM" src="https://github.com/hackforla/tdm-calculator/assets/98936028/faf1f4e8-3cbf-43dc-b91f-74becf872a0e">

**Comment by Biuwa** [comment]
Admin account Security page.

<img width="1707" alt="Screenshot 2023-05-31 at 9 46 19 PM" src="https://github.com/hackforla/tdm-calculator/assets/98936028/e9841cd0-3447-4942-a1c3-257db3e7f68a">

**Comment by Biuwa** [comment]
@limjoyce, this issue needs further discussion with the dev team, so ill be putting this in the ice box for now and unassigning you. 

Thank You
