### ISSUE TITLE
Implement Thunderclient Web API test request scripts

### ISSUE THREAD

**Issue by entrotech** [hackforla/tdm-calculator#1373]
### Overview
We want to be able to quickly and easily test that all the web API server endpoints are working properly. A good way to do this is to implement a test client application that exercises the endpoints. Thunderclient is a VSCode extension that allows you to easily script Web API requests and then run them and check the responses to verify that the endpoints are returning reasonable results.

### Action Items
- [ ] Read about Thunderclient here: https://github.com/rangav/thunder-client-support
- [ ] Add the following lines to the /server/.env file, so thunderclient can have access to test user accounts without storing secrets in the github repo:
```
# User Test Accounts for Shared AWS Development Environment
# (Used by ThunderClient for API Endpoint testing)
USERTEST_EMAIL=usertest@dispostable.com
USERTEST_PASSWORD=LosAngelesDOT1!
ROLESTEST_EMAIL=rolestest@dispostable.com
ROLESTEST_PASSWORD=LosAngelesDOT1!
ADMINTEST_EMAIL=admintest@dispostable.com
ADMINTEST_PASSWORD=LosAngelesDOT1!
```
- [ ] Implement a Thunderclient test that performs a login with each of the three test accounts
- [ ] Implement a few more thunderclient tests that use one of these login requests, then test a protected endpoint and verify the results.
- [ ] Systematically go through all the endpoints and create test requests for them. It might be good to exercise some of the endpoints with multiple requests including some with invalid requests to verify that the appropriate error responses occur.  E.g., attempting to access a secured endpoint without first logging in should probably result in an HTTP 40* error code.

**Comment by entrotech** [comment]
The Thunderclient extension is no longer free - the GitSync feature costs $4/developer/month. I did a search and could not find any other Web API test tools that were free and allowed you to keep the test scripts in the GitHub repo, so I'm closing this issue as infeasible.

**Comment by ExperimentsInHonesty** [comment]
I have added this decision to the wiki decision records
https://github.com/hackforla/tdm-calculator/wiki/DR:-Implement-Thunderclient-Web-API-test-request-scripts
