### ISSUE TITLE
Design Mock-up: Allow users to delete/hide projects

### ISSUE THREAD

**Issue by Biuwa** [hackforla/tdm-calculator#1383]
### Dependency
- This issue is part of the grouped redesign issues for my project page https://github.com/hackforla/tdm-calculator/issues/1386

### Overview
We need users to have a way to delete or hide projects on my project page.

### Details

- Users/project authors would be able to hide/delete projects to allow them to see only the projects they want. Deleted projects would be kept for 90 days so they can be retrieved or restored by users.

### Action Items
- [ ] Mock up changes on my project page 

### Resources/Instructions
- #1369 
- [Video Guide](https://drive.google.com/file/d/1tPp97C8U3zpKYcnJJFl5hiuLcsN_mEKc/view?usp=drive_link)
- [Audio Guide](https://drive.google.com/file/d/1BtEDE3oe_SNtPfTdZ6DsPZjod2kfADNq/view?usp=drive_link)

**Comment by Noushie** [comment]
- 'Archive feature' 
- Users should be informed that a) that it will only be stored for 90 days
- Purpose/Impact: Be able to hide specific project(s)

**Comment by ExperimentsInHonesty** [comment]
I removed the dependency label from this issue because it does not have one listed at the top. This issue is currently in the icebox. Please either add a dependency to the top and re-add the dependency label, or move to the appropriate column.
