### ISSUE TITLE
Design mockup: Create a share modal on my project page

### ISSUE THREAD

**Issue by Biuwa** [hackforla/tdm-calculator#1384]
### Dependency
- This issue is part of the grouped redesign issues for my project page https://github.com/hackforla/tdm-calculator/issues/1386

### Overview
We need to create a share modal on my project page that will provide users with different share options 

### Action Items
The modal should have the following options:

- [ ] Download project summary pdf. which will also have an option of downloading either a single project, filtered projects, selected projects, or all projects)
- [ ] Download CSV (single, filtered, selected, and all projects)
- [ ] Download only filtered projects modified after X date

### Resources/Instructions
- #1357

**Comment by ExperimentsInHonesty** [comment]
I removed the dependency label from this issue because it does not have one listed at the top. This issue is currently in the icebox. Please either add a dependency to the top and re-add the dependency label, or move to the appropriate column.
