### ISSUE TITLE
Design Mock up: Allow Users to filter projects on my project page by date

### ISSUE THREAD

**Issue by Biuwa** [hackforla/tdm-calculator#1385]
### Dependency
- This issue is part of the grouped redesign issues for my project page https://github.com/hackforla/tdm-calculator/issues/1386

### Overview
We need to have a way to filter projects on my projects page by date. 

### Details
- Users/project authors would be able to filter projects either by:
      - [ ] Dates created
      - [ ] Dates last modified
      - [ ] Project Name
      - [ ] Address
      - [ ] AIN/APN (Assessor’s Identification Number), 
      - [ ] Alternative #
      - [ ] Building Permit #1388 
      - [ ] LADOT Case #
      - [ ] City Planning Case #1388 
      - [ ] Project Description

- When Projects are filtered, users will have the option of downloading all filtered projects according to the filter applied
- All the fields from the create project page(Address, LADOT case #, etc), user, region, and staff notes should be filtering options

### Action Items
- [x] Mock up changes on my project page

### Resources/Instructions
- #1357 
- [Video Guide](https://drive.google.com/file/d/10ZaEMrrAABp-xe7bhXAKGLmmUUpLs8Wr/view?usp=drive_link)
- [Audio Guide](https://drive.google.com/file/d/13nqSiZbj1z-6eS_We-tGb3mMz-xG_gW6/view?usp=drive_link)

**Comment by DevPJ9** [comment]
Hello @Biuwa I would like to work on this.

**Comment by Biuwa** [comment]
Hello, @DevPJ9 this is a design issue and not a dev one. 

Did you attend onboarding? If yes, you need to join the Slack channel, and I will redirect you on what to do next.

**Comment by DevPJ9** [comment]
Thank you for the response, @Biuwa. 
Unfortunately, I haven't had the chance to attend the onboarding. Regarding the issue at hand: `it appears to be a design matter rather than a development one.` 
I come from a backend background However, I am currently actively learning React and working on building my own website using it.
Therefore, if this task is open for learners, I would like to take part and contribute.

**Comment by Biuwa** [comment]
@DevPJ9 Unfortunately, the next onboarding session is scheduled for July 10th [here](https://www.meetup.com/hackforla/events/293863578/).

In the meantime Join this slack [channel](https://app.slack.com/client/T04502KQX/CKY65G266), leave a message and we would get to you

**Comment by DevPJ9** [comment]
ok. sure

**Comment by Biuwa** [comment]
Address, LADOT case #, should also be filtering options.

**Comment by edela0015** [comment]
"When Projects are filtered, users will have the option of downloading all filtered projects according to the filter applied( date created or date modified)" 

so this will download every single project right just in the order of the filter (date created/modified)?

**Comment by ExperimentsInHonesty** [comment]
I removed the dependency label from this issue because it does not have one listed at the top. This issue is currently in the icebox. Please either add a dependency to the top and re-add the dependency label, or move to the appropriate column.
