### ISSUE TITLE
Create a "Delete User" API Endpoint for Security Admin Only

### ISSUE THREAD

**Issue by azajzon** [hackforla/tdm-calculator#1395]
### Overview

There is currently no way for the security admin to control the deletion of users. A delete API endpoint must be created to meet this requirement, but it should work as a "soft delete" in order to be able to reverse the action if necessary for a set time period.

#### Frontend
The security admin should be able to log in and see his users with a delete option for each user. 

#### Backend
Create archiving and deleting api endpoints and SQL migration for affected tables.

***

#### Backend Action Items
- [x] Create a api endpoints for deleting users and accounts (soft delete and hard delete)

#### Frontend Action Items
- [x] implement UI to interact with backend api

**Comment by agosmou** [comment]
Adding John to this issue for visibility and discussion 

@entrotech

**Comment by agosmou** [comment]
Possible Implementations assuming 30 day expiration after soft delete
1. a user is archived for 30 days by simply not displaying on the FrontEnd
    a. This would require editing the other api endpoints such as the GET all users in order to hide the "deleted" users
2.  an archive table is created in the database, so when a user is indicated to be deleted, he will be moved to the archive table for 30 days, where he will be deleted after the time limit expires.
    a. This would isolate this endpoint and the deleted users to prevent bugs/errors

**Comment by agosmou** [comment]
Regarding the reversal action:

We should discuss how this would look because it could create more scope for the front end, such as creating an archive page that shows all deleted users and the timeline they have until irreversible deletion with a button to reverse the action.

The reversal itself could be implemented as:
- a function with an event listener "onclick" that calls a "reversal" api endpoint

**Comment by agosmou** [comment]
WIP

https://github.com/hackforla/tdm-calculator/commit/8cb57229292c43418dc4b50da5bae2cd269940e3

**Comment by agosmou** [comment]
If we implement a soft delete by adding a column with a date and time such as "deleted_on"

then all devs must always remember to filter out the rows from the table where "deleted_on" is not null....

**Comment by agosmou** [comment]
Looking into this further, the stored procedures can create another layer of complexity when implementing this db change. 


Perhaps an alternative to the soft delete could be a hard delete with 2FA and have the user type in the name and email of the user to confirm their deletion.

**Comment by agosmou** [comment]
Met with team, need info from product to know how long users and their data should persist. (e.g. 30 days, 1 year, indefinite, etc)

**Comment by agosmou** [comment]
Added frontend (react implementation). Editing branch to add toasts and modals to improve user feedback. Also editing backend to prevent security admins from being deleted. I'll clean this up and push commits.

**Comment by agosmou** [comment]
Created a new branch to work on this feature end-to-end using a more proper implementation - users and respective projects are soft deleted by adding a column to the Login and Project table, but can be un-archived if needed. They can then be deleted after being archived. These endpoints are for security admins only. 

[WIP branch](https://github.com/hackforla/tdm-calculator/compare/develop...delete-api-2)
