### ISSUE TITLE
Engineer tests and validation for 'Account' Web API requests

### ISSUE THREAD

**Issue by agosmou** [hackforla/tdm-calculator#1400]
### Overview

We need to create a workflow for testing all 'account' endpoints. We will need to set up tests and web API request validation for the endpoints.

### Details | Scope of Work
We need to test the API endpoints using 'jest'  

### Action Items

- [x] write all tests for endpoints and documentation
- [x] set up server side validation schema

### Resources/Instructions
Server Side Validation
- https://www.npmjs.com/package/express-json-validator-middleware
- https://simonplend.com/how-to-handle-request-validation-in-your-express-api/  

Testing
- https://jestjs.io/

**Comment by agosmou** [comment]
server side validation done via this [PR](https://github.com/hackforla/tdm-calculator/pull/1394)

**Comment by agosmou** [comment]
Starting to work on the api endpoint tests.

An additional consideration should be to add testing to the CI/CD pipeline

**Comment by agosmou** [comment]
[WIP Branch](https://github.com/hackforla/tdm-calculator/tree/1400-ag-accounts-api-tests)

**Comment by agosmou** [comment]
Aiming to submit PR this weekend

**Comment by Biuwa** [comment]
@agosmou Thanks for the Update.

**Comment by Biuwa** [comment]
@agosmou Please provide update
1. Progress: 
2. Blockers: 
3. Availability:
4. ETA: 
5. Pictures (if necessary):

**Comment by agosmou** [comment]
@Biuwa 
>     1. Progress:
Good progress this week - set up the test suite and [currently working](https://github.com/hackforla/tdm-calculator/tree/1400-ag-accounts-api-tests) on the the integration and unit tests for the accounts
>     2. Blockers:
none
>     3. Availability:
currently available
>     4. ETA:
EOW - it took me a couple of days to do more research and figure out the implementation of the test suite in preparation for future CI
>     5. Pictures (if necessary):
backend only - no pictures

**Comment by agosmou** [comment]
Refactored code. Waiting to hear back from John on how to structure a test and will finish writing the test cases. Then I can submit a PR.
