### ISSUE TITLE
Change Tooltip Hover/Clicked State 

### ISSUE THREAD

**Issue by Noushie** [hackforla/tdm-calculator#1402]
### Overview

**Replace the bolded, underlined hover over terms with an 'i' icon (on pages 1,2,4):**

![image](https://github.com/hackforla/tdm-calculator/assets/115515867/8557d697-2007-4ec0-96a0-1c91ca50a656)

**Once clicked the terms are clicked and the tooltip drops down, it will become bolded:**

![image](https://github.com/hackforla/tdm-calculator/assets/115515867/04e53b54-c4b6-49fc-8acc-74b0e0e0061c)

### Action Items (colours + icons can be found in 'Full Design System')

**Hover state:**

- [ ] Remove bold, underlined hover state 

- [ ] Add a navy blue (#002E6D) 'i' or information icon next to regular text term

**Clicked state:**

- [ ] Change term text colour to 'navy blue' (#002E6D)

- [ ] Bold term text

- 'i' icon remains on screen

- No changes to the tooltip itself

### Resources/Instructions

View in figma [here](https://www.figma.com/file/nD9QK56Mzq7xNSaSUoeGx0/TDM-Calculator?type=design&node-id=9791%3A25976&mode=design&t=prphMoNVohaH2WBs-1)

Note*: See #1403 for the state's activation/trigger

**Comment by Jonathanko52** [comment]
Progress: Tracked down the component that needs to be changed and the icon. Component is being re-used across the project wizard now, so I'm trying to figure out how the data is coming in and how to append the icon without adding it to literally every field.
Blockers: None.
Availability: Weekdays.
ETA: One week.
Pictures (if necessary):

**Comment by Jonathanko52** [comment]
Progress: New Hover and onclick behaviro added to first page. Working on second page items
Blockers: None.
Availability: Weekdays.
ETA: One week.
Pictures (if necessary):
![Screen Shot 2023-08-01 at 10 40 27 PM](https://github.com/hackforla/tdm-calculator/assets/30099154/f4e4cb42-8dec-41bf-9698-ae64c5bd37cc)

**Comment by Jonathanko52** [comment]
Progress: New Hover and onclick behavior added to second page. Icons removed for items without descriptions.
Blockers: None.
Availability: Weekdays.
ETA: Completed

**Comment by Jonathanko52** [comment]
Progress: Fixed issues with text bolding. Ready for review.
Blockers: None.
Availability: Weekdays.
ETA: Completed

**Comment by Biuwa** [comment]
@Jonathanko52 Please provide an update

Progress: "What is the current status of your project? What have you completed and what is left to do?"
Blockers: "Difficulties or errors encountered."
Availability: "How much time will you have this week to work on this issue?"
ETA: "When do you expect this issue to be completed?"
Pictures (if necessary): "Add any pictures that will help illustrate what you are working on

**Comment by Jonathanko52** [comment]
Progress: Removed hover status from items without tooltips
Blockers: None. ready for review.
Availability: 
ETA: 
Pictures (if necessary):
