### ISSUE TITLE
Tooltip Hover Activation

### ISSUE THREAD

**Issue by Noushie** [hackforla/tdm-calculator#1403]
### Overview

**Note*: Revert back to #1402 for actual hover state changes** 

Goal is to increase visibility of the 'information' icon, the hope is to have the hover state activated as the user places their cursor in any of the following area (denoted by the highlighted bar below):

![image](https://github.com/hackforla/tdm-calculator/assets/115515867/13edcfa7-1baf-44d1-8373-b589c9369ac3)

### Action Items

- Increase distance from term that activates hover state 

### Resources/Instructions

View in Figma [here](https://www.figma.com/file/nD9QK56Mzq7xNSaSUoeGx0/TDM-Calculator?type=design&node-id=9846%3A27098&mode=design&t=prphMoNVohaH2WBs-1)

**Comment by Jonathanko52** [comment]
Hi team, I just wanted to check on something"

Not included in the "Action Items" of this issue are new behaviors demonstrated in the figma, such as:
1. graying out the background of the term item
2. graying out of the new "i" icon added in term 1402.

Is this correct?

**Comment by Noushie** [comment]
Hi Jonathan,

Is the following image what you're referring to? 
![image](https://github.com/hackforla/tdm-calculator/assets/115515867/c05352d7-5286-4342-be98-c00b25fc8462)

If that's the case - the 'highlight' is only meant as visual indicator for where we hope to a user would activate the hover state (in other words, the background/icon should not be greyed out). It is only meant to visual depict where we decided the hover state should start based on user feedback. 

Please let me know if you have any other questions/feedback. Thanks!

**Comment by Biuwa** [comment]
Pull Request has been merged and closed per JK and John's review
