### ISSUE TITLE
Change the Download Summary button to Print Summary on Page 5

### ISSUE THREAD

**Issue by Biuwa** [hackforla/tdm-calculator#1406]
### Overview
We need to change the `DOWNLOAD SUMMARY` button on page 5 to `PRINT SUMMARY` per stakeholders' request on 2023-06-13

### Action Items
- [ ] Change the  `DOWNLOAD SUMMARY` button to `PRINT SUMMARY`

### Resources/Instructions
![image](https://github.com/hackforla/tdm-calculator/assets/98936028/a74154ec-39e9-4af4-95ab-0c3b64395bb7)
- Please reference #1314

**Comment by Biuwa** [comment]
@jeffmchang has this been implemented in the Dev Environment?

**Comment by jeffmchang** [comment]
> @jeffmchang has this been implemented in the Dev Environment?
Not just yet, I can push the changes and make a PR right now

**Comment by Biuwa** [comment]
Implemented in the dev environment
