### ISSUE TITLE
Create separate form for submission

### ISSUE THREAD

**Issue by Biuwa** [hackforla/tdm-calculator#1407]
### Overview
We need to create separate forms for submission; snapshots must meet target points before they can be submitted and there should be only one snapshot/submission per form

### Action Items

- [x] Design Mockups using the feedback page as a guide
- [ ] Discuss with the team/PM
- [ ] Get final approval from stakeholders

### Resources/Instructions

- [2023-07-25 Release Updates](https://docs.google.com/presentation/d/1zbyuYIDzat0b5IqnCTYM-kTqDFSkaERDhomriN5t2Gk/edit?usp=sharing)
- [Video](https://drive.google.com/file/d/1K2RpMlsr6GkoqtYGj5dmoIcxYUNilY-E/view?usp=sharing) Timestamp: 5:56

**Comment by ExperimentsInHonesty** [comment]
Additional notes
- It won't need to ask them for their email address or name, because we will use the info from their account.  
- It should a comment field, but it is not required
- It will list the name of the snapshot that is being submitted
- It will have a Submit button

**Comment by Biuwa** [comment]
**2023-09-05 STAKEHOLDERS' MEETING NOTES:**
**Modal Wording:**
'Since your project has not met its point target, you cannot submit this project. Please go back and select enough strategies to meet the point target, or contact a LADOT planner for assistance.'

**Comment by Biuwa** [comment]
@ShahAmani do you have any questions concerning this issue?

**Comment by ShahAmani** [comment]
Hello Ebi,

Update on issue 1407 - Create a Separate Form for Submission

Over the last week, I have learned about the TDM calculator: users, design
files, and what's expected.

I have some questions about the issue that I have been assigned.

   1.

   Will the form appear after the “Create Project” flow, after the “Create
   Snapshot” flow (still in the Figma drafts under Ongoing Issues #1369), or
   both?
   2.

   What is the difference between submitting a snapshot (uneditable copy)
   versus submitting an active project (still editable)?
   1.

      Does this impact the submission form?
      3.

   I have attached two Figma pages below titled,  “Project Submission Form”
   which I found under Ongoing Issues#1396
   1.

      Is this what you had in mind for the Submission Form that I will be
      designing?
      2.

      What are some of the expectations on how my designs will differ from
      these pages?


Looking forward to hearing your insight. Please let me know if you would
prefer to schedule a one-on-one to discuss more.

Thank you,

Shah

**Comment by ShahAmani** [comment]
@Biuwa I have some questions about this issue

1. Will the form appear after the “Create Project” flow, after the “Create Snapshot” flow (still in the figma drafts under Ongoing Issues #1369), or both? 
2. What is the difference between submitting a snapshot (uneditable copy) verse submitting a active project (still editable) Does this impact the submission form?

**Comment by Biuwa** [comment]
Submitted badge Mockup on My project page:

![image](https://github.com/hackforla/tdm-calculator/assets/98936028/0f7ffcbc-dbfe-4740-bb27-c5f7e38ebfdb)

**Comment by limjoyce** [comment]
MODAL FOR SUBMISSION FORM WHEN TARGET POINTS ARE NOT MET:
![Project Submission Form 1](https://github.com/hackforla/tdm-calculator/assets/130421333/4ba083ec-5a5c-4843-8cc1-bfe518d7f10d)

SUBMISSION FORM WHEN TARGET POINTS ARE MET:
![Project Submission Form 2](https://github.com/hackforla/tdm-calculator/assets/130421333/44a98723-40d4-4bb4-94e4-eab44d43d6a7)

**Comment by ExperimentsInHonesty** [comment]
REQUIREMENTS for the submission

### Places you can create a submission from
1. My Projects page, the three dots on any snapshot will have a "submit to LADOT" link/button
2. On Page 5, in addition to being able to print, if its a snapshot, you can also submit.
3. A Separate link that will show up on the main menu, for Submitting

### What will happen when you choose submit to LADOT from any of the above locations
- You will be taken to a page that looks like the feedbackback page, but that only lists snapshots
- If you came from My projects, or page 5, the snapshot is already selected
- If you came from the main menu link, you can choose all the snapshots, but you can only pick one

### Warning modal
You cannot submit a snapshot that does not have enough target points.  If you try to do that, you will get a modal.  The modal needs to tell you what the current modal says, plus it needs to tell you re-snapshot the project.

### After they successfully submit
User should get a thank you modal which has a OK button.
User should then be returned to page they came from.
On the My Project's page, it says submitted and the date under last updated.

**Comment by Biuwa** [comment]
**2023-11-28 MEETING FEEDBACK: **
<img width="493" alt="Screenshot 2023-11-27 at 8 10 21 PM" src="https://github.com/hackforla/tdm-calculator/assets/98936028/b649d535-d3dd-42fb-b81c-332900fb843a">

- [ ] Please change checkboxes to radio buttons

**Comment by Biuwa** [comment]
**2023-11-28 STAKEHOLDER MEETING FEEDBACK:**

<img width="224" alt="Screenshot 2023-11-29 at 4 15 55 PM" src="https://github.com/hackforla/tdm-calculator/assets/98936028/027cc927-d6c9-4d6e-977b-68252424f3c8">

- [ ] Remove the radio button next to the title 'Name'
_______________________________________________________

- [ ] The submission page should have the following: Name, Address, Alternative No, Created On, Last Modified; Keep the Created On if there is room

______________________________________________________

- [ ]  Users should be able to submit from page 5, but it's not urgent( This can be done when there are fewer designs or issues to work on). 
- [ ] The submit button on page 5 is grayed out if the points don't add up (this is a correction for the grayed-out submit button added earlier)  with a tooltip/hover explaining why and what users should do.
- [ ] Add a note on the bottom of page 5 with what the status of the project is and let the user know they can go to my projects page to update status/submit (only available on snapshots that meet points) Emily says the note can say `To manage the status of this project, go to my projects page`

**Comment by Parisajf** [comment]
**Notes from the call on 11-28:**

1. We need to think about what happens if they use the menu on a **non-snapshot** on my projects page : is the option there but grayed out with a tooltip?Right now, things don’t show up
2. Remove the radio button next to the title “Name”
3. On the last screen in the workflow where the person has used the Submit Snapshot, the mockup should show the project just submitted, **not grayed out.**
4. The submission page should have the following: **Name, Address, Alternative No, Created On, Last Modified, Created On (if there is room)**
5. On My Project’s page, please bring back address.
6. We need all pages to be consistent in Figma ( or one single page that shows the finished project column headers and all possible values)
 7. It would be nice to be able to submit from page 5, but not urgent, and the submit button is grayed out if the points don't add up, and then a tooltip or hover explains why and what you should do.
8. Add a note on page 5 with what the status is and letting the user know they can go to my projects to update status/submit (only available on snapshots that meet points)

**Comment by Biuwa** [comment]
**Please provide an update:**

1. **Progress**_(What is the current status of your project? What have you completed, and what is left to do)_:
2. **Blockers**_(Difficulties or errors encountered)_:
3. **Availability**_(How much time will you have this week to work on this issue)_:
4. **ETA**_(When do you expect this issue to be completed)_:
5. **Pictures** _(if necessary)(Add any pictures that will help illustrate what you are working on)_:

**Comment by Biuwa** [comment]
@limjoyce 

**Please provide an update:**

1. Progress(What is the current status of your project? What have you completed, and what is left to do):
2. Blockers(Difficulties or errors encountered):
3. Availability(How much time will you have this week to work on this issue):
4. ETA(When do you expect this issue to be completed):
5. Pictures (if necessary)(Add any pictures that will help illustrate what you are working on)

**Comment by limjoyce** [comment]
1. Progress(What is the current status of your project? What have you completed, and what is left to do): Completed - see flows below
2. Blockers(Difficulties or errors encountered): n/a
3. Availability(How much time will you have this week to work on this issue): 
4. ETA(When do you expect this issue to be completed):
5. Pictures (if necessary)(Add any pictures that will help illustrate what you are working on):

**SUBMITTING FROM MY PROJECTS PAGE:**
![1407_My Projects 1-1](https://github.com/hackforla/tdm-calculator/assets/130421333/a18f99b2-7346-4d31-8e75-440fdcd57fda)

![1407_My Projects 1-2](https://github.com/hackforla/tdm-calculator/assets/130421333/5507d936-07cf-45b4-bd30-856bf940944c)

![1407_My Projects 1-3](https://github.com/hackforla/tdm-calculator/assets/130421333/6c21db44-77c1-4cf4-ae14-9a9cb3a3b86a)

![1407_My Projects 1-4](https://github.com/hackforla/tdm-calculator/assets/130421333/6fddd63d-8073-4f76-8689-7156d51741b9)


**SUBMITTING FROM PAGE 5**
![1407_My Projects 2-1](https://github.com/hackforla/tdm-calculator/assets/130421333/04f8ce0a-b2a3-4c7a-aee6-7be65a03636d)

![1407_My Projects 2-2](https://github.com/hackforla/tdm-calculator/assets/130421333/9d7d9e67-3aa2-464b-8d39-3a5e5fab8693)

![1407_My Projects 2-3](https://github.com/hackforla/tdm-calculator/assets/130421333/741c1272-74d1-4978-8cef-d800d5166fdc)

![1407_My Projects 2-4](https://github.com/hackforla/tdm-calculator/assets/130421333/d1ff8556-f986-43ae-b674-c2d34a15061b)


**SUBMITTING FROM MAIN NAVIGATION**
![1407_My Projects 3-1](https://github.com/hackforla/tdm-calculator/assets/130421333/9f2f89bf-e646-415e-9ac8-ff8b6f8850cb)

![1407_My Projects 3-2](https://github.com/hackforla/tdm-calculator/assets/130421333/59155d95-2f46-4b2b-a183-127e940ee868)

![1407_My Projects 3-3](https://github.com/hackforla/tdm-calculator/assets/130421333/a5027531-567a-4f27-8a60-38ddd52bc58a)

**Comment by Biuwa** [comment]
@limjoyce Please review the [feedback](https://github.com/hackforla/tdm-calculator/issues/1407#issuecomment-1828907896) and tick off which was implemented in the new mockups

**Comment by ExperimentsInHonesty** [comment]
We accept this design with a few minor mods.  The language should say target points, not point target and the button one of the page 5 images has the save button selected, and I think its meant to have the submit button selected.
