### ISSUE TITLE
Change the "Version #" tab title to "Alternative #" on the My Projects page

### ISSUE THREAD

**Issue by fnaneberhane** [hackforla/tdm-calculator#1418]
### Overview
One of the tabs on the My Projects page displays "Version #" as the title and needs to change to "Alternative #" based off users being unclear what "Version #" means from usability testing.

### Action Items
 - [ ] Change Version # to Alternative #

### Resources/Instructions
- use this issue as a reference #869 
- <img width="1412" alt="Screenshot 2023-08-08 at 2 20 49 PM" src="https://github.com/hackforla/tdm-calculator/assets/140571786/211b85c1-d500-49d7-accc-4bfbe34fbd3b">

**Comment by jeffmchang** [comment]
The issue has been addressed in PR #1419

**Comment by Biuwa** [comment]
@entrotech - Please review
