### ISSUE TITLE
UI/UIX Wireframe: Target Point Calculation Page 

### ISSUE THREAD

**Issue by entrotech** [hackforla/tdm-calculator#142]
### Overview
Design the target point calculation page in the Calculation wizard.

### Action Items
- Design in Figma
- Assign someone to review
- Create New Issue for front end development 

### Resources/Instructions
Figma Wireframe Link:
https://www.figma.com/file/qNgPc5lttpf0SWSwkbbWyT/TDM-Calculator?node-id=0%3A1
Follows up issue #18

**Comment by KPHowley** [comment]
<img width="1440" alt="A7 Target point Calculation@2x" src="https://user-images.githubusercontent.com/49739276/72689779-24987f00-3aca-11ea-9516-bd092f395422.png">
Here's a proposal for a slightly updated design.
@nekobox - Can you review, and any changes. If you can get back to me by tomorrow 1/20 I'd appreciate it!

**Comment by KPHowley** [comment]
@ExperimentsInHonesty - if you want to review and share, I can then close this out and make a new issue for front end development
