### ISSUE TITLE
Replace code for America on the policy page

### ISSUE THREAD

**Issue by Biuwa** [hackforla/tdm-calculator#1421]
### Overview
We need to replace the references to Code for America shown on the privacy policy page with the current updated information.

### Action Items

- [ ] Replace 
```
Code for America Labs, Inc. ("Code for America"
```
with
```
Civic Tech Structure, Inc. ("Civic Tech Structure"
```
- [ ] Replace
```
Code for America
Ref: Hack for LA, TDM Calculator
155 9th Street
San Francisco, CA 94103
```
with
```
Civic Tech Structure, Inc.
Ref: Hack for LA, TDM Calculator
13428 Maxella Avenue, 821
Marina Del Rey, CA 90292
```

### Resources/Instructions
https://tdm.ladot.lacity.org/privacypolicy
https://github.com/hackforla/tdm-calculator/blob/develop/client/src/components/PrivacyPolicy.js

**Comment by ExperimentsInHonesty** [comment]
@karandeep4423 if you are working on this issue, you need to move this into the 'in Progress' column and provide weekly issue updates, otherwise, if you are not working on it, then please unassign

**Comment by jeffmchang** [comment]
@karandeep4423 If you don't have time to fix this I can make the change.
