### ISSUE TITLE
Implement Rule that disables specific strategies when no parking is provided.

### ISSUE THREAD

**Issue by entrotech** [hackforla/tdm-calculator#1434]
### Overview
- We want to implement a rule that automatically disables strategies that do not apply when no parking is provided as described in Issue #829

### Action Items
- [ ] Implement as described in Issue #829

**Comment by Biuwa** [comment]
- Car Share Parking and Shared Parking are still available. Is this the desired behavior?

**Comment by Biuwa** [comment]
2023-11-14 STAKEHOLDERS FEEDBACK:

> What they cannot select if they have indicated 0 parking
HOV Parking
Pricing Unbundling
Cash Out Parking
Public Parking
Car Share Parking and Shared Parking are still available. Is this the desired behavior?

- NO, Car Share Parking should not be available

**Comment by entrotech** [comment]
Added Car Share Parking to the set of strategies that are disabled if no parking is provided
