### ISSUE TITLE
Implement "Move to Trash" and "Remove from Trash" Project Features

### ISSUE THREAD

**Issue by entrotech** [hackforla/tdm-calculator#1436]
### Dependency
- [x] #1383 

### Overview
We want users to be able to "move to trash" (and "restore from trash") projects that they own.  This allows users to remove projects.  Filtering requirements for the My Project page are TBD, but should, by default not list projects in the trash, but have the option to include them on the grid, in case the user wants to remove them from the trash.  A separate issue will address how projects are permanently deleted - possibly by allowing the user to "empty the trash" or implementing a system that automatically deletes projects from the trash after a specified number of days.

### Action Items
- [x] Create a database migration script that adds a dateTrashed column to the Project table in the database. This column will be normally be null, but have the UTC datetime that the project was trashed for projects in the trash. there is no need to record which user hid or unhide the project, since it is the same as the createdBy user.
- [x] Create a stored procedure called Project_Trash with parameters [id] int, trash bool and loginId int.  The array of ids identifies the projects to update. the trash parameter indicates whether to trash (true) or untrash(false) the project(s), and the loginId must match the loginId column of each or the update should fail and return an error code indicating that the operation is unauthorized.
- [x] Create a Web API endpoint with the path /api/projects/trash and body object. The request body should contain properties ids (an array of integers) and trash boolean.  (The loginId parameter for the user should be extracted from the JSON Web token, to avoid tampering.) Add the appropriate methods to the project.controller.js, project.routes.js, project.service.js methods to implement the endpoint and call the stored procedure. This ensures that the request is coming from a logged in user and reliably determines the loginId of the user.
- [x] At this time, it's not determined how many different places in the UI that the trash feature may be called. We can start by implementing the feature from the "More..." menu that appears on individual lines of the My Project page design. If the project is already in the trash, the menu choice should be to "Restore from Trash", if the project is not in the trash), the menu choice should be "Delete" 
![image](https://github.com/hackforla/tdm-calculator/assets/9939032/1cd00a37-fa43-4362-bc1a-edc65a92b2fa)

(This screenshot shows the TEMPORARY implementation of the My Projects Page, which includes icons to indicate if a project is hidden, trashed or snapshotted, since we need a visual indication of the project statuses until we can implement the desired filtering for the My Projects page.)
- [x] You will need to create a client-side service to call the Web API endpoint.
- [x] You will need to wire-up the delete/undelete context menu item to call the client-side service.
- [x] When deleting, be sure to call the existing Delete modal dialog. Talk with the PMs about how the wording should be changed, since the delete is no longer immediate or permanent.  I would prefer that we use the word Trash, instead of delete, since that seems to be what most applications do if an item is not deleted immediately.
- [ ] We anticipate that it might also be desirable for users to be able to trash/untrash multiple projects at once (hence the above convention to pass an array of (project) ids to the web api endpoint.  To do this the selected projects must all have the same trash vs not in trash status, so the same operation will be performed on all selected projects. This is NOT part of this issue.
- [ ] It may also be desirable to show somewhere on the Project Wizard if a project is in the trash and maybe to provide a button to trash/untrash from the wizard. This is NOT part of this issue.

### Resources/Instructions
- Related Design Issue #1383
- My Project Page Design Issue #1386
- #1388
Icons to use:
font-awesome free solid icons trash and trash-restore for "Move to Trash" and "Restore from Trash", respectively.

**Comment by kianadk** [comment]
@entrotech could you please add me to the team gdrive so i can grab the .env file?

**Comment by Biuwa** [comment]
@kianadk 
Please provide update

Progress: "What is the current status of your project? What have you completed and what is left to do?"
Blockers: "Difficulties or errors encountered."
Availability: "How much time will you have this week to work on this issue?"
ETA: "When do you expect this issue to be completed?"
Pictures (if necessary): "Add any pictures that will help illustrate what you are working on.

**Comment by kianadk** [comment]
@Biuwa I've decided I need to step away from this project, I underestimated the time I had available to work on it. I'll unassign myself from the issue. Apologies for any inconvenience

**Comment by joelfuelling** [comment]
<br />


## Clarifying Questions for PM/UX team: 

1 - Is the wording below acceptable for the "Trash project" confirmation warning?

![TrashModalOpenText](https://github.com/hackforla/tdm-calculator/assets/127354185/7899cf82-e084-43ab-9b1a-4697bd6b73d5)

<br />



2 - From the context menu (screenshot below), are the existing terms 'Move to Trash' and 'Remove from Trash' sufficient? 

3 - The default text color is currently red when it's not in the trash. What would be an ideal color for when it is in the trash?

![MoveToTrash](https://github.com/hackforla/tdm-calculator/assets/127354185/d3281c27-02ad-4d1f-a2e8-385b59d31e1d)

# Dev Team

I created a separate 'Trash' component mirroring the Delete component, so I could recreate the process as much to understand more of the process flow. That being said, I was a bit confused as if the end goal is to have the Delete functionality "built into" the projectTrashed (happens at the end of the grace period), or if there would be a separate delete component, or both? I got a bit caught up in parts of the structure which slowed me down but I would like to better understand the end goal for this portion!

Currently, I'm getting "TypeError: axios__WEBPACK_IMPORTED_MODULE_0___default(...).trash is not a function" when I click the 'Trach' button to alter the project.dateTrashed attribute, but I'm still working through it.

**Comment by Biuwa** [comment]
Red Hex Code is: B64E38

**Comment by Noushie** [comment]
View in Figma [here](https://www.figma.com/file/nD9QK56Mzq7xNSaSUoeGx0/TDM-Calculator?type=design&node-id=11041%3A20315&mode=design&t=MUv700PMF89bpCDm-1)


**Deletion Modal:**
<img width="593" alt="image" src="https://github.com/hackforla/tdm-calculator/assets/115515867/36d37f2a-1c95-48c8-803d-e9d163321ca0">

**Recovery Option:**
<img width="487" alt="image" src="https://github.com/hackforla/tdm-calculator/assets/115515867/b6bb3bd6-7641-4ebc-be7e-0d23c8b50428">

**Recovery Modal:**

<img width="540" alt="image" src="https://github.com/hackforla/tdm-calculator/assets/115515867/93ba318d-e184-4e1d-ae95-e0e59e53f186">

**Comment by Biuwa** [comment]
**Please provide an update:**

1. **Progress**_(What is the current status of your project? What have you completed, and what is left to do)_:
2. **Blockers**_(Difficulties or errors encountered)_:
3. **Availability**_(How much time will you have this week to work on this issue)_:
4. **ETA**_(When do you expect this issue to be completed)_:
5. **Pictures** _(if necessary)(Add any pictures that will help illustrate what you are working on)_:
