### ISSUE TITLE
Implement a Feature to Create a Project Snapshot

### ISSUE THREAD

**Issue by entrotech** [hackforla/tdm-calculator#1437]
### Dependency

- [x] #1369 

### Overview
We want users to be able to freeze a version of a Project by creating a "snapshot" that is no longer editable. We will use the term "draft" to describe an editable calculation/project, and "snapshot" to describe a calculation that has been converted to a non-editable snapshot. When a snapshot is created, the user will be able to change the project name and Alternate #. These changes do not count as a Modification to the project for purposes of the Modified By date.  If the user wants to create a modified version of the calculation, they will do so by making a copy from the My Projects Page, which will then be an (editable) draft.

A separate follow-on issue will be created that allows the user to share a snapshot with other users, but the requirements are TBD.

Separate issues will be created for modifying the user access list for a snapshot.  Snapshots may also be hidden or moved to the trash or deleted.

### Action Items
- [x] Create a database migration script that adds a dateSnapshotted column to the Project table in the database. This column will be null for draft projects, but have the UTC datetime that the snapshot was created for projects that are a snapshot. there is no need to record which user hid or unhide the project, since it is the same as the createdBy user.
- [x] Create a stored procedure called Project_Snapshot with parameters id int and loginId int.  The id identifies the projectd to snapshot. The loginId must match the loginId column of each or the update should fail and return an error code indicating that the operation is unauthorized.
- [x] Create a Web API endpoint with method PUT and path /api/projects/snapshot and a body object with a single integer parameter named "id" that indicates the project to create a snapshot from.  (The loginId parameter for the user should be extracted from the JSON Web token, to avoid tampering.) Add the appropriate methods to the project.controller.js, project.routes.js, project.service.js methods to implement the endpoint and call the stored procedure. This ensures that the request is coming from a logged in user and reliably determines the loginId of the user.
- [ ] At this time, it's not determined how many different places in the UI that the snapshot feature may be called, but we are assuming that the user must create snapshots for one project at a time. We can start by implementing the feature from the "More..." menu that appears on individual lines of the My Project page design if the selected line does not represent a project that is already a snapshot, is not deleted and not hidden. 
![image](https://github.com/hackforla/tdm-calculator/assets/9939032/1cd00a37-fa43-4362-bc1a-edc65a92b2fa)

(This screenshot shows the TEMPORARY implementation of the My Projects Page, which includes icons to indicate if a project is hidden, trashed or snapshotted, since we need a visual indication of the project statuses until we can implement the desired filtering for the My Projects page.)
- [ ] You will need to add a method to the /client/src/services/project.service.js to call the Web API endpoint mentioned above.
- [ ] You will need to wire-up the snapshot menu item from the context menu shown above to call this new client-side service method.
- [ ] As a starting point, clicking on the snapshot menu item will immediately create the snapshot without any kind of modal dialog or prompt. The UI team is working on a modal that will allow the user to re-name the project and add a list of email addresses to share the snapshot with, but the implementation will be in separate follow-on development issues.
- [ ] It may also be desirable to show somewhere on the Project Wizard if a project is a snapshot and maybe to provide a button to convert a snapshot to a draft, but the requirements are TBD as of 9/7/23.

### Resources/Instructions
- My Project Page Design Issue #1386
- #1388
Icon to use:
font-awesome free solid icons fa-camera

**Comment by Biuwa** [comment]
ETA: Next Week

**Comment by Jonathanko52** [comment]
![Screen Shot 2023-10-04 at 7 40 39 PM](https://github.com/hackforla/tdm-calculator/assets/30099154/197351c2-5556-4a7f-ba12-1e7920c636a7)

**Comment by Biuwa** [comment]
@Jonathanko52 Please provide update
1. Progress: 
2. Blockers: 
3. Availability:
4. ETA: 
5. Pictures (if necessary):

**Comment by Jonathanko52** [comment]
Progress: Creating a new modal for the snapshot function.
Blockers: Issues running TDM locally, and therefore making any changes.
Availability: Weekdays.
ETA: One week once I get this blocker resolved.

Pictures (if necessary):

**Comment by Jonathanko52** [comment]
Progress: Snapshot function implemented. Modal finished. Ready for review.
Blockers: None
Availability: Weekdays.
ETA: One week once I get this blocker resolved.

Pictures (if necessary):[](url)
![Screen Shot 2023-10-25 at 5 52 34 PM](https://github.com/hackforla/tdm-calculator/assets/30099154/fc24f4f4-57a9-4223-b40f-73e2d18cbbe4)

**Comment by Biuwa** [comment]
@Jonathanko52 Please provide update

Progress:
Blockers:
Availability:
ETA:
Pictures (if necessary):

**Comment by Jonathanko52** [comment]
Progress: Added API calls for snapshot and rename paths. Added project name to the payload.
Blockers: None
Availability: Weekdays.
ETA:

**Comment by Parisajf** [comment]
John created a procedure and is working with JK next week
