### ISSUE TITLE
My Projects Page Snapshot Feature Requirements

### ISSUE THREAD

**Issue by Biuwa** [hackforla/tdm-calculator#1438]
### Overview
This issue will track the design requirements for the snapshot feature on the My Projects page
- #1386 
- #1369 

### Action Items
- [x] Watch/Listen to the briefing video/Audio
- [x] Compare design mockups with the requirements in the briefing video
- [x] Discuss with UX Design/PM team
- [ ] Forward to the Dev team for implementation

.

### Resources/Instructions
[Video](https://drive.google.com/file/d/1K2RpMlsr6GkoqtYGj5dmoIcxYUNilY-E/view?usp=sharing)
[Audio](https://drive.google.com/file/d/1wvjgR-j5zZltMKxA64FUy2tuDcyOswlo/view?usp=drive_link)
- https://github.com/hackforla/tdm-calculator/issues/1386#issuecomment-1670664432

**Comment by Biuwa** [comment]
- Snapshot requirements per video for #1369 
   - [ ] Create a snapshot of a project (A conversion of a particular project to a snapshot)
   - [ ] The project will not be an editable project while a snapshot is being created.
   - [ ] The user can make a copy of the snapshot and save it as a new project
   - [ ] The snapshot will be sent to recipients emails as a link
   - [ ] The user will indicate the email/emails of the people he is sharing the snapshot with and should be able to retract access by deleting any of the emails on the access list
   - [ ] The recipients can view the snapshot via the link and can save and edit the project locally
   - [ ] If a User tries to click or edit a snapshotted project, they will get a popup informing them that the project is a snapshot and they cannot edit it directly, because it is a permanent record, but they can create a copy and edit that copy,  (PMs and Stakeholder will provide wording)

**Comment by Biuwa** [comment]
@Noushie Please confirm requirements above meet the mockups designed

**Comment by Noushie** [comment]
@Biuwa - Are we able to get the wording for the 'duplicate' snapshot prompt? 

I'm also a little confused with checkbox number 7.

Do you mean a recipient can save the snapshot, duplicate and then edit?
