### ISSUE TITLE
My Projects page Filtering Requirements

### ISSUE THREAD

**Issue by fnaneberhane** [hackforla/tdm-calculator#1440]
### Overview
This issue will track the requirements needed for filtering on the My Projects Page

- #1386 
- #1385 

### Action Items

- [x] Watch/listen to the briefing video 
- [x] Compare the requirements listed in the briefing video to the design mockups
- [ ] Discuss with UX/PM team
- [ ] Forward to Dev team for implementation

### Resources/Instructions

- [Video ](https://drive.google.com/drive/u/0/folders/1xbZQX8FvRh-DdFw20baJQ8wAwU9quNp4)
- [Audio](https://drive.google.com/drive/u/0/folders/1xbZQX8FvRh-DdFw20baJQ8wAwU9quNp4)
- #1386 
- #1385

**Comment by fnaneberhane** [comment]
Filtering requirements from #1385: 
- [ ] Dates created
- [ ] Dates last modified
- [ ] Project Name
<img width="777" alt="Screenshot 2023-09-03 at 5 32 07 PM" src="https://github.com/hackforla/tdm-calculator/assets/140571786/e4548d01-df62-4a99-96a2-65142c3b4a38">

- [ ] Address
- [ ] AIN/APN (Assessor’s Identification Number),
- [ ] Alternative #
- [ ] Building Permit https://github.com/hackforla/tdm-calculator/issues/1388
- [ ] LADOT Case #
- [ ] City Planning Case https://github.com/hackforla/tdm-calculator/issues/1388
- [ ] Project Description
@Noushie can the remaining filter requirements above(e.g address, AIN, Alternative #, etc) be done using keywords in the search bar? 

Filtering requirements from [Video](https://drive.google.com/drive/u/0/folders/1xbZQX8FvRh-DdFw20baJQ8wAwU9quNp4)/[Audio](https://drive.google.com/drive/u/0/folders/1xbZQX8FvRh-DdFw20baJQ8wAwU9quNp4) brief: 
- [ ] Flexible date filtering using date picker shown above
- [ ] **Admin view specific**: Have a drop-down menu for regions to choose a region for that project.
- [ ] **Admin view specific**: Notes field for staff to leave notes only for admin view and not viewed by user

**Comment by Noushie** [comment]
> Filtering requirements from #1385:
> 
> * [x]  Dates created
> * [x]  Dates last modified
> * [x]  Project Name
> 
> <img alt="Screenshot 2023-09-03 at 5 32 07 PM" width="777" src="https://user-images.githubusercontent.com/140571786/265289962-e4548d01-df62-4a99-96a2-65142c3b4a38.png">
> * [ ]  Address
> * [ ]  AIN/APN (Assessor’s Identification Number),
> * [ ]  Alternative #
> * [ ]  Building Permit [Create a more modal on my projects page #1388](https://github.com/hackforla/tdm-calculator/issues/1388)
> * [ ]  LADOT Case #
> * [ ]  City Planning Case [Create a more modal on my projects page #1388](https://github.com/hackforla/tdm-calculator/issues/1388)
> * [ ]  Project Description
>   @Noushie can the remaining filter requirements above(e.g address, AIN, Alternative #, etc) be done using keywords in the search bar?
> 
> Filtering requirements from [Video](https://drive.google.com/drive/u/0/folders/1xbZQX8FvRh-DdFw20baJQ8wAwU9quNp4)/[Audio](https://drive.google.com/drive/u/0/folders/1xbZQX8FvRh-DdFw20baJQ8wAwU9quNp4) brief:
> 
> * [ ]  Flexible date filtering using date picker shown above
> * [ ]  **Admin view specific**: Have a drop-down menu for regions to choose a region for that project.
> * [ ]  **Admin view specific**: Notes field for staff to leave notes only for admin view and not viewed by user

Hi @fnaneberhane,

For a further breakdown:

1. My apologies the description omitted a lot of information, the 'search' feature should allow users to input ANY keyword (ex. building permit, project name, address, etc.) - if there is any blockers for this, I'm happy to make adjustments (CC: @entrotech).

![image](https://github.com/hackforla/tdm-calculator/assets/115515867/e1e712d7-52d6-4556-9757-20b13ab9cc34)

2. If a user wants to specifically search by date range(s), they can use the 'filter' option in the search box which would allow them to do so (i.e., by dates the project was created on or last modified).

![image](https://github.com/hackforla/tdm-calculator/assets/115515867/1d642271-66c1-4829-ac7a-25f6dcc11c7d)

3. Users can use the headers at the top of the table to sort projects accordingly. In this case, 'Last Modified' is how the table is sorted by default, but if a user wanted to sort it by alphabetically by 'Name,' they could click on that header).  This needs further polishing according to stakeholder requirements and we do have to still determine the specifications (ex. would users want to sort names by descending AND ascending order? etc.).

![image](https://github.com/hackforla/tdm-calculator/assets/115515867/1a983ab3-234c-4f88-ab0f-a37f5d3f33da)

Hope this helps clarify things.

**Comment by fnaneberhane** [comment]
Thanks @Noushie, another question I had was is there any figma mockups of the filtering requirements in the Admin view mentioned by @bonniewolfe in the [video](https://drive.google.com/drive/u/0/folders/1xbZQX8FvRh-DdFw20baJQ8wAwU9quNp4)?
Such as:
- Admin view specific filtering: Have a drop-down menu for regions to choose a region for that project.
- Admin view specific filtering: Notes field for staff to leave notes only for admin view and not viewed by user

**Comment by Biuwa** [comment]
**2023-09-07 PM Meeting Feedback:**
- Ask Stakeholders in the next meeting if the 'choose a region feature' is still something they want on the admin screen

**Comment by Noushie** [comment]
Hi @fnaneberhane - not yet.. We were hoping to solidify the 'My Projects' for users before making the adjustments for Admin. We can start that as well - Can I just clarify what 'region' means in this particular context? Just want to make sure I'm understanding correctly. Thanks a lot.

**Comment by Biuwa** [comment]
**2023-10-04 STAKEHOLDERS MEETING FEEDBACK:**

@Noushie 

- Projects should be filtered by Development Review Offices (DRO) instead of Regions
- Yes, LADOT wants it visible to users(Submitted project only), so they can be able to see inquiries and status about their projects so it can be directed to the Development Review Offices.
- The also provided us a link to the map of the DROs:  https://lahub.maps.arcgis.com/apps/instant/nearby/index.html?appid=3f1ffa8b2949449e9038ee54aede3458

**Comment by Biuwa** [comment]
- All issues have been addressed and can be tracked with #1386
