### ISSUE TITLE
Fix the spelling of "residential" on the Checklist Dialog

### ISSUE THREAD

**Issue by entrotech** [hackforla/tdm-calculator#1446]
### Overview
Fix the spelling of "residential" on the Checklist Dialog

### Action Items
- [ ] Fix the spelling error as described on Issue #1146

**Comment by Biuwa** [comment]
- Implemented in the dev environment

**Comment by jackberrypassionfruit** [comment]
I can confirm that "residentian" has been fixed to "residential" for the production deployment:

![Image](https://github.com/user-attachments/assets/394af372-3efa-40c2-8ec7-f462a8f83cf6)
