### ISSUE TITLE
Submission Form design Requirements

### ISSUE THREAD

**Issue by Biuwa** [hackforla/tdm-calculator#1447]
### Overview
This issue will track the design requirements for the submit feature on the My Projects page

### Action Items
- [ ] Watch/listen to the briefing video
- [ ] Compare the requirements listed in the briefing video to the design mockups
- [ ] Discuss with UX/PM team
- [ ] Forward to Dev team for implementation

### Resources/Instructions
[Video](https://drive.google.com/file/d/1K2RpMlsr6GkoqtYGj5dmoIcxYUNilY-E/view?usp=sharing) Timestamp: 5:56

**Comment by ExperimentsInHonesty** [comment]
- This issue is complete.  The requirements were shared with design on issue #1407
