### ISSUE TITLE
UI/UX Wireframe: Transportation Demand Strategies Page

### ISSUE THREAD

**Issue by KPHowley** [hackforla/tdm-calculator#145]
### Overview
Redesign the Strategies page in the wizard to include Bundles and re-design to improve user functionality 

### Action Items
- Design in Figma
- Assign someone to review
- Create New Issue for front end development 

### Resources/Instructions
Figma Wireframe Link:
https://www.figma.com/file/qNgPc5lttpf0SWSwkbbWyT/TDM-Calculator?node-id=0%3A1
Follows up issue #18

**Comment by nekobox** [comment]
Per project leads' meeting with LADOT on Thursday, January 9th, 2020, the design team will provide LADOT with 2 design options for the strategies page via clickable prototypes by Monday, January 13th, 2020:

1) [Tabbed Option](https://www.figma.com/proto/qNgPc5lttpf0SWSwkbbWyT/TDM-Calculator?node-id=523%3A1684&scaling=scale-down)
2) [Accordion Option](https://www.figma.com/proto/qNgPc5lttpf0SWSwkbbWyT/TDM-Calculator?node-id=533%3A14&scaling=scale-down)

LADOT to provide additional feedback by end of week on Friday, January 17th, 2020.
