### ISSUE TITLE
Change the Link on the Security Role Screen to "Return to Active Accounts"

### ISSUE THREAD

**Issue by entrotech** [hackforla/tdm-calculator#1453]
### Overview
Change the links on the Security Roles Pages as described below for clarity.

### Action Items
- [x] On the Archived Accounts Page, change the wording of the "Return to Active Roles" link to "Return to Active Accounts".
- [x] On the Archived Project Page, change the wording of the "Return to Active Roles" link to "Return to Active Accounts", and change the wording of the "Return to Archived Users" link to "Return to Archived Accounts"'

### Resources/Instructions

![image](https://github.com/hackforla/tdm-calculator/assets/9939032/f1453b52-5e0a-4acc-bfb4-e3266eeca284)

![image](https://github.com/hackforla/tdm-calculator/assets/9939032/f74bd65c-a03a-4cda-935d-7f311ef16f81)

**Comment by janurag1** [comment]
Please Assign this issue to me.

**Comment by Biuwa** [comment]
@stephfrian 

Please provide update

Progress: "What is the current status of your project? What have you completed and what is left to do?"
Blockers: "Difficulties or errors encountered."
Availability: "How much time will you have this week to work on this issue?"
ETA: "When do you expect this issue to be completed?"
Pictures (if necessary): "Add any pictures that will help illustrate what you are working on.

**Comment by Biuwa** [comment]
@stephfrian 
Please provide update

Progress: "What is the current status of your project? What have you completed and what is left to do?"
Blockers: "Difficulties or errors encountered."
Availability: "How much time will you have this week to work on this issue?"
ETA: "When do you expect this issue to be completed?"
Pictures (if necessary): "Add any pictures that will help illustrate what you are working on

**Comment by Biuwa** [comment]
Returning this to the new issue column, as Stephaine is taking some time off the project
