### ISSUE TITLE
Change the email on the Privacy Policy Page to "tdm@hackforla.org"

### ISSUE THREAD

**Issue by agosmou** [hackforla/tdm-calculator#1454]
### Overview
Correct the email on the Privacy Policy Page as described below.

### Action Items
- [x] On the Privacy Policy Page, change the email at the bottom from "TDM-Calculator@hackforla.org" to 
```
<a href="mailto:tdm@hackforla.org?subject=Privacy Policy">tdm@hackforla.org</a>
```
- [ ] Change the words "to our Review Tool websites" to "to the TDM Calculator website".

### Resources/Instructions

![image](https://github.com/hackforla/tdm-calculator/assets/73868258/8a8ecf04-f87c-46a2-89d5-cc5320f9151f)
- #1421

**Comment by amanverma2908** [comment]
Hello @agosmou 
Please assign this task to me.
Thanks

**Comment by Biuwa** [comment]
> Hello @agosmou Please assign this task to me. Thanks

Hello Agosmou, are you on the TDM Calculator team?

**Comment by agosmou** [comment]
> > Hello @agosmou Please assign this task to me. Thanks
> 
> Hello Agosmou, are you on the TDM Calculator team?

Hi Ebi. yup - this is Alejandro!

**Comment by entrotech** [comment]
The email link should be 
<a href="mailto:tdm@hackforla.org?subject=privacy policy">tdm@hackforla.org</a>

**Comment by shanesween** [comment]
@amanverma2908 please see the second issue listed in this ticket, it looks like the first issue is completed but not the second

@Biuwa @entrotech @Parisajf

**Comment by Biuwa** [comment]
@shanesween, I cannot verify that @amanverma2908 is a TDM Calculator team member, so I have unassigned him and assigned you instead
