### ISSUE TITLE
QA HTML divs in the Admin FAQ page

### ISSUE THREAD

**Issue by Parisajf** [hackforla/tdm-calculator#1456]
### Overview
We need to test all the HTML pages to make sure the links are functioning.

### Action Items

- [x] Review Admin FAQ Pages
- [x] Test the HTML to ensure links to the right pages.
- [ ] Discuss with PM and Dev team

### Resources/Instructions
https://tdm-dev.azurewebsites.net/faqs

**Comment by Biuwa** [comment]
HTML Links on the FAQ page

- [ ] [City Clerk's website](https://cityclerk.lacity.org/lacityclerkconnect/index.cfm?fa=ccfi.viewrecord&cfnumber=15-0719-S19) 
- [ ] [checklist](https://tdm-dev.azurewebsites.net/faqs/true)
- [ ] [Draft Revised TDM Ordinance](https://planning.lacity.org/odocument/bb9114b3-29e3-423f-8b91-027afb242e63/Revised_DRAFT_TDMOrdinance_June2022.pdf/#page=1)
- [ ] [Chapter 3](https://planning.lacity.org/odocument/c3c9b320-4431-49ff-99d2-15b479c06074/Revised_DRAFT_TDMProgramGuidelines_June2022.pdf/#page=16)
- [ ] [Chapter 3](https://planning.lacity.org/odocument/c3c9b320-4431-49ff-99d2-15b479c06074/Revised_DRAFT_TDMProgramGuidelines_June2022.pdf/#page=16)
- [ ] [Chapter 4](https://planning.lacity.org/odocument/c3c9b320-4431-49ff-99d2-15b479c06074/Revised_DRAFT_TDMProgramGuidelines_June2022.pdf/#page=22)
- [ ] [Chapter 4](https://planning.lacity.org/odocument/c3c9b320-4431-49ff-99d2-15b479c06074/Revised_DRAFT_TDMProgramGuidelines_June2022.pdf/#page=22)
- [ ] [Chapter 4](https://planning.lacity.org/odocument/c3c9b320-4431-49ff-99d2-15b479c06074/Revised_DRAFT_TDMProgramGuidelines_June2022.pdf/#page=22)
- [ ] [Development Services Center](https://appointments.lacity.org/apptsys/Public/Account)
- [ ] [TDM Program Guidelines](https://planning.lacity.org/odocument/c3c9b320-4431-49ff-99d2-15b479c06074/Revised_DRAFT_TDMProgramGuidelines_June2022.pdf/#page=1)
- [ ] [feedback](https://tdm-dev.azurewebsites.net/publicComment)

- As of 2023-10-12: All of the hyperlinks link to the right pages except the Checklist Hyperlink and that will be addressed in Issue #1478
