### ISSUE TITLE
Improving the Project Page Experience

### ISSUE THREAD

**Issue by Parisajf** [hackforla/tdm-calculator#1457]
### Dependency
**This issue will track the sub-issues below** 

### Overview
We need to enhance the Project Page making the the process easier for the user to delete and archive a project also we need to manage different user accounts created by the client or created for test porposes.

### Action Items

- [x] #1458 
- [x] #1462 

### Resources/Instructions
(https://tdmdev.azurewebsites.net/projects)

**Comment by Biuwa** [comment]
All dependent issues have been addressed and closed.
