### ISSUE TITLE
Managing the user accounts for the test cases

### ISSUE THREAD

**Issue by Biuwa** [hackforla/tdm-calculator#1462]
### Overview

We need to have a format for the accounts we create for testing, each user creates the account and after the testing is done they need to delete the account.

### Action Items

- [ ] We need multiple users to be able to use an account for testing
- [ ] The format will be for user account for the test cases to be added to the wiki ( TDM-Dev+issue#+letter@hackforla.org) accounts should be deleted after the issue is resolved
   - Examples
      - tdm-dev+49a@hackforla.org
  Once the issue is closed the account should be deleted by the person who closed the issue.

### Resources

https://tdmdev.azurewebsites.net/projects

**Comment by entrotech** [comment]
I created "permanent" test accounts, tdm-dev+user@hackforla.org, tdm-dev+admin@hackforla.org and tdm-dev+security@hackforla.org for regular user, admin and security admin roles, respectively. The login credentials are in the 1Password vault called "TDM - Test Cases"

**Comment by Biuwa** [comment]
- @entrotech we need to discuss the different types of permissions granted to the test accounts so that they cannot be randomly deleted and also the admin account that only a Hack for LA admin can delete.

**Comment by Biuwa** [comment]
@Parisajf Please provide an update

Progress: "What is the current status of your project? What have you completed and what is left to do?"
Blockers: "Difficulties or errors encountered."
Availability: "How much time will you have this week to work on this issue?"
ETA: "When do you expect this issue to be completed?"
Pictures (if necessary): "Add any pictures that will help illustrate what you are working on
