### ISSUE TITLE
UI/UX Wireframe: About Page

### ISSUE THREAD

**Issue by KPHowley** [hackforla/tdm-calculator#147]
### Overview
Develop a basic page design for an about page that will include copy about the TDM calculator tool and Hack for La's work with The Department of Transportation to create it.

### Action Items
- Design in Figma
- Assign someone to review
- Create New Issue for front end development 

### Resources/Instructions
Figma Wireframe Link:
https://www.figma.com/file/qNgPc5lttpf0SWSwkbbWyT/TDM-Calculator?node-id=0%3A1
Follows up issue #18

**Comment by ExperimentsInHonesty** [comment]
ETA by 2/11 am. for Bonnie to review.

**Comment by KPHowley** [comment]
**First draft of the copy:** 

About the TDM Calculator

The TDM Calculator was created by Hack for LA in partnership with the L.A. Department of Transportation. Hack for LA is a non-profit organization making an impact in Los Angeles through building digital products, programs and services. Using agile methodology and user centered design, Hack for LA creates complicated tech projects that address important issues. 

The TDM Calculator was developed after the Department of Transportation came to Hack for LA looking for a tool to help them present, explain and implement a new measure aimed at transportation demand management. Working in conjunction with the city, software developers and designers, the calculator was built in short iterations, until it became what it is today. 

Our initial goal with the TDM Calculator is to create a tool that is useful both before and after the implementation of this measure. Ultimately, however, we hope to help transform Los Angeles from a city for cars into a better city for people.

To find more about Hack for LA and their work to improve Los Angeles please visit https://www.hackforla.org/

**Working Document:**
https://docs.google.com/document/d/1Ptp-_E6M1e5Fn9tT4JqrQv1NDMhPPBJIJMquTZ4Pr04/edit?usp=sharing

@ExperimentsInHonesty  to review
