### ISSUE TITLE
Migrate Application Insights Analytics to the City's Azure Account

### ISSUE THREAD

**Issue by entrotech** [hackforla/tdm-calculator#1476]
### Overview
We had Application Insights services set up for the DEV and UAT environments prior to moving them to the City's Azure account. This required creating a Log Analytics Workspace and an Application Insights resource.  Creating these resources allows Application Insights to collect operational data about the TDM application. These are currently not set up for any of the three environments. We need to decide what to do.

### Action Items
- [ ] Decide if we want to collect analytics data.
- [ ] I am not currently able to create a Log Analytics Workspace:
![image](https://github.com/hackforla/tdm-calculator/assets/9939032/15b22c3c-7a51-4bf0-b687-fa60b9883258)
because the Azure Subscription "AcitveTransportation" does not have permission to register the appropriate resource. So we would need to grant the appropriate permission to the subscription. This would probably need to be done by someone  from ITA, and involve determining the cost for this service.
- [ ] If we want to proceed, we would need to decide if we want to use a single Log Analytics Workspace, or separate ones for each environment, and then create the Application Insights resources accordingly.
- [ ] Finally, the configuration setting APPLICATION_INSIGHTS_CONNECTION_STRING would need to be set up for each environment.
- [ ] IF we elect not to implement Application Insights, there is some code that should be removed from the application.

**Comment by Biuwa** [comment]
- Add to Stakeholder deck #888

**Comment by entrotech** [comment]
Elected to remove Application Insights code from application, as no one was using Application Insights, and it would require additional Azure resources on the city's account, (possibly incurring additional usage fees?)
