### ISSUE TITLE
Keep TDM calculator read Me updated

### ISSUE THREAD

**Issue by Parisajf** [hackforla/tdm-calculator#1483]
### Overview
We need to make sure the Read me is accurate and update, all the links work and are connected to the updated pages.

### Action Items

- [ ] Check the  list of the tools under **Technology used** is accurate

### Resources/Instructions
[REPLACE THIS TEXT -If there is a website which has documentation that helps with this issue provide the link(s) here.](https://github.com/hackforla/tdm-calculator/edit/develop/README.md)

**Comment by entrotech** [comment]
@Parisajf Is this about the wiki pages, the contributing.md file, the hack for la.org website project description, or something else?

**Comment by Parisajf** [comment]
@entrotech I sent you the ReadMe. just the technologies should be looked into. Let me know if you have any questions.
