### ISSUE TITLE
Tooltip Discoverability Documentation

### ISSUE THREAD

**Issue by abbyrivard** [hackforla/tdm-calculator#1492]
### Overview
Write and upload the documentation to the Research Wiki for the last round of testing completed (Tooltip Discoverability).

### Action Items
Complete documentation in the following steps:

- [x] Review documentation outline on Google Drive
  - [x] Refer to [Google Doc](https://docs.google.com/document/d/1RMy_XBMc0LssWMMonHqQFGTWxuS932CNd3Bh-hEEb9o/edit)
  - [x] clean up the drive

- [x] Make any necessary edits to documentation
  - [x] Combine multiple documentation sources into one
  - [x] Recreate the structure of wiki page

- [x] Add to the [Wiki Page](https://github.com/hackforla/tdm-calculator/wiki/Tooltip-Usability-Test)
  - [x] Have UXR team review and add notes/comments to identify areas that still need refining
     - [x] make necessary edits 
  - [x] Check links for Wiki page using incognito mode
     - [x]  Adjust links as needed
     - [x] Add needed comments on links that require further access or logins

- [x] Present to Bonnie for Approval

### Resources/Instructions

- [Documentation Google Doc](https://docs.google.com/document/d/1RMy_XBMc0LssWMMonHqQFGTWxuS932CNd3Bh-hEEb9o/edit)

- [Wiki Page to upload documentation on](https://github.com/hackforla/tdm-calculator/wiki/Tooltip-Usability-Test)

- #1219

**Comment by abbyrivard** [comment]
Abby, Melissa, and Jane have been working on this issue weekly. Have combined most of the documentation but need to finalize a couple links and then we can confirm if it's good to convert to wiki with Bonnie

**Comment by Biuwa** [comment]
**Please provide an update:**

1. **Progress**_(What is the current status of your project? What have you completed, and what is left to do)_:
2. **Blockers**_(Difficulties or errors encountered)_:
3. **Availability**_(How much time will you have this week to work on this issue)_:
4. **ETA**_(When do you expect this issue to be completed)_:
5. **Pictures** _(if necessary)(Add any pictures that will help illustrate what you are working on)_:

**Comment by Biuwa** [comment]
@abbyrivard, @melissaperry09 

**Please provide an update:**

1. Progress(What is the current status of your project? What have you completed, and what is left to do):
2. Blockers(Difficulties or errors encountered):
3. Availability(How much time will you have this week to work on this issue):
4. ETA(When do you expect this issue to be completed):
5. Pictures (if necessary)(Add any pictures that will help illustrate what you are working on)

**Comment by abbyrivard** [comment]
@Biuwa @melissaperry09 

Update:

1. Progress: 
    a. Current Status: Need to meet with Jane for final review and then ready for review by PM team. 
    b. Completed Objectives: 
        - [] Finalized [Decision Records](https://github.com/hackforla/tdm-calculator/wiki/Decision-Records-on-Solutions-Adopted)
        - [] [RP003: Research Plan](https://docs.google.com/document/d/1VTJnYr4C--v2zKEHkSww_-oc07JTg4P0VkiV1jTauGQ/edit) - [need PM approval]
        - [] Finalized Wiki Documentation to be reviewed by PMs
3. Blockers: 
    a. Timing and gathering past known knowledge of previous UXR team. We meet once a week on Mondays with Jane so we can further progress the documentation. 
    b. Retro-active creation of documents because they are time intensive and require some past UXR team knowledge
    c.  Retro-active organization of Google Drive. Has made finding documents for wiki page difficult and slowed process as we work to organize all the files. 
5. Availability: Flexible availability. Have next meeting at 4PM PST Monday (02/12/2024) with Jane 
6. ETA: 02/15/2024
7. Pictures/Links: 
    a. [Wiki Documentation](https://github.com/hackforla/tdm-calculator/wiki/Tooltip-Usability-Test)
    b. [Research Plan](https://docs.google.com/document/d/1VTJnYr4C--v2zKEHkSww_-oc07JTg4P0VkiV1jTauGQ/edit)

**Comment by ExperimentsInHonesty** [comment]
Review of https://github.com/hackforla/tdm-calculator/wiki/Tooltip-Usability-Test wiki page

> Therefore, the UXR team determined that more focused testing on tooltip discoverability was needed to determine why this issue had not been resolved in the previous two rounds of testing

Suggested update, previous design iterations

---

Where it says
>Referenced [RP002: Usability Test #2](https://github.com/hackforla/tdm-calculator/wiki/Usability-Testing-Round-2#i---test-plan).

Add more words to communicate its an older test

---

The spreadsheet dosent have the communication gudes standards applied so if someone opens it, it won't be clear which project its for
Created [Participant Tracker Template](https://docs.google.com/spreadsheets/d/1Ye7jOaZ7_nDwAhX-P8H3NVzVdfJ7OOqB__dquHj6ikw/edit#gid=1710408819).

---

**Comment by abbyrivard** [comment]
UXR Notes for Changes

**Comment by Gbondy15** [comment]
UXR Notes for Changes in the ToolTip Usability Test page -- (Gary)

1 Prerequisites
   i. Test Plan
      - Are stakeholders/lay people going to know what DR means?
      - https://github.com/hackforla/tdm-calculator/wiki/DR:-More-focused-testing-on-tooltip-discoverability-is-needed-to-determine-why-previous-design-iterations-did-not-resolve-this-issue 
         - Perhaps shorten this name to DR: Enhanced tooltip discoverability testing needed to assess current design limitations?
      - https://docs.google.com/document/d/1VTJnYr4C--v2zKEHkSww_-oc07JTg4P0VkiV1jTauGQ/edit
         - Limited access. Need to sign into Google account. Replace Google Doc with (Design team's?) PDF?
      - https://docs.google.com/document/d/1PpW7Kd_gpwmUaVTAcOjnWhpjQSD_ND5-J5qlEqlG7IA/edit
          - Limited access. Need to sign into Google account.
      - https://docs.google.com/spreadsheets/d/1Ye7jOaZ7_nDwAhX-P8H3NVzVdfJ7OOqB__dquHj6ikw/edit#gid=1710408819
          - Limited access. Need to sign into Google account.

2 Preparation

- There is a note [webpage needs updating] must update before launching next study?
   - ii: Target users -- Do we need a link to this or can we just tell them, "We decided to use HfLA participants who are unaware of TDM site."
   - iii: Sample Project Landing Pages
    -https://sites.google.com/d/1zHVDosgbTyi8qjk1iCZNIKxgaicD5MdP/p/1Sg7qxPj2JKZn0ZQeVdYQXeZ_2oT-N0Dx/edit
       - Limited access. Need to sign into Google account.
    - Sample test cases
       - Limited access. Need Google account.
    - 2 Landing pages UAT & Dev
       - Limited access. Need Google account.
    
3 Recruitment
- All links here have limited access. Need Google account

4 Interview Logistics
- Interview Materials
   - Both PR003 and background image have limited access. Need Google account
-UXRs Training
   - Link is limited access. Need Google account

5 Results
- Interview records requires Google account
- ii: Data Analysis: RP003 requires Google account
-  Findings' links require Google account

**Comment by abbyrivard** [comment]
Met with Bonnie for final review and got approval on wiki documentation. Issue is now closed

**Comment by cheesarah** [comment]
Hi,

I’m no longer on the team.

Could you please remove me? 

Sarah

**Comment by melissaperry09** [comment]
@cheesarah This is an old issue that was closed with no one assigned to it. As we are winding down the project, we are retroactively adding former contributors so that everyone receives credit on GitHub for the work they did on the project. Please let me know if you would still like your name removed.
