### ISSUE TITLE
BUG: [react-tooltip] "true" is not a valid `border` on Create Project

### ISSUE THREAD

**Issue by ZekeAranyLucas** [hackforla/tdm-calculator#1510]
### Overview
ToolTip.js#21 initializes the border style improperly

`      border={true}`

need to set the border to something specific.
https://react-tooltip.com/docs/examples/styling#changing-the-border

### REPRO
Not sure how to trigger toolip, but browsing around I see this in the console. 
```
react-tooltip.min.mjs:7 [react-tooltip] "true" is not a valid `border`. 
    at B (http://localhost:3000/static/js/bundle.js:161844:9)
    at ToolTip (http://localhost:3000/static/js/bundle.js:26637:3)
    at SidebarPointsPanel (http://localhost:3000/static/js/bundle.js:21826:5)
    at div
    at div
    at div
    at div
    at Sidebar (http://localhost:3000/static/js/bundle.js:25345:3)

```

**Comment by ZekeAranyLucas** [comment]
Not sure if there is really supposed to be a border because there isn't one.  ask design?

**Comment by heejung-hong** [comment]
It appears the border={true} has been removed from ToolTip.js and the error message no longer visible in the console.

**Comment by lkim016** [comment]
This fix got solved on another unknown issue.
