### ISSUE TITLE
BUG: Warning: Received `false` for a non-boolean attribute `className` on FAQ page

### ISSUE THREAD

**Issue by ZekeAranyLucas** [hackforla/tdm-calculator#1511]
### Overview
FaqView.jsx#378 initializes the border style improperly

`        <div className={admin && classes.editCategoryContainer}>
`
### Action Items
[] make sure the proper class name is used for both admin true and false 
[] replace boolean expression with ternary

**Comment by HuijungYoon** [comment]
can i have with this issue?

**Comment by ZekeAranyLucas** [comment]
Take it. To test your changes make sure to run as both admin and non-admin user.
