### ISSUE TITLE
BUG: ResizeObserver loop completed with undelivered notifications.

### ISSUE THREAD

**Issue by ZekeAranyLucas** [hackforla/tdm-calculator#1512]
### Overview 
This is a problem that is only visible on the dev server because that's when the overlay pops up.  But this is actually a signal of something more sinister in the code. These kinds of problems can cause hangs, unresponsive pages, or just a bunch of jitter.  Right now the browser recovers by breaking the loop for us.

Learn more here: 
* https://developer.mozilla.org/en-US/docs/Web/API/ResizeObserver
* https://webpack.js.org/configuration/dev-server/#overlay

### REPRO
when navigating from "Create Project" or "Feedback" to "My Projects" there is an error overlay
1. run the dev server locally (overlay is only visible there).
2. create at least one project
3. go to "My Projects"
4. go to "Create Project" or "Feedback"
5. go to "My Projects"

### RESULTS:
Error overlay as described below.
```
ERROR
ResizeObserver loop completed with undelivered notifications.
    at handleError (http://localhost:3000/static/js/bundle.js:128757:58)
    at http://localhost:3000/static/js/bundle.js:128776:7
```

### EXPECTED:
no error

NOTE: doesn't repro on refresh of "MyProjects" or navigation from "About" and "FAQ".  

Might be something to do with scroll bars

_Originally posted by @ZekeAranyLucas in https://github.com/hackforla/tdm-calculator/issues/1508#issuecomment-1808771189_

**Comment by ZekeAranyLucas** [comment]
I did some digging into this, and the key suspects are tooltips or similar overlay components.

**Comment by Biuwa** [comment]
@ZekeAranyLucas 
**Please provide an update:**

1. Progress(What is the current status of your project? What have you completed, and what is left to do):
2. Blockers(Difficulties or errors encountered):
3. Availability(How much time will you have this week to work on this issue):
4. ETA(When do you expect this issue to be completed):
5. Pictures (if necessary)(Add any pictures that will help illustrate what you are working on)
