### ISSUE TITLE
On My Projects Page, Implement UI for operations on Multiple Projects

### ISSUE THREAD

**Issue by entrotech** [hackforla/tdm-calculator#1520]
### Overview
Users need to be able to perform some My Projects Page operations on more than one project at a time. Add checkboxes to the beginning of each row and a toolbar above the grid with toolbar buttons to effect the appropriate actions.

### Action Items
- [x] Add a checkbox to the header row and beginning of each project row in the grid.
- [x] Add a toolbar with icons for the available operations.
- [x] Implement logic to enable/disable and, in some cases, change the icon and operation as described in the document linked below in the Resources section.
- [ ] Hook up each toolbar button to code that implements the corresponding operation

### Resources/Instructions
REPLACE THIS TEXT -If there is a website which has documentation that helps with this issue provide the link(s) here.

**Comment by Biuwa** [comment]
**Please provide an update:**

1. **Progress**_(What is the current status of your project? What have you completed, and what is left to do)_:
2. **Blockers**_(Difficulties or errors encountered)_:
3. **Availability**_(How much time will you have this week to work on this issue)_:
4. **ETA**_(When do you expect this issue to be completed)_:
5. **Pictures** _(if necessary)(Add any pictures that will help illustrate what you are working on)_:

**Comment by Biuwa** [comment]
@agutiernc, @ZekeAranyLucas 

** Please provide an update:**

Progress(What is the current status of your project? What have you completed, and what is left to do):
Blockers(Difficulties or errors encountered):
Availability(How much time will you have this week to work on this issue):
ETA(When do you expect this issue to be completed):
Pictures (if necessary)(Add any pictures that will help illustrate what you are working on)

**Comment by agutiernc** [comment]
Progress: I have refactored the hide feature and implemented the delete feature. I am currently working on the rules check and need to add the tooltips to the toolbar menu. The CSV feature will be a separate issue.

Blockers: Implementing rules

Availability: Afternoons/Evenings this week

ETA: EoW

Pictures: N/A
