### ISSUE TITLE
Spacing issues with the checklist

### ISSUE THREAD

**Issue by Biuwa** [hackforla/tdm-calculator#1545]
### Overview
Our checklist spacing needs to be adjusted in order to ensure uniformity

### Action Items

- Add a vertical space between the `Create Project` and `p. 1 General project information` 

### Resources/Instructions
<img width="516" alt="Screenshot 2023-11-29 at 3 16 14 PM" src="https://github.com/hackforla/tdm-calculator/assets/98936028/bdb35f52-1ec3-4982-8c70-47b8eeec3fd8">

**Comment by Jonathanko52** [comment]
[](url)
![Screenshot 2023-11-29 at 4 44 53 PM](https://github.com/hackforla/tdm-calculator/assets/30099154/2bf94ccc-24ee-43f7-93d8-417b40c5e8a5)
Like this?

**Comment by lchauha** [comment]
Hi @Jonathanko52 I would like to work on this issue. Can you please assign this to me?

**Comment by Jonathanko52** [comment]
@Ichauha

It looks like @heejung-hong has decided to pick up the task.
