### ISSUE TITLE
[My Projects] BUG: Unexpected Application Error! Cannot read properties of undefined (reading 'toLowerCase')

### ISSUE THREAD

**Issue by ZekeAranyLucas** [hackforla/tdm-calculator#1552]
### Overview
In My Projects, clicking on the header for the context menu (kebab menu) column has no effect but causes an error in the browser console. 
### REPRO
1. login
2. navigate to "My Projects" : http://localhost:3000/projects
3. on the far right is a column header without text (rows contain a kebab button)
4. click on the blank header above the kebabs.

### EXPECTED
Nothing.  it should not indicate the header is even clickable since it doesn't make sense.

### RESULTS
```
Unexpected Application Error!
Cannot read properties of undefined (reading 'toLowerCase')
TypeError: Cannot read properties of undefined (reading 'toLowerCase')
    at descCompareBy (http://localhost:3000/static/js/bundle.js:25989:29)
    at http://localhost:3000/static/js/bundle.js:26001:83
    at http://localhost:3000/static/js/bundle.js:26006:21
    at Array.sort (<anonymous>)
    at stableSort (http://localhost:3000/static/js/bundle.js:26005:20)
    at ProjectsPage (http://localhost:3000/static/js/bundle.js:26080:26)
    at renderWithHooks (http://localhost:3000/static/js/bundle.js:112927:22)
    at updateFunctionComponent (http://localhost:3000/static/js/bundle.js:115809:24)
    at beginWork (http://localhost:3000/static/js/bundle.js:117521:20)
    at beginWork$1 (http://localhost:3000/static/js/bundle.js:122472:18)
💿 Hey developer 👋

You can provide a way better UX than this when your app throws errors by providing your own ErrorBoundary or errorElement prop on your route.
```
Debugger Console shows something similar and a few followups

**Comment by Biuwa** [comment]
**Please provide an update:**

1. **Progress**_(What is the current status of your project? What have you completed, and what is left to do)_:
2. **Blockers**_(Difficulties or errors encountered)_:
3. **Availability**_(How much time will you have this week to work on this issue)_:
4. **ETA**_(When do you expect this issue to be completed)_:
5. **Pictures** _(if necessary)(Add any pictures that will help illustrate what you are working on)_:
