### ISSUE TITLE
Engineer tests and validation for 'Email' Web API requests

### ISSUE THREAD

**Issue by agosmou** [hackforla/tdm-calculator#1554]
### Overview

We need to create a workflow for testing all 'email' endpoints. We will need to set up tests and web API request validation for the endpoints.

### Details | Scope of Work
We need to test the API endpoints using 'jest'  

### Action Items

- [x] write all tests for endpoints and documentation

### Resources/Instructions

Testing
- https://jestjs.io/
- https://testcontainers.com/

**Comment by Biuwa** [comment]
**Please provide an update:**
1. **Progress**_(What is the current status of your project? What have you completed, and what is left to do)_:
2. **Blockers**_(Difficulties or errors encountered)_:
3. **Availability**_(How much time will you have this week to work on this issue)_:
4. **ETA**_(When do you expect this issue to be completed)_:
5. **Pictures** _(if necessary)(Add any pictures that will help illustrate what you are working on)_:

**Comment by agosmou** [comment]
Still working on this! Was out of town for a while

1. in progress
2. no blockers
3. ill jump back into this late next week (started up school)
4. If I dont get it done by next weekend, then feb 12
5. na

**Comment by Biuwa** [comment]
@agosmou 

**Please provide an update:**

1. Progress(What is the current status of your project? What have you completed, and what is left to do):
2. Blockers(Difficulties or errors encountered):
3. Availability(How much time will you have this week to work on this issue):
4. ETA(When do you expect this issue to be completed):
5. Pictures (if necessary)(Add any pictures that will help illustrate what you are working on)

**Comment by agosmou** [comment]
1. In progress
2. n/a
3. not available until after feb12th
4. a few days after feb12th
5. n/a
