### ISSUE TITLE
Implement the "Rename Snapshot" feature

### ISSUE THREAD

**Issue by entrotech** [hackforla/tdm-calculator#1556]
### Overview
User should be able to rename an existing snapshot from the context menu on the My Projects Page.

### Action Items
- [x] Create a Project_Rename stored procedure that is similar to the Project_Snapshot stored procedure, except that it does not update the dateSnapshotted column.
- [x] Create a web api endpoint for PUT to /api/projects/rename that will rename a project. The web api router should use the jwtSession.valdiateUser middleware to verify that the request is from a logged-in user, The request should have the same body as the /api/projects/snapshot endpoint.
- [x] Create a client-side service that makes the PUT request described above.
- [x] Modify the context menu to display the "Rename Snapshot menu item in the context menu as shown in the below screenshot when
  - [x] The project is a snapshot (dateSnapshotted is not null)
  - [x] The project is owned by the logged-in user
  - [x] If the project is not a snapshot, the existing "Convert To Snapshot menu Item should be shown instead.
  - [x] If the project is a snapshot, but not owned by the logged-in user, the menu item should be disabled (greyed-out and not responsive to click events.
  - [ ] Create a dialog as shown below that prompts the user to supply the new project name. When the user clicks "Rename", the dialog will close and the client service called to effect the snapshot re-naming. You should consult with the UI/UX design team for the exact wording on the dialog, but use the existing SnapshotModalDialog.js in the code for the implementation code that should be used, so we use our "standard" modal dialog design.

### Resources/Instructions
![image](https://github.com/hackforla/tdm-calculator/assets/9939032/9dacf575-b7e2-4fe1-9ee4-b67dbc590f02)
![image](https://github.com/hackforla/tdm-calculator/assets/9939032/339573a0-d7f7-43fd-837e-2627ba28549a)

**Comment by Jonathanko52** [comment]
1. New Modal created.

<img width="454" alt="Screenshot 2024-01-03 at 3 51 55 PM" src="https://github.com/hackforla/tdm-calculator/assets/30099154/d8439c26-5dd6-4340-9cb0-9e6868e19311">

2. Project Context Menu now:
     1. Shows the "convert to snapshot" option for non-snapshot projects.
     2. Shows the "rename snapshot" option for snapshot projects when user ID matches.
     3. Shows a disabled, greyed out "rename snapshot" option for snapshots projects where user ID does not match.
     
<img width="225" alt="Screenshot 2024-01-03 at 2 43 15 PM" src="https://github.com/hackforla/tdm-calculator/assets/30099154/bc93fcd2-778e-4317-a892-17f6ae33edbb">

3. Client-side PUT and web API endpoint setup. 

Todo:

1. Verification for whether the call comes from a logged-in user is still in progress.

2. Project_Rename stored procedure not yet created.
