### ISSUE TITLE
Document CSS properties for the Feedback page

### ISSUE THREAD

**Issue by heejung-hong** [hackforla/tdm-calculator#1562]
### Overview
In order to convert SCSS to JSS where possible, the css properties of the Feedback page will be documented for reference.

### Action Items
- [x] Use the Google Sheets link below to document the css properties of the Feedback tab.
https://docs.google.com/spreadsheets/d/1eWFAv9TTyq6steNO1tyPFfJ0LciRKnDT9W4sAolrg0g/edit?usp=sharing

**Comment by Biuwa** [comment]
**Please provide an update:**

1. **Progress**_(What is the current status of your project? What have you completed, and what is left to do)_:
2. **Blockers**_(Difficulties or errors encountered)_:
3. **Availability**_(How much time will you have this week to work on this issue)_:
4. **ETA**_(When do you expect this issue to be completed)_:
5. **Pictures** _(if necessary)(Add any pictures that will help illustrate what you are working on)_:

**Comment by Tomomi-K1** [comment]
I've done with with this task.
