### ISSUE TITLE
Cleanup CSS and set project standards

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/tdm-calculator#157]
### Overview
We have been doing a lot of quick and dirty production styling on this project.  In preparation for meeting with multiple city departments and them looking more deeply at our code, we need to clean things up and set new project standards)

### Action Items
- [ ] fix css so that it reflects the fonts and styling and remove inline styles. Note: some of the pages have inline align center styling to differentiate them from the calculator pages which are top justified.
- [ ] check @ mentions for this [comment on issue #71 ](https://github.com/hackforla/tdm-calculator/issues/71#issuecomment-571271845) re warning messages.
- [ ] the navigation on the calculator pages, is being pushed way down the page, so on some pages without very much content, you have to scroll to get to the nav at the bottom.  
![Screen Shot 2020-01-06 at 11 21 17 AM](https://user-images.githubusercontent.com/37763229/71842514-ae7e2c00-3076-11ea-892d-0107dc9ccd1e.png)

### Resources/Instructions
[Figma](https://www.figma.com/file/qNgPc5lttpf0SWSwkbbWyT/TDM-Calculator?node-id=105%3A0 )
[Live application](http://tdm-calc.herokuapp.com)
[Github Repository](https://github.com/hackforla/tdm-calculator)
[Google Folder](https://drive.google.com/drive/u/1/folders/1XI0ZP21DoNM8uTKVJkRBiMhtP652X8KM)

**Comment by ExperimentsInHonesty** [comment]
@bfojas mentioned you were going to use JSS.  His notes via slack were "...It makes it easier to see where the styles are coming from and makes it easier to keep our styles from being overridden by other parts of the app."

@mmorgs please note whatever decisions you make here and why so we can have a decision record.  If someone else participated in the conversation, feel free to put the relevant parts of the conversation into your notes.

**Comment by entrotech** [comment]
The issue with the nav buttons appearing below the visible part of the page is somewhat better, but not completely resolved. What I want for the CalculationWizard is for the page to take the entire height of the browser window, regardless of the display resolution or user's page zoom setting. The browser window should not show a vert scrollbar at all.  The sidebar should occupy the left 389 pixels (per Nicole) and whatever height is available. The content area (ie. the area to the right of the sidebar should occupy at least the full height of the available area and display the nav bar near the bottom if  the content does not overflow vertically. If the content does overflow vertically, then there should be a vert scrollbar for just the content area.  I'm pretty close to having this now, except for the part about controlling the height of the main div under all device sizes and browser zoom levels.

**Comment by ExperimentsInHonesty** [comment]
@mmorgs please update this issue with:
1. Progress
2. Blocks
3. Availability
4. Eta to completion

**Comment by mmorgs** [comment]
pushed a PR - assigned to @fyliu to code review

**Comment by fyliu** [comment]
@mmorgs I found a few issues:

- The project description textarea is missing
![Screenshot from 2020-01-23 11-35-59](https://user-images.githubusercontent.com/1160105/73018361-59f8e180-3dd6-11ea-9e79-c0b10b4150aa.png)

- Slightly less vertical space under the first category
![Screenshot from 2020-01-23 11-39-01](https://user-images.githubusercontent.com/1160105/73018366-5b2a0e80-3dd6-11ea-8f19-8370d8b9386a.png)

- Styling at the bottom of the summary page
![Screenshot from 2020-01-23 11-39-19](https://user-images.githubusercontent.com/1160105/73018371-5d8c6880-3dd6-11ea-9149-b8b18a4b07c2.png)
