### ISSUE TITLE
Clean up FAQ 

### ISSUE THREAD

**Issue by irisslee** [hackforla/tdm-calculator#1573]
### Overview
Clean up FAQ files and functions from server to client

As prerequisite to 
#1531

**Comment by Biuwa** [comment]
**Please provide an update:**

1. **Progress**_(What is the current status of your project? What have you completed, and what is left to do)_:
2. **Blockers**_(Difficulties or errors encountered)_:
3. **Availability**_(How much time will you have this week to work on this issue)_:
4. **ETA**_(When do you expect this issue to be completed)_:
5. **Pictures** _(if necessary)(Add any pictures that will help illustrate what you are working on)_:
