### ISSUE TITLE
Remove the N/A columns from the CSV export file

### ISSUE THREAD

**Issue by entrotech** [hackforla/tdm-calculator#1574]
### Overview
On the My Projects Page, you can generate a CSV file containing project information. In the 1/9/24 stakeholder meeting, we decided that is was not necessary to include the columns representing multiple choice strategies where the N/A option is selected, since that means the strategy is not used. This will also apply when the feature is implemented for multiple-project selection

### Action Items
- [x] Implement

**Comment by Biuwa** [comment]
**@heejung-hong**

**Please provide an update:**

1. Progress(What is the current status of your project? What have you completed, and what is left to do):
2. Blockers(Difficulties or errors encountered):
3. Availability(How much time will you have this week to work on this issue):
4. ETA(When do you expect this issue to be completed):
5. Pictures (if necessary)(Add any pictures that will help illustrate what you are working on)
6.

**Comment by heejung-hong** [comment]
1. **Progress:** Currently reviewing requirements.
2. **Blockers:** Would like to wait till issue 1604 is approved by the stakeholders before working on this issue.
3. **Availability:** Weekdays after 6pm
4. **ETA:** 03/14
