### ISSUE TITLE
Design Mockup: Redesign the My Projects Filtering UI

### ISSUE THREAD

**Issue by Biuwa** [hackforla/tdm-calculator#1578]
### Overview
We need to redesign the filter user experience so that its self explanatory
### Action Items
- [x] ~Change the funnel icon (e.g to an arrow)~
- [x] ~Let the placement of the icon change with the user's interaction (e.g right facing to open, left facing to close~
- [ ] Reimagine how the filters could work

### Resources/Instructions
<img width="1284" alt="Screenshot 2024-01-14 at 10 13 15 AM" src="https://github.com/hackforla/tdm-calculator/assets/98936028/fe7b4125-f980-4ea4-b1a6-52f903d24976">

**Comment by yiranshan** [comment]
1. Progress: communicated with teammates about how to approach this problem. Watched the weekly video recording and thought maybe the whole search panel should be moved to the side like the other pages. 
2. Blockers: Not sure what criteria are final for the project page. mock-up and test site should have different items. 
3. Availability: most nights from 9 pm to 11 pm. 
4. ETA: after the next weekly meeting, once all questions cleared and talked to teammates, we should be able to finish all 3 issues around search functions. 
![#1578 - ONGOING](https://github.com/hackforla/tdm-calculator/assets/79798670/049c9476-cf28-4141-acb7-8fd3cf46f071)
<img width="537" alt="Screen Shot 2024-01-27 at 2 07 11 PM" src="https://github.com/hackforla/tdm-calculator/assets/79798670/f2b0e571-6068-4420-b80f-a52f5cb11f5c">

**Comment by yiranshan** [comment]
**Progress**
1. made a new filter button option based on the current design and setup. (see image 1 and 2)
2. designed a new version of searching and filtering inspired by LinkedIn and Google sheet (see image 3 and 4)
**Blockers**
1. still need to confirm what items would be included in the chart 
2. don't know if it's doable for dev team
**Availability**
6 hours min
**ETA**
hopefully the end of the week. 
![Filter Side Placement (#1579)](https://github.com/hackforla/tdm-calculator/assets/79798670/dc2eda0c-982f-4cfc-997f-bc5d254ad2da)
![Filter Side Placement (#1579) (1)](https://github.com/hackforla/tdm-calculator/assets/79798670/df2d7782-84dc-4c1c-83f0-8b089fd35ac8)

![#1578 - 02 06 2024 version 2](https://github.com/hackforla/tdm-calculator/assets/79798670/1745692e-0e44-4a4a-ad7f-f5e557cafc29)
![#1578 - 02 06 2024 version 3](https://github.com/hackforla/tdm-calculator/assets/79798670/3da3f61b-b0d1-41f2-98d1-63ea8c75a109)

**Comment by yiranshan** [comment]
Meeting summary:
1. focus on the google Sheets version
2. main search bar can search name, address, description, alt#
3. take in the toolbox that’s been developed into the mock-up 
4. move the search bar to the top right side
5. create a search box for each column name
6. default items for each page with a selection of how many items to add

<img width="1363" alt="Screen Shot 2024-02-13 at 11 08 20 PM" src="https://github.com/hackforla/tdm-calculator/assets/79798670/37e66c9c-6a74-42d1-9f03-99026e648fc2">
<img width="1366" alt="Screen Shot 2024-02-13 at 11 06 17 PM" src="https://github.com/hackforla/tdm-calculator/assets/79798670/6195f201-9441-4e48-b3c5-20bcb0b67606">
<img width="1368" alt="Screen Shot 2024-02-13 at 11 06 03 PM" src="https://github.com/hackforla/tdm-calculator/assets/79798670/fa86ce0d-b066-4744-a4b8-7861e8384082">

Update issue on Github 02.13.2024:
Progress: 
- finalized version 3 which it simulates google sheets on the filtering system
- changed page selection and added items per page option
- pulled in the box on left corner
- updated keywords in the general search box

   **Click [here](https://www.figma.com/proto/nD9QK56Mzq7xNSaSUoeGx0/TDM-Calculator?type=design&node-id=11997-885&t=Tz8SJ4c1v4FRan2H-1&scaling=scale-down&page-id=2499%3A11472&starting-point-node-id=11997%3A885&mode=design) for prototype.**

Blockers: not sure how the toolbox would interact with the table 
Availability: unsure
ETA: depends on the user feedback

**Comment by ExperimentsInHonesty** [comment]
https://www.permitla.org/ipars/permit_help.cfm#:~:text=The%2010%2Ddigit%20number%2C%20with,the%20plans%20were%20first%20submitted

This is a 10-digit number assigned by the PCIS system when an applicant first applies for a permit. The purpose of this number is to identify the plans that are associated with the application or permit. There is a "one-to-many" relationship between the plan check number and the associated application or permit number(s). If an application or permit does not require plan check, this number is referred to as a "Job Number". Otherwise, it is referred to as a "Plan Check Number" (PC Number) . The 10-digit number, with the format TYYOO#####, has the following meaning:
--
  | T = The type of plans that were checked (B = Building, E = Electrical, G = Grading, M = Mechanical, X = Express Permit [no plan check required]).
  | YY = The 2-digit year when the plans were first submitted.
  | OO = A 2-digit code that corresponds to the LADBS branch office where the plans were submitted (and usually reviewed). It can have the following values: LA = Metro, VN = Van Nuys, WL = West LA, SP = San Pedro, SL = South LA.
  | ##### = A 5-digit sequential number so the entire 10-

**Comment by yiranshan** [comment]
02.15.2024 before meeting
Progress: 
changed sort by for each filter
added states for sort buttons
added top labels for different types of projects
autocomplete for some filters

[Prototype link (old)](https://www.figma.com/proto/nD9QK56Mzq7xNSaSUoeGx0/TDM-Calculator?type=design&node-id=12040-9276&t=oCoaBh2DPZ8rXTUs-1&scaling=scale-down&page-id=2499%3A11472&starting-point-node-id=11997%3A885&mode=design)

<img width="1314" alt="Screen Shot 2024-02-15 at 11 41 35 PM" src="https://github.com/hackforla/tdm-calculator/assets/79798670/f8fd077e-47a3-4ca9-9043-2c2e9b7a1de9">
<img width="1313" alt="Screen Shot 2024-02-15 at 11 41 23 PM" src="https://github.com/hackforla/tdm-calculator/assets/79798670/4a48a94d-c957-470b-9b96-0681707e352b">


02.15.2024 after the meeting:
Progress: 
changed sort by for some filters
auto-complete follow Google sheet
added modified and deleted items 
added page drawer
got rid of top labels

[Updated prototype link](https://www.figma.com/proto/nD9QK56Mzq7xNSaSUoeGx0/TDM-Calculator?type=design&node-id=12064-10415&t=sU0XqEA8xPZtF2pg-1&scaling=scale-down&page-id=2499%3A11472&starting-point-node-id=11997%3A885&mode=design)

<img width="1697" alt="Screen Shot 2024-02-15 at 11 39 14 PM" src="https://github.com/hackforla/tdm-calculator/assets/79798670/693c7c8d-5178-4d9e-a602-ee62001935ff">
<img width="1693" alt="Screen Shot 2024-02-15 at 11 39 33 PM" src="https://github.com/hackforla/tdm-calculator/assets/79798670/d419a939-21c6-4b41-9a01-8466e1dd110e">
<img width="1698" alt="Screen Shot 2024-02-15 at 11 39 58 PM" src="https://github.com/hackforla/tdm-calculator/assets/79798670/9c3ec22e-1223-4dcc-9c3b-54603f59b7ab">
<img width="1698" alt="Screen Shot 2024-02-15 at 11 40 12 PM" src="https://github.com/hackforla/tdm-calculator/assets/79798670/89ecb05f-172d-4726-9b30-0bcf93cce0a5">
<img width="1704" alt="Screen Shot 2024-02-15 at 11 49 26 PM" src="https://github.com/hackforla/tdm-calculator/assets/79798670/eb5d8d8b-3016-4980-a9d7-1642683fcae0">

**Comment by yiranshan** [comment]
Update issue on Github 02.22.2024:
Progress: 
     for user view:
Edited item per page to include “all”
Added the 3 dots back to the right
added select all and clear all to address the filter and increased the width to remove the scroll bar
Abbreviated DRO and removed development review 
Add submitted
removed “on” in created and modified
no content for non-submitted projects for certain columns
[Prototype link](https://www.figma.com/proto/nD9QK56Mzq7xNSaSUoeGx0/TDM-Calculator?type=design&node-id=12137-1607&t=t3ZY0yWf4IQL4xPD-1&scaling=scale-down&page-id=2499%3A11472&starting-point-node-id=11997%3A885&mode=design)
<img width="1702" alt="Screen Shot 2024-02-22 at 2 41 32 PM" src="https://github.com/hackforla/tdm-calculator/assets/79798670/8f05c94d-bb01-4cbb-ae0c-4ae8894f5761">
<img width="1700" alt="Screen Shot 2024-02-22 at 2 41 21 PM" src="https://github.com/hackforla/tdm-calculator/assets/79798670/08b5684e-81e2-45a6-b810-0ab9d3e5226c">
<img width="1701" alt="Screen Shot 2024-02-22 at 2 41 11 PM" src="https://github.com/hackforla/tdm-calculator/assets/79798670/e6c638da-21f7-41d3-be8d-f8dd6ad31ebb">

**Comment by yiranshan** [comment]
Update issue on Github 02.29.2024:
Progress: 
     for user view:
change page to right justified
add scroll bar to the bottom (don’t include the check box and the 3 dots)
change “clear selection” to “clear all selection”
Keep “DRO” as is for now and see if need to update
Make a mock-up for long address wrap

      Please see the [Prototype here](https://www.figma.com/proto/nD9QK56Mzq7xNSaSUoeGx0/TDM-Calculator?type=design&node-id=12173-2052&t=9jie4ZgndIHK1zt4-1&scaling=scale-down&page-id=2499%3A11472&starting-point-node-id=11997%3A885&mode=design) **(address filter might need a refresh page to look proper)**

<img width="1373" alt="Screen Shot 2024-02-29 at 4 29 51 PM" src="https://github.com/hackforla/tdm-calculator/assets/79798670/459bb047-3920-42ef-9603-f82146a0aa31">
<img width="1369" alt="Screen Shot 2024-02-29 at 4 29 39 PM" src="https://github.com/hackforla/tdm-calculator/assets/79798670/00c6eb72-5910-4894-b1c5-fceb9e5181b2">
<img width="1372" alt="Screen Shot 2024-02-29 at 4 29 30 PM" src="https://github.com/hackforla/tdm-calculator/assets/79798670/4c6ef2b3-dec4-44e4-a24c-cbd31a20e4d4">

for admin view -- in progress

**Comment by Biuwa** [comment]
**2023-03-05 STAKEHOLDERS' MEETING FEEDBACK NOTES**

- [ ] Change name of page to My Projects, not active projects
- [ ] Gray out the trashcan or other top icon if it's not available
- [ ] Move the showing and hiding options for deleted projects to the status drop-down making it a separate option from what Draft/Snapshot/Both radio button

**Comment by yiranshan** [comment]
Got it! Thank you!

**Comment by ExperimentsInHonesty** [comment]
@yiranshan are these changes completed?  Please provide update
1. Progress: "What is the current status of your project? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"
5. Pictures or links* (if necessary): "Add any pictures or links that will help illustrate what you are working on."

* remember to add links to the top of the issue if they are going to be needed again.

**Comment by yiranshan** [comment]
**Progress:** 
     for user view:
 Change the name of the page to My Projects, not active projects
 Gray out the trashcan or other top icon if it's not available
 Move the showing and hiding options for deleted projects to the status drop-down making it a separate option from what Draft/Snapshot/Both radio button

**Blockers:**  
not sure if status should use radio buttons
not sure if DRO should stay abbreviated 

**Availability:** had flu the past 2 weeks, should be able to 6 hrs per week onward
**ETA:** next week

[Link to the prototype.](https://www.figma.com/proto/nD9QK56Mzq7xNSaSUoeGx0/TDM-Calculator?type=design&node-id=12173-2052&t=wQuxLI1JbOw0OzLn-1&scaling=scale-down&page-id=2499%3A11472&starting-point-node-id=11997%3A885&mode=design
)

<img width="1512" alt="Screen Shot 2024-03-21 at 11 07 35 PM" src="https://github.com/hackforla/tdm-calculator/assets/79798670/9d30b7df-0eb1-4768-8db4-8a4a6013d6d9">

**Comment by yiranshan** [comment]
Hi Bonnie,

So sorry for the delay, I just updated the issue.

Thanks,
Yiran

**Comment by ExperimentsInHonesty** [comment]
snapshot will have icon next to it if its shared
"(deleted)" notation will be moved to the Status

**Comment by yiranshan** [comment]
Update issue on Github 03.28.2024:
Progress: 
     for user view:
 - [x] snapshot will have icon next to it if its shared
 - [x] "(deleted)" notation will be moved to the Status
 - [x] grey out deleted option for snapshot only selection

Blockers:  

Availability: 6 hrs 

Link to the prototype:
https://www.figma.com/proto/nD9QK56Mzq7xNSaSUoeGx0/TDM-Calculator?type=design&node-id=12173-2052&t=wQuxLI1JbOw0OzLn-1&scaling=scale-down&page-id=2499%3A11472&starting-point-node-id=11997%3A885&mode=design

<img width="1508" alt="Screen Shot 2024-03-28 at 5 25 44 PM" src="https://github.com/hackforla/tdm-calculator/assets/79798670/93d30990-20b6-4519-b41a-a3fdf57432d8">
<img width="286" alt="Screen Shot 2024-03-28 at 5 31 30 PM" src="https://github.com/hackforla/tdm-calculator/assets/79798670/5bc5c91c-b3cf-46e4-8c51-6cfab1c4a5ad">
<img width="294" alt="Screen Shot 2024-03-28 at 5 31 41 PM" src="https://github.com/hackforla/tdm-calculator/assets/79798670/a1d3e5d7-6d00-4ab5-a922-642543668aed">

**Comment by Parisajf** [comment]
The issue reopened to let the Dev ask their questions.

**Comment by roslynwythe** [comment]
Hi I'm a dev working on #1647 and on my local branch I have implemented the filters.  I am looking for a design prototype for the filter/autocomplete UX and I found this one in a comment above

<details><summary>Details</summary>

![image](https://github.com/hackforla/tdm-calculator/assets/98936028/291773b7-32c9-471b-929f-b8358ddead16)

</details> 

so please correct me if that is not the design I should be aiming for.  

I have implemented the filter functionality locally and now am working on styling.  Here is a sample


<details><summary>Filter on Address column</summary>
![image](https://github.com/user-attachments/assets/c1a2083c-002d-4c5b-b108-5fa278628622)
</details> 

To populate the drop-down list of possible matches, I retrieved data from all visible projects, not just the ones displayed on the current page.  Therefore my list is longer than the one depicted in the design prototype so I'm wondering

1. Should I have populated the drop-down just with projects from the current page
2. If I populate the drop-down with all visible projects, how should I limit the vertical size of the drop down?

**Comment by ExperimentsInHonesty** [comment]
- The new issue for clarifications and questions is https://github.com/hackforla/tdm-calculator/issues/1816
