### ISSUE TITLE
Design Mockup: Filter slide in placement

### ISSUE THREAD

**Issue by Biuwa** [hackforla/tdm-calculator#1579]
### Overview
We need to redesign the filter slide-in placement/position on the right side of My Projects Page to ensure that the project columns do not compress when the filter side panel slides in

### Action Items
- [ ] Slide-in placement be redesigned as the margins on the other pages of the project

### Resources/Instructions
**Before Slide in:**
<img width="1257" alt="Screenshot 2024-01-14 at 10 36 01 AM" src="https://github.com/hackforla/tdm-calculator/assets/98936028/eaea087d-712f-486d-9a48-a2956344e94c">
---------------------------------------------
**After Slide in:**
<img width="1485" alt="Screenshot 2024-01-14 at 10 35 49 AM" src="https://github.com/hackforla/tdm-calculator/assets/98936028/f0c74385-4dfe-4989-b0d3-a9ddf4c35639">

**Comment by hanselnoriega** [comment]
![Filter Side Placement (#1579)](https://github.com/hackforla/tdm-calculator/assets/156873530/0354d98c-1d07-4a43-a221-a236b984c3f7)

Please find attached the following changes:
- Placed search panel on the right side

**Comment by hanselnoriega** [comment]
![Filter Side Placement (#1579)](https://github.com/hackforla/tdm-calculator/assets/156873530/e57ef857-f723-46a3-9f29-089c2d35104c)
Please find attached the updated filter slide

**Comment by hanselnoriega** [comment]
![Filter Side Placement (#1579)](https://github.com/hackforla/tdm-calculator/assets/156873530/84784be2-9461-48ae-8ab5-99108180d558)

Please find attached the revision. Changes made to the attached screenshot:
- remove Project Name
- remove Address field
- remove Alternative Number
- add DRO field, fully spelled w/drop down

**Comment by Parisajf** [comment]
We came up with another methodology to have the filters in the top row
