### ISSUE TITLE
Design Mockup: redesign the search bar 

### ISSUE THREAD

**Issue by Biuwa** [hackforla/tdm-calculator#1580]
### Overview
We need to redesign the search bar and filter slide-in panels so users can get specific results for their search inputs.

### Action Items
- [ ] The design team should work out how the search function will output search results between the search bar and the filter panels in the slide-in.
 - Currently, the filter panels in the filter slide-in search only specific combinations input in the exact field, while the search bar searches all fields for the search input

**Comment by hanselnoriega** [comment]
![Redesign the Search Bar (#1580 - Ongoing)](https://github.com/hackforla/tdm-calculator/assets/156873530/c1f111ec-456e-4e87-93bd-3095b11123e0)
Please find attached the revised search panel to include filter information on:
- AIN/APN Assessor ID Number
- Building Permit Number
- LADOT Case Number
- City Planning Number
- Toggle button for Status and Visibility selection

**Comment by ExperimentsInHonesty** [comment]
![image](https://github.com/hackforla/tdm-calculator/assets/37763229/ba666cf3-63fe-4a6f-8670-c6c430c37df8)

**Comment by ExperimentsInHonesty** [comment]
![image](https://github.com/hackforla/tdm-calculator/assets/37763229/85b6227f-77ff-4bb6-ad12-eefef226d01d)

DRO should be "District Region Office (DRO)" and a drop down

**Comment by hanselnoriega** [comment]
![Filter Side Placement (#1579) (1)](https://github.com/hackforla/tdm-calculator/assets/156873530/d08edbd7-2f2f-47e3-b9d3-06e23aa35cf4)

Please find attached the revision. Changes made to the attached screenshot:

**Filter**, Side Panel Edits
- remove Project Name
- remove Address field
- remove Alternative Number
- add DRO field, fully spelled w/drop down

**All Categories**, Drop Down Edits
- add Address
- remove status
- remove DRO
- remove Created By
- remove Created On
- remove Last Modified
- remove Submitted On

Search by **Keyword Bar** Edits
- Remove the word "Data" from the search description
