### ISSUE TITLE
Engineer tests and validation for 'FAQ' and 'FAQCategory' Web API requests

### ISSUE THREAD

**Issue by agosmou** [hackforla/tdm-calculator#1581]
### Overview

We need to create a workflow for testing all 'FAQ' and 'FAQCategory' endpoints. We will need to set up tests and web API request validation for the endpoints.

### Details | Scope of Work
We need to test the API endpoints using 'jest'  

### Action Items

- [x] write all tests for endpoints
- [x] set up server side validation schema (this should be done for the POST requests that contain a body - we validate the body data)

### Resources/Instructions
TDM Testing
- [Testing Wiki](https://github.com/hackforla/tdm-calculator/wiki/Testing)
- Check existing tests and build your tests to match what is in the codebase

Server Side Validation
- https://www.npmjs.com/package/express-json-validator-middleware
- https://simonplend.com/how-to-handle-request-validation-in-your-express-api/  

Testing
- https://jestjs.io/
- https://testcontainers.com/

**Comment by Biuwa** [comment]
@neyaadeez, @WomB0ComB0 

**Please provide an update:**

1. Progress(What is the current status of your project? What have you completed, and what is left to do):
2. Blockers(Difficulties or errors encountered):
3. Availability(How much time will you have this week to work on this issue):
4. ETA(When do you expect this issue to be completed):
5. Pictures (if necessary)(Add any pictures that will help illustrate what you are working on)

**Comment by WomB0ComB0** [comment]
@Biuwa 

1. Still in progress, we have not completed anything yet just minor fixes within the codebase.
2. I am having issues with testing with authentication headers
3. I can spend 6 hours this week on the project
4. Sometime this week
5. ![image (1)](https://github.com/hackforla/tdm-calculator/assets/95197809/9c637f1b-a2bf-48f0-9971-cb3eb54ba4be)

**Comment by neyaadeez** [comment]
@Biuwa 
1. Progress: In progress. Started working on FaqCategory test cases.
2. Blockers: Not discovered yet.
3. Availability: Tuesdays, Wednesdays, Fridays - Approximately 6-8 hours.
4. ETA: By the end of this week.
5. Pictures: -

**Comment by entrotech** [comment]
- All of the endpoints for FAQs are obsolete and have been removed under Issue #1573. This also removes all but two of the FaqCategory endpoints, so you are left with only two endpoints to test:
GET /api/faqcategories
POST /api/faqcategories

- The obsolete endpoints were removed from the develop branch on PR #1616

**Comment by agosmou** [comment]
@neyaadeez 

Did you get the faq category tests and validation working? If so, you can push your branch and maybe Mike or I can clean it up for the two active endpoints left. Then we can close this issue and move forward.

**Comment by neyaadeez** [comment]
I made a pull request for the faqCategory testcase and validation. It works as expected.
