### ISSUE TITLE
BUG : Fix Feedback page to make it available for non-login user

### ISSUE THREAD

**Issue by Tomomi-K1** [hackforla/tdm-calculator#1582]
### Overview
Currently, if a user have never logged in the page, a user cannot open feedback page. Instead, error message "For your security, your session has expired. Please log in again." pops up.

#### Steps to reproduce the issue
1. On the homepage, without logging in, click "Feedback" tab.
2. Error message "For your security, your session has expired. Please log in again." pops up.
Note: if you login once and logout and then try this steps, this bug will not happen. It only happens when a user had never logged in on that window session.

#### What's the expected result?
non-login user should still be able to access the feedback page.
But should not show the list of projects at the bottom of the form if a user is not logged in.

### Action Items
- [x]  Take a look at `Feedback.js` (client/src/components/Feedback/FeedbackPage.js)
- [x]  locate problem code that prevents non-login user from seeing Feedback page and implement a fix.

```
import useErrorHandler from "../../hooks/useErrorHandler";
import useProjects from "../../hooks/useGetProjects";
```

###

**Comment by Sathurshanan-Kandhasamy** [comment]
Hi @Tomomi-K1, can I work on this issue?
