### ISSUE TITLE
Document CSS properties for the Calculation.scss page

### ISSUE THREAD

**Issue by heejung-hong** [hackforla/tdm-calculator#1585]
### Overview
In order to convert SCSS to JSS where possible, the css properties of the Calculation.scss page will be documented for reference.

### Action Items
- [x] Use the Google Sheets link below to document the css properties of the Calculation.scss.
https://docs.google.com/spreadsheets/d/1eWFAv9TTyq6steNO1tyPFfJ0LciRKnDT9W4sAolrg0g/edit?usp=sharing
- [x] #1586
- [x] #1588
- [x] #1599
- [x] #1600
- [x] #1610
- [x] #1611
- [x] #1612

**Comment by Biuwa** [comment]
@heejung-hong 

**Please provide an update:**

Progress(What is the current status of your project? What have you completed, and what is left to do):
Blockers(Difficulties or errors encountered):
Availability(How much time will you have this week to work on this issue):
ETA(When do you expect this issue to be completed):
Pictures (if necessary)(Add any pictures that will help illustrate what you are working on)

**Comment by heejung-hong** [comment]
1. **Progress:** There are three pages that are left to convert to JSS.  SidebarPointsPanel, SidebarPoints, and Project Summary
2. **Blockers:** None at this time
3. **Availability:** Weekdays after 6pm
4. **ETA:** 02/14

**Comment by Biuwa** [comment]
@heejung-hong

**Please provide an update:**

1. Progress(What is the current status of your project? What have you completed, and what is left to do):
2. Blockers(Difficulties or errors encountered):
3. Availability(How much time will you have this week to work on this issue):
4. ETA(When do you expect this issue to be completed):
5. Pictures (if necessary)(Add any pictures that will help illustrate what you are working on)

**Comment by heejung-hong** [comment]
1. **Progress:** All SCSS styles have been converted to JSS and the Calculation.scss page has been deleted.  Pull request created and waiting for John to review and approve for merge.
2. **Blockers:** None at this time
3. **Availability:** Weekdays after 6pm
4. **ETA:** 03/14
