### ISSUE TITLE
Reordering the CSV File Download Columns

### ISSUE THREAD

**Issue by Biuwa** [hackforla/tdm-calculator#1591]
### Overview
This issue will track the progress of the CSV download column reorder by LACP and LADOT

### Action Items
- [x] Review columns
- [x] #1604
- [ ] Discuss in the stakeholder meeting
- [ ] Approve

### Resources/Instructions
[TDM EXAMPLE CSV](https://docs.google.com/spreadsheets/d/1fPj-RdfQjyTF7hSXwZpKB8KwhqQC2B4ZpjbjvznYbBw/edit?usp=sharing)

**Comment by eglacp** [comment]
Hi, you can look at the 2nd tab of the spreadsheet linked in this issue. Emily and Xander reorganized the fields into the desired order on 1/24/2024. Thanks!

**Comment by ExperimentsInHonesty** [comment]
@eglacp thanks for the reodering.
