### ISSUE TITLE
Create an Issue Template for Bug Reports

### ISSUE THREAD

**Issue by entrotech** [hackforla/tdm-calculator#1592]
### Overview
We need to create an Issue Template in our repo for Bug Reports, to standardize the way Bug Report information is collected.

### Action Items
- [ ] Discuss with interested people what the standard format of our Bug Report issues should be.
- [ ] Add a "bug-report.md" file to the .github/ISSUEW_TEMPLATE folder in a feature branch and submit a PR to implement the change.

### Resources/Instructions

When you create a new issue, you are presented with a list of Issue Templates, and most of us just use the first choice called "Blank Issue".  It is very easy to add a new template, and we should  create one for "Bug Reports".  All you need to do is add a *.md file to the .github/ISSUE_TEMPLATE folder in the project and follow the markup format in the blank-issue.md file to supply the meta data and default description format.   As an example, here is the bug template from the Food Oasis project:
```
---
name: Bug report
about: Create a report to help us improve
title: 'Bug: '
labels: 'bug, priority: MUST HAVE'
assignees: ''

---

#### Describe the bug 

A clear and concise description of what the bug is, who it affects, how it affects users.

(optional) What is the user's goal?


#### Steps to reproduce the issue

(if applicable, please specify platform (iOS, Android, Windows, Mac version) and brower)

1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error 


#### What's the expected result?

-

(if you have a suggested solution, you can add it here)

#### What's the actual result?

-


#### Additional details / screenshot

- Screenshot (drag in)
- Video recording (drag in)

#### Device configuration
- Device: [e.g. type of smartphone, tablet, desktop computer]
- OS version: [e.g. iOS, Android version #]
- Browser [e.g. Chrome, Firefox, Safari, etc.]
- Browser version [e.g. 22]
- ```

**Comment by Biuwa** [comment]
**@Jonathanko52** 

**Please** provide an update:

1. Progress(What is the current status of your project? What have you completed, and what is left to do):
2. Blockers(Difficulties or errors encountered):
3. Availability(How much time will you have this week to work on this issue):
4. ETA(When do you expect this issue to be completed):
5. Pictures (if necessary)(Add any pictures that will help illustrate what you are working on)

**Comment by Jonathanko52** [comment]
Please provide an update:

Progress(What is the current status of your project? What have you completed, and what is left to do): Template added and pull request made.
Blockers(Difficulties or errors encountered): None
Availability(How much time will you have this week to work on this issue): 
ETA(When do you expect this issue to be completed): Immediate
Pictures (if necessary)(Add any pictures that will help illustrate what you are working on)
