### ISSUE TITLE
Develop algorithm to detect circular reference in rules

### ISSUE THREAD

**Issue by entrotech** [hackforla/tdm-calculator#16]
IF we were to implement features for an administrator to edit the calculation rules, it would be helpful to have a feature that detects when the admin creates rules that cause circular references. That is, situations where Rule A depends on the results of Rule B, but Rule B depends on the result for Rule A.

**Comment by mojimoh** [comment]
@entrotech please update issue to provide information on what is needed and what actions required to better assign for a new developer

**Comment by entrotech** [comment]
since we are not implementing features for the admin to edit the calculation rules, we don't need this.
