### ISSUE TITLE
Revise Detailed Project Level Calculation per Rosemary's Input.

### ISSUE THREAD

**Issue by entrotech** [hackforla/tdm-calculator#160]
Bonnie created a GoogleSheet with a breakdown of the Level calculation info we have so far, and Rosemary is in the process of clarifying how the calculation should work. Once that is complete, we can revised the Level Calculation code to comply with the new specs.

As part of this, projects below a certain size are considered Level 0 and are not subject to TDM requirements - this needs to be incorporated in the application.

**Comment by ExperimentsInHonesty** [comment]
@KPHowley please add the spreadsheet referred to above.

**Comment by KPHowley** [comment]
Here is a spreadsheet with current project level figures: https://docs.google.com/spreadsheets/d/12U5NrqCYJLTUp1I8WMtdubLb_FgyWK4fahia_scNfng/edit?usp=sharing

**Comment by ExperimentsInHonesty** [comment]
Here are the updates Rosemary has asked for 
![Screen Shot 2020-02-01 at 11 40 53 AM](https://user-images.githubusercontent.com/37763229/73598035-d16df580-44e7-11ea-945f-d56691c5f5b6.png)

#### Here is what has been completed:

- [ ] Condos: add input for unit number 
![Screen Shot 2020-02-01 at 11 45 58 AM](https://user-images.githubusercontent.com/37763229/73598132-f31bac80-44e8-11ea-9901-136490941882.png)

- [ ] School: Add input for number of students
![Screen Shot 2020-02-01 at 11 43 47 AM](https://user-images.githubusercontent.com/37763229/73598144-15adc580-44e9-11ea-8f11-1ebec6b16e09.png)

- [ ] Institutional Sq Ft. has been removed

#### What has not been completed
- [ ] Hospitals (Beds) or Convalescent Beds: Add input for sq ft
![Screen Shot 2020-02-01 at 11 52 37 AM](https://user-images.githubusercontent.com/37763229/73598162-632a3280-44e9-11ea-80d8-3e68d3599cb6.png)

- [ ] Residential Inputs: Remove Senior Independent Housing and Assisted Living Care Unit
![Screen Shot 2020-02-01 at 11 57 15 AM](https://user-images.githubusercontent.com/37763229/73598198-0418ed80-44ea-11ea-9644-d968a8c9425a.png)

**Comment by ExperimentsInHonesty** [comment]
Sent Rosemary 2/1/20 and email asking her confirm these changes before sending to development.

**Comment by ramccarr** [comment]
Yes, please execute those changes.

**Comment by ExperimentsInHonesty** [comment]
Temporary fix applied by @bfojas to remove Senior Independent Housing and Assisted Living Care Unit from display. 

![Screen Shot 2020-02-08 at 10 57 19 AM](https://user-images.githubusercontent.com/37763229/74090578-d3910080-4a61-11ea-9e8e-576f6ffc1239.png)

 In order to remove permanently it has to be done in coordination with John.  This is being tabled until he returns.

**Comment by ExperimentsInHonesty** [comment]
@entrotech is going to remove the two rules that are no longer applicable.

**Comment by entrotech** [comment]
Closed by PR #239
