### ISSUE TITLE
Reorder the CSV columns

### ISSUE THREAD

**Issue by entrotech** [hackforla/tdm-calculator#1604]
### Overview
We need to Implement the change to the CSV column order according to the reordering done by Emily and Xander(LACP/LADOT) per Issue #1591

### Action Items
- [x] Reorder based on [TDM EXAMPLE CSV](https://docs.google.com/spreadsheets/d/1fPj-RdfQjyTF7hSXwZpKB8KwhqQC2B4ZpjbjvznYbBw/edit?usp=sharing)
- [ ] Review with Team/Stakeholders

### Resources/Instructions
[TDM EXAMPLE CSV](https://docs.google.com/spreadsheets/d/1fPj-RdfQjyTF7hSXwZpKB8KwhqQC2B4ZpjbjvznYbBw/edit?usp=sharing)

**Comment by ExperimentsInHonesty** [comment]
The issue needs the standard issue format
```
### Dependencies
ANY ISSUE NUMBERS THAT ARE BLOCKERS OR OTHER REASONS WHY THIS WOULD LIVE IN THE ICEBOX

### Overview
WE NEED TO DO X FOR Y REASON

### Action Items
A STEP BY STEP LIST OF ALL THE TASK ITEMS THAT YOU CAN THINK OF NOW EXAMPLES INCLUDE: Research, reporting, etc.

### Resources/Instructions
REPLACE THIS TEXT -If there is a any documentation or screenshots that help with this issue provide the link(s) here.
```
