### ISSUE TITLE
DB Migration to Remove Unused Faq table and Stored Procedures

### ISSUE THREAD

**Issue by entrotech** [hackforla/tdm-calculator#1605]
### Overview
To keep the database free of unused components, we need to create a DB migration script to remove the Faq table and it's stored procedures, and well as unused FaqCategory_* stored procedures.

### Action Items
- [ ] Create DB Migration script(s)

### Resources/Instructions
- Follow-up to Issue #1573

**Comment by irisslee** [comment]
Progress(What is the current status of your project? What have you completed, and what is left to do):
   Migration scripts need to be tested on local environment
Blockers(Difficulties or errors encountered):
    None yet
Availability(How much time will you have this week to work on this issue):
   4 hours
ETA(When do you expect this issue to be completed):
   2 weeks
Pictures (if necessary)(Add any pictures that will help illustrate what you are working on) - N/A

**Comment by ExperimentsInHonesty** [comment]
@irisslee 
Please provide update
1. Progress: "What is the current status of your project? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"
5. Pictures or links* (if necessary): "Add any pictures or links that will help illustrate what you are working on."

* remember to add links to the top of the issue if they are going to be needed again.
