### ISSUE TITLE
Update the Default (Single-Page) View of the Calculation

### ISSUE THREAD

**Issue by entrotech** [hackforla/tdm-calculator#161]
Clean up the look and design of the single page view.

- [ ] Create mock up with the following
  - [x] Clean up boxes at the top
  - [x] Reposition buttons
  - [x] Remove extra greater than signs
  - [x] Add save button
  - [x] Fix alignment on all text boxes
  - [ ] Center "Project Parameters" and "Transportation Demand Strategies"

FRONT END:
- [ ]  Implement the redesign, as noted in the figma document below

RESOURCES:
  - https://www.figma.com/file/qNgPc5lttpf0SWSwkbbWyT/TDM-Calculator?node-id=2129%3A1608

**Comment by dazainus** [comment]
I came up with 3 variations of the Single Page View design, reflecting the guidelines stated above.

### Changes Made
- [ ]  Clean up boxes at the top
- [ ]  Reposition buttons
- [ ]  Remove extra greater than signs
- [ ]  Add save button
- [ ]  Fix alignment on all text boxes
- [ ]  Center "Project Parameters" and "Transportation Demand Strategies"

Additionally
- [ ]  Add background light green and blue highlights to tell apart 'Target Points' and 'Earned Points' from 'Project Level' and 'Parking Provided/Baseline.'
- [ ]  Insert 'Last saved timestamps' on the top and bottom
- [ ]  Make additional design options with sticky TDM point calculation area, reflecting our wizard view's UI (See Version 2 & 3)


### Design Mockups
**Version 1: Default (No Sticky)**
https://marvelapp.com/ee0fhde/screen/70341110

**Version 2: TDM Point Calculation Sticky on Top**
https://marvelapp.com/ee0fhde/screen/70341107

**Version 3: TDM Point Calculation Sticky at Bottom**
https://marvelapp.com/ee0fhde/screen/70341111

### Resource
- Figma file: https://www.figma.com/file/qNgPc5lttpf0SWSwkbbWyT/TDM-Calculator?node-id=1923%3A2914

**Comment by dazainus** [comment]
After the team review, here are 2 design variations, reflecting the agreed changes.

### Changes Made
- [ ] Relocate ‘Save project’ button on the sticky
- [ ] Reduce the size of the 'TDM points values' on the sticky (Project Level, Parking Provided/ Baseline, Target Points, Earned Points)
- [ ] Right-align the ‘strategy’ part of the chart
- [ ] Insert separate column for 'Possible Points'
- [ ] Make 'Item Titles' into two lines from a single line
- [ ] Make 'Drop down menu' into two lines from a single line

### Design Mockups
#### Version 1: Double Lines for 'TDM points values' (Default Styling)
![VER 4  header](https://user-images.githubusercontent.com/55513459/85917584-2d774480-b810-11ea-9903-5dfc4af7183d.jpg)

- Perks: Uses the shared, default style of the TDM points value -> Increased consistency, Visually friendly to the users
- Prototype: https://marvelapp.com/ee0fhde/screen/70674554
#### Version 2: Single Line for 'TDM points values'
![VER 5  header](https://user-images.githubusercontent.com/55513459/85917588-336d2580-b810-11ea-9c20-7e7c174eb051.jpg)
- Perks: By displaying them in single line, we are saving some vertical room of the top dashboard -> Covering less of the main content
- Prototype: https://marvelapp.com/ee0fhde/screen/70674555


### Resources
- Figma file: https://www.figma.com/file/qNgPc5lttpf0SWSwkbbWyT/TDM-Calculator?node-id=2084%3A7502

**Comment by entrotech** [comment]
About halfway down the right-hand columnet, the caption "Target Demand Strategies" should be "Transportation Demand Strategies".

**Comment by dazainus** [comment]
@KPHowley - Previously discussed updates are made.

### Changes Made
- [ ] "Target Demand Strategies" -> "Transportation Demand Strategies"
- [ ] Under "Transportation Demand Strategies" section, added is "Select Employment Package" button
- [ ] Under "Transportation Demand Strategies" section, button styles have been revised
     - [ ] Distinguish selected and unselected button styles (Clickable button is regular button style, Unclickable/disabled/selected button is lighter in color)
     - [ ] Status message is inserted to clearly communicate which package the user has selected.
![VER 6  single page view-revision-button](https://user-images.githubusercontent.com/55513459/86988180-8027f900-c14c-11ea-8c0a-0885d230d6f8.png)

### Design Mockup
- Prototype: https://marvelapp.com/prototype/ee0fhde/screen/71003830
- Image:
![VER 6  single page view-revision](https://user-images.githubusercontent.com/55513459/86988390-f4629c80-c14c-11ea-979a-3b28c4656df8.png)

### Resource
- Figma: https://www.figma.com/file/qNgPc5lttpf0SWSwkbbWyT/TDM-Calculator?node-id=2129%3A1608

**Comment by KPHowley** [comment]
given the interrelated nature of the information, and the subsequent changes made to the calculator this is not feasible.  This is being closed
