### ISSUE TITLE
Implement Web API tests for /api/feedbacks

### ISSUE THREAD

**Issue by agosmou** [hackforla/tdm-calculator#1624]
### Overview

We need to create a workflow for testing all 'Feedback' endpoints. We will need to set up tests and web API request validation for the endpoints.

### Details | Scope of Work
We need to test the API endpoints using 'jest'  

### Action Items

- [x] write all tests for endpoints
- [x] set up server side validation schema (this should be done for the POST requests that contain a body - we validate the body data)

### Resources/Instructions
TDM Testing
- [Testing Wiki](https://github.com/hackforla/tdm-calculator/wiki/Testing)
- Check existing tests and build your tests to match what is in the codebase

Server Side Validation
- https://www.npmjs.com/package/express-json-validator-middleware
- https://simonplend.com/how-to-handle-request-validation-in-your-express-api/  

Testing
- https://jestjs.io/
- https://testcontainers.com/

**Comment by agosmou** [comment]
Here's a PR submitted that can be used to model your implementation

- make sure you test your code in the test environment and as the end user (ie by manually going through the feedback items on the browser to make sure it would work for the end user)

**Comment by agosmou** [comment]
Additionally, make sure you mock out the sendgrid-service.js so that your tests dont send out any actual emails by engaging a 3rd party API

You can copy the scaffolding for this from account.test.js

**Comment by ExperimentsInHonesty** [comment]
@WomB0ComB0 Please provide update
1. Progress: "What is the current status of your project? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"
5. Pictures or links* (if necessary): "Add any pictures or links that will help illustrate what you are working on."

* remember to add links to the top of the issue if they are going to be needed again.

**Comment by WomB0ComB0** [comment]
@ExperimentsInHonesty 
 1. The current status of the issue is, 'incomplete', we had to get the tests running on everyone's machines. However, my only task was to write the tests and schema validation for this particular issue.
 2. Getting the tests to run on everyone's machines
 3. I am done, I need to have it run on everyone who was involved in machines.
 4. I am done.
