### ISSUE TITLE
Implement Web API tests for /api/rules endpoints

### ISSUE THREAD

**Issue by agosmou** [hackforla/tdm-calculator#1629]
### Overview

**NOTE: We aren't using these endpoints, so I (John Darragh) changed this issue to remove the obsolete endpoints.**

### Actions
- [x] Remove obsolete /api/rules endpoints

**Comment by agosmou** [comment]
@entrotech

We had discussed removing obsolete and/or over-exposed endpoints and I wanted to see if we were still thinking of removing some of the "Rules" endpoints

[See services in question here](https://github.com/hackforla/tdm-calculator/blob/develop/server/app/services/rule.service.js)

**Comment by entrotech** [comment]
We can remove all the rule endpoints in the rule.routes.js file, but there is an unusual endpoint that is in calculation.routes.js /api/calculations/:id/rules that uses a single method in the rule.controller.js, which, in turn, uses a method in the rule.service.js file, and we need to keep just those methods in those files.

The other rule endpoints were intended for creating a UI that allowed an administrator to edit rules, but we decided that those features were too complicated and dangerous to build into the application.

**Comment by entrotech** [comment]
Modified this task to just remove the /api/rules endpoints entirely, since we decided not to implement an Admin feature for editing the rules.
