### ISSUE TITLE
Design Mockup: Admin view of my projects page

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/tdm-calculator#1641]
### Overview
Create the project page for admin view.  So that admins can do additional actions on projects and see all projects across all users.

### Action Items
- [x]  Add a notes column on the far right, it should have two mutually exclusive icons, one for making a note and one for seeing/editing an existing note
- [x]  Dev Review Office is a drop-down select 
- [x]  Add another new column called Modified by Admin.  The date in this column will be updated if the Admin adds a note, or DRO to the project.

### Resources/Instructions
- https://tdm-dev.azurewebsites.net/projects
- [[figma link for designs]](https://www.figma.com/file/nD9QK56Mzq7xNSaSUoeGx0/TDM-Calculator?type=design&node-id=5844-21001&mode=design&t=pqzwYnjwz79uFWqD-0)

**Comment by yiranshan** [comment]
Update issue on Github 04.02.2024:
Progress: 
- Add a notes column on the far right, it should have two mutually exclusive icons, one for making a note and one for seeing/editing an existing note
- Dev Review Office is a drop-down select
- Add another new column called Modified by Admin. The date in this column will be updated if the Admin adds a note, or DRO to the project.
[Prototype Link.](https://www.figma.com/proto/nD9QK56Mzq7xNSaSUoeGx0/TDM-Calculator?type=design&node-id=12369-5071&t=D3AjzQN4CWLLJvfh-1&scaling=contain&page-id=5844%3A21001&starting-point-node-id=12369%3A5071&mode=design)

**Comment by yiranshan** [comment]
<img width="1510" alt="Screen Shot 2024-04-02 at 11 52 40 PM" src="https://github.com/hackforla/tdm-calculator/assets/79798670/a5d37c61-abf7-447e-be20-f33572e1cb6a">
<img width="1514" alt="Screen Shot 2024-04-02 at 11 52 18 PM" src="https://github.com/hackforla/tdm-calculator/assets/79798670/84525410-52ef-4f4b-a2fd-79661b492ed2">

**Comment by yiranshan** [comment]
Update issue on Github 04.10.2024:
Progress: 
Add download all options for projects download
<img width="684" alt="Screen Shot 2024-04-10 at 9 39 00 PM" src="https://github.com/hackforla/tdm-calculator/assets/79798670/1c9d2b91-fb21-46db-88c5-bce7e86eefc8">

[Prototype Link](https://www.figma.com/proto/nD9QK56Mzq7xNSaSUoeGx0/TDM-Calculator?type=design&node-id=12369-5071&t=D3AjzQN4CWLLJvfh-1&scaling=contain&page-id=5844%3A21001&starting-point-node-id=12369%3A5071&mode=design).

**Comment by yiranshan** [comment]
Update issue on Github 04.11.2024:
Progress: 
Add numbers next to the “download all project icon”
Add notification of “Found 152 matching results.”, when search results number will reflect the number of results matching the search criteria. 
Add “Notes” in the search bar

Prototype Link.
https://www.figma.com/proto/nD9QK56Mzq7xNSaSUoeGx0/TDM-Calculator?type=design&node-id=12369-5071&t=D3AjzQN4CWLLJvfh-1&scaling=contain&page-id=5844%3A21001&starting-point-node-id=12369%3A5071&mode=design
<img width="1559" alt="Screen Shot 2024-04-11 at 4 49 48 PM" src="https://github.com/hackforla/tdm-calculator/assets/79798670/3fe45486-94e6-4140-b487-aca807f031f3">
<img width="1558" alt="Screen Shot 2024-04-11 at 4 43 15 PM" src="https://github.com/hackforla/tdm-calculator/assets/79798670/7fc9aa3b-7534-4c12-b84c-26487ebd6ed7">
<img width="1560" alt="Screen Shot 2024-04-11 at 4 46 35 PM" src="https://github.com/hackforla/tdm-calculator/assets/79798670/4069e061-4f98-47d4-b69f-04c2525ef1b0">

**Comment by Parisajf** [comment]
Updates after the steak holder meeting:
The download icon choices need to be revised:
The two options need to be dark if they are available (not grayed out)
There should be a third option to download filtered projects
If there are no projects selected, gray out and disable the Download Selected (0)

**Comment by Parisajf** [comment]
When no projects selected, we can only gray out the text Selected (0)

**Comment by Parisajf** [comment]
new issue created for  download flow 
https://github.com/hackforla/tdm-calculator/issues/1676
