### ISSUE TITLE
Modify the behavior of the Search By Text Box on the My Projects page

### ISSUE THREAD

**Issue by entrotech** [hackforla/tdm-calculator#1649]
### Dependency
- #1647 

### Overview
- To comply with design Issue #1578, The Search By Text Box should filter by project that substring match the search text in the Name, Address, Description, OR Alt # fields of the Project.  (Not the Building Permit or Created fields). If the user types any text in this Search By control, any test filtering on the individual column filters for Name, Address, or Alt # fields should be cleared.

#### Details
We removed some of the action items

### Action Items
- [ ] ~Modify the search to search in any of the specified fields only, and apply the filtering when the Search button is clicked.~
- [ ] ~When a user types any text into the Search By Text Box, clear any filtering by individual fields Name, Address, or Alt #.~
- [x] Add searching the description field

### Resources/Instructions
Refer to this Figma prototype: https://www.figma.com/proto/nD9QK56Mzq7xNSaSUoeGx0/TDM-Calculator?type=design&node-id=12173-2052&t=wQuxLI1JbOw0OzLn-1&scaling=scale-down&page-id=2499%3A11472&starting-point-node-id=11997%3A885

**Comment by roslynwythe** [comment]
@entrotech I don't see the the Description field; please advise how to display it.  Is it called something else in the code?

**Comment by ExperimentsInHonesty** [comment]
@roslynwythe we just revised the action items

**Comment by roslynwythe** [comment]
@entrotech In the Figma design, the input box and the adjacent button have rounded corners and the button displays the text "Search".  However in the current dev branch, the corners are not rounded and the button displays the text "Filter By".  Should I change the shape of the box, button and the button text to match Figma?

**Comment by ExperimentsInHonesty** [comment]
Before image ![image](https://github.com/user-attachments/assets/33892661-6b96-4423-a71d-1e842d7b1bdc)
