### ISSUE TITLE
Implement the DRO and Admin Notes columns for Projects

### ISSUE THREAD

**Issue by entrotech** [hackforla/tdm-calculator#1650]
### Overview
- Implement the DRO and admin notes columns to Projects

### Action Items
 - [x] Add a Dro table to the database with columns, id (pk, int), name nvarchar(200) not null, displayOrder int, not null, default 10 to the database.
 - [x] Add columns droId (int, null, fk to Dro table), and adminNotes varchar(max), null , and dateModifiedAdmin datetime2(7), null, to the Project table.
 - [x] Add the new columns to the SELECT web api call for retrieving projects.
 - [x] Create an update web api call that allows an admin to update the droId column value of a project. When this api is called, the droId column will be updated and the dateModifiedAdmin value will be set to the current datetime (UTC), but do not modify the dateModified column.
 - [x] Add a DRO column to the My Projects page grid. It should be read-only text showing the DRO name if the user is not an admin, or a drop-down list box if the user is an admin. When an admin selects a new value, is should call the updateDro web api call.
 - [x] Create an updateAdminNotes web api call that allows and admin to update the adminNotes column value in the Project table. When this is updated, also update the dateModifiedAdmin column to the current datetime (UTC), but do not update the dateModified column.
 - [x] Add a column to the My Projects grid for Admin Notes. It should display an "add note" (see resources Add Circle) icon if the project has no admin notes, or an "edit note" icon (see resources Edit) if the project has some text in the admin note column. Adding or editing the admin notes, should make the corresponding change to the contents of the project's admin notes column by using the above-mentioned updateAdminNotes web api call. This column should only show if the user is an admin.
 - [x] Add the dateModifiedAdmin column to show in the My Project grid if the user is an admin. Format should be the same as the Created, Modified columns.
 - [x] Filtering for these two new columns will be included on another follow-up issue.
 - [x] Release dependency on #1651 and move it from the icebox to the new issue approval column.
 
### Resources/Instructions
Dev, my projects page: https://tdm-dev.azurewebsites.net/projects

For the Edit icon: https://mui.com/material-ui/material-icons/?query=edit&selected=Edit
For the Add Circle icon: https://mui.com/material-ui/material-icons/?query=addc&selected=AddCircle

**Comment by ExperimentsInHonesty** [comment]
@dipitvasdev i have moved this issue into the in progress column.  In the future, please do that when you self assign.

**Comment by ExperimentsInHonesty** [comment]
@dipitvasdev Please provide update
1. Progress: "What is the current status of your project? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"
5. Pictures or links* (if necessary): "Add any pictures or links that will help illustrate what you are working on."

* remember to add links to the top of the issue if they are going to be needed again.

**Comment by dipitvasdev** [comment]
Hi @ExperimentsInHonesty, I was having some problems setting up the database so I am working on that. I was moving so was not able to devote that much time. I should be able to solve it by next week.

**Comment by ExperimentsInHonesty** [comment]
@dipitvasdev here are some changes for the DRO column

Change the names of the DROs to exclude the words Development Review Office

The names become 
Metro
Valley
West LA

Make sure the drop-down is alphabetized 

Add a value "Select..."  so that when if they choose one but later realize it's the wrong one, they can choose Select...

**Comment by dipitvasdev** [comment]
Okay @ExperimentsInHonesty, I'll work on those changes

**Comment by ExperimentsInHonesty** [comment]
Its not showing up with the short names yet.  John thinks he has to run migration script to get it to show up.  When it is working properly.  Add to slide deck for stakeholder confirmation to push to production.

**Comment by entrotech** [comment]
Migration script run on 10/16/24 at 5:20PM. Drop-down now uses the shortened version of the DRO names.  No PR or code changes required.
