### ISSUE TITLE
Redesign the date and project status info on the summary page and the PDF

### ISSUE THREAD

**Issue by Parisajf** [hackforla/tdm-calculator#1653]
### Overview
We need to redesign where the status and saved date information displays on page 5 and its PDF so that it's consistent between views and so that later, if we need to add additional information, it will be easy to place. 

### Details
About the end users of printed materials.  Generally, when you are working on a real estate development project, its a sea of paperwork, and you often end up with multiple versions of the same document, and want a way to compare them (date, version number, etc.), to sort them into the most current to oldest.  So that information is usually on bottom or top right or left, almost never centered.

### Action Items
- [ ] Page 5 and PDF need status.  The following status options are mutually exclusive
   - [ ] Snapshot Created: YYYY-MM-DD 11:03 AM Pacific Time
   - [ ] Snapshot submitted: YYYY-MM-DD 11:03 AM Pacific Time
   - [ ] Snapshot deleted: YYYY-MM-DD 11:03 AM Pacific Time
   - [ ] Deleted: YYYY-MM-DD 11:03 AM Pacific Time
- [ ] Page 5 and PDF should have Date Last saved
- [ ] PDF will have Date Printed, but page 5 will not

### Resources/Instructions
- https://github.com/hackforla/tdm-calculator/issues/1568
- [Figma. PDF page](https://www.figma.com/file/nD9QK56Mzq7xNSaSUoeGx0/TDM-Calculator?type=design&node-id=8953-21658&mode=design&t=7WiYITW3waS30fhm-0)

Date info appears differently on two versions of the same page

Top of page 5
![image](https://github.com/hackforla/tdm-calculator/assets/37763229/7589fb73-849c-4f54-83f0-d1b7080965ae)

Bottom of PDF 
![image](https://github.com/hackforla/tdm-calculator/assets/37763229/04c1a5a6-e229-463c-8038-d54873bb5161)
Date Last Saved: 03/04/2023 11:03 AM Pacific Time
Date Printed: 4/4/2024, 1:50:47 PM Pacific Time

**Comment by marlenamellody** [comment]
Update on project summary PDF (parking subheader and project description): 
Progress: 
- added parking subheader 
![Test Case 1 - Pacific Time - parking subheader](https://github.com/hackforla/tdm-calculator/assets/156871712/73b38e3c-3854-4ad1-9e32-2e0a539f7f3e)

- updated parking description placement (two options) 
PROJECT DESCRIPTION UNDER PROJECT DETAILS
![Test Case 1 - Pacific Time (PROJECT DESCRIPTION UNDER PROJECT DETAILS)](https://github.com/hackforla/tdm-calculator/assets/156871712/8dc6766d-6eee-4cc8-8c1c-262bf2d09d99)
PROJECT DESCRIPTION UNDER PROJECT NAME
![Test Case 1 - Pacific Time (PROJECT DESCRIPTION UNDER PROJECT NAME)](https://github.com/hackforla/tdm-calculator/assets/156871712/9283d245-b706-436f-b2ef-03d355bb43fa)

**Comment by marlenamellody** [comment]
Update on project summary PDF (date and project status info on summary page PDF - at BOTTOM OF PAGE):
- Project status added to the bottom of the page along with the date information that was previously located at the bottom of the summary page PDF 
![DATE - BOTTOM)](https://github.com/hackforla/tdm-calculator/assets/156871712/d35acb6d-bbbe-493e-854c-92e1f219f07d)
![BOLD)](https://github.com/hackforla/tdm-calculator/assets/156871712/01737379-e08f-4b54-a0b5-5498360117f3)

[Figma Link](https://www.figma.com/file/nD9QK56Mzq7xNSaSUoeGx0/TDM-Calculator?type=design&node-id=12498-16712&mode=design&t=IIrkdFoo7aJxIH87-4)

**Comment by marlenamellody** [comment]
Update on project summary PDF (date and project status info on summary page PDF - at TOP OF PAGE):
Project status and date at the top of the page. 
possible issues: alters header and may not be consistent with page 5

![project status information - top)](https://github.com/hackforla/tdm-calculator/assets/156871712/2fd390f7-b460-42ad-b683-4ee93514536a)
![bold)](https://github.com/hackforla/tdm-calculator/assets/156871712/4eaba47d-5ed8-4837-b08b-d80f42e1ec3e)

[Figma Link](https://www.figma.com/file/nD9QK56Mzq7xNSaSUoeGx0/TDM-Calculator?type=design&node-id=12498-16713&mode=design&t=IIrkdFoo7aJxIH87-4)

**Comment by marlenamellody** [comment]
Update on page 5: (date and project status info added) 

In TDM strategies column: 
- Font size had to be reduced from 16px 14px to fit in column
![CP Page- Guest User (Status in strategies selected column )](https://github.com/hackforla/tdm-calculator/assets/156871712/8c6150aa-fc89-48e3-8bcb-1283cac53470)

In Calculation summary column: 
![CP Page- Guest User (date and status info in summary column)](https://github.com/hackforla/tdm-calculator/assets/156871712/396d6dd2-bf45-4cae-a993-a538dceeb201)

[Figma Link](https://www.figma.com/file/nD9QK56Mzq7xNSaSUoeGx0/TDM-Calculator?type=design&node-id=12498-19644&mode=design&t=IIrkdFoo7aJxIH87-4)

**Comment by Parisajf** [comment]
Updates after the steak holder meeting:

PDF: Project Details: version on right 
PDF: Snapshot and saved details: Bold the titles in footer
WEB: Snapshot and saved details: Add to bottom of main section of page, Bold the titles in footer
Confirmations
If it's not a snapshot, the snapshot text will not appear
If you are not logged in, no text will appear

**Comment by marlenamellody** [comment]
Updates after stakeholder's meeting: 
![TDM Summary page updated](https://github.com/hackforla/tdm-calculator/assets/156871712/103f8f17-6b3a-4dff-a45f-dfc96702bff0)
![CP Page- Guest User updated](https://github.com/hackforla/tdm-calculator/assets/156871712/42f81fa5-3e39-49f2-8707-0a653153cb67)

[Figma Link](https://www.figma.com/file/nD9QK56Mzq7xNSaSUoeGx0/TDM-Calculator?type=design&node-id=12572-3493&mode=design&t=dr1DejrU990dETRl-4)

**Comment by ExperimentsInHonesty** [comment]
The dev issues for this work are 
- #1674 
- #1675
