### ISSUE TITLE
Implement filtering, sorting  by Submit Date to the My Projects Page

### ISSUE THREAD

**Issue by entrotech** [hackforla/tdm-calculator#1659]
### Dependencies
- #1658 
- #1648 

### Overview
Add filtering and sorting of the projects by Submitted Date, so the user can filter and/or sort by Submitted date.

### Details 
The filtering and sorting UI has already been created for a similar field in the My Projects page (Created Date).  This issue will use that example and copy its code to implement the filtering for Submitted Date.  Please be aware the actual implementation differs from the Figma design, and we will fix that on another issue.

### Actions
- [ ] Review the Mockup
   - We don't have an exact mockup for how the Submit date is supposed to work or look, but we can use the [clickable Figma prototype for Created Date](https://www.figma.com/proto/nD9QK56Mzq7xNSaSUoeGx0/TDM-Calculator?type=design&node-id=12173-2052&t=wQuxLI1JbOw0OzLn-1&scaling=scale-down&page-id=2499%3A11472&starting-point-node-id=11997%3A885), because it will look and work the same.  Also, here is a screenshot:

   <details><summary>Screenshot</summary>

   ![image](https://github.com/user-attachments/assets/47f6c7ba-026b-4f45-8568-cb99f61701e9)
   </details> 
- [ ] Review the images from the actual implementation on the Created Date Filter

   <details><summary>When you click on the menu item filter</summary>

   
   ![image](https://github.com/user-attachments/assets/7068e3ea-359e-4eec-8af6-c406bb8d6329)

   </details> 

   <details><summary>When you click inside the date field</summary>

   
   ![image](https://github.com/user-attachments/assets/a1bc3d19-f61d-4507-9c95-1f0b1ffc31dd)

   </details> 

- [ ] Add sorting by Submitted Date
- [ ] Add filtering of Submitted Date by a Date Range

#### Examples from Created Date Filtering Issue and PR
- #1648 an issue that implements the filtering and sorting of created date
- https://github.com/hackforla/tdm-calculator/pull/1803 the PR that implements the Created Date filter

**Comment by ExperimentsInHonesty** [comment]
- This is already developed when #1801 was completed
