### ISSUE TITLE
Change trash can icon for Delete and Restore

### ISSUE THREAD

**Issue by heejung-hong** [hackforla/tdm-calculator#1661]
### Overview

To clarify the Restore function of the deleted project, the icon for the trash can will need to be replaced with a new icon.
The Delete icon will need to be changed to match the look of the Restore trash can icon.

### Action Items

- [x] Restore icon
  - `<FontAwesomeIcon icon="fa-solid fa-trash-arrow-up" />`
  - Color of trash can icon to be green when the project is selected.
- [x] Restore Project modal
  - `<FontAwesomeIcon icon="fa-solid fa-trash-arrow-up" />`
  - Color of the trash can icon to be green along with the wording "Restore Project from Trash."
  - The "RESTORE" button in the modal to also be green.
- [x] Delete icon
  - `<FontAwesomeIcon icon="fa-solid fa-trash" />`

### Resources/Instructions
- [fontawesome](https://fontawesome.com/search?q=trash&o=r&m=free)

**Comment by Parisajf** [comment]
Emily and Alexander have signed off on this
