### ISSUE TITLE
Design Mockup: My Project Page download

### ISSUE THREAD

**Issue by Parisajf** [hackforla/tdm-calculator#1676]
### Overview
We need to design a new flow for the downloading  in my project page.

### Action Items
We already worked on a download CSV flow in the admin view of my project page [issue 1641](https://github.com/hackforla/tdm-calculator/issues/1641#issuecomment-2062843455) and  it was decided to change the flow, we need to make sure that:

- The flow should be consistent with the rest of the flows like submit, delete...
- Revise the modal to use a download icon from Material UI

### Resources/Instructions
[Material UI](https://mui.com/material-ui/)
[Previous work on Download in admin view](https://github.com/hackforla/tdm-calculator/issues/1641)
[Dev issue ](https://github.com/hackforla/tdm-calculator/issues/1672)

**Comment by Parisajf** [comment]
We need the design to match modals with what we have in the website

**Comment by ExperimentsInHonesty** [comment]
![image](https://github.com/hackforla/tdm-calculator/assets/37763229/37cc0de0-76a4-42b4-ae3a-1b1a32e76fab)

![image](https://github.com/hackforla/tdm-calculator/assets/37763229/0ecf0d35-21d5-47bb-925e-e367fc834b56)

**Comment by ExperimentsInHonesty** [comment]
@yiranshan 
Please provide update
1. Progress: "What is the current status of your project? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"
5. Pictures or links* (if necessary): "Add any pictures or links that will help illustrate what you are working on."

* remember to add links to the top of the issue if they are going to be needed again.

**Comment by yiranshan** [comment]
Progress: update design follow dev version, change the button color to match design system
Blockers: delay on update the issue on my end. 
Availability: 6 hours this week
ETA: end of week

below screenshot is the older version, just to post here for record keeping
<img width="896" alt="Screen Shot 2024-05-09 at 4 21 16 PM" src="https://github.com/hackforla/tdm-calculator/assets/79798670/b852dd33-a951-4bc4-a056-ef7fe7cc8c1b">

This is the updated version to put on slide.
<img width="1018" alt="Screen Shot 2024-05-09 at 5 16 49 PM" src="https://github.com/hackforla/tdm-calculator/assets/79798670/48a820f7-7363-4eb5-9db5-06adb9680170">

**Comment by yiranshan** [comment]
update the 3 scenarios: 
1. filter applied and selected
2. filtered or selected (show either selection)
3. no action is appli
<img width="456" alt="Screen Shot 2024-05-09 at 9 01 27 PM" src="https://github.com/hackforla/tdm-calculator/assets/79798670/8167e55c-9cc0-4404-895a-e635d6a15ce1">
<img width="457" alt="Screen Shot 2024-05-09 at 9 01 37 PM" src="https://github.com/hackforla/tdm-calculator/assets/79798670/2b35b73c-8db6-4e25-8466-4c972199bb9c">
<img width="468" alt="Screen Shot 2024-05-09 at 9 02 49 PM" src="https://github.com/hackforla/tdm-calculator/assets/79798670/49b7c519-7b9f-4f25-8e1e-d0cfcc80aa8a">
ed

**Comment by Parisajf** [comment]
Approved
