### ISSUE TITLE
Implement My Projects Page Filter Settings Retention

### ISSUE THREAD

**Issue by Parisajf** [hackforla/tdm-calculator#1683]
### Dependencies
- #1646 
- #1647 
- #1648 

### Overview
To make the My Projects Page easier for users, the application should "remember" their filter and sorting settings for a browser session.

### Action Items
- [ ] Once all the filters have been implemented, implement code that saves the My Project Page filter and sorting criteria whenever a user makes changes.  If the user leaves the page and later returns within the same browser session, the setting should be restored so the user does not have to re-enter them

### Resources/Instructions
**2023-01-23 Stakeholder meeting feedback:**

- Emily and Xander both agreed that filter choices should be saved for the session, but not beyond.   A Session was then defined as until you log out or close the tab.

- See the screenshots on recreation.gov for how it shows the number of filters you are using:

![image](https://github.com/hackforla/tdm-clculator/assets/37763229/baefab86-6d69-49d1-a2b4-7ff8604f8416)

![image](https://github.com/hackforla/tdm-calculator/assets/37763229/25098653-dea8-4d9f-883e-20faf735ecc8)

**Comment by entrotech** [comment]
[Video Demo](https://drive.google.com/file/d/1ZKPr-tbE8eyayp1wRSxkISqI6rj2sULA/view?usp=sharing)

**Comment by ExperimentsInHonesty** [comment]
Appeared in the [2024-12-03 Stakeholder deck](https://docs.google.com/presentation/d/1vc_LUPreHrToHBRGUekbXfLflOi3omt2Bo8M7uxMovI/edit#slide=id.g31a1cbf228f_0_62) and was approved.
