### ISSUE TITLE
Update Icons

### ISSUE THREAD

**Issue by marlenamellody** [hackforla/tdm-calculator#1687]
### Overview
We need to arrange our existing icons from Figma and locate replacements from Material UI.
### Action Items
- [x] Organize existing Figma icons 
- [x] Find suitable replacements from Material UI. 
- [ ] don't change anything in Figma, this issue is to determine replacements only
- [ ] get sign-off from product.

### Resources/Instructions
[Material](https://mui.com/material-ui/material-icons/)
[Figma](https://www.figma.com/file/nD9QK56Mzq7xNSaSUoeGx0/TDM-Calculator?type=design&node-id=2619%3A11671&mode=design&t=XibyMVkHwPX3HMGK-1)

**Comment by yiranshan** [comment]
size added on for this issue, @Parisajf please adjust "feature", " milestone", " priority" tags.

**Comment by marlenamellody** [comment]
Updated iconography with replacements from [Material UI](https://fonts.google.com/icons?icon.set=Material+Icons): 
![Iconography (in progress)](https://github.com/hackforla/tdm-calculator/assets/156871712/75e10961-202c-442b-aea0-7ee63b60e175)
- The “save” icon in the current design system is not “filled” - I'm not sure where this icon is located on the site to compare, but based on the current design system standards, all icons should default to a filled version.
- The sort icon on the "my projects" page is not in the design system and I've proposed a replacement from MUI. 
- The color of selected checkboxes does not match the design system's color palette. 
- Need to confirm which "download" icon to use. 

[Figma](https://www.figma.com/design/nD9QK56Mzq7xNSaSUoeGx0/TDM-Calculator?node-id=12988-1277&t=FFzG5GfyIVWm2z6I-4)

**Comment by marlenamellody** [comment]
Progress: I've updated the iconography section for the style guide presentation slides.
Blockers: Still waiting on feedback re: icon selections (download icon, sort icon, save icon) 

<img width="1600" alt="Iconography1-slide" src="https://github.com/hackforla/tdm-calculator/assets/156871712/95bb6da5-97e7-4ddf-8152-bb496e8739b3">
<img width="1600" alt="Iconography2-slide" src="https://github.com/hackforla/tdm-calculator/assets/156871712/9fe065e1-9fb1-4ae0-a3ba-9c8910f06f96">

[Figma](https://www.figma.com/design/nD9QK56Mzq7xNSaSUoeGx0/TDM-Calculator?node-id=13143-209&t=SqJAG52BhxHlsMZX-4)

**Comment by yiranshan** [comment]
dependency on dev confirmation, waiting for further instructions.

**Comment by entrotech** [comment]
- Issue #1682 determined that there is no measurable impact to the bundle size by switching to any of the icon libraries mentioned here: https://react-icons.github.io/react-icons/, so this issue is ready to work on.  I would recommend that you look at these available sets and pick one that you think will cover almost all our needs.  We can always work with custom SVG icons for special cases, but sticking to a pre-designed library will be much less work.

**Comment by marlenamellody** [comment]
Icon replacements from https://react-icons.github.io/react-icons/icons/md/

**Comment by Parisajf** [comment]
Add names of icons and link the icon name to the relevant material UI Page.

**Comment by marlenamellody** [comment]
Replacement Icons from [Material UI](https://mui.com/material-ui/material-icons/) with links to relevant pages. 
[Figma](https://www.figma.com/design/nD9QK56Mzq7xNSaSUoeGx0/TDM-Calculator?node-id=13485-1236&t=OCX1JCiHP9dYzttR-4)

![Status Icons](https://github.com/hackforla/tdm-calculator/assets/156871712/8f217c5f-9aa4-41a7-bd91-09ac93853e94)
![Navigation Icons](https://github.com/hackforla/tdm-calculator/assets/156871712/e6825a22-0c97-409d-b25e-f40b763ce1a3)
![View Icons](https://github.com/hackforla/tdm-calculator/assets/156871712/776c9325-d813-47e7-ae57-ede4ddb9e40e)
![Action Icons](https://github.com/hackforla/tdm-calculator/assets/156871712/92a58255-6b57-4450-8b49-8a64be465091)

**Comment by ExperimentsInHonesty** [comment]
This issue is in the prioritized backlog and still assigned to someone.  Why? what needs to be done next.

**Comment by NilakshiS** [comment]
All the icons from FontAwesome have been replaced by Material UI icons, except for FileCSV icon for which no suitable replacement was found. The final icons have been approved by dev and stakeholders.

[Link to the latest icons on style guide presentation](https://docs.google.com/presentation/d/1I4q35NL2WW2RpksIyawhHCd8qJnrjme1ZDNIBxu24hQ/edit#slide=id.g2e77662f2ce_0_10)
