### ISSUE TITLE
Bug: NPM Server Tests do not run on Windows Machines.

### ISSUE THREAD

**Issue by entrotech** [hackforla/tdm-calculator#1695]
### Overview
Some of the developers have been working on jest tests for the web api server endpoints, and have them working on *nix machines, but when I (John Darragh) try to run them on a Windows machine, the Docker test container starts but fails to return from the call that starts the test container, preventing the tests from running.  Get the tests running on Windows, *nix and Mac OS machines.

### Action Items
- [x] Spent some time with @agosmou debugging, with limited success.
- [x] He mentioned that there is a new Test Container specifically for MS SQL Server that might work better than the Generic Container.
- [x] I re-wrote the mssql-container-setup.js file to use the new MS SQL Test Container, and it seems to be working well on Windows now.
- [ ] Need to have @agosmou , @WomB0ComB0  and @neyaadeez verify that the test run on their preferred platforms as well.

### Resources/Instructions

New MS SQL Container: https://node.testcontainers.org/modules/mssqlserver/

**Comment by neyaadeez** [comment]
It's working on my Linux system. Initially, I encountered an error with an npm package, so I simply ran the 'npm i' command, and the issue was resolved.

![image](https://github.com/hackforla/tdm-calculator/assets/87611344/5a3f6942-54ea-41be-825a-2d6af7fdb90b)
