### ISSUE TITLE
UI/UX: update project specifications page. 

### ISSUE THREAD

**Issue by KPHowley** [hackforla/tdm-calculator#170]
### Overview
Update the A6 project specifications page in Figma to reflect the data which is shown on the current website. Then update to make the data more clear, including updating column headers. 

### Action Items
- Update the Figma file to include the data fields on the Heroku app. 
- add column headers
- Make it more clear which entry box correlates to each specification. 
- Assign someone to review
- Create New Issue for front end development 

### Resources/Instructions
Figma Wireframe Link:
https://www.figma.com/file/qNgPc5lttpf0SWSwkbbWyT/TDM-Calculator?node-id=0%3A1
Heroku site:
http://tdm-calc.herokuapp.com/calculation
Follows up issue #18

**Comment by KPHowley** [comment]
Web page view before redesign: 
![Screen Shot 2020-01-08 at 6 10 17 PM](https://user-images.githubusercontent.com/49739276/72032431-3a917e80-3244-11ea-8baa-1e39bd042992.png)

**Comment by leopeng101** [comment]
As discussed with the lead last week, here is a clickable prototype of the page on January 28, 2020:

[Accordion option](url=https://www.figma.com/proto/hRvPuPi1XsV0vqd9Xy0yrm/TDM-Calculator?node-id=62%3A814&viewport=1452%2C422%2C0.12071696668863297&scaling=min-zoom).

**Comment by ExperimentsInHonesty** [comment]
We decided to apply the styling from the other designs we had approved.  But are retaining the design for future discussion.

![Screen Shot 2020-02-08 at 10 09 22 AM](https://user-images.githubusercontent.com/37763229/74089988-6e3a1100-4a5b-11ea-92ae-3eaa88842163.png)
