### ISSUE TITLE
Create Web API endpoints to support Submitting a Project for Approval

### ISSUE THREAD

**Issue by entrotech** [hackforla/tdm-calculator#1704]
### Overview
In order to support features related to submitting a project for approval, we need to implement the web api endpoints and supporting database changes.

### Action Items
- [x] Add a dateSubmitted column to the Project table.
- [x] Add a web api endpoint for HTTP PUT requests with url /api/proects/submit. The body will consist of the project id, and the route will use the jwtSession.validateUser middleware to verify the user identity.  The Controller function should verify that the project id corresponds to the loginId of the user that owns the corresponding project, and call a service that, in turn, calls a Project_Submit stored procedure. The stored procedure should have argument projectId, loginId, and update the dateSubmitted column value to the current datetime.  Most of this is very  similar to the existing /api/projects/snapshot endpoint.

**Comment by Parisajf** [comment]
@heejung-hong 
Please provide update
1. Progress: "What is the current status of your project? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"
5. Pictures or links* (if necessary): "Add any pictures or links that will help illustrate what you are working on."

* remember to add links to the top of the issue if they are going to be needed again.

**Comment by heejung-hong** [comment]
@Parisajf 
1. Progress: Coded the backend, but could not complete route testing in Postman.  Will work on creating the frontend submit button with modal and submit to John for review.
2. Blockers: Wasn't able to complete test in Postman.
3. Availability: Evenings
4. ETA: Front-end by 6/19

**Comment by ExperimentsInHonesty** [comment]
@heejung-hong 
Please provide update
1. Progress: "What is the current status of your project? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"
5. Pictures or links* (if necessary): "Add any pictures or links that will help illustrate what you are working on."

* remember to add links to the top of the issue if they are going to be needed again.

**Comment by heejung-hong** [comment]
Please find my update below.

1. Progress: Need to create new migration script for Project_Submit store procedure and continue to work on a new endpoint.
2. Blockers: Need to review the project.
3. Availability: Weekdays after 6pm.
4. ETA: Can't confirm the ETA at this time.
