### ISSUE TITLE
Research: Create Research Plan for My Projects Page Usability Testing

### ISSUE THREAD

**Issue by abbyrivard** [hackforla/tdm-calculator#1711]
### Overview
We need to create a research plan to define the research scope, goals, and methods for the My Projects page usability testing.

#### Details
This testing will only include end users and not admins.

### Action Items
- [x] Create Research Plan Google Doc utilizing the TDM style guides [needs creation]
- [x] Add information for each section below and check off as you go:
    - [x] Background
    - [x] Research Questions and Objectives
    - [x] Participants
    - [x] Research Assumptions
    - [x] Research Methods
    - [x] Data Analysis
    - [x] Timeline
    - [x] Resources
        - [x] Wiki Pages
        - [x] Further Documentation
- [x] Get Research Plan approved by PMs
- [x] Check off the Dependency on #1712 
- [x] Add Research Plan Link to Issue 1712
- [x] Add Research Plan to the wiki documentation
- [x] Add Research Plan Link to resources section of #1715 

#### Resources for creating this issue
- #1663
- Reference previous research plan: [TDM: RP004 Reset Button Research Plan](https://docs.google.com/document/d/12GB3YQfh6cy9ynXriRNNwWAMQ8PTpkHfc8J4qPBXMO0/edit).
- Wiki: [RP005 My Projects Page Usability Test](https://github.com/hackforla/tdm-calculator/wiki/RP005-My-Projects-Page-Usability-Test)
#### Resources gathered during the completion of this issue
- [RP005: My Projects Page Research Plan](https://docs.google.com/document/d/1kgn9mjatonuqM0Fy4ej5yfI6iE7jQI-Thk6MA9UAi7A/edit?tab=t.0)
- [DR Determining who to recruit for the My Projects page usability testing](https://github.com/hackforla/tdm-calculator/wiki/DR-Determining-who-to-recruit-for-the-My-Projects-page-usability-testing)

**Comment by melissaperry09** [comment]
**Progress:** Team leads have created the structure of the document and completed the background and methodology sections. 
**Blockers:** Need to discuss the primary goals of the My Projects page testing with PMs to ensure our research questions and user recruitment strategy align with the insights we are trying to gain from this testing. 
**Availability:** Team leads will work on this during team breakout on October 16, 2024, and have additional discussion at the leads meeting on October 17, 2024, if needed. 
**ETA:** October 23, 2024.

**Comment by abbyrivard** [comment]
Ready for a review of the [RP005: My Projects Page Research Plan](https://docs.google.com/document/d/1kgn9mjatonuqM0Fy4ej5yfI6iE7jQI-Thk6MA9UAi7A/edit?tab=t.0)

**Comment by abbyrivard** [comment]
Bonnie approved the research plan after reviewing it with @melissaperry09 at the leads meeting on 10/31/2024. Therefore, we are closing this issue and moving forward to the next issue on the Epic.
