### ISSUE TITLE
Produce a list of the features in My Projects Page

### ISSUE THREAD

**Issue by Parisajf** [hackforla/tdm-calculator#1719]
### Overview
We need to create a list with all the  the features in My Projects Page.

### Action Items
- [x] Find the Figma Designs for My Projects and add the links in the Resources section
- [x] Open the My Project's page (in Figma), create a list of every feature that user can do per designs in the spreadsheet provided
- [x] Go to the My Project's page in Dev environment and add check boxes next to each feature that is deployed (column D)
- [x] get sign-off by design/dev/product on the list
- [x] look for issues already written for each missing deployment (pm, design, dev), and annotate any you find on the spreadsheet (column E).
- [x] get sign-off by design/dev/product on the list.
- [x] Create epics to make all the issues.

### Resources/Instructions
- Spreadsheet: [My Project's page features](https://docs.google.com/spreadsheets/d/149NsNfjEuiKsgw0L_t3fWR-ttRuGJWCwp2gKgU73fNg)
- My Project's page: https://tdm-dev.azurewebsites.net/projects
- Figma Designs: [Link to the section on Figma file](https://www.figma.com/design/nD9QK56Mzq7xNSaSUoeGx0/TDM-Calculator?node-id=14202-27208&t=C41q3U9Xuc7C7uPb-1)

**Comment by NilakshiS** [comment]
Added a link the latest designs in the Figma file to the resources section.

**Comment by Parisajf** [comment]
@entrotech @NilakshiS @marlenamellody Please check the spreadsheet and sign it off by Wednesday
