### ISSUE TITLE
Design: Create Style Guide - Dialog Boxes, Modals, Accordions Tabs, Tooltips, Infoboxes

### ISSUE THREAD

**Issue by yiranshan** [hackforla/tdm-calculator#1721]
### Overview
We need to create a Google deck of all the style guide pages on Figma and add a link to the wiki
This is a sub issue for Dialog Boxes, Modals, Accordions Tabs, Tooltips, Infoboxes

### Action Items

- [ ] Finalize this section for design system
- [ ] update Style Guide Presentation

### Resources/Instructions
- [Google Slides Style Guide Presentation](https://docs.google.com/presentation/d/1I4q35NL2WW2RpksIyawhHCd8qJnrjme1ZDNIBxu24hQ/edit#slide=id.g2a6d1bfeb46_0_103)
- [Link to style guide in Figma](https://www.figma.com/file/nD9QK56Mzq7xNSaSUoeGx0/TDM-Calculator?type=design&node-id=2619-11671&mode=design&t=oSV4Vrfj1WvuN2Rw-0)
- [presentation format](https://github.com/hackforla/tdm-calculator/wiki/Style-Guide#:~:text=calculator.wiki.git-,Presentation%20Format,-Add%20a%20custom)
- [Wiki](https://github.com/hackforla/tdm-calculator/wiki#:~:text=Team%20Meetings-,Style%20Guide,-Add%20a%20custom)

**Comment by yiranshan** [comment]
1. Progress: edited notes from stakeholder
2. Blockers: not sure if the edits are correct
3. Availability: 4 hours next week 
4. ETA: next week 
<img width="1304" alt="Screen Shot 2024-05-28 at 10 45 34 PM" src="https://github.com/hackforla/tdm-calculator/assets/79798670/78719936-cead-43ef-b740-1da5f719561c">
<img width="1303" alt="Screen Shot 2024-05-28 at 10 45 17 PM" src="https://github.com/hackforla/tdm-calculator/assets/79798670/d9a8456d-a86b-4a37-8ad1-f08b2aea5ec1">

**Comment by lbeatonn** [comment]
![Screen Shot 2024-06-17 at 4 42 36 PM](https://github.com/hackforla/tdm-calculator/assets/91226916/e76ae555-e1e9-408c-8a34-2f47c3a4919d)

Emily's comment on Typography slide 7: "Are tool tips in the Paragraph 1 style?"

See resolution on Slide 8

**Comment by lbeatonn** [comment]
![Screen Shot 2024-06-17 at 4 43 57 PM](https://github.com/hackforla/tdm-calculator/assets/91226916/7945a773-2c24-455b-b03e-d381d8f0dbb5)

Emily's comment on Buttons slide 13: "At the top of the 2nd column, the "Edit Section" button is a style that we don't see outlined on the left of this slide. Please make sure there's an explanation of when to use that style, too." 

Resolved on slide 14 with that button style removed

**Comment by lbeatonn** [comment]
![Screen Shot 2024-06-17 at 4 53 55 PM](https://github.com/hackforla/tdm-calculator/assets/91226916/d69655c6-d2c3-45f4-8807-35547197fd45)

Emily's comment on Icons slide 18: "I think there was recent discussion of changing the icon library... did that happen, and if so, are these all the new icons for the app?"

@marlenamellody changed the icons, but the status is Pending Approval from dev team

**Comment by lbeatonn** [comment]
![Screen Shot 2024-06-17 at 4 57 29 PM](https://github.com/hackforla/tdm-calculator/assets/91226916/745d222e-7a26-4057-bc42-437794da155e)

Emily's comment on Icons slide 28 Tooltips

Resolved on Slide 29

**Comment by lbeatonn** [comment]
![Screen Shot 2024-06-17 at 4 59 20 PM](https://github.com/hackforla/tdm-calculator/assets/91226916/3918f9d2-2178-45e1-9330-9f8cd61be44e)

Emily's comment on Headers slide 37 "The Logged-in header may be the wrong image (it still says "Login")"

Resolved on Slide 38

**Comment by lbeatonn** [comment]
Added caption for tooltip in typography - Slide 9 is new slide [Comment](https://docs.google.com/presentation/d/1I4q35NL2WW2RpksIyawhHCd8qJnrjme1ZDNIBxu24hQ/edit?disco=AAABQJowock)

**Comment by Parisajf** [comment]
Buttons:

The use of the tertiary button (when it has a green outline), is for when there are two positive buttons on the same page, the outline version is less important option)

![Screen Shot 2024-06-20 at 4 04 30 PM](https://github.com/hackforla/tdm-calculator/assets/134427433/a51791b9-e185-489b-a4a7-fafbb6bd18a3)


https://docs.google.com/presentation/d/1I4q35NL2WW2RpksIyawhHCd8qJnrjme1ZDNIBxu24hQ/edit#slide=id.g27275e02f73_6_0
https://docs.google.com/presentation/d/1I4q35NL2WW2RpksIyawhHCd8qJnrjme1ZDNIBxu24hQ/edit#slide=id.g2e134a56948_6_41

**Comment by Parisajf** [comment]
Default Text Inputs
Missing Active with no placeholder (see page 2 of calculator)

Slide:
https://docs.google.com/presentation/d/1I4q35NL2WW2RpksIyawhHCd8qJnrjme1ZDNIBxu24hQ/edit#slide=id.g2a5d13e8d2c_0_196

**Comment by namigoeku** [comment]
![image](https://github.com/hackforla/tdm-calculator/assets/126614231/042d2fc6-bdfa-440b-aeaa-4f2012f90541)
[https://docs.google.com/presentation/d/1I4q35NL2WW2RpksIyawhHCd8qJnrjme1ZDNIBxu24hQ/edit?disco=AAABN4cO7ng](url)

**Comment by namigoeku** [comment]
![image](https://github.com/hackforla/tdm-calculator/assets/126614231/6cb49934-f4ac-42e5-b98a-2280fdcd8e40)
[https://docs.google.com/presentation/d/1I4q35NL2WW2RpksIyawhHCd8qJnrjme1ZDNIBxu24hQ/edit?disco=AAABQJowock](url)

**Comment by namigoeku** [comment]
![image](https://github.com/hackforla/tdm-calculator/assets/126614231/eb7fb610-252e-4ffc-a835-cc1d456fa1c4)
[https://docs.google.com/presentation/d/1I4q35NL2WW2RpksIyawhHCd8qJnrjme1ZDNIBxu24hQ/edit?disco=AAABN4cO7no](url)

**Comment by namigoeku** [comment]
[https://docs.google.com/presentation/d/1I4q35NL2WW2RpksIyawhHCd8qJnrjme1ZDNIBxu24hQ/edit?disco=AAABQGiLbOM](url)

![image](https://github.com/hackforla/tdm-calculator/assets/126614231/f5721f7d-7b6e-468d-96ef-1a5b258ca4fc)

**Comment by namigoeku** [comment]
[https://docs.google.com/presentation/d/1I4q35NL2WW2RpksIyawhHCd8qJnrjme1ZDNIBxu24hQ/edit?disco=AAABPnC9w6w](url)

![image](https://github.com/hackforla/tdm-calculator/assets/126614231/c9f04da9-3b2e-4130-a1f8-f37a88c16c13)

**Comment by NilakshiS** [comment]
Added the different infoboxes currently on the dev site (as of 08/21/24) to the style guide:
[Link to "Infoboxes" on Figma](https://www.figma.com/design/nD9QK56Mzq7xNSaSUoeGx0/TDM-Calculator?node-id=13759-501&t=4UkLiYbzAvEGotvY-1)
<img width="1600" alt="Infoboxes" src="https://github.com/user-attachments/assets/f504540d-4298-4a4e-a5d0-0318e5aaa2ab">

[Link to "Infoboxes - 2" on Figma](https://www.figma.com/design/nD9QK56Mzq7xNSaSUoeGx0/TDM-Calculator?node-id=13857-505&t=4UkLiYbzAvEGotvY-1)
<img width="1600" alt="Infoboxes - 2" src="https://github.com/user-attachments/assets/5a2b5261-76dc-40a2-a13c-11cd6b53f247">

**Comment by NilakshiS** [comment]
Made the following changes to infoboxes to match the style guide prescribed typography and colors:

- Warning infobox: changed background color to "Error background" and title font to "Heading 1".
- Guide infobox: changed background color to "Greyscale/Light Gray", added a bottom padding.
- Target points infobox: changed font to "Paragraph" style.
- Points Notification infobox: Changed font to "Subheading" style, removed drop shadow, reduced container size to fit-content.

[Link to "Infoboxes - iteration 2" on Figma](https://www.figma.com/design/nD9QK56Mzq7xNSaSUoeGx0/TDM-Calculator?node-id=13874-505&t=4UkLiYbzAvEGotvY-1)
<img width="1600" alt="Infoboxes - interation 2" src="https://github.com/user-attachments/assets/5bb19f5f-1398-4412-9fc1-25c1032d57d5">

[Link to "Infoboxes - 2 - iteration 2" on Figma](https://www.figma.com/design/nD9QK56Mzq7xNSaSUoeGx0/TDM-Calculator?node-id=13874-547&t=4UkLiYbzAvEGotvY-1)
<img width="1600" alt="Infoboxes - 2 iteration 2" src="https://github.com/user-attachments/assets/16bbbe19-2a2b-4cb5-8ede-d11a5c60d3e9">

**Comment by ExperimentsInHonesty** [comment]
Changes accepted by stakeholder
