### ISSUE TITLE
Design: Mock up Copy Snapshot user flow

### ISSUE THREAD

**Issue by yiranshan** [hackforla/tdm-calculator#1723]
### Overview
We need to design a user flow for snap shot to be copied and edited. 
START - OPEN SNAPSHOT
There will be 2 scenarios that a snapshot will be opened: 
1) shared through email with a link.
2) opened from my project page, 
both scenarios should lead to directly open page 5(summary page) of a snapshot. 
FLOW 1
copy snapshot-open modal-create copy-wizard-save
FLOW 2
Edit snapshot- open modal-copy snapshot-create copy-wizard-save

### Action Items
- [ ]  design a user flow that will make this process accessible
- [ ]  mock up the related screens
- [ ]  report to design team for feedback
- [ ]  report to product owner and stake holders for iterations

urgent, first draft should be done by 06.05.2024

### Resources:

- [FIGMA LINK](https://www.figma.com/design/nD9QK56Mzq7xNSaSUoeGx0/TDM-Calculator?node-id=13241-7534&t=6ypyhp0s2F3n4tWU-1)
<img width="745" alt="Screen Shot 2024-05-30 at 9 01 00 PM" src="https://github.com/hackforla/tdm-calculator/assets/79798670/afa97c16-091c-490d-a7f1-2d478b406611">
<img width="525" alt="Screen Shot 2024-05-30 at 9 04 17 PM" src="https://github.com/hackforla/tdm-calculator/assets/79798670/3eb0dc61-a5b2-436c-a1d8-dd261458045a">
<img width="914" alt="Screen Shot 2024-05-30 at 9 04 22 PM" src="https://github.com/hackforla/tdm-calculator/assets/79798670/4b30747c-6ec3-40e5-b605-9d81d6dc7b22">
Rources/Instructions

**Comment by lbeatonn** [comment]
IN PROGRESS

**Comment by lbeatonn** [comment]
Added figma link under resources

**Comment by Parisajf** [comment]
- Need to find an alternative for  the wording instead of " You are not the owner of the project..."
- When the user does not  own the project :After clicking on "Edit" the user will see another modal with two options : want  to save or edit? landing page will be different based on the selection  ( my projects page  Vs  page 1 of the project )

**Comment by ExperimentsInHonesty** [comment]
Shared File
1. Click `COPY & EDIT PROJECT`

2. Modal Copy & Edit Project
    Text: You are looking at a project snapshot that has been shared with you. To save it to your "My Projects" page, create a copy of this project, which you can view and edit.
    Buttons: `NO, CANCEL` `CREATE A COPY`

**Comment by Parisajf** [comment]
@hanselnoriega Please provide an update by Aug-14.

**Comment by ExperimentsInHonesty** [comment]
@hanselnoriega All you have to do is write up what you already have in Figma.  This should be done by now.  Please reach out in the Slack channel for tdm as soon as this has been completed so that we can get back to you with changes to the designs.  If you don't have time to work on this anymore, please let us know asap, as this issue is overdue and holding up an important part of development.

**Comment by Parisajf** [comment]
Hansel's Update:
Shared File: User-Journey

Click on COPY & EDIT PROJECT button
Buttons: a) Copy & Edit Project b) Print Summary


Copy & Edit Project screen modal appears
Text: You are looking at a project snapshot that has been shared with you. To save it to your "My Projects" page, create a copy of this project, which you can view and edit.
Click on CREATE A COPY button 
Buttons: a) No, Cancel b) Create A Copy


Edit Project screen modal appears
Text: Edit the new copy or go to the “My Projects” dashboard
Click on EDIT PROJECT COPY button
Buttons: a) My Projects b) Edit Project Copy


If the MY PROJECT COPY  button is selected, then Welcome to Los Angeles’ Transportation Demand Management (TDM) Calculator. First, let’s get some information about your project screen appears
Text: Original text from page 1 screen
Buttons: a) Page ⅕, Next > b) Save Project

If EDIT PROJECT COPY button is selected, then Active Projects screen appears
Text: Original text from Active Project screen
Buttons: a) Page 1 b) Page 2 c) Page 3 d) Page 4 e) Page 5




Snapshot Viewed by Owner

Click on COPY & EDIT PROJECT button
Buttons: a) Copy & Edit Project b) Print Summary


Create Editable Copy screen modal appears
Click on CREATE A COPY button
Text: This snapshot cannot be edited. Create a copy of the project to edit. Name the new project to start editing.
Buttons: a) No, Cancel b) Create A Copy


If CREATE A COPY button is selected, then Continue? modal appears
Text: View the “My Project” dashboard or continue to edit the new copy.
Buttons: a) My Project b) Edit Copy

If NO, CANCEL button is selected, then TDM Calculation Summary (back to the beginning) screen appears
Text: Original text from TDM Calculation Summary screen appears 
Buttons: a) Copy & Edit Project b) Print Summary

[Link to Figma](https://www.figma.com/design/nD9QK56Mzq7xNSaSUoeGx0/TDM-Calculator?t=hEbWKbm4ZABgnyru-0)

**Comment by Parisajf** [comment]
The client signed off on the flow and design.

**Comment by entrotech** [comment]
- Created follow-up Dev Issue #1795

**Comment by ExperimentsInHonesty** [comment]
@hanselnoriega please move this file [LADOT - Issue 1723 - 08.12.24](https://docs.google.com/document/d/1eBndP-nLFOZrI6TNctHgeWfVF2-ZFBlvpJ1E2lt5csU/edit?tab=t.0) into the Shared drive.

**Comment by ExperimentsInHonesty** [comment]
The document has been moved
