### ISSUE TITLE
Design: Create Style Guide Presentation (Text Area/Fields)

### ISSUE THREAD

**Issue by namigoeku** [hackforla/tdm-calculator#1725]
### Overview
We need to create a Google deck of all the style guide pages on Figma and add a link to the wiki

### Action Items

- [X] Finalize this section for design system
- [x] update Style Guide Presentation

### Resources/Instructions
- [Google Slides Style Guide Presentation](https://docs.google.com/presentation/d/1I4q35NL2WW2RpksIyawhHCd8qJnrjme1ZDNIBxu24hQ/edit#slide=id.g2a6d1bfeb46_0_103)
- [Link to style guide in Figma](https://www.figma.com/file/nD9QK56Mzq7xNSaSUoeGx0/TDM-Calculator?type=design&node-id=2619-11671&mode=design&t=oSV4Vrfj1WvuN2Rw-0)
- [presentation format](https://github.com/hackforla/tdm-calculator/wiki/Style-Guide#:~:text=calculator.wiki.git-,Presentation%20Format,-Add%20a%20custom)
- [Wiki](https://github.com/hackforla/tdm-calculator/wiki#:~:text=Team%20Meetings-,Style%20Guide,-Add%20a%20custom)

**Comment by namigoeku** [comment]
![Done Slides](https://github.com/hackforla/tdm-calculator/assets/126614231/1bd4b888-e7d4-4e02-90f9-9d5aafac6a80)

**Comment by lbeatonn** [comment]
![Screen Shot 2024-06-17 at 5 04 18 PM](https://github.com/hackforla/tdm-calculator/assets/91226916/8651b7c9-e34b-46de-95e4-577769c5cb21)

Bonnie's Comment on Text Inputs Slide 32: "should there be a Active (not selected)?"

We are currently looking into this as a team

**Comment by namigoeku** [comment]
Updated. 
<img width="963" alt="Screenshot 2024-06-19 at 6 58 10 PM" src="https://github.com/hackforla/tdm-calculator/assets/126614231/d27d3a36-f228-4137-9ec1-5916ab951f71">

**Comment by NilakshiS** [comment]
By Parisa:
Default Text Inputs

Terms:
Active: Selected
Inactive: Not selected
Disabled: Not available

Slide:
https://docs.google.com/presentation/d/1I4q35NL2WW2RpksIyawhHCd8qJnrjme1ZDNIBxu24hQ/edit#slide=id.g2a5d13e8d2c_0_196

**Comment by namigoeku** [comment]
![image](https://github.com/hackforla/tdm-calculator/assets/126614231/042d2fc6-bdfa-440b-aeaa-4f2012f90541)
[https://docs.google.com/presentation/d/1I4q35NL2WW2RpksIyawhHCd8qJnrjme1ZDNIBxu24hQ/edit?disco=AAABN4cO7ng](url)

**Comment by namigoeku** [comment]
![image](https://github.com/hackforla/tdm-calculator/assets/126614231/6cb49934-f4ac-42e5-b98a-2280fdcd8e40)
[https://docs.google.com/presentation/d/1I4q35NL2WW2RpksIyawhHCd8qJnrjme1ZDNIBxu24hQ/edit?disco=AAABQJowock](url)

**Comment by namigoeku** [comment]
[https://docs.google.com/presentation/d/1I4q35NL2WW2RpksIyawhHCd8qJnrjme1ZDNIBxu24hQ/edit?disco=AAABQGiLbOM](url)

![image](https://github.com/hackforla/tdm-calculator/assets/126614231/f5721f7d-7b6e-468d-96ef-1a5b258ca4fc)

**Comment by namigoeku** [comment]
[https://docs.google.com/presentation/d/1I4q35NL2WW2RpksIyawhHCd8qJnrjme1ZDNIBxu24hQ/edit?disco=AAABPnC9w6w](url)

![image](https://github.com/hackforla/tdm-calculator/assets/126614231/c9f04da9-3b2e-4130-a1f8-f37a88c16c13)

**Dropdown on the Select TDM Strategies Page**
![image](https://github.com/hackforla/tdm-calculator/assets/126614231/8ce992dc-0de5-4662-b9ab-b9ef54e39ca8)

**Searchbar on My Projects Page**
![image](https://github.com/hackforla/tdm-calculator/assets/126614231/c8e475ef-55b6-464f-b76a-4971eccc07a2)

**Comment by ExperimentsInHonesty** [comment]
![image](https://github.com/user-attachments/assets/18bdd5ca-169c-4cf9-ad04-27ed8518826b)

**Comment by ExperimentsInHonesty** [comment]
Screenshot of Parisa's Mac ![image](https://github.com/user-attachments/assets/59650312-9be8-465f-99ba-a6fb38bb792e)

**Comment by ExperimentsInHonesty** [comment]
Screenshot of John's Windows machine
![image](https://github.com/user-attachments/assets/f27f7522-aa73-4bb5-a7f9-f16f30a788d5)

**Comment by namigoeku** [comment]
Made the changes to the dropdown according to how it appears in Bonnie's comment. Updated the slide. 

![Frame 625015](https://github.com/user-attachments/assets/8acf28a5-e572-42f8-86aa-119c0cd4bf04)

**Comment by NilakshiS** [comment]
Added required field (inactive) with red dashed border and no label as seen on the "create project - page 1"
<img width="1600" alt="Fields - iteration 2 part 1" src="https://github.com/user-attachments/assets/a8932c96-99ca-4920-b9f9-aa1124f18fdb">

Added default text inputs with no placeholders as seen on the "create project - page 2"
<img width="1600" alt="Fields - iteration 2 part 2" src="https://github.com/user-attachments/assets/d829ac0e-ef70-40d4-ab1f-531500771ff4">

Added these to the style guide slide deck:
[Default text inputs slide](https://docs.google.com/presentation/d/1I4q35NL2WW2RpksIyawhHCd8qJnrjme1ZDNIBxu24hQ/edit#slide=id.g2a5d13e8d2c_0_196)
[Default text inputs slide 2](https://docs.google.com/presentation/d/1I4q35NL2WW2RpksIyawhHCd8qJnrjme1ZDNIBxu24hQ/edit#slide=id.g2f74a24ec8f_0_58)

**Comment by ExperimentsInHonesty** [comment]
The text inputs have been accepted by stakeholder
