### ISSUE TITLE
UI/UX: Allow for saving throughout the Wizard

### ISSUE THREAD

**Issue by KPHowley** [hackforla/tdm-calculator#173]
### Overview
Design the interface for a saving feature which allows users to save their calculations. Research and thought still needs to be put into the best user design for this 

### Action Items
- [x] Design a save button to be used throughout the wizard
- [x] Experiment with progress bar or page numbers
- [x] Review with LADOT
- [x] Create issue for front end development.

**Comment by dreams0ng** [comment]
CHANGES

1. - [X] Design a save button to be used throughout the wizard
2. - [X] Experiment with progress bar or page numbers

MOCKUPS
1a
![Screen Shot 2020-07-30 at 2 11 03 PM](https://user-images.githubusercontent.com/22779768/88975152-9407dc00-d26e-11ea-880e-a6ed16004a68.png)

1b
![Screen Shot 2020-07-30 at 2 12 00 PM](https://user-images.githubusercontent.com/22779768/88975206-a97d0600-d26e-11ea-8084-38d0d3d2466a.png)

2a
*this is the progress bar version, and you can see how it would work with pages one and two, where the translucent boxes hit full opacity
![Screen Shot 2020-07-30 at 2 12 45 PM](https://user-images.githubusercontent.com/22779768/88975363-e943ed80-d26e-11ea-9944-7a123ba2f705.png)
![Screen Shot 2020-07-30 at 2 12 51 PM](https://user-images.githubusercontent.com/22779768/88975374-ecd77480-d26e-11ea-9c26-00fa2458662f.png)

2b
*page number version seen elsewhere
![Screen Shot 2020-07-30 at 2 15 07 PM](https://user-images.githubusercontent.com/22779768/88975473-18f2f580-d26f-11ea-90ef-9dbf92e5d395.png)

LINKS
https://www.figma.com/file/6h72XLxK76m4INtsSu8Mt0/TDM-Calculator-Copy?node-id=2246%3A20

**Comment by dreams0ng** [comment]
CHANGES
+separated reset page and save project buttons
-moved reset page to original position at top right of form

MOCKUPS
![giphy-3](https://user-images.githubusercontent.com/22779768/90557474-63211580-e14f-11ea-8347-f15b8fb342c1.gif)

LINKS
https://xd.adobe.com/view/f32a7d21-a346-43a1-6e66-809bd1399976-851b/

**Comment by ExperimentsInHonesty** [comment]
@KPHowley What else is there to show David.  He didn't have any comments on it.  Can we just go direct to development?

**Comment by dreams0ng** [comment]
CHANGES
+changed save button color from gray to green

MOCKUPS
![Screen Shot 2020-08-26 at 6 18 31 PM](https://user-images.githubusercontent.com/22779768/91372562-cbfc3380-e7c8-11ea-9961-b4d9a0a77e55.png)

LINKS
https://xd.adobe.com/view/f32a7d21-a346-43a1-6e66-809bd1399976-851b/screen/e6396816-04b0-4958-a5f8-e788f740c02b

**Comment by KPHowley** [comment]
@dreams0ng  - Can you make a design just for the save project button so we can update that first before deciding on the page #'s (or page icons)

**Comment by KPHowley** [comment]
@VJ1285 @KPHowley - Need to update this for front end development, and create a separate issue for the progress bar

**Comment by dreams0ng** [comment]
1) Progress
v5 - removed progress indicators

![Screen Shot 2020-10-20 at 10 16 35 AM](https://user-images.githubusercontent.com/22779768/96622137-6c993c00-12be-11eb-8791-253bf6a4fff3.png)

2) Blockers
n/a
3) Availability

4) ETA
10/20/20
