### ISSUE TITLE
User Registration: Need prompt to check email

### ISSUE THREAD

**Issue by entrotech** [hackforla/tdm-calculator#174]
When a user registers successfully, they need to be prompted with a notification to check their email. This used to work until PR #163   , which replaced the toaster-style notification with a message that shows up on the Register.js component.  The problem is that upon successful registration, the user is immediately redirected to the Login page and does not get a chance to see this important message.

**Comment by ExperimentsInHonesty** [comment]
@bfojas says eta is 1/18 end of day

**Comment by bfojas** [comment]
Fixed in PR #208
