### ISSUE TITLE
Bug: Test case number and the texts alignment

### ISSUE THREAD

**Issue by Parisajf** [hackforla/tdm-calculator#1741]
### Overview
We need to fix the number and the texts alignment in the page and the prints

### Action Items
- Check the alignment of numbers and texts and fix them in the page
- Check the alignment of numbers and texts and fix them in the print
- 
### Resources/Instructions
 Review the screenshots in the first comment

**Comment by ExperimentsInHonesty** [comment]
<details><summary>Dev Summary Screenshot</summary>
<p>

![image](https://github.com/hackforla/tdm-calculator/assets/37763229/f53d7fca-338f-4d00-81fc-bc9f9eb156ea)


</p>
</details> 

<details><summary>Prod Summary Screenshot</summary>
<p>

![image](https://github.com/hackforla/tdm-calculator/assets/37763229/71b414b0-93ba-4d26-b189-5757e45fe9e4)

![image](https://github.com/hackforla/tdm-calculator/assets/37763229/4e2e133b-b451-460e-bd0f-064283238f1c)


</p>
</details>

**Comment by entrotech** [comment]
- Fixed on pull request #1756
