### ISSUE TITLE
Modify the PDF Print format so the footer appears on each page.

### ISSUE THREAD

**Issue by entrotech** [hackforla/tdm-calculator#1757]
### Overview
When you print a Project to a PDF file, it contains some date information in a footer. Currently, the footer appears under the last part of the body, wherever  that lies on the page. Instead, the date information should appear as a footer at the bottom of each page.

### Action Items
- [ ] PR #11756 includes a temporary fix that just puts the footer after all the report content, but not at the bottom of the page - this issue improves on that quick fix.
- [ ] Apply the technique described [here](https://medium.com/@Idan_Co/the-ultimate-print-html-template-with-header-footer-568f415f6d2a) to display the footer at the bottom of each page without overlapping the report content.

### Resources/Instructions
Current implementation (Notice how the footer is overlaid on top of the report content at the bottom of the page):
![image](https://github.com/hackforla/tdm-calculator/assets/9939032/20575c30-6d20-4028-94d7-0bcf60430397)

**Comment by ParthJohri** [comment]
Greetings @entrotech, I would like to work on this issue, could you please assign it to me?
Thank you!
