### ISSUE TITLE
Reset Password: need confirmation that email was sent/prompt to check email.

### ISSUE THREAD

**Issue by entrotech** [hackforla/tdm-calculator#176]
PR #171 implemented the reset password feature, which seems to work well. However, I would like to see a toast message or some other prominent notification confirming that the email was sent and directing the user to check their email and use the link provided.

**Comment by bfojas** [comment]
@entrotech there is a conditional render on it that should change when the submit is successful (lines 146 - 151). It works on the local, but I have to look into why it doesnt work on the heroku app. Might be something weird with the useState.

**Comment by bfojas** [comment]
PR #186

**Comment by KPHowley** [comment]
@bfojas - did we figure out was going on with the duplicate email issue?
