### ISSUE TITLE
Change iconography with icons from Material UI

### ISSUE THREAD

**Issue by heejung-hong** [hackforla/tdm-calculator#1760]
### Overview
Font Awesome free version doesn't have all of the icons needed for the project.  All icons in the project will need to be swapped out with Material UI icons.

### Action Items
- [ ] Replace all icons in the project with Material UI icons linked below in the resources section.

### Resources/Instructions
[Links to icons in Material UI](https://docs.google.com/presentation/d/1I4q35NL2WW2RpksIyawhHCd8qJnrjme1ZDNIBxu24hQ/edit#slide=id.g2e77662f2ce_0_10)

**Comment by ExperimentsInHonesty** [comment]
@bilalbg 
Please provide update
1. Progress: "What is the current status of your project? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"
5. Pictures or links* (if necessary): "Add any pictures or links that will help illustrate what you are working on."

* remember to add links to the top of the issue if they are going to be needed again.

**Comment by bilalbg** [comment]
1. Everything is done, just resolving merge conflicts
2. None now, there were some icons no in the slides/figma previously but I discussed and cleared those up with design
3. I have at least a few hours today and more over the weekend
4. I should have a PR pretty soon, the issue should be done today if everything is fine
