### ISSUE TITLE
Insert a new row on Page 5 showing the project status on pdf and website

### ISSUE THREAD

**Issue by Parisajf** [hackforla/tdm-calculator#1764]
### Overview
We need a new line at the very bottom of my project- page 5 showing the status on both PDF and website.

### Action Items
- [x] Insert a new line on website in my project- page 5 under Date last saved showing the status with this format: 
        **Status**: Draft or **Status**: Snapshot or **Status**: Shared Snapshot and the same font and color as two above rows.

- [x] Insert a new line on pdf in my project- page 5 under Date last saved showing the status with this format: 
        **Status**: Draft or **Status**: Snapshot or **Status**: Shared Snapshot and the same font and color as two 

### Resources/Instructions
[TDM calculator My Projects: Page 5](https://tdm-dev.azurewebsites.net/calculation/5/0)

![Screen Shot 2024-06-26 at 8 23 51 PM](https://github.com/hackforla/tdm-calculator/assets/134427433/a17572e4-5c36-46ad-976e-2f48d89b4b99)

**Comment by entrotech** [comment]
Completed in PR #1769 for both PDF Download and Project Summary Page
