### ISSUE TITLE
"Snapshot  submitted" should not appear on pdf if snap shot is not submitted

### ISSUE THREAD

**Issue by Parisajf** [hackforla/tdm-calculator#1765]
### Overview
On my project page, page 5 pdf "**Snapshot submitted**" should not appear on pdf if snap shot is not submitted.

### Action Items

- [ ] Change the pdf on my project page Not to show "**Snapshot submitted**"  if snap shot is not submitted.

### Resources/Instructions
![Screen Shot 2024-06-26 at 8 05 21 PM](https://github.com/hackforla/tdm-calculator/assets/134427433/7ae80633-2bd8-4f11-8550-8e4b277aeda7)

**Comment by entrotech** [comment]
- Fixed under Issue #1759 and PR #1769
