### ISSUE TITLE
Remove the old code of assigning the new issue to the project

### ISSUE THREAD

**Issue by Parisajf** [hackforla/tdm-calculator#1767]
### Overview
Remove the old code to assign the new issue to the project, as we moved to the new board it's happening automatically and we just receive failure issue

### Action Items
Remove the flow code that is assigning the new issue to the project from the repository. find the code in the resources below.

### Resources/Instructions
https://github.com/hackforla/tdm-calculator/blob/develop/.github/workflows/new-issue-create-card.yml

**Comment by entrotech** [comment]
What ParIsa is talking about is the GitHub Action that automatically assigns any new issue to the project board.
