### ISSUE TITLE
Design: Create Style Guide Presentation (Buttons/Pagination)

### ISSUE THREAD

**Issue by marlenamellody** [hackforla/tdm-calculator#1768]
### Overview
We need to create a Google deck of all the style guide pages on Figma and add a link to the wiki

### Action Items

- [x]  Finalize this section for design system
- [x] Update style guide presentation
- [x] Update Button Styles  and Use Cases - refer to [comment](https://github.com/hackforla/tdm-calculator/issues/1365#issuecomment-2183154499)

### Resources/Instructions
[Style Guide Presentation](https://docs.google.com/presentation/d/1I4q35NL2WW2RpksIyawhHCd8qJnrjme1ZDNIBxu24hQ/edit#slide=id.g2a6d1bfeb46_0_103)
[Figma](https://www.figma.com/design/nD9QK56Mzq7xNSaSUoeGx0/TDM-Calculator?node-id=12962-4606&t=Zm14H9JP8NWc3314-4)

**Comment by marlenamellody** [comment]
Updates on the buttons in the design system and style guide presentation: 

**original design system:** 

- doesn't include tertiary style (green stroke - present on page 5)
- focus/hover buttons have a red stroke 

![Image](https://github.com/user-attachments/assets/8c9e5671-c479-4eb8-8d55-ef42401f6285)

**updated design system:**

- includes tertiary style (The use of the tertiary button - example: “print summary” (when it has a green outline), is for when there are two positive buttons on the same page, the outlined version is less important option.)


![Image](https://github.com/user-attachments/assets/589a1d3e-a61b-4a73-a3bc-080bc15eef85)

**blockers**

- Because a default/ disabled state of the tertiary style isn't present on the site, should it be included in the design system?

**Comment by marlenamellody** [comment]
Updated buttons: 
![button type](https://github.com/user-attachments/assets/27801d01-38f5-4f36-88a7-42f997ad309f)

Button style with icons removed based on feedback.

**Comment by NilakshiS** [comment]
Added a slide for difference between Hover and Default state buttons, waiting on stakeholder feedback
![Image](https://github.com/user-attachments/assets/ae12d842-2bf3-4c50-8c2d-d56716d6fecf)

**Comment by NilakshiS** [comment]
Updated slides on style guide to have more explanation
![Image](https://github.com/user-attachments/assets/e0599a02-467a-40af-a5d7-678d9d238eaf)

![Image](https://github.com/user-attachments/assets/e7d063a5-d6c9-4f43-818a-d6991fca68f6)

**Comment by NilakshiS** [comment]
Approved by the stakeholders on 10/15/2024.

**Comment by NilakshiS** [comment]
Creating a design for "CANCEL" button and trying to find a button style that fits "CLEAR ALL FILTERS" button, we realized that the current button styles in the design system do not work well with what we have on the website:
 
- Secondary button styles are not used anywhere on the website, except for the incorrect usage on "EDIT FAQS" button.
- "CANCEL" buttons should use secondary button style, but the gray background might make them look disabled.
- "CLEAR ALL FILTERS" should use tertiary style, but it does not look visually appealing without a primary button next to it.
- Accent button styles are not used anywhere on the website.

We suggest alternate "secondary" and "tertiary" button styles and refined type descriptions to better align with our use case.
![Image](https://github.com/user-attachments/assets/07ef9469-7a1e-4fa5-812e-3d535fcd444a)

**Comment by marlenamellody** [comment]
Warning button type will have white text instead of black text for increased accessibility. Approved by the stakeholders on 10/29/2024. 


<img width="464" alt="Screen Shot 2024-10-29 at 6 46 27 PM" src="https://github.com/user-attachments/assets/a7d36e18-8a66-44a4-9124-bf97e0358920">
