### ISSUE TITLE
Decide if we want to keep the single-page view of a Project calculation

### ISSUE THREAD

**Issue by entrotech** [hackforla/tdm-calculator#178]
I believe the single-page view should be dropped. The wizard is really much nicer and does show almost all the information about the project on the Review page.

**Comment by ExperimentsInHonesty** [comment]
Stakeholder meeting 1/9/2020
decision was made to keep for now.

**Comment by KPHowley** [comment]
Brought up again on 4/28, we are keeping and updating the design.
