### ISSUE TITLE
Add Sorting and Filtering to the the Projects Page

### ISSUE THREAD

**Issue by entrotech** [hackforla/tdm-calculator#179]
The existing Project component had a crude UI and just lists all the projects in the database. Before the app goes to production, it will need to:

- [x] - Based on the user's id, always filter to only show their own projects, if they are not an admin.
- [x] - Allow viewing all projects if they have the admin role (when we implement a submission process, we may restrict the admin to only seeing other users' projects if they have been "submitted").
- [x] - Allow specifying a sort criteria (by created date, modified date, name, user)
- [x] - Allow filtering by created date, modified date, partial name and maybe other criteria, like building permit #, etc.
- [x] - Work on the appearance of the list based on Issue #182

**Comment by KPHowley** [comment]
made comments about the styling for this in #182

**Comment by ExperimentsInHonesty** [comment]
@nicholaspung we had roll back your pull request.  Please attach a screen shot of the page here, so we can discuss additional tweaks before roll out

**Comment by ExperimentsInHonesty** [comment]
if no answer by next week, put this issue, back into the prioritized backlog for reassignment.

**Comment by nicholaspung** [comment]
Here's what it looks like. 
![image](https://user-images.githubusercontent.com/22228236/74090559-9fb5db00-4a61-11ea-943c-261bbe4ca511.png)

If you still want this component, checkout branch `nicholas-pung` to take the code, as I will be moving out of state.

**Comment by ExperimentsInHonesty** [comment]
@natjng please let us know your progress
1. Progress
2. Blocks if any
3. Availability
4. ETA

**Comment by natjng** [comment]
@ExperimentsInHonesty Hi Bonnie, I'll be working on this during the weekend and will be there on Tuesday!

**Comment by ExperimentsInHonesty** [comment]
@natjng hi.  Can you give us an update on this.  Hope you are ok!
1. Progress
2. Blocks
3. Availability
4. ETA
