### ISSUE TITLE
Updates to Feedback page required fields 

### ISSUE THREAD

**Issue by Parisajf** [hackforla/tdm-calculator#1796]
### Overview
We need to update the feedback page so that the field boxes for Name and comment shows they are required before the user clicks on them

### Action Items
Add the word "required" in gray inside the field box for:
Name
Comment

### Resources/Instructions
https://tdm-dev.azurewebsites.net/feedback

**Comment by ExperimentsInHonesty** [comment]
Appeared in the [2024-11-12 Stakeholder deck](https://docs.google.com/presentation/d/1Urb8pV-P-05586u2c59nEjmUeWa_3s4kJUETi8lllOw/edit#slide=id.g315a9f4f3f2_4_0) and was approved.
