### ISSUE TITLE
Develop Layout wireframes for webapp

### ISSUE THREAD

**Issue by entrotech** [hackforla/tdm-calculator#18]
This is a UI/UX issue to come up with a wireframe for how the calculation should look. It must adhere to LADOT and LA City style guides, but otherwise use contemporary design themes.

**Comment by nekobox** [comment]
Hi-fidelity Screens: https://www.figma.com/file/qNgPc5lttpf0SWSwkbbWyT/TDM-Calculator?node-id=0%3A1

**Comment by ExperimentsInHonesty** [comment]
Kevin, leo, nicole to have a conversation about rosemary's view

**Comment by KPHowley** [comment]
Notes from meeting with rosemary about UI: https://docs.google.com/document/d/1F6OLS8P7en9B6EipiV3diRQ6MupBhP0E3rqLWK_P1iE/edit?usp=sharing

**Comment by ExperimentsInHonesty** [comment]
@nekobox 
Here is a link to the document where I am putting all the [logged in examples](https://docs.google.com/document/d/1Eyzfqq32lt-9ExWBgw8roRooq00Oi3by6adfKYIE2jo/edit#) I could find, where the website doesn't display your picture once you have logged in.  
please update the figma with whichever style you think is appropriate.

**Comment by ExperimentsInHonesty** [comment]
snipits from slack
@entrotech on 12/31/19
In your [@nekobox] mock-up you have Points Earned and Measure Points as separate displays, but they are the same thing.  The other top-level information that could appear on the left panel might be some combination of required and provided parking spaces, and the project level. Should solicit Rosemary McCarron opinion.

**Comment by ExperimentsInHonesty** [comment]
snipits from slack
@entrotech on 12/31/19
@Nicole Doan if you want me to use the background image with the hard hats, and it is public domain, can you put the image somewhere I can get to it?

@nekobox uploaded the following image
![hard-hats-silvia-brazzoduro](https://user-images.githubusercontent.com/37763229/71700049-59d96900-2d77-11ea-8a75-768619916cfc.png)
