### ISSUE TITLE
Wizard Strategies Page: Add Uncheck All feature

### ISSUE THREAD

**Issue by entrotech** [hackforla/tdm-calculator#180]

**Comment by KPHowley** [comment]
@bfojas @ExperimentsInHonesty  This would be my suggestion for adding the box for now, just to keep it in line with the other buttons we have:
![Uncheck Box](https://user-images.githubusercontent.com/49739276/73141522-c1629b80-4039-11ea-8f22-41d209138855.png)

If the other buttons aren't applicable/visible then I'd just keep it centered, and I would use the same button format for #181 as well
