### ISSUE TITLE
Wizard Project Parameters Page: Add Uncheck All feature

### ISSUE THREAD

**Issue by entrotech** [hackforla/tdm-calculator#181]
The goal is to have a feature on this page that allows a user to reset all the inputs on this page to their default values to "reset" the inputs.

- [ ] Agree on how the UI should work
- [x] Implement the feature in code - changing multiple formInputs will need to be an event that bubbles up from the page component to the top-level container.

**Comment by bfojas** [comment]
@KPHowley @ExperimentsInHonesty @nekobox 

Do we have any specific way that the uncheck all option should appear on the page (button appearance and placement)?
