### ISSUE TITLE
Reformat Projects Page

### ISSUE THREAD

**Issue by entrotech** [hackforla/tdm-calculator#182]
There is a very basic Project Page. Come up with a more attractive design for the page. Consider the functionality roughly outlined in the companion development issue #179

**Comment by ExperimentsInHonesty** [comment]
Decided by Bonnie, Kevin, Bradley, Rance and other people from a prior meeting (including John)

Remove description and add version number in its place
Change Date Entered to Created On
Change Date Modified to Last Modified

Created On   | Last Modified
01/08/2020   | 01/14/2020
1/10/2020      | 12:55 PM

Divide display into 
Your Projects

Other Projects

**Comment by KPHowley** [comment]
![A12 Projects](https://user-images.githubusercontent.com/49739276/73142127-2c16d580-4040-11ea-9ad6-04231cfba6bb.png)
@ExperimentsInHonesty @nicholaspung
