### ISSUE TITLE
EPIC: UI changes in infoboxes to match the style guide

### ISSUE THREAD

**Issue by NilakshiS** [hackforla/tdm-calculator#1820]
### Overview
Some of the infoboxes on the website need changes in color and typography to match the prescribed style in the existing design system. 

### Action Items

- [x] #1822
- [x] #1823
- [x] #1824
- [x] #1825 
- [x] #1826
- [x] #1827
### Resources/Instructions

[Link to typography in the Style Guide](https://docs.google.com/presentation/d/1I4q35NL2WW2RpksIyawhHCd8qJnrjme1ZDNIBxu24hQ/edit#slide=id.g2e724fd73fd_0_15)
[Link to Color Palette in the Style Guide](https://docs.google.com/presentation/d/1I4q35NL2WW2RpksIyawhHCd8qJnrjme1ZDNIBxu24hQ/edit#slide=id.g2e134a56948_3_13)
[Link to infoboxes in the Style Guide for more information](https://docs.google.com/presentation/d/1I4q35NL2WW2RpksIyawhHCd8qJnrjme1ZDNIBxu24hQ/edit#slide=id.g2f74a24ec8f_0_8)

**Comment by ExperimentsInHonesty** [comment]
@NilakshiS
On the issues you created, 
- https://github.com/hackforla/tdm-calculator/issues/1822
-  https://github.com/hackforla/tdm-calculator/issues/1823
-  https://github.com/hackforla/tdm-calculator/issues/1824
-  https://github.com/hackforla/tdm-calculator/issues/1825
-  https://github.com/hackforla/tdm-calculator/issues/1826
-  https://github.com/hackforla/tdm-calculator/issues/1827

The Next steps are:
- if you are ready to have this prioritized, please add the ready for prioritization label.
- If you are still working on the issue drafts, add the draft label
- If you have a question for product or dev or research, use the ready for dev lead, ready for product ready for research lead labels

**Comment by NilakshiS** [comment]
@ExperimentsInHonesty @entrotech I've added the https://github.com/hackforla/tdm-calculator/labels/ready%20for%20dev%20lead label. I need help in determining the level and size for these issues as well as a review of the content in case they are missing any details.

**Comment by amiteshsrivastava11** [comment]
@NilakshiS It looks like the EPIC is ready to be closed. Do you agree? If yes, close the issue.
