### ISSUE TITLE
Color and typography changes to level 0 warning infobox

### ISSUE THREAD

**Issue by NilakshiS** [hackforla/tdm-calculator#1822]
### Overview
The level 0 warning infobox on page 3 uses a different font style and background color than what's used in the current Design System, change the font styling and background color to match the style guide.

### Action Items
- [x] Change the background color from `#FEF4F2` to "Error Background (`#F9DFDA`)".
- [x] Change the H1 heading font style to "Heading 1" style of the style guide.

#### Steps to reproduce this infobox

1. Login to the [dev site](https://tdm-dev.azurewebsites.net/login).
2. Go to "Create Project" page.
3. Enter some values for the required fields "Project Name", "Address" and "AIN" on Page 1.
4. Click the forward button to go to the next page.
5. Without filling any details on Page 2, click the forward button to go to the next page.
6. Page 3 should be displayed with the Level 0 Warning box.
<details><summary>Image for current Level 0 warning box</summary>
  
  ![image](https://github.com/user-attachments/assets/7c62d854-4da2-4b13-b0fb-990c1f524619)
  
  </details>

[Link to typography in the Style Guide](https://docs.google.com/presentation/d/1I4q35NL2WW2RpksIyawhHCd8qJnrjme1ZDNIBxu24hQ/edit#slide=id.g2e724fd73fd_0_15)
[Link to Color Palette in the Style Guide](https://docs.google.com/presentation/d/1I4q35NL2WW2RpksIyawhHCd8qJnrjme1ZDNIBxu24hQ/edit#slide=id.g2e134a56948_3_13)
[Link to infoboxes in the Style Guide for more information](https://docs.google.com/presentation/d/1I4q35NL2WW2RpksIyawhHCd8qJnrjme1ZDNIBxu24hQ/edit#slide=id.g2f74a24ec8f_0_8)

**Comment by ExperimentsInHonesty** [comment]
@NilakshiS
if you are ready to have this prioritized, please add the ready for prioritization label.
If you are still working on this issue draft, add the draft label
If you have a question for product or dev or research, use the ready for dev lead, ready for product ready for research lead labels

**Comment by ExperimentsInHonesty** [comment]
Appeared in the [2024-11-12 Stakeholder deck](https://docs.google.com/presentation/d/1Urb8pV-P-05586u2c59nEjmUeWa_3s4kJUETi8lllOw/edit#slide=id.g315a9f4f3f2_4_63) and was NOT APPROVED

"Decision: Release to Production? NO, fix accessibility first (font size different, informational box)"
