### ISSUE TITLE
Background color and spacing changes to Guide Infobox

### ISSUE THREAD

**Issue by NilakshiS** [hackforla/tdm-calculator#1823]
### Overview
The guide infobox on Page 1 uses a different background color than what's used in the current Design System, change the background color to match the style guide. Also add a bottom padding for consistency.

### Action Items
- [x] Change the background color to "Light Gray (`#EEF1F4`)".
- [x] Add a bottom padding equal to top padding.

#### Steps to reproduce this infobox

1. Login to the [dev site](https://tdm-dev.azurewebsites.net/login).
2. Go to "Create Project" page.
3. The guide infobox should be on the bottom left of the page above the footer.
  <details><summary>Image for current Guide infobox</summary>
  
  ![image](https://github.com/user-attachments/assets/75424075-b81a-4c21-8747-82694e4b1489)
  
  </details>

[Link to Color Palette in the Style Guide](https://docs.google.com/presentation/d/1I4q35NL2WW2RpksIyawhHCd8qJnrjme1ZDNIBxu24hQ/edit#slide=id.g2e134a56948_3_13)
[Link to infoboxes in the Style Guide for more information](https://docs.google.com/presentation/d/1I4q35NL2WW2RpksIyawhHCd8qJnrjme1ZDNIBxu24hQ/edit#slide=id.g2f74a24ec8f_0_8)

**Comment by ExperimentsInHonesty** [comment]
@NilakshiS
if you are ready to have this prioritized, please add the ready for prioritization label.
If you are still working on this issue draft, add the draft label
If you have a question for product or dev or research, use the ready for dev lead, ready for product ready for research lead labels
