### ISSUE TITLE
Typography changes to target points infobox

### ISSUE THREAD

**Issue by NilakshiS** [hackforla/tdm-calculator#1824]
### Overview
The target points infobox on Page 3 uses a different font style than what's used in the current Design System, change the font styling to match the style guide.

### Action Items

- [ ] Change the font to "Paragraph" style for all the infoboxes.

#### Steps to reproduce this infobox

1. Login to the [dev site](https://tdm-dev.azurewebsites.net/login).
2. Go to "Create Project" page.
3. Enter some values for the required fields "Project Name", "Address" and "AIN" on Page 1.
4. Click the forward button to go to the next page.
5. Put the following values on Page 2:
   1. "Condominium Units": 1000
   2. "..... Enter Parking Spaces req'd": 1000
6. Click the forward button to go to the next page.
7. On Page 3 enter the value '50' for "Parking Provided"
8. You should see the target points infobox in the panel on the left.
 <details><summary>Image for current Reduced Parking infobox</summary>
  
  ![image](https://github.com/user-attachments/assets/68f807a6-4cb5-4887-8d69-12a893647e6a)
  
  </details>

[Link to typography in the Style Guide](https://docs.google.com/presentation/d/1I4q35NL2WW2RpksIyawhHCd8qJnrjme1ZDNIBxu24hQ/edit#slide=id.g2e724fd73fd_0_15)
[Link to infoboxes in the Style Guide for more information](https://docs.google.com/presentation/d/1I4q35NL2WW2RpksIyawhHCd8qJnrjme1ZDNIBxu24hQ/edit#slide=id.g2fb650933c5_0_0)

**Comment by ExperimentsInHonesty** [comment]
@NilakshiS
if you are ready to have this prioritized, please add the ready for prioritization label.
If you are still working on this issue draft, add the draft label
If you have a question for product or dev or research, use the ready for dev lead, ready for product ready for research lead labels
