### ISSUE TITLE
Typography style changes to info box page 5

### ISSUE THREAD

**Issue by NilakshiS** [hackforla/tdm-calculator#1826]
### Overview
The notification for successfully earned target points on Page 5 uses a different font style than what's used in the current Design System, change the font styling to match the style guide.

### Action Items
- [x] Remove the drop shadow from the text.
- [x] Change the font to "Subheading" style in the style guide.

#### Steps to reproduce this infobox

1. Login to the [dev site](https://tdm-dev.azurewebsites.net/login).
2. Go to "Create Project" page.
3. Enter some values for the required fields "Project Name", "Address" and "AIN" on Page 1.
4. Click the forward button to go to the next page.
5. Put the following values on Page 2:
   1. "Condominium Units": 1000
   2. "..... Enter Parking Spaces req'd": 1000
6. Click the forward button to go to the next page.
7. On Page 3 enter the value '50' for "Parking Provided"
8. Click the forward button to go to the next page.
9. On Page 4, select "100% Affordable" in the affordable housing selection.
10. Click the forward button to go to the next page.
11. On Page 5, you should see the successfully earned target points on top.
 <details><summary>Image for current successfully earned target points infobox</summary>
  
   ![image](https://github.com/user-attachments/assets/dbd19b1c-270e-4420-b6b3-0b23c0a82999)
  
  </details>

[Link to typography in the Style Guide](https://docs.google.com/presentation/d/1I4q35NL2WW2RpksIyawhHCd8qJnrjme1ZDNIBxu24hQ/edit#slide=id.g2e724fd73fd_0_15)
[Link to infoboxes in the Style Guide for more information](https://docs.google.com/presentation/d/1I4q35NL2WW2RpksIyawhHCd8qJnrjme1ZDNIBxu24hQ/edit#slide=id.g2f74a24ec8f_0_21)

**Comment by ExperimentsInHonesty** [comment]
@NilakshiS
Remove the ready for design lead, then:
- if you are ready to have this prioritized, please add the ready for prioritization label.
- If you are still working on this issue draft, add the draft label
- If you have a question for product or dev or research, use the ready for dev lead, ready for product ready for research lead labels
