### ISSUE TITLE
Color and typography style changes to target points not reached notification

### ISSUE THREAD

**Issue by NilakshiS** [hackforla/tdm-calculator#1827]
### Overview
The notification for target points not reached on Page 5 uses a different font style and icon color than what's used in the current Design System, change the font styling and icon color to match the style guide.

### Action Items
- [x] Remove the line break to align the text to a single line.
- [x] Remove the drop shadow from the text.
- [x] Change the font to "Subheading" style in the style guide.
- [x] Change warning icon color to "Warning (`#E87D00`)".

#### Steps to reproduce this infobox

1. Login to the [dev site](https://tdm-dev.azurewebsites.net/login).
2. Go to "Create Project" page.
3. Enter some values for the required fields "Project Name", "Address" and "AIN" on Page 1.
4. Click the forward button to go to the next page.
5. Put the following values on Page 2:
   1. "Condominium Units": 1000
   2. "..... Enter Parking Spaces req'd": 1000
6. Click the forward button to go to the next page.
7. On Page 3 enter the value '50' for "Parking Provided"
8. Click the forward button to go to the next page.
9. Do not select anything on Page 4 and click the forward button to go to the next page.
10. On Page 5, you should see the  target points not reached on top.
 <details><summary>Image for current target points not reached infobox</summary>
  
  ![image](https://github.com/user-attachments/assets/0dc05605-bc26-4eba-b189-8338dc08e6fa)
  
  </details>

[Link to Typography in the Style Guide](https://docs.google.com/presentation/d/1I4q35NL2WW2RpksIyawhHCd8qJnrjme1ZDNIBxu24hQ/edit#slide=id.g2e724fd73fd_0_15)
[Link to Color Palette in the Style Guide](https://docs.google.com/presentation/d/1I4q35NL2WW2RpksIyawhHCd8qJnrjme1ZDNIBxu24hQ/edit#slide=id.g2e134a56948_3_13)
[Link to Infoboxes in the Style Guide for more information](https://docs.google.com/presentation/d/1I4q35NL2WW2RpksIyawhHCd8qJnrjme1ZDNIBxu24hQ/edit#slide=id.g2f74a24ec8f_0_21)

**Comment by ExperimentsInHonesty** [comment]
@NilakshiS 
if you are ready to have this prioritized, please add the `ready for prioritization` label.  
If you are still working on this issue draft, add the `draft label`
If you have a question for product or dev or research, use the `ready for dev lead`, `ready for product` `ready for research labels
