### ISSUE TITLE
Design a way to see what filters have been chosen

### ISSUE THREAD

**Issue by NilakshiS** [hackforla/tdm-calculator#1829]
### Overview
As a user, I want to be able to see what filters and sorting I have chosen and what filters / sorting are selected by default so I understand my results better.

### Details
If you have all the popups closed, there is no indication of which, if any, filters are applied and no indication of any applied sorting.
<details><summary>Screenshots of TDM dev to illustrate the issue</summary>

I chose this filter

<img src="https://github.com/user-attachments/assets/e2a0cc48-1f14-443b-a5b4-92d22df85283" width=200px>

And then after I applied, it was not possible to see that I had used the filter

![image](https://github.com/user-attachments/assets/76b8636f-f4bd-49f7-a2da-6ceab4695d43)

</details> 

### Action Items
- [x]  Compare the current designs (in figma), to see if there was something that did not get developed and needs to be sent again to dev.
- [ ] If there is no design already, create one and update the Figma Designs and Prototype.
  - [ ]  Also decide on icons for the design: #1837 
- [ ] Review with Product, Dev and Research and iterate if needed based on feedback.
- [ ] Update the style guide to add the new design.
- [ ] Once finalized, get Stakeholder sign-off via the stakeholder meeting slide deck.

### Resources
<details><summary>An example of how Google Sheets indicates selected filters</summary>

![image](https://github.com/user-attachments/assets/ca25d7a2-e287-4f74-aaba-95b3845ece76)

</details> 

- [Link to "My Projects" page](https://tdm-dev.azurewebsites.net/projects)
- Design Issue #1578
- [Link to Figma file](https://www.figma.com/design/nD9QK56Mzq7xNSaSUoeGx0/TDM-Calculator?node-id=11866-11910&t=T72RYUQU9k6TOA9W-1)
- [Link to the Figma Prototype for filtering UI](https://www.figma.com/proto/nD9QK56Mzq7xNSaSUoeGx0/TDM-Calculator?type=design&node-id=12173-2052&t=wQuxLI1JbOw0OzLn-1&scaling=scale-down&page-id=2499%3A11472&starting-point-node-id=11997%3A885)

**Comment by lbeatonn** [comment]
I did not see a design solution for this in the Figma file so I checked the first action item " Compare the current designs (in figma), to see if there was something that did not get developed and needs to be sent again to dev."

**Comment by lbeatonn** [comment]
![Screenshot 2024-09-18 at 5 12 10 PM](https://github.com/user-attachments/assets/1782fa75-1d36-4213-b546-5928ede3b12f)
Update: Iteration #1 shows the filter tags front facing, awaiting feedback from team

**Comment by NilakshiS** [comment]
Feedback received in the Stakeholder Prep meeting (09/19/24):

This list would get too long if multiple addresses are selected.

**Comment by lbeatonn** [comment]
UPDATE - Sept 25th

Bonnie FEEDBACK Sept 20th - Bonnie said the list would get too long if 10 addresses are selected.

**Iteration #2**

States

[Short List] [Default] (3 or less filters selected)

![#1829 - 09 18 2024 - Iteration #2  Short List   Default](https://github.com/user-attachments/assets/828d1994-917a-4990-8b9d-8fe14714c080)

[Long List] [Default/Collapsed]

![Collapsed](https://github.com/user-attachments/assets/0523126e-d441-456d-b159-d5b2bbf1d41f)

[Long List] [Expanded]

![#1829 - 09 18 2024 - Iteration #2  Long List   Expanded](https://github.com/user-attachments/assets/59bc426b-955e-44da-873b-1244f6a3766a)

**Comment by greenishviolet** [comment]
### 10/08 Progress Update

**Progress**
- I have created four variations of the side drawer where the pills will be stored
- I created a mockup of the My Projects page with the side panel opened
- I am playing around with how users will access the side panel. I have created different variations of the filter button and am experimenting with different places to place it.
- I am working on incorporating mechanisms to clear filters by category with @thetanmancan

**Blockers**
- I noticed that the side drawer does not fill the length of the page on the TDM Dev website. It might be a problem when more than 10 items are on the page.

<details>
<summary>Gif of TDM Dev website</summary>

![Image](https://github.com/user-attachments/assets/0f9c3016-9e8e-440a-9463-9dd41deadfb4)

</details>

- I tried making a mockup, but I am having trouble with adding rows to the table on the Figma file

**Availability**
I can dedicate about 12 hours this week

**ETA**
I am hoping to complete this issue by next week, which might be a bit ambitious

**Pictures**
<details>
<summary>My Projects page with side panel</summary>

![Image](https://github.com/user-attachments/assets/9b665a5d-3b13-4d11-9709-cc5cf23c9ff5)

</details>

<details>
<summary>Side panel variations</summary>

![Image](https://github.com/user-attachments/assets/dafba632-13f9-4f35-81e9-60bb51900449)

</details>

<details>
<summary>Accessing the side panel - filter button next to the search bar</summary>

With the search button

![Image](https://github.com/user-attachments/assets/a4ad788d-a9f9-4c4e-aa49-0ccffd95b376)


Without the search button
![Image](https://github.com/user-attachments/assets/04bb28b0-3fb7-4167-921c-70010e2d7abd)

</details>

<details>
<summary>Accessing the side panel - filter bar below tool bar</summary>

![Image](https://github.com/user-attachments/assets/86a3ef95-1e7a-43d6-9601-4f6aecd041f6)

</details>

**Comment by NilakshiS** [comment]
Feedback from stakeholder meeting on 10/15: We will not have this feature this time but we'll keep these designs for future developments.
