### ISSUE TITLE
Update Project Name/Information page: Version # box, Project description, and required fields

### ISSUE THREAD

**Issue by KPHowley** [hackforla/tdm-calculator#183]
### Overview
Add a version # entry field, and adjust the project description box on the first page of the wizard (the project name/information page). Then mark the project name field as "Required", and the Permit number field as "Required to Submit". 

### Action Items
- [x] add a version # field that has a limited # or characters (7)
- [x] move the project description field to the bottom of the list 
- [x] change project description to text area box
- [x] Add "Required" to Project name field 
- [x] Add "Required to Submit"  to permit # field

**Comment by entrotech** [comment]
For the version # changes,  I separated out "Implement database-driven rule validation for string or textarea input length" as a separate issue.
For the textarea change, I separated out a separate issue to support textarea controls Issue #191, and implemented it already.
The rest of the changes were simple database changes, requiring no coe modification.
