### ISSUE TITLE
Re-Design sort options: change toggle buttons to radio buttons for mutually exclusive options and update style guide

### ISSUE THREAD

**Issue by NilakshiS** [hackforla/tdm-calculator#1834]
### Overview
The toggle buttons currently used in the prototype might confuse users, as they look like you can select multiple options. However, you can only sort in one way at a time. We should either change the design or use radio buttons instead, as the Dev team suggested.

### Details
Each popup has an option to sort by that column. The prototype design uses two toggle buttons that essentially mean "Sort Ascending" or "Sort Descending" (though the labels differ based on the column).
<details><summary>Image of Toggle buttons on "Created On" column by default</summary>

![image](https://github.com/user-attachments/assets/bc01f9f3-df45-4c67-8e74-c6b51dc21cca)

</details> 

<details><summary>Image of Toggle buttons on "Created On" column on Hover</summary>

![image](https://github.com/user-attachments/assets/ea949624-bc88-4689-bb52-40108263c909)

</details> 

Dev team suggests that toggle buttons are not an appropriate choice, since it is not possible to sort ascending and descending simultaneously. A better choice is a set of two radio buttons. This allows the user to select one or the other, but not both. 

<details><summary>A prototype using radio buttons instead of toggle buttons</summary>

![image](https://github.com/user-attachments/assets/660e2563-b73d-47d5-8bff-ec94ea5b3326)

</details> 

Moreover, the data might not be sorted by that column at all, in which case neither radio button is checked when the popup is first opened. If the user then clicks on one of the choices, it will be applied when the Apply button is clicked. They can also choose Reset to not apply sorting by that column.

Dev has already implemented this change (see My Project's page).

### Action Items
- [x] Create a prototype for an alternative design.
- [x] Review with Product, Dev and Research and iterate if needed based on feedback.
- [x] ~~Update the style guide to add the new design.~~
- [x] ~~Once finalized, get Stakeholder sign-off via the stakeholder meeting slide deck.~~
- Will be added to style guide and approved by stakeholders using #1843 

#### Resources
- My Project's page https://tdm-dev.azurewebsites.net/projects
- Design Issue for filters #1578
- [Link to Figma file](https://www.figma.com/design/nD9QK56Mzq7xNSaSUoeGx0/TDM-Calculator?node-id=11866-11910&t=Tjy2GqHLts2dywS1-1) (Refer to designs dated 01/31/2024 and 02/15/2024)
- [Link to the Figma Prototype for filtering UI](https://www.figma.com/proto/nD9QK56Mzq7xNSaSUoeGx0/TDM-Calculator?type=design&node-id=12173-2052&t=wQuxLI1JbOw0OzLn-1&scaling=scale-down&page-id=2499%3A11472&starting-point-node-id=11997%3A885)

**Comment by namigoeku** [comment]
Although I understand Dev's concern regarding the toggles, I believe toggles would provide a more modern UI as they are either on or off and when paired with other features like the checkboxes, offer less cognitive load. I have drafted some ideas. 
![7](https://github.com/user-attachments/assets/34ae986b-19da-4140-bbb4-fc420d383407)
![6](https://github.com/user-attachments/assets/044c2e35-bc0f-49a2-9801-13c3eb050edc)

**Comment by namigoeku** [comment]
Changed the design to include just the radio sort by ascending/descending.
Updated this portion in the Figma prototype (#1578 #1386 )
<img width="588" alt="Screenshot 2024-10-01 at 11 07 46 PM" src="https://github.com/user-attachments/assets/1ef8b829-eb2a-4e6c-be2c-c0323e668ab4">

![image](https://github.com/user-attachments/assets/27d5f6d9-e748-4133-ba6a-814d233c0d86)

**Comment by NilakshiS** [comment]
Added the radio buttons and sort options to the new [prototype](https://www.figma.com/design/nD9QK56Mzq7xNSaSUoeGx0/TDM-Calculator?node-id=14857-36047&t=A0bRLWt5p4KOHWTF-1).
<details><summary>Screenshots of the updated designs from Figma</summary>

![Image](https://github.com/user-attachments/assets/a254a6b8-4261-43e1-a642-f44a36f3a683)
![Image](https://github.com/user-attachments/assets/1c667cc4-a5c4-4947-899b-74844c5d5f19)
![Image](https://github.com/user-attachments/assets/2ec00c60-4cf0-40a9-8655-08be755d777e)
![Image](https://github.com/user-attachments/assets/9cd7f981-31ce-401e-903d-b4939b010bfc)

</details>
