### ISSUE TITLE
Update the design for filters on "Status" on my projects page

### ISSUE THREAD

**Issue by NilakshiS** [hackforla/tdm-calculator#1836]
### Possible Dependency
- #1834 

### Overview
For the filter options on "Status" column remove the "Search By Keyword" option, change the sort options and redesign the selection for filter options.

### Details
<details><summary>The current design of status filters</summary>

[Link to design on Figma](https://www.figma.com/design/nD9QK56Mzq7xNSaSUoeGx0/TDM-Calculator?node-id=12137-2469&t=uJzpHJgqcQNjjtxj-1)

![image](https://github.com/user-attachments/assets/87c5ca4b-611d-4520-b0c0-3e1029dbcbfe)

</details> 

- The status column has only three options for filtering: "Snapshot", "Draft" or "Both". Hence, it is suggested to remove the "Search by Keyword" control, since it is unnecessary and possibly confusing. 
- Consider if we need to change the sorting options, currently the options are "sort A to Z" and "sort Z to A", which might be confusing to the users when the only values in the column are "Snapshot" and "Draft". 
- The selection of "Draft", "Snapshot" and "Draft and Snapshot" choices needs to be redesigned but it seems the dev team's suggestion was designed but changed for some reason. Research the previous designs and determine the best course of action.
  - Dev suggests changing the checkboxes to radio buttons for the "Draft", "Snapshot" and "Draft and Snapshot" choices:
    > The three choices for filtering by status are "Draft", "Snapshot" or "Draft and Snapshot", which would be better represented by a set of three radio buttons with the corresponding labels. Using two checkboxes like the prototype has a problem where unchecking both boxes would filter out all projects and isn't a useful choice, so we can prevent this problem by switching to radio buttons.
   - However the design was changed from Radio buttons to check boxes in the design. 
      [Notes by the designer on 03/21/2024 mentioning the change](https://www.figma.com/design/nD9QK56Mzq7xNSaSUoeGx0/TDM-Calculator?node-id=11866-11910&t=uJzpHJgqcQNjjtxj-1)
      <details><summary>Previous design of status filters</summary>
      
      [Link to previous status filter design on Figma](https://www.figma.com/design/nD9QK56Mzq7xNSaSUoeGx0/TDM-Calculator?node-id=12076-13062&t=uJzpHJgqcQNjjtxj-1)
      
      ![image](https://github.com/user-attachments/assets/2fe517db-c716-46dc-ad9d-8c7657f30832)
      
      </details> 
      <details><summary>Current design of status filters</summary>
      
      [Link to current status filter design on Figma](https://www.figma.com/design/nD9QK56Mzq7xNSaSUoeGx0/TDM-Calculator?node-id=12137-2469&t=uJzpHJgqcQNjjtxj-1)
      
      ![image](https://github.com/user-attachments/assets/87c5ca4b-611d-4520-b0c0-3e1029dbcbfe)
      
      </details>
    

 - Dev team also suggests adding a second set of radio buttons to filter for "Active" and "Deleted" projects instead of a checkbox for "Deleted projects". Redesign the filter for based on the feedback.
    > IMO, we should use a second set of three radio buttons for filtering by Active vs Deleted, with the choices "Active", "Deleted" or "Active and Deleted" instead of a single checkbox, because the prototype design with a single checkbox is ambiguous to users (if the box is unchecked, will you see just the deleted projects or both the active and deleted projects?).

### Action Items
- [x] Create a prototype for the new design:
  - [x] Remove "Search by Keyword".
  - [x] Change Sort options. (for updated sort design refer to #1834 )
  - [x] Redesign selection for "Draft", "Snapshot" and "Draft and Snapshot" choices.
  - [x] Redesign selection for "Active", "Deleted" and "Active and Deleted" choices.
- [x] Review with Product, Dev and Research and iterate if needed based on feedback.
- [ ] Update the style guide to add the new design.
- [ ] Once finalized, get Stakeholder sign-off via the stakeholder meeting slide deck.

#### Resources
- My Project's page https://tdm-dev.azurewebsites.net/projects
- New Filter Designs:
   - Design Issue #1885
   - [Link to new prototype on Figma](https://www.figma.com/design/nD9QK56Mzq7xNSaSUoeGx0/TDM-Calculator?node-id=14857-36047&t=asZQfnZ5cldg15st-1)
  - [Link to interactive prototype](https://www.figma.com/proto/nD9QK56Mzq7xNSaSUoeGx0/TDM-Calculator?page-id=3331%3A11990&node-id=14857-37246&node-type=frame&viewport=6839%2C-4000%2C0.25&t=6BZzZiFUkD2agnPC-1&scaling=min-zoom&content-scaling=fixed&starting-point-node-id=14857%3A37246&show-proto-sidebar=1)
- Old Filter Designs:
   - Design Issue for filters #1578
   - [Link to Figma file](https://www.figma.com/design/nD9QK56Mzq7xNSaSUoeGx0/TDM-Calculator?node-id=11866-11910&t=Tjy2GqHLts2dywS1-1) (Refer to designs dated 01/31/2024 and 02/15/2024)
   - [Link to the Figma Prototype for filtering UI](https://www.figma.com/proto/nD9QK56Mzq7xNSaSUoeGx0/TDM-Calculator?type=design&node-id=12173-2052&t=wQuxLI1JbOw0OzLn-1&scaling=scale-down&page-id=2499%3A11472&starting-point-node-id=11997%3A885)

**Comment by malubongestab** [comment]
Progress: Completed on my end
Availability/duration: 3h30
Blockers: Possible dependency if any changes occur on the design of the My Projects page (issue #1816)

Using the resources added to this issue I mapped out the previous designs of the filter in the Status column to understand what was already done. ![Image](https://github.com/user-attachments/assets/eab81a6a-ceae-450a-a931-59b4a78564b4)

So based on filter re-designs made on issue #1816, I only added the requested changes in the current issue to the latest Status filter design with a couple of variants for my peers to choose from, which I believe would improve user experience by adding simplicity and clarity to an already very information-loaded table. The changes include:

- Removed search by keyword field.
- Changed copy on drafts/snapshots section.
- Reordered layout to follow better UX.
- Changed copy for active/deleted projects section.
- Included option with radio button for active/deleted project section.
[Figma File](https://www.figma.com/design/nD9QK56Mzq7xNSaSUoeGx0/TDM-Calculator?node-id=4919-17246&t=292RPVuyi1ZPB0K2-1)

![Image](https://github.com/user-attachments/assets/8b5af47e-c18a-4c1c-98dd-bd1980259fc8)
**Design decisions for each version:**

> **V1** Kept the design as it was. Just removed the keyword search bar.
> 
> **V2** Moved the sorting section down, since to my knowledge a user will first choose what he wants to see and then select he wants 
> to see first. Plus it makes even more sense especially when he selects the option ”both”.  
> 
> Changed copy from “Drafts and Snapshots” to ”Both”. It was a bit repetitive, stating the obvious and helping make the modal look cluttered.
> 
> Removed copy explaining the action: “Click to show or hide deleted projects". I felt it a bit confusing and adding clutter. So I removed it and added the word ”show” to the copy to help the user understand that this action will also open/show deleted projects. 
> 
> **V3** The Only difference to V2 is the addition of the word ”Also” to the active/deleted section to help eliminate any ambiguity, due to the developer's concerns listed on the issue that ”the prototype design with a single checkbox is ambiguous to users (if the box is unchecked, will you see just the deleted projects or both the active and deleted projects?).”.
> 
> **V4** Just in case developers or stakeholders push for radio buttons all over this filter, here it is.

**Comment by malubongestab** [comment]
Based on feedback from my team lead I changed back the sorting section to the top in all the versions proposed here. This way consistency is kept with the other filter overlays recently designed for the other columns on this table. (view issue #1816)

- Moved the sorting section to the top of the modal.
 ![Image](https://github.com/user-attachments/assets/5eb73732-a77e-40ad-8724-ebc4abd68603)

**Comment by NilakshiS** [comment]
Approved by design. Design suggests version 3.1. Ready for feedback from dev and product.

**Comment by NilakshiS** [comment]
3.1 is approved. Dev will create issue to apply the change.

**Comment by ExperimentsInHonesty** [comment]
@thetanmancan Why is this in the questions column?
