### ISSUE TITLE
Re-Design Filters: select new icons to indicate filter state

### ISSUE THREAD

**Issue by NilakshiS** [hackforla/tdm-calculator#1837]
### Dependency
- [x] Make sure the changes are added to the new prototype in #1885 

### Overview
We need to some icons to visually inform users about which filters are active or selected. But the iconography from previous designs has been replaced by Material UI icons, so new icons are needed to indicate Filter states.

### Details
The previous design for filters uses the following default and hover icons for the Filter.
![image](https://github.com/user-attachments/assets/8eec29c7-880c-4aad-96e2-10964feec6df) ![image](https://github.com/user-attachments/assets/2e206042-7dda-4326-be13-3266220159ab)

However the old icons have been replaced by Material UI icons and the style guide currently uses the [MdFilterAlt icon](https://mui.com/material-ui/material-icons/?query=filter&selected=FilterAlt) 
![image](https://github.com/user-attachments/assets/e867d565-0f8d-4ab6-8ca2-e8cfdf82a997)

From Material UI icons, select appropriate icons for the different possible states of the filter:
- Default icon state (Filter/Sorting not yet applied)
- Hover icon state
- Filter Active icon state(Filter/Sorting applied)

Here are some suggestions for icons to use:
- From Dev:
  > We might also need an icon to indicate that a filter is not applied to the column - Maybe MdFilterAltOff? 
  - [FilterAltOff](https://mui.com/material-ui/material-icons/?query=filter&selected=FilterAltOff)
  - ![image](https://github.com/user-attachments/assets/95acd9d3-2869-4549-a6cf-a73e014a0210)
- From Product:
  > Product thinks it should use [filled](https://mui.com/material-ui/material-icons/?query=filter&selected=FilterAlt) and [unfilled](https://mui.com/material-ui/material-icons/?query=filter&theme=Outlined&selected=FilterAltOutlined)
   - ![image](https://github.com/user-attachments/assets/322524db-1080-472d-b4c1-ef1e1a3d5b0e)
 

### Action Items
- [x] Select an icon for each of the following states, add more if needed:
  - [x] Default icon state (Filter/Sorting not yet applied)
  - [x] Hover icon state
  - [x] Filter Active icon state(Filter/Sorting applied)
- [x] Update the Figma Designs and Prototype to use the new icons.
- [x] Review with Product, Dev and Research and iterate if needed based on feedback.
- [ ] Update the style guide to add the new design.
- [x] Once finalized, get Stakeholder sign-off via the stakeholder meeting slide deck.

#### Resources
- [List of Material UI Icons](https://react-icons.github.io/react-icons/icons/md/)
- [An example of how filters are displayed in Google Sheets](https://github.com/hackforla/tdm-calculator/issues/1816#issuecomment-2332553148)
- My Projects page https://tdm-dev.azurewebsites.net/projects
- Design Issue for filters #1578
- [Link to Figma file](https://www.figma.com/design/nD9QK56Mzq7xNSaSUoeGx0/TDM-Calculator?node-id=11866-11910&t=Tjy2GqHLts2dywS1-1)
- [Link to the Figma Prototype for filtering UI](https://www.figma.com/proto/nD9QK56Mzq7xNSaSUoeGx0/TDM-Calculator?type=design&node-id=12173-2052&t=wQuxLI1JbOw0OzLn-1&scaling=scale-down&page-id=2499%3A11472&starting-point-node-id=11997%3A885)

**Comment by marlenamellody** [comment]
In the current design of the "my projects" page, the filter icon has been replaced by Material UI icons and there's no visual change to indicate filter states when a filter is added or selected:

![current my projects](https://github.com/user-attachments/assets/9a850171-7ae9-4975-9308-5909fc59a152)

Suggestion: 
After reviewing options with the design team, we decided to use filled/unfilled versions of the same [icon](https://fonts.google.com/icons?selected=Material+Symbols+Outlined:filter_alt:FILL@0;wght@400;GRAD@0;opsz@24&icon.query=filter&icon.size=24&icon.color=%23000000) to represent possible states of the filter.  
![filter suggestion](https://github.com/user-attachments/assets/3a8e319e-8650-4eea-8386-6692ef749e0d)

Default State (unfilled filter icon): Filter/Sorting not applied: [Filter Alt Unfilled](https://fonts.google.com/icons?selected=Material+Symbols+Outlined:filter_alt:FILL@0;wght@400;GRAD@0;opsz@24&icon.query=filter&icon.size=24&icon.color=%23000000)

Hover State (unfilled filter icon with background color): positioning cursor over icon without selecting it: 
![hover icon](https://github.com/user-attachments/assets/1b14d850-5d68-422b-92aa-15b0c345b00e)



Active Icon State (filled filter icon) : Filter/Sorting applied: [Filter Alt](https://fonts.google.com/icons?selected=Material+Symbols+Outlined:filter_alt:FILL@1;wght@400;GRAD@0;opsz@24&icon.query=filter&icon.size=24&icon.color=%23000000)

Blocker: need to determine background color for hover state icon

**Comment by NilakshiS** [comment]
Feedback received in the Stakeholder Prep meeting (09/19/24):
 
Provide icons with suitable foreground and background colors to fit the dark blue background of the table headers on the dev site.

Suggestions for hover state background color (examples from Google Sheets when column background color is set to #002E6D ): 
- an unfilled icon with light background (Hover icon state):
![image](https://github.com/user-attachments/assets/f9a2fce5-b5ce-49b3-b797-cdc09955fc61)
- filled icon with light color (Active icon state):
![image](https://github.com/user-attachments/assets/2b5608fa-4bba-4a6a-b81a-c7eaef820f48)

**Comment by marlenamellody** [comment]
Progress: Identified icons and suitable foreground and background colors to fit the dark blue background of the table headers. 
![Image](https://github.com/user-attachments/assets/ddc23918-6568-47c3-a41a-c5cd5c0a7fb2)

Default State (unfilled filter icon): Filter/Sorting not applied: [Filter Alt Unfilled](https://fonts.google.com/icons?selected=Material+Symbols+Outlined:filter_alt:FILL@0;wght@400;GRAD@0;opsz@24&icon.query=filter&icon.size=24&icon.color=%23000000): #F9FAFB

Hover State (unfilled filter icon with background color): positioning cursor over icon without selecting it: [Filter Alt Unfilled](https://fonts.google.com/icons?selected=Material+Symbols+Outlined:filter_alt:FILL@0;wght@400;GRAD@0;opsz@24&icon.query=filter&icon.size=24&icon.color=%23000000)
icon color : #002E6D with background color: #F9FAFB with corner radius 2.

Active Icon State (filled filter icon) : Filter/Sorting applied: [Filter Alt](https://fonts.google.com/icons?selected=Material+Symbols+Outlined:filter_alt:FILL@1;wght@400;GRAD@0;opsz@24&icon.query=filter&icon.size=24&icon.color=%23000000) #F9FAFB

[Figma Prototype](https://www.figma.com/proto/nD9QK56Mzq7xNSaSUoeGx0/TDM-Calculator?page-id=3331%3A11990&node-id=14722-24288&node-type=frame&viewport=30498%2C-20318%2C1.5&t=xQAaGaXfBF72xVwe-1&scaling=min-zoom&content-scaling=fixed&starting-point-node-id=14722%3A24282&show-proto-sidebar=1)

**Comment by NilakshiS** [comment]
Approved by stakeholders:

Default State (unfilled filter icon): Filter/Sorting not applied: [Filter Alt Unfilled](https://fonts.google.com/icons?selected=Material+Symbols+Outlined:filter_alt:FILL@0;wght@400;GRAD@0;opsz@24&icon.query=filter&icon.size=24&icon.color=%23000000): `#FFFFFF`

Hover State (unfilled filter icon with background color): positioning cursor over icon without selecting it: [Filter Alt Unfilled](https://fonts.google.com/icons?selected=Material+Symbols+Outlined:filter_alt:FILL@0;wght@400;GRAD@0;opsz@24&icon.query=filter&icon.size=24&icon.color=%23000000)
icon color : `#002E6D` (Navy Blue - Primary) with background color: `#FFFFFF` with corner radius 2.

Active Icon State (filled filter icon) : Filter/Sorting applied: [Filter Alt](https://fonts.google.com/icons?selected=Material+Symbols+Outlined:filter_alt:FILL@1;wght@400;GRAD@0;opsz@24&icon.query=filter&icon.size=24&icon.color=%23000000) `#FFFFFF`

**Comment by NilakshiS** [comment]
Added the icons to the new prototype in #1885
