### ISSUE TITLE
Minor changes to Filtering UI Mockup to match the style guide

### ISSUE THREAD

**Issue by NilakshiS** [hackforla/tdm-calculator#1838]
### Overview
The Figma designs and prototypes created for the Filter functionality on My Projects page need to be updated to be consistent with the styles in the style guide.

### Details
The style guide has some different styles than what the design mockups for filter use, we need to update the design mockups to keep it consistent with the style guide. There are also some suggestions to implement.

1. Change "Show Result" on buttons to "Apply".
  <details><summary>Details</summary>
  
The Primary Call to Action button on each popup is labelled "Show Result", but the usual word used for something like this is "Apply".  
  - This is just John's opinion, so we can use another working if you want.  
  - Product agrees Apply is more consistent with industry standard.  
  - If Design has a different word we should use, please provide industry examples.  
  - Examples
     - Google Sheets uses "OK"
    
  <img src="https://github.com/user-attachments/assets/3d06302b-f1d8-405c-b0f6-feb7fd36a441" width=200px>
  
- Dev has already implemented this, see screenshot from dev site
  <img src="https://github.com/user-attachments/assets/af436635-f345-4c2f-afb0-05bb35461064" width=200px>

  </details> 

2. Apply the "Primary" button style from the style guide to the "Apply" button.
3. Design a style for "Cancel" button or propose another from the existing styles.
    > The Reset button is functionally equivalent to a Cancel button on, say the Duplicate Project Dialog, so we will apply that style unless directed otherwise. It's not clear to me if the style guide includes a button style for "Cancel". In some case Cancel is the Primary (safest option) and in others it might be Secondary, but maybe Cancel-type operations need their own button design.

### Action Items
- [x] Implement the changes to the design mockup and update the designs and prototype on Figma: 
  - [x] Change "Show Result" on buttons to "Apply"
  - [x] Apply the "Primary" button style from the style guide to the "Apply" button.
  - [x] Design a style for "Cancel" button or propose another from the existing styles
- [x] Review with Product, Dev and Research and iterate if needed based on feedback.
- [x] Update the style guide to add the new design.
- [ ] Once finalized, get Stakeholder sign-off via the stakeholder meeting slide deck.

### Resources
- [Link to Buttons and Pagination in the style guide presentation](https://docs.google.com/presentation/d/1I4q35NL2WW2RpksIyawhHCd8qJnrjme1ZDNIBxu24hQ/edit#slide=id.g27275e02f73_6_0)
- New Filter Designs:
   - Design Issue #1885
   - [Link to new prototype on Figma](https://www.figma.com/design/nD9QK56Mzq7xNSaSUoeGx0/TDM-Calculator?node-id=14857-36047&t=NeVOumFN3snNa4Cg-1)
  - [Link to interactive prototype](https://www.figma.com/proto/nD9QK56Mzq7xNSaSUoeGx0/TDM-Calculator?page-id=3331%3A11990&node-id=14857-37246&node-type=frame&viewport=6839%2C-4000%2C0.25&t=6BZzZiFUkD2agnPC-1&scaling=min-zoom&content-scaling=fixed&starting-point-node-id=14857%3A37246&show-proto-sidebar=1)
- Old Filter Designs:
  - Design Issue #1578
  - [Link to the Filter designs on Figma file](https://www.figma.com/design/nD9QK56Mzq7xNSaSUoeGx0/TDM-Calculator?node-id=11866-11910&t=T72RYUQU9k6TOA9W-1)
  - [Link to the Figma Prototype for filtering UI](https://www.figma.com/proto/nD9QK56Mzq7xNSaSUoeGx0/TDM-Calculator?type=design&node-id=12173-2052&t=wQuxLI1JbOw0OzLn-1&scaling=scale-down&page-id=2499%3A11472&starting-point-node-id=11997%3A885)

**Comment by serena1214** [comment]
![Redesign Cancel Button](https://github.com/user-attachments/assets/1a5fc24e-3f6e-4ca1-b236-4f355cb846f2)
I made 3 new designs for the cancel button. I'd like to get the team's thoughts before moving on to the next step.

**Comment by serena1214** [comment]
Updated all the cancel and apply buttons on #1885 New prototype for filters and my projects based on dev site.

**Comment by NilakshiS** [comment]
@serena1214 Could you also change the button text to "RESET" instead of "CANCEL". It is more accurate for use in context of filters and is also used on the dev site. I've added a "Button Text" property to the component so it should be easier to change the value for multiple instances.
![image](https://github.com/user-attachments/assets/7651f60b-3fde-49a4-927b-75b165180888)
)

**Comment by serena1214** [comment]
Thank you @NilakshiS! I've updated all to "RESET"

**Comment by NilakshiS** [comment]
New button styles suggested for cancel and reset buttons:
- https://github.com/hackforla/tdm-calculator/issues/1768#issuecomment-2421364257

**Comment by NilakshiS** [comment]
New button styles have been approved by the stakeholders on 10/29/2024. Updated the new filter prototype (#1885) with the new design.
![image](https://github.com/user-attachments/assets/2265317c-e755-4f41-a038-2bcac8fc8502)
