### ISSUE TITLE
Cleanup Github Repo 

### ISSUE THREAD

**Issue by KPHowley** [hackforla/tdm-calculator#184]
### Overview
Cleanup the GitHub repository to remove unnecessary files and information. This should be done by John or under his direction.

A couple to dos: 

- [ ] Organize files into folders

**Comment by entrotech** [comment]
I'm not see much of any junk in the repo, except for an .ideas folder in the root directory that vivian checked in.  I'm not sure what that is. Bonnie said there were things like a .vscode directory, but I don't see that, nor do I see anything else that looks out of order. Personally, I think it is good to have the standard create-react-app README.md in the client directory, as it clearly identifies the client as a create-react-app application and give important information about how to work with it.  If we want, I suppose we could add some caveat at the top of that README.md that directs the user to the README file in the root directory for top-level project information.

**Comment by joelparkerhenderson** [comment]
The `.idea` folder is a typical tool directory for an IDEA editor such as by JetBrains, akin to `.vscode` or `.emacs` etc. Delete it. 

If possible, consider ways to stop it in the future, such as by adding to your `.gitignore` file, or a commit hook, etc.

**Comment by entrotech** [comment]
Thanks Joel, I'll add it to the .gitignore file.  I beleive I also need to get every developer to run 
```
git rm --cached ./.idea/*
``` 
once to keep the folder from being recreated with subsequent comits?

**Comment by joelparkerhenderson** [comment]
Yes you're right. 

And if you want to ensure the developer does it at the top level:

```
git rm --cached $(git rev-parse --show-toplevel)/.idea
```
