### ISSUE TITLE
Create Seperate Development Website & Branch for Testing 

### ISSUE THREAD

**Issue by KPHowley** [hackforla/tdm-calculator#185]
### Overview
Create a way to test features before deploying to the main TDM website, by creating a separate branch in git hub and specific development website. 

### Action Items
- [ ] research best methodology and update issue

**Comment by entrotech** [comment]
I'm proposing using "Git Flow"  - see https://nvie.com/posts/a-successful-git-branching-model/  This seems to be widely adopted and appropriate for our team. Posted this suggestion on the slack channel, but haven't had any feed back on the suggestion yet. We will need to designate one or more people other than me (but probably a limited number of people) to be able to do the releases.

**Comment by entrotech** [comment]
Closed by PR #195
