### ISSUE TITLE
Experiment: Try two different implementations of filtering text columns on the My Projects Page

### ISSUE THREAD

**Issue by entrotech** [hackforla/tdm-calculator#1850]
### Overview
We need to converge on a design for the column header filter UI for text-based columns. To let the designers, PMs and stakeholders get some experience with the general approaches, implement two different approaches on different text columns. Eventually, we should get feedback from the above parties to decide on the best UX.

### Action Items
- [x] Implement a text column heading filter for the Address column that implements a stripped-down Google Sheets style filter control, similar to the prototype.  This can be re-styled to better comply with the style guide.  I would suggest adding additional features found in the Google Sheets control (i.e, a "Select all n" link, a "clear" link, a indication of how many items are currently selected).
- [x] For other text columns (e.g., Name, Alternative Number) implement a more traditional multi-select drop-down filter. With some effort, we can probably re-style the badges indicating what is selected, add check boxes to the list items, and get the styling of all the elements of the control be more compliant with the style guide.
- [ ] Solicit feedback from designers, PMs and possibly stakeholders.

### Resources/Instructions
[Prototype](https://www.figma.com/proto/nD9QK56Mzq7xNSaSUoeGx0/TDM-Calculator?type=design&node-id=12173-2052&t=wQuxLI1JbOw0OzLn-1&scaling=scale-down&page-id=2499%3A11472&starting-point-node-id=11997%3A885)

Google Sheets / Prototype Style:

**Comment by thetanmancan** [comment]
Hi @entrotech. Can this issue be closed?
