### ISSUE TITLE
TDM: Open Role for: UX Designer

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/tdm-calculator#1856]
<img src="https://www.hackforla.org/assets/images/projects/tdm-calculator.jpg">

**Project Name:** TDM Calculator

**About:** “Transportation demand management” or TDM focuses on understanding how people make their transportation decisions and helping people use the infrastructure in place for transit, ridesharing, walking, biking, and telework. 

The LA TDM Calculator is a web app, created in conjunction with the L.A. Department of Transportation (LADOT) and Los Angeles City Planning, to help real estate developers design better projects for Los Angeles. It gives real-time feedback while developers explore TDM strategies and enables easier access for general public to explore various TDM strategies. The Calculator is being implemented alongside a new ordinance reducing over-parking and improving the infrastructure to incentivize public transportation and discourage single occupancy vehicle trips. 

**Volunteer Opportunity**: Help us make sure the site we are about to launch with the Los Angeles Department of Transportation and LA City Planning matches our design system. We will also soon be creating a whole new website from scratch including design system.

We are looking for 2-3 UI/UX designers to help us improve our website by:
- Reviewing the website to ensure consistency with the design system.
- Creating designs in Wireframe, High Fidelity, and Prototype format using Figma.
- Presenting the design to the team.
- Handing off the design to the developers.

**Duration:** 2-3 months

**Meeting Times:** 
- Design Team meeting (required):
Wednesdays 6:30 PM - 7:00 PM PST

Even better, if you can attend the All-team and Stakeholder meetings, more meeting times on this page: https://www.hackforla.org/projects/tdm-calculator

**Communicate your interest**
Slack channel link: [#tdm-calculator](https://hackforla.slack.com/archives/CKY65G266)
Slack name of person to contact in the channel: see who this issue is assigned to and @ message them in the channel above
[Read more about the project](https://www.hackforla.org/projects/tdm-calculator)

**Comment by NilakshiS** [comment]
This role has been filled by @malubongestab @mjldesign @greenishviolet
