### ISSUE TITLE
Implement the reset the filters and sort back to default

### ISSUE THREAD

**Issue by Parisajf** [hackforla/tdm-calculator#1858]
### Dependency
- Design an easy option to reset the filters and sort back to default #1833 

### Overview
As a user I want to be able to clear all the filters and sort sections at once, so I can get back to the default view. Design a way to reset the sort and filters to default.

### Action Items

[INSERT ACTION ITEMS HERE]

### Resources/Instructions

- On Page load the following filters and sort order is selected by default:
- Filter by "Visible" projects
- Sort by oldest "Created On" date first
- My Project's page https://tdm-dev.azurewebsites.net/projects
- Design Issue for filters https://github.com/hackforla/tdm-calculator/issues/1578
- [Link to Issue 1578 Figma file](https://www.figma.com/design/nD9QK56Mzq7xNSaSUoeGx0/TDM-Calculator?node-id=11866-11910&t=T72RYUQU9k6TOA9W-1)
- [Link to Issue 1578 protype](https://www.figma.com/proto/nD9QK56Mzq7xNSaSUoeGx0/TDM-Calculator?type=design&node-id=12173-2052&t=wQuxLI1JbOw0OzLn-1&scaling=scale-down&page-id=2499%3A11472&starting-point-node-id=11997%3A885)
- [Link to current Figma file, Issue 1816](https://www.figma.com/design/nD9QK56Mzq7xNSaSUoeGx0/TDM-Calculator?node-id=3331-11990&t=hfZyqX5uESvG4vA3-1)

**Comment by ExperimentsInHonesty** [comment]
This issue is a duplicate of https://github.com/hackforla/tdm-calculator/issues/1915
