### ISSUE TITLE
Replace graphics with Material Design Icons from Style Guide

### ISSUE THREAD

**Issue by entrotech** [hackforla/tdm-calculator#1880]
### Overview
This issue reconciles various icons in the application with the current design standards document.

### Action Items
Here is a list of pages where replacements are required:

1. Use [Warning icon](https://mui.com/material-ui/material-icons/?query=warning&selected=Warning) in Material Design instead of warning-icon.png
   - client/src/components/Faq/DeleteFaqModal.jsx
   - client/src/components/Layout/NavBarToolTip.js
   - client/src/components/ProjectWizard/WizardPages/Level0Page.jsx
   - client/src/components/ProjectWizard/NavConfirmDialog.js
   - client/src/components/Projects/DeleteProjectModal.js
   - client/src/components/Faq/SaveConfirmationModal.jsx
2. Use [Search icon](https://mui.com/material-ui/material-icons/?query=s&selected=Search) in Material Design instead of search.png
   - client/src/components/Projects/ColumnHeaderPopups/MultiSelectText.js
   - client/src/components/Projects/ProjectsPage.js
   - client/src/components/Projects/ColumnHeaderPopups/TextPopup.js
3. Use [Close icon](https://mui.com/material-ui/material-icons/?query=close&selected=Close) in Material Design instead of Font Awesome close icon
   - client/src/components/Checklist/ChecklistModal.js
   - client/src/components/UI/AriaModal/ModalDialog.js
4. Verify that the following images are no longer used and remove them from the /client/src/images folder:
  - close.png
  - copy.png
  - trash.png

### Resources/Instructions
- #1681

**Comment by ExperimentsInHonesty** [comment]
Appeared in the [2024-11-12 Stakeholder deck](https://docs.google.com/presentation/d/1Urb8pV-P-05586u2c59nEjmUeWa_3s4kJUETi8lllOw/edit#slide=id.g3130e663650_0_0) and was approved.
