### ISSUE TITLE
Design: Create Mockups for adding/editing admin notes on the My projects page

### ISSUE THREAD

**Issue by NilakshiS** [hackforla/tdm-calculator#1889]
### Overview
Admin needs the ability to view, add and edit notes to a project from the "My Projects Page". Create design mockups for possible solutions.

### Details
Dev has implemented a basic view, add and edit notes functionality on the "My Projects Page" but it is not very user friendly. One suggested solution is to use Modals. Create different mock-ups using modals as well as any other possible solutions to help visualize ideas and get feedback.

(Expand to see screenshots from dev site below)

<details><summary>Image of admin notes column currently</summary>

![image](https://github.com/user-attachments/assets/9165fd63-bd5c-4db2-9999-9175627fc4fc)
</details> 
<details><summary>Notes which have already been created show a pencil icon to edit them, while a plus icon indicates adding a new note</summary>

![image](https://github.com/user-attachments/assets/3c549b63-d4f6-423e-a292-5362224198ee)
</details>
<details><summary>Editing a note changes the note to an editable text box with save and cancel buttons</summary>

![image](https://github.com/user-attachments/assets/862347cb-1cc6-4597-8be6-1d8715f54441)
</details>
<details><summary>Adding a new note also opens an editable text box with save and cancel buttons</summary>

![image](https://github.com/user-attachments/assets/16434bf6-fa55-44b7-9e17-d89646471746)
</details>

### Action Items
- [x] Create design mockups
- [ ]  Connect the mockup to the new "My Projects Page" prototype if possible #1885 
- [ ] Review with Product, Dev and Research and iterate if needed based on feedback.
- [ ] Once finalized, get Stakeholder sign-off via the stakeholder meeting slide deck.

### Resources/Instructions
- [Link to "My Projects Page" on dev site](https://tdm-dev.azurewebsites.net/projects)
- [Link to old prototype on Figma](https://www.figma.com/design/nD9QK56Mzq7xNSaSUoeGx0/TDM-Calculator?node-id=12173-2052&t=asZQfnZ5cldg15st-1)
- [Link to new prototype on Figma](https://www.figma.com/design/nD9QK56Mzq7xNSaSUoeGx0/TDM-Calculator?node-id=14857-36047&t=asZQfnZ5cldg15st-1)
  - [Link to interactive prototype](https://www.figma.com/proto/nD9QK56Mzq7xNSaSUoeGx0/TDM-Calculator?page-id=3331%3A11990&node-id=14857-37246&node-type=frame&viewport=6839%2C-4000%2C0.25&t=6BZzZiFUkD2agnPC-1&scaling=min-zoom&content-scaling=fixed&starting-point-node-id=14857%3A37246&show-proto-sidebar=1)

**Comment by namigoeku** [comment]
Took dev's suggestion of using a modal for the edit portion. 

User would continue to add note by clicking the plus icon
![1](https://github.com/user-attachments/assets/30c5b8b4-9872-47fd-bf0e-771ed112abc5)




Then the modal pops up, with a text box and a save and cancel button. 
<b>Question 1: Is there a character limit in this text box? If so, we can indicate this. 
Question 2: Can the modal be resized with a text area resize icon? </b>
![pajamas_resize](https://github.com/user-attachments/assets/efa399f2-ec31-419a-be3b-61e620cdd128)
![2](https://github.com/user-attachments/assets/f517e0fe-19a9-4615-b918-b8f875464b60)




Once saved, there is a note preview with a limited number of characters. 
The expand icon can be used to indicate opening the modal.
<b>Question: Does this need an additional modal indicating a 'view' mode for the note</b>
![3](https://github.com/user-attachments/assets/0e48cada-6b36-424c-8ebd-9b0e109f5b15)

**Comment by namigoeku** [comment]
I took the suggestion in using a modal. 

The user would press the plus icon to add a note
![1](https://github.com/user-attachments/assets/25c83144-8509-4141-89f6-e671ed10fd8c)

<br><br>
That would open a modal with a text box and a save and cancel button.<br>
<b>Question 1: Is there a character limit in the notes? We can notate a character limit at the top.
Question 2: Do we need a scrollbar or textarea resize icon to account for a large amount of characters? 
![pajamas_resize](https://github.com/user-attachments/assets/6278d893-0cef-4bb6-ae11-f5496760f161)
![2](https://github.com/user-attachments/assets/5ca86ad2-5058-473c-b590-e417d572e86a)

<br><br>
Once the note is saved, the note preview would indicate a limited number of characters to indicate there is a note attached.
The user can press the expand icon to edit or view the comment.<br>
<b>Question: Would it be an issue if the user accidentally edits the modal while viewing?</b>
![3](https://github.com/user-attachments/assets/657405db-b098-4718-8224-0f35d433b47f)

**Comment by ExperimentsInHonesty** [comment]
Column should have two icons (no text).  Icons represent
- add a new note
<details><summary>Add new note modal image</summary>

![image](https://github.com/user-attachments/assets/a0f3ddd9-ff44-4cc3-848e-4a20e1c39f0c)
</details> 

- read/edit a note
   - Modal option 1 (it takes you to a modal that looks like the add a new note modal)
   - Modal option 2 (it takes you to a modal that has the text, and you have to click on pencil)

**Comment by namigoeku** [comment]
- To do: create specs with paragraph spacings of the modal.  
- Done this week: Created 2nd version of modal for editing admin notes. 
- Used larger plus sign used by Yiran in her latest design. 
![Image](https://github.com/user-attachments/assets/1a5580a8-a3a7-444d-af3c-6a13f330b318)

![Image](https://github.com/user-attachments/assets/b3402a5e-adaa-4cca-bb11-4647d8ce1ac3)


- Larger text area as requested by Bonnie and dev's to account for potentially large area of text. 
- 16:9 ratio, or 1080px by 608px
- Blue bounding box indicates you are in edit mode, similar to edit mode in the admin FAQ page. 

![Image](https://github.com/user-attachments/assets/aa63eb02-4fe0-4169-bcbb-b7ff3b2919df)


- Once the note is saved and the user returns to the page there is a note icon indicating there is a saved note. 

![Image](https://github.com/user-attachments/assets/55be7893-163b-4042-a5a6-9584f8cf7fba)


- Text box is grey to indicate the note is in view mode. 
- User clicks the edit note button to take the user into edit mode. 
![Image](https://github.com/user-attachments/assets/ab4045bc-6b41-4288-a595-8fd838367cab)

<b>Question 1: Will the background of the modal be blurred so draw the user's attention to the note?
Question 2: If the user attempts to click outside or write a note without saving will a warning modal appear?</b>

![Image](https://github.com/user-attachments/assets/a6e444ef-ea58-4e5e-993c-95bf24c0427c)

**Comment by NilakshiS** [comment]
Feedback from stakeholder's meeting on 10/15: 

- Design approved
- Clicking outside should not close the modal. If the users click close icon or the cancel button without saving the changes, it should give a warning about unsaved changes similar to what we have when we navigate to another page without saving a project.
- Blurring the background is fine.

<details><summary>Image of the warning dialog box from create project page</summary>

![Image](https://github.com/user-attachments/assets/8c70f6e3-33c8-472c-a48c-7e835396620d)

</details>

**Comment by namigoeku** [comment]
Created the warning modal. 

[
![#1889 Edit Note Modal](https://github.com/user-attachments/assets/4f4170ab-fb4b-4e29-8f6d-791f2426fb22)
](url)

![warning modal](https://github.com/user-attachments/assets/8c5f447c-f7a0-4017-9ca7-4ab135776e93)

**Comment by namigoeku** [comment]
Updated the warning modal to match the current design system. Updated the modal to current font styling. 

![Important Info Box](https://github.com/user-attachments/assets/6524f102-9b49-44ba-b825-4eb34f4757c8)

![#1885 - My Projects page](https://github.com/user-attachments/assets/72c82355-96ec-46ab-8c07-637900f31406)

**Comment by NilakshiS** [comment]
Updated spelling for discard, used the new secondary button.
![#1885 - My Projects page](https://github.com/user-attachments/assets/3c698712-37d3-47c2-9856-c9cd2d477cb7)

**Comment by ExperimentsInHonesty** [comment]
@namigoeku there are two issues we would like to solve
1. the modal refers to a page, but it should be referring to the note
2. the modal is appearing, but the note has disappeared, and we see the my projects page in the background.  Wouldn't we see the note in the background?

**Comment by namigoeku** [comment]
@ExperimentsInHonesty 

1. Can you clarify what you meant by this? The modal is the screen that will act as a popup overlay over the page. 
2. Thank you for catching that. Added the note behind the warning modal. Please see revised mockups. 

Other things to note:

- Updated the background overlay to Grace's specifications
- Updated the corner radius to Grace's specifications

Click plus sign to add a new note. Opens in edit mode (blue outline). Use text box expand icon used in "Project Description" section of create projects page. 
![#1885 - My Projects page - 1](https://github.com/user-attachments/assets/b4dd3607-34e2-4630-9447-37fa674fd220)
![image](https://github.com/user-attachments/assets/6da5e971-0140-4a4f-bd1c-ca84e882c3f4)

View Note - opens in view mode (grey outline)
![#1885 - My Projects page - 2](https://github.com/user-attachments/assets/47642fac-9862-47ec-a6f0-dfafbc0c15c4)

Edit Note - textbox appears in edit mode (blue outline)
![#1885 - My Projects page - 3](https://github.com/user-attachments/assets/710bba0d-618e-41ef-911b-90c903266121)

Error Modal - Appears over the edit note modal. 
![#1885 - My Projects page - 4](https://github.com/user-attachments/assets/3487adeb-269a-4f8d-8670-1be25fa7e442)

**Comment by namigoeku** [comment]
@ExperimentsInHonesty Took your suggestion in darkening the stacked overlays by layer. Will be working separately with @greenishviolet in refining the overlay color and add to the design system. 

![#1885 - My Projects page - 4](https://github.com/user-attachments/assets/3ea00756-7faa-4f17-8326-6faa5dd3bdfb)

**Comment by NilakshiS** [comment]
From the Stakeholder meeting 11-12-2024: unsaved changes modal design approved, however the lighter overlay version is preferred over the stacked dark overlays. Final designs : https://github.com/hackforla/tdm-calculator/issues/1889#issuecomment-2448395660
