### ISSUE TITLE
Communicating unsaved changes on FAQ page

### ISSUE THREAD

**Issue by namigoeku** [hackforla/tdm-calculator#1896]
### Overview
FAQ Page: When attempting to navigate away from the page, there should be a warning indicating unsaved changes. 

### Action Items

- [ ] This can be accomplished by using the modal previously created by devs on the projects page. The modal's verbiage should say something like "Unsaved Changes: Are you sure you want to leave the page?", along with "Save"/"Stay" and "Discard Changes" CTA buttons. 
- [ ] Would devs prefer "Save" or "Stay"? "Save" should automatically save the progress, whereas "Stay" indicates the user will remain on the page to continue their progress. 
- [ ] Review with product and dev. Update if needed based on feedback
- [ ] Once finalized, add before and after images to the [staging deck on this slide](https://docs.google.com/presentation/d/1crZ3IxqA4hAu3qzD7ns93Ieuqjwh6wyEtuX_46cP-fg/edit#slide=id.g31011179ea8_0_108) 
- [ ] Get Stakeholder sign-off via the stakeholder meeting slide deck.

![Image](https://github.com/user-attachments/assets/047327cd-2be2-4c0e-82a0-63dfebddee16)

<b>FAQ Page</b>
![image](https://github.com/user-attachments/assets/97644399-12ae-4f13-9210-ab5d47e6f597)

<b>Example solution</b>
![image](https://github.com/user-attachments/assets/afc8aece-3b5e-4952-a414-95982f209968)

**Comment by ExperimentsInHonesty** [comment]
latest image.... @NilakshiS might replace in a new comment
![image](https://github.com/user-attachments/assets/bbc95cd7-313a-4bf6-b250-c9068ba52049)

**Comment by NilakshiS** [comment]
Suggested Modal Design: 
![Navigation Confirm Modal](https://github.com/user-attachments/assets/2aa22d20-1bb9-4534-b0c9-7c048d47dd6f)

**Comment by ExperimentsInHonesty** [comment]
@npang4 Please provide update
1. Progress: "What is the current status of your project? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"
5. Pictures or links* (if necessary): "Add any pictures or links that will help illustrate what you are working on."

* remember to add links to the top of the issue if they are going to be needed again.

**Comment by npang4** [comment]
> @npang4 Please provide update
> 
> 1. Progress: "What is the current status of your project? What have you completed and what is left to do?"
> 
> 2. Blockers: "Difficulties or errors encountered."
> 
> 3. Availability: "How much time will you have this week to work on this issue?"
> 
> 4. ETA: "When do you expect this issue to be completed?"
> 
> 5. Pictures or links* (if necessary): "Add any pictures or links that will help illustrate what you are working on."
> 
> 
> 
> * remember to add links to the top of the issue if they are going to be needed again.

Hi, I am still working on this issue. I currently have the modal up, but I am having issues getting the modal to pop up when trying to leave the page after making edits. I am going to bring this up in the dev meeting next Wednesday. I hope to have it completed in the first week of December.

**Comment by NilakshiS** [comment]
From stakeholder meeting on 03/12/2024:
Updated design for the modal (title and description are changed, similar to the navigation confirmation modal on the calculator)
![FAQ navigation confirm Modal](https://github.com/user-attachments/assets/b29260c5-5e94-4ad2-aea2-d6120ac24405)

**Comment by ExperimentsInHonesty** [comment]
@npang4 Please provide update.  Also, note that design left you an updated modal design and working in comment above

**Comment by npang4** [comment]
@ExperimentsInHonesty Noted the updated modal. Still currently working on the issue as of right now. Working on getting the modal to trigger when trying to navigate away from the page after making an edit.

**Comment by NilakshiS** [comment]
[Added to the 2025-01-07 Release Updates](https://docs.google.com/presentation/d/1dnA-b6dYk86VCg6LBDiOXjoX60mR0Lpy5q7apVoABRA/edit#slide=id.g2d705dd7a05_0_1)

**Comment by ExperimentsInHonesty** [comment]
Appeared in the [2025-01-07 Stakeholder deck](https://docs.google.com/presentation/d/1dnA-b6dYk86VCg6LBDiOXjoX60mR0Lpy5q7apVoABRA/edit#slide=id.g2d705dd7a05_0_1) and was approved.
