### ISSUE TITLE
Design: Create mockups with alternate wording for "Reset Page"

### ISSUE THREAD

**Issue by NilakshiS** [hackforla/tdm-calculator#1901]
### Overview
The "Reset Page" button should be reworded using terms such as “Clear Fields,” or “Clear Page” so it is less likely to be confused with Reset Project. Create mockups with different wording options, including but not limited to “Clear Fields” and “Clear Page”.

### Action Items
- [x] Create a mockup of calculator pages with alternate wording:
   - [x] mockup of page 2
   - [x] mockup of page 4
- [x] Review with product and design. Update if needed based on feedback
- [x] Once finalized, add before and after images to the [staging deck on this slide](https://docs.google.com/presentation/d/1crZ3IxqA4hAu3qzD7ns93Ieuqjwh6wyEtuX_46cP-fg/edit#slide=id.g3163b6ed272_0_46) 
   - [x] if no slide has been made, make one in [the staging deck](https://docs.google.com/presentation/d/1crZ3IxqA4hAu3qzD7ns93Ieuqjwh6wyEtuX_46cP-fg)
- [x] Get Stakeholder sign-off via the stakeholder meeting slide deck.

### Resources/Instructions
- [Link to page 2 on TDM Calculator dev site](https://tdm-dev.azurewebsites.net/calculation/2/0)
- [UX Research recommendation on reset button wording](https://docs.google.com/presentation/d/15T05DYjmiuiztDpU8iGzn2zHb7i2ANn9XjpJCqUKdvo/edit#slide=id.g20534e932cc_0_89)

**Comment by ancyjoy7** [comment]
Made iterations with suggested wordings for the "Reset Page" button.

**Option 1 - replace “Reset Page” to “Clear Page”**

<img width="1114" alt="image" src="https://github.com/user-attachments/assets/bb8f7fa2-971d-46b1-98b6-33e6e0f7d423">


**Option 2 - replace “Reset Page” to “Clear Fields”**

<img width="1132" alt="image" src="https://github.com/user-attachments/assets/9a73cccb-c589-4852-b3d6-6fcd12f9d706">


**Option 3 - replace “Reset Page” wording to suggested wordings and make the most destructive action a negative color”**

<img width="1121" alt="image" src="https://github.com/user-attachments/assets/d9a5a2e2-a787-4255-81cd-862c1fe04f4b">

**Comment by NilakshiS** [comment]
From team meeting on 2024-11-20: "Clear Page" was selected as the preferred choice. Need to inform stakeholders and get sign-off.

**Comment by NilakshiS** [comment]
From Stakeholder meeting on 2024-12-03: Changes approved, signed-off by stakeholders.
