### ISSUE TITLE
Design: Create mockups for editing tooltips

### ISSUE THREAD

**Issue by NilakshiS** [hackforla/tdm-calculator#1903]
### Overview
Admin users need the ability to edit the tooltip text in the calculator pages (1-4).  So that they can update the information related to Strategies and Input fields that define a project (e.g., APN number).

### Details
All the users on website have the ability to view tooltips on fields: 
<details><summary>The "i" icon shows a Tooltip exists on a field</summary>
 
![image](https://github.com/user-attachments/assets/97f38a0c-66d0-40c7-b92e-8b111cdcf5ca)
</details> 

<details><summary>Clicking on the icon opens the Tooltip with related information</summary>

![image](https://github.com/user-attachments/assets/7910b088-315b-4a0e-b9d5-3f7731e6d79e)
</details> 

However Admin users need ability to modify the tooltips. We need to create mockups for the different actions admin user can take on tooltips:
- View existing tooltips
- Add a new tooltip if it does not exist
- Edit the tooltip

Suggested design ideas for the new actions:
- Add a new tooltip:
  - For fields that do not have a tooltip, the ["i" icon](https://mui.com/material-ui/material-icons/?query=info&selected=Info) ![image](https://github.com/user-attachments/assets/fe5763ac-7090-45b2-90c6-4be751015295) can be replaced with a ["+" icon](https://mui.com/material-ui/material-icons/?query=addc&selected=AddCircle) ![image](https://github.com/user-attachments/assets/c0e0945b-07da-453b-b254-09fddb64431a) instead.
  - Clicking on the "+" icon should open a modal to allow user to add text for the tool tip, similar to admin notes design.
 
      <details><summary>Design of the modal to add an admin note</summary>
      
      ![image](https://github.com/user-attachments/assets/2a8e49fc-d832-44d6-8dd5-fea901230869)
      </details> 
   - After the tooltip text is saved, the field should have the "i" icon to indicate that a tooltip now exists

- Edit the tooltip
   - Since a tooltip already exists, the field will have an "i" icon.
   - On the bottom right of the expanded tooltip an [edit icon button](https://mui.com/material-ui/material-icons/?query=edit&selected=Edit) ![image](https://github.com/user-attachments/assets/bf6849be-4a2f-4bcd-b235-2c34bf62e7f9) can be used to edit the text
    ![image](https://github.com/user-attachments/assets/0edc1564-97fb-4205-bc31-3f36dcaec5be)
   - Clicking the edit icon button, opens a modal to edit the tooltip text, similar to admin notes design.

### Action Items
- [x] Create mockups for each user flow on Figma:
   - [x] View a tooltip
   - [x] Add a new tooltip
   - [x] Edit a tooltip
- [x] Review with product and design. Update if needed based on feedback.
- [x] Once finalized, add images to the [staging deck on this slide](https://docs.google.com/presentation/d/1crZ3IxqA4hAu3qzD7ns93Ieuqjwh6wyEtuX_46cP-fg/edit#slide=id.g31011179ea8_0_0) 
- [x] get Stakeholder sign-off via the stakeholder meeting slide deck.

### Resources/Instructions
- [Link to TDM Calculator dev site](https://tdm-dev.azurewebsites.net/calculation/1/0)
- [Link to the style guide](https://docs.google.com/presentation/d/1I4q35NL2WW2RpksIyawhHCd8qJnrjme1ZDNIBxu24hQ/edit#slide=id.g2a6d1bfeb46_0_103)

**Comment by namigoeku** [comment]
Questions for team:

1. <b>What will be editable in the popover modal?</b>
   - Text
   - Hyperlink
   - Ability to delete


2. <b>What is the maximum text length?</b>
   - Maximum text should be as short as possible, with external link to guide user to more information. 


3. <b>Secondary issue 1: Tooltip and modal behavior: In-line with text, when should function as an overlay</b>


4. <b>Secondary issue 2: Tooltip vs. Popover verbiage should be distinct</b>
   - A tooltip is used to give the user hints or help them to complete an action. They are also non-interactive.
   - A popover is used to give the user more detail about how to complete an action and can include links, is clickable, can support larger text area. 
   - Created issue #1916 so we can differentiate a tooltip from a popover in the design system.

**Comment by namigoeku** [comment]
I took the suggestions and made a mockup flow with as few steps as possible.

Blockers: 
- The proximity between the close button and edit button may cause the user to accidentally click something. 
<br>

Plus icon indicates a tooltip may be added. 
![#1903 - 1](https://github.com/user-attachments/assets/3e451367-22c9-4972-8d2b-ea2dfc0535f2)

An edit modal opens, with note that indicates the textbox is HTML only. 
![#1903 - 3](https://github.com/user-attachments/assets/f5b8556c-cb23-43b8-ac7c-09967055363e)

Once the user closes the modal, they have a preview of the tooltip. To edit, they click the edit button on the bottom righthand corner. 
![#1903 - 4](https://github.com/user-attachments/assets/bd864203-1200-41e7-bf51-219bfd8cdec9)

The edit modal appears and behaves similarly to the first modal. 
![#1903 - 5](https://github.com/user-attachments/assets/705eedac-35bc-4290-b75d-aef849412aac)

Clicking outside the modal will prompt a warning modal indicating the user will lose their changes. 
![#1903 - 6](https://github.com/user-attachments/assets/d8f24053-3c65-4697-920b-b5bc9f1a12ba)

**Comment by ExperimentsInHonesty** [comment]
Small change required, it will use the same editing functionality as the FAQ.  It will not require HTMLS

**Comment by namigoeku** [comment]
@ExperimentsInHonesty Hi Bonnie, would you suggest I make the edit modal look similar to the edit FAQ page portion?

**Comment by ExperimentsInHonesty** [comment]
@namigoeku Please provide update
1. Progress: "What is the current status of your project? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"
5. Pictures or links* (if necessary): "Add any pictures or links that will help illustrate what you are working on."

* remember to add links to the top of the issue if they are going to be needed again.

**Comment by namigoeku** [comment]
@ExperimentsInHonesty Apologies for the delay. It's been a busy few weeks personally. 

Progress: I will need 1 more week to complete this. 
Blockers: None currently. 
Availability: 8 hrs
ETA: Next Wednesday

**Comment by namigoeku** [comment]
Added the editing tools in the modal. 

Design System: Added additional icons (bold, underline, strikethrough, bulleted list, numbered list) to the design system. I'd like to mention that the link icon is not a current material design icon. 


![#1889 Note Modal](https://github.com/user-attachments/assets/0b86a7a0-fd9b-44f6-8a17-9708c703fc79)

**Comment by NilakshiS** [comment]
From the stakeholder meeting on 03/12/2024:
- Designs are approved

[Link to approved designs on Figma](https://www.figma.com/design/nD9QK56Mzq7xNSaSUoeGx0/TDM-Calculator?node-id=16602-2553&t=1OUA2KgVC7uuqGqH-1)

<details><summary>No tooltip exists, "plus sign" icon to add a tooltip</summary>

![1](https://github.com/user-attachments/assets/d1f33312-5b91-4445-a77d-494768d8aedb)
</details> 
<details><summary>Modal to add the tooltip text</summary>

![3](https://github.com/user-attachments/assets/a7bb112b-feb1-4ad3-8a4b-fde817076f3b)
</details> 

<details><summary>Tooltip exists, "i" icon is displayed, opening the tooltip shows a "pencil" icon on bottom right to edit it</summary>

![4](https://github.com/user-attachments/assets/24cc0c6f-129d-4eb0-8c68-953b28881c75)
</details> 

<details><summary>Same modal opens to edit the tooltip text</summary>

![5](https://github.com/user-attachments/assets/adcd14a7-4c26-4b45-aceb-17adf0c9188b)
</details> 

<details><summary>Warning modal in case the user leaves without saving</summary>

![6](https://github.com/user-attachments/assets/4c9ebd6a-018d-4824-96d2-d1677e0d01b6)
</details>
