### ISSUE TITLE
Design and Implement Tooltip Editing Feature for LADOT

### ISSUE THREAD

**Issue by Varun710** [hackforla/tdm-calculator#1905]
### Overview
LADOT requires the ability to edit tooltips and update strategies annually.

### Action Items

- [ ] Design an interface for editing tooltips and strategies.
- [ ] Review the design with product and stakeholders.

### Resources/Instructions
- https://tdm-dev.azurewebsites.net/

**Comment by NilakshiS** [comment]
Duplicate issue, addressed by: 
- https://github.com/hackforla/tdm-calculator/issues/1903
