### ISSUE TITLE
Add Warning Modal for Cancel/Close Actions

### ISSUE THREAD

**Issue by Varun710** [hackforla/tdm-calculator#1906]
### Overview
A warning needs to be displayed when users click the "X" or "Cancel" buttons to prevent accidental closure.

### Action Items
- [ ] Design a modal warning for "X" or "Cancel" actions.
- [ ] Review the design with the product and stakeholders.

### Resources/Instructions
REPLACE THIS TEXT -If there is a website which has documentation that helps with this issue provide the link(s) here.

**Comment by NilakshiS** [comment]
Duplicate issue, Addressed by 
- https://github.com/hackforla/tdm-calculator/issues/1889#issuecomment-2415421830
