### ISSUE TITLE
Implement New Icons to Indicate Filter State

### ISSUE THREAD

**Issue by entrotech** [hackforla/tdm-calculator#1914]
### Overview
- In order to make the change requested by Design on Issue #1837, we need to change the filter icons that indicate the "state" of each column filter in the column heading

### Action Items
- Replace the filters per the instructions in Issue #1837. Make sure to reference the theme for colors (instead of hard-coding hex values), and use the react-icons library to import the icons, e.g.
 ```import { MdFilterAlt } from "react-icons/md";``` 
and
```import {MdOutlineFilterAlt } from "react-icons/md";```
- This change should only require changes to the[ ProjectTableColumnHeader.jsx](https://github.com/hackforla/tdm-calculator/blob/develop/client/src/components/Projects/ColumnHeaderPopups/ProjectTableColumnHeader.jsx) component.

**Comment by roslynwythe** [comment]
Update: 
I completed the issue but when I brought in recent changes from the `develop` branch, I have a problem:
```
Module not found: Error: Can't resolve 'react-tiny-popover' in 'C:\Users\rosly\hfla\tdm-calc\client\src\components\Projects\ColumnHeaderPopups'
```
