### ISSUE TITLE
Review warning button text color

### ISSUE THREAD

**Issue by NilakshiS** [hackforla/tdm-calculator#1917]
### Overview
For better contrast, Bonnie suggested using white text color for the red warning buttons instead of black that is currently being used. Need to review with stakeholders for their preference .

### Detail
<details><summary>Current: Warning button with black text</summary>

![Screenshot 2024-10-24 180505](https://github.com/user-attachments/assets/74d20c49-9c05-4292-b9b4-088b7fa2e8fc)

</details> 

<details><summary>Suggested: Warning button with White text</summary>

![Screenshot 2024-10-24 180537](https://github.com/user-attachments/assets/a7bf02a9-7e46-438f-8d04-598009b3f0b6)

</details> 

### Action Items
- [x] Note down stakeholder decision on this issue
- [ ] Create new issues for dev and design if needed

**Comment by marlenamellody** [comment]
Approved by stakeholders on 10/29/24. Dev will create an issue to implement.
