### ISSUE TITLE
Modify Buttons that have a Close or Cancel function to use the "Secondary" button style

### ISSUE THREAD

**Issue by entrotech** [hackforla/tdm-calculator#1920]
### Overview
Modify the existing buttons that have a "close" or "cancel" function to use the "Secondary" style instead of the current "Text" styling, in order to comply with changes requested by the design team and PMs

### Action Items

- [x] Search for instances of the Button component that have attribute variant="text".
- [x] Determine which of them have a function that is a "cancel" or "close" type of operation.
- [x] Take screenshots of the components before making any changes and include in this description under the Resources section.
- [x] Change the attribute to variant="outlined" to switch to the "Secondary/Outlined" styling.
- [x] Add screenshots of the modified UI to this issue and the PR.

### Resources/Instructions

Examples before change:

![image](https://github.com/user-attachments/assets/658b0d1f-b202-42ab-8116-a69beb4c3c8a)

![image](https://github.com/user-attachments/assets/72110ff0-9d94-4291-8523-7ee4c032b9f8)

Here are screenshots of the buttons that have been changed for this issue:

- [ ] NavConfirmDialog.jsx
![image](https://github.com/user-attachments/assets/1d633a66-5dd0-4e3c-a3f2-32e6b5a724c8)

- [ ] AffordableEdgeCaseModal.jsx
![image](https://github.com/user-attachments/assets/162b740c-a8d5-494a-85f4-ccf854b92247)

- [ ] VisibilityPopup.jsx
![image](https://github.com/user-attachments/assets/844180ed-e7db-4404-b0a5-dbddd1183ac1)

- [ ] TextPopup.jsx
![image](https://github.com/user-attachments/assets/601c9fa5-531a-4a47-b6a7-2a389fe125a0)

- [ ] StatusPopup.jsx
![image](https://github.com/user-attachments/assets/2fbcee0c-3126-4224-bcb4-64e25d3d153b)

- [ ] DatePopup.jsx
![image](https://github.com/user-attachments/assets/a4b9c6c1-078f-4c04-88fd-f5281fc24706)

- [ ] DeleteProjectModal.jsx
![image](https://github.com/user-attachments/assets/6144f183-9b3b-4dd2-94a7-e7c28e86059a)

- [ ] CsvModal.jsx
![image](https://github.com/user-attachments/assets/4e8680a9-8d9a-4d59-9ef4-d003950c8ee5)

- [ ] CopyProjectModal.jsx
![image](https://github.com/user-attachments/assets/331c36a7-3b6e-4c87-8bfd-f1dd872688ae)

- [ ] SaveConfirmationModal.jsx
![image](https://github.com/user-attachments/assets/8cd51b1e-e094-47bd-beb8-8aa4f604b029)

- [ ] DeleteFaqModal.jsx
![image](https://github.com/user-attachments/assets/f71b6a9f-d684-4592-8d0b-69eb2e97f3a4)

- [ ] Login.jsx
![image](https://github.com/user-attachments/assets/3f9a3033-e805-49e1-8609-02a7249e59a1)

NewFaqButton.jsx  (Don't change this one)
AddNewCategory.jsx (Don't change this one)

**Comment by tntruong-iter** [comment]
Hi @entrotech, could you please assign this issue to me? I'd like to work on it. Thanks!"

**Comment by entrotech** [comment]
@tntruong-iter   Have you completed the onboarding  process to join the project?  See the repo readme file for the onboarding instructions.
