### ISSUE TITLE
Change Text Color on the Warning Buttons (sitewide)

### ISSUE THREAD

**Issue by entrotech** [hackforla/tdm-calculator#1929]
### Overview
We need to change the warning buttons (red button) to have white text instead of the standard black, so that the button is more legible 

#### Details
The hex color currently used on the site for warnings is #e46247

### Action Items
- [x] Change the coding so that it uses the color whenever something is a warning button (potentially distructive action).  
- [x] Once finalized, add  before and after images to the [staging deck on this slide](https://docs.google.com/presentation/d/1crZ3IxqA4hAu3qzD7ns93Ieuqjwh6wyEtuX_46cP-fg/edit#slide=id.g31011179ea8_0_72)
- [ ] get Stakeholder sign-off via the stakeholder meeting slide deck.

### Resources/Instructions
![image](https://github.com/user-attachments/assets/0349392d-a77b-49a2-9757-b01fcb5dd7fb)

![image](https://github.com/user-attachments/assets/a83b02c5-1730-4e55-a58c-bb1b28a2f2b8)

![image](https://github.com/user-attachments/assets/3979229c-6fc6-42be-a6ce-5a935713496f)

**Comment by Mandla-tech** [comment]
Hi @entrotech 
I noticed this task related to the Navigation Warning Dialog: changing the text color on the Proceed button to white. I would love to take on this task and contribute to the project, if you could assign this task to me.

**Comment by entrotech** [comment]
Also Changed the Share Snapshot Modal to use the standard cancel and primary button styles:

![image](https://github.com/user-attachments/assets/f41148c1-76af-4bb5-8a9e-74912af686f3)

![image](https://github.com/user-attachments/assets/f526befe-9aeb-4e78-aea2-b0a0732f2e6a)

![image](https://github.com/user-attachments/assets/080b156e-8c1b-4439-bae1-fc942b10da09)

![image](https://github.com/user-attachments/assets/786f18a9-c865-47c6-8de5-df0a556d5766)

**Comment by ExperimentsInHonesty** [comment]
Appeared in the [2024-12-03 Stakeholder deck](https://docs.google.com/presentation/d/1vc_LUPreHrToHBRGUekbXfLflOi3omt2Bo8M7uxMovI/edit#slide=id.g3173acc9abf_0_68) and was approved.
