### ISSUE TITLE
Set the default project sort order on the My Projects Page to Last Modified Date, descending

### ISSUE THREAD

**Issue by entrotech** [hackforla/tdm-calculator#1930]
### Overview
Set the default project sort order on the My Projects Page to Last Modified Date, descending, since that was agreed to in the 10/29/24 stakeholder meeting.

### Action Items
- [x] Set the default sort order
- [ ] Once finalized, add  before and after images to the [staging deck on this slide](https://docs.google.com/presentation/d/1crZ3IxqA4hAu3qzD7ns93Ieuqjwh6wyEtuX_46cP-fg/edit#slide=id.g1443c52839c_0_165)
- [ ] get Stakeholder sign-off via the stakeholder meeting slide deck.

**Comment by ExperimentsInHonesty** [comment]
@npang4 we are assigning this issue to you, because we need to get this feature delivered so we can start research.  I'll be unassigning you from the issue below for right now.
- https://github.com/hackforla/tdm-calculator/issues/1896

**Comment by ExperimentsInHonesty** [comment]
Appeared in the [2024-12-03 Stakeholder deck](https://docs.google.com/presentation/d/1vc_LUPreHrToHBRGUekbXfLflOi3omt2Bo8M7uxMovI/edit#slide=id.g314f011919a_0_126) and was approved.
