### ISSUE TITLE
Implement a string minLength and maxLength validation rule for string or textarea inputs.

### ISSUE THREAD

**Issue by entrotech** [hackforla/tdm-calculator#197]
- [x] Add minStringLength and maxStringLength columns to the CalculationRule table.
- [x] Modify CalculationRule_Select* stored procedures to return the new values.
- [x] Update the rules to use a maxStringLength value of 400 for inputs of type string.
- [x] Modify client to use the rules to implement validation

**Comment by ExperimentsInHonesty** [comment]
@entrotech Where are we at with this issue
1. Progress
2. Blocks
3. Availability
4. ETA

**Comment by entrotech** [comment]
Proposed solution for review in PR #272

**Comment by ExperimentsInHonesty** [comment]
@rosemary can you look at this paging on the dev environment to see if this is working the way you want. - here is the staging [url](https://tdm-calc-staging.herokuapp.com/) . click new project
![Screen Shot 2020-03-14 at 11 34 31 AM](https://user-images.githubusercontent.com/37763229/76688196-e90cc380-65e7-11ea-88b8-0197f6ab1706.png)
