### ISSUE TITLE
Update issues in the IN PROGRESS column with staging deck links

### ISSUE THREAD

**Issue by jmeasow** [hackforla/tdm-calculator#1970]
### Overview
Update the issues in the IN PROGRESS column with the staging deck links so that we can reduce the time it takes to make the staging deck every week, and so that we don't miss issues.

### Action Items

- [x] Go to the column
- [x] Open all the issues in the column
- [x] Add the text from template to each
- [x] Check to see if there is a slide in the Staging deck
   - [x] if not, create a slide in the appropriate section
- [x] Customize the issue with the URL from the deck 

### Resources
- [Project Board, In Progress](https://github.com/orgs/hackforla/projects/68/views/1?filterQuery=status%3A%22In+progress+%28actively+working%29%22)
- [Staging Deck](https://docs.google.com/presentation/d/1crZ3IxqA4hAu3qzD7ns93Ieuqjwh6wyEtuX_46cP-fg)
- This issue is part of an epic https://github.com/hackforla/tdm-calculator/issues/1963

#### Sections
- Discussion Topics (product or research)
- Design Review (design)
- Updates to Review & Release (dev)

### Template
```
- [ ] Review with product and dev. Update if needed based on feedback
- [ ] Once finalized, add before and after images to the [staging deck on this slide]() 
   - [ ] if no slide has been made, make one in [the staging deck](https://docs.google.com/presentation/d/1crZ3IxqA4hAu3qzD7ns93Ieuqjwh6wyEtuX_46cP-fg)
- [ ] Get Stakeholder sign-off via the stakeholder meeting slide deck.
```

**Comment by ExperimentsInHonesty** [comment]
@jmeasow its for bugs as well.

**Comment by ExperimentsInHonesty** [comment]
I reviewed all the issues.  Made minor changes.  All looks good.  I am closing this issue.
