### ISSUE TITLE
Update all issue templates with staging deck links and resource links for related issues

### ISSUE THREAD

**Issue by jmeasow** [hackforla/tdm-calculator#1973]
### Overview
Update the issues in the issue templates with the staging deck links so that we can reduce the time it takes to make the staging deck every week, and so that we don't miss issues.

### Action Items

- [x] Go to the templates
- [x] Open all the templates
- [x] Add the text from template to each
- [x] Check to see if there is a slide in the Staging deck
   - [x] if not, create a slide in the appropriate section
- [x] Customize the issue with the URL from the deck 

### Resources
- [Project Board, Issue Templates]()
- [Staging Deck](https://docs.google.com/presentation/d/1crZ3IxqA4hAu3qzD7ns93Ieuqjwh6wyEtuX_46cP-fg)
- This issue is part of an epic https://github.com/hackforla/tdm-calculator/issues/1963

#### Sections
- Discussion Topics (product or research)
- Design Review (design)
- Updates to Review & Release (dev)

### Template
```
- [ ] Review with product and dev. Update if needed based on feedback
- [ ] Once finalized, add before and after images to the [staging deck on this slide]() 
   - [ ] if no slide has been made, make one in [the staging deck](https://docs.google.com/presentation/d/1crZ3IxqA4hAu3qzD7ns93Ieuqjwh6wyEtuX_46cP-fg)
- [ ] Get Stakeholder sign-off via the stakeholder meeting slide deck.
```

**Comment by Parisajf** [comment]
I updated all the templates.
