### ISSUE TITLE
Add a loading icon for the wizard. 

### ISSUE THREAD

**Issue by KPHowley** [hackforla/tdm-calculator#198]
### Overview
The wizard sometimes takes a long time to load initially, so we should add a loading icon or bar to notify users that nothing is wrong. 

### Action Items
- [x] add loading icon/bar

**Comment by nclairesays** [comment]
eta for now: end of saturday (maybe earlier)

**Comment by ExperimentsInHonesty** [comment]
@nclairesays please provide an update on this
1. Progress
2. Block
3. Availability
4. ETA
