### ISSUE TITLE
Implement Stable Sorting by Multiple Columns on the My Projects Page

### ISSUE THREAD

**Issue by entrotech** [hackforla/tdm-calculator#1981]
### Overview
Allow the user to sort by multiple columns on the My Projects Page, in order to sort by a "primary" column, then by a second "secondary" column among the projects with the same value for the primary column, then optionally by a third "tertiary" column among the projects with the same values for both primary and secondary columns, and so on.

### Details
To sort by three columns, the user sorts first by the "tertiary" column by selecting the sort order for that column, then sorts by the secondary column by selecting the sort order for the secondary column, and finally sorts by the primary column by selecting the sort order for the primary column.  This should work for as many sort levels as desired.  There is always at least one sort order (the default Date Modified, default to descending - most recent first). User-selected sort columns (if any) are then applied after the first sort order.

Another way to think of this is that the projects are sorted by a single column, then sorted again by a second column, that only re-orders rows with different values for the second sort criterion, otherwise, leaving the first sort intact. If you then sort by a third column it only re-orders rows with different values for the third column, otherwise leaving the first two sorts intact.  And so on...

Note that the **last** column you sort by is the **primary** sort criterion, consistent with other applications that allow multi-column sorting, like Google Sheets, Excel, etc. This is the more user-friendly option, as the primary use case for sorting is to sort by a single column and not care about secondary or previously specified sort orders.

For example, before the user specifies any sort order, projects are sorted by Date Modified, descending.  If the user then sorts by the Visibility column, with Visible projects first, the resulting sort is:

1. Sort by Visibility, Visible first, then
2. Among the projects with the same visibility, sort the projects by Date Modified, descending.

If the user then Sorts by Status, with Drafts First, the resulting sort will be:
1. Sort by Status, with Drafts first, then
2. Among the projects with the same Status, sort the projects by Visibility, with Visible first, then
3. Among projects with the same Status and Visibility, sort the projects by Date Modified, descending.

When you have sorted by multiple columns, our current UI design does not let you explicitly see the sort criteria for all the columns, but if you open the popup for the primary sort column, the popup will show the corresponding direction radio button as pre-selected. We could consider alternative UI designs that would expose the full sort criteria stack, if desired.

If you re-specify sorting for a column that is already among the sort criteria, it is removed from the existing stack of sort criteria and re-added to the end of the sort criteria with the specified direction.

If you use the "Reset Filters / Sort" button to clear the sort criteria, it returns to the default of sorting only by Date Modified, descending.

- Per Issue #1683, the entire stack of sort criteria are retained in session storage, so if you navigate away from the page, then return to the page later in the same browser session, the sort criteria will be what they were when you were last on the page.

### Action Items
- [x] Implement
- [ ] Review with product and dev. Update if needed based on feedback
- [x] Once finalized, add before and after images to the [staging deck on this slide]() 
   - [x] if no slide has been made, make one in [the staging deck](https://docs.google.com/presentation/d/1crZ3IxqA4hAu3qzD7ns93Ieuqjwh6wyEtuX_46cP-fg)
- [ ] Get Stakeholder sign-off via the stakeholder meeting slide deck.

**Comment by entrotech** [comment]
[Video](https://drive.google.com/file/d/1ZKPr-tbE8eyayp1wRSxkISqI6rj2sULA/view?usp=sharing)

**Comment by ExperimentsInHonesty** [comment]
Appeared in the [2024-12-03 Stakeholder deck](https://docs.google.com/presentation/d/1vc_LUPreHrToHBRGUekbXfLflOi3omt2Bo8M7uxMovI/edit#slide=id.g31a1cbf228f_0_62) and was approved.
