### ISSUE TITLE
Create a System architecture document 

### ISSUE THREAD

**Issue by KPHowley** [hackforla/tdm-calculator#203]
### Overview
The LA DOT / City  would like an document explaining the system architecture of the TDM calculator website.  They provided a sample document linked below. 

### Action Items
- [x] Create list of architecture components
- [x] Create list of data definitions 
- [x] Write description of architecture
- [x] Create diagram 
- [x] Write short  summary
- [x] Style

### Resources/Instructions
sample document: https://docs.google.com/document/d/1IsLLZvupKjiHyktfXPuImzFOjsskYICT84hqyTstZTk/edit?usp=sharing

**Comment by fyliu** [comment]
Link to document: https://docs.google.com/document/d/1lSOdgQTdqKYDZmX1QhMHqcslsmAngb7VAu3KiqKcaCI

**Comment by ExperimentsInHonesty** [comment]
@entrotech will write a paragraph of whats missing 
@KPHowley will style the doc
