### ISSUE TITLE
Develop Style guide

### ISSUE THREAD

**Issue by entrotech** [hackforla/tdm-calculator#21]
This is the UI/UX guide (probably wireframes) for the overall navigation and visual appearance of the site.

**Comment by dazainus** [comment]
Just to add in addition to @entrotech's comment.
 
### Overview
Develop a new design system to use going forward.

### Action Items

- [ ] Define a color guide
- [ ] Define a typography system
- [ ] Create key components

### Resources/Instructions
- Figma File: https://www.figma.com/file/qNgPc5lttpf0SWSwkbbWyT/TDM-Calculator?node-id=980%3A0

**Comment by KPHowley** [comment]
closed as there is a duplicate issue being worked on #972
