### ISSUE TITLE
Auto-generate release notes

### ISSUE THREAD

**Issue by fyliu** [hackforla/tdm-calculator#216]
### Motivation
Make it autogenerate to save time on releases.

### How
Use something like gren

### Tasks
- [x] autogenerate release notes

### Resources
- https://www.drupixels.com/blog/git-tags-guide-create-delete-push-tags-remote-and-much-more
- https://github.com/github-tools/github-release-notes

**Comment by fyliu** [comment]
I've been playing with generating release notes. See here: https://github.com/hackforla/tdm-calculator/releases
I changed the version tags to 0.x.0 to conform to semantic versioning
For the future (or even this release), we should put all the issues into milestones so that we can generate release notes for milestone v0.3.0, for example.
I'm not sure if there's significant value in generating changelog in addition to release notes. The upside is it's not difficult to do. I'm thinking that changelog would be generated from the commit messages rather than issue names.
Having to generate these documents would force github contributors to use better issue names and developers to write better commit message because they show up in release notes and changelogs.

**Comment by fyliu** [comment]
I made progress on this in a commit 38fee9b. This will need to be discussed to decide what to generate release notes from. I personally think release notes should be generated from issues and changelogs from commits.

**Comment by ExperimentsInHonesty** [comment]
@fyliu add documentation to the readme file including guidance for commit messages.  Add config file updates.
ETA is 2/14

**Comment by fyliu** [comment]
I'll have to work on the next week. ETA 2/25

**Comment by fyliu** [comment]
I didn't check in the changes for this because I thought this hasn't been maintained for a while. Looks like I was wrong.

The nice thing about this one is it has the flexibility to generate release notes from different data, such as issues, commits, milestones, PRs, and PRs with issues, as well as filtering and grouping items to list features and bugs in separate groups.

I still think we should look at a few different solutions before settling on one.

**Comment by fyliu** [comment]
The pull request should be good now.

For convenience, I added a script to generate release notes in package.json. It requires a package that needs to be installed but not included in package dependencies, because the project doesn't really depend on it. The "release manager" is the only one who needs to install it and that should be done globally. Instructions on installing the package and setting up the github token is in the contributing.md changes in the pull request.
