### ISSUE TITLE
Remove two items from the residential inputs page

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/tdm-calculator#217]
### Overview
Senior Independent Housing and Assisted Living Care Unit  will not be part of the calculations anymore.  We need to remove their corresponding inputs from the calculator.

### Action Items
Remove Senior Independent Housing and Assisted Living Care Unit from the residential inputs page.

### Dependancies
Issue #160 

### Resources/Instructions
![Screen Shot 2020-01-30 at 11 28 11 AM](https://user-images.githubusercontent.com/37763229/73483017-9e92f880-4353-11ea-8199-21f0f470a1de.png)

Rosemary's message on slack 
Rosemary McCarron  1/30/20 9:00 AM
...
Can you remove Senior Independent Housing and Assisted Living Care Unit from the residential inputs page? They were in the parking spreadsheet, but the TDM ordinance will not apply to them

**Comment by bfojas** [comment]
@ExperimentsInHonesty @fyliu @KPHowley @entrotech 

This is temporarily resolved and now a lower priority. I am moving it to the Ice Box.

**Comment by ExperimentsInHonesty** [comment]
@entrotech will look at a more permanent solution

**Comment by entrotech** [comment]
Closed by PR #239 (A hotfix that applies to production as well as staging)
