### ISSUE TITLE
Develop a react living style guide

### ISSUE THREAD

**Issue by entrotech** [hackforla/tdm-calculator#22]
### Overview
This is a developer task to create items in React Storybook that comprise a living style guide of components. This task is to establish a few examples to get started with storybook and unit testing for other devs to follow.

Subsequently, each feature that involves creating one or more component should also have one or more storied and unit tests created.

**Comment by entrotech** [comment]
Documented here: https://github.com/hackforla/tdm-calculator/blob/master/Contributing.md

**Comment by entrotech** [comment]
Closed by PR #247

**Comment by joelparkerhenderson** [comment]
Is Puppeteer in your mix? Busby on the gender-equity team is trying Puppeteer and so far it looks promising, especially for Chrome headless and Node.
