### ISSUE TITLE
Remove projects that start with the word test

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/tdm-calculator#220]
### Overview
In the process of fixing a bug we created a bunch of projects called test*.* and those all need to be removed before we give this to planning today at 2pm.

### Action Items
Remove the following projects from the database
test4 |   |   |   | Bonnie Wolfe | 01/30/2020 | 10:13 AM
test 14 | 13428 Maxella Ave | 6 | 1234 | Bonnie Wolfe | 01/30/2020 | 10:22 AM
test23 | 13428 Maxella Ave |   |   | Bonnie Wolfe | 01/30/2020 | 10:38 AM
test 26 | 13428 Maxella Ave |   |   | Bonnie Wolfe | 01/30/2020 | 11:41 AM
test29 | 13428 Maxella Ave |   |   | Bonnie Wolfe | 01/30/2020 | 11:59 AM
test30 | 13428 Maxella Ave |   |   | Bonnie Wolfe | 01/30/2020 | 12:24 PM
test31

### Resources/Instructions
![Screen Shot 2020-01-30 at 12 29 14 PM](https://user-images.githubusercontent.com/37763229/73487593-27159700-435c-11ea-8472-f33fe068f2bb.png)

**Comment by fyliu** [comment]
I remove these projects.
Tell me if any future projects need removing before the demo.

**Comment by fyliu** [comment]
Closing since the demo should be done by now.

**Comment by ExperimentsInHonesty** [comment]
The demo is a 30 day long process.

**Comment by ExperimentsInHonesty** [comment]
Left a message for Rosemary on the slack
Bonnie  1/30/20 1:07 PM
@Rosemary McCarron are there any test cases you want us to remove from the project list before your demo?

Didn't receive a response.  Sent email on 2/1/20 with this image
![Screen Shot 2020-02-01 at 11 26 06 AM](https://user-images.githubusercontent.com/37763229/73597880-eea1c480-44e5-11ea-8d6a-3edb03d0aa06.png)

**Comment by ExperimentsInHonesty** [comment]
Rosemary said yes, delete these three indicated above

**Comment by entrotech** [comment]
Done
