### ISSUE TITLE
Request for calculation rule

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/tdm-calculator#221]
### Overview
A calculation rule to be implemented that caps the value that development can receive when two strategies are both checked.

### Action Items
See the snipit from slack below:
Discuss challenges and if we are waiting for John before we tackle.

### Resources/Instructions
snipit from slack
Rosemary McCarron  7 minutes ago
This is not an immediate concern, but Education, Marketing, Outreach, and Voluntary Travel Behavior-Change Program should be mutually exclusive because one is a less intensive version of the other. We still want the option for users to select both because Education, Marketing, Outreach is part of the packages. But if both are selected, the total earned points should be 6, not 10.

Rosemary McCarron 
(discussed with John at a Hack night)
![image (7)](https://user-images.githubusercontent.com/37763229/73489597-b2dcf280-435f-11ea-8e9c-9786dcf31f57.png)

Bonnie  
@Rosemary McCarron thanks for the clarification.  We will work on that, but it won’t be available today.

**Comment by ExperimentsInHonesty** [comment]
After discussion with team, it's clear we need more guidance from Rosemary about how we would communicate this combo to stake holders.   Invite Rosemary to review in person with us.

pending to do  - Send email to Rosemary with optional dates.

**Comment by ExperimentsInHonesty** [comment]
Sent Rosemary an email on 2/1.  Just heard back on 2/6 saying she would get back to next us.

**Comment by ExperimentsInHonesty** [comment]
Applied the formatting that we had approved on other pages.  Still keeping the drawers design for potential future iterations.
![Screen Shot 2020-02-08 at 10 09 22 AM](https://user-images.githubusercontent.com/37763229/74089941-1a2f2c80-4a5b-11ea-800d-a74a168386ca.png)

**Comment by entrotech** [comment]
I implemented this a bit differently than Bonnie envisoned, by changing the Education, Marketing and Outreach Strategy into a multiple-choice strategy with the options of "none" 0 pts, "Basic" 4 pts or "Voluntary Behavior Change Program". Then dropped the separate strategy called "Voluntary Behavior Change Program".

This is a database-only change - no PR required.

**Comment by fyliu** [comment]
Note from zoom meeting: the package selection buttons is not affecting this field correctly.
