### ISSUE TITLE
Implement Required Field Validation

### ISSUE THREAD

**Issue by fyliu** [hackforla/tdm-calculator#224]
### Overview
Implement a better solution for the #218 required input fields fix.
The fix used an asterisk ending in the field name to denote required fields, but a database column is better for the long term.

### Action Items
- [x] add required column to CalculationRule table for input rules
- [x] set Project Name and Address to required

- [x] Modify CalculationRule_Select* stored procedures to return the required column value.

- [ ] switch to the new way of checking required inputs

**Comment by entrotech** [comment]
Implemented database changes before splitting production and staging databases.

**Comment by ExperimentsInHonesty** [comment]
@fyliu can you and @entrotech talk about next steps on this.
