### ISSUE TITLE
Create staging database

### ISSUE THREAD

**Issue by bfojas** [hackforla/tdm-calculator#228]
### Overview
Create a staging database to separate functionality of master and staging apps.

### Action Items

- [ ] Create database instance

- [ ] Migrate/Export current master database

- [ ] Change environment variables in staging heroku app to connect to the staging database.

- [ ] See issue #229 Develop and implement version control

**Comment by bfojas** [comment]
Current issues that need clarification: 

- SQL Server management studio can migrate/export the tables, but does not keep the id/identity column consistent with the original db unless the identity constraint is removed, but removing the constraint creates a null id for insert statements.

- Foreign key constraints on CalculationRuleCalculation table prevent simple copying of rule sets. Rules need to be inserted in a specific order, otherwise they break the constraints and the insert fails.

**Comment by entrotech** [comment]
Implemented on 2/18. Need to get developers to chenge their .env file database name. No code changes or PR.

**Comment by KPHowley** [comment]
@fyliu - I think this should be designated as a system update for the release, can we update?
