### ISSUE TITLE
Develop and implement version control

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/tdm-calculator#229]
### Overview
Develop version control practices/processes for iterating changes on both master and staging.

### Action Items

- [ ] Discus options with John, and get recommendation
- [ ] Writeup proposal with steps (as google doc linked to this issue, or in this issue itself if short) and disseminate among the team for feedback.
- [ ] Address feedback
- [ ] Write up next next steps
- [ ] Discuss with PM allocation of tasks
- [ ] etc.

**Comment by fyliu** [comment]
There's a system called semantic versioning ([semver](https://semver.org/)) that John and I were following. See [Contributing.md](https://github.com/hackforla/tdm-calculator/blob/develop/Contributing.md) for release tagging procedure although it needs updating.

#216 depends on this
