### ISSUE TITLE
run a code auto-formatter on commit to reduce code churn

### ISSUE THREAD

**Issue by fyliu** [hackforla/tdm-calculator#230]
Auto-format code on commit according to some basic standard.

This should be according to prettier with default options since that's what we've been doing so far.

**Comment by fyliu** [comment]
I added this to a commit 5cdd759 using prettier, lint-staged, and husky.

**Comment by ExperimentsInHonesty** [comment]
This needs another developer to check this.

**Comment by entrotech** [comment]
Made slight change to lint0staged configuration in package.json to prevent warning about extra "git add" command when committing.

**Comment by entrotech** [comment]
Closed PR #245
