### ISSUE TITLE
Refactor Wizard to use react-router to render steps

### ISSUE THREAD

**Issue by bfojas** [hackforla/tdm-calculator#232]
### Overview
Refactor the wizard to use react router rather than a large ternary.

### Action Items
- Create components for each step in the wizard.
- Refactor wizard logic to step based on route

**Comment by ExperimentsInHonesty** [comment]
@bfojas @mmorgs is this a dependency for Issue #209.  If yes, please post something on that issue about it (and here too) , and move the issue to the icebox.  When this issue is complete, that other issue can be moved back into prioritized backlog.

**Comment by ExperimentsInHonesty** [comment]
@bfojas decided not to use React router.  Instead we changed each of the steps into their own component using a switch statement instead of the ternary.

**Comment by bfojas** [comment]
Closed with PR #249
