### ISSUE TITLE
Set up to run code linter at checkin.

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/tdm-calculator#235]

**Comment by fyliu** [comment]
I have a branch setup to run the recommended linter rules for es6 and react on checkin.
**Lint-staged** runs the linter on only the staged files.
**Husky** runs commands in the pre-commit hook.
**Lerna** is a tool that manages multi-project projects.
https://github.com/hackforla/tdm-calculator/tree/eslint
