### ISSUE TITLE
Make checking at least one option on page 2 of the Wizard Mandatory

### ISSUE THREAD

**Issue by KPHowley** [hackforla/tdm-calculator#242]
### Overview
Before going past we need to make sure the user selects at least one option on the "What kind of development is your project?" page so we don't display a black page or forever spinning wheel. 

### Action Items
-[] Make pressing forward disabled until an option is chosen
-[] Add "* please select at least one option"

**Comment by bfojas** [comment]
Page 1 validations need to match page 2 validation. Decision is to keep the 'next' button active, but display warning instead of moving to next page when validations fail

**Comment by entrotech** [comment]
@bfojas  Don't know what work has been done on this, but I provided a proposed implementation as part of PR #272.
