### ISSUE TITLE
Updated Stakeholder Revisions 

### ISSUE THREAD

**Issue by KPHowley** [hackforla/tdm-calculator#253]
### Overview
Get an updated list of revisions and features from our stakeholder, broken down through the  MoSCoW method.

### Action Items
- Create list of wanted features and revisions 
- Breakdown through the MoSCoW method

### Resources/Instructions
Spreadsheet:
https://docs.google.com/spreadsheets/d/1Z2MyLYZAzz2yjTbB1v7F5ycg4kic0Al030VNWQrZLkY/edit?usp=sharing

MoSCoW Framework:
https://en.wikipedia.org/wiki/MoSCoW_method

**Comment by ExperimentsInHonesty** [comment]
see spreadsheet for status of issues

**Comment by KPHowley** [comment]
Updated again on 12/26 with More issues. Closing ticket.
