### ISSUE TITLE
Add basic responsiveness to the sidebar & horizontal resizing 

### ISSUE THREAD

**Issue by KPHowley** [hackforla/tdm-calculator#258]
### Overview
When horizontally resizing the webpage the wizard content shrinks while the sidebar stays the same.

### Action Items
- allow the sidebar to resize once the wizard content begins to be hidden
- add a break point to move the sidebar to the bottom.

**Comment by ExperimentsInHonesty** [comment]
Hi @lemazza Can you give us an update on this.  Hope you are ok!
1. Progress
2. Blocks
3. Availability
4. ETA
