### ISSUE TITLE
re-factor rule input types

### ISSUE THREAD

**Issue by mmorgs** [hackforla/tdm-calculator#259]
create NEW components, keep separate from rule input files to prevent breaking calculations

**Comment by ExperimentsInHonesty** [comment]
Hi @mmorgs Can you give us an update on this.  Hope you are ok!
1. Progress
2. Blocks
3. Availability
4. ETA

**Comment by ExperimentsInHonesty** [comment]
@mmorgs is this still necessary.  John did some work in this area.  Please confer and let us know if we can close as duplicate or no longer necessary.

**Comment by entrotech** [comment]
Implemented on a different issue
