### ISSUE TITLE
Create a CRUD feature for an admin to enter and maintain a list of frequently asked questions.

### ISSUE THREAD

**Issue by entrotech** [hackforla/tdm-calculator#26]
### Overview 
Provide a page for a user with the admin role to view a list of FAQs, create new ones and edit existing ones.
### Action items
- [x] Creating the crud feature
- [ ] Design the React Components for listing existing FAQs
- [ ] Design React Form(s) for Adding and Editing an FAQ and connect with the list.
- [ ] Add appropriate menu items which are enables only for an admin user.

**Comment by kkchu791** [comment]
I'm interested to take this one on.

**Comment by nicholaspung** [comment]
Sent a PR. Feature done!

**Comment by nicholaspung** [comment]
Front End
- Display FAQs with update/delete functionality
- Able to add FAQs

**Comment by ExperimentsInHonesty** [comment]
Needs to be integrated.  new issue will be created

**Comment by KPHowley** [comment]
closed as we have duplicate issues for FAQ screen  #76 and #42 and #604
