### ISSUE TITLE
Add babel-eslint

### ISSUE THREAD

**Issue by fyliu** [hackforla/tdm-calculator#266]
### Overview
TdmCalculationContainer.js fails eslint right now because it is using a javascript syntax not yet recognized by eslint. Babel-eslint is the way to fix it.

Continuation of #262 . 

### Resources/Instructions
https://stackoverflow.com/questions/42701440/eslint-parsing-error-unexpected-token-error-for-assigned-fat-arrow-prop
https://stackoverflow.com/questions/34244888/how-do-i-configure-eslint-to-allow-fat-arrow-class-methods
https://medium.com/@chestozo/fixing-eslint-no-invalid-this-error-for-fat-arrow-class-methods-a56908ca8bb6

**Comment by bfojas** [comment]
Eslint failure was corrected by changing the TdmCalculationContainer to a functional component. Issue is returned to the backlog, because adding babel-eslint to he project should still be considered.

**Comment by ExperimentsInHonesty** [comment]
its no a priority right now.

**Comment by KPHowley** [comment]
@fyliu  - Is this still needed?

**Comment by fyliu** [comment]
@KPHowley It's been too long. I'm not sure. We should close it.
