### ISSUE TITLE
Tests: Develop new cypress tests for each use case

### ISSUE THREAD

**Issue by KPHowley** [hackforla/tdm-calculator#269]
### Overview
Write test cases in Cypress for each of the LA DOT use  cases.

### Action Items

- [x] Barrington Condos
- [x] Beatrice Building
- [x] Clarendon Apartments
- [x] Fountain Apartments
- [x] Jewish Family Service - Social Services Center
- [x] Victory Hotel 
- [x] Marina Towers Village

**Comment by nclairesays** [comment]
Finished integration tests for the 7 example test cases listed:
 Barrington Condos
 Beatrice Building
 Clarendon Apartments
 Fountain Apartments
 Jewish Family Service - Social Services Center
 Victory Hotel
 Marina Towers Village
