### ISSUE TITLE
Allow normal users to see only their own projects

### ISSUE THREAD

**Issue by entrotech** [hackforla/tdm-calculator#275]
A non-admin user should only be able to see their own saved projeccts.
An admin user should be able to see all projects (eventually only projects that have been submitted, but for now, we don't have such a thing as a submitted status).
Whether or not a user has the "security admin" role does not affect which projects they can see or work with.

**Comment by entrotech** [comment]
This would be partially implemented on the Projects page, in that the list there would only show user the projects they can view or edit.  However, if a user attempts to go to the Project page for a project they do not have any access to, they should be re-directed to somewhere sensible (the Projects page?).
We also need to work on locking down the web API based on the user's roles, such that they can only get projects that they can at least view, and they can only update the projects they are allowed to edit.  But the details kind of depend on how we implement "organizations" as well.

**Comment by ExperimentsInHonesty** [comment]
@bfojas Can you give us an update on this.  Hope you are ok!
1. Progress
2. Blocks
3. Availability
4. ETA

**Comment by fyliu** [comment]
2/18 meeting John says the stored procedure call should include a user id (either owner of the project or have admin rights)
What about visibility for organization?(see also other projects in the same org)

**Comment by entrotech** [comment]
Duplicate of #309

**Comment by entrotech** [comment]
PR #310

**Comment by entrotech** [comment]
Most of this is done, just need to modify the TdmCalculationWizard so that if the route takes the user to a route for a project that the user does not have access to, they get redirected to somewhere else sensible, rather than just seeing the wizard with a loading spinner.
