### ISSUE TITLE
Create Agenda for Aug 6

### ISSUE THREAD

**Issue by Rankazze** [hackforla/tdm-calculator#28]
### Overview
Gather all items team members want to propose for this weeks' agenda.

### Action Items
REPLACE THIS TEXT -If this is the beginning of the task this is most likely something to be researched and documented.

REPLACE THIS TEXT -If the issue has already been researched, and the course of action is clear, this will describe the steps.  However, if the steps can be divided into tasks for more than one person, we recommend dividing it up into separate issues, or assigning it as a pair programming task.

### Resources/Instructions
REPLACE THIS TEXT -If there is a website which has documentation that helps with this issue provide the link(s) here.

**Comment by entrotech** [comment]
I think one major objective of the meeting should be to identify actionable issues for developers to work on.  At this point, the development is sort of ahead of the requirements gathering and UI/UX tasks, so developers may need to work on issues that are more research and requirements analysis than coding, but that's kind of where we need the most effort at this point.  I will be out for the next three weeks, so I want to have enough issues in pipe to keep s/w developers going and talk about who should fill in for me with respect to approving pull requests, etc.
