### ISSUE TITLE
New data fields: City Planning Case Number and LADOT Case Number

### ISSUE THREAD

**Issue by KPHowley** [hackforla/tdm-calculator#280]
### Overview
We need to make two case number fields for input, a City planning case number and a LADOT case number

- Change in database
- Make the two data types display on page 1

**Comment by entrotech** [comment]
Looks good to me!

**Comment by KPHowley** [comment]
Ready for Client Release:
![Uploading Screen Shot 2020-03-30 at 9.07.03 PM.png…]()
