### ISSUE TITLE
Commercial Package should not display when only residential land uses are selected

### ISSUE THREAD

**Issue by entrotech** [hackforla/tdm-calculator#283]
The commercial package button is already hidden if only the Residential Land Use is selected.  At present, if only Residential and/or Hotel land uses are selected, the Commercial Package Button is hidden, but this is controlled by the requirements ab out which strategies apply to each land use per this spreadsheet [Strategies - Land Use spreadsheet](https://docs.google.com/spreadsheets/d/1_VjRefk_7ch-eqIHK_gHIUXwcTYtvM0FO07K7gaqKGg/edit#gid=0)

Specific Details:
The commercial package includes these strategies:

- Bike Parking,
- Education, Marketing, Outreach or Voluntary Behavior-change Program, and 
- Parking Cash-Out

Referring to the  [Strategies - Land Use spreadsheet](https://docs.google.com/spreadsheets/d/1_VjRefk_7ch-eqIHK_gHIUXwcTYtvM0FO07K7gaqKGg/edit#gid=0) , the first two of these are applicable to all land uses.

Since Parking Cash-out is not applicable to Residential or Hotel Land Uses, but applicable to all other land uses (Retail, Commercial, Institutional, School, Other and Major Development), the commercial package is currently applicable to all land uses to which Parking Cash-Out applies. The system already hides the Commercial Package button when only Residential and/or Hotel land uses are selected.

Maybe what you are asking for is to change the requirements such that parking cash-out is applicable to Hotels? If so, we should update the spreadsheet and then will make the change to the visibility settings for the Parking Cash-Out to show it for Hotels, which will, in turn enable the Commercial Package for Hotels.

**Comment by fyliu** [comment]
This is the land use selections and corresponding package selection button showing on https://tdm-calc.herokuapp.com
<img width="933" alt="Screen Shot 2020-03-14 at 10 56 33 AM" src="https://user-images.githubusercontent.com/1160105/76687603-a8f71200-65e2-11ea-9be6-4e20f6a48f50.png">
<img width="928" alt="Screen Shot 2020-03-14 at 10 56 46 AM" src="https://user-images.githubusercontent.com/1160105/76687604-ab596c00-65e2-11ea-91e5-030f90d57bb9.png">

**Comment by fyliu** [comment]
@entrotech said he was not able to find anything wrong with it. See screenshots.
Can we get more specific information on what the bug is?
1. user action
2. expected behavior
3. actual behavior
