### ISSUE TITLE
Transportation Demand Strategies: Display only strategies applicable to selected land uses

### ISSUE THREAD

**Issue by KPHowley** [hackforla/tdm-calculator#285]
### Overview
Compare the Strategies on the spreadsheet vs what is on the site, to make sure only applicable strategies are shown. 

Spreadsheet:
https://docs.google.com/spreadsheets/d/1_VjRefk_7ch-eqIHK_gHIUXwcTYtvM0FO07K7gaqKGg/edit#gid=0

**Comment by KPHowley** [comment]
@entrotech  - I double checked this and found a few inconsistencies between whats show on the site and the spreadsheet. 

I notated them all on the bottom of the original spreadsheet: https://docs.google.com/spreadsheets/d/1_VjRefk_7ch-eqIHK_gHIUXwcTYtvM0FO07K7gaqKGg/edit#gid=0

Let me know if you can check or fix them, or if you have any questions or issues.

**Comment by entrotech** [comment]
Updates per Kevin's notes on the spreadsheet - no PR required.

**Comment by entrotech** [comment]
NOTE: This also included adding a Telecommute strategy:

![image](https://user-images.githubusercontent.com/9939032/77854306-67e42d80-719e-11ea-8c0c-3af63ad7dfe8.png)
