### ISSUE TITLE
Refactor: Fix NPM package vulnerabilities

### ISSUE THREAD

**Issue by entrotech** [hackforla/tdm-calculator#287]
Running npm i on client and server shows over 40,000 npm package vulnerabilities.  Run npm audit on both and attempt to resolve any issues.

**Comment by ExperimentsInHonesty** [comment]
This issue requires someone very experienced with React

**Comment by fyliu** [comment]
I made as much progress as I could at this point.
These are the remaining ones:
- 1 high severity vulnerability is not yet patched. Times 5 places in storybook that depends on it.
- 1 low severity that's patched but the newest react-scripts has not moved to the patched version of the package
