### ISSUE TITLE
Transportation Demand Strategies: strategy details displayed by info button or hover

### ISSUE THREAD

**Issue by KPHowley** [hackforla/tdm-calculator#294]
### Overview
 The LA DOT will be updating HfLA with information about each Strategy.  This needs to be added to the Strategies page via a tool tip, link, or some other way (TBD). 

### Action Items
- [x] LADOT: provide update descriptions and strategies spreadsheet
- [x] Designs Mockups
- [x] Decide on implementation
- [ ] Implement in the front end 
 
### Resources
Current Descriptions: https://docs.google.com/spreadsheets/d/1gyp3Cg24InPbin2LqMhbHoI7tmYRpKvg/edit#gid=1029793026

**Comment by ExperimentsInHonesty** [comment]
@ramccarr  can we get updated info about the strategies for the tool tips

**Comment by ramccarr** [comment]
The most recent info is here: https://docs.google.com/spreadsheets/d/1LBGlYyj3kiRb9p0UNCWRo9DZVRFAFNEeccCjkCT5jek/edit

**Comment by ExperimentsInHonesty** [comment]
@KPHowley @dazainus are going to meet to discuss how this would get implemented.
@entrotech is going to work on backend.

**Comment by entrotech** [comment]
@KPHowley  @ExperimentsInHonesty @ramccarr @Dsomers74 Just to get this started, I did all the back-end work for this, and I'm currently showing the descriptions as a tooltip.  We can change how the info is displayed in the UI, or just pretty-up the tooltip.
![image](https://user-images.githubusercontent.com/9939032/79090099-69b10380-7cfd-11ea-852f-0f97cc1e3516.png)

**Comment by entrotech** [comment]
Fixed tooltip maxwidth with styling:
![image](https://user-images.githubusercontent.com/9939032/79394766-1e7d3780-7f2d-11ea-9695-9af9383e392e.png)

**Comment by dazainus** [comment]
### Overview
Design tooltips 

- [ ] 3 mockup designs

#### DESIGN 1
![Screen Shot 2020-04-15 at 7 02 32 PM](https://user-images.githubusercontent.com/55513459/79406456-fb15b500-7f4b-11ea-8441-214f1f39e071.jpg)

#### DESIGN 2
![Screen Shot 2020-04-15 at 7 03 57 PM](https://user-images.githubusercontent.com/55513459/79406459-ff41d280-7f4b-11ea-9cd7-e051009bc13d.jpg)

#### DESIGN 3
No initiation:
![Screen Shot 2020-04-15 at 7 04 23 PM](https://user-images.githubusercontent.com/55513459/79406471-0cf75800-7f4c-11ea-8717-90c202e43057.jpg)

Mouse hover:
![Screen Shot 2020-04-15 at 7 04 37 PM](https://user-images.githubusercontent.com/55513459/79406475-0f59b200-7f4c-11ea-87de-41aefa8ecd87.jpg)


### Resources
https://www.figma.com/file/qNgPc5lttpf0SWSwkbbWyT/TDM-Calculator?node-id=1126%3A377

**Comment by KPHowley** [comment]
@ramccarr and @Dsomers74 - We would love your opinion on these three options for the final implementation of the tool tips for this page. The team discussed this on Wednesday and felt that option 2 was our favorite, but we'd love your opinion as well.

We would also like to set standard buttons and icons throughout the wizard, so hopefully this can can a standard for tool tips elsewhere,  however that can be discussed further later as well.

**Comment by Dsomers74** [comment]
I like option 2 as well.

**Comment by dazainus** [comment]
@Dsomers74 - great to hear your feedback.

Shared here is an improved version of OPTION 2.
#### Improvements
- The 'information' icons from the dashboard on the left has been changed due to poor visibility (green outlined -> green solid).

![Screen Shot 2020-04-17 at 5 43 09 PM](https://user-images.githubusercontent.com/55513459/79624147-bff2bd80-80d4-11ea-9fe0-8346b0954f6d.jpg)

**Comment by KPHowley** [comment]
@dazainus will update with a design without tool tip icons, definitions that display on hover, and one question mark at the top of the page that explains that tool tips will appear on hover. 

We will send to David for approval and then move to front end for implementation. Implementation will include redesign of tool tip box as well.

**Comment by dazainus** [comment]
### Revised Design Outlines
- Tool tip icons are removed.
- Information about the tool tip feature is inserted.

#### Before mouse hover:
![OPTION5-TDM-tooltip](https://user-images.githubusercontent.com/55513459/80047195-9fa27480-84c1-11ea-83a2-68f2708f2438.jpg)

#### When mouse hovers & tool tip popup is active:
![OPTION5-TDM-tooltip-hover](https://user-images.githubusercontent.com/55513459/80047199-a29d6500-84c1-11ea-886c-c26c6cd2541a.jpg)

**Comment by KPHowley** [comment]
After meeting with LADOT on 4/28 we have determined that we want to go ahead with the tool tips in a slightly different way:

- We want tool tips to be displayed by hover without any icons.
- When a user first comes to the screen a message should be displayed with a "?" icon that lets them know that tool tips will be displayed by hovering over titles
  - This should be a dismiss able notification the shrinks into the "?" icon when the user clicks a "x" that is displayed in the message
  - After the user dismisses this message the first time is should no longer be displayed to the user unless they click on the "?" again

@dazainus

**Comment by dazainus** [comment]
@KPHowley - Made a simple design mockup reflecting the comments above. We can test this during our meeting tonight and address further changes.

#### Screenshots
![Screen Shot 2020-04-29 at 3 29 47 PM](https://user-images.githubusercontent.com/55513459/80653262-a3d51180-8a2e-11ea-838c-5fd220ac2f93.jpg)

![Screen Shot 2020-04-29 at 3 29 38 PM](https://user-images.githubusercontent.com/55513459/80653268-a8012f00-8a2e-11ea-819d-6ec7a6442e3a.jpg)


#### Interactive Prototype
https://www.figma.com/proto/qNgPc5lttpf0SWSwkbbWyT/TDM-Calculator?node-id=1439%3A0&viewport=-5893%2C-2164%2C1&scaling=min-zoom

**Comment by ExperimentsInHonesty** [comment]
Hi @dazainus   On this live site, here is what the side pannel looks like, vs your mockup

![Screen Shot 2020-04-19 at 3 46 39 PM](https://user-images.githubusercontent.com/37763229/80657552-bfddb080-8a38-11ea-9e46-e7e26680722c.png)

see the green question marks?  They are the same color as the navigation to indicate that they are clickable.  Can we make the question mark on your mockup above emulate that?

**Comment by dazainus** [comment]
Sure, I can update the design mockup accordingly.
@ExperimentsInHonesty - Just to be on the clear side, please confirm that below is what you indicated.

1) we still want the '?' marks on the side widget (as shown in the image from your previous comment).
2) For the body text area the big '?' icon will reflect the same yellow-green color as the ones from the side widget.

**Comment by dazainus** [comment]
By the way, I want to address the accessibility issue before making any adjustment on the design. Our site should meet WebAIM's accessibility guideline in attempts to make all letters legible. Currently, some of the elements do not qualify for the color contrast measures. For example, the '?' element with white letter on yellow-green background color fails the accessibility contrast test. 

**Consequently, we should change the white letter to darker color to meet the WebAM's accessibility guideline.** I did the contrast tests on current color combination and another option as my recommendation. Please see below screenshots for WebAIM color contrast test results (https://webaim.org/resources/contrastchecker/):

#### Current : Fails to meet WebAIM contrast guideline
![screencapture-webaim-org-resources-contrastchecker-2020-04-29-17_00_14](https://user-images.githubusercontent.com/55513459/80659210-22d14680-8a3d-11ea-9775-55a16ea3f94c.png)

#### Suggested : Has better color contrast between the letter against the background
![screencapture-webaim-org-resources-contrastchecker-2020-04-29-17_00_28](https://user-images.githubusercontent.com/55513459/80659256-485e5000-8a3d-11ea-932b-9d845bd6aa21.png)

**Comment by KPHowley** [comment]
ETA UPDATE: Diane will make mock up by by 4/6, and move this to development. Design will be implemented by 4/12.

**Comment by dazainus** [comment]
@KPHowley @ExperimentsInHonesty Below are the screenshots and prototype for the design reflecting previous feedback.

### Screenshots
1. Initial screen: notification is shown.
![OPTION 6  tooltip-pop-up copy](https://user-images.githubusercontent.com/55513459/80896403-5cef5200-8ca2-11ea-8b4f-52637401c919.png)

2. Press close button: notification disappears into '?' icon
![OPTION 6  tooltip-pop-up-2 copy](https://user-images.githubusercontent.com/55513459/80896404-5f51ac00-8ca2-11ea-8fc7-4eb2fec78aa5.png)

3. Press '?' button: pops up the notification
![OPTION 6  tooltip-pop-up copy](https://user-images.githubusercontent.com/55513459/80896405-611b6f80-8ca2-11ea-891f-daf1ddf6f70b.png)

### Prototype
Use this like to access the working prototype:
- https://invis.io/X4X4ISCYPCJ

### Resources
- Figma file: https://www.figma.com/file/qNgPc5lttpf0SWSwkbbWyT/TDM-Calculator?node-id=1444%3A2572

**Comment by Dsomers74** [comment]
Looks great @dazainus. The collapsable pop-out reflects what we discussed.

**Comment by ExperimentsInHonesty** [comment]
This is ready for development: https://github.com/hackforla/tdm-calculator/issues/294#issuecomment-623038773

**Comment by KPHowley** [comment]
Eta to push this: 5/9

**Comment by lemazza** [comment]
updating the current status ahead of the Tuesday meeting: 

Still need to fix the vertical space left when the infobox is closed, and keep the box closed on return if the user has closed it before

![tdm294](https://user-images.githubusercontent.com/32402365/81658615-c9c6c280-93ed-11ea-9b14-a130e50d25e3.gif)

![issue-294-infobox-closed](https://user-images.githubusercontent.com/32402365/81657065-6ee09b80-93ec-11ea-9c46-acecd3a85e56.jpg)

![issue-294-infobox-open](https://user-images.githubusercontent.com/32402365/81657068-6f793200-93ec-11ea-91b5-a2165de5db48.jpg)

**Comment by KPHowley** [comment]
Closing this pending acceptance of pull request #294
