### ISSUE TITLE
Land use Page: Definition of each type of land use displayed

### ISSUE THREAD

**Issue by KPHowley** [hackforla/tdm-calculator#295]
### Overview
The LADOT will supply us with detailed definitions of each land use type. these need to be added to the Land use selection page, via tooltip, link or some other method. 

### Action Items

- [ ] LADOT: Update us with Each type of Land use
- [ ] determine best way to display based on length
- [ ] implement in front end

**Comment by ExperimentsInHonesty** [comment]
@ramccarr are you able to provide detailed definitions of each land use type.

**Comment by ExperimentsInHonesty** [comment]
@Dsomers74 either you or rose to provide detailed definition of each land use type.

**Comment by KPHowley** [comment]
After redesigning the pages of the wizard, we will no longer need this.
