### ISSUE TITLE
Allow sharing of permissions by organization

### ISSUE THREAD

**Issue by KPHowley** [hackforla/tdm-calculator#296]
### Overview
We need to add "Organization" as data field in account creation to allow permissions to edit projects to be shared by an organization.

### Action Items

- [ ] Identify what needs to happen for user profiles, what are the likely scenarios requiring profile update at an organization level or manage projects
- [ ] Interview user stakeholder organizations (developers, expediters, etc [the IT people at their organizations]) ask them how they would like manage their organization's accounts in the TDM application
- [ ] Determine method of implementation 
   - [ ] Consider Build LA account features

**Comment by Biuwa** [comment]
**2023-04-04 TEAM MEETING NOTES:**

Users should be able to delete themselves from a project, and also be able to transfer projects to a second primary user.
During Sign on, creating a profile,  we should have a section that asks if its a business or personal account to be able to capture the right username.

**Comment by entrotech** [comment]
I created a document with suggested use cases [here](https://docs.google.com/document/d/1Xy9n0A4Xw3HYJncVW0Gz9hQ9zYf9EAUWvQer0vY5nFU/edit?usp=share_link).

**Comment by Biuwa** [comment]
**2023-05-02 Stakeholder meeting Notes** 

We will talk with users to find out the needs for provisioning and transferring ownership. 

Emily is going to put together a list.
