### ISSUE TITLE
Admin ability to override points for a specific case.

### ISSUE THREAD

**Issue by KPHowley** [hackforla/tdm-calculator#297]
### Overview
Admin ability to override points for a specific case

### Action Items

- [x]  Determine intended functionality with LADOT

**Comment by ExperimentsInHonesty** [comment]
@ramccarr Does Issue #318  address Admin ability to override points for a specific case?  Or is it still wanted?

**Comment by ramccarr** [comment]
Yes, we do not need a point override. We can use this user defined field to make adjustments if necessary.

**Comment by KPHowley** [comment]
Addressed by issue #318,
