### ISSUE TITLE
Create E2E test on project user flow

### ISSUE THREAD

**Issue by nclairesays** [hackforla/tdm-calculator#303]
Create end-to-end (Cypress) tests around a user's workflow in regards to projects.  This entails:
1. Navigating to an existing project (after logging in)
2. Create a new project, saving it, and seeing it displayed in /projects
3. Updating an existing project

Note:
- These tests will programmatically log in (ie. does not include logging in via UI, which is covered by other tests)
- When updating an existing project, that project will be programmatically created/seeded beforehand. Test will only test the updating functionality with UI. 
- Because these tests are using a real database (ie projects will actually get created in the db), this means that created test projects should be deleted before each running test in order to clean up state/data

Blockers: 
- This issue relies on a DELETE api endpoint in order to delete data and reseed new data. (#302)

**Comment by ExperimentsInHonesty** [comment]
@nclairesays is going to make it automatically delete the test projects when testing is done.

**Comment by nclairesays** [comment]
Update:
Previously blocked on Wednesday and was able to figure that out and am moving forward. Hopefully will be done by next meetup.

**Comment by nclairesays** [comment]
Update: Was able to unblock something I was stuck on regarding cypress closures but still blocked on my ability to get from /api/projects as discussed on Wednesday

**Comment by nclairesays** [comment]
I've updated the description and title of the issue to better match what I've been working on

**Comment by ExperimentsInHonesty** [comment]
@fyliu will review
