### ISSUE TITLE
Add E2E test for login

### ISSUE THREAD

**Issue by fyliu** [hackforla/tdm-calculator#306]
Integration/E2E test:
- [x]  Write cypress test -- visit app, login, validate that you can see your name [Louis]
- [x]  Add cypress helper to auto login as different types of users (regular, admin, security admin) [Claire]
- [x] valid login (Cypress automatically adds cookies in the browser) [Claire]
- [x] invalid login with wrong password [Claire]

*does not include unit tests anymore*

**Comment by fyliu** [comment]
I had trouble mocking async code and tried jest/enzyme and react testing library. React testing library seems to do the trick. I still need to add the actual tests. This should be done by Wednesday if no other issues come up.

**Comment by nclairesays** [comment]
Cypress tests in progress. Adding edge cases for what happens during failed login attempts. Eta hopefully Wednesday also. 

@fyliu you can try mocking out async calls using the nock library

**Comment by fyliu** [comment]
I checked that this works and the code looks good.
