### ISSUE TITLE
Redirect to Projects screen if user tries to access a project they are not allowed to.

### ISSUE THREAD

**Issue by bfojas** [hackforla/tdm-calculator#313]
### Overview

Redirect to new project if user tries to access a project they are not allowed to.

### Action Items

- [ ] Change the redirect for blocked project routes

**Comment by ExperimentsInHonesty** [comment]
@bfojas have you had a chance to do any work on this?

**Comment by KPHowley** [comment]
@bfojas - just wanted to check back and see if you had been able to work on this at all!

**Comment by fyliu** [comment]
Accessing an unauthorized project:
signed in - go to projects page to choose project
not signed in - go to start new project

**Comment by KPHowley** [comment]
@lemazza - For this we would like the message to say "The project you are trying to view can only be viewed by the user"
