### ISSUE TITLE
UI/UX: Develop a Design System

### ISSUE THREAD

**Issue by KPHowley** [hackforla/tdm-calculator#314]
### Overview
Develop a new design system to use going forward.

### Action Items

- [ ] Define a color guide
- [ ] Define a typography system
- [ ] Create key components

### Resources/Instructions
- Figma File: https://www.figma.com/file/qNgPc5lttpf0SWSwkbbWyT/TDM-Calculator?node-id=980%3A0

**Comment by SMR9220** [comment]
@ExperimentsInHonesty Should the role for this issue be development? Or have these designs systems already been created/implemented into the application, and this issue can be closed?

**Comment by ExperimentsInHonesty** [comment]
@mojimoh & @Biuwa The design system will be made by the designers.  This is an example of what I am talking about [hackforla.org] Design system Figma page](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=3464%3A3&t=YbtblVeXv5rbIO92-0)

If this issue overlaps with another issue, then please sort it out

**Comment by mojimoh** [comment]
- This issue is duplicated in issue #972 which is referenced in issue #536.  The designers are working their way through it so will close this issue
