### ISSUE TITLE
Stakeholder Meeting (agenda) March 2020

### ISSUE THREAD

**Issue by KPHowley** [hackforla/tdm-calculator#315]
### Overview
Have a meeting with our LA DOT stakeholders, and go over the following items. 

### Action Items

- [ ] Set up a regular meeting time
- [ ] Go over stakeholder revisions
- [ ] Go over staging site (with video)
- [ ] Get a status report about progress with planning
- [ ] Updates on timelines  (Impact of COVID-19)
- [ ] Talk about next steps & software development cycle

### Resources/Instructions
[Stakeholder Revisions Documents](https://docs.google.com/spreadsheets/d/1Z2MyLYZAzz2yjTbB1v7F5ycg4kic0Al030VNWQrZLkY/edit#gid=0)

[Software Development Cycle Diagram](https://drive.google.com/file/d/1uZ5QG0N4--nQ-jMy1BfKuZSe7Wumhtb3/view)

[PDF of Architecture doc]( https://drive.google.com/file/d/1azHbT5DeVaVi-fXFdaTRqAurJv3kckRX/view?usp=sharing)

[System Architecture Document](https://docs.google.com/document/d/1lSOdgQTdqKYDZmX1QhMHqcslsmAngb7VAu3KiqKcaCI/edit)

Videos of current changes available on Dev site
[Level 0 behavior change](https://drive.google.com/open?id=1dyy9WmJqresPBp3yj-XXH6yiamSOrMmS)

[Compilation of changes](https://drive.google.com/open?id=1CYRcegcypsvI8owd9JYzTO1sa3F1dzrv)
includes :
- new footer placement on each page under all content (previously under the sidebar)
- ability to filter/search any column
- ability to sort any column in asc/desc order
- responsive behavior if working with smaller screens
- also included how the last summary page looks with smaller screen, which still needs work but needs feedback from stakeholders/users

**Comment by KPHowley** [comment]
@entrotech Hey John, take a look this agenda, and let us know if there's other things you want to go over.

**Comment by ExperimentsInHonesty** [comment]
-- snipit from slack --
Claire Nguyen

video https://drive.google.com/open?id=1CYRcegcypsvI8owd9JYzTO1sa3F1dzrv
It includes :
new footer placement on each page under all content (previously under the sidebar)
ability to filter/search any column
ability to sort any column in asc/desc order
responsive behavior if working with smaller screens
also included how the last summary page looks with smaller screen, which still needs work but needs feedback

Just realized that the video does not include the Level 0 behavior that was requested in the stakeholder revision notes. I made another video specific to that:
https://drive.google.com/open?id=1dyy9WmJqresPBp3yj-XXH6yiamSOrMmS
We also have questions about functionality specifically. As I was playing around and making a random project, I actually had no idea that what I was typing would have been a level 0 until I got to the last page. It would be a waste if a user had to go through the entire wizard only to find out that their project doesn’t qualify. We would like feedback on how we can give the user feedback that their project is currently a level 0 before they reach the last summary page.

**Comment by dazainus** [comment]
Hey Bonnie & Kevin,

The word file has been styled and stored in the Google Drive. As discussed with Bonnie via Slack chat, Google Word actually wouldn't allow background image insertions & additional visual features, so we ended up deciding to use Microsoft Word. With that said, the preview looks funky, but once you download it in your local computer it works perfectly. 
A pdf version is also in the folder for your convenience.

Here are the links: 

- **Google Drive Folder (named '[STYLED]')**: https://drive.google.com/drive/folders/17YylktqsPobnyczu4ArHAXXtawrV1_Dz?usp=sharing

- **MS Word**: https://drive.google.com/file/d/1hlDEJHAMtchUO_1VosUifdUwS5YWfZ0k/view?usp=sharing

- **PDF**: https://drive.google.com/file/d/1prSSUO1SgmemnSI7aK4-d3VTcllBnEp4/view?usp=sharing

Please let me know if these look good and if there are last minute changes. Otherwise, good luck with the client meeting!

**Comment by entrotech** [comment]
Keep in mind that this is still a rough draft.  It looks like the sample they gave us may have been redacted (or maybe not), so we're quite on how much detail we need, and whether we should include descriptions of the user stories, security roles and other workings of the application itself.

**Comment by dazainus** [comment]
@entrotech Thanks for sharing the insight. We can update the documentation as it grows with more information. I'd be happy to help organize that.

**Comment by dazainus** [comment]
@ExperimentsInHonesty 

Minor visual errors are adjusted: Removed white lines created by the background.

New files are uploaded (old files removed to prevent confusion)

- **MS Word**: https://drive.google.com/file/d/1BqWoe1tGoBLGsDBo7QIxcLRkgpWJsm03/view?usp=sharing

- **PDF**: https://drive.google.com/file/d/1azHbT5DeVaVi-fXFdaTRqAurJv3kckRX/view?usp=sharing
