### ISSUE TITLE
Add display of Project Level to Sidebar

### ISSUE THREAD

**Issue by entrotech** [hackforla/tdm-calculator#317]
### Overview
Rosemary requested that the Project Level be displayed in the sidebar somewhere near the Target Points and Earned Points. Show blank if Project Level is 0.

### Action items
Once Stakeholder signs off on one of the designs from 209, implement the changes requested.

### Dependency
Issue #209

**Comment by lemazza** [comment]
Was there a wireframe for this issue? I could swear I remember seeing one during Wednesday's meeting.

**Comment by ExperimentsInHonesty** [comment]
Issue #337 will be the issue for implementing changes
