### ISSUE TITLE
Add ability to enter a text note for Applicant-Defined Strategy with Explanation

### ISSUE THREAD

**Issue by entrotech** [hackforla/tdm-calculator#318]
- [ ]  Add text area (optional input)
- [ ] Provide designs with differently styled text areas options

**Comment by dazainus** [comment]
I will be able to provide quick design mock-ups.

### Goal
- [ ] Add text area (optional input)
- [ ] Provide designs with differently styled text areas options

**Comment by dazainus** [comment]
Sharing the two design options here.

### Screenshots

#### OPTION 1: Small Text Box Expandable Upon Click
-  Initial page is introduced with a small text box, and upon a user clicking the box, it will expand to a larger text box for paragraphs.

**Initial Screen**
![Option 1-1](https://user-images.githubusercontent.com/55513459/77859881-c3271780-71c0-11ea-9876-6a6a3a371567.jpg)

**Upon clicking the small text box**
![Option 1-2](https://user-images.githubusercontent.com/55513459/77859897-d20dca00-71c0-11ea-9fbd-c35db60c529c.jpg)

- See Figma prototype here (kind of jankey but you get the idea): https://www.figma.com/proto/qNgPc5lttpf0SWSwkbbWyT/TDM-Calculator?node-id=1018%3A10&viewport=111%2C177%2C0.25&scaling=min-zoom


#### OPTION 2: Fixed Box for Paragraph
- No changes in text box's sizes.

![Option 2](https://user-images.githubusercontent.com/55513459/77859949-2022cd80-71c1-11ea-8723-05e1f0885722.jpg)


### Resources

- Figma file: https://www.figma.com/file/qNgPc5lttpf0SWSwkbbWyT/TDM-Calculator?node-id=1018%3A10

**Comment by entrotech** [comment]
Screenshot of feature as implemented: 
![image](https://user-images.githubusercontent.com/9939032/79089919-d4157400-7cfc-11ea-871d-bae145f4e67d.png)
