### ISSUE TITLE
Change Wizard Page 3 Heading and remove parking space info

### ISSUE THREAD

**Issue by entrotech** [hackforla/tdm-calculator#319]
### Overview
Even though the purpose of entering the project specs is to calculate a nominal "parking requirement", the parking requirement doesn't exactly correspond to the actual parking requirement, so it is confusing to users to use the term "parking requirement" and show an impact on parking spaced in the right-hand columns. To de-emphasize the relationship between inputs and required parking calculation do the following:

### Action Items
- [ ] The heading was "Determine the required parking spaces". Change it to something like "Enter Project Specifications". 
- [ ] remove subtitle from "Enter the project specifications to determine the required parking" 
- [ ] Remove the columns showing the number of resulting spaces and the "spcs" units.

### Resources
Current state image
![Screen Shot 2020-03-28 at 11 58 36 AM](https://user-images.githubusercontent.com/37763229/77831283-7d4c4f80-70eb-11ea-8194-2abb62b15875.png)

**Comment by entrotech** [comment]
![image](https://user-images.githubusercontent.com/9939032/77853121-49c6ff00-7197-11ea-8c6e-e382afe96a40.png)

**Comment by KPHowley** [comment]
Reviewed, This appears ready for release to client from the above picture
