### ISSUE TITLE
UI/UX: Prototype & Design a way to share organization permissions for projects 

### ISSUE THREAD

**Issue by KPHowley** [hackforla/tdm-calculator#323]
### Dependency
- Once the application is launched, we can reconsider if this is a feature worth designing
- #296

### Overview
This is to create a field on projects for organizations and allow them to Share projects edit privileges between users. 

### Action Items
- [ ] add data field for Organization in backend
- [ ] add a way to share permissions to edit projects between individuals in organization
- [x] Sort out this issue from #780

**Comment by ExperimentsInHonesty** [comment]
- This issue might overlap with the issue about profiles #780.  Figure out how to write this issue after reviewing it

**Comment by entrotech** [comment]
@bonniewolfe @Biuwa 
I put some thought into what Use Cases we might put together to support this kind of functionality [here](https://docs.google.com/document/d/1Xy9n0A4Xw3HYJncVW0Gz9hQ9zYf9EAUWvQer0vY5nFU/edit?usp=share_link) for possible discussion at the 4/22 meeting.
