### ISSUE TITLE
Design an editing interface for the About page 

### ISSUE THREAD

**Issue by KPHowley** [hackforla/tdm-calculator#325]
### Overview
We want a redesign the About page, and add a way for admins to edit the copy on it. This is an issue for both UI and for Front end development.

### Action Items

- [ ] Create a mockup of what the editing interface will look like based on the current content of the About page using requirements and design of the FAQ editing
 

#### Requirements
- Ability to add/update or delete the following
  - Headers
  - Text under headers
  - Links in the Resources section 
    - name of link
    - link URL
    - indication if it's external or internal
  - Release  number

**Comment by Noushie** [comment]
Hi @Biuwa - Joyce is ready to present her designs to the group tonight, if that's possible as an addition to the meeting agenda

**Comment by limjoyce** [comment]
@Biuwa Updated Admin About page based on FAQ editing design:

**MOCKUP 1**

About Page - Edit Mode
![image](https://github.com/hackforla/tdm-calculator/assets/130421333/008001de-3acb-4f26-a0a8-2233958d7b5c)

**CHANGES MADE**

- Added "Edit Section" and "Save Edits" button at top left that brings you in and out of edit mode
- Create "Add category" CTA at top left to add a new category
- Added trash icon & grippy dots next to each text group to quickly move or delete categories


**MOCKUP 2**

About Page - Edit Category Text
![image](https://github.com/hackforla/tdm-calculator/assets/130421333/cc282f31-2230-47d1-9347-95871ded5f3d)

![image](https://github.com/hackforla/tdm-calculator/assets/130421333/51b8b877-2c37-45fe-a753-980f78d8cb06)


**CHANGES MADE**

- Option to edit both the Header & Body text


**MOCKUP 3**

Text Editor - Option 3B
![image](https://github.com/hackforla/tdm-calculator/assets/130421333/dc71419a-8b2c-4a56-8bd5-2f4f5e3efb08)

**CHANGES MADE**
- Added a rich text editor to format text, add links, attach images, bullets/lists, & indents



**LINK TO FIGMA FILE FOR ALL SHOWN MOCKUPS:**
[https://www.figma.com/file/nD9QK56Mzq7xNSaSUoeGx0/TDM-Calculator?type=design&node-id=2626-11673](https://www.figma.com/file/nD9QK56Mzq7xNSaSUoeGx0/TDM-Calculator?type=design&node-id=2626-11673)

**Comment by Biuwa** [comment]
The dev team is waiting for the FAQ Page to be finalized because it uses the same code for implementation

**Comment by Biuwa** [comment]
@entrotech This is ready for Dev

**Comment by entrotech** [comment]
- Created Issue #1531 for development
