### ISSUE TITLE
Change "Commercial Package" to "Employment Package" on the Strategies Page of the Wizard

### ISSUE THREAD

**Issue by entrotech** [hackforla/tdm-calculator#329]
### Overview
Change labels on the Wizard's "Transportation Demand Strategies" page  as below.

### Action Items
- [x] Replace "Select Commercial Package" label on button with "Select Employment Package".
- [x] Replace "TDM Commercial Package" as shown on below screenshot with "TDM Employment Package".
### Resources/Instructions
![image](https://user-images.githubusercontent.com/9939032/78088044-ddefbc80-7377-11ea-8401-43dfaa7cf586.png)

**Comment by fyliu** [comment]
I added the SQL changes to https://docs.google.com/document/d/172G0OKlMtikwIJCCeHOMdUTHMhnB6Qr2HMftXl_csYA/edit

**Comment by KPHowley** [comment]
@lemazza  I don't see the new text on the button when I reviewed it in staging
