### ISSUE TITLE
Create more specific status codes from the backend for errors

### ISSUE THREAD

**Issue by bfojas** [hackforla/tdm-calculator#332]
### Overview
Find opportunities to make the error handling from the backend return more specific error codes and implement.

**Comment by mojimoh** [comment]
@entrotech please work with developers to make this issue clearer for new developers, during the dev breakout

**Comment by entrotech** [comment]
This issue is too vague to be actionable.  I don't know what situation @bfojas was referring to or what his idea of a better solution might have been.
