### ISSUE TITLE
Redesign Dashboard in TDM Calculation Page

### ISSUE THREAD

**Issue by dazainus** [hackforla/tdm-calculator#335]
### Overview
Reorganize / redesign dashboard area in TDM Calculation pages.

### Objective

- To make the TDM calculation process more intuitive 
- To reflect various levels of information on Dashboard
- To retain consistency in showcasing of information

### Action Items
- [ ] Design/come up with best practice for information arrangement

### Resources/Instructions

- Figma file: https://www.figma.com/file/qNgPc5lttpf0SWSwkbbWyT/TDM-Calculator?node-id=1054%3A846

**Comment by dazainus** [comment]
@KPHowley, I am creating a separate issue addressing the best practice of the dashboard (I didn't want to create a long post in issue #321).  

### SUGGESTION IN CHANGE OF DESIGN

My suggestion is to rearrange how we show various pieces and levels of information on the Dashboard.

#### 1. SHOW 'PROJECT LEVEL' FIRST

- 'Project Level' should be seen first (on the top), then the 'TDM Point Value' (on the bottom) because 'Project Level' is somewhat a larger categorization than 'TDM Point Value'. 
- For instance, if a project level is calculated to be 0, the calculation process ends right away, thus TDM Point Values should not be emphasized to these kinds of users.
- By introducing 'Project Level' first, we can make this process much more intuitive.

![Frame 1](https://user-images.githubusercontent.com/55513459/78520676-4249bc00-777c-11ea-81ac-1dac994ba5b5.png)

#### 2. USE OPACITY

- When some pieces of information is not yet applicable, they should be seen less visible. 
- Utilizing opacity gives us some benefits:
  - It provides hierarchy.
  - It guides users which information to focus on.
  - It gives a sense of which information is active or inactive.
  - It helps indicate what information is available or to look for in future steps.

![Frame 2](https://user-images.githubusercontent.com/55513459/78520678-44137f80-777c-11ea-95d5-bcbf2e4652a1.png)

**Comment by JRAlexander72** [comment]
I like the reasoning behind the opacity. I'm kind of concerned about those with vision problems having difficulty navigating around that, you know?

**Comment by KPHowley** [comment]
I do like this as a redesign of the sidebar, and I think the opacity works as long as its ADA complaint. I do think we also need to think of it in conjunction with #209, do you think would it be redundant if we choose option 2?  

 @ExperimentsInHonesty - Do you want to take a look and share with LA DOT?

**Comment by KPHowley** [comment]
@ramccarr and @Dsomers74   - We'd love your opinion on this!

**Comment by ramccarr** [comment]
I like the redesign and I don't mind that some of the information on the page in issue #209 will be redundant in the sidebar. I also like the transparency, but defer to your judgement on ADA compliance.

**Comment by ExperimentsInHonesty** [comment]
Issue #337 will be the issue for implementing changes
