### ISSUE TITLE
Implement new design on side bar and project specification page

### ISSUE THREAD

**Issue by KPHowley** [hackforla/tdm-calculator#337]
### Overview
Implement the new design of the side bar including project level and opacity. Then implement the new design of the Target point calculation  page, with included emphasis on project level. 

### Action Items

- [x] Add Project Level to side bar
- [x] Reorganize side bar 
- [x] Implement opacity based on when values have been calculated 
- [x] Implement redesign of Target Point Calculation page 
         - Hold off on Save Button
- [x] Review

### Resources/Instructions
Design of Side bar:
![Frame 2](https://user-images.githubusercontent.com/55513459/78520678-44137f80-777c-11ea-95d5-bcbf2e4652a1.png)

Design of Target Point Calculation page:
![image](https://user-images.githubusercontent.com/49739276/79056615-3727dd80-7c0d-11ea-93b6-be6e800ba986.png)
From issue #209

**Comment by KPHowley** [comment]
@lemazza  - I'm copying your pull request breakdown here: 

**Overview**
Implement the new design of the side bar including project level and opacity. Then implement the new design of the Target point calculation page, with included emphasis on project level.

 **Action**
- Add Project Level to side bar
- Reorganize side bar
- Implement opacity based on when values have been calculated
- Implement redesign of Target Point Calculation page

- Implemented placeholder Tooltip, but now realize that was part of another issue. Can remove and create a new request in a little while, but thought I'd post this now in case its needed.

![issue-337-sidebar-p4](https://user-images.githubusercontent.com/32402365/79285835-8a02ce80-7e73-11ea-92a8-354115516ca4.PNG)

closes #337 

**Possible Future Issues**
- RuleCalculations for page 4 seem largely unused. Might need to be refactored
- Sidebar content scrolls out of view on the larger Summary page of the wizard. User won't know the current status. video below:


![tdm-scroll](https://user-images.githubusercontent.com/32402365/79286258-e5818c00-7e74-11ea-90aa-3c4fc24535f8.gif)

**Comment by KPHowley** [comment]
From meeting 4/15 - David Somers asked for Target points to be displayed in the blue bar, can we get an updated mockup.

**Comment by KPHowley** [comment]
From stakeholder meeting 4/28: We do want to proceed with simply adding the target points as shown in this image :

![image](https://user-images.githubusercontent.com/49739276/80639383-c78c5d80-8a16-11ea-86ce-6b98a6416298.png)
@lemazza

**Comment by ExperimentsInHonesty** [comment]
Implemented.  Ready for stakeholder signoff on next meeting
![Screen Shot 2020-05-02 at 10 46 54 AM](https://user-images.githubusercontent.com/37763229/80871605-60fb7f80-8c62-11ea-96a5-046f45bb7292.png)
