### ISSUE TITLE
UI/UX: Design a mockup for the deleting and duplicating projects

### ISSUE THREAD

**Issue by KPHowley** [hackforla/tdm-calculator#338]
### Overview
We need to design a way for the users to duplicate and delete existing projects. 

### Action Items

- [x] Design duplication feature
- [x] Design deletion feature
- [x] Determine if any related tools are needed
- [x] Review with LADOT
- [ ] Move issue to Front end development

**Comment by dazainus** [comment]
I've created a design mockup for this.

### Design Mockup
![Screen Shot 2020-05-02 at 10 36 59 AM](https://user-images.githubusercontent.com/55513459/80871386-280edb00-8c61-11ea-8707-549e096b0514.jpg)
When user clicks 'three dots icon,' an option area with 'duplicate' and 'delete' functions.
![Screen Shot 2020-05-02 at 10 37 14 AM](https://user-images.githubusercontent.com/55513459/80871396-3b21ab00-8c61-11ea-9446-f993a22d60db.jpg)

### Action Items
- [ ] Confirm on the design 
- [ ] Design 'Duplicate' window and 'Delete' window @dazainus 
- [ ] Approve on the feature titles 
- 'Duplicate' -> 'Create a duplicate' ?
- 'Delete' -> 'Delete project' ?

**Comment by KPHowley** [comment]
@dazainus per meeting on 2/26: Please change design to have 2 buttons for duplicate and delete in line for each project, rather than behind the "..." button.

**Comment by dazainus** [comment]
@KPHowley - Above changes are reflected in the designs here.

### Main Project page
- "..." button is removed
- 'Duplicate' and 'Delete' icons are inserted 
![Up to date](https://user-images.githubusercontent.com/55513459/83091743-c0c22c00-a050-11ea-92d8-2587dfa52c65.png)

### Duplicate Window
![Projects-Duplicate-window](https://user-images.githubusercontent.com/55513459/83091825-eea77080-a050-11ea-8d26-141d8d8e0fba.png)
![Projects-Duplicate-window-copycreated](https://user-images.githubusercontent.com/55513459/83091831-f49d5180-a050-11ea-8d3d-fc85f4f73571.png)

### Delete Window
![Projects-delete-window](https://user-images.githubusercontent.com/55513459/83091836-f8c96f00-a050-11ea-86c5-4e37834b0db1.png)

### Resource
Figma: https://www.figma.com/proto/qNgPc5lttpf0SWSwkbbWyT/TDM-Calculator?node-id=1444%3A467&viewport=572%2C-1013%2C0.5&scaling=min-zoom

**Comment by KPHowley** [comment]
@Dsomers74  - We updated this design for the projects page to include the duplicate and delete buttons on each project's line, as discussed on 5/26 could you please review the image above?

**Comment by nclairesays** [comment]
Hi @KPHowley, @dazainus, @ExperimentsInHonesty , can we actually revisit this design? I'm working on the implementation of this all of this and have a few thoughts:

Can we add to the Duplicate/Delete windows the name of the project that you user selected? As I was testing it out, I would forget which project I  was copying/deleting. 
1. For the delete, maybe: 
"Are you sure you want to _permanently_ delete the selected project (**Name of Project here**)?
 
2. a) For the duplicate, I actually think it's better to not even have a modal window at all. I would recommend letting the backend handle this and just having the app duplicate the project with the word "(Copy)" at the end of the title and not require the user to come up with a new title. It would be an exact copy of the project and the database can just add the text at the end of the title. This requires less code.  I'm also assuming that the user would end up editing the duplicate project anyway and if they wanted to change the project name, then they would do it in the wizard along with any other changes to that copy.
b) But if we must have the modal, then maybe change the text to something like: 
"Do you wish to make a copy of the selected project (**Name of Project here**)? Type in a title of the duplicated project."

**Comment by dazainus** [comment]
@nclairesays - Thanks for addressing this, Claire. From the design perspective, I agree that the wording you suggested read nicely and would be a better user experience.

In regards to the decision about having / removing the 'Duplicate' modal, it would be beneficial to talk with the whole team during tomorrow's meeting.
