### ISSUE TITLE
Stakeholder Meeting 4/15

### ISSUE THREAD

**Issue by KPHowley** [hackforla/tdm-calculator#342]
### Overview
The issues to review during stakeholder meeting on 4/15 are linked in this presentation :
[Release Updates & Stakeholder Questions 4/15](https://docs.google.com/presentation/d/1zzeSun0_HIF3W1QzitJl02KjOkiyKLnK6aHSR2tTeqo/edit?usp=sharing)

**Comment by entrotech** [comment]
Questions:

- Are tooltips a good approach to displaying the descriptions on the Strategies page? If so, what improvements should we make to the appearance?
- With the de-emphasis on the parking calculation we need to review how that calculation is displayed on the Summary page and decide on changes.
- Do we want to do a release to the test environment this week?
