### ISSUE TITLE
Redirect Http to Https

### ISSUE THREAD

**Issue by KPHowley** [hackforla/tdm-calculator#348]
### Overview
Currently the site can be viewed on a Http url, we want to make sure users can only see the site via a https site. 

https://tdm-calc-staging.herokuapp.com
http://tdm-calc-staging.herokuapp.com

### Action Items

- [ ] Read up on issue, and determine if it needs to be addressed in Heroku or in the Code
- [ ] Document solution and review with Joel
- [ ] Address if possible

**Comment by entrotech** [comment]
Closed by PR #377
