### ISSUE TITLE
Projects page is not visible after a user is logged in for a while

### ISSUE THREAD

**Issue by KPHowley** [hackforla/tdm-calculator#351]
### Overview
If a user is logged into the app, but is inactive for a while, or closes the app's browser window and then comes back later and opens a page that requires the user to be logged in, the requests to the back end fail silently. For example, the projects page will not display the projects, and a new project cannot save successfully.
This is believed to be a problem with the web api and client not properly handling an expired login token.

### Action Items
- [ ] Investigate when exactly the bug is happening. 
- [ ] Check the token expiration time out on cookies

**Comment by KPHowley** [comment]
Eta to determine next steps: 5/12

**Comment by ExperimentsInHonesty** [comment]
@fyliu  can you provide an update on this issue.
1. Progress
2. Blocks
3. Availability
4. ETA

**Comment by fyliu** [comment]
It's not breaking for me anymore lately. I'll try logging out and logging in again.

**Comment by fyliu** [comment]
I'm able to reproduce this on staging but not locally. I have an old token that's unable to list projects and a new logged in token that is able to list projects. This is reproducible in Postman and only the new token request produces a logging output in node in staging, the other request results in a connection error on Postman.

**Comment by entrotech** [comment]
PR #438 modifies the JWT token expiration and adds an expiration time (also 12 hours) to the cookie containing the JWT, so the cookie can live between browser sessions.
