### ISSUE TITLE
Delete Land use page from the wizard

### ISSUE THREAD

**Issue by KPHowley** [hackforla/tdm-calculator#354]
### Overview
Determination has been made that the land use page is redundant with the project specification page, and makes land use definitions hard to interpret. We want to delete this page, and have users go directly to entering project specifications, and land use types to be determined via which boxes users fill in 

### Action Items

- [ ] Delete the land use page
- [ ] Update routes if necessary
- [ ] Update Back end if necessary
- [ ] Make sure land uses types are still determined automatically

**Comment by entrotech** [comment]
I implemented this is the staging database, but then did not have a place for the Major CUP checkbox, so I put it at the top of the Project Specifications page of the wizard. @Dsomers74  and @ramccarr need to decide where this belongs or if it should be removed from the calculation entirely.

**Comment by Dsomers74** [comment]
> I implemented this is the staging database, but then did not have a place for the Major CUP checkbox, so I put it at the top of the Project Specifications page of the wizard. @Dsomers74 and @ramccarr need to decide where this belongs or if it should be removed from the calculation entirely.
> ![Screen Shot 2020-05-02 at 10 56 37 AM](https://user-images.githubusercontent.com/37763229/80871942-a2405f00-8c63-11ea-82ae-fddba9fc8bb2.png)

After a deeper review of our Municipal Code (LAMC), I request to remove reference entirely. I will be bringing up with the team. There is an off chance I am overruled and it comes back in later, though I'd rather risk than contribute to the beta-testers confusion. Plus, I think they will agree with me (knock on wood).

**Comment by ExperimentsInHonesty** [comment]
@entrotech can we hide the CUP now on this version and the single page view?

**Comment by entrotech** [comment]
I disabled the Major CUP input and deployed to staging - just a database change, no PR or deployment required. This will be deployed to testing with the next release.
