### ISSUE TITLE
Change percentage wording on Final summary page

### ISSUE THREAD

**Issue by KPHowley** [hackforla/tdm-calculator#364]
### Overview
The label on the percentage displayed on the final summary page still says "Provided / Required Parking" "however elsewhere this wording has been changed to "Parking Provided / Baseline."

### Action Items
Change wording to "Parking Provided / Baseline " on final summary page

**Comment by KPHowley** [comment]
Eta to push this: 5/9

**Comment by fyliu** [comment]
See pull request for screenshot

**Comment by mmorgs** [comment]
approved and merged ticket

**Comment by nclairesays** [comment]
Need to update Cypress tests to also reflect wording "Parking Provided / Baseline " on final summary page for all the test cases. Updating tests should have been part of this same issue.
