### ISSUE TITLE
Prepare List of Questions for submittal to Rosemary at LADOT

### ISSUE THREAD

**Issue by Rankazze** [hackforla/tdm-calculator#38]
Generate a Google document gathering questions to give to Bonnie who will review and then send to Rosemary

**Comment by dreams0ng** [comment]
@ExperimentsInHonesty , @Rankazze 

Is it possible to add to this list? I have business design questions for Rosemary which are essential to developing the logo. I can either add my questions in the google drive document, or upload a .pdf here.

-Tyler H.
