### ISSUE TITLE
Add Documentation for using Azure's  Third Party Error Logger 

### ISSUE THREAD

**Issue by KPHowley** [hackforla/tdm-calculator#381]
### Overview

Add a third party error logger

### Action Items

- [x] Research 
- [x] Implement
- [ ] Create documentation on how to use Azure for this.

**Comment by fyliu** [comment]
I'm making a spreadsheet to compare features: https://docs.google.com/spreadsheets/d/1uqroX7_3Xg6FCTGlKIMhQP_VPVWbMd6hPHBbRahaf4E

It's probably better to try adding loggers to the project to get a feel of each one. Winston is the most popular for sure. John has used pino in fola so there's experience there.

**Comment by entrotech** [comment]
This is implemented in Azure Application Insights, and viewable from the Development Azure account by running standard or customied reports, though nobody has really dug into how to use this as part of our production monitoring process.

**Comment by ExperimentsInHonesty** [comment]
closing this issue because we created a new issue #941
