### ISSUE TITLE
Convert the TDM Calculator to be run with docker

### ISSUE THREAD

**Issue by KPHowley** [hackforla/tdm-calculator#391]
### Overview
"Dockerize" the application for deployment to Azure. This is separate from "Dockerizing" for development purposes.

### Action Items

- [x] Create a Dockerfile and .dockerignore to create a docker container suitable for deployment to Azure.
- [x] Set up a personal or HfLA Azure accocunt to test deployment of the web app via docker containers
- [x] Create a Docker Hub project for TDM.
- [x] Publish our Docker container to Docker Hub?
- [ ] Set up Travis (or Azure equiv) to auto-deploy container to docker host when changes are pushed to the master branch.
- [x] Test the application deployed to the test Azure account and verify that it works.
- [x] Move deployment environment to the LADOT Azure accounts.
- [ ] Document deployment procedures in an *.md file.

**Comment by entrotech** [comment]
Running both dev and UAT in AZure now.  Still need work on the deployment procedure and automation for it, and documentation is incomplete.

**Comment by KPHowley** [comment]
@entrotech - Can we consider this issue as done?
