### ISSUE TITLE
Include new input of Assessor Parcel Number (APN) input on landing page 

### ISSUE THREAD

**Issue by Dsomers74** [hackforla/tdm-calculator#394]
### Overview
Add an APN entry field on the landing/welcome page will help enable mapping output files to link each project to APN, which are already mapped. This is a work around of address geolocator is the wrong data entry format.

### Action Items
Add new Assessor Parcel Number (APN) input field on landing page - 10 digit number in 4-3-3 string entry, entered as ####-###-###

**Comment by fyliu** [comment]
@Dsomers74 I would like to ask for confirmation of the field name. LA County calls this the Assessor's ID Number (AIN).

**Comment by KPHowley** [comment]
- and thanks for adding this David!

**Comment by entrotech** [comment]
This is a database-only change at this time. It is scripted in the Database Change script on G-Drive. I did not add this as a masked input, enforcing the 4-4-3 format. That would require allowing the calculation engine to support an additional client-side validation rule.

**Comment by entrotech** [comment]
For maksing, might be able to use this libary (React Version) : https://github.com/estelle/input-masking

**Comment by entrotech** [comment]
Added input masking in 9999-999-999 format. Changed name to "Assessor ID", Underlined label to make it clear that it's a hyperlink.  Made AIN required.

**Comment by entrotech** [comment]
Per Bonnie, changed the label to "AIN" instead of "Assessor ID"
