### ISSUE TITLE
Update Navbar to display current page

### ISSUE THREAD

**Issue by KPHowley** [hackforla/tdm-calculator#395]
### Overview
Update the navbar to notate which page the user is on by changing color. 

### Action Items

- [ ] Add highlighting of current page using the TDM calculator yellow/green color
- [ ] Make the new projects page visible when user is on it, but with 50% opacity, and unclickable.

**Comment by alexchoiweb** [comment]
Hey Kevin

1. Added a highlight background but the nav link became less readable so I also tried an underline version. Let me know what you think works best. Personally I'm for the underline unless we use a different color combination for the current page link
![highlight](https://user-images.githubusercontent.com/35116846/83108114-2b389380-a074-11ea-9144-cfb826ddd91d.png)
![underline](https://user-images.githubusercontent.com/35116846/83108181-45727180-a074-11ea-8db8-0bbe9f08f7d4.png)

2. Done - also removed pointer if it's the current page
https://streamable.com/vgqn2t

If you guys have a preferred video snippet sharing site let me know too - my .mov files aren't being accepted here

**Comment by KPHowley** [comment]
@alexchoiweb  - I like this implementation! @dazainus - Any thoughts on this?

**Comment by dazainus** [comment]
@alexchoiweb - Great job within a quick turnaround time! And thank you for attaching the live action video. The lime color underbar looks really good to me.

With the work you did, it really visualizes that having 50% opacity on the 'New Project' element wouldn't be enough to refrain users from clicking it again (which would cause the loss of information inputted in the current project page). With that being said, it may be **ideal for us to come up with 'Exit Warning' system** to better inform and guide the users. 

@KPHowley - Could you please check with the dev team if the engineering would be capable in consideration of our timeline? I can work on developing this in conjunction with the 'Save' feature.

@alexchoiweb - In the mean time, could we make following changes? I think it would look better with the current lime underline solution.

- [ ] **Remove the white underline when the mouse hovers**
- [ ] **At mouse hover, the letters would turn into lime color**
- [ ] Lime underline indicates the page user is currently on. (Successfully done by Alex!)

**Comment by alexchoiweb** [comment]
@dazainus Thank you and done
https://streamable.com/n549rs

**Comment by alexchoiweb** [comment]
@KPHowley I can try to push and make a pull request today if we're good here?

**Comment by KPHowley** [comment]
@alexchoiweb - yes go ahead and push to staging!

**Comment by nclairesays** [comment]
I went ahead and accepted @alexchoiweb's PR #403 in order to add small/incremental changes to our code when they make sense. We need to discuss on Wednesday the behavior of the navbar in situations when a user clicks on an existing project, should the active/highlighted link in the navbar be "my projects" or "create project." The current behavior of the PR is that it will highlight "create project."

**Comment by nclairesays** [comment]
@KPHowley if it’s cool with you, I want to keep this issue open until we talk about my comment above. Currently, if you open an existing project, the active/highlighted menu item is the “create project.” Figured it would be good to talk tomorrow (or event do some user testing) about whether it should be “create project” or “my project” that’s highlighted, as I don’t think we decided on that last week.

**Comment by KPHowley** [comment]
@nclairesays - OK, we can discuss - I thought you meant push this change and then do another issues for changing anything further than this, but your thought is to  just do an additional pull request on this issue?

**Comment by nclairesays** [comment]
@KPHowley yes, i figured we could do incremental changes to address an issue. even if it's not 100% complete, it could still bring value to the user. maybe we can also discuss if for scenarios like this, does it make sense to close an issue and make another or to keep it open and make multiple prs to the same issue.
