### ISSUE TITLE
Make Sidebar "sticky" on screen 

### ISSUE THREAD

**Issue by KPHowley** [hackforla/tdm-calculator#405]
### Overview
Based of  feedback with the LADOT and with internal Hack for LA users, having the sidebar be fixed to the screen when scrolling would be ideal. 

### Action Items

- [x] Adjust sidebar properties
- [x] Review

**Comment by lemazza** [comment]
The sidebarContainer element is now sticky. As far as I can tell it all works and there are no adverse effects on the sidebar on other pages or sizes.

![tdm-sticky-scroll](https://user-images.githubusercontent.com/32402365/83995852-5d1ce600-a90f-11ea-9fe7-af9e0e7472d2.gif)

**Comment by KPHowley** [comment]
@lemazza - I'm going to get some feedback on the scrolling on the image to the side, and update you as I think it can be a bit distracting. Thanks for this!
