### ISSUE TITLE
Add Page numbers OR progress bars on bottom of wizard

### ISSUE THREAD

**Issue by KPHowley** [hackforla/tdm-calculator#406]
### Overview
From user feedback it seems that having page numbers on the bottom of the wizard pages would be beneficial. 

### Action Items

- [ ]  Figure out styling
- [ ]  and Numbers 
- [ ]  investigate changing arrows to say "next page" and "previous page"

**Comment by dreams0ng** [comment]
CHANGES

- [ ] Figure out styling
- [X] and Numbers
- [X] investigate changing arrows to say "next page" and "previous page"

MOCKUPS
![Screen Shot 2020-07-30 at 12 20 54 PM](https://user-images.githubusercontent.com/22779768/88965114-230cf800-d25f-11ea-9422-0ab8c9392a7f.png)

LINKS
https://www.figma.com/file/6h72XLxK76m4INtsSu8Mt0/TDM-Calculator-Copy?node-id=0%3A1

**Comment by dreams0ng** [comment]
CHANGES
-removed text to indicate page #
+added progress bars that match LADOT approved iconography

MOCKUPS 
![Screen Shot 2020-10-07 at 11 56 31 AM](https://user-images.githubusercontent.com/22779768/95375370-5fc72200-0894-11eb-94fb-527db8321a13.png)


LINKS
https://www.figma.com/file/6h72XLxK76m4INtsSu8Mt0/TDM-Calculator-Copy?node-id=0%3A1

**Comment by KPHowley** [comment]
Please provide an update with: 

    1) Progress
    2) Blockers
    3) Availability
    4) ETA

**Comment by dreams0ng** [comment]
1) Progress 
See last post
2) Blockers
n/a
3) Avail
4) ETA
n/a

**Comment by dreams0ng** [comment]
1. Progress
+Added hover interaction to see page number

2. Blockers
n/a

![Page # Hover](https://user-images.githubusercontent.com/22779768/96945418-91460d00-1492-11eb-81b0-0fb79111ace4.gif)

**Comment by KPHowley** [comment]
@dreams0ng  - can you do just a basic updated version that just just displays page numbers similar to the first mock up in this issue?

**Comment by KPHowley** [comment]
@dreams0ng - I just updated this myself do I can share and discuss if we just want to do this as a Quick iteration for the MVP. 


![Screen Shot 2020-10-27 at 3 07 55 PM](https://user-images.githubusercontent.com/49739276/97367441-55ca8a80-1866-11eb-8763-93e0ce312004.png)

**Comment by KPHowley** [comment]
@dreams0ng  Please provide an update with:
1) Progress
2) Blockers
3) Availability
4) ETA
