### ISSUE TITLE
Add “Fill out only what applies to your project"  to project specification page 

### ISSUE THREAD

**Issue by KPHowley** [hackforla/tdm-calculator#409]
### Overview

Add “Fill out only what applies to your project" to the project specifications page.

### Action Items

- [x] Make quick mockup 
- [x] Review
- [x] Move to Front end

**Comment by KPHowley** [comment]
![Project specs subtitle](https://user-images.githubusercontent.com/49739276/83955346-dc72c280-a806-11ea-8236-2dc356d93ca6.jpg)
@Dsomers74 - through our internal user testing we determined that adding this subtitle "Fill out only what applies to your project" to the top of the project specification page would help, can you please take a look and approve?

**Comment by Dsomers74** [comment]
This is a helpful prompt. Can we change to say: "fill out the use specifications that applies to your project"

**Comment by KPHowley** [comment]
@Dsomers74  - 
![Updated specification subtitle](https://user-images.githubusercontent.com/49739276/84193010-aaa06c80-aa4f-11ea-93e1-16983845f18f.jpg)

**Comment by Dsomers74** [comment]
That works for me.
