### ISSUE TITLE
Develop guide/ info on how to use Git for our project

### ISSUE THREAD

**Issue by entrotech** [hackforla/tdm-calculator#41]
Define git branch naming convention
https://dev.to/hardkoded/how-to-organize-your-git-branches-4dci
https://stackoverflow.com/questions/273695/what-are-some-examples-of-commonly-used-practices-for-naming-git-branches

- [x] Add instructions to contributing.md for GitFlow:
- [x] Add instructions for developers to contribute to develop branch.
- [x] Add instruction for release manager to create a release.
- [ ] Add instructions for release manager for\ HotFixes.

**Comment by entrotech** [comment]
Need to update documentation in contributinng.md for HotFixes after change to Git Flow

**Comment by fyliu** [comment]
I found an existing one for reference: https://github.com/thoughtbot/guides/tree/master/protocol/git

Code review: https://github.com/thoughtbot/guides/tree/master/code-review

Interesting git aliases to borrow: https://github.com/thoughtbot/dotfiles

**Comment by joelparkerhenderson** [comment]
https://github.com/gitalias

For git aliases, here's what I use and advocate for all of HfLA to choose - it's the best git aliases I've found from hundreds of projects, and that I've professionally used with dozens of teams.

I'm happy to teach it one night too, and help each team customize it as desired.

**Comment by fyliu** [comment]
@joelparkerhenderson this is great! Just need to replace a few "origin/master" with whatever the dev/project is using as the remote merge target.

**Comment by ExperimentsInHonesty** [comment]
@entrotech is still working on this.  
next steps:
are making sure eslint issue is working #251 
make sure application is running unit tests after people do a commit #235

**Comment by ExperimentsInHonesty** [comment]
@entrotech Where are we at with this issue
1. Progress
2. Blocks
3. Availability
4. ETA

**Comment by joelparkerhenderson** [comment]
Here's git branch name info, including conventions, and how to edit branch descriptions (which is worth doing IMHO).

https://github.com/joelparkerhenderson/git_branch_name

**Comment by entrotech** [comment]
Fixed in PR #274  by adding section for HotFix reelases.
