### ISSUE TITLE
Correct spelling on "100% affortdable " in affordable housing drop down menu on measure selection page 

### ISSUE THREAD

**Issue by KPHowley** [hackforla/tdm-calculator#410]
### Overview
"Affordable housing" is spelled "Affortable housing" in the drop down menu on the measure selection page for the affordable housing measure. We need to update this.

### Action Items

- [x] correct spelling

### Resources/Instructions
![Screen Shot 2020-06-06 at 10 57 19 AM](https://user-images.githubusercontent.com/49739276/83952846-be01cc80-a7f0-11ea-99f7-ac0ecc72f3ab.png)

**Comment by KPHowley** [comment]
@entrotech  - I wanted to see if we could make this change quickly, but I'm not sure if this is a database or front end issue, could you let me know?

**Comment by entrotech** [comment]
Database only. Applied to staging, added to Database Scripts file for deployment to production.

**Comment by KPHowley** [comment]
![Screen Shot 2020-06-09 at 1 28 26 PM](https://user-images.githubusercontent.com/49739276/84196515-2cdf5f80-aa55-11ea-9165-e4c2d39caaf9.png)
