### ISSUE TITLE
Prototype and test the user journey from arriving to site, through logging in and creating a project 

### ISSUE THREAD

**Issue by KPHowley** [hackforla/tdm-calculator#411]
### Overview
 
We need to create a prototype and test the user experience for coming to the website, to determine where to direct users and if a landing page is necessary. We also have to make sure the user knows how to log in or continue without saving. 

### Action Items

- [ ] Create a test for three user journeys
    - [ ]  the user goes to a landing site and gets directed to either log in/sign up or to continue without the ability to save
    - [ ] The user goes to the create new project link, but gets notified that they can't save progress unless they log in,
    - [ ] The user the goes directly to log in , but knows they don't have to sign in and can go directly to the create a project page if they don't want to save the project
- [ ] Test this with users 
- [ ]  Create issue for development

**Comment by amberyou** [comment]
I mapped out the 3 user journeys here: [https://www.figma.com/file/ZoLYZ4sey37GNGyRV2x1GZ/TDM-Calculator-Copy?node-id=1054%3A0]

**Comment by ExperimentsInHonesty** [comment]
We are not creating a landing page for the site.  The stakeholder rejected the suggestion
