### ISSUE TITLE
Determine if "my projects" should be visible  on menu when users are not logged in

### ISSUE THREAD

**Issue by KPHowley** [hackforla/tdm-calculator#414]
### Overview
Determine if "my projects" should be visible on menu when users are not logged in, and if so whether it should be unclickable or greyed out. 

### Action Items

- [ ] Test and determine best method
- [ ] Move to front end development

**Comment by ExperimentsInHonesty** [comment]
Did this already get done.  I have not logged in recently.  This is what I see when I am not logged in
![image](https://user-images.githubusercontent.com/37763229/215298404-a02d1830-3c68-4fde-8a6d-af9b541c56c7.png)
![image](https://user-images.githubusercontent.com/37763229/215298410-6904b9ba-5552-4915-a022-02bf2ddb5e55.png)

Can someone who is logged in add a screenshot here that shows what it looks like then?

**Comment by mojimoh** [comment]
![image](https://user-images.githubusercontent.com/121916285/218625342-66ed282a-ab75-4efb-acd7-dd431a090a0e.png)
This issue has been addressed. Closing and pushing to released
