### ISSUE TITLE
Discuss and review notifications and toasts used throughout the site

### ISSUE THREAD

**Issue by KPHowley** [hackforla/tdm-calculator#416]
### Overview

We currently are using toasts as a system for notifying people on the site, we want to discuss if this is the best method to use, and what are the capabilities of this. 

### Action Items

- [ ] Discuss toast capabilities, optics, and alternatives with team.
- [ ] Get feedback from stakeholders. 
- [ ] Determine if we need to keep using toast, alter them, or change notifications
- [ ] Implement changes 

### Resources/Instructions
discussed in - #407

**Comment by KPHowley** [comment]
@lemazza I assigned this to you because it follows up on #407. If you can help lead us through some of the options we have tomorrow that would be great.

**Comment by lemazza** [comment]
No problem, I'm messing around with react-toastify right now
