### ISSUE TITLE
Make changes in Earned points clearer when measures are selected

### ISSUE THREAD

**Issue by KPHowley** [hackforla/tdm-calculator#417]
### Overview

From user testing we have realized users are unclear that the earned points are changing as measures are selected. We are trying to determine a best way to emphasize this

### Action Items

- [x] Discuss with TDM Team 
- [x] Discuss with Stakeholders
- [x] Come up with design 
- [ ] Review / test 
- [ ] Implement in the front end

**Comment by dreams0ng** [comment]
CHANGES
- [X] Come up with design

MOCKUPS
Page 1
![Screen Shot 2020-07-27 at 10 32 56 PM](https://user-images.githubusercontent.com/22779768/88623200-4d8d6400-d059-11ea-8f35-2a43f2e9ae8e.png)

Page 2
![Screen Shot 2020-07-27 at 10 33 16 PM](https://user-images.githubusercontent.com/22779768/88623210-52521800-d059-11ea-9419-7e1e8175a13d.png)

Page 3
![Screen Shot 2020-07-27 at 10 33 24 PM](https://user-images.githubusercontent.com/22779768/88623222-5aaa5300-d059-11ea-9461-fce15d0f8234.png)

Page 4 - Once you surpass the target points the box and text switch colors
![Screen Shot 2020-07-27 at 10 33 30 PM](https://user-images.githubusercontent.com/22779768/88623241-6433bb00-d059-11ea-9545-9f708df7b29a.png)

Page 5
![Screen Shot 2020-07-27 at 10 33 43 PM](https://user-images.githubusercontent.com/22779768/88623248-685fd880-d059-11ea-83f3-35471a68325f.png)

Page 1 ALT - Target Point Feature Removed (It doesn't seem to be heavily used until Page 4 of the Wizard View)
![Screen Shot 2020-07-27 at 10 33 56 PM](https://user-images.githubusercontent.com/22779768/88623280-77df2180-d059-11ea-97f9-c13527338993.png)

LINKS
https://www.figma.com/file/6h72XLxK76m4INtsSu8Mt0/TDM-Calculator-Copy?node-id=0%3A1

**Comment by dreams0ng** [comment]
CHANGES
+visualized points added with correct style elements
+used new point title placement and font color change in sidebar

MOCKUPS
![giphy-4](https://user-images.githubusercontent.com/22779768/90579212-2fa7b080-e17a-11ea-9077-80a81f3dfa0c.gif)

LINKS
https://xd.adobe.com/view/f32a7d21-a346-43a1-6e66-809bd1399976-851b/screen/e6396816-04b0-4958-a5f8-e788f740c02b

**Comment by dreams0ng** [comment]
CHANGES
+executed new font color change without font size change
+visualized font color and size change
+visualized live point additions

MOCKUPS
1a.
![giphy](https://user-images.githubusercontent.com/22779768/91374658-8726cb80-e7cd-11ea-85fd-7a08bae4d2a9.gif)

1.b 
![giphy-1](https://user-images.githubusercontent.com/22779768/91374695-9c035f00-e7cd-11ea-8049-03863e3212e2.gif)

LINKS
1a.
https://xd.adobe.com/view/f32a7d21-a346-43a1-6e66-809bd1399976-851b/screen/e6396816-04b0-4958-a5f8-e788f740c02b

1b.
https://xd.adobe.com/view/f32a7d21-a346-43a1-6e66-809bd1399976-851b/screen/32582e0e-0064-4157-8a7d-5fca3d7f9d9e

**Comment by dreams0ng** [comment]
CHANGES
+Changed font color from blue to orange
+Put plus numbers next to earned numbers

MOCKUPS
1a.  
![giphy](https://user-images.githubusercontent.com/22779768/92029022-c8f9c980-ed19-11ea-8181-d8e309e6bd9c.gif)

1b.
![giphy-1](https://user-images.githubusercontent.com/22779768/92029048-d1ea9b00-ed19-11ea-82b1-c686a1fedbb3.gif)

LINKS
1a.
https://xd.adobe.com/view/f32a7d21-a346-43a1-6e66-809bd1399976-851b/

1b.
https://xd.adobe.com/view/f32a7d21-a346-43a1-6e66-809bd1399976-851b/screen/32582e0e-0064-4157-8a7d-5fca3d7f9d9e

**Comment by dreams0ng** [comment]
1) Progress
Settled on two versions for testing
2) Blockers
Testing
3) Availability

4) ETA
n/a
