### ISSUE TITLE
Make it more clear to users when Target points have been met in the wizard

### ISSUE THREAD

**Issue by KPHowley** [hackforla/tdm-calculator#418]
### Overview

From user testing we have figured out that it is not immediately clear when you have reached your  target points, and in essence, completed the goal of the wizard. This can be done simply by soething such as a color change or text notification 

### Action Items

- [ ] Discuss with Stakeholders
- [ ] Discuss with TDM Team
- [ ] Come up with design 
- [ ] Review / test 
- [ ] Implement in the front end

REPLACE THIS TEXT -If the issue has already been researched, and the course of action is clear, this will describe the steps.  However, if the steps can be divided into tasks for more than one person, we recommend dividing it up into separate issues, or assigning it as a pair programming task.

**Comment by dreams0ng** [comment]
CHANGES
Please find below a proposed design solution for coming up with a design to "make it more clear to users when Target points have been met in the wizard". Once target points are met, the white box switches to earned points and the text color changes
- [X] Come up with design

MOCKUPS
Before hitting target points
![Screen Shot 2020-07-30 at 12 28 04 PM](https://user-images.githubusercontent.com/22779768/88965805-29e83a80-d260-11ea-8aa1-45f78363cdde.png)

After hitting target points
![Screen Shot 2020-07-30 at 12 28 10 PM](https://user-images.githubusercontent.com/22779768/88965824-2ce32b00-d260-11ea-800e-5024003b88f8.png)


LINKS
https://www.figma.com/file/6h72XLxK76m4INtsSu8Mt0/TDM-Calculator-Copy?node-id=0%3A1

**Comment by dreams0ng** [comment]
CHANGES
Further demonstration of animation

MOCKUPS
![giphy](https://user-images.githubusercontent.com/22779768/89005681-eae6d300-d2b9-11ea-9676-ccdbc6551850.gif)

LINKS
https://xd.adobe.com/view/f32a7d21-a346-43a1-6e66-809bd1399976-851b/

**Comment by dreams0ng** [comment]
CHANGES
1a. Visualized font color change
     +moved target points to right
     +made target points font green
     +earned points font turns green to match target
     +green font clearly visible over image in three color blind tests

1b. Visualized font size change (if this qualifies as animation, please disregard)
     +put target points over earned
     +earned points font size increases to match target
 
MOCKUPS
1a.  
![colorchange](https://user-images.githubusercontent.com/22779768/90442867-29d5a080-e090-11ea-918e-5176d1ea8cb1.gif)

1b.
![sizechange](https://user-images.githubusercontent.com/22779768/90442525-a9af3b00-e08f-11ea-830b-b3dd6f50a71f.gif)

LINKS
https://xd.adobe.com/view/f32a7d21-a346-43a1-6e66-809bd1399976-851b/

**Comment by dreams0ng** [comment]
CHANGES
+executed new font color change without font size change
+visualized font color and size change
+visualized live point additions

MOCKUPS
1a.
![giphy](https://user-images.githubusercontent.com/22779768/91374658-8726cb80-e7cd-11ea-85fd-7a08bae4d2a9.gif)

1.b 
![giphy-1](https://user-images.githubusercontent.com/22779768/91374695-9c035f00-e7cd-11ea-8049-03863e3212e2.gif)

LINKS
1a.
https://xd.adobe.com/view/f32a7d21-a346-43a1-6e66-809bd1399976-851b/screen/e6396816-04b0-4958-a5f8-e788f740c02b

1b.
https://xd.adobe.com/view/f32a7d21-a346-43a1-6e66-809bd1399976-851b/screen/32582e0e-0064-4157-8a7d-5fca3d7f9d9e

**Comment by dreams0ng** [comment]
CHANGES
+Changed font color from blue to orange
+Put plus numbers next to earned numbers

MOCKUPS
1a.  
![giphy](https://user-images.githubusercontent.com/22779768/92029022-c8f9c980-ed19-11ea-8181-d8e309e6bd9c.gif)

1b.
![giphy-1](https://user-images.githubusercontent.com/22779768/92029048-d1ea9b00-ed19-11ea-82b1-c686a1fedbb3.gif)

LINKS
1a.
https://xd.adobe.com/view/f32a7d21-a346-43a1-6e66-809bd1399976-851b/

1b.
https://xd.adobe.com/view/f32a7d21-a346-43a1-6e66-809bd1399976-851b/screen/32582e0e-0064-4157-8a7d-5fca3d7f9d9e

**Comment by KPHowley** [comment]
@dreams0ng  Please provide an update with: 

    1) Progress
    2) Blockers
    3) Availability
    4) ETA

**Comment by KPHowley** [comment]
@KPHowley @VJ1285  - Create a issue for a test of this.

**Comment by dreams0ng** [comment]
1) Progress
Settled on two versions for testing
2) Blockers
Testing
3) Availability

4) ETA
n/a
