### ISSUE TITLE
Design Customer facing FAQ view screen

### ISSUE THREAD

**Issue by entrotech** [hackforla/tdm-calculator#42]
### Overview 

We are looking to implement a FAQ soon, and want to update the design for this to be in line with current site. 

### Action item

- [x] Review UI wire-frame (dependency for development)
- [ ] Adjust or update Wireframe 
- [ ] determine how to link on the navbar or elsewhere. 
- [ ] Add an expand all feature

### Resources

See #26 for back end Admin screen

see: https://tdmdev.azurewebsites.net/faqs

**Comment by KianBadie** [comment]
Test comment

**Comment by entrotech** [comment]
Requires completion of Issue #76 before work can efficiently start.

**Comment by ExperimentsInHonesty** [comment]
#76 has been completed (rudementy).  We will need a list of features they want for the faq first.

**Comment by ExperimentsInHonesty** [comment]
This is a current functionality: https://tdm-calc-staging.herokuapp.com/faqs. What additional features do you want?

**Comment by ExperimentsInHonesty** [comment]
@JRAlexander72 please review other website faq tools (the admin screens) and see if there is a set of common features and then discuss with @KPHowley .

**Comment by dreams0ng** [comment]
CHANGES
- [X] Create UI wireframe (dependency for development)
- [X] Review other issue for backend admin (please see issue #76 for Admin FAQ Page mockups)
- [ ]  Create a react component to display faq details

MOCKUPS
![Screen Shot 2020-07-27 at 10 13 57 PM](https://user-images.githubusercontent.com/22779768/88622249-41a0a280-d057-11ea-986f-00fdaaf4774f.png)
![Screen Shot 2020-07-27 at 10 14 06 PM](https://user-images.githubusercontent.com/22779768/88622369-862c3e00-d057-11ea-9de2-9bf92c33aaf2.png)

LINKS
https://www.figma.com/file/6h72XLxK76m4INtsSu8Mt0/TDM-Calculator-Copy?node-id=1%3A562

**Comment by dreams0ng** [comment]
CHANGES
Visualize scroll bar for longer FAQ text

MOCKUPS
![Screen Shot 2020-07-30 at 11 50 48 AM](https://user-images.githubusercontent.com/22779768/88962190-f0f99700-d25a-11ea-9202-48f14ea131e8.png)

LINKS
https://www.figma.com/file/6h72XLxK76m4INtsSu8Mt0/TDM-Calculator-Copy?node-id=0%3A1

**Comment by dreams0ng** [comment]
CHANGES
Scrollbar element better matches style
Animated visual demonstration

MOCKUPS
![scroll](https://user-images.githubusercontent.com/22779768/89067381-04bd0000-d324-11ea-94d7-64e49aca4b76.gif)

LINKS
n/a

**Comment by dreams0ng** [comment]
CHANGES
+removed faq entry scrollbar
+visualized extended drop-down scenario
+corrected font family / size

MOCKUPS
![giphy copy](https://user-images.githubusercontent.com/22779768/90474348-ec960080-e0d9-11ea-968c-6ddd3a698a6a.gif)

LINKS
https://xd.adobe.com/view/f32a7d21-a346-43a1-6e66-809bd1399976-851b/

**Comment by KPHowley** [comment]
@dreams0ng - I believe the Adobe link goes to a mock up for the designed/earned points

**Comment by dreams0ng** [comment]
This should be working now, and the first drop down arrow is interactive

**Comment by ExperimentsInHonesty** [comment]
The design works for David, so we can send this to development.  @Dsomers74 will provide initial FAQ questions and about text approximately before September 1st.  

FYI - I did not mention this at meeting, but another benefit of having the questions in a digital faq, is that we can provide statistics on which questions get clicked on.  This helps the department understand what visitors most want to know (this can inform informational marking campaigns on a granular level, in a way that # of people clicking on a PDF cannot).

**Comment by KPHowley** [comment]
As with 76 this is ready for front end development, but was not in line with LADOT's desire to link to their FAQ page.

This could potentially be used in the future and should be discussed and prioritized for future  milestones along with #76

**Comment by Reneedesigns** [comment]
FAQ (screen examples- initial question list and answer views-not prototyped) @SMR9220 @Biuwa 

https://www.figma.com/file/nD9QK56Mzq7xNSaSUoeGx0/TDM-Calculator?node-id=3331%3A11982

Option 1- Boxes expand to answers with caret icons 

![FAQ option 1](https://user-images.githubusercontent.com/99779174/185733410-248b2055-2d55-4188-b24f-3567619f82d5.png)



Option 2- Similar to design from LADOT's FAQ section, +/-  icons with question boxed once selected


![FAQ option 2](https://user-images.githubusercontent.com/99779174/185733456-15d69c51-dc21-41f1-8b10-763e61b768f8.png)

**Comment by Biuwa** [comment]
Stakeholders went with option two (2) at today's meeting.

![image](https://user-images.githubusercontent.com/98936028/186283191-2863af7e-f950-4d7c-9e68-a135d0abefd6.png)

**Comment by Biuwa** [comment]
They also want to have an expand all feature added to option 2

**Comment by Reneedesigns** [comment]
Chosen "Expand All" screen (no box)  at 8/31 team mtg @SMR9220 @Biuwa 
Secondary option screen has green box

https://www.figma.com/file/nD9QK56Mzq7xNSaSUoeGx0/TDM-Calculator?node-id=6820%3A24494


![FAQ expand 1](https://user-images.githubusercontent.com/99779174/188256037-498757b0-20f8-469b-bf0e-bd1c0754f951.png)

![FAQ expand all](https://user-images.githubusercontent.com/99779174/188256054-724e7563-87cf-4d44-98e6-90c1ba63a69e.png)

![FAQ one question expanded](https://user-images.githubusercontent.com/99779174/188256062-1cee9167-a616-4f7b-885e-81cc3d8f308b.png)

![FAQ green box](https://user-images.githubusercontent.com/99779174/188256084-46f6033b-497f-413e-8a03-38f2dd13bf0c.png)

**Comment by ExperimentsInHonesty** [comment]
Alexander says use the green box version

**Comment by Biuwa** [comment]
Stakeholders went with this option:

![image](https://user-images.githubusercontent.com/98936028/188756336-deb308d6-4243-49ab-9639-c90ba95ab3ed.png)

**Comment by dreams0ng** [comment]
Hi! 

Hope you’re doing great Bonnie! Can someone please unsubscribe me from this chain, please?

**Comment by ExperimentsInHonesty** [comment]
@dreams0ng, only you can unsubscribe yourself.  Open this issue and click on the button. It looks like this
![image](https://user-images.githubusercontent.com/37763229/188759187-685ba885-9591-41d8-9320-d478617b9566.png)

**Comment by ExperimentsInHonesty** [comment]
#76 should get decided first, and then mockup made of that page, with the two options on the expand/collapse

**Comment by SMR9220** [comment]
Design wants to move forward with the text only option.

**Comment by ExperimentsInHonesty** [comment]
These are final designs

https://www.figma.com/file/nD9QK56Mzq7xNSaSUoeGx0/TDM-Calculator?node-id=6820%3A24494



![FAQ option 1](https://user-images.githubusercontent.com/99779174/188256125-b6299550-2c0b-46da-b74d-fefed7f3bf1b.png)



![FAQ expand all](https://user-images.githubusercontent.com/99779174/188256054-724e7563-87cf-4d44-98e6-90c1ba63a69e.png)

![FAQ one question expanded](https://user-images.githubusercontent.com/99779174/188256062-1cee9167-a616-4f7b-885e-81cc3d8f308b.png)

**Comment by ExperimentsInHonesty** [comment]
The dev issue has been made https://github.com/hackforla/tdm-calculator/issues/1248
