### ISSUE TITLE
Implement the redesign on the final summary page

### ISSUE THREAD

**Issue by KPHowley** [hackforla/tdm-calculator#421]
### Overview
Implement the new redesign of the final summary page as shown in the attached mock up. 

### Action Items

- [ ] Redesign page according to design. 
- [ ] When "Save project" button is pressed than make it so the user is not redirected from the page
- [ ] When "Save project" button is pressed add a time stamp next to it that noted the last modified date 

#### Design
![VER 2  tdm-summary](https://user-images.githubusercontent.com/55513459/84340768-474d3200-ab56-11ea-974c-bf2e40c2bfbd.png)

#### Resource
- Figma: https://www.figma.com/file/qNgPc5lttpf0SWSwkbbWyT/TDM-Calculator?node-id=1807%3A3610

**Comment by nclairesays** [comment]
I went ahead and approved the pull request so that we can have this as part of our meeting with LADOT tomorrow. However, I noticed that the time stamp is not in the same location as the figma design above.  Are we ok with this? @KPHowley @dazainus @alexchoiweb 
![image](https://user-images.githubusercontent.com/45305029/85376736-faba0d00-b4ec-11ea-95c3-ff0fb50141cd.png)

**Comment by KPHowley** [comment]
I believe we discussed the last save location staying up there in case the title is long, and Diane actually changed that in the figma design, however we didn't update the screenshot!

The only thing I noticed was that the button says "Save as new project" if the project hasn't been saved before and "Save project" if it has. I don't think this is necessary and just puts too much text in there, but will defer to @dazainus.

**Comment by KPHowley** [comment]
@alexchoiweb , @nclairesays  - I actually have some updates on this that  we want to change before pushing to live - most of these were on the design too (I should've reviewed it more thoroughly!)... 

We want to make these changes:
- [ ] The encouragement program is being shown as selected, even though it was not selected and 0 points were awarded (seems to happen for all projects)
- [ ]  The earned points does not actually apply for the "required parking calculation" and so we want to remove that column and right justify the other data. 
- [ ]   We want to rename "required parking calculation"  to "Project Specifications" to be consistent
- [ ]  We want to change the label on the figures at the bottom from pts to spcs

![Screen Shot 2020-06-24 at 4 18 42 PM](https://user-images.githubusercontent.com/49739276/85637827-13cfd480-b639-11ea-8c55-a17a34ce7a0d.png)

This screenshot from "Different Version of Clarendon Apartments" saved in the LADOT@dispostable.com account if you want to check it!

**Comment by alexchoiweb** [comment]
3/4 of requested changes implemented

For the encouragement program issue of being displayed when not selected, the cause of this could be that the rule is being sent back with these properties (even when not selected): `used:true, value: true`

My guess would be we should be expecting a `value: null` returned at the least, and then the frontend logic will hide the rule

@nclairesays Thoughts?

![Screen Shot 2020-06-29 at 3 56 15 PM](https://user-images.githubusercontent.com/35116846/86064353-b3b6a500-ba21-11ea-8a63-4d6ce9502da5.png)

**Comment by alexchoiweb** [comment]
3/4 of requested changes implemented

For the encouragement program issue - with some testing I see that toggling the dropdown for Encouragement Program in the wizard to a value that is not 'none' and then back to 'none' resolves the issue of the encouragement program rule being displayed in the final summary. I just can't save this change in the project with the account that I have.

Also I tested creating a new project and not using the encouragement program rule and found that the rule doesn't show in the final summary page, functioning as expected.

Let me know if there are more issues you find however

**Comment by nclairesays** [comment]
@alexchoiweb sending you info on slack with the login credentials for LADOT@dispostable.com account

**Comment by alexchoiweb** [comment]
Issue fixed for Clarendon Apartments using ladot@dispostable.com account but for every other issue the user will have to go through the process above and save which will resolve the issue.

Going forward new issues will not be generated when creating new projects and leaving the encouragment program dropdown to none

<img width="995" alt="Screen Shot 2020-06-30 at 10 43 14 AM" src="https://user-images.githubusercontent.com/35116846/86159103-a7345a00-babe-11ea-9af2-6a0b9d5f48fb.png">
