### ISSUE TITLE
Add tooltips to side bar 

### ISSUE THREAD

**Issue by KPHowley** [hackforla/tdm-calculator#433]
### Overview
Add tooltips for the terms in the sidebar, these are defined in the attached google doc

### Action Items

- [x] add tool tips so it pops up when hovering over the "?" in the sidebar

### Resources/Instructions
On 2nd Sheet of this document 
https://docs.google.com/spreadsheets/d/1Wq4yxRaS0EF0DCKdcyzmMjp3F6opF_VuiTOhf_qzrN8/edit?usp=sharing

**Comment by mmorgs** [comment]
@KPHowley i need permissions to access that google doc. sent a request. can u approve? thx!

**Comment by mmorgs** [comment]
https://docs.google.com/spreadsheets/d/1Wq4yxRaS0EF0DCKdcyzmMjp3F6opF_VuiTOhf_qzrN8/edit#gid=931994480

**Comment by mmorgs** [comment]
hey @Bishoy-Tawfik ! please add the following descriptions to the `rule` entries. let me know if u have any questions :)

**Project Level**
`The City assigns a Project Level based on project size and use activity, which is reflective of the project’s transportation demand related to the project's scope of activities. The Project Level informs progressive compliance and monitoring requirements of the TDM program.`

**Target Points:**
`The Point Target establishes the total number of points a project must meet by selecting from the list of TDM strategies. Target points are a function of Project Level and the total parking supply of a project.`

**Earned Points:**
`Each TDM strategy has been assigned a point value a project applicant can select and implement to meet its Point Target. The slection of TDM strategies informs the total earned points. This should be referenced to determine when the project meets the Target Points.`

**Comment by Bishoy-Tawfik** [comment]
hey @mmorgs , the calculation rules above have been updated. Please let me know for any issue.

**Comment by jahpe777** [comment]
I added tooltip messages within the Project Wizard for the Sidebar section - "Project Level”,  "Target Points", and "Earned Points".

<img width="1438" alt="1" src="https://user-images.githubusercontent.com/40730303/89596040-12cebd00-d80b-11ea-91e7-a8885a858606.png">
<img width="1438" alt="2" src="https://user-images.githubusercontent.com/40730303/89596106-385bc680-d80b-11ea-9efb-252793e8875e.png">
<img width="1439" alt="3" src="https://user-images.githubusercontent.com/40730303/89596124-3e51a780-d80b-11ea-8fdb-6afd25ca99c8.png">
