### ISSUE TITLE
Update TDM measures, point values, and tool tips

### ISSUE THREAD

**Issue by KPHowley** [hackforla/tdm-calculator#437]
### Overview

Some of the TDM measures,the point values associated, and the tool tip descriptions, have changes recently, and so we need to update them in the backend

### Action Items

- [x] Update measures in the database with new point values
- [x] #474 -Add drop downs for measures with new point ranges 
- [ ] Add new measures to database
- [x] Update tool tips

### Resources/Instructions
This issue has been split into: 

- [ ] #474, 
- [x] #476, 
- [ ] #477, 
- [ ] #478, 
- [ ] #479

- [Latest TDM Strategies, Tooltips & Project Specification Inputs ](https://docs.google.com/spreadsheets/d/1LBGlYyj3kiRb9p0UNCWRo9DZVRFAFNEeccCjkCT5jek/edit?usp=sharing) *Changes are noted in orange, Slack Kevin if you need access

**Comment by KPHowley** [comment]
@Dsomers74  - We just wanted to double check that the strategies with lines through them on the - [Latest TDM Strategies, Tooltips & Project Specification Inputs ](https://docs.google.com/spreadsheets/d/1LBGlYyj3kiRb9p0UNCWRo9DZVRFAFNEeccCjkCT5jek/edit?usp=sharing) - document are to be deleted completely. Let us know so @entrotech can finish updating this!

**Comment by Dsomers74** [comment]
Affirmative Kevin. Some of the strategies strikethrough have been renamed,
consolidated, or combined with other strategies, though they can be removed
from the Calculator as described.

**Comment by entrotech** [comment]
I split this issue out into several development issues to "divide and conquer", and give Claire and Bishoy some practice with modifying rules.  These changes are split out into issues #474, #476, #477, #478, #479

**Comment by entrotech** [comment]
I'm going to consider all the sub-issues under this one closed, and suggest that we take additional requests or changes under this issue as an umbrella for changes to measures. It was useful to split the issue into parts for the developers to implement as a team, but now additional changes can be attached to this issue.
