### ISSUE TITLE
Phase 2: Develop user registration functionality

### ISSUE THREAD

**Issue by entrotech** [hackforla/tdm-calculator#44]
This will be a farily typical SPA user registration and login.  Adding roles, etc. will be a separate issue.

- [x] Back-End Web API implementation
- [x] Front-End functionality
- [x] Front-End User Notifications to replace console.log
- [ ] Cosmetic clean-up

**Comment by nclairesays** [comment]
I've created the backend registration routes.
I"m going to go ahead and create the front end registration component.

@pelmini is working on the Login Frontend component

**Comment by entrotech** [comment]
Here's a video showing how registration works in Food Oasis - this is pretty much what I expect to implement for TDM.

https://www.loom.com/share/e11a92f6878d48adac9ed65c947770af

**Comment by entrotech** [comment]
Also added a GitHub markdown page describing in detail how the registration/login features are intended to work: https://github.com/hackforla/tdm-calculator/blob/master/register.md

**Comment by entrotech** [comment]
I believe this is working, though it needs to be thoroughly tested per the register.md process description, including all the "unhappy paths".  In the Register.js component, I put a TODO comment where we need to add user notifications, to let the user know what happened and/or what to do next. I'll let somebody else pick up this issue and complete it :)

**Comment by nclairesays** [comment]
This is already moved from review to done. Closing this issue.
