### ISSUE TITLE
Realign project specifications and Levels with new Land Use Categories

### ISSUE THREAD

**Issue by KPHowley** [hackforla/tdm-calculator#443]
### Overview

We are going to realigned and altering the categories on the project specification page to fit into new land use categories. 

### Action Items

- [x] Get design new land use category break titles and breakdown from LADOT  ([TDM Strategies - Hack for LA -Tab 4 ](https://docs.google.com/document/d/185LUz5VI0VoBp4kDx0KSZ_pI1zzXfgdB0PlsIgJvxx8/edit))
- [x] Get the parking values formulas associated with each new input (spots per unit)  if needed 
- [ ] Finalize units, titles, and max values or any other details on inputs.
- [ ] Review Level Document to reflect these as well (if needed)

- [ ]  update [Strategies List and Applicable Land Uses ](https://docs.google.com/spreadsheets/d/1_VjRefk_7ch-eqIHK_gHIUXwcTYtvM0FO07K7gaqKGg/edit#gid=0)

### Resources/Instructions

[TDM Strategies - Hack for LA - 2020.04.08](https://docs.google.com/document/d/185LUz5VI0VoBp4kDx0KSZ_pI1zzXfgdB0PlsIgJvxx8/edit)

[Strategies List and Applicable Land Uses ](https://docs.google.com/spreadsheets/d/1_VjRefk_7ch-eqIHK_gHIUXwcTYtvM0FO07K7gaqKGg/edit#gid=0)

**Comment by Dsomers74** [comment]
Realign the project specifications categories with Land Use Categories in [Table 1](https://docs.google.com/document/d/185LUz5VI0VoBp4kDx0KSZ_pI1zzXfgdB0PlsIgJvxx8/edit) as further defined in Column B in the ['Land Use Redesign' worksheet](https://docs.google.com/spreadsheets/d/1LBGlYyj3kiRb9p0UNCWRo9DZVRFAFNEeccCjkCT5jek/edit#gid=353819215)

**Comment by Dsomers74** [comment]
The revised land use categories will not too be checked with TDM strategies in the land use correspondance table (reference [issue #437](https://github.com/hackforla/tdm-calculator/issues/437))

**Comment by awikstrom-ladot** [comment]
https://docs.google.com/spreadsheets/d/1LBGlYyj3kiRb9p0UNCWRo9DZVRFAFNEeccCjkCT5jek/edit#gid=1209152938

I've created a new tab with a proposed reorganization of land use categories.

**Comment by KPHowley** [comment]
@awikstrom-ladot @Dsomers74 _ thanks for the updated Tab!

 -  Just to be sure: The unit for high school is students, that determines level (exactly the same as other school inputs) and  the user should be required to fill out one of the other two options, sq foot of auditorium or # of seats auditorium, which determines parking,  and has the same parking calculations as the current auditorium inputs in special uses - Correct?

- The only other thing we need to work figure out now is  [Strategies List and Applicable Land Uses](https://docs.google.com/spreadsheets/d/1_VjRefk_7ch-eqIHK_gHIUXwcTYtvM0FO07K7gaqKGg/edit#gid=0)

**Comment by awikstrom-ladot** [comment]
Yes. The number of parking spaces for high schools is determined by the square footage of the auditorium (if there are no seats) or the number of seats. The calculator has the correct ratios. @Dsomers74  can you confirm that what I said fits?

**Comment by Dsomers74** [comment]
Yes, Auditorium (seats or sq ft) determines the baseline parking, and students determines the levels. Thanks Xander. 

Similar with hospitals/convalescent care where beds determines the baseline parking, and sq ft determines the levels.

**Comment by Dsomers74** [comment]
Realign the project specifications categories with Land Use Categories in Table 1 as further defined in Column B in the '[Land Use Redesign](https://docs.google.com/spreadsheets/d/1LBGlYyj3kiRb9p0UNCWRo9DZVRFAFNEeccCjkCT5jek/edit#gid=1209152938)' worksheet (**Updated Link**)

**Comment by entrotech** [comment]
Implementation issues are #451, #452, #494

**Comment by entrotech** [comment]
@Dsomers74 @KPHowley In the previous version of the level calculation there was a calculation for Arena/STadium/Theater w/o seats where if sq ft > 250000 then Level 3, if sq ft > 50000 then Level 2, if sqft > 25000 then Level 1. Do we want to keep this rule or does the Project Level calculation no longer consider Arena/Stadium/Thaters w/o seats?

**Comment by Dsomers74** [comment]
Yes, for now, we want the rule for Stadium/Theatre Levels to be set by the
range of seats in Table 1
<https://docs.google.com/document/d/185LUz5VI0VoBp4kDx0KSZ_pI1zzXfgdB0PlsIgJvxx8/edit>
.


The baseline Parking rule = 1 per 35 square feet or 1 per 5 fixed seats


I realize that sets up a Level quandary for uses with no fixed seats. This
will be fairly novel, and something we can address as a long term fix.

**Comment by entrotech** [comment]
PR #495  - released to tdmdev.azurewebsites.net - development environment
