### ISSUE TITLE
UI/UX: Mock up ways to decribe employment and residential bundles  'Transportation Demand Strategies' page

### ISSUE THREAD

**Issue by KPHowley** [hackforla/tdm-calculator#444]
### Overview
The bundles descriptions need some more explaining for the user, 

### Action Items

- [x] Mock up adding linkage between measures included in each bundle on the page itself
        - add dashed and dotted lines to link measures included 

Mock up three ways of explaining the packages to the user:
- [x] Mock up for a pop up or other way of explaining the packages on the measure selection page
- [ ] Mock up adding a page in between the two that explains the packages and what the user qualifies for  
- [ ] Mock up adding an explanation to the Calculate TDM Target Points for the packages and what the user qualifies for.

**Comment by dreams0ng** [comment]
CHANGES
- [ ] Mock up adding linkage between measures included in each bundle on the page itself
 add dashed and dotted lines to link measures included

*I need further clarification before I can move forward on this

Mock up three ways of explaining the packages to the user:
- [X] (1) Mock up for a pop up or other way of explaining the packages on the measure selection page
- [X] (2) Mock up adding a page in between the two that explains the packages and what the user qualifies for
- [X] (3) Mock up adding an explanation to the Calculate TDM Target Points for the packages and what the user qualifies for.

MOCKUPS
1
![2](https://user-images.githubusercontent.com/22779768/89080845-dc8eca80-d33e-11ea-95bf-d8529bf54392.png)

2
![3](https://user-images.githubusercontent.com/22779768/89080858-e44e6f00-d33e-11ea-9969-8ef80bdd0e31.png)

3 *This is a tight fit and would either need a resize or scroll element
![4](https://user-images.githubusercontent.com/22779768/89080868-e87a8c80-d33e-11ea-8e35-fa75d078ca53.png)

LINKS
https://www.figma.com/file/6h72XLxK76m4INtsSu8Mt0/TDM-Calculator-Copy?node-id=2273%3A125

**Comment by dreams0ng** [comment]
CHANGES:

- [X] Mock up adding linkage between measures included in each bundle on the page itself - add dashed and dotted lines to link measures included

Amber and I added the dashed lines and arrow boxes at the intersections.

MOCKUP:
![Screen Shot 2020-08-04 at 10 20 04 AM](https://user-images.githubusercontent.com/22779768/89327247-78bb1900-d640-11ea-89b3-9a980da02422.png)

LINKS:
https://www.figma.com/file/6h72XLxK76m4INtsSu8Mt0/TDM-Calculator-Copy?node-id=0%3A1

**Comment by KPHowley** [comment]
@dreams0ng @amberyou   - after hearing from LADOT that we do want to make it so the packages are only available for level 1 projects, We are going to propose a separate page to come up, I am going to put in a little work on this now!

**Comment by KPHowley** [comment]
I mocked up and prototyped two pages, one for two packages and one for one packages:

**1. Mockup for one Package being available:** 
![1 package mockup](https://user-images.githubusercontent.com/49739276/90076179-e952dd00-dcb3-11ea-87e0-e94cdb3be2ad.png)

**Prototype**
https://www.figma.com/proto/qNgPc5lttpf0SWSwkbbWyT/TDM-Calculator?node-id=2172%3A11468&viewport=-28%2C456%2C0.25&scaling=min-zoom


**2. Mockup for two Packages being available:** 
![Mockup - 2 Packages](https://user-images.githubusercontent.com/49739276/90076262-21f2b680-dcb4-11ea-9f3a-86bc4e3fb15a.png)

**Prototype**
https://www.figma.com/proto/qNgPc5lttpf0SWSwkbbWyT/TDM-Calculator?node-id=2172%3A11538&viewport=526%2C45%2C0.5&scaling=min-zoom

**Figma**
https://www.figma.com/file/qNgPc5lttpf0SWSwkbbWyT/TDM-Calculator?node-id=2172%3A11480

**Comment by KPHowley** [comment]
After discussing on Wednesday 8/12, we realized the use case where both projects are selected needs to be shown, here is a new mock up showing what happens when both packages are selected:

![Two Packages V2](https://user-images.githubusercontent.com/49739276/90317110-fc47f600-dedb-11ea-81d7-f1e907b62a50.png)


https://www.figma.com/proto/qNgPc5lttpf0SWSwkbbWyT/TDM-Calculator?node-id=2172%3A11538&viewport=157%2C143%2C0.25&scaling=min-zoom

**Comment by ExperimentsInHonesty** [comment]
Single Package Message:
All LEVEL 1 projects qualify for at least one optional bonus package.  Based on your land use you qualify for the package below:

Both Packages Message: 
All LEVEL 1 projects qualify for at least one optional bonus package.  Because of your land uses you qualify for both packages.  Here is a breakdown of each package, and point totals when both are selected:

**Comment by KPHowley** [comment]
@Dsomers74 @awikstrom-ladot 

Here are two mock ups for a conditional page that will appear for level one users to whom packages are applicable. After discussing we felel a page is the best way to explain packages, and since it will only be shown to users who are level 1 we don't believe it will burden users with unnecessary information. 

If approved we can add these pages in conjunction with rules which only show the bonus packages buttons  to Level one users. Please review the wording we have used as well to make sure it is correct. 


1. Page when two Packages are applicable
![One Package V3](https://user-images.githubusercontent.com/49739276/90453640-0584be80-e0a6-11ea-8241-58ce71e53cce.png)
https://www.figma.com/proto/qNgPc5lttpf0SWSwkbbWyT/TDM-Calculator?node-id=2172%3A11538&viewport=157%2C143%2C0.25&scaling=min-zoom

2. Page when one package is applicable
![Two Packages V3](https://user-images.githubusercontent.com/49739276/90454011-e8042480-e0a6-11ea-92db-2c89b1358de8.png)

https://www.figma.com/proto/qNgPc5lttpf0SWSwkbbWyT/TDM-Calculator?node-id=2172%3A11538&viewport=-301%2C85%2C0.5&scaling=min-zoom

**Comment by ExperimentsInHonesty** [comment]
@Dsomers74 please review the images above https://github.com/hackforla/tdm-calculator/issues/444#issuecomment-675165484 and let us know if you are signing off on this addtion or have questions/comments

**Comment by Dsomers74** [comment]
I am linking here to the [TDM Package Tool Tip](https://docs.google.com/document/d/1Fa9yyxAM0ahG3TFbu1-7q47Gv-PgetIADmLmlyI7kfE/edit) which explains why we provide the option/incentive.

**Comment by ExperimentsInHonesty** [comment]
@Dsomers74 I did little suggested rewrite of the tool tip.  I added it below your draft in this [document](https://docs.google.com/document/d/1Fa9yyxAM0ahG3TFbu1-7q47Gv-PgetIADmLmlyI7kfE/edit). Can you take a look?

Bonnie

**Comment by KPHowley** [comment]
### Version 1 (Before re-write)
Here are more options of the mock up with the added Text:

![Mid- 2 - alt](https://user-images.githubusercontent.com/49739276/91912180-7233b780-ec67-11ea-80b9-62391218d254.png)
### Version 2 (added Copy)
![Mid- 2 V3](https://user-images.githubusercontent.com/49739276/91912261-9becde80-ec67-11ea-9ec8-c337f9e0440e.png)
### Version 3 (with Tool tip)
![Mid- 2 V4 with tooltip](https://user-images.githubusercontent.com/49739276/91912312-b1fa9f00-ec67-11ea-8086-019b10053346.png)

**Comment by KPHowley** [comment]
FINALIZED DESIGNS:

![Mid- 2 V4 without  tooltip](https://user-images.githubusercontent.com/49739276/93424200-67cf0b80-f86c-11ea-98f5-c93534b4bf1b.png)
![Mid- 2 V4 with tooltip](https://user-images.githubusercontent.com/49739276/93424201-69003880-f86c-11ea-8a65-e9ffd7626523.png)
![Mid - 1](https://user-images.githubusercontent.com/49739276/93424207-6a316580-f86c-11ea-9fe5-9170fd025a9d.png)




https://www.figma.com/file/qNgPc5lttpf0SWSwkbbWyT/TDM-Calculator?node-id=2301%3A11744
