### ISSUE TITLE
Add form input field validations to Duplicate Project Modal

### ISSUE THREAD

**Issue by nclairesays** [hackforla/tdm-calculator#445]
Current behavior of the form input fields in the duplicate project modal:
- no validations
- can enter empty string

Action Items:

- [x] If the user enters a blank project name please save the project as the previous project name and "(Copy)"

**Comment by jahpe777** [comment]
Added form input field validations to Duplicate Project Modal #445

https://www.dropbox.com/s/v1mene8lvw6zf8s/Screen%20Recording%202020-12-06%20at%2012.58.55%20PM.mov?dl=0
