### ISSUE TITLE
Add Alternate Residential Land Use Entry

### ISSUE THREAD

**Issue by KPHowley** [hackforla/tdm-calculator#447]
### Overview
Add another residential land use entry that requires parking per dwelling unit w/ 2 spaces per dweling unit as baseline. we want this to be displayed as an alternative to the normal residential uses with a method to select this instead and make the other inputs unaccesable. 

### Action Items
TBD

### Resources/Instructions
TBD

**Comment by Dsomers74** [comment]
We are evaluating and will provide instruction from team as there are more detailed requirements in specific areas of the City. We still need the functionality of conditional entry, though the baseline details may change. Resolution pending July 1st.

**Comment by Biuwa** [comment]
**2023-02-07 STAKEHOLDER MEETING NOTES:**
Emily: potentially related to specific plans that have different parking requirements from city baseline requirements - also probably not required.  We could try to follow up with David, but neither Alexander nor Emily had any other knowledge or input.  There are also statewide regulations that might keep the city from imposing regulations.

**Comment by Biuwa** [comment]
No additional action needed
