### ISSUE TITLE
Add responsiveness or scrollbar to project table

### ISSUE THREAD

**Issue by nclairesays** [hackforla/tdm-calculator#449]
(Needs design decision)

Current behavior: When screen size is smaller, part of the project table is hidden and cannot be viewed. 

Suggestion for design: either add a scroll bar, or change how the project is responsive.

### Update action items (10/28):

- [ ] Add a basic level of responsiveness to the width of the Table 

- [ ] *if necessary* display a scroll bar when certain parts can not be viewed

**Comment by Jonathanko52** [comment]
![Preview](https://user-images.githubusercontent.com/30099154/99046366-7f163680-2547-11eb-8f73-70222ee41741.png)

Table shrinks to fit window. Scroll bar appears if window becomes too small to fit table. Do we want the margins on the sides to shrink as the window does so the table fits better, or do we want the margins to stay the same size?

**Comment by Jonathanko52** [comment]
Scrolling Bar inserted when window gets too small to render table without squishing things.
![image](https://user-images.githubusercontent.com/30099154/99465116-7a0e0a00-28ee-11eb-9638-8eb1dc4c32b6.png)
