### ISSUE TITLE
Always default bicycle parking as selected strategy 

### ISSUE THREAD

**Issue by KPHowley** [hackforla/tdm-calculator#450]
### Overview

Bicycle parking is required on all new projects, and so we want it to be checked off as a default. 

### Action Items

- [x] Come up with note for bicycle parking. 
- [x] Update bicycle parking to be selected as a default

Updated items as of 8/12
- [x] Update bike parking to be un-selectable, however not un-selected when the page is reset. 
- [x]  add " (required on all new developments)" on line next to bike parking. 

### Resources/Instructions
.

**Comment by KPHowley** [comment]
![Bike Parking notification](https://user-images.githubusercontent.com/49739276/86987070-0d1d8300-c14a-11ea-8148-df3177b8128e.png)
This image shows one option for notifying a user - we need to decide if this should be used, if nothing is needed, or if this should be added to the tooltip.

**Comment by entrotech** [comment]
Implemented selecting as a default
@KPHowley Still need to decide on how to show the note.

**Comment by KPHowley** [comment]
Per our meeting yesterday - Bike parking should be un-selectable, however should not be reset along with all other strategies when "reset page" is selected at the top of the page....
