### ISSUE TITLE
Add a Checkbox for "100% Affordable Housing" on Project Specification Page to only require Level 1

### ISSUE THREAD

**Issue by KPHowley** [hackforla/tdm-calculator#451]
### Overview
Projects that are 100% affordable should always be level 1 and so we want to add a checkbox on the second page so users can select this option. 

### Action Items

- [x] Determine where this needs to be placed
- [x] Determine if there's any other ramifications
- [x] Determine wording to put next to checkbox
- [x] Go over edge cases with LADOT (mixed use?)
- [x] implement changes

**Added Items on 8/5:**

- [ ] Change wording to "Does this project qualify as 100% Affordable Housing"
- [ ] Please change rules to only force 100% affordable housing to only affect the residential portion of the calculation. All residential inputs should only contribute to a unit being level one, however any additional use types can bring the project above that level. 

### Resources/Instructions

**Comment by KPHowley** [comment]
@Dsomers74 - Before we add this we just want to make sure we know how to deal with some edge cases. Should the 100% affordable check force all projects to be Level 1, even mixed use projects with large retail or commercial parts? Or is The 100% affordable only applicable for residential projects?  Perhaps these mixed use projects won't qualify for the official  designation.

Also, for the text displayed next to the checkbox would something like -  "Does this project qualify as 100% Affordable Housing" work for you? 

Let us know, and we can get this going!

**Comment by Dsomers74** [comment]
Hi Kevin, yes to all 100% Affordable Projects would be Level 1. There are
logistical financing requirements that would make it difficult for mixed
use projects to qualify for housing funds that these projects rely on, and
even if they did, our intent is to allow it as an incentive.

That check-box description works for me.

**Comment by entrotech** [comment]
PR #495

**Comment by KPHowley** [comment]
@Dsomers74 - Currently this has been implemented, and there is a checkbox that forces any project to become level 1 if checked. Please let us know if you do want us to disable any other inputs or do anything else to make sure user's don't use this option when they should not. 

If people need to apply for 100% affordable housing status I would suggest changing this to  "Has this project been approved as 100% Affordable Housing?" otherwise we can just change the text next to the box to "Does this project qualify as 100% Affordable Housing?"

**Comment by KPHowley** [comment]
@entrotech Per our stakeholder meeting on 8/4:

- [ ] Change wording to "Does this project qualify as 100% Affordable Housing"
- [ ] Please change rules to only force 100% affordable housing to only affect the residential portion of the calculation. All residential inputs should only contribute to a unit being level one, however any additional use types can bring the project above that level.

**Comment by Dsomers74** [comment]
👍
