### ISSUE TITLE
Select Bundle as a default based on Land-Use, and option to customize

### ISSUE THREAD

**Issue by KPHowley** [hackforla/tdm-calculator#453]
### Overview
We're interested in making the bundles for employment and commercial defaults, and need to discuss possible ramifications & implementation. 

### Action Items

- [ ] Discuss ramifications of this and how the user might be informed
- [ ] discuss edge cases 
- [ ] Dscuss coding issues

- [ ] implement changes if necessary

**Comment by ExperimentsInHonesty** [comment]
@KPHowley  John thinks this is obsolete now.  Please confirm and if it is, close with comment

**Comment by ExperimentsInHonesty** [comment]
Kevin agreed that it is obsolete.
