### ISSUE TITLE
An Admin should be able to create and maintain calculations

### ISSUE THREAD

**Issue by entrotech** [hackforla/tdm-calculator#46]
### Dependencies
- [x] After all the issues in the prioritized backlog have milestones, release dependency and prioritize this. 

### Overview
LADOT would like a feature where they can perform CRUD operations on strategies so that they can keep a tool current with the regulation.

### Action Items
- [ ] Define requirements (e.g. what happens to saved projects when a strategy change is made)
   - [ ] Auditability 
   - [ ] User Notifications
   - [ ] Administrator Screen
   - [ ] Edge Case Scenarios

#### Tables involved
This is a CRUD feature against the Calculation table in the db. 

#### Who would use it and why
It would be used by an admin to create and maintain different types of calculations (maybe TDM for other cities with different rules, test calculations or calculations for completely different purposes, such as carbon tax credits, property tax rates, etc.).

**Comment by agosmou** [comment]
This is stale and will not be implemented per [comment](https://github.com/hackforla/tdm-calculator/pull/1521#issuecomment-1820080783)
