### ISSUE TITLE
Delete the landing page, and redirect or delete the Home button on Navbar

### ISSUE THREAD

**Issue by KPHowley** [hackforla/tdm-calculator#462]
### Overview
The LADOT has requested that we remove the landing page from the Calculator, and to have users directed to login.

### Action Items

- [x] Decision  - Redirect the home button on the Navbar to Login in/ or Delete completely 
- [ ] Remove the landing page from the website
- [x] Redirect routes

**Comment by alexchoiweb** [comment]
-Removed "Home" link from Navbar
-Redirected path "/" to "/login"

https://streamable.com/foozi8

**Comment by KPHowley** [comment]
Hey @alexchoiweb, 

this loos good to me can you put in a pull request for it if you haven't already.
