### ISSUE TITLE
Bug: clicking "Create project" when in the wizard directs to /calculation instead of /calculation/1/

### ISSUE THREAD

**Issue by KPHowley** [hackforla/tdm-calculator#463]
### Overview

Clicking "Create project" when in the wizard directs to /calculation instead of /calculation/1/ this causes a blank page to review, since we have not disabled the button we should make it function like other buttons and go to /calculation/1/

### Action Items

- [x] fix routes in front end.

**Comment by jahpe777** [comment]
I updated the route for the "create project" button within the NavBar. 

<img width="1438" alt="200712_#463_1" src="https://user-images.githubusercontent.com/40730303/87256837-d649b480-c44a-11ea-971a-36e0dc2321e4.png">
