### ISSUE TITLE
Change wording on Measure selection Page to "Reset All Strategies”

### ISSUE THREAD

**Issue by KPHowley** [hackforla/tdm-calculator#466]
### Overview
Change wording on Measure selection Page to "Reset All Strategies” to be consistent with the single page view.

### Action Items

- [x] Change wording

**Comment by jahpe777** [comment]
I changed the wording on Measure Selection Page to "Reset All Strategies” to be consistent with the single page view.

![Screenshot 2020-07-14 14 34 44](https://user-images.githubusercontent.com/40730303/87488404-249ab700-c5f5-11ea-89cd-97dc1788a158.png)

![Screenshot 2020-07-14 17 25 36](https://user-images.githubusercontent.com/40730303/87489178-341aff80-c5f7-11ea-8696-1149911dea3b.png)
