### ISSUE TITLE
Update TDM Strategies with multiple values, via drop downs  

### ISSUE THREAD

**Issue by KPHowley** [hackforla/tdm-calculator#474]
### Overview
There are some TDM strategies which now have multiple choices available to users, so drop down selection menus need to be added and adjusted on the Strategy page. 

### Action Items

- [x] Identify all changes
- [x] Alter old menus now with Drop down choices
- [ ] Add new drop down menus for items with choices

### Resources/Instructions
Connected to #437 

- [Latest TDM Strategies, Tooltips & Project Specification Inputs ](https://docs.google.com/spreadsheets/d/1LBGlYyj3kiRb9p0UNCWRo9DZVRFAFNEeccCjkCT5jek/edit?usp=sharing) (slack Kevin is you need access)

**Comment by Bishoy-Tawfik** [comment]
@KPHowley Hey Kevin, for the points update for all the strategies associated to 474, are they all drop downs? and if the answer is  yes, then what should be the text of each option for line 57 and 61 in the Excel sheet, because the current text seems too long for a drop down.

**Comment by Bishoy-Tawfik** [comment]
@KPHowley Hey Kevin, as we discussed once the pull request is approved and the changes have been deployed to dev, please review and let me know if I need to update any drop down text.

**Comment by entrotech** [comment]
@DSomers @KPHowley @Bishoy-Tawfik These changes are deployed and available on tdmdev.azurewebsites.net. 

However, the Pricing/Unbundling strategy is also part of the Residential Package, and no changes were made to the logic for the residential package, which brings up the following questions:
1. When the user presses the button or otherwise selects the Residential Package, which "level" of unbundling should be selected. I'm guessing it's the $220 level, since that would earn them the same number of points, but wanted to check.
2. if they also select Bike Parking and one of the "Encouragment Programs", then do they get the Residentail Package Bonus point for any level of Unbundling, or do they have to pick the $220 level to get the package bonus point?

**Comment by entrotech** [comment]
@DSomers @Bishoy-Tawfik 
I went ahead and implemented the changes to the Residential Package logic as described in the previous comment and deployed to tdmdev.azurewebsites.net

**Comment by KPHowley** [comment]
@entrotech @Bishoy-Tawfik  - I have a couple thoughts on this, but @Dsomers74 can you answer John's 2 questions and let me know  if you disagree with me on anything else. 

- Reduced Parking Supply

   ![Screen Shot 2020-08-01 at 3 46 43 PM](https://user-images.githubusercontent.com/49739276/89111772-9f920900-d40e-11ea-96c2-3f8b0cc630aa.png)

    For this, I would propose that we change the wording to "Reduces XX% of the spaces available relative to the baseline" To limit the length on the text. On my browser the text box offer flows into the next column, and this is not ideal. 
 
- Shared Parking

 ![Screen Shot 2020-08-01 at 3 47 36 PM](https://user-images.githubusercontent.com/49739276/89111781-a4ef5380-d40e-11ea-969d-7b61c884d410.png)
 
    On this I would suggest changing "< 25% improved" to None (or N/A)  to be consistent with the rest of the drop downs. 

- Pricing/Unbundling
![Screen Shot 2020-08-01 at 4 24 37 PM](https://user-images.githubusercontent.com/49739276/89112156-90fa2080-d413-11ea-8e05-64e3ed82b513.png)

    I would just make sure "The" is capitialized in this.  but I also want to reiterate John's questions on this:

    1. When the user presses the button or otherwise selects the Residential Package, which "level" of unbundling should be selected. I'm guessing it's the $220 level, since that would earn them the same number of points, but wanted to check.
    2.  if they also select Bike Parking and one of the "Unbundling" strategies, then do they get the Residentail Package Bonus point for any level of Unbundling, or do they have to pick the $220 level to get the package bonus point?


- I would also actually suggest just changing none to "N/A" as well

David, if you want to review just look at all of the strategy drop downs on the https://tdmdev.azurewebsites.net website

**Comment by KPHowley** [comment]
@entrotech @Bishoy-Tawfik - Per our conversation Yesterday, we want to make the following changes to these drop downs: 

- [ ] Change the wording  on pricing/unbundling to "The cost of each parking space is at least $XX a month"
- [ ] Change the wording from none (or anything else) to "N/A" as the on all strategies as the 1st option, awarding no points
- [ ] Change wording on Reduced Parking supply to "Reduces XX% of the spaces available relative to the baseline"

*We also verified that only parking sots with costs of at least $220 will contribute to the package, this is the current implementation so no change is needed

**Comment by Dsomers74** [comment]
Hi Kevin, verifying that this is the direction.
Thanks.

**Comment by KPHowley** [comment]
As the drop down options  were still very long with the previously mentioned wording, please make to following changes:

- [ ] Change the wording on pricing/unbundling to "Each parking space is at least $XX a month"
- [ ] Change wording on Reduced Parking supply to "Reduces XX% of spaces available"

*changing none to N/A has been made it's own issue
