### ISSUE TITLE
Implement a Public Comment Form

### ISSUE THREAD

**Issue by entrotech** [hackforla/tdm-calculator#481]
### Overview
During the public comment period, the application will need a feature that allows the public to submit comments.

We need to design this, and thn move it to front end and back end development 

### Action Items

**UI/UX**
- [ ] Decide on where to put the link to the form - it will probably be a main menu item. Implement the link to open the Public Comment form:
- [ ] add Disclaimer on the form - "Comments submitted will be part of the public record"
 - [ ] Create a modal dialog form for the Public to make a comment. It should accept the following fields:
                   - User Name: (required, can b ea single field)
                   - User Email: (optional, but if supplied, validate that the format is a valid email address)
                   - Comment required (TextArea with large number of characters allowed)
                   - Checkbox to indicate if the comment should be forwarded to the web site developers as well as the City.

**Development**
- [ ] Create a database table named suggestion with an id primary key identity column, columns for each of the input fields, dateCreated, dateModified and modfiedLoginId columns, and a non-null integer commentStatusId column initialized to the value of 1 (meaning a "new" comment).
- [ ] Create a web api endpoint that handles a POST request to /api/comments and inserts a new record into the database, using a stored procedure named Comment_Insert.
- [ ] Create a client-side service that calls the above endpoint, and wire it up to the submit button of the Comment form

### Resources/Instructions
The UI/UX style should attempt to match the general styling of the existing "Register Page"
![image](https://user-images.githubusercontent.com/9939032/88236637-508bed00-cc32-11ea-97a0-9ca8eedbb78b.png)

**Comment by ExperimentsInHonesty** [comment]
@entrotech did you mean to indicate that the login page should mimic the login page of TDM.  I ask because you inserted a picture of FOLA sigin instead.  Here is the screen shot of TDM

![Screen Shot 2020-07-25 at 11 42 14 AM](https://user-images.githubusercontent.com/37763229/88472954-7385fd80-cecd-11ea-942d-ed95c417a58a.png)

**Comment by ExperimentsInHonesty** [comment]
@KPHowley Here are my mock ups, what else do you think we need language wise on the page?

either this style
![Screen Shot 2020-07-25 at 11 16 23 PM](https://user-images.githubusercontent.com/37763229/88473147-75e95700-cecf-11ea-9c63-d64f0b9213b8.png)

or this style

![Screen Shot 2020-07-25 at 11 33 44 PM](https://user-images.githubusercontent.com/37763229/88473158-83064600-cecf-11ea-9b51-8fd43021d364.png)

**Comment by dreams0ng** [comment]
CHANGES

- [X]  add Disclaimer on the form - "Comments submitted will be part of the public record"
- [X]  Create a modal dialog form for the Public to make a comment. It should accept the following fields:
- User Name: (required, can b ea single field)
- User Email: (optional, but if supplied, validate that the format is a valid email address)
- Comment required (TextArea with large number of characters allowed)
- Checkbox to indicate if the comment should be forwarded to the web site developers as well as the City.

MOCKUPS
*note for both: green lines indicate currently entered field
v1
![Screen Shot 2020-07-27 at 11 12 31 PM](https://user-images.githubusercontent.com/22779768/88626016-bc20f080-d05e-11ea-8c87-2dab09ff4e6e.png)

v2
![Screen Shot 2020-07-27 at 11 12 53 PM](https://user-images.githubusercontent.com/22779768/88626025-c0e5a480-d05e-11ea-9fc4-c9cfdf60a644.png)

LINKS
https://www.figma.com/file/6h72XLxK76m4INtsSu8Mt0/TDM-Calculator-Copy?node-id=0%3A1

**Comment by dreams0ng** [comment]
CHANGES
Corrected style elements 

MOCKUPS
![Screen Shot 2020-07-30 at 12 17 01 PM](https://user-images.githubusercontent.com/22779768/88964761-aed25480-d25e-11ea-8183-48b11b0f00ee.png)

LINKS
https://www.figma.com/file/6h72XLxK76m4INtsSu8Mt0/TDM-Calculator-Copy?node-id=0%3A1

**Comment by KPHowley** [comment]
@dreams0ng - After discussing trying to keep our styling consistent on Saturday we figured we would try and keep this design as close to the established style of the Wizard, which is similar to: 
![image](https://user-images.githubusercontent.com/49739276/90069422-22388500-dca7-11ea-9586-779cda6b7790.png)
I believe we can just merge this  with your design as we do need to keep the disclaimer and submit button.

**Comment by dreams0ng** [comment]
CHANGES
+merged approved comment form with submit button and disclaimer

MOCKUPS
![Screen Shot 2020-08-18 at 12 51 34 PM](https://user-images.githubusercontent.com/22779768/90558919-ae3c2800-e151-11ea-9b69-bdac93ebf775.png)

LINKS
https://xd.adobe.com/view/f32a7d21-a346-43a1-6e66-809bd1399976-851b/

**Comment by ExperimentsInHonesty** [comment]
David and Emily signed off on this in the meeting.

**Comment by Dsomers74** [comment]
We prefer to have all comments automatically routed to [ladot.TDM@lacity.org](url)

**Comment by nclairesays** [comment]
The designs above do not take into account the styling for validation error messages; for example, if someone entered an invalid email, a message will appear.   With the two column style for the label/input boxes, the input boxes will wrap depending on the length of the form label and error message that appear, which makes the form look really awkward:  ![image](https://user-images.githubusercontent.com/45305029/95718224-fdb74580-0c22-11eb-8a60-36901bb6dfb9.png)

So I've restyled the form/page to what I think is the next best option, while keeping in mind style consistency with the rest of the app, per @KPHowley's comment above.  I'm going to go ahead and make a PR with this so we can include it for this week's commit and get feedback on it. 
![image](https://user-images.githubusercontent.com/45305029/95721307-4113b300-0c27-11eb-9562-a672a7cb5b79.png)
![image](https://user-images.githubusercontent.com/45305029/95718526-70c0bc00-0c23-11eb-8441-933cb5149572.png)
