### ISSUE TITLE
Reconcile issues not showing up on any project board

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/tdm-calculator#485]
### Overview
There are open issues that are not on the project boards.

### Action Items

- [x] review the missing issues
- [x] assign them to the appropriate boards, or close them.

### Resources/Instructions
https://github.com/hackforla/tdm-calculator/issues?q=no%3Aproject+type%3Aissue+is%3Aopen+

**Comment by entrotech** [comment]
Most of these were duplicates or obsolete. The few that weren't I put in the Icebox or Prioritized backlog.
