### ISSUE TITLE
Make Trip Reduction Program, Travel Behavior Change Program &  Education, Marketing, Outreach Mutually exclusive 

### ISSUE THREAD

**Issue by KPHowley** [hackforla/tdm-calculator#497]
### Overview

According to the new TDM Strategy sheet, Trip Reduction Program, Travel Behavior Change Program  Education, Marketing, Outreach are all mutually exclusive, and for ease and consistency it would help to rethink these as a single choice with a drop down. 

### Action Items

- [x] Get approval for change from LADOT
- [x] Get updated name for the strategy and for each drop down
- [x] Know which subcategory of strategies this new one belongs to
- [x] Update all of this on: https://docs.google.com/spreadsheets/d/1LBGlYyj3kiRb9p0UNCWRo9DZVRFAFNEeccCjkCT5jek/edit#gid=0
- [x] Move to Back end for development

**Updated items from 8/5:**
 
After discussion, we should not make the above changes, and should make them mutually exclusive 

- [x] Once one of the options is chosen, grey out the other option on the page, but leave visible
- [ ] Add the note "*The Mandatory Trip Reduction and Encouragement programs are mutually exclusive" under whichever strategy is greyed out. 

### Resources/Instructions
https://docs.google.com/spreadsheets/d/1LBGlYyj3kiRb9p0UNCWRo9DZVRFAFNEeccCjkCT5jek/edit#gid=0

**Comment by entrotech** [comment]
@Dsomers74 @KPHowley 

There is one problem with this approach: The Mandatory Trip-Reduction Program is not applicable to the Residential (aka Housing) land use, but the other two choice are applicable to all land uses, and we don't have a way for a drop-down to apply different land-use exclusions to different choices in a list.  I'm working on a way to make different strategies mutually exclusive without combining them into a single multiple-choice strategy.

**Comment by entrotech** [comment]
This is also complicated by the fact that the Education, Marketing and Outreach and Voluntary Travel Behavior Change Program are part of the Employment Package.  If Mandatory Trip-Reduction Program is selected, will it also count toward earning a point for the Employment Package?

**Comment by KPHowley** [comment]
After discussion on the stakeholder meeting on 8/4, we should not make the above changes, and should make them mutually exclusive 

- [ ] Once one of the options is chosen, grey out the other option on the page, but leave visible
- [ ] Add the note "*The Mandatory Trip Reduction and Encouragement programs are mutually exclusive" under whichever strategy is greyed out.

**Comment by Dsomers74** [comment]
👍
