### ISSUE TITLE
Create Agenda July 23 2019

### ISSUE THREAD

**Issue by Rankazze** [hackforla/tdm-calculator#5]
### Overview
Gather all items team members want to propose for this weeks' agenda.

### Action Items
Add comment to this issue with your proposed agenda item. if item warrants an issue of its own please start a [new issue](https://github.com/hackforla/tdm-calculator/issues)

**Comment by entrotech** [comment]
If we can have a room with a functioning projector, I would like to show the Parking Calculation Spreadsheet and the prototype application, though this is a lower priority than the planning that the groupd started last week.

**Comment by entrotech** [comment]
Hopefully Rosemary will be there and we can discuss where to get the rules about how developers earn credits toward their target point goal.

**Comment by ramccarr** [comment]
I won't be able to make it tonight, and we're still ironing out a few of the rules. Out of caution, I'd prefer to defer this conversation until next week. I will keep you updated and am available to answer other questions.

**Comment by Rankazze** [comment]
Thanks Rosemary.  See you next week!
