### ISSUE TITLE
Develop privacy policy for the TDM Calculator website

### ISSUE THREAD

**Issue by KPHowley** [hackforla/tdm-calculator#505]
### Overview
 The TDM calculator is required to display a  privacy policy by law, and so we do need to develop one that will be linked to on the footer. 

### Action Items
- [ ] Product
   - [x] Develop proposed privacy policy 
   - [x] Review with  LADOT & Development
   - [x] Finalize copy
   - [x] Move issue to front end development. 

### Resources/Instructions
Sample privacy policy for 311 calculator - https://311-data.org/privacy
Legal overview- https://www.nolo.com/legal-encyclopedia/what-to-include-in-your-website-s-privacy-policy.html
[LATDM calc dev site](https://tdmdev.azurewebsites.net/privacypolicy)

Working Doc:
[LADOT & CfA approved Privacy Policy draft](https://docs.google.com/document/d/1zlGAsEjkBocqxW9osIhHs8EbHdquYdqm-yxSbd4ZjcM/edit)

It will look like this but more text (so a scroll bar will appear)
![Screen Shot 2020-12-05 at 11 34 03 AM](https://user-images.githubusercontent.com/37763229/101261671-e0b46580-36ed-11eb-8b37-a3c68a7f3082.png)

**Comment by KPHowley** [comment]
Working Doc: 
https://docs.google.com/document/d/1zlGAsEjkBocqxW9osIhHs8EbHdquYdqm-yxSbd4ZjcM/edit#heading=h.1kvk4qkoxhzw

**Comment by ExperimentsInHonesty** [comment]
@ExperimentsInHonesty will review

**Comment by KPHowley** [comment]
@ExperimentsInHonesty  - David and myself made some revisions to this but David had a comment in the working doc, we would like you to weigh in on.  - https://docs.google.com/document/d/1zlGAsEjkBocqxW9osIhHs8EbHdquYdqm-yxSbd4ZjcM/edit#heading=h.1kvk4qkoxhzw

**Comment by Rankazze** [comment]
I have conducted my review and comment pass.  Looking good.

**Comment by KPHowley** [comment]
@Rankazze  - It looks like there's some comments from Bonnie on language from the city that we should look into including, can you resolve?

**Comment by Rankazze** [comment]
@KPHowley @ExperimentsInHonesty @Dsomers74  I have completed a review and added suggestions for inclusion.  I reviewed the LA City Privacy Policy link provided and included appropriate sections (PII, Google Analytics opt-out, and Email address)

**Comment by ExperimentsInHonesty** [comment]
@Dsomers74 Can you review the latest changes that @Rankazze added in response to my review of the city links that you sent.  If it seems good to you, you can accept his changes and then send the link to your legal for review. https://docs.google.com/document/d/1zlGAsEjkBocqxW9osIhHs8EbHdquYdqm-yxSbd4ZjcM/edit#heading=h.1kvk4qkoxhzw

**Comment by Dsomers74** [comment]
@ExperimentsInHonesty Thanks! I reviewed and the changes look fine. I don't have edit access, so if you don't mind accepting the changes and I can reroute to City Attorney. They already reviewed an earlier version and did not have revisions.

**Comment by ExperimentsInHonesty** [comment]
@Dsomers74 I have accepted all the changes and made sure you have edit access to the doc

**Comment by Dsomers74** [comment]
@ExperimentsInHonesty I just added one minor change to [the draft Privacy Policy](https://docs.google.com/document/d/1zlGAsEjkBocqxW9osIhHs8EbHdquYdqm-yxSbd4ZjcM/edit).

**Comment by KPHowley** [comment]
@ExperimentsInHonesty   - Screen shot of Comment form. 

![Screen Shot 2020-10-31 at 11 01 43 AM](https://user-images.githubusercontent.com/49739276/97786392-806b5a80-1b68-11eb-88ad-65592a4c00ec.png)

**Comment by ExperimentsInHonesty** [comment]
@KPHowley @Dsomers74 - The privacy policy has been approved by CFA with no changes.  This issue has now been put in the queue for development to add the final version to the website:
[Privacy Policy](https://docs.google.com/document/d/1zlGAsEjkBocqxW9osIhHs8EbHdquYdqm-yxSbd4ZjcM/edit)

**Comment by ExperimentsInHonesty** [comment]
Created new issue for implementation #686
