### ISSUE TITLE
Bug: The toast to notify users after login information has timed out is displayed twice

### ISSUE THREAD

**Issue by KPHowley** [hackforla/tdm-calculator#506]
### Overview
After a user's is logged out due to having their security authentication time out, the toast which notifies them ids displayed twice. It should only be displayed once. 

### Action Items

- [x] Further document the issue 
- [x] Bug fix by front end(?)

**Comment by KPHowley** [comment]
@jahpe777  give us an update on:
    1. Progress
    2. Blockers
    3. Availability
    4. ETA

**Comment by jahpe777** [comment]
Edited the toast to only display once in order to notify users after login information has timed out. #506

![1](https://user-images.githubusercontent.com/40730303/97125143-27c33a00-16f0-11eb-83f5-9e00701ddf31.jpg)
