### ISSUE TITLE
Review and Fix Land Use Calculations and Parking Subtotal Calculations

### ISSUE THREAD

**Issue by entrotech** [hackforla/tdm-calculator#512]
### Overview
With the recent reorganization of Project Specifications, various inputs have moved around to different land uses. Review and fix the calculations that determine whether each land use is applicable to the project for given inputs.

### Action Items

- [ ] Modify the set of land use calculations to include those listed below
- [ ] Modify the corresponding calculation of whethe a project includes each land use per the new grouping of inputs under sections.
- [ ] Modify the parking calculation subtotals according to the new land uses.

### Resources/Instructions
The land uses are (the parenthesized text corresponds to the Section Header of the inputs on the Project Specifications Page)

- LAND_USE_RESIDENTIAL (AKA Housing)
- LAND_USE_HOTEL (Hotel / Motel)
- LAND_USE_RETAIL
- LAND_USE_COMMERCIAL (AKA Employment/Office)
- LAND_USE_WAREHOUSE (Warehouse Space)
- LAND_USE_MEDICAL (Medical Care
- LAND_USE_SCHOOL (Schools)
- LAND_USE_Other (AKA Special Usess)

The parking requirements for inputs from each land use are subtotalled and then rounded up to the nerest whole space, then totalled to arrive at the Parking Baselint.

**Comment by awikstrom-ladot** [comment]
[SUMMARY OF PARKING REGULATIONS_04-15-2020 (FINAL).pdf](https://github.com/hackforla/tdm-calculator/files/5043832/SUMMARY.OF.PARKING.REGULATIONS_04-15-2020.FINAL.pdf)
@Dsomers74 
Hello @entrotech and @KPHowley!

I'd like to add the method that schools calculate baseline parking requirements to the calculator. Elementary and middle schools (K-8) use the metric of 1 space per classroom. High schools (9-12) use either the auditorium ratios previously discussed (1 space per 5 seats or 1 space per 35 sf if no fixed seats) or 1 space per 500 sf of building area, whichever ends up being greater. I've attached the bulletin from City Planning explaining these ratios. Please let me know if I need to specify this any further.

Have a good weekend,
Xander Wikstrom
