### ISSUE TITLE
Make bike share membership strategy a hyperlink to: https://bikeshare.metro.net/for-business/

### ISSUE THREAD

**Issue by KPHowley** [hackforla/tdm-calculator#517]
### Overview
Make bike share membership strategy a link to: https://bikeshare.metro.net/for-business/ as a way to exlain the levels of gold silver and bronze 

### Action Items

- [ ] Add link to strategy

**Comment by KPHowley** [comment]
@Bishoy-Tawfik  - I just got around to reviewing this, and is there a way we can just make it so the strategy has an underline on it and appears as hyperlink - it's unclear that it links to anything as it is now, and is a little surprising when it is clicked on! I can make a new issues, unless this is simple!

**Comment by Bishoy-Tawfik** [comment]
@entrotech @nclairesays  - Hey John/Claire, this is a bit tricky for me. I'm applying the class {classes.textInputLabelAnchor} on the label but it's not showing up when the page is rendered, I believe I'm missing something, but not sure what it is. Could you please take a look and let me know what am I missing.

**Comment by nclairesays** [comment]
@Bishoy-Tawfik and @KPHowley where is the link? were you actually able to click on anything? is it just the underline style that's missing? can you take a screenshot where I should be looking?

**Comment by KPHowley** [comment]
@nclairesays @Bishoy-Tawfik  I can't get on the Dev site now, but the last time I was on it the " bike share membership" strategy was actually a link that brought me to  https://bikeshare.metro.net/for-business/ , however there was just no underline on it, so it was a  surprising interaction. I don't see this on the UAT site now though...

Here's what we did with another link on the first page, let m eknow if we can make it look like that:
![Screen Shot 2020-09-23 at 12 47 28 PM](https://user-images.githubusercontent.com/49739276/94062526-a64c5500-fd9b-11ea-88a6-bb79b1aeae8c.png)
