### ISSUE TITLE
Add warning and logic to require users to fill out any "sub" input boxes

### ISSUE THREAD

**Issue by KPHowley** [hackforla/tdm-calculator#518]
### Overview

There are several required fields when users select a 

### Action Items

Design:
 - [x] Come up with design for warning 
-  [x] Come up with wording 

*Per meeting on 8/8 no mock up is needed. 

Dev:
- [x] Implement logic to display message below or on  "sub" box when "main" box is checked
- [x]  make sure users can not advance unless box is filled in
- [x]   Add text:  "This  is a required with  _______ " for each message 

 

### Resources/Instructions

Warnings used on previous page:
![Screen Shot 2020-08-05 at 4 59 08 PM](https://user-images.githubusercontent.com/49739276/89475688-899d8480-d73d-11ea-84bf-4f602b682c00.png)

suggestion for design is to simply mimic the above message when users fill out one of the "main" boxes with the text "this  is a required with  _______ "

**Comment by entrotech** [comment]
Might still need to work on appearance a bit. Messages are pretty big, and disabled Forward button is out of position for some reason.
