### ISSUE TITLE
Create Terms and Conditions for the website 

### ISSUE THREAD

**Issue by KPHowley** [hackforla/tdm-calculator#527]
### Overview
The website needs a terms ad conditions, which needs to be written. After this we will need to determine how to display it for users. 

### Action Items

- [x] Create terms and conditions
- [ ]  Create issue to add to the website

### Working Document
https://docs.google.com/document/d/1wzVJdshngud0X7hbSC6kWGdWI01Y0mQr/edit

**Comment by Rankazze** [comment]
I have done my review & comment pass

**Comment by Rankazze** [comment]
@Dsomers74 this is ready for you to finalize and submit to your Legal.  After they have concluded their review please send to Bonnie for submission to Code for America Legal.

**Comment by Dsomers74** [comment]
@Rankazze sorry, you were referencing an older version linked above. This is the [most updated version](https://docs.google.com/document/d/1wzVJdshngud0X7hbSC6kWGdWI01Y0mQr/edit). I think it may address your remaining comment(s).

Thanks for your review!

**Comment by Rankazze** [comment]
@Dsomers74  Thanks for sending the most recent version.  I made a couple minor suggestions.  Good luck with getting sign off.

**Comment by Rankazze** [comment]
@Dsomers74 @KPHowley @ExperimentsInHonesty   I made one suggestion.  All good.

**Comment by ExperimentsInHonesty** [comment]
@Dsomers74 Can you review the latest changes that @Rankazze added (just one) to the **terms and conditions**. If it seems good to you, you can accept his change and then send the link to your legal for review.
https://docs.google.com/document/d/1wzVJdshngud0X7hbSC6kWGdWI01Y0mQr/edit

**Comment by Dsomers74** [comment]
@ExperimentsInHonesty Thanks! I reviewed and accepted the change. I rerouted to our City Attorney and will keep you posted.

**Comment by ExperimentsInHonesty** [comment]
kevin created Issue #672 for implementation now that t&c has been approved
