### ISSUE TITLE
Design - mock up changing package buttons to allow them to be unselectable

### ISSUE THREAD

**Issue by KPHowley** [hackforla/tdm-calculator#528]
### Overview
We need to make it so users can select the package buttons on the Strategy selection page. 

### Action Items

- [ ] Create design of either an unselectable button or a alternative check box

- [ ] Move issue to front end for development.

**Comment by dreams0ng** [comment]
CHANGES
+ moved button to left edge to ease visual crowding

MOCKUPS
1.
![cp1](https://user-images.githubusercontent.com/22779768/92648700-af6afb80-f29e-11ea-96d7-46f658b8f945.gif)
![Screen Shot 2020-09-09 at 1 17 09 PM](https://user-images.githubusercontent.com/22779768/92649125-6798a400-f29f-11ea-9ffb-8964b7d3c2e1.png)
![Screen Shot 2020-09-09 at 1 17 27 PM](https://user-images.githubusercontent.com/22779768/92649129-68c9d100-f29f-11ea-8c86-764827d302f5.png)

2.
![cp2](https://user-images.githubusercontent.com/22779768/92649173-77b08380-f29f-11ea-92c1-b044ce4879dd.gif)
![Screen Shot 2020-09-09 at 1 17 43 PM](https://user-images.githubusercontent.com/22779768/92649200-81d28200-f29f-11ea-8b92-e08394871558.png)
![Screen Shot 2020-09-09 at 1 18 03 PM](https://user-images.githubusercontent.com/22779768/92649201-839c4580-f29f-11ea-95d5-d8e1ef893647.png)

3.
![cp3](https://user-images.githubusercontent.com/22779768/92649246-91ea6180-f29f-11ea-9fcc-f010927f0db8.gif)
![Screen Shot 2020-09-09 at 1 18 22 PM](https://user-images.githubusercontent.com/22779768/92649266-9ca4f680-f29f-11ea-952c-81c52da43de0.png)
![Screen Shot 2020-09-09 at 1 18 36 PM](https://user-images.githubusercontent.com/22779768/92649274-9e6eba00-f29f-11ea-96ff-f8a573d6411e.png)

LINKS
https://xd.adobe.com/view/9a62a7fd-77fc-4555-7e09-781c4fdfc3f9-ec53/
https://xd.adobe.com/view/9a62a7fd-77fc-4555-7e09-781c4fdfc3f9-ec53/screen/dc6230ee-8b41-4bd3-afb4-30887158a534
https://xd.adobe.com/view/9a62a7fd-77fc-4555-7e09-781c4fdfc3f9-ec53/screen/2b1e6d96-0ef0-435c-8a35-c86861d8ef48

**Comment by dreams0ng** [comment]
CHANGES
+moved toggle in line with package bonus section bar
+changed colors for toggle on/off states

MOCKUPS
![giphy-3](https://user-images.githubusercontent.com/22779768/92800135-42706800-f369-11ea-8199-53b2f1ab17b3.gif)
![Screen Shot 2020-09-10 at 1 25 09 PM](https://user-images.githubusercontent.com/22779768/92800149-443a2b80-f369-11ea-890f-bca08726c694.png)
![Screen Shot 2020-09-10 at 1 25 23 PM](https://user-images.githubusercontent.com/22779768/92800156-4603ef00-f369-11ea-9ebe-6b8faba91899.png)

LINKS
https://xd.adobe.com/view/9a62a7fd-77fc-4555-7e09-781c4fdfc3f9-ec53/screen/dc6230ee-8b41-4bd3-afb4-30887158a534

**Comment by ExperimentsInHonesty** [comment]
@KPHowley the design shown above is not what was discussed in the meeting with the stakeholder.  Please don't send that to development

**Comment by KPHowley** [comment]
@ExperimentsInHonesty - that was from before our meeting, and we are still working on this. It has not be sent to development yet.

**Comment by dreams0ng** [comment]
CHANGES
created in line checkbox options
used smaller tooltip icon inline with checkboxes
moved primary, large tooltip icon closer to title text to alleviate crowding

MOCKUPS
![Screen Shot 2020-09-30 at 7 13 56 PM](https://user-images.githubusercontent.com/22779768/94758101-1c7b2980-0351-11eb-984b-274a9162c4cb.png)

LINKS
https://xd.adobe.com/view/9a62a7fd-77fc-4555-7e09-781c4fdfc3f9-ec53/screen/04bb1f98-9156-425d-a7ac-a256e28c9e76
