### ISSUE TITLE
Replace left banner image with LADOT Mobility Icons

### ISSUE THREAD

**Issue by Dsomers74** [hackforla/tdm-calculator#530]
### Overview
replace the left banner image within the TDM Calculator with LADOT Mobility Icons.

### Action Items
I provided [Two Banner Versions](https://drive.google.com/drive/folders/1hpXqZVrSHz_hGQtOmJvyNi_-lqD7yipu?usp=sharing) and I prefer the more simple single vertical row of mobility icons.

[Single Vertical Row Version ](https://drive.google.com/file/d/1zWcCR4SuxrSAyXgAkNh8FUDA4Pamid7V/view?usp=sharing)

Link to images in Google Drive:
https://drive.google.com/drive/folders/1r31ktJUIPEmyUDpDuQ-61vUVFfD8Swwv?usp=sharing

UPDATE:

- [ ] update with the new alter image V2:

![TDM_web_Banner_V3](https://user-images.githubusercontent.com/49739276/94754651-aa054c00-0346-11eb-909c-22101d112497.png)

**Comment by ExperimentsInHonesty** [comment]
![TDM Calculator - Banner V1](https://user-images.githubusercontent.com/37763229/91905147-ed42a100-ec5a-11ea-850d-5035889896ea.png)
![TDM Calculator - Banner V2](https://user-images.githubusercontent.com/37763229/91905151-efa4fb00-ec5a-11ea-9f3c-3c3e5abadf32.png)

**Comment by KPHowley** [comment]
* BLOCKED BY #553

**Comment by KPHowley** [comment]
@entrotech - after discussion with @Dsomers74 we are pulling the trigger on V2 picture or the "wrapping paper design"
