### ISSUE TITLE
Audit the style of the website. 

### ISSUE THREAD

**Issue by KPHowley** [hackforla/tdm-calculator#536]
### Overview

In order to achieve consistent styling and a working style guide, we should come up with an Audit of components of the site. After this is done we can then create a consistent style guide and work on standardizing components.  

### Action Items

- [x] Perform Audit of site
- [x] Determine standards
- [x] Determine which changes need to be made
- [x] #972 - action items listed below for ease

> Create detailed information about: 
> - [x] Notifications
> - [x] Popups
> - [x] Errors
> - [x] Close Crosses
> - [x] Tooltips
> - [x] Colors
> - [x] Menus
> - [x] Buttons
> - [x] Fields and Labels
> - [x] Typography
> - [x] Iconography
> - [x] Margins/Padding **(CURRENTLY READJUSTING CURRENT SCREENS TO FIT)**
> - [x] Logo
> - [ ] .... all other components deemed necessary **(CURRENTLY ADDING MISSING SCREENS TO SYSTEM)**

### Resources/Instructions
[ Current Design System](https://www.figma.com/file/nD9QK56Mzq7xNSaSUoeGx0/TDM-Calculator?node-id=4041%3A12655)

**Sample documents from other projects:** 
https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website

https://www.figma.com/file/BJL6ZHfjrxVhU8jvD9gB3P/HomeUniteUs-Everything-Figma?node-id=1%3A934

**Comment by KPHowley** [comment]
@anamsha - have you been actively working on this? if not I'll just un-tag you for now on this until you are

**Comment by mojimoh** [comment]
Please provide update by Wednesday
1. Progress: "What is the current status of your project? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"
5. Pictures (if necessary): "Add any pictures that will help illustrate what you are working on."

**Comment by Noushie** [comment]
> Please provide update by Wednesday
> 
> 1. Progress: "What is the current status of your project? What have you completed and what is left to do?"

**We still have to complete the unchecked options above**

> 2. Blockers: "Difficulties or errors encountered."

**I think busyness/time is a big blocker... My apologies, I've been pretty busy lately and my team also expressed the same- we will try to get this done ASAP**

> 3. Availability: "How much time will you have this week to work on this issue?"

**Estimated 2-5 hours**

> 4. ETA: "When do you expect this issue to be completed?"

**Aiming before 2/25 (as discussed in the last meeting- giving about a month to complete but will try to do it before then)**

> 5. Pictures (if necessary): "Add any pictures that will help illustrate what you are working on."

**Comment by Noushie** [comment]
Checklist reupdated

**Comment by Noushie** [comment]
Checklist updated

**Comment by Biuwa** [comment]
@noushie please add a link to the current figma file here

**Comment by Noushie** [comment]
[Link to Current Figma File](https://www.figma.com/file/nD9QK56Mzq7xNSaSUoeGx0/TDM-Calculator?node-id=7864%3A23370&t=FwLhzRhcRTRdoJ99-1)

**Comment by Noushie** [comment]
![image](https://user-images.githubusercontent.com/115515867/222333822-a45972db-a065-4d66-ab46-77f07044df21.png)

Just for reference - once all of it is fully organised it will be in the 'full design system' tab. Above is a screenshot for a general idea of how it will look all together

**Comment by Noushie** [comment]
**### 3/8 Update**
Progress: "What is the current status of your project? What have you completed and what is left to do?"

**Working on updating screens to the new grid and organising all of the design components we've worked on into the 'design system' page. Also annotating screens with visual changes that need to be done to be more consistent**

Blockers: "Difficulties or errors encountered."

**A lot of this work is time consuming/busy work, so a) carving out the time to do it has been a blocker**

Availability: "How much time will you have this week to work on this issue?"

**5-6 hours**

ETA: "When do you expect this issue to be completed?"

**If I can grind it out, hopefully by next week - design systems have to constantly be updated anyway, but to at least have something more current/up-to-date to show would be helpful**

Pictures (if necessary): "Add any pictures that will help illustrate what you are working on."

**Example of readjusting wireframes**
![image](https://user-images.githubusercontent.com/115515867/223865687-0ef2cb7d-6c20-4ee2-b8ad-ddf6896ccf77.png)

**Example of write-ups for components (i.e., how they're used/what they look like, etc.)**
![image](https://user-images.githubusercontent.com/115515867/223865841-2d595b3d-6421-4ae4-ad59-23d03a85c1a1.png)

**Example of annotated screen (the updated version will be next to it)**

![image](https://user-images.githubusercontent.com/115515867/223866483-c4ca9fa0-52ad-41a1-b0a8-1ea42b8f2cc6.png)

**Comment by Noushie** [comment]
### 3/15 Update

Progress: "What is the current status of your project? What have you completed and what is left to do?"

**Finishing dev changes to match current design system**

Blockers: "Difficulties or errors encountered."

**Have been really sick these past few days**

Availability: "How much time will you have this week to work on this issue?"

**N/A**

ETA: "When do you expect this issue to be completed?"

**End of week**

Pictures (if necessary): "Add any pictures that will help illustrate what you are working on."

![image](https://user-images.githubusercontent.com/115515867/225489379-fbddbcda-88c6-4c93-9139-17a124b35911.png)

**Comment by Biuwa** [comment]
- Anousha has completed the documentation in [Figma](https://www.figma.com/file/nD9QK56Mzq7xNSaSUoeGx0/TDM-Calculator) and #1340 will be the documentation issue for the website audit
