### ISSUE TITLE
Create a page for the Privacy policy and link to it on the footer

### ISSUE THREAD

**Issue by KPHowley** [hackforla/tdm-calculator#539]
### Overview
We do have a privacy policy which will be linked on the bottom of the page. The final language is still TDB but a working sheet will be put  in the resources. We need to create a page to display this.
 
### Action Items

- [x] Create page 

- [x] Create link on footer to page

**Comment by jahpe777** [comment]
I created a page for "Terms and Conditions" and implemented a functional footer link. #539

![Screen Shot 2020-09-13 at 7 58 28 PM](https://user-images.githubusercontent.com/40730303/93039134-95f9e480-f5fb-11ea-8ac7-a313ed6d939a.png)
