### ISSUE TITLE
Create a page for the Terms and conditions and link to it on the footer

### ISSUE THREAD

**Issue by KPHowley** [hackforla/tdm-calculator#540]
### Overview
We do have Terms and conditions which will be linked on the bottom of the page. The final language is still TDB but a working sheet will be put in the resources. We need to create a page to display this.
 
### Action Items

- [x] Create page 
- [x] Create link on footer to page

**Comment by jahpe777** [comment]
I created a page for "Terms and Conditons" and implemented a functional footer link. #540

![Screen Shot 2020-09-13 at 7 28 07 PM](https://user-images.githubusercontent.com/40730303/93037637-bde74900-f5f7-11ea-8125-d3ff31662f32.png)
