### ISSUE TITLE
Research and Create a mockup for a terms of service "pop-up"

### ISSUE THREAD

**Issue by KPHowley** [hackforla/tdm-calculator#541]
### Overview
The LADOT is finalizing a terms of service for the Calculator, and we will need users to accept this before using the site. We need to then design a mock up of a "pop-up," "slide-up" or similar form to notify users

### Action Items

- [x] Discuss feasibility with Development
- [x] Research best practices for this
- [x] Determine best implementation
- [x] Mock up
- [ ] Create ticket for Development

**Comment by chalimar** [comment]
Here is a possible modal design.

![image](https://user-images.githubusercontent.com/34084181/91913297-19195300-ec6a-11ea-869b-55f7fbbf65ec.png)

**Comment by KPHowley** [comment]
Per meeting on 9/02 we need to add a decline button, which will return the user to the LADOT website. 

We will have a further iteration for a "don't show this message again" option

**Comment by chalimar** [comment]
![image](https://user-images.githubusercontent.com/34084181/92664431-d3d3d180-f2b8-11ea-8d42-5907b0eb28c0.png)

**Comment by KPHowley** [comment]
I Just deleted the x on the mock-up because we need people to accept this or not!
![TAC Popup](https://user-images.githubusercontent.com/49739276/93415316-161c8600-f858-11ea-8d97-10f37336c5d7.png)
