### ISSUE TITLE
Fix alignment of right button on specifications page, when disabled

### ISSUE THREAD

**Issue by KPHowley** [hackforla/tdm-calculator#548]
### Overview

The right button is out of line when disabled on the second page, the project specifications page. this needs to be in line, as on the first page of the wizard

### Action Items

- [x] Fix aligmentme

**Comment by jahpe777** [comment]
I fixed the alignment of the right button on the second page of the wizard, the project specifications page. #548

![1](https://user-images.githubusercontent.com/40730303/92759486-a7659700-f344-11ea-8f60-48fddd1665b3.png)

![2](https://user-images.githubusercontent.com/40730303/92759506-af253b80-f344-11ea-826f-be30a1fef4c5.png)
