### ISSUE TITLE
Create test for different Side bar options. 

### ISSUE THREAD

**Issue by KPHowley** [hackforla/tdm-calculator#553]
### Overview
Two sidebar options were created for issue  # . We want to sdo some testing and send this to LADOT to poll interenally

### Action Items

- [ ] Finish design on issue # 

- [ ] Create A/B test

- [ ] Share with LADOT

**Comment by dreams0ng** [comment]
CHANGES
+used in line graphic
+used wrapping graphic
+tested wrapping auto-scroll 

MOCKUPS
1.
![giphy](https://user-images.githubusercontent.com/22779768/92784244-5a40ef80-f35b-11ea-833c-c0750a48ca49.gif)

2.
![giphy-1](https://user-images.githubusercontent.com/22779768/92784288-6331c100-f35b-11ea-9764-ea57e3777e02.gif)

3.
![giphy-2](https://user-images.githubusercontent.com/22779768/92784331-6af16580-f35b-11ea-8751-39b9aab65c3c.gif)

LINKS
1. https://xd.adobe.com/view/9a62a7fd-77fc-4555-7e09-781c4fdfc3f9-ec53/
2. https://xd.adobe.com/view/9a62a7fd-77fc-4555-7e09-781c4fdfc3f9-ec53/screen/da654040-b516-4b2b-8a71-d518a050d55d
3. https://xd.adobe.com/view/9a62a7fd-77fc-4555-7e09-781c4fdfc3f9-ec53/screen/7dcddafc-e55d-4fd9-b207-a7e1f889389d

**Comment by KPHowley** [comment]
@amberyou  - can you first just verify that we will be able to use Gif's in testing, or can you let me know if not?

@dreams0ng  - Can you make the nav bar sticky to the top of the page as well as the single page button? also for this one can you just make the color of earned and target points white and add a tool tip to each? I just want to make it look as much like the page if not.

**Comment by amberyou** [comment]
> @amberyou - can you first just verify that we will be able to use Gif's in testing, or can you let me know if not?
> 
> @dreams0ng - Can you make the nav bar sticky to the top of the page as well as the single page button? also for this one can you just make the color of earned and target points white and add a tool tip to each? I just want to make it look as much like the page if not.

@KPHowley - Yes, the Gif works in Usability Hub!

**Comment by chalimar** [comment]
Providing longer page view with both banner versions as requested by @ExperimentsInHonesty. Thank you.

![image](https://user-images.githubusercontent.com/34084181/93397281-215abc00-f82e-11ea-9ca0-67a4880f133e.png)

![image](https://user-images.githubusercontent.com/34084181/93397287-2586d980-f82e-11ea-8d08-b857ccd50f51.png)
