### ISSUE TITLE
Make save button keep users on the same page,  update timestamp, and display a toast 

### ISSUE THREAD

**Issue by nclairesays** [hackforla/tdm-calculator#565]
UPDATED Overview: 

Currently when the project is saved on the final page it bring to calculation/1 and starts a new project. We want the user to stay on the same page when they save a project, display an updated time stamp as well as a toast. 

ACTION 

- [ ] Change  redirect when user "saves" a project

- [ ] Make toast display on all pages

- [ ] Update time stamp at bottom of page 

potentially connected to #603

**Comment by KPHowley** [comment]
Changing this following last weeks discussion.

**Comment by KPHowley** [comment]
Hey @Jonathanko52 - I went over the changes you pushed with John and Bonnie on Saturday, and found a couple things i just wanted to bring up, that should be addressed under this issue 

-  There are some weird interaction with the timestamp on the bottom of the page after saving, I believe it stays even when you create a new project. Please keep an ey e on this when working on it, and let me know if you need to discuss

- The toast does appear to work fine

- I believe it currently clears all data and starts a new project whenever you press save, and whether you are redirected to the first calculation page depends on whether you are saving for the first time or not.

**Comment by Jonathanko52** [comment]
@KPHowley Thanks for the update. Here's what I've seen so far.

1. Have timestamp updating on save, but still having that interaction issue. Think I can handle it though.

2. As of 11/2,there may still be an issue with the toast. The toast appears on the page where the user saves, yes, but if you move to another page, the toast remains on the former page. If you scroll back to the former page before its timer expires, the toast remains intact until the timer runs out.

3. The issue appears to be that when the user saves a new project for the first time, the page seems to think users are creating a brand new project: Saves to database properly, but wipes the form. I'm working on fixing that.

**Comment by Jonathanko52** [comment]
Progress: Problem seems primarily caused by saving a new project and its side effects on the TDMcalculaitonwizard form. Narrowing down the cause.
Blockers: None
Availability: Weekdays after 1pm.
ETA:11/7

**Comment by Jonathanko52** [comment]
Progress: Timestamp updating on save. Narrowing down other problem.
Blockers: None
Availability Weekdays after 1pm
ETA:11/11

Notes: 
Redirect issue is tied to untimely rerendering of page.

Narrowed problem down line 90: setStrategiesInitialized(false) of TDMcalculationWizard. However, can't tell why this particular state change is triggering the problem. The 'strategiesInitialized' state value isn't passed down, and the function that uses it doesn't seem to run before the page forcibly rerenders.

Theory: strategiesInitialized is being passed down not as prop, but in closure of function its tied to, "initializeStrategies", and that's still triggering the rerender.

Possible solutions: 
1. Find an equivalent to shouldComponentUpdate and use it in TDM calculation wizard. 
2. Convert to class component and use shouldComponentUpdate
3. conditionally render TDMcalculationwizard to not receive "initializeStrategies" if it's not going to run it anyways.

For now, pull request made for the timestamp fix.
