### ISSUE TITLE
Hide "Switch to Single Page View" button

### ISSUE THREAD

**Issue by VJ1285** [hackforla/tdm-calculator#567]
### Overview
Hide "Switch to Single Page View"  

### Action Items
Front End

Need to hide the "Switch to Single View" button from all pages. The single view page is not part of the MVP and will be worked on later.

**Comment by jahpe777** [comment]
I hid the "Switch to Single Page View" button. #567

![Screen Shot 2020-09-17 at 10 24 10 AM](https://user-images.githubusercontent.com/40730303/93505826-36882700-f8d0-11ea-9280-7debb0291be1.png)
