### ISSUE TITLE
Add Bonus Package explanation

### ISSUE THREAD

**Issue by VJ1285** [hackforla/tdm-calculator#575]
### Overview
Based on the input, if the user qualifies for one or more packages, then we need to provide an explanation about these packages. This explanation would come after Page 3 of the existing flow. 

**Note: Only Project Level 1 qualifies for the below packages.** 

### Action Items

- [ ] Case 1 - Based on the input, if the user qualifies for the "Residential Package" then the below should show up after the existing page 3.

![image](https://user-images.githubusercontent.com/70343417/93835867-b30f6280-fc4e-11ea-93cd-75e3ca5d69cf.png)

- [ ] Case 2 - Based on the input, if the user qualifies for the "Employment Package" then the below should show up after the existing page 3.

![image](https://user-images.githubusercontent.com/70343417/93835856-abe85480-fc4e-11ea-8aff-fa43b2d2f039.png)

- [ ] Case 3 - Based on the input, if the user qualifies for both the  "Residential Package" and "Employment Package" then the below should show up after the existing page 3.

![image](https://user-images.githubusercontent.com/70343417/93835880-befb2480-fc4e-11ea-87cd-7e3077bee868.png)

- [ ] - When the user hovers over the "?" mark at the end of "Learn more about Packages" the below window should pop up.
![image](https://user-images.githubusercontent.com/70343417/93835900-cde1d700-fc4e-11ea-8961-2984851e6d06.png)

 

### Resources/Instructions
https://www.figma.com/file/qNgPc5lttpf0SWSwkbbWyT/TDM-Calculator?node-id=2301%3A11467

**Comment by KPHowley** [comment]
@entrotech  tool tip text: 

 " There are many TDM strategies choices and most involve making long-term commitments in meeting program compliance.

Small development projects (defined as Program Level 1 that provide no more than the parking baseline), are provided TDM packages that allow fulfillment of the minimum 15 point target from a pre-selected menu. 

A point incentive is provided for the packages made up of strategies that work together to reinforce their effectiveness in reducing drive-alone trips. 

Each strategy selected on its own does not result in the required minimum point target but several selected together will. Each package can be unselected and individual strategies that will work best to both achieve the TDM program goals and your specific development objectives should be chosen. "

**Comment by entrotech** [comment]
@KPHowley Is there more work to do on this?

**Comment by KPHowley** [comment]
Hey John, @entrotech  It appears done from my point of view!
