### ISSUE TITLE
Make Demo/Walkthrough video

### ISSUE THREAD

**Issue by VJ1285** [hackforla/tdm-calculator#583]
### Overview
Make a demo/walkthrough video that showcases how the website works. 

### Action Items

- [ ] Make a video that guides the user with typical examples of how the website works from the landing page to the final output.

- [ ] This video will be used during the webinar by LADOT.

- [ ] Provide the link to this video on the website.

- [ ] Edit the video such that it's broken down by each page of the website such that when the user is on a specific page, the video link at the bottom shows the functionality of that specific page.

**Comment by ExperimentsInHonesty** [comment]
This issue is being replaced by #866
