### ISSUE TITLE
Add tooltip to Habitible rooms on project specification page

### ISSUE THREAD

**Issue by KPHowley** [hackforla/tdm-calculator#601]
### Overview
As habitable rooms may be a confusing term we want to add a tool tip icon to the habitable rooms inputs on the project specification page.  

### Action Items

- [ ]  Add tool tip icon either to all lines mentioning Habitable rooms, in the same way we display tool tips on the final page 
        
### Resources/Instructions
**Text:** The City defines "habitable rooms" as enclosed spaces used for living purposes. This includes bedrooms, living rooms and dining rooms, given that they are all enclosed. Any non-enclosed alcove more than 50 square feet in size is also included in this definition (dining area excluded). The City's definition of habitable room excludes lobbies, hallways, and bathrooms. The City includes kitchens in the definition only for calculating parking requirements. Therefore, a living room, dining room, and kitchen, all completely separated from each other with walls, will count as three habitable rooms for parking calculation purposes

**Comment by Jonathanko52** [comment]
Progess: None
Blockers: None.
Availability: Saturday afternoon. Weekdays after 1pm.
ETA: 10/24

**Comment by KPHowley** [comment]
@KPHowley @VJ1285  - Change this to be similar to tooltips on strategy page
