### ISSUE TITLE
Create a testing plan for the new sidebar options. 

### ISSUE THREAD

**Issue by KPHowley** [hackforla/tdm-calculator#602]
- [ ] ### Overview

We are trying to implement new changes in the sidebar in #417 and #418 and we want them tested first. We want to come up with a testing plan to isolate the changes and then do user testing of them

### Action Items

- [x] Come up with a breakdown of the specific things we need to test on the side bar. 
- [x] Determine how to isolate each specific aspect/feature
- [x] Make sure A/B testing is the best option
- [x] Develop an order for the testing
- [ ] Implement the tests

Follow up items:

- [x] Test Orientation of Points numbers  
- [x] Test Size of Points numbers  
- [x] Test Side bar notification of "success"
- [x] Test Color Change

**Comment by amberyou** [comment]
Testing horizontal vs vertical alignment of Target and Earned Points: [Test Link Here](https://app.usabilityhub.com/do/17dcb7db0d9a/9d48)

**Comment by KPHowley** [comment]
Please provide an update with:
1) Progress
2) Blockers
3) Availability
4) ETA

**Comment by amberyou** [comment]
1. Progress: test is active and being sent out to different groups
2. Blockers: none currently
3. Availability: here is the [results link](https://app.usabilityhub.com/tests/17dcb7db0d9a/results/3e3bfee548e8)
4. ETA: will be finished be next Tuesday/Wednesday

**Comment by amberyou** [comment]
Here is the [test link](https://app.usabilityhub.com/do/df31288d0608/ad43) for different sizes of the sidebar points text.

**Comment by amberyou** [comment]
Here is the [test](https://app.usabilityhub.com/do/881ea0de530a/9715) for having a notification or not when points are met.

**Comment by amberyou** [comment]
Final [test](https://app.usabilityhub.com/do/98227f54445c/d705) of whether or not to have the points color change
