### ISSUE TITLE
Add Save Button to all pages of the Wizard

### ISSUE THREAD

**Issue by KPHowley** [hackforla/tdm-calculator#603]
### Overview
Add a save button to all pages of the wizard, and update styling & wording 

### Action Items

- [ ] Change wording on save  button (currently visible only on final page) to "Save Project"
- [ ] change order of buttons
- [ ] make visible on all pages 
- [ ] Make in line with the Design below (except maintain current spacing between the arrow buttons)

- [ ] Add last saved timestamp that is currently visible on final page to all pages. 

### Resources/Instructions
![96622137-6c993c00-12be-11eb-8791-253bf6a4fff3](https://user-images.githubusercontent.com/49739276/96807785-482b8580-13cc-11eb-8234-761138db3352.png)

**Comment by Jonathanko52** [comment]
Pull request merged
