### ISSUE TITLE
Update the "About" page and Review Copy 

### ISSUE THREAD

**Issue by VJ1285** [hackforla/tdm-calculator#606]
### Overview
Review the copy for the  "About" page, and make links to the fact sheet the mobility plan. 

### Action Items

Design:
- [x] Rewrite copy and post as text for review 
- [x] Develop design with hyperlink where we talk mention the LA mobility plan on the "About" page.

Front End
- [ ] Update Copy 
- [ ] Add the hyperlink
- [ ] Style to match Design

### Resources/Instructions

TEXT ONLY: https://docs.google.com/document/d/17BOkryqIPCa_Fb1X-eF2JboW_JuH1E3EnXnWqx1sa5w/edit?usp=sharing

Hyperlink to mobiity plan : https://planning.lacity.org/odocument/523f2a95-9d72-41d7-aba5-1972f84c1d36/Mobility_Plan_2035.pdf

**Comment by dreams0ng** [comment]
Changes
+Added hyperlink leading to LA's Mobility Plan 2035 page
+Changed voice from passive to active
+Edited 132 words down to 115
+Added hfla logo to bottom of page, size tbd

Mockups
![Screen Shot 2020-11-04 at 1 08 28 PM](https://user-images.githubusercontent.com/22779768/98168059-df99d980-1e9e-11eb-8fcc-10ccffb156c2.png)

Links
https://www.figma.com/file/6h72XLxK76m4INtsSu8Mt0/TDM-Calculator-Copy?node-id=2155%3A12744

**Comment by KPHowley** [comment]
I Will review this with @ExperimentsInHonesty

**Comment by KPHowley** [comment]
@dreams0ng  - Can you put the Copy in a separate google doc and link to it here so we can review?

**Comment by KPHowley** [comment]
Google Doc with Text ONLY: https://docs.google.com/document/d/17BOkryqIPCa_Fb1X-eF2JboW_JuH1E3EnXnWqx1sa5w/edit?usp=sharing

**Comment by dreams0ng** [comment]
1. Progress
- Utilized D. Sommers' latest edits to create 144wc draft (current draft is at 174wc)
- Maintained active voice
2. Blockers
- LADOT Edits
3. Availability
- Any
4. ETA
- Presented

**Comment by KPHowley** [comment]
@ExperimentsInHonesty  - reminder to review  the updates from David and Emily on the [About Page Copy ](https://docs.google.com/document/d/17BOkryqIPCa_Fb1X-eF2JboW_JuH1E3EnXnWqx1sa5w/edit) before our meeting on Tuesday afternoon

**Comment by ExperimentsInHonesty** [comment]
I added my updates to the [About page](https://docs.google.com/document/d/17BOkryqIPCa_Fb1X-eF2JboW_JuH1E3EnXnWqx1sa5w/edit) doc.  @Dsomers74 please review
