### ISSUE TITLE
Remove "Earned Points" from Page 6 (Final Page) next to "Project Specifciations"

### ISSUE THREAD

**Issue by VJ1285** [hackforla/tdm-calculator#608]
### Overview
Remove the "Earned Points" on page 6 (final/result page) next to "Project Specifications".

### Action Items
The "Earned Points" on page 6 (final/result page) next to "Project Specifications" are not required and need to be removed. 

### Resources/Instructions

![image](https://user-images.githubusercontent.com/70343417/97058560-282acc00-155c-11eb-9e7d-c04b390d1f50.png)

**Comment by KPHowley** [comment]
@jahpe777  Please provide an update with:
1) Progress
2) Blockers
3) Availability
4) ETA

**Comment by jahpe777** [comment]
#608

Remove "Earned Points" from Page 6 (Final Page) next to "Project Specifications"

![3](https://user-images.githubusercontent.com/40730303/98622524-98588200-22be-11eb-8c90-15de18b5a397.jpg)
