### ISSUE TITLE
Televisits shows that it is contingent on telecomute options (NEEDS UPDATE)

### ISSUE THREAD

**Issue by KPHowley** [hackforla/tdm-calculator#618]
### Overview
There is potentially a change to the interaction between Televisits and Telecommute options. We need some clarity on how this works however. 

This is what the current interaction was based off: 

"
Under Telecommute: Televisits, checking the box changes the Telecommute line to 3 points as well, but does not seem to alter overall point value. Make it so that if Televisits in checked, and the Telecommute strategy is set at 0 days, no points are gained in the Telecommute row.
"

**Comment by KPHowley** [comment]
@awikstrom-ladot @Dsomers74 -  I created an issue for this but we do need a bit of clarity on the intended interaction.

**Comment by KPHowley** [comment]
Determined no change was needed

**Comment by ExperimentsInHonesty** [comment]
as per David and Emily this is a bug, the choices should not be tied to each other.  You should be able to select the check box without using the drop down.

**Comment by KPHowley** [comment]
@entrotech  - opening this up as the Televisits option currently only gives users 1pt in earned points instead of 3!
