### ISSUE TITLE
Mixed Use AH Projects assign Level to non-affordable housing level rather than other uses

### ISSUE THREAD

**Issue by KPHowley** [hackforla/tdm-calculator#619]
### Overview

The affordable housing project checkbox currently forces residential only projects to be level 1, however when a project is mixed use the residential portion contributes to the level calculation. According to LA DOT the data from residential land uses should not be included in the level calculation.  For example this means a project that is mixed use and at level 2 (based on non residential inputs) it should not become level 3,  no matter how large any Affordable housing inputs are . 

### Action Items

- [x] update Affordable housing checkbox on backed

**Comment by entrotech** [comment]
PR #623
