### ISSUE TITLE
Add Page numbers to navigation area on bottom of the wizard. 

### ISSUE THREAD

**Issue by KPHowley** [hackforla/tdm-calculator#620]
### Overview
Page numbers need to be added to the bottom of the wizard to display progress. This should be styled as shown in the picture/figma link. 

This is connected to issue #603 for adding the save button to the Navigation area. 

### Action Items

- [ ] Add page numbers for the 5 main pages of the wizard i accordance with the mock up 

- [ ] For all the conditional "Level 0" page please make the page display 5/5

- [ ] For the conditional page describing the packages please make the page display remain at 3/5

### Resources/Instructions
![Screen Shot 2020-10-27 at 3 07 55 PM](https://user-images.githubusercontent.com/49739276/97513749-53416100-194a-11eb-9054-cd4ae924f688.png)

https://www.figma.com/file/qNgPc5lttpf0SWSwkbbWyT/TDM-Calculator?node-id=2626%3A11673

**Comment by Jonathanko52** [comment]
Merged
