### ISSUE TITLE
Add paragraphs breaks to habitable room tool tip 

### ISSUE THREAD

**Issue by KPHowley** [hackforla/tdm-calculator#626]
### Overview
The habitable tool tip is very difficult to read, and so we would like to break it up into pragraghs as shown in the resources area.

### Action Items

- [x] Add paragraph breaks into text 

### Resources/Instructions

"
The City defines "habitable rooms" as enclosed spaces used for living purposes. This includes bedrooms, living rooms and dining rooms, given that they are all enclosed. 

Any non-enclosed alcove more than 50 square feet in size is also included in this definition (dining area excluded). The City's definition of habitable room excludes lobbies, hallways, and bathrooms. The City includes kitchens in the definition only for calculating parking requirements. 

Therefore, a living room, dining room, and kitchen, all completely separated from each other with walls, will count as three habitable rooms for parking calculation purposes.

"

**Comment by jahpe777** [comment]
Added paragraphs breaks to habitable room tool tip #626

![Screen Shot 2020-11-24 at 1 29 08 PM](https://user-images.githubusercontent.com/40730303/100158901-c367d780-2e61-11eb-8b15-9a5bd931bbe8.jpg)
