### ISSUE TITLE
Make save Button only visible when logged in. 

### ISSUE THREAD

**Issue by KPHowley** [hackforla/tdm-calculator#628]
### Overview
Currently the save button is displayed when users are not logged in, even though they can not use it. We would like it to not be visible and for users to just see a centered start over button. 

### Action Items

- [ ] Make save button conditional only for signed in users 

- [ ] Center stat button under arrows for users not logged in . 

### Resources/Instructions

Linked to #565  so check this issue before starting

**Comment by Jonathanko52** [comment]
Merge request sent

**Comment by Jonathanko52** [comment]
Pull request amended. Awaiting review.
