### ISSUE TITLE
Investigate Citygro.ws platform

### ISSUE THREAD

**Issue by bfojas** [hackforla/tdm-calculator#67]
### Overview
Register and explore citygro.ws and see if this platform is right for our project.

**Comment by KPHowley** [comment]
I don't think Citygro.ws will be useful to us for the tdm Calculator, as its a bit limited. it's a good resource for creating simple forms, and could potentially be used for the DOT to manage payments, however It's not able to do the complex calculations we need. Everything is built into their website and interface so we couldn't even implement parts of it.

It's worth looking at if you have a need to create basic forms, track responses and/or accept payments on projects in the future.
