### ISSUE TITLE
Defining HQTA for Neighborhood Shuttles/Microtransit Service - related to #656

### ISSUE THREAD

**Issue by Dsomers74** [hackforla/tdm-calculator#678]
### Overview
David provided us with an updated tool tip definition for Neighborhood Shuttles/Microtransit Service with definition for HQTA

### Action Items

- [ ] Update Tool tip 

### Reference

Tool tip text:

Operate a neighborhood serving transit service

High-quality Transit Areas (HQTA's) are within one-half mile from major transit stops and high-quality transit corridors and developed based on the language in Senate Bill (SB) 375. The definitions of major transit stops and high-quality transit corridors are as follows:
A. Major Transit Stop: A site containing an existing rail transit station, a ferry terminal served by either a bus or rail transit service, or the intersection of two or more major bus routes with a frequency of service interval of 15 minutes or less during the morning and afternoon peak commute periods (CA Public Resource Code Section 21064.3). It also includes major transit stops that are included in the applicable regional transportation. 
B. High-Quality Transit Corridor (HQTC): A corridor with fixed-route bus service with service intervals no longer than 15 minutes during peak commute hours.
"
 
### From David: 
related to #656 
I found the definition to support a tool tip, though it is not as straightforward as citing a code reference. I believe HQTA is a term of art that SCAG developed to interpret the requirements of SB 375, though HQTA term is not directly stated in the bill. 

I found the definition of how SCAG applies the term in the [ArcGIS Open Data Portal](https://maps.scag.ca.gov/scaggis/rest/services/OpenData/High_Quality_Transit_Areas/MapServer/1):

Define HQTA

High-quality transit areas (HQTA) is within one-half mile from major transit stops and high-quality transit corridors and developed based on the language in Senate Bill (SB) 375. The definitions of major transit stops and high-quality transit corridors are as follows:

- A. Major Transit Stop: A site containing an existing rail transit station, a ferry terminal served by either a bus or rail transit service, or the intersection of two or more major bus routes with a frequency of service interval of 15 minutes or less during the morning and afternoon peak commute periods (CA Public Resource Code Section 21064.3). It also includes major transit stops that are included in the applicable regional transportation. 

- B. High-Quality Transit Corridor (HQTC): A corridor with fixed-route bus service with service intervals no longer than 15 minutes during peak commute hours.

**Comment by KPHowley** [comment]
@Jonathanko52  - If you're trying this I'm moving to the in progress!

**Comment by Jonathanko52** [comment]
Progress: None to speak of.
Blockers: None.
Availability: weekdays 1pm onwards
ETA:1/27

**Comment by Jonathanko52** [comment]
Progress: Going over codebase
Blockers: None.
Availability: weekdays 1pm onward
ETA: 2/3

**Comment by Jonathanko52** [comment]
Progress: Completed. Pull request reviewed and merged
