### ISSUE TITLE
Review and update copy and title on headers

### ISSUE THREAD

**Issue by KPHowley** [hackforla/tdm-calculator#694]
### Overview
The headers and sub-headers might be somewhat confusing or dense to users. These should be reviewed and updated to help the used experience 

### Action Items

- [x] Come up with alternative headers
- [x] Discuss with the Product team
- [x] Do user testing if necessary 
- [ ] Change the heading on page 2 to: 
**Determine Project Level**
Project Level (left Panel) and Citywide Parking Baseline (next page) are determined by the use specifications entered below
- [x] Change the heading on page 3 to: 
**Calculate Project TDM Target Points**
Target Points (left panel) may be adjusted based on parking Spaces entered below
- [x] Change the heading on page 4 to: 
**Select TDM Strategies**
Select TDM strategies to earn points to reach the Target (left panel)### Resources/Instructions
- [x] #1197

### Resources/Instructions
https://docs.google.com/document/d/1kdO_EXJJ-JXRFIW6ejjbBmeGclnPD5Uv0xRa6TboyUw/edit

https://docs.google.com/document/d/1kdO_EXJJ-JXRFIW6ejjbBmeGclnPD5Uv0xRa6TboyUw/edit#heading=h.7gvz0mime3a
<img width="627" alt="New Headers" src="https://user-images.githubusercontent.com/69442669/177008997-9f0df847-2cf1-4971-83a0-53e39ad6c427.png">
9

**Comment by KPHowley** [comment]
Created a ticket for updating just the sub header on calculation/1 and am moving this back to the backlog!

**Comment by ExperimentsInHonesty** [comment]
Add screenshots of what the problem is now.

**Comment by KPHowley** [comment]
Page 2: Project Level and Target Points (see left panel) are determined by details entered below
Page 3: Target Points (see left panel) may be adjusted based on details entered below
Page 4: Select TDM strategies to earn Target Points

**Comment by Biuwa** [comment]
Approved Page Heading Changes for page 2:
**Enter Project Specifications**
Fill out the use specifications that apply to your project
**Determine Project Level**
Project Level (left Panel) and Citywide Parking Baseline (next page) are determined by the use specifications entered below.

**Comment by Biuwa** [comment]
Approved Page Heading Changes for page 3:
**Calculate Project TDM Target Points**
Target Points (left panel) may be adjusted based on parking Spaces entered below

**Comment by Biuwa** [comment]
Approved Page Heading Changes for page 4:
**Transportation Demand Management Strategies**
Select TDM strategies to earn points to reach the Target (left panel)

**Comment by entrotech** [comment]
Work completed under development issue #1197
