### ISSUE TITLE
Update Terms and conditions text to add a hyperlink

### ISSUE THREAD

**Issue by KPHowley** [hackforla/tdm-calculator#697]
### Overview
We need to update the privacy policy to add a hyperlink to replace the pending case number on the terms and conditions

Link: planning4la.org/mobility 
 (Full Webaddress)https://planning.lacity.org/plans-policies/initiatives-policies/mobility 

### Action Items

- [x] Update wording on page 
- [x] Update wording on pop up  

### Resources/Instructions

2nd paragraph updated:
"
The Los Angeles Department of Transportation (LADOT), in partnership with the Department of City Planning and Hack for LA (a project of Code for America), has developed the City of Los Angeles Transportation Demand Management (TDM) Calculator (TDM Calculator) to provide the public with an understanding of the TDM Ordinance. Currently available for review: Council File 15-0719-S19 / The Los Angeles Department of City Planning website: [planning4la.org/mobility ](url). The TDM Ordinance proposes to revise regulations that require eligible land use development projects to adopt TDM strategies with the goal to reduce the reliance on drive-alone trips in the City of Los Angeles.  The term “City” as used below shall refer to the City of Los Angeles. The terms “City” and “Hack for LA” as used below shall include their respective affiliates, sub-consultants, employees, volunteers, and representatives.
"
Full new text updated here: 
https://docs.google.com/document/d/1zlGAsEjkBocqxW9osIhHs8EbHdquYdqm-yxSbd4ZjcM/edit

**Comment by jahpe777** [comment]
Updated Terms and conditions text to add a hyperlink #697

![Uploading Screen Shot 2021-01-10 at 5.37.26 PM.png…]()

**Comment by jahpe777** [comment]
Updated Terms and conditions text to add a hyperlink #697

<img width="1440" alt="Screen Shot 2021-01-10 at 5 37 26 PM" src="https://user-images.githubusercontent.com/40730303/104141300-d891ba80-536a-11eb-89e8-7ace007a2fca.png">

**Comment by KPHowley** [comment]
Hi @jahpe777  - 

I see this updated on the page, but not on the pop up, were you able to make that change as well?
