### ISSUE TITLE
Code review of prototype

### ISSUE THREAD

**Issue by Rankazze** [hackforla/tdm-calculator#7]
### Overview
Code review of John's prototype

### Action Items
- [ ] Review code.
- [ ] Report findings.

### Resources/Instructions
[TDM-Calculator repo](https://github.com/hackforla/tdm-calculator)

**Comment by fyliu** [comment]
Code looks clean.
Database:
- id=79 input should not contain functionBody. Doesn't cause any problem.
- id=12 missing some parking excess percentages. Will need to add them later, maybe when we have a rule editor frontend.

**Comment by fyliu** [comment]
Closing issue after the previous comments have been converted to issues.
