### ISSUE TITLE
Add sidebar to confirm email page

### ISSUE THREAD

**Issue by nclairesays** [hackforla/tdm-calculator#703]
Add styling to /confirm/1 page

**Comment by jahpe777** [comment]
#703 should be closed. Sidebar currently renders on confirm email page. 

<img width="1440" alt="Screen Shot 2021-09-26 at 5 38 52 PM" src="https://user-images.githubusercontent.com/40730303/134830178-61800216-7b5f-4bfa-82fd-ce6b6aa2e23b.png">

**Comment by KPHowley** [comment]
Looks good for visual review!

**Comment by seenaiype** [comment]
The changes already in UAT, no code changes needed
