### ISSUE TITLE
Update Wiki

### ISSUE THREAD

**Issue by entrotech** [hackforla/tdm-calculator#707]
### Overview
After re-organizing the source code folder structure and setting up a new machine on Windows, it became apparent that the developer notes need to be updated to:

### Action Items

- [ ] Set up Git Bash on Windows to use LF instead of the Git Bash recommended line-ending setting, as the default introduces CRLF endings in files, which violate the project linting setup.
- [ ] Add instructions for working with Lerna
- [ ] Instruct developer to run `npm install` in root. server and client folders.
- [x] Move *.md files into the Wiki, so they are easier to update and more accessible to non-developers.

**Comment by ExperimentsInHonesty** [comment]
@entrotech when you get back from your vakay, please update the labels on this issue.

**Comment by Akheal** [comment]
@entrotech Hey John, when you get a chance can you pls update the labels on this issue?
