### ISSUE TITLE
Increase Size of Earned Points and Target Points on Sidebar to be equal to Project Level

### ISSUE THREAD

**Issue by KPHowley** [hackforla/tdm-calculator#712]
### Overview
After testing we want to make the Earned points and Target Points on the side bar larger. 

### Action Items

- [x] Increase Size of Target Points 
- [x] Increase Size of Earned Points 

### Resources/Instructions

Figma: TBD

![Screen Shot 2021-01-17 at 6 23 43 PM](https://user-images.githubusercontent.com/49739276/104865762-b4495700-58f1-11eb-94cf-5edf9a3b31e1.png)

**Comment by KPHowley** [comment]
@dreams0ng - Can you update this with the Figma link and a picture. (3 of 3 issues)

**Comment by dreams0ng** [comment]
1. Progress
- Updated UI to match live site
2. Blockers
- N/A
3. Availability
- Any
4. ETA
- Presented

MOCKUPS
![CC1](https://user-images.githubusercontent.com/22779768/105244892-007cdd00-5b26-11eb-8482-5451a1560cdc.png)

LINKS
https://www.figma.com/proto/6h72XLxK76m4INtsSu8Mt0/TDM-Calculator-(Copy)?node-id=2392%3A222&viewport=-1041%2C821%2C0.1437286138534546&scaling=min-zoom

**Comment by jahpe777** [comment]
Increased Size of Earned Points and Target Points on Sidebar to be equal to Project Level #712

![Screen Shot 2021-01-24 at 8 50 49 AM](https://user-images.githubusercontent.com/40730303/105637243-4afda280-5e21-11eb-92e2-ddcc9b3370ed.png)
