### ISSUE TITLE
Change Colors of Earned Points and Target Points on Sidebar

### ISSUE THREAD

**Issue by KPHowley** [hackforla/tdm-calculator#713]
### Overview
Change the Color of Earned Points to be orange before equaling target points, and green once it equals or is greater than target points.  Change  Target Points to be Green on Sidebar

### Action Items

- [x] Change the Color of Earned Points to be orange before equaling target points, 
- [x] Change the Color of Earned Points to be green once it equals or is greater than target points.
- [x] Change Target Points to be Green on Sidebar

### Resources/Instructions
Figma: TBD 

![Screen Shot 2021-01-17 at 6 23 43 PM](https://user-images.githubusercontent.com/49739276/104866275-ffb03500-58f2-11eb-9c9f-63937050d6ba.png)

**Comment by KPHowley** [comment]
@dreams0ng - Can you update this with the Figma link and a picture for this issues (2 of 3 issues)

**Comment by dreams0ng** [comment]
1. Progress
- Updated UI to match live site
2. Blockers
- N/A
3. Availability
- Any
4. ETA
- Presented

MOCKUPS

1. ![CC1](https://user-images.githubusercontent.com/22779768/105244892-007cdd00-5b26-11eb-8482-5451a1560cdc.png)
2. ![CC2](https://user-images.githubusercontent.com/22779768/105244902-0246a080-5b26-11eb-8d02-d3bd41ab877d.png)
3. ![CC3](https://user-images.githubusercontent.com/22779768/105244921-0a9edb80-5b26-11eb-8323-547c8e438473.png)
4. ![CC4](https://user-images.githubusercontent.com/22779768/105244925-0bd00880-5b26-11eb-9d02-d36fd89f6701.png)

![CC](https://user-images.githubusercontent.com/22779768/105244943-12f71680-5b26-11eb-94ba-b3e4997c54b7.gif)

LINKS
https://www.figma.com/proto/6h72XLxK76m4INtsSu8Mt0/TDM-Calculator-(Copy)?node-id=2392%3A222&viewport=-1041%2C821%2C0.1437286138534546&scaling=min-zoom

**Comment by jahpe777** [comment]
Changed Colors of Earned Points and Target Points on Sidebar #713

![Screen Shot 2021-01-26 at 11 36 09 AM](https://user-images.githubusercontent.com/40730303/105895971-11689b00-5fcb-11eb-8205-aa21ec754ce0.png)

![Screen Shot 2021-01-26 at 11 36 31 AM](https://user-images.githubusercontent.com/40730303/105896000-1c233000-5fcb-11eb-977a-a04fb9666604.png)

![Screen Shot 2021-01-26 at 11 36 48 AM](https://user-images.githubusercontent.com/40730303/105896015-234a3e00-5fcb-11eb-8467-f2e9a790b6d6.png)

![Screen Shot 2021-01-26 at 11 37 57 AM](https://user-images.githubusercontent.com/40730303/105896029-29401f00-5fcb-11eb-94c1-5f47aa9a3a50.png)

![Screen Shot 2021-01-26 at 11 38 03 AM](https://user-images.githubusercontent.com/40730303/105896053-30672d00-5fcb-11eb-93ba-514c121a7a95.png)

![Screen Shot 2021-01-26 at 11 38 06 AM](https://user-images.githubusercontent.com/40730303/105896073-36f5a480-5fcb-11eb-870a-15cd0c385ca0.png)

![Screen Shot 2021-01-26 at 11 38 19 AM](https://user-images.githubusercontent.com/40730303/105896091-3c52ef00-5fcb-11eb-8e0b-f6660e206d56.png)
