### ISSUE TITLE
Add success notification when Target Points equals Earned points on the side bar 

### ISSUE THREAD

**Issue by KPHowley** [hackforla/tdm-calculator#714]
### Overview

When Target points meets earned points display a message notifying the user 

### Action Items

- [x] Add message - TEXT TO BE ADDED BY UI 
- [x]  Only display message when Target points equals earned points
- [ ]  Leave message up for 5 seconds 

### Resources/Instructions

Figma: TBD

Picture: TBD

**Comment by KPHowley** [comment]
@dreams0ng  - Can you update this with the Figma link and a picture for this issues

**Comment by dreams0ng** [comment]
1. Progress
- Updated UI to match live site
2. Blockers
- N/A
3. Availability
- Any
4. ETA
- Presented

MOCKUPS
![TPS](https://user-images.githubusercontent.com/22779768/105229713-323b7700-5b19-11eb-9dc8-a017190acfbb.png)

https://user-images.githubusercontent.com/22779768/105243447-f2c65800-5b23-11eb-8f71-4de42c1948e5.mov

LINKS
https://www.figma.com/proto/6h72XLxK76m4INtsSu8Mt0/TDM-Calculator-(Copy)?node-id=2392%3A222&viewport=-1041%2C821%2C0.1437286138534546&scaling=min-zoom

**Comment by nclairesays** [comment]
@KPHowley I feel like it makes more sense for the notification to be a toast at the top center of the page. it's more noticeable that way.  And we have existing UI feature/behaviors already for this.

**Comment by KPHowley** [comment]
Discussion 2/24: Text should be black,  we will use a tooltip, positioning should be on side bar, as in the mock-up

**Comment by jahpe777** [comment]
Added success notification when Target Points equals Earned points on the side bar #714

![Screen Shot 2021-02-28 at 6 49 51 PM](https://user-images.githubusercontent.com/40730303/109446081-dc9a9a00-79f5-11eb-8e59-7a42d5b93194.png)
