### ISSUE TITLE
Update About Page Copy 

### ISSUE THREAD

**Issue by KPHowley** [hackforla/tdm-calculator#715]
### Overview
Update the Copy for the About Page

### Action Items

- [ ] Update About Page copy
- [ ] Make sure headers and margins are consistent with the rest of the web app.

### Resources/Instructions

Document with Text:
https://docs.google.com/document/d/17BOkryqIPCa_Fb1X-eF2JboW_JuH1E3EnXnWqx1sa5w/edit

**Comment by Jonathanko52** [comment]
About page contents updated and CSS changed. Pull request made.

**Comment by Jonathanko52** [comment]
Additional Change: Left align the headers
