### ISSUE TITLE
tool tip icon for earned points should be consistent with target points

### ISSUE THREAD

**Issue by nclairesays** [hackforla/tdm-calculator#719]
When the app is a specific width, the tooltip icon under earned points is not consistent with the one under target points

![image](https://user-images.githubusercontent.com/45305029/105139816-a7706300-5aab-11eb-8ef4-406a4244ebde.png)

**Comment by jahpe777** [comment]
Tooltip icon for earned points is now consistent with target points #719

![Screen Shot 2021-03-08 at 9 40 29 AM](https://user-images.githubusercontent.com/40730303/110359479-64823480-7ff2-11eb-8595-fdd2d3ed74a0.png)

**Comment by ExperimentsInHonesty** [comment]
@jahpe777 can you update the labels for this issue and then close it please.

**Comment by ExperimentsInHonesty** [comment]
No longer an issue because we moved to dial format
