### ISSUE TITLE
Create survey for user testing 

### ISSUE THREAD

**Issue by KPHowley** [hackforla/tdm-calculator#725]
### Overview
Create a questionnaire for the user pre-survey  

### Action Items
- [x] Develop first round of questions 
- [x] Review with Product team 
- [x] Share With LADOT 
- [x] Revise 
- [x] Create survey in ArcGIS
- [ ] Share with LADOT

### Resources/Instructions

Link TO Draft of Survey:   [https://arcg.is/0HqL09](https://arcg.is/0HqL09)

 [Survey Questions Draft 2](https://docs.google.com/document/d/11nwSyPwxDObe5EKqlwCA0tFbqdKCw_chHDojGetMMko/edit?ts=60318304)
[Survey questions that were used for the DONE website survey](https://docs.google.com/document/d/13iI-GPFDMn99Mv74iNifvADyXqRwtQ59xcRB_j94U2o/edit)

**Comment by KPHowley** [comment]
For internal testing Researchers should use the email: Test@Dispostable.com

**Comment by KPHowley** [comment]
Proposal of changes from @anamsha : [Survey Questions Draft 2](https://docs.google.com/document/d/11nwSyPwxDObe5EKqlwCA0tFbqdKCw_chHDojGetMMko/edit?ts=60318304)

**Comment by KPHowley** [comment]
Published a draft version of the survey in ArcGIS   -  https://arcg.is/0HqL09

**Comment by ExperimentsInHonesty** [comment]
on the first page
![Screen Shot 2021-03-10 at 3 28 46 PM](https://user-images.githubusercontent.com/37763229/110712053-67795280-81b5-11eb-82fa-6851a92c7b5a.png)

Please change this
We will be sending follow up emails to those selected with more information and a link to schedule a 30 minute User Testing session with Hack for LA, who has partnered with the LADOT and LACP to develop the TDM Calculator website.

to this
We will be sending follow up emails to those selected with more information and a link to schedule a 30 minute User Testing session with Hack for LA.

LADOT and LACP have partnered with Hack for LA to develop the TDM Calculator website.

**Comment by ExperimentsInHonesty** [comment]
It feels like there is a disconnect or a shorthand we are using when we take people from this screen
![Screen Shot 2021-03-10 at 3 36 54 PM](https://user-images.githubusercontent.com/37763229/110713256-757ba300-81b6-11eb-91a4-05c0ac85af1f.png)
to this screen
![Screen Shot 2021-03-10 at 3 37 21 PM](https://user-images.githubusercontent.com/37763229/110713294-85938280-81b6-11eb-8b2a-e1b0c18ff467.png)
Please look at the wording of the question we are taking them to and see if we can tie them more closely together.  I had to click the back button to see what I had just answered.

**Comment by ExperimentsInHonesty** [comment]
I think the survey allows for embedding of images.  Is it possible to put the LADOT and LACP and HfLA logo on this survey.  Also can we control the colors?

**Comment by KPHowley** [comment]
@ExperimentsInHonesty @kevinshih613 

-  I just updated the text on the first page
- On questions 1 &2  we can give it a little though
- On the colors and images - we can customize the colors, and can make them consistent with the calculator, however the only picture we can upload is one which would be displayed as a background (behind the Component that displays the survey). We might be able to use the icon set or something similar, but will need to look into this.

**Comment by KPHowley** [comment]
@ExperimentsInHonesty and @kevinshih613  :

I took a stab at adjusting the wording on the first question a bit, and updated the colors. I attempted to add a logo but this is a bit of a complicated work around to do. 

Please take a look and let me know if you feel OK with sending this over to LADOT/Planning to review.
