### ISSUE TITLE
UI/UX Survey and usabilty test plan - Overview

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/tdm-calculator#726]
### Overview
We need a survey plan so that we can create all the related issues

### Action Items
- [x] Define Personas #724 
- [x] See Goals for Hack for LA community Outreach
- [x] Work on a  list of questions For Product Survey #725 
- [x] Review First round of questions Saturday 1/30 and share with partners Tuesday 2/1 
- [x] Get more information from partner re types of developers (see below)
- [x] Create a sample document for questionnaire
- [x] Come up with wording for sharing the survey
- [x] Speak with other UI Community members (Dana Chen from 311-data)
- [x] Come up with Schedule for Survey
- [x] Develop charts for LADOT Presentation
- [x] Work on Detailed user interview Plan [733](https://github.com/hackforla/tdm-calculator/issues/733)

#### Personas List 

   - Large (number of employees/annual projects/size of projects?)
   - Small (number of employees/annual projects/size of projects?)
- Real Estate Developers
- Real Estate Financers
- Real Estate Owners
- Transportation Consultants
- Architects & AIA
- Land use attorneys
- Expeditors
- Citizens
- Activists and Public Policy groups
- Neighborhood Council Transportation Committee member
     Other considerations
- Want geographical representations as well  

#### Links

Example of Survey: [DONE Survey](https://docs.google.com/document/d/13iI-GPFDMn99Mv74iNifvADyXqRwtQ59xcRB_j94U2o/edit)

[Code For America Interview Training - Github](https://github.com/codeforamerica/brigade-playbook/wiki/Training-for-Interviews)

 [Code For America Interview instructions -Doc](https://docs.google.com/document/d/1cQumMP3mBUR595ZUkOgxoiLPkLL4WmgRWcAP_e3cWoQ/edit#heading=h.cqoydgo3qccu)

 [Sample Script - Brigade Organizer Playbook](https://docs.google.com/forms/d/e/1FAIpQLScis5UgFcNXKFxxioozsQVEJbQFuhE84W9W-Z3MQS_BQOseRA/viewform?entry.963965308=000&entry.666737716=Code+Island&entry.7436934=Clark+Kent&entry.2107947631=Clark+Kent&entry.1936764276=1&entry.1596745969=1&entry.20968895=1&entry.220171659=1&entry.744655585=1&entry.87105960=1&entry.764846038=1&entry.838021204=1&entry.2090362621=1&entry.1620052194=1&entry.1755843168=1&entry.1513441199=1&entry.115635811=1&entry.725190403=1&entry.830064905=1&entry.2133624628=1&entry.1392108993=1&entry.270807956=1&entry.1254273785=1&entry.1341981479=Batman&entry.367451046=Yes&entry.1777111311=Clark+Kent&entry.526388299=Save+Gotham&entry.26483174=Video&entry.1444254824=1&entry.1540797580=Batcave+visit&entry.1513478109=Email+Clark&entry.611037114=Yes&entry.1601355305=Clark+Kent&entry.1619466247=Rescue+someone&entry.567205019=Video&entry.1994972314=1&entry.1400149957=Batcar&entry.1230232240=Take+a+ride&entry.1582132702=No&entry.1550151393=Clark+Kent&entry.769408763=I%27m+batman.&entry.1722247594=10&entry.763928116=One+millenium.&entry.1124824014=Yes&entry.1454706658=Never&entry.934901218=Clark+Kent&entry.1365932542=1&entry.737328644=10&entry.1421219581=Clark+Kent&entry.1809304853=No&entry.1693546739=My+co-captain+Robin&entry.2138785186=N/A&entry.1923194020=Fully+public)

**Comment by ExperimentsInHonesty** [comment]
@KPHowley @kevinshih613 I spoke to LA Department of Neighborhood Empowerment, and Julien let me know that any city department can use the ArcGIS survey tools.  They just have to ask for access by emailing Mayor.OpenData@LACity.org with the Subject=GeoHub Account Request.  I am going to write to David and Emily via email.

We had quite a detailed conversation about the tool and its advantage over google forms.  It's definitely got more functionality and one of the features that it includes is the ability to embed images.

In the meantime, please signup for an account so we can start playing with the tool
https://geohub.lacity.org/ click sign in and setup an account using the tdm-ux@hackforla.org account

**Comment by KPHowley** [comment]
Discussion From 2/18:

Questionnaire - Created by Hack for LA and LADOT, Sent out by LADOT/Planning

    Waiting for deliverables from LADOT (log in info From arcGIS)
    Will finish and send out on or before march 1st
    Can start on personas based off occupations already
    Need to keep eye on demographic distribution

UX Researcher Training - Hack for LA

    Documents: Script or "discussion guide with listening points"
    Sample Projects: Waiting on deliverables from LADOT
    Kevin needs to request specific project information from LADOT Planning
    Mock interviews should be given before and after
    Run as a workshop.
    Look into using Miro or something similar
    Weekend of 13th tentative schedule for this.

Follow up email (Requesting documents and scheduling)

    need determination of who will send
    Pending time - March 8th
    Will discuss further

Guided user experience testing - Run by Hack for LA

    Start of the week of march 22st
    Most documents will be Ready bu IX training

Analysis - Hack for LA initially, data available and reviewed by LADOT/Planning

    Will discuss more later
