### ISSUE TITLE
Apply for JetBrains IntelliJ IDE free license

### ISSUE THREAD

**Issue by nclairesays** [hackforla/tdm-calculator#737]
### Dependency - Issue #755 

So I was just looking into using [IntelliJ IDEA IDE](https://www.jetbrains.com/idea/features/editions_comparison_matrix.html) (software by Jet Brains). It’s one of the best IDEs out there and supports many different languages for web development. I would like to use it while I code for HFLA because it’s a lot easier, powerful, and efficient compared to Visual Studio Code for how I work.

While I was researching, I discovered that they issue [free licenses](https://www.jetbrains.com/community/opensource/#support) for open source projects! Could we apply for some licenses? If approved, they actually grant the leads/core project committers licenses to [all their JetBrain tools](https://www.jetbrains.com/products/) for a year (about $250 worth per individual licenses)! Pretty sweet deal.  

Only caveat, they do ask for our repo, project description, and website links in the application. I’m not sure how our NDA may affect this. Was thinking we can keep these responses abstract or only include the git repo but not the website?

[The form](https://www.jetbrains.com/shop/eform/opensource) is pretty straight forward. I can just apply if it sounds good to you guys!

**Comment by ExperimentsInHonesty** [comment]
@nclairesays can you provide a link to the form.  the link you provided above just goes to their product page

**Comment by nclairesays** [comment]
@ExperimentsInHonesty apologies, i linked the wrong url in my original post.  Here it is for your convenient https://www.jetbrains.com/shop/eform/opensource

**Comment by KPHowley** [comment]
We have to review our license in github before we move forward with this. A new issue will be open and this issue is dependent upon that.
