### ISSUE TITLE
Create a Script for the Guided User Test 

### ISSUE THREAD

**Issue by KPHowley** [hackforla/tdm-calculator#742]
### Overview
 Develop a script for the guided user test for UX researchers to use.

### Action Items

- [ ] Develop first pass 
- [ ] Review with TDM Product team
- [ ] Revise
- [ ] Review with LADOT
- [ ] Revise
- [ ] Perform timed  mock interview

### Resources/Instructions
[Example of Current Permit Document](https://planning.lacity.org/odocument/3d913582-d6e7-4375-90e8-3e276b9c28bb/Department%20of%20City%20Planning%20Application.pdf)

In progress usability test guide: https://docs.google.com/spreadsheets/d/1M5DBKVm9pOgmzjXyUCUS8tCsF00lfZYvI6Fpi8qGNc8/edit?ts=6061e355#gid=670903472

**Comment by anamsha** [comment]
In progress usability test guide: https://docs.google.com/spreadsheets/d/1kndkqEZsFldaV0sNWyHwO3cgnUnX2XYjGX5V8OtrXww/edit?usp=sharing

**Comment by VJ1285** [comment]
@anamsha I updated the google sheet link.

**Comment by anamsha** [comment]
Doc version of guide: https://docs.google.com/document/d/1vxullaEgTGNxFlrKDOsGzYFSiOAazNgiubFYOxY6h30/edit#heading=h.oo7cvu53wf50

Master google sheets file: https://docs.google.com/spreadsheets/d/1kndkqEZsFldaV0sNWyHwO3cgnUnX2XYjGX5V8OtrXww/edit#gid=0
