### ISSUE TITLE
Create sample projects  & project information sheets for the guided user test

### ISSUE THREAD

**Issue by KPHowley** [hackforla/tdm-calculator#743]
### Overview
Some users will need to be provided projects, and we need to create these projects and determine the scope and type of them, how many projects are need  

### Action Items

- [x] Determine Number and type of projects to be supplied
- [x] Create one mock up project sheet 
- [ ] Review with Hack for LA 
- [x] Review with LADOT
- [ ] Create all sheets
- [ ] Make Project sheets available and ready for User testing 

### Resources/Instructions

Proposed List Of Sample Projects:

https://docs.google.com/spreadsheets/d/1Qi_GuJJSO6Y12r5LyqnrBN4spX0-SG3j0BNl50IKZog/edit#gid=2110000857

[types of Sample Projects](https://docs.google.com/spreadsheets/d/1x-Hx_bNZ8d6YjRIU6kog37tFaB3j1DZ7ZCh1a3W8fW4/edit?usp=sharing)

Sampple documents for reference: 

[Sample Permit Application](https://planning.lacity.org/pdiscaseinfo/document/MTQ1NTM0/148832b8-0422-4180-949f-53278685ec6d/esubmit)

[Assessment Form ](
https://planning.lacity.org/odocument/2cfe7c08-54e2-4d73-8bab-58cc4a6cbe42/Transportation%20Study%20Assessment.pdf)

**Comment by anamsha** [comment]
https://docs.google.com/presentation/d/1wznzfoLwsPsEYT335iZlL0AzIAe-7mhwZplC390VBv0/edit#slide=id.gcf739112c6_0_24
