### ISSUE TITLE
Develop Template to apply Analytics to other Web Products

### ISSUE THREAD

**Issue by VJ1285** [hackforla/tdm-calculator#750]
### Overview
As part of applying analytics to the TDM calculator, develop a template that can be used across HackforLA

### Action Items

- [ ] Step by Step Instruction Guide on Google Document to set-up dashboards. 

### Resources/Instructions
https://docs.google.com/document/d/14t06vRGA9DhpxEjZqWascmBqhsVJFohcMUDb0DaLSIk/edit?usp=sharing

**Comment by ExperimentsInHonesty** [comment]
We will not be doing this.  The hack for LA website team will be making a guide.  We will be making our own guidance on azure on this issue #941
