### ISSUE TITLE
Review UX for consistency

### ISSUE THREAD

**Issue by VJ1285** [hackforla/tdm-calculator#751]
### Overview
Review UX for consistency before user testing begins. 

### Action Items

- [ ] Review UX
- [ ] Make issues to address UX issues

google doc with review comments: 
https://docs.google.com/document/d/1AoJvxvmL91G2RM5SVyvO7yqxy89wLrG3Nq6dFpzXJ1Y/edit?usp=sharing

**Comment by VJ1285** [comment]
@KPHowley - Please review the google doc document with my review.

**Comment by ExperimentsInHonesty** [comment]
@VJ1285 will review document to make sure that all items are addressed, and make issues for any that are not, adding them to the tracker as necessary

**Comment by KPHowley** [comment]
@VJ1285  - Are you alright with us closing this?
