### ISSUE TITLE
Review Project License in Github 

### ISSUE THREAD

**Issue by KPHowley** [hackforla/tdm-calculator#755]
### Overview
We need to review our project's license in git hub to make sure it is accurate to 

### Action Items

- [ ]  Review License at [github.com/hackforla/tdm-calculator/blob/develop/LICENSE](https://github.com/hackforla/tdm-calculator/blob/develop/LICENSE) 
- [ ] Investigate licenses used for other projects 
- [ ]  Find correct license format/wording and update 

### Resources/Instructions

[github.com/hackforla/tdm-calculator/blob/develop/LICENSE](https://github.com/hackforla/tdm-calculator/blob/develop/LICENSE) 

**Issue #737 is a dependency on this**

**Comment by KPHowley** [comment]
Discussion 2/24: We are using a MIT License. We may need to switch to the newer GPL 2 license

**Comment by ExperimentsInHonesty** [comment]
We need to use the following license
https://github.com/hackforla/.github/blob/main/LICENSE
we will need to inform users.  I will write up the instructions for that.

**Comment by ExperimentsInHonesty** [comment]
Sent @akibrhast this message in the  TDM slack channel   

`@Akib Rhast Can you figure out where the script that was here https://github.com/akibrhast/website/blob/gh-pages/.github/workflows/contributors.yml has gone.  It was a script to grab all the contributors to a repo so that we can change the license.  Did you ever commit it to a hackforla repo? Or do you have another copy someplace.  We need it on this project.`

**Comment by ExperimentsInHonesty** [comment]
When we have the list of people, we open a new issue and do not link to it from anywhere.  That issue will be formatted like this issue 
https://github.com/hackforla/VRMS/issues/449

**Comment by akibrhast** [comment]
@ExperimentsInHonesty , sorry to be not helpful and bearer of bad news. I had committed it somewhere, but I have tried going back through my commit histories and for the life of me , am unable to find the action anymore.... 🙄😶

**Comment by fyliu** [comment]
> That issue will be formatted like this issue `https://github.com/hackforla/VRMS/issues/528`

Wow! We're switching to AGPL3? That's a bold stance. I personally support using the strong copy-left licenses so people don't just take the code and say goodbye.

**Comment by entrotech** [comment]
I think @ExperimentsInHonesty wanted to take herself off this issue and let us follow through with changing the license and notifying the contributors.  Would you like to take this one @fyliu ?

**Comment by fyliu** [comment]
@entrotech oh really. Sure, I can take this one. Just extract all the repo contributors and use the VRMS issue as a template to call for the license change, right?

**Comment by fyliu** [comment]
@ExperimentsInHonesty I can extract all the contributors from git logs but is that enough? I remember seeing an action that also extracted non-coding contributors to the project as well. Is that what you were referring to?

**Comment by fyliu** [comment]
Here are all the contributors to our git repo and their number of commits. It's a complete list, but doesn't 
<details>
  <summary>Here are all the contributors to our git repo and their number of commits. It's a complete list, but doesn't show if they have code in the current HEAD of the repo</summary>

  ```
$ git shortlog --email --numbered --summary --no-merges
   256   John Darragh <darragh@entrotech.net>
   213   nclairesays <45305029+nclairesays@users.noreply.github.com>
   124   Fang Liu <fangyiliu@gmail.com>
    58   Fang Yi Liu <fangyiliu@gmail.com>
    51   James Higgs <james.y.higgs@gmail.com>
    49   Louis Mazza <louismazza@gmail.com>
    40   Jonathan Ko <jonathan.ko523@gmail.com>
    37   Natalie <49847911+natjng@users.noreply.github.com>
    27   Bradley Fojas <bradfojas@gmail.com>
    21   alexchoiweb <alexchoiweb@gmail.com>
    20   Mindy Morgan <multimindia@gmail.com>
    20   dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>
    17   Nicholas Pung <nckpng95@gmail.com>
    10   Dean Church <paridox@hotmail.com>
     9   Bradley Fojas <43628838+bfojas@users.noreply.github.com>
     8   Bishoy Tawfik <btprogramer@gmail.com>
     7   Claire N <45305029+nclairesays@users.noreply.github.com>
     7   tan-nate <nktan93@gmail.com>
     5   Bonnie Wolfe <37763229+ExperimentsInHonesty@users.noreply.github.com>
     4   Louis Mazza <32402365+lemazza@users.noreply.github.com>
     4   Tyler Thome <tyler.thome@outlook.com>
     3   nicholaspung <nicholaspungdev@gmail.com>
     3   pelmini <vbai@go.pasadena.edu>
     2   Claire N <ms.clarewynn@gmail.com>
     2   fyliu <fyliu@users.noreply.github.com>
     1   David Somers <david.somers@lacity.org>
     1   Nicholas Pung <nicholaspung>
     1   R-Tomas-Gonzalez <tomas@rtomasgonzalez.com>
     1   Vivek Jha <70343417+VJ1285@users.noreply.github.com>
```
</details>

<details>
  <summary>Here's one using git blame to get all lines from the head of the repo HEAD, listing by email. It unfortunately includes merge commits. I think Mindy has so many lines because she made changes that touched a lot of files, so the lines' original author info are lost.</summary>

```
$ git ls-files | \
> while read f; do \
>     git blame -w -M -C -C --line-porcelain "$f" | \
>    grep -I '^author-mail '; \
> done | cut -f2 -d'<' | cut -f1 -d'>' | sort -f | uniq -ic | sort -n --reverse
  87383 darragh@entrotech.net
  77554 multimindia@gmail.com
  12202 45305029+nclairesays@users.noreply.github.com
   4061 fangyiliu@gmail.com
    669 louismazza@gmail.com
    633 james.y.higgs@gmail.com
    467 nckpng95@gmail.com
    450 alexchoiweb@gmail.com
    368 bradfojas@gmail.com
    313 jonathan.ko523@gmail.com
    296 49847911+natjng@users.noreply.github.com
    283 43628838+bfojas@users.noreply.github.com
    244 37763229+ExperimentsInHonesty@users.noreply.github.com
    133 btprogramer@gmail.com
     92 tomas@rtomasgonzalez.com
     59 49699333+dependabot[bot]@users.noreply.github.com
     22 nktan93@gmail.com
     21 ms.clarewynn@gmail.com
     18 fyliu@users.noreply.github.com
     12 tyler.thome@outlook.com
     10 nicholaspungdev@gmail.com
      9 nicholaspung
      4 paridox@hotmail.com
      4 not.committed.yet
      2 david.somers@lacity.org
      2 32402365+lemazza@users.noreply.github.com
```
</details>


<details>
  <summary>This command is similar but lists by authors</summary>

```
$ git ls-files | while read f; do git blame -w -M -C -C --line-porcelain "$f" | grep -I '^author '
; done | sort -f | uniq -ic | sort -n --reverse                                                                                               
  87383 author John Darragh                                                                                                                   
  77554 author Mindy Morgan                                                                                                                   
  12175 author nclairesays                                                                                                                    
   2092 author Fang Yi Liu                                                                                                                    
   1969 author Fang Liu                                                                                                                       
    671 author Louis Mazza                                                                                                                    
    651 author Bradley Fojas                                                                                                                  
    633 author James Higgs                                                                                                                    
    476 author Nicholas Pung                                                                                                                  
    450 author alexchoiweb                                                                                                                    
    313 author Jonathan Ko                                                                                                                    
    296 author Natalie                                                                                                                        
    244 author Bonnie Wolfe                                                                                                                   
    133 author Bishoy Tawfik                                                                                                                  
     92 author R-Tomas-Gonzalez                                                                                                               
     59 author dependabot[bot]                                                                                                                
     48 author Claire N                                                                                                                       
     22 author tan-nate                                                                                                                       
     18 author fyliu                                                                                                                          
     12 author Tyler Thome
     10 author nicholaspung
      4 author Not Committed Yet
      4 author Dean Church
      2 author David Somers
</details>

**Comment by fyliu** [comment]
Testing quoting github handles
```
@fyliu 
```

**Comment by fyliu** [comment]
Test quoting github handle

> @fyliu

**Comment by fyliu** [comment]
Command asking github for code contributors.
$ curl   -H "Accept: application/vnd.github.v3+json"   https://api.github.com/repos/hackforla/tdm-calculator/contributors? anon=1 > contributors.json

The results misses 2 contributors.
- vbai@go.pasadena.edu had 3 commits that I read through and none of that code is in the HEAD of the current main branch
- Tyler Thome does still have 12 lines of code, mostly in Dockerfile. I've messaged him for his github handle

Putting together github handle with name and email
<details>
  <summary>click to expand</summary>

```
entrotech
 256   John Darragh <darragh@entrotech.net>
nclairesays
 222   nclairesays <45305029+nclairesays@users.noreply.github.com>
fyliu
 184   Fang Liu <fangyiliu@gmail.com>
jahpe777
  51   James Higgs <james.y.higgs@gmail.com>
lemazza
  53   Louis Mazza <louismazza@gmail.com>
Jonathanko52
  40   Jonathan Ko <jonathan.ko523@gmail.com>
bfojas
  36   Bradley Fojas <bradfojas@gmail.com>
natjng
  37   Natalie <49847911+natjng@users.noreply.github.com>
alexchoiweb
  21   alexchoiweb <alexchoiweb@gmail.com>
nicholaspung
  21   Nicholas Pung <nckpng95@gmail.com> <nicholaspungdev@gmail.com>
mmorgs
  20   Mindy Morgan <multimindia@gmail.com>
ExperimentsInHonesty
   5   Bonnie Wolfe <37763229+ExperimentsInHonesty@users.noreply.github.com>
Rankazze
  10   Dean Church <paridox@hotmail.com>
Bishoy-Tawfik
   8   Bishoy Tawfik <btprogramer@gmail.com>
tan-nate
   7   tan-nate <nktan93@gmail.com>
VJ1285
   1   Vivek Jha <70343417+VJ1285@users.noreply.github.com>
R-Tomas-Gonzalez 
   1   R-Tomas-Gonzalez <tomas@rtomasgonzalez.com>
Dsomers74
   1   David Somers <david.somers@lacity.org>

   4   Tyler Thome <tyler.thome@outlook.com>
   3   pelmini <vbai@go.pasadena.edu>
```
</details>

**Comment by ExperimentsInHonesty** [comment]
@fyliu we don't need their emails, we just need their GitHub handles.  Please provide that in a code block.  Ideally all run together, e.g.
```
@ExperimentsInHonesty @fyliu @Shaeeka @Jane4925 
```

**Comment by fyliu** [comment]
@ExperimentsInHonesty Will do. They're actually in my last comment but I didn't @ them since it'll notify them even within a code block or a > quote.

I will create a new issue with a block in serial format and send you the issue number here so you can check it before I add the @. It'll just be the number without the # so it doesn't link to here.

**Comment by fyliu** [comment]
@ExperimentsInHonesty I created the license change issue in `https://github.com/hackforla/tdm-calculator/issues/997` but I want to confirm a couple things.

1. We're changing to "GPL2.0 or later" for tdm-calculator as opposed to "AGPL3.0 or later" that's used for VRMS, yes?
2. IANAL, but I'm fairly certain the way it's done for VRMS doesn't pass legally. Posting a notice and getting no responses is not the same as getting permission. The original authors must give permission for the new license or their code is not covered by the new license.
3. For our case of the code already being under MIT, the license permits anyone to also sub-license the code under GPL without asking for permission. This would result in a dual MIT plus GPL license, which is effectively GPL, but the text of the MIT must also be included. I'm sure this is not the desired outcome since it's not as clean as getting permission from the authors and be free of the MIT license.

**Comment by fyliu** [comment]
Here's information from a friend who's look into software licenses more than myself. This a potential way to get the signatures for the license change.
https://github.com/cla-assistant/cla-assistant

Here's a pull request in his project where he asks the other contributor to sign to agree to a license change. It places a button in the pull request and contributors can click on it to read and sign to use the new license.
`https://github.com/mbe-shipyard/sysml.py/pull/41`

There's a possibility that a former contributor doesn't see it and doesn't complete the signature step. This is why I extracted the list of contributors and lines of current code they're responsible for in a comment above, in case we don't get their permission.

**Comment by ExperimentsInHonesty** [comment]
Hi Fang, I see you put the list of contributors on 997 what I need is the following format though with handles

```
@ExperimentsInHonesty @fyliu @Shaeeka @Jane4925 
```

**Comment by fyliu** [comment]
@ExperimentsInHonesty I've updated 997 to tag everybody.
