### ISSUE TITLE
Enforce Secure Password

### ISSUE THREAD

**Issue by nclairesays** [hackforla/tdm-calculator#762]
### Overview
We should enforce users to create strong passwords.

### Action Items

Make the password so it requires: 
- [x] 12 Characters 
- [x] 1 Special Character
- [x] 1 Capitalization 
- [x] 1 Number

Update wording on red warning box under "password" on  /register page to "

- [x] "Your password must have at least 12 characters, at least one number, one special character, and one capitalization"

**Comment by jahpe777** [comment]
#762 Implemented password requirements

<img width="950" alt="Screen Shot 2021-04-27 at 9 00 05 AM" src="https://user-images.githubusercontent.com/40730303/116273891-00990400-a737-11eb-9e50-fe5d44e2624f.png">

**Comment by nclairesays** [comment]
@KPHowley Just fyi, i updated the issue to include 12 characters minimum and at least 1 number. These things are pretty standard for secure passwords these days.
