### ISSUE TITLE
Create draft for email sending out initial UX survey

### ISSUE THREAD

**Issue by KPHowley** [hackforla/tdm-calculator#768]
### Overview

Our email survey needs to be sent out in an email explaining it. We need to take a first pass at the draft of this email  and share with LADOT

### Action Items

- [x] Write draft of email in Google Sheet: [TDM Survey Email Draft](https://docs.google.com/document/d/16C6vepVsvq-JM3OQHQ-XhK04yNnCILMpXyb3NZfrBOI/edit?usp=sharing)
- [ ]  Share with LADOT and Planning

### Resources/Instructions.

Reference this wording from D.O.N.E's survey with hack for LA. 
https://empowerla.org/redesign/

 [TDM Survey Email Draft](https://docs.google.com/document/d/16C6vepVsvq-JM3OQHQ-XhK04yNnCILMpXyb3NZfrBOI/edit?usp=sharing)

**Comment by ashaikh05** [comment]
Started throwing ideas into the doc, using inspiration from the reference provided. Feel free to contribute, revise, edit, all that good stuff.

**Comment by VJ1285** [comment]
@KPHowley - I edited the google doc. Let me know your thoughts. What's left is the link to the survey and actual dates. I also made this below document
https://docs.google.com/document/d/1p7dC-1Kpvyd1E2yIxkOLyYXlMco2rFaKrv0m-xcdkcU/edit?usp=sharing

**Comment by VJ1285** [comment]
@ashaikh05 - I reviewed your template and have some comments. Let me know if you want to go over the comments together so we can finalize the email and send it for @KPHowley and then @ExperimentsInHonesty approval.

**Comment by VJ1285** [comment]
@KPHowley - @anamsha   and I worked on the draft based on Saturday's meeting discussion. Let us know your thoughts. if it looks good, please ask @ExperimentsInHonesty to review and give us the final go-ahead.

**Comment by KPHowley** [comment]
I updated this again! [EMAIL DRAFT](https://docs.google.com/document/d/16C6vepVsvq-JM3OQHQ-XhK04yNnCILMpXyb3NZfrBOI/edit?usp=sharing )

**Comment by ExperimentsInHonesty** [comment]
@KPHowley ill have some comments tomorrow

**Comment by ExperimentsInHonesty** [comment]
This was done.  See wiki for research communication details
