### ISSUE TITLE
Display "Yes" or "No" in the final summary sheet for Affordable housing

### ISSUE THREAD

**Issue by VJ1285** [hackforla/tdm-calculator#778]
### Overview
Currently, if the user selects Affordable housing on Pg 2. The final results do not note that the project includes affordable housing. 

### Action Items
Add "Yes" or "No" option in the result based on user selection of Affordable housing on page 2. 

### Resources/Instructions
https://docs.google.com/document/d/1AoJvxvmL91G2RM5SVyvO7yqxy89wLrG3Nq6dFpzXJ1Y/edit?usp=sharing

**Comment by Jonathanko52** [comment]
Now displays "yes" or "no" if there's a boolean in the calculations. May want to adjust the CSS for the fields, as the affordable housing line seems squished.
