### ISSUE TITLE
Add "NA" as one of the option to all items on Page 4 

### ISSUE THREAD

**Issue by VJ1285** [hackforla/tdm-calculator#779]
### Overview
We need to add "NA" as one of the options to all the items on Page 4. Currently, some items have "NA" while others don't.

### Action Items

- [ ] Affordable Housing - Add "NA" as an option
- [ ] Shared Parking - Change "<25% Spaces Shared" to "NA"

### Resources/Instructions
https://docs.google.com/document/d/1AoJvxvmL91G2RM5SVyvO7yqxy89wLrG3Nq6dFpzXJ1Y/edit?usp=sharing

**Comment by nclairesays** [comment]
I lost permission to assign myself and push my code but I've completed this issue
