### ISSUE TITLE
Add an option to update Profile Information

### ISSUE THREAD

**Issue by VJ1285** [hackforla/tdm-calculator#780]
### Overview
We need to add an option that allows users to update their profile information so that if their information changes they can update. 

### Action Items
- [x] Determine the intended functionality of the Profile information page (answer questions below)
- [ ] Clarify feature for further UI design
- [x] Mock up a profile page
-
#### Questions
- What will happen when the account that is tied to a user's email address, is their personal address, and they leave the company they are at?
- What happens to the projects and the profile when a user uses their company email address and then they leave and another team member becomes responsible?

**Comment by KPHowley** [comment]
This Issue needs to be fleshed out for design.

**Comment by jahpe777** [comment]
Implemented a new page and flow to update account information.
