### ISSUE TITLE
Create Public Facing Website with Landing Page

### ISSUE THREAD

**Issue by KPHowley** [hackforla/tdm-calculator#782]
### Overview

We are creating a separate Public facing website for the TDM calculator project. This will be made in the New GitHub Repo and will currently display one landing page, a privacy policy and linking to other resources

### Action Items

- [x] Create GitHub repo for the -  LA TDM Calculator Webpage
- [x] Create HTML Landing page.  
- [x] Connect Links
- [ ] Connect to Domain Name (PENDING FINAL DECISION on Name)
- [ ] Create Privacy Policy (PENDING APPROVAL & DESIGN)

### Resources/Instructions

[Figma Document with Landing Page Design](https://www.figma.com/file/qNgPc5lttpf0SWSwkbbWyT/TDM-Calculator?node-id=3062%3A11962)
[Privacy Policy content](https://docs.google.com/document/d/1TeKVCYCIX0MdNJ004ZA4n5iQ6cP33dFbDk0m1BRbU68/edit)
[Temp url](https://hackforla.github.io/tdm-calculator-landing/)
GitHub Repository: https://github.com/hackforla/tdm-calculator-landing/

**Comment by KPHowley** [comment]
@ExperimentsInHonesty  - My initial design for the Landing Page is linked in here, can you review this as well as the requirements for creating the new public facing website

**Comment by ExperimentsInHonesty** [comment]
@qiqicodes has volunteered.
