### ISSUE TITLE
Convert styles from scss to jss where possible

### ISSUE THREAD

**Issue by nclairesays** [hackforla/tdm-calculator#790]
### Overview
Convert styles from scss to jss where possible so that we are not maintaining styles in multiple places.  There has also been issues that arose from us resetting the default html elements. We should use the default ones and customize them in the components intentionally. 

### Action Items

- [ ] Convert styles from scss to jss where possible 

### Dependency
- [x] #1562
- [ ] #1585

**Comment by Biuwa** [comment]
**Please provide an update:**

1. **Progress**_(What is the current status of your project? What have you completed, and what is left to do)_:
2. **Blockers**_(Difficulties or errors encountered)_:
3. **Availability**_(How much time will you have this week to work on this issue)_:
4. **ETA**_(When do you expect this issue to be completed)_:
5. **Pictures** _(if necessary)(Add any pictures that will help illustrate what you are working on)_:

**Comment by heejung-hong** [comment]
1. **Progress**: Completed analysis of Calculation.scss page and ready to create sub issues to convert Calculation.scss to JSS.
2. **Blockers**: No blockers at this time
3. **Availability**: Mon-Fri after 6pm. 
4. **ETA**: Thurs 01/01/24
5. **Pictures**:
