### ISSUE TITLE
Create Follow up  Email Draft to schedule usability testing 

### ISSUE THREAD

**Issue by KPHowley** [hackforla/tdm-calculator#796]
### Overview
Create Follow Email Draft to schedule usability testing 

### Action Items

- [ ] Come up with Proposed email draft 
- [ ] Review 
- [ ] Share with LADOT Tuesday 4/13

### Resources/Instructions

[Usability Test Scheduling Email Draft](https://docs.google.com/document/d/1T2kdLIlo-_BamIH3m_WPiBhQh2ILhpv-L7BJ7afGMsw/edit?usp=sharing)

**Comment by KPHowley** [comment]
@kevinshih613 - take a look at the doc [Email Draft](https://docs.google.com/document/d/1T2kdLIlo-_BamIH3m_WPiBhQh2ILhpv-L7BJ7afGMsw/edit?usp=sharing) and let me know what we need to ask for

**Comment by ExperimentsInHonesty** [comment]
Hi @KPHowley I have rewritten the draft.  Its below the current draft.  Just trying to make it more concise.  Also there was a sentence in the bullets in the first draft and now second that is unfinished.
