### ISSUE TITLE
Making landing pages for the interviews

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/tdm-calculator#797]
### Overview
We need to simplify the usability testing process and have one link to send participants

### Action Items
- [X] @anamsha 
   - [X] Make PDFs for all of the test cases
   - [X] Make unique user/passes for each interview (30 to start)
- [ ] @kevinshih613
   - [x] Build spreadsheet of people being interviewed
      - [x] role
      - [x] if they are bringing their own case
      - [x] if they are not brining their own case, what test case we want to assign them
- [ ] @ExperimentsInHonesty 
   - [ ] Make webpages
      - [ ] test case link (if needed)
      - [ ] all test cases (incase something goes wrong or they want to create more)
      - [ ] url to the application: https://tdmuat.azurewebsites.net/login
      - [ ] login for their session
      - [ ] SUS likert scale

### Resources/Instructions
Likert Scale
[Passwords in this sheet](https://docs.google.com/spreadsheets/d/12gRid6DQ_7fK5-sNUM2L7L5mY4wYC52Pi70A60eDqVI/edit#gid=0)
[Folder for PDFs](https://drive.google.com/drive/u/1/folders/1jWRsDzj6y_RsDujJMRn728Rgd8kSaGHl)

[Final Survey Results](https://docs.google.com/spreadsheets/d/14hVD2om7ET7dwhTvbi1hoXoupjllyNDcCXvqZpb3WEQ/edit?usp=sharing)

**Comment by anamsha** [comment]
Link to folder with all projects: https://drive.google.com/drive/folders/1jWRsDzj6y_RsDujJMRn728Rgd8kSaGHl?usp=sharing

Table with logins/passwords: https://docs.google.com/spreadsheets/d/12gRid6DQ_7fK5-sNUM2L7L5mY4wYC52Pi70A60eDqVI/edit#gid=0

Ease of Use scale:
1 - Very Easy
2 - Easy
3 - Neutral
4 - Difficult
5 - Very difficult


SUS Score
1 - Strongly agree
2 - Agree
3 - Neutral
4 - Disagree
5 - Strongly disagree

**Comment by anamsha** [comment]
-[X] Make PDFs for all of the test cases - https://drive.google.com/drive/folders/1jWRsDzj6y_RsDujJMRn728Rgd8kSaGHl?usp=sharing
- [X] Make unique user/passes for each interview (30 to start) https://docs.google.com/spreadsheets/d/12gRid6DQ_7fK5-sNUM2L7L5mY4wYC52Pi70A60eDqVI/edit#gid=0

Both items are complete!

**Comment by KPHowley** [comment]
@ExperimentsInHonesty @kevinshih613  Link to Excel Sheet: [Final Survey Results](https://docs.google.com/spreadsheets/d/14hVD2om7ET7dwhTvbi1hoXoupjllyNDcCXvqZpb3WEQ/edit?usp=sharing)

**Comment by VJ1285** [comment]
@ExperimentsInHonesty - Were you looking something like the below. 
https://sites.google.com/view/latdmuserresearch-beatrice/resources

**Comment by VJ1285** [comment]
@ExperimentsInHonesty - Did you get a chance to review the landing page?
https://sites.google.com/view/latdmuserresearch-beatrice/home

**Comment by VJ1285** [comment]
made some updates to the landing page. @anamsha We need a single pdf with all the test cases.
https://sites.google.com/view/landing-pg-user-research-bf/resources
