### ISSUE TITLE
Create Logo Drafts

### ISSUE THREAD

**Issue by Rankazze** [hackforla/tdm-calculator#8]
### Overview
Client Rosemary has informed us that we can propose logo designs (if compliant with LADOT style guide) for the TDM-Calculator tool.

### Action Items
Review Style Guide.
Ideate logo designs (3).
Review with team for input.
Revise logo.
Pitch to client.

### Resources/Instructions
[LADOT Style Guide](https://drive.google.com/drive/folders/19rqv650kLS8ERpxcDxpqN3bcoAl_uaJt)

**Comment by dreams0ng** [comment]
Round one selects
![Screen Shot 2019-07-24 at 12 34 19 PM](https://user-images.githubusercontent.com/22779768/61822833-64c6bf80-ae0f-11e9-80ab-fc9ff96fc096.png)

**Comment by dreams0ng** [comment]
![Calc-Icon](https://user-images.githubusercontent.com/22779768/64220359-f2b9af80-ce7d-11e9-8a08-b8fc86015bd8.png)

**Comment by dreams0ng** [comment]
![Calc-Icon](https://user-images.githubusercontent.com/22779768/64220369-fd744480-ce7d-11e9-8a82-0ea098fe49e6.png)
After design research including heat mapping, memory endurance testing, top-mind emotional responses, etc. this is the icon to we will present to RM to be on the LADOT website to re-direct to our TDM calculator

**Comment by dreams0ng** [comment]
![R2](https://user-images.githubusercontent.com/22779768/65555165-9f68d900-dee0-11e9-9547-056c98f9ccaa.png)
Logo drafts round 2

**Comment by dreams0ng** [comment]
<img width="364" alt="Asset 123" src="https://user-images.githubusercontent.com/22779768/80445987-6f484500-88ca-11ea-8af3-50266ef0fbda.png">
<img width="364" alt="Asset 124" src="https://user-images.githubusercontent.com/22779768/80445990-72dbcc00-88ca-11ea-8fba-9ead344c212b.png">

**Comment by dreams0ng** [comment]
CHANGES
+new logo design
+matched color scheme
+color and grayscale versions shown

MOCKUPS
![TDM_Logo](https://user-images.githubusercontent.com/22779768/92637755-26e45f00-f28e-11ea-881a-411af0db821d.png)

LINKS
n/a

**Comment by ExperimentsInHonesty** [comment]
we decided not to
