### ISSUE TITLE
Change spc to Spaces in Wizard

### ISSUE THREAD

**Issue by KPHowley** [hackforla/tdm-calculator#800]
### Overview
There are several places where spcs is displayed on the wizard, and we should have this changed to "Spaces"

### Action Items

- [ ] Update "spcs" to "spaces" on calculation/2
- [ ] Update "spcs" to "spaces" on calculation/3 
- [ ] Update "spcs" to "spaces" on calculation/5 if necessary

**Comment by Jonathanko52** [comment]
![image](https://user-images.githubusercontent.com/30099154/114807799-e422c200-9d5b-11eb-8f86-8d686c118070.png)
![image](https://user-images.githubusercontent.com/30099154/114807893-159b8d80-9d5c-11eb-96cb-5e5aa6285df0.png)

Changes implemented in the commit, but additional characters throw the text out of alignment. May want to reconsider this issue.
