### ISSUE TITLE
Create push script for developers

### ISSUE THREAD

**Issue by nclairesays** [hackforla/tdm-calculator#806]
### Overview
Create Push script for developers to run before they make a push so that tests are run before making a PR. 

### Action Items

- [x] Create commands that will start up the backend and frontend 
- [x] Fix tests so that they run as part of the script
- [x] Skip any failing tests

**Comment by nclairesays** [comment]
I added a comment on PR #864: 
> I went ahead and merged this without having someone review because it doesn't affect developers' ability to start up servers as they have been doing. However, because cypress tests have been improved, I wanted to make sure they are available on the develop branch. I will go over with other developers during a meeting on how to use the scripts, as well as add documentation when I get the chance.

Will have John or Fang review the code when John is back or when Fang has proper access to our Github

**Comment by KPHowley** [comment]
hey @entrotech or @fyliu - can you review this or let me know if you already have?

**Comment by nclairesays** [comment]
Just FYI, I can write up some docs for this tonight before you officially review.
