### ISSUE TITLE
Set up Otter.AI and integrate to Zoom Account. 

### ISSUE THREAD

**Issue by KPHowley** [hackforla/tdm-calculator#807]
### Overview

Set up Otter.AI and integrate to Zoom Account. 

### Action Items

- [x] Set up Otter.AI and 
- [x] integrate to Zoom Account. 
- [x] Document for future users.

**Comment by jarmitageux** [comment]
In Tool Set Up [https://github.com/hackforla/tdm-calculator/wiki/(Pilot-Page)-Usability-Testing] looks like considering renewal of Otter.ai for testing. 

Could we look at Dovetail [https://dovetailapp.com/] as alternate tool option - it has been recommended to me for quickly grabbing video clips, voice transcription with in-line theming could save tons of time, etc. Could we check cost/features compared to Otter.ai tool?
