### ISSUE TITLE
Adjust points assigned to four TDM Strategies and provide new point drop down for Mobility Investment: Access Improvements

### ISSUE THREAD

**Issue by Dsomers74** [hackforla/tdm-calculator#826]
### Overview
Adjust points assigned to four TDM Strategies as listed below. A new point drop down for Mobility Investment: Access Improvements will need to be added with associated discrete point values (this will replace the manual entry for this TDM Strategy) 

### Action Items

1. **Mobility Investment: Access Improvements**
Adjust from 5 - 10 point range to specifically define discrete values in a new drop down option as follows (replace the manual entry):

- 4 points for improvements to 25 percent of ¼ mile walkshed or commensurate value
- 6 points for improvements to 50 percent of ¼ mile walkshed or commensurate value
- 8  points for improvements to 75 percent of ¼ mile walkshed or commensurate value
- 10 points for 100 percent of improvements to ¼ mile walkshed or commensurate value

2.  **Mobility Investment: Mobility Management**
Adjust points as follows:

- Change from 4 to 2 points for $50,000 
- Change from 8 to 4 points for $200,000 
- Change from 12 to 6 points for $500,000 

3. **Parking: Cash Out**
- Change points from 8 to 4 points

4. **Parking: Reduced Parking Supply**
- Change from 1 to 2 points - reduces 25% of the parking spaces available relative to the  parking baseline.
- Change from 2 to 4 points  -  reduces 50% of the parking spaces available relative to the  parking baseline.
- Change from 3 to 8 points - reduces 75% of the parking spaces available relative to the  parking baseline.
- Change from 4 to 12 points  - reduces 100% of the parking spaces available relative to the  parking baseline.  

### Resources/Instructions
[This is the google doc](https://docs.google.com/document/d/1pK9W6Wjeddjbla29l3rsA8F41SpIV8X1pe9eg-W3b7c/edit#) that specifies the needed adjustments

@entrotech @KPHowley

**Comment by KPHowley** [comment]
@entrotech  this is all working as specified, but can we also  add ">" before al of the percentage values in the Transit Access: Transit Passes  strategy..?

**Comment by Dsomers74** [comment]
@entrotech the TDM Calculator is not adding/displaying points when the Reduced Parking Supply Strategy is selected.

**Comment by Dsomers74** [comment]
@entrotech the TDM Calculator is also not displaying earned points for Transit Access: Transit Passes. I created new [issue #848](https://github.com/hackforla/tdm-calculator/issues/848)
