### ISSUE TITLE
Revise drop down value of the Affordable Housing Level: Affordable Housing TDM Strategy

### ISSUE THREAD

**Issue by Dsomers74** [hackforla/tdm-calculator#827]
### Overview
Revise drop down value of the Affordable Housing Level: Affordable Housing TDM Strategy to specify the minimum point range is assigned to projects that achieve the 20% density bonus value (formerly 35%). 

### Action Items
In the drop down menu for Affordable Housing Level, revise the first option (after N/A) from ‘35% of State Density Bonus’ to ‘20% of State Density Bonus’

### Resources/Instructions
[This is the google doc](https://docs.google.com/document/d/1pK9W6Wjeddjbla29l3rsA8F41SpIV8X1pe9eg-W3b7c/edit#) that specifies the needed adjustments

@entrotech @KPHowley

**Comment by KPHowley** [comment]
verified this is working
