### ISSUE TITLE
Revise Applicable Land Uses that are eligible for TDM Strategies

### ISSUE THREAD

**Issue by Dsomers74** [hackforla/tdm-calculator#828]
### Overview
Revise Applicable Land Uses that are eligible for TDM Strategies for those listed below:

### Action Items

- **Child Care: On-site Child Care** - remove as an eligible TDM strategy for **Residential** 

- **Parking: Pricing and Unbundling Parking** - Add as an TDM eligible strategy to **Employment/Office** and **Warehousing** uses 

- **Transit Access: Neighborhood Shuttles/Microtransit Service** - add as an eligible TDM strategy to Retail 

### Resources/Instructions
[This is the google doc](https://docs.google.com/document/d/1pK9W6Wjeddjbla29l3rsA8F41SpIV8X1pe9eg-W3b7c/edit#) that specifies the needed adjustments. I also updated the [Strategies List and Applicable Land Uses](https://docs.google.com/spreadsheets/d/1_VjRefk_7ch-eqIHK_gHIUXwcTYtvM0FO07K7gaqKGg/edit#gid=542599558) to reflect this revised alignment. 

@entrotech @KPHowley

**Comment by KPHowley** [comment]
verified this is working as intended
