### ISSUE TITLE
New mutually exclusive rule for Parking TDM Strategies

### ISSUE THREAD

**Issue by Dsomers74** [hackforla/tdm-calculator#829]
### Dependency
**Ice Box - Post MVP**
- [x] 2021-11-30 Currently holding this in icebox, per David, this will get addressed again after we have received the changes before it goes to planning commission.
- [x] TDM Calculator team will revisit this issue after all other issues in prioritized backlog have a milestone

### Overview
We need a new mutually exclusive rule for the Parking TDM Strategies where parking Cash-Out and priced parking strategies are not applicable where there is no parking provided on-site. 

### Action Items
Restrict both **Pricing/Unbundling** and **Cash Out** Strategies when "Reduce 100% of Space Available" drop down option is selected for **Reduced Parking Supply**

### Resources/Instructions
This is [the google doc](https://docs.google.com/document/d/1pK9W6Wjeddjbla29l3rsA8F41SpIV8X1pe9eg-W3b7c/edit#) that specifies the needed adjustments.

@entrotech  @KPHowley

**Comment by KPHowley** [comment]
reviewed and verified this is working as intended

**Comment by entrotech** [comment]
There is a bug where if you:

- select Pricing/Unbundling and/or Cash-out strategy, then
- set Reduced Parking Suppy to 100%,
- the Pricing/Unbundling and Cash-Out options aredisabled, but should also be reset to their default choice and have their earned points zeroed out.
The disabling is working, but the points for the two disabled options are not zeroed out and set ot their default values.

**Comment by Dsomers74** [comment]
We need to research this rule more before we push out. Could you restore the previous function where both parking strategies can be selected with 100% reduced parking? Sorry for the redirection. We can revisit this after the code freeze.

**Comment by entrotech** [comment]
I rolled this back in the development environment.

**Comment by ExperimentsInHonesty** [comment]
Currently holding this in icebox, per David, this will get addressed again after we have received the changes before it goes to planning commission.

**Comment by ExperimentsInHonesty** [comment]
What they cannot select if they have indicated 0 parking
HOV Parking
Pricing Unbundling
Cash Out Parking
Public Parking

**Comment by ExperimentsInHonesty** [comment]
This has been confirmed by stakeholder and is ready for development

**Comment by Biuwa** [comment]
- #1434 is the dev issue to implement the changes/corrections
