### ISSUE TITLE
Revise the TDM Strategies that are included in the School Package 

### ISSUE THREAD

**Issue by Dsomers74** [hackforla/tdm-calculator#830]
### Overview
Revise the TDM Strategies that are included in the School Package from the Employee Package currently in the Calculator to one that includes the TDM strategies below:

### Action Items

Include only these TDM Strategies in a School Package that is separate from the Employee Package: 

- **Bicycle Facilities: Bicycle Parking**
- **Information: Encouragement Program** - select the Voluntary Travel Behavior Change Program option from the menu
- **High-Occupancy Vehicles: HOV Program**
- **Information: School Safety Campaign**

- [ ] Add checkbox for school package on calculator

### Resources/Instructions
The changes are reflected in the [google doc](https://docs.google.com/document/d/1pK9W6Wjeddjbla29l3rsA8F41SpIV8X1pe9eg-W3b7c/edit#).

@entrotech  @KPHowley

**Comment by Dsomers74** [comment]
@KPHowley Note I updated this Action item to revise the Strategies to be selected for in the School Package.

**Comment by KPHowley** [comment]
@Dsomers74 - We should discuss this today-  this issuet is a bit of a heavier lift than the others!

**Comment by seenaiype** [comment]
Discussed with LADOT (09/28)

1. School package needed (school packages are always level 1) Need to figure the details around school bonus package
2. Can school be combined with residential and/or employment packages? - based on history only 3 school / year and not mixed uses
3. Confirm if we need Employment and residential packages? edge cases

to regroup

**Comment by jackrinjames** [comment]
Discussed with LADOT (11/2)

- Explanation not exactly necessary, someone developing a school is unlikely to use TDM calculator to see how it applies to them.
- If such a rare case comes up, they would likely just work with Planning/LADOT to figure out the program guidelines
- Will still include school package checkbox to have as an option, and explanation of school package is not a priority

**Comment by Dsomers74** [comment]
Replace the combined 'Employment & Residential Packages' with 'School Package' with strategies as [defined](https://docs.google.com/document/d/1pK9W6Wjeddjbla29l3rsA8F41SpIV8X1pe9eg-W3b7c/edit#):

- **Bicycle Facilities:** Bicycle Parking
- **Information:** Encouragement Program - select the Voluntary Travel Behavior Change Program option from the menu
- **High-Occupancy Vehicles:** HOV Program
- **Information:** School Safety Campaign
