### ISSUE TITLE
Update several Tooltips on Strategies page

### ISSUE THREAD

**Issue by KPHowley** [hackforla/tdm-calculator#832]
### Overview

The wording on several of the tool tips for the TDM Strategies have been updated 

### Action Items

- [x] Update Affordable Housing Tool tip
- [x] Update Voluntary Travel Behavior Change Program Tool tip
- [x] Update Mobility Investment: Access Improvements Tool tip
- [x] Update Parking: Parking Cash Out Tool tip
- [x] Update Public Parking Tool tip
- [x] Change Shared Mobility header to Shared Micro-Mobility
- [x] Update Shared Micro-Mobility: Existing Provider Tool tip
- [x] Update Shared Micro-Mobility: Local Shared Fleet Tool tip
- [x] Update Transit Access - Improve Transit ServiceTool tip

### Resources/Instructions

**Affordable Housing** 

< 20% of State Density Bonus: Projects that do not meet any of the below criteria

20% of State Density Bonus: Projects that receive 20% of California’s Density Bonus and provide a minimum of:
10%  Low Income; or
5% Very Low Income.

_The rest of the Affordable Housing Tool Tip remains the same_

**Information: Encouragement program - Voluntary Travel Behavior Change Program** 

1. _same_

2. Travel Behavior Change Program: A multi-faceted program involving two-way communication campaigns and travel feedback that actively engages participants to target individual attitudes, goals, and travel behaviors to alter their travel choices and habits. Program must include the distribution of a one Metro TAP card pre-loaded with a trip, to each employee or residential unit. Selection of this strategy requires a coordinator to manage the program, and ensure communication is available to all regular occupants of a site with a special focus on new occupants and/or employees.

3. _same_

**Mobility Investment: Access Improvements**
Install or make contributions to new or improved facilities in the public right-of-way (PROW) that support greater access to the project by people that bicycle, walk, and take transit. All PROW investment shall be consistent with the Mobility Plan 2035, and may include, but are not limited to, curb extensions, leading pedestrian intervals, controlled mid-block crosswalks, pedestrian refuge islands, protected bicycle lanes, bike boxes, exclusive bicycle signal phases, street trees, etc. LADOT shall be consulted to verify the opportunity and feasibility of access improvements near the project site.. Point value relative to improvement and location, and determined in coordination with LADOT staff.

**Parking: Parking Cash Out**
Implement a “cash out” program, where all full or part-time employees who do not use a parking space are paid the value of the space instead in time increments that the parking is leased. The value of a space shall be the leased value, if leased, and shall be the market value of a parking space if owned by the property owner.

**Public Parking**
Provide public access to the property's parking. Must be coupled with on-demand parking availability publicized through public signage and/or approved mobile application. This strategy is especially encouraged for properties that provide parking supply at rates above L.A.M.C. or a Specific Plan requirements. To earn points for this strategy, a project must provide the number of parking spaces available for public use. That supply must be, at a minimum, 25% of the total parking supply rounded up to the next whole number. 

**Shared Micro-Mobility: Existing Provider** 
Partner with a shared micro-mobility company to provide discounted membership fees for building occupants (e.g. residents and employees) Make shared micro-mobility fleet devices accessible for easy identification and use. 

**Shared Micro-Mobility: Local Shared Fleet** 
Purchase and operate a shared micro-mobility fleet that is available on-site for use or rent for building occupants (e.g. residents and employees). The fleet size shall be determined to ensure a shared device is available 90 percent of the time it is requested. 

**Transit Access - Improve Transit Service**
Provide funding to a local transit provider for improvements that improve service quality (reduce headways, etc.) at transit stops within ¼ mile radius of the project site. Funds could also contribute to an existing shuttle or microtransit service (e.g. DASH) in consultation with LADOT if this option is available near the project site.

**Comment by KPHowley** [comment]
Hey @entrotech  - I just double checked and i think we just need to update the first part of Affordable housing.  This should be under the text- "20% 35% of State Density Bonus: Projects that do not meet any of the below criteria::

"
20% of State Density Bonus: Projects that receive 20% of California’s Density Bonus and provide a minimum of:
10% Low Income; or
5% Very Low Income.
"
see screenshot!

![Screen Shot 2021-05-26 at 5 38 52 PM](https://user-images.githubusercontent.com/49739276/119748238-4ede1780-be49-11eb-8f72-7bf22944e9c6.png)

**Comment by entrotech** [comment]
Here's what it looks like now. I don't see the difference between this and the "screen shot" in your above comment - assuming strike-through means delete and underline means add.

![image](https://user-images.githubusercontent.com/9939032/119754062-be0d3900-be54-11eb-99ba-b27de592e06a.png)
