### ISSUE TITLE
Add " * designates required fields" to page 1

### ISSUE THREAD

**Issue by KPHowley** [hackforla/tdm-calculator#835]
### Overview

We need to be more explicit on required fields and to add " * designates required fields" to calculation/1

### Action Items

- [x] " * designates required fields" to calculation/1 
- [x] Locate centered above buttons on bottom of page

**Comment by jahpe777** [comment]
#835 Added " * designates required fields" to page 1

<img width="1440" alt="Screen Shot 2021-05-29 at 8 03 54 PM" src="https://user-images.githubusercontent.com/40730303/120090657-0c227680-c0b9-11eb-9517-1bbda0162707.png">
