### ISSUE TITLE
The TDM Calculator is non-responsive for two TDM strategies: Transit Passes and Reduced Parking Supply

### ISSUE THREAD

**Issue by Dsomers74** [hackforla/tdm-calculator#848]
### Overview
The TDM Calculator is non-responsive for two TDM strategies: Transit Passes and Reduced Parking Supply

### Action Items
On the [Transportation Demand Strategies page](https://tdm.azurewebsites.net/calculation/5), the two TDM strategies, Transit Passes and Reduced Parking Supply need to display earned points when the respective drop down option is selected. 

@entrotech @KPHowley

**Comment by KPHowley** [comment]
Hi @Dsomers74 

We are looking over this now and will try to get his fixed as soon as possible!

@entrotech @nclairesays

**Comment by nclairesays** [comment]
I've addressed this issue. Please see PR #849.

**Comment by Dsomers74** [comment]
Thanks Team!

David
