### ISSUE TITLE
Add User defined strategy description on Summary Page

### ISSUE THREAD

**Issue by KPHowley** [hackforla/tdm-calculator#850]
### Overview

We need to add a new section on the final summary page that displays the user's description of the User defined strategy. 

### Action Items

- [ ] Add a line called "User Defined Strategy Description:" to the final summary page
- [ ] Display the description in the column under the other project information or inputs
- [ ] Make so this is formatted correctly for long blocks of text 

### Resources/Instructions
https://www.figma.com/file/nD9QK56Mzq7xNSaSUoeGx0/TDM-Calculator?node-id=1744%3A3531

**Comment by Jonathanko52** [comment]
-Move User Defined Strategy description under TDM measures selected header instead of its own header.

**Comment by Shaeeka** [comment]
[Figma file](https://www.figma.com/file/nD9QK56Mzq7xNSaSUoeGx0/TDM-Calculator?node-id=1744%3A3531), please refer to the Summary page Final Draft

-  Updated the color to match the style guide
-  Fixed the spacing of the Project Detail section

![image](https://user-images.githubusercontent.com/88021166/131802606-71e423c3-97db-4eed-b56a-1634fb8e2669.png)

**Comment by seenaiype** [comment]
@Jonathanko52 , as discussed, this ticket is for the userDefined Strategy piece on the summary page.

**Comment by Shaeeka** [comment]
![image](https://user-images.githubusercontent.com/88021166/132611841-0879b82e-1dab-401d-a134-fbb4b5afa72d.png)

**Comment by Jonathanko52** [comment]
1. Move summary text from center align to left align.
2. Change title to "User-Defined Strategy Details."
3. make spacing between 'User-Defined Strategy' and 'User-Defined Strategy Details' consistent with the others.
4. Remove the floating "5" That appears in the User-Defined Strategy row, between the two columns.

**Comment by seenaiype** [comment]
Changes we talked about 

1. Update the header to "User Defined Strategy Details"
2. Remove the extra points that is showing up on the user defined strategy row
3. make the spacing consistent
4. Left allign the user defined strategy details text.

Please, check [Figma file](https://www.figma.com/file/nD9QK56Mzq7xNSaSUoeGx0/TDM-Calculator?node-id=1744%3A3531), please refer to the Summary page Final Draft, for anything i might have missed.

**Comment by Shaeeka** [comment]
Changed the border's design (corners to 0, stroke to 1, shadow to inside) to match it with the original Earned and Target Point Border
![image](https://user-images.githubusercontent.com/88021166/132869421-8d1495c2-13ad-4f36-b903-3dbcd5205e91.png)

**Comment by seenaiype** [comment]
Looks good. Can we merge and deploy into Dev environment, so we can see all the updates to this page together and demo it to LADOT on our tuesday meeting.

CC: @fyliu

**Comment by fyliu** [comment]
@seenaiype I made the lastest updates to the UI. Just need visual and technical reviews and it will automatically get pushed to dev

**Comment by seenaiype** [comment]
@Jonathanko52 , i see most of the changes around USerdefiened strategies in Dev now. But, it still shows me the text center alligned, can you check on that. 

![image](https://user-images.githubusercontent.com/20568596/132953746-5a6f0f60-6687-46b6-bad1-68ceb481d176.png)

**Comment by Shaeeka** [comment]
Combining all the update requests in one comment
![image](https://user-images.githubusercontent.com/88021166/132957339-ea1790eb-4585-40a3-90ef-acb3680e99a4.png)

1. Move summary text from center align to left align.
2. Change title to "User-Defined Strategy Details:"-Add a colon. 
3. Make spacing between 'User-Defined Strategy' and 'User-Defined Strategy Details' consistent with the others.
4. Chang the border's design (corners to 0, stroke to 1, shadow to inside) to match it with the Earned and Target Point Border on the top.
5. Remove the floating "5" That appears in the User-Defined Strategy row, between the two columns.

Refer to the final draft on the [Figma file ](https://www.figma.com/file/nD9QK56Mzq7xNSaSUoeGx0/TDM-Calculator?node-id=4027%3A12775)

**Comment by ExperimentsInHonesty** [comment]
Bonnie 
- Suggest limiting the colors on this page.  The red color could be the orange color if we did an outline or the box that the number is in could be solid orange and the text could be dark blue

David
- change version number to Alternative # 
- Case to be City Planning Case #
- add LADOT Case # 
- add Project Description under Project Details header
- Move the address to the smaller font (similar to PARCEL #(AIN))
- everse the order of Parking Provided and Baseline Parking

Emily 
- Limit the number of colors on the page (through outlines with the colors, keeping the text in the dark blue).
