### ISSUE TITLE
Investigate best practices for Tooltips 

### ISSUE THREAD

**Issue by KPHowley** [hackforla/tdm-calculator#851]
### Overview
Investigate best practices for Tooltips 

### Action Items

- [x] research use of tool tips on other websites including government sites
- [x] come up with proposals/ recommendations on what should be used for our website. 

Make determinations to guide our use of tool tips addressing the following issues/questions
- [ ] Should tooltips be displayed on hover
- [ ] Should tooltips all have "?" icons
- [ ] Should tools tips be static in one spot
- [ ] Should we time out tool tips?
- [ ] Do we want a legend or information describing them?

**Comment by mttran234** [comment]
I made a slide deck of my research to discuss the tooltip issue: https://docs.google.com/presentation/d/17Vm5pVXfyU6-Mmx0KtdSPWGuVBcp7VUzx6L2oJGtZqs/edit#slide=id.p
