### ISSUE TITLE
Coding error: the TDM Levels associated with hotel guest rooms needs to be adjusted

### ISSUE THREAD

**Issue by Dsomers74** [hackforla/tdm-calculator#855]
### Overview
There is a coding error: the TDM Levels associated with hotel guest rooms where the guest rooms are not correctly aligned with TDM Project Levels

### Action Items
Align guest rooms and TDM Project Levels as follows for hotel/motels under Special Uses:

- hotel/motel with 0 - 49 guest rooms = TDM Project Level 0
- hotel/motel with 50 - 99 guest rooms = TDM Project Level 1
- hotel/motel with 100 - 249 guest rooms = TDM Project Level 2
- hotel/motel with 250 or more guest rooms  = TDM Project Level 3

### Resources/Instructions
This is specific in the [TDM Program Description Table 1](https://docs.google.com/document/d/185LUz5VI0VoBp4kDx0KSZ_pI1zzXfgdB0PlsIgJvxx8/edit) 

@entrotech @KPHowley

**Comment by VJ1285** [comment]
@Dsomers74 - what happens if the hotel/motel has less than 50 guest rooms? Would that also qualify for Project Level 1?

**Comment by Dsomers74** [comment]
@VJ1285 TDM Project Level 1 would be 50 - 99 guest rooms. Hotels with guest rooms under 50 (0-49) would not apply, Project Level = 0.

**Comment by VJ1285** [comment]
@Dsomers74 sounds good.
