### ISSUE TITLE
 Make Priced Parking an eligible TDM Strategy for Hotel Uses

### ISSUE THREAD

**Issue by Dsomers74** [hackforla/tdm-calculator#856]
### Overview

Price parking has been determined to be an eligible strategy for Hotel, and we need to update this. 

### Tasks

- [ ] Change Pricing/unbundling to be visible and selectable on calcualtion'4 

### Reference

Orginal comment from David: 

 The team is considering making Priced Parking an eligible TDM Strategy for Hotel Uses.

We still need to discuss internally, though we may provide updated direction to include Priced Parking as an eligible TDM Strategy for Hotel Uses. 

The issue has not been thoroughly research, though there is not an apparent reason why parking ca. not be priced for hotel patrons independent of their room fee. 

Refer to the [Strategies List and Applicable Land Uses Matrix](https://docs.google.com/spreadsheets/d/1_VjRefk_7ch-eqIHK_gHIUXwcTYtvM0FO07K7gaqKGg/edit#gid=542599558) for updates.

**Comment by KPHowley** [comment]
This should be discussed with LADOT to determine if this should be closed or we are still waiting on a decision.

**Comment by ExperimentsInHonesty** [comment]
Priced parking is an eligible strategy for for Hotel Uses.
