### ISSUE TITLE
Child Care and School Safety Campaign issues

### ISSUE THREAD

**Issue by awikstrom-ladot** [hackforla/tdm-calculator#858]
### Overview

The Child Care strategy is greyed out on all uses, even though it is applicable to all uses except housing. 
School Safety Campaign is select-able under multiple uses, and should only be select-able with schools

### Action Items

- [x] Allow Child Care strategy with all projects, except for housing
- [x]  Exclude School Safety Campaign strategy from Employment, Retail, and Housing uses.

**Comment by nclairesays** [comment]
@awikstrom-ladot your original message says 
> School Safety Campaign ...should only be select-able with schools

The action item says: 
> Exclude School Safety Campaign strategy from Employment, Retail, and Housing uses.

Does this mean that the other types like, Hotel, warehouse, medical, other, and major  can select School Safety Campaign? Or is it literally only checkboxes under "Schools" that can choose that measure?

**Comment by awikstrom-ladot** [comment]
This means that only schools can select School Safety Campaign as a strategy. Unless school is selected when an applicant is inputting their project, this measure should be greyed out
