### ISSUE TITLE
Copy Project error

### ISSUE THREAD

**Issue by awikstrom-ladot** [hackforla/tdm-calculator#859]
### Overview

Copy Project function in the Projects tab is not actually copying projects. When clicking on the copied project, it results in a blank project with none of the original project's information. 

### Action Items

- [ ] Identify the exact source of the issue 
- [ ] Fix funstionality

### Resources/Instructions

@entrotech @KPHowley

**Comment by Akheal** [comment]
@KPHowley do we need to list this on the issue tracker, this seems to be a bug rather than a feature/enhancement.

**Comment by KPHowley** [comment]
@nclairesays or @entrotech  - Just verifying - is this just implemented on the Dev site, or on the live/UAT site as well?

**Comment by nclairesays** [comment]
@KPHowley just the dev site. We haven't done any releases in a while.
