### ISSUE TITLE
Fix bug due to Habitable Rooms tool tip logic

### ISSUE THREAD

**Issue by nclairesays** [hackforla/tdm-calculator#861]
Expected: 

- see tool tip icon for 3 habitable room rules
- able to go through full calculation flow

Actual:

- page 3 skips to page 5

Bug introduced due to #857

**Comment by seenaiype** [comment]
@nclairesays , I am trying to put an update for this bug on the presentation for LADOT. Can you provide me what was the original issue for this bug?
