### ISSUE TITLE
 Make "Proposed Ordinances and Initiatives"  a link in the about page 

### ISSUE THREAD

**Issue by VJ1285** [hackforla/tdm-calculator#865]
### Overview
One of the issues that were raised during usability testing was that users questioned the legitimacy of calculations.

### Action item

- [x] Make "Proposed Ordinances and Initiatives" as a separate bullet.
- [x] Add a hyperlink to - "Proposed Ordinances and Initiatives". The link should take the user to the "Draft TDM Program Guidelines (June 2021)"
- [x] Update TDM Program Guidelines link to the following URL:
https://planning.lacity.org/odocument/c3c9b320-4431-49ff-99d2-15b479c06074/Revised_DRAFT_TDMProgramGuidelines_June2022.pdf

### Resources
Link to "Draft TDM Program Guidelines (June 2021)" - https://planning.lacity.org/odocument/9fae920f-d618-4362-bd01-adb6abfbd80d/Draft_TDM_Program_Guidelines.pdf

![image](https://user-images.githubusercontent.com/70343417/126713752-d349a8b7-d0a1-40b5-b2a9-2e9ee5d96d5c.png)

**Comment by Dsomers74** [comment]
Here is our document links as they are reflected on the City Planning website.  

[Draft TDM Ordinance (June 2021)](https://planning.lacity.org/odocument/1dc924ce-b94a-403b-afe0-17ba33b3dbe1/Draft_TDM_Ordinance.pdf)
[Draft TDM Program Guidelines (June 2021)](https://planning.lacity.org/odocument/9fae920f-d618-4362-bd01-adb6abfbd80d/Draft_TDM_Program_Guidelines.pdf)

**Comment by jahpe777** [comment]
#865 Made "Proposed Ordinances and Initiatives" a link in the about page

**Comment by SMR9220** [comment]
<img width="1397" alt="about us link" src="https://user-images.githubusercontent.com/69442669/178385196-46b4fb76-343e-43f3-9d83-74710ffb3e7e.png">

The current TDM Program Guidelines link should be updated to the following URL:
https://planning.lacity.org/odocument/c3c9b320-4431-49ff-99d2-15b479c06074/Revised_DRAFT_TDMProgramGuidelines_June2022.pdf
The wording of the display text should not change, only the link it goes to.

**Comment by jahpe777** [comment]
Updated the “About Page” link for “Proposed Ordinances and Initiatives"
