### ISSUE TITLE
Change "Version #" to "Alternative #"

### ISSUE THREAD

**Issue by VJ1285** [hackforla/tdm-calculator#869]
### Overview
Based on the usability testing (row 8), users are unclear what "Version #" means. Let's change "Version #" to "Alternative #"  

### Action Items

- [x] Change Version # to Alternative #

### Resources/Instructions
https://docs.google.com/spreadsheets/d/1SEd8uPOwOmEMdsDR_pylZ2tiByopzPrmlqB5Y4Ka4xc/edit?usp=sharing

**Comment by VJ1285** [comment]
@Dsomers74 - Do we need to have a version # or is it something that we can take out?

**Comment by Dsomers74** [comment]
Hi Vivek, I am not sure what the Version X relates to. Is this in the TDM Calculator? If so, kindly take a screen shot and I can assess its use. 

Thanks.

**Comment by VJ1285** [comment]
@Dsomers74 see Image below.

![image](https://user-images.githubusercontent.com/70343417/126717427-6a76f14d-9e44-4c0b-94ac-c3b98a9024d1.png)

**Comment by Dsomers74** [comment]
oh yes, I think we used this for project alternatives, though I am not sure
it has a lot of value. It could be renamed to "Alternative #" since that is
a commonly understood term for real estate entitlement projects.

David

**Comment by VJ1285** [comment]
@Dsomers74 - Sounds good. Do we need to add any tool tip with it? For e.g. "This helps distinguish different alternatives/trials for the same project."

**Comment by Dsomers74** [comment]
Yes, how about: "This helps distinguish different alternatives/scenarios for the same project."

**Comment by fyliu** [comment]
@VJ1285 If this is settled and in the current sprint, can you assign it to me? I have 2 other tickets updating rule descriptions and this is just another quick change.

**Comment by VJ1285** [comment]
@Dsomers74 - Sounds good. I think "This helps distinguish different alternatives/scenarios for the same project." clearly conveys the function. We will change the Version # to Alternative # and have the above tooltip that you suggested.

**Comment by fyliu** [comment]
Progress: changed name and added tooltip
Not done: need to add ToolTipIcon to the item. This might be better put into a new bug, since there are other places with tooltips that are not displaying the icon.

**Comment by fyliu** [comment]
Since Vivek is adding the missing tool tip icon as a new ticket, I'm considering this done.

**Comment by ExperimentsInHonesty** [comment]
This issue can be marked as closed after visual review and the new issue being opened about tool tip icons that Fang is referencing.
