### ISSUE TITLE
Case or Planning Number Issues (Issue from Usability Testing)

### ISSUE THREAD

**Issue by VJ1285** [hackforla/tdm-calculator#870]
### Overview
Row 9 Users are unsure if they can proceed if they don't have case or planning numbers. 

### Ideas
On Page 1 add a horizontal line that divides required and optional information

### Resources/Instructions
https://docs.google.com/spreadsheets/d/1SEd8uPOwOmEMdsDR_pylZ2tiByopzPrmlqB5Y4Ka4xc/edit?usp=sharing

**Comment by KPHowley** [comment]
@VJ1285  - did we ever disuses this at a meeting or with LADOT? We added the wording "* designates required fields" at the bottom of the page after user testing which should clear this up.

**Comment by KPHowley** [comment]
closing this as *Designates required fields is meant to address this
