### ISSUE TITLE
Parking Spaces Required on Page 2

### ISSUE THREAD

**Issue by VJ1285** [hackforla/tdm-calculator#871]
**An issue for this already exists - #834** 

### Overview
Row 12 - Users thought that "Enter Parking Spaces req'd" was an input for all parking to be provided.

### Idea
Take out the parking information from Page 2 and move all the parking-related information to Page 3. 

### Resources/Instructions
https://docs.google.com/spreadsheets/d/1SEd8uPOwOmEMdsDR_pylZ2tiByopzPrmlqB5Y4Ka4xc/edit?usp=sharing

**Comment by ExperimentsInHonesty** [comment]
We met with David and Emily, and decided that we would hide the condo spaces until they indicated that they will be using condo units.  Same with the other items that are conditional on the pages

**Comment by KPHowley** [comment]
Closing this issue as an  **An issue for this already exists - #834**
