### ISSUE TITLE
# Habitable Rooms is unclear

### ISSUE THREAD

**Issue by VJ1285** [hackforla/tdm-calculator#872]
### Overview
Row 14 - Usuability testing found that user found ""# Habitable Rooms" is unclear. The use of numerical notation is confusing"

### Ideas
Replace "#" with "No." or "Number"

### Resources/Instructions
https://docs.google.com/spreadsheets/d/1SEd8uPOwOmEMdsDR_pylZ2tiByopzPrmlqB5Y4Ka4xc/edit?usp=sharing

**Comment by fyliu** [comment]
potential duplicate of #876
@VJ1285

**Comment by fyliu** [comment]
@VJ1285 this may be a duplicate of #876

**Comment by KPHowley** [comment]
@fyliu  - Thank you.

This is a duplicate issue of   #876. Closing.
