### ISSUE TITLE
Need to update sidebar & Success Toast

### ISSUE THREAD

**Issue by VJ1285** [hackforla/tdm-calculator#874]
### Overview
Need to update the sidebar (and change of states) and success toast such that they are readily identified by the user

### Action Items

_**Finished:** 
- [x] ~Need to add animation to the sidebar to attract users attention~
- [x] Summary of points below Earned Points help users see what they have selected.
Example
      25
      ----
      bike parking (2pt)
      wayfinding (1 pt)
      rideshare (2 pt)
Also see summary on last page of calculato
- [x] ~Not Run animation on page change.~
- [x] Fix crashing bug_

**Design updates as of 8/18**
- [ ] remove the pts under earned until they actual have earned them
- [ ] make sure Line breaks are spaced correctly on shopping cart
- [ ] Decide on what to do when too shopping cart items are longer than the available space  - scroll bar? 

**Front end issues to create once design is finalized:**
- [x] create issue to remove the pts under earned until they actual have earned them
- [ ] create issue to swap the current side bar numbers for the two circle design
- [ ] create issue toUpdate tool tip to display both "earned point" and "target point" descriptions. 
- [ ] create issue to add the shopping cart

**Final tasks **
- [ ] implement the above and push to UAT
- [ ] move the points/cart to right and then test with users both versions before pushing the right one to UAT.  If the left one wins, we will roll back the right version on dev.
- [ ] strikethrough dependency on issue #866 

### Resources/Instructions
https://docs.google.com/spreadsheets/d/1SEd8uPOwOmEMdsDR_pylZ2tiByopzPrmlqB5Y4Ka4xc/edit?usp=sharing

**Comment by ExperimentsInHonesty** [comment]
David said he was interested in having a list of items selected appear under the accruing points earned

**Comment by ExperimentsInHonesty** [comment]
@Jonathanko52 We have reduced scope on this issue until the usability comes back from adding the measures they have selected.  We are also going send it back to design so I am un assigning you for now.  You can pick this back up once design has come up with mock ups and the stakeholder has reviewed.

**Comment by seenaiype** [comment]
As discussed, we shall come up with 3 mockups 
1. Shopping cart on left and right pane - Shaeeka / Madison
2. 3. Different way to show the earned vs target points - Hope Shin

**Comment by shinhope** [comment]
Progress: finished and added to figma
![circle 1-12](https://user-images.githubusercontent.com/79497980/128258788-15568555-20c4-41a4-b335-fad217837c56.png)
![tracker 1-12](https://user-images.githubusercontent.com/79497980/128258799-5115369a-76c1-4178-a9f5-443c737f5e23.png)
![new sidebar](https://user-images.githubusercontent.com/79497980/128258813-7aebb0fb-e944-457f-a39f-ded1aded114e.png)

**Comment by salauds** [comment]
Option 2: Bottom Bar Variation by Madison- Located at Figma "New Sidebar- Aug 2021" page
![image](https://user-images.githubusercontent.com/88021166/128552452-627af448-95f2-4a63-9e2d-c1ffe651ee97.png)

**Comment by salauds** [comment]
Option 3a: Cart Style R. Sidebar by Shaeeka - Located at Figma "New Sidebar- Aug 2021" page

Features: 
1. Target bar to show if a user is meeting its target point.
2. Earned point highlighted in color green to draw attention of the user so they are aware
3. List of TDM measures that are selected by a user                
![image](https://user-images.githubusercontent.com/88021166/128553969-738baadf-bd69-4c14-81b9-b88bbef66a8a.png)

**Comment by salauds** [comment]
Option 3b: Cart Style L. Sidebar by Shaeeka - Located at Figma "New Sidebar- Aug 2021" page

Features:
1. Target bar to show if a user is meeting its target point.
2. List of TDM measures that are selected by a user

![image](https://user-images.githubusercontent.com/88021166/128556203-a81324bc-ec17-463b-a810-c0f042813cd9.png)

**Comment by salauds** [comment]
Option 3c: Cart Style R. Sidebar Version 2 by Shaeeka - Located at Figma "New Sidebar- Aug 2021" page

Features
- Same as Option 3b, side bar is moved to right. 

![image](https://user-images.githubusercontent.com/88021166/128557223-4f527ffb-6ef9-4e18-9095-20f881fc10dc.png)

**Comment by seenaiype** [comment]
@salauds , we discussed and would like to have the below three mockups

1. Left Pane with the existing Project and earned and target points with the shopping cart 
2. Left Pane with the existing Project level and earned and target points in the circle dial with the shopping cart. 
- To use the below dial 
![image](https://user-images.githubusercontent.com/20568596/128619100-75455f68-2138-45ba-9d00-b6aa8cb54c23.png)
- Update the dial to show Colors - red till 25% of the target achieved, orange from 25 to 75 %, yellow 75% to 90% and then green when target achieved. If the points go beyond, leave it as green , but increase the points shown.

3. show the Project , earned and target points on the right pane.

**Comment by Shaeeka** [comment]
Listing the 3 Mock ups for the Side Slidebars.
![image](https://user-images.githubusercontent.com/88021166/129122926-6d90bdfa-57fc-4788-8337-76b786c9057a.png)
Mock Up No. 1
![image](https://user-images.githubusercontent.com/88021166/129122989-501d6d3b-c11d-4d2e-a8d2-d3575ff2b886.png)
Mock Up No. 2
![image](https://user-images.githubusercontent.com/88021166/129123021-e7a4f68c-96d0-4d35-b4ba-39a21f505406.png)
Mock Up No. 3
![image](https://user-images.githubusercontent.com/88021166/129123063-d76c532f-d570-4721-b4f2-f815435e05e6.png)

**Comment by seenaiype** [comment]
@Shaeeka - we had a review with bonnie on the mockups. She really liked them.. couple of updates to be made before we present it to ladot

1. Try to update the cart with white background and blue text to stand out a little for mockup 1 and 2. 
2. For mockup 3, show the dial with target not achieved scenario like 15/25 points to show the transition
3. Since our team is split on the two designs for the dial. We would also like to get poll done with the ui/us community, let's do the mockup using usability hub free account and create 4 designs - circle or / for points and dial color to have start with grey or red. 

Let me know if any questions

**Comment by Shaeeka** [comment]
![image](https://user-images.githubusercontent.com/88021166/129661951-23e14ec1-2619-49d7-b782-f3c578e0a247.png)
![image](https://user-images.githubusercontent.com/88021166/129663006-06e62282-7832-4a83-900d-9c4ad5c6f10c.png)
![image](https://user-images.githubusercontent.com/88021166/129663048-d51f64f3-6e66-4c62-a1b2-b1b867ddf602.png)
![image](https://user-images.githubusercontent.com/88021166/129663074-edbe2ce2-421e-4e16-92fa-1cfb4b325e1c.png)

**Comment by ExperimentsInHonesty** [comment]
LADOT decisions made

1. remove the pts under earned until they actual have any
2. use the circle with the small circle for target
3. add the shopping cart
4. implement the above and push to UAT
5. move the points/cart to right and then test with users both versions before pushing the right one to UAT.  If the left one wins, we will roll back the right version on dev.

**Comment by seenaiype** [comment]
3 new issues to be created for developers

1. Removing the points (pts ) from earned column , when there is no points gained
2. Issues with two circles for earned and target and add the shopping cart (confirm the strategies with multiple choices to show properly) 
3. Issue with the two circles for earned and target and add the shopping cart (confirm the strategies with multiple choices to show properly) on the right pane (leave this in dev environment) for usability testing.

**Comment by seenaiype** [comment]
Questions 

1. Do we need the shopping cart on all the pages or only on page 4 (strategies)?
2. How to handle scroll bar for shopping cart as it grows?
3. Confirm the order of which items are added to the shopping cart? 
3. Do we need the success toast or only the dial is enough?2.

**Comment by Shaeeka** [comment]
Updated the cart background (in the screen shot the cart texts look blurry but in the actual file it looks clear) and including the final designs for the Dev team.
**Left Side Bar**
![image](https://user-images.githubusercontent.com/88021166/130021502-2a9708cf-c735-4e4c-9b0c-cf458afed921.png)
**Right Side Bar**
![image](https://user-images.githubusercontent.com/88021166/130021643-91eb1a23-7b84-4b35-b437-9a1a041fbab8.png)
**Chosen Donut Chart**
![image](https://user-images.githubusercontent.com/88021166/130021719-a7ba0692-94e4-42ac-b61f-05e4578b4b94.png)

**Comment by entrotech** [comment]
Created Issue #908 for developers to create the "Donut Chart", i.e., Earned Points progress control.

**Comment by seenaiype** [comment]
Couple of updates

- [ ] The initial state for the dial, as the page loads for a new project. 
- [ ] Let's put a small description on each of the stage for explanation
- [ ] the words to be bigger font - earnings and target
- [ ] For the points cart - The cart to have plain white background, the transparency is hard to read
- [ ] Once ready, update Figma to have a green line, for the dev team to pickup

**Comment by seenaiype** [comment]
Created - [909 ](https://github.com/hackforla/tdm-calculator/issues/909) for removing pts from earned section

**Comment by Shaeeka** [comment]
![image](https://user-images.githubusercontent.com/88021166/130580959-6db6f48e-035b-4af4-bba5-b3338f9b3e47.png)
