### ISSUE TITLE
Simplify Page 4 

### ISSUE THREAD

**Issue by VJ1285** [hackforla/tdm-calculator#878]
### DEPENDENCY 
- #957 

### Overview
Need to simplify age 4 as Users are overwhelmed and intimated by the information presented on this page.

### Resources/Instructions
https://docs.google.com/spreadsheets/d/1SEd8uPOwOmEMdsDR_pylZ2tiByopzPrmlqB5Y4Ka4xc/edit?usp=sharing

**Comment by KPHowley** [comment]
This needs to be fleshed out into a more complete issue.

I'm  adding a dependecy to finish tool tip issue first as well #957

**Comment by ExperimentsInHonesty** [comment]
This came out of UXR 01 and has been addressed by several issues and new research was done UXR 02 that replaces this general item
