### ISSUE TITLE
Mixed use points to be determined automatically

### ISSUE THREAD

**Issue by VJ1285** [hackforla/tdm-calculator#879]
### Overview
We need to determine the points for mixed-use automatically 

### Action Items
Based on the user input the TDM points associated with mixed-use should be calculated automatically. 

### Resources/Instructions
https://docs.google.com/spreadsheets/d/1SEd8uPOwOmEMdsDR_pylZ2tiByopzPrmlqB5Y4Ka4xc/edit?usp=sharing

**Comment by ExperimentsInHonesty** [comment]
Can't automate the mixed use strategy because we don't ask for sq ft of residential, so hard to if its 85%

**Comment by jackrinjames** [comment]
Discussed with LADOT (11/2)

- Will be removed per Dave
