### ISSUE TITLE
Delete the left "Sq Ft" from Page 2

### ISSUE THREAD

**Issue by VJ1285** [hackforla/tdm-calculator#881]
### Overview
Delete left "Sq Ft" from page 2 as its confusing users. 

### Action Items
Delete the left "Sq Ft" from page 2

### Resources/Instructions
https://docs.google.com/spreadsheets/d/1SEd8uPOwOmEMdsDR_pylZ2tiByopzPrmlqB5Y4Ka4xc/edit?usp=sharing

**Comment by ExperimentsInHonesty** [comment]
David agrees and says we can delete any other redundant info that is similar.
