### ISSUE TITLE
Add tool tip icon to AIN & Alternative #

### ISSUE THREAD

**Issue by VJ1285** [hackforla/tdm-calculator#886]
### Overview
Need to add tooltip icon to AIN & Alternative #/Version # on Page 1

### Action Items

- [ ] Add tool tip icon to AIN & Alternative # similar to Page 2

### Resources/Instructions
![image](https://user-images.githubusercontent.com/70343417/127749216-3276ef5b-f2fc-4107-97e2-75486fcb4f96.png)

**Comment by fyliu** [comment]
This is a quick change in ToolTipLabel.js

**Comment by seenaiype** [comment]
@fyliu , can you add a screenshot of the update that was made as part of this ticket. I am not able to find the update and getting confused between page 1 and Page2 :)

**Comment by fyliu** [comment]
@seenaiype #887 was adding the tooltips. This one is adding the icons that indicate there's tooltips for the items. I put the screenshot in the pull request. It's under "Linked pull requests" on the right side here.

**Comment by seenaiype** [comment]
Silly question, was the expectation to add the question mark , or the header with information to hover over??
