### ISSUE TITLE
Add the following tool tip to Version#/Alternative #

### ISSUE THREAD

**Issue by VJ1285** [hackforla/tdm-calculator#887]
### Overview
Need to add a tooltip to Alternative#/Version# to make it clear to the user what the function of this data. 

### Action Items

- [x] Add tooltip - "This helps distinguish different alternatives/scenarios for the same project."

### Resources/Instructions
REPLACE THIS TEXT -If there is a website which has documentation that helps with this issue provide the link(s) here.

**Comment by fyliu** [comment]
Assigning this one to myself since I already did this when it was part of #869

**Comment by fyliu** [comment]
See screenshot in pull request
