### ISSUE TITLE
EPIC: Button for reset project redesign

### ISSUE THREAD

**Issue by fyliu** [hackforla/tdm-calculator#898]
### Dependency
 - #974
 - #1344 
 - Determine based on the research if we are going to change the design and placement of the "reset project" or "start over" button, if we are, put this issue in prioritized backlog, if not, close this issue as unplanned

### Overview
We need to redesign the placement of the reset button to make it easier for users to understand it.

### Action Items
Create issues to 
- [ ] design button
- [ ] make change in code

### Resources/Instructions
  @KPHowley added the figma file for the existing design in the previous ticket
  https://www.figma.com/file/nD9QK56Mzq7xNSaSUoeGx0/?node-id=2626%3A11673

**Comment by SMR9220** [comment]
@ExperimentsInHonesty Are we moving forward with [this](https://www.figma.com/file/nD9QK56Mzq7xNSaSUoeGx0/?node-id=2626%3A11673) Figma design, or does the button design need to be revised? Just want to verify before I change the labels on this issue.

**Comment by pmeda12** [comment]
Summary of findings after reviewing interview recordings: Only 1 participant total interacted with the reset page button on page 4. 0 participants referred to, hovered over, or clicked the reset page or reset project button on page 2.

**Comment by amiteshsrivastava11** [comment]
At our 2024-12-03 stakeholder meeting, the stakeholders approved putting the reset button on the page as long as we added some space on the top of page 3.

**Comment by NilakshiS** [comment]
Replaced by:
- #1902
- #1993
