### ISSUE TITLE
Sort out hosting issues with LADOT to make a UAT and Production version

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/tdm-calculator#904]
### Overview
We need to have a UAT version and a Prod version with different databases

### Action Items
- [x] LA City to purchase and install to Azure an SSL Certificate for the url https://TDMCalc.lacity.org
- [x] LA City to establish Azure production Subscription, Resource Group, App Service and Database as described [here](https://github.com/hackforla/tdm-calculator/wiki/Azure-Deployment) - replacing the development settings with production settings. The existing App Service "tdm" will probably need to be dropped and re=created, unless it is possible to move it to the new production resource group.

### Resources/Instructions
[System Architecture Doc 3/2020](https://docs.google.com/document/d/1lSOdgQTdqKYDZmX1QhMHqcslsmAngb7VAu3KiqKcaCI/edit)
[Azure Deployment](https://github.com/hackforla/tdm-calculator/wiki/Azure-Deployment)

**Comment by ExperimentsInHonesty** [comment]
@entrotech please remember to copy tdm@hackforla.org on any communication with the department.

**Comment by ExperimentsInHonesty** [comment]
Next steps is that John will follow-up on current email chain so that we can have truly separate UAT and Production environments

**Comment by ExperimentsInHonesty** [comment]
Mentioned this during meeting today with David today.  David will follow up with Lon on setting up the Live production environment.

**Comment by entrotech** [comment]
Status update received from Lon Soh on Dec 2:

John and David, just to keep you abreast... I haven't forgotten about the PROD environment.  The cloning appears to be more involved than I had originally anticipated.  Also, I need to get caught up with other more pressing matters.  I just got back from a one week vacation.  Will get to the TDM Prod cloning as soon as I can.

**Comment by entrotech** [comment]
Still blocked waiting for ITA (Lon Soh, et. al) to be ready to work on this.

**Comment by entrotech** [comment]
Worked with Lon Soh and Alex Molina of ITA today, and go the production environment created and mostly configured.

After the meeting, I created the TDMPROD database table and data and changed the configuration settings for the production App Service at tdmprod.azurewebsites.net to use the new database.
To start, I created two user accounts ladot@dispostable and securityadmin@dispostable.com with the standard passwords. We should change the passwords to something more secure as soon as feasible.  Production users will need to register, confirm their email, etc. to be able to save projects in production, and there are no projects in production now, so we are starting with a clean slate.
There are a few tasks that Lon needs to follow-up on:1. Currently, the URL https://tdm.ladot.lacity.org is redirected to the "old" production url at tdm.azurewebsites.net, and it needs to be re-direct to https://tdmprod.ladot.lacity.org instead.2. We need to either move the SSL Certificate to the new App service or set up a new SSL certificate for the tdmprod App Service.3. Create an email account - something like ladot.tdm.noreply@lacity.org, which will be the "from address" for automated emails from the production application.4. Create a SendGrid account using the email address from Step 3 that is owned by Lon, configure the Email API for the account and change the configuration settings in the tdmprod App Service for EMAIL_SENDER to this email address, and the SENDGRID_API_KEY to the value obtained from the SendGrid Email API setup. (David needs to give Lon a memo to authorize funding for the new SendGrid account first.)
In the meantime, you should be able to access the production environment at https://tdmprod.azurewebsites.net. Let me know if any of you run into issues.

**Comment by entrotech** [comment]
This all seems to be working. We should drop the App Service "tdm" that was created to temporarily simulate a production environment, and possibly the SSL Certificate that goes with it in coordination with Lon.

![image](https://user-images.githubusercontent.com/9939032/153094615-445a5ac6-1d32-4dc1-ad8e-8140dfc8be7f.png)

**Comment by entrotech** [comment]
Met with Lon Soh and Alex Molina today and worked through deleting the extra App Service and configuring the production settings to use the correct email settings. Looks good!
