### ISSUE TITLE
Update the TDM strategies page to show nothing under earned section till any points are gained

### ISSUE THREAD

**Issue by seenaiype** [hackforla/tdm-calculator#909]
Based on discussion with LADOT, it would be helpful to keep earned point section empty till any points are gained. 

- [x] remove pts under earned section when no points are gained
- [x] Add the _count_ pts under earned section when any selection is done
- [x] When the points are unchecked, the column should be empty
- [x] Review with the PM

![image](https://user-images.githubusercontent.com/20568596/130542560-b1b562bb-f820-4874-9d0a-f7265ef16a3f.png)

**Comment by ExperimentsInHonesty** [comment]
Demoed to Stakholder (Dave/Alexander)

**Comment by seenaiype** [comment]
Closing ticket. Looks its been deployed into prod 

![image](https://user-images.githubusercontent.com/20568596/147416932-b009e316-b975-4ff6-9ce3-1e310a6c06fd.png)
