### ISSUE TITLE
Bug: Tabbing into AIN field should take a single tab in Page 1 / Project specification page

### ISSUE THREAD

**Issue by seenaiype** [hackforla/tdm-calculator#924]
### Overview
On the project overview page, the tabs work for the first two text boxes but not for the third text box for the AIN entry. Its not working on Chrome, Microsoft Edge, and Firefox

The tab problem specifically is that it takes 2 tab presses to get input focus on the AIN field. It should take only 1 tab press like all the other input fields.

Same problem when Shift-tabbing to go from AIN to the previous field. It's like there's a hidden tab stop between them.

### Action Items

- [x] Update the tab order to flow thru all the required text boxes
- [x] Confirm it works on couple of browser - IE, edge, chrome, firefox etc

### Resources/Instructions
![image](https://user-images.githubusercontent.com/20568596/131739066-8da9ccb2-f02f-4d63-bed9-e11ac6dedf09.png)

**Comment by R-Tomas-Gonzalez** [comment]
Hi, 

Can I work on this? Would love to help!

Thanks, 

-Tomas

**Comment by seenaiype** [comment]
Go ahead, and assign this ticket and move it to in-progress. Let us know, if you have any questions

**Comment by R-Tomas-Gonzalez** [comment]
@seenaiype Hi, I do not have access to the slack with my email

**Comment by seenaiype** [comment]
We would love to have you on our team. We do have an on-boarding session for HFLA , please enroll thru - https://www.hackforla.org/getting-started 

If the time zone doesn't work for you, please join our slack and we can help you get onboarded.

**Comment by fyliu** [comment]
We discussed this a little with @entrotech and he thought that it has to do with the field formatter that's being used for the AIN input. The behavior is it takes 2 tabs to get into that input field (on Firefix only for me). My main browser (Vivaldi, a Chromium-based browser) works fine.

**Comment by seenaiype** [comment]
Can we make it a single tab to the AIN input?

**Comment by R-Tomas-Gonzalez** [comment]
Hi @seenaiype, John and I went through this issue tonight together. 

**Reason for Issue:** 
We found that the reason it takes two tabs to get into the field is that the tab focus is catching on to the "AIN/APN (Assessor’s Identification Number)" link first, THEN tabbing into the form field. 

**Possible Solutions:** 
- Somehow skipping the tab focus from the link and going straight to the form field
- Creating focus to the link when we tab to it, possibly by bolding it or creating some sort of contrast

_Note_
I will be attending the tdm calculator meeting tomorrow evening and will bring this up with the team. I hope this helps and looking forward to meeting you! 

Cheers,

– Tomas

**Comment by fyliu** [comment]
https://stackoverflow.com/questions/2757973/can-i-ignore-some-website-element-when-navigating-using-the-tab-key

Proposed solution is tabindex="-1"

I was looking for something else I read before about taking elements out of tab ordering, but this one came up and looks promising.

**Comment by R-Tomas-Gonzalez** [comment]
> Good work figuring out the real problem!
> 
> https://stackoverflow.com/questions/2757973/can-i-ignore-some-website-element-when-navigating-using-the-tab-key
> 
> Proposed solution is tabindex="-1"
> 
> I was looking for something else I read before about taking elements out of tab ordering, but this one came up and looks promising.

Thanks for this @fyliu, this worked! Cheers :)
