### ISSUE TITLE
Auto-calculate project TDM Level based on entered project land use.

### ISSUE THREAD

**Issue by entrotech** [hackforla/tdm-calculator#93]

**Comment by entrotech** [comment]
Questions:  For purposes of calculating level:
I counted only Retail and Warehouse toward the Retail/Warehouse level (e.g., not Furniture Retail).
I counted all other inputs measured in Sq. Ft towards the "Commercial" total - even if they are "Institutional".
Inputs measured in classrooms or beds I did not count toward the level calculation at all.
I counted every input in the Residential box toward the residential level calculation except for Guest Rooms and Skilled Nursing Care Beds.

Is this right? If not, can you give me explicit rules?

**Comment by nicholaspung** [comment]
Line 2 of [rosemary requirements](https://drive.google.com/open?id=1F03uD-yk9aPuKoc6YuRyCI_kvZRCORwn)

**Comment by entrotech** [comment]
PR #117

**Comment by ExperimentsInHonesty** [comment]
Fang and Keven to review

**Comment by ExperimentsInHonesty** [comment]
move to questions when both reviews have reviewed

**Comment by entrotech** [comment]
This is implemented. However, there are "edge cases" where we don't have a way to calculate level. For example, a Hospital that only has a # of beds, or a school that only has a number of classrooms. Currently beds, classrooms and other unusual inputs don't count toward project level at all.
