### ISSUE TITLE
Implement and Document Application Insights Analytics  and Production Error Logging

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/tdm-calculator#941]
### Dependency
- #1268 

### Overview
We need to have documentation about Azure applicationinsights so that relevant team members can get up to speed quickly.

### Action Items
- [ ] Review issue #381
- [ ] Get added to 1password vault (if you are not already)
- [ ] interview John and record
- [ ] write up steps to access and interpret what is currently setup
- [ ] identify other items we want to track and why
- [ ] review with whole product team and Tech and Research lead
- [ ] implement new reports
- [ ] document reports

### Resources/Instructions
https://docs.microsoft.com/en-us/azure/azure-monitor/app/app-insights-overview

**Comment by Parisajf** [comment]
John recommended we cols this issue.
