### ISSUE TITLE
Refactor: Conditional Logic into variable names

### ISSUE THREAD

**Issue by jackrinjames** [hackforla/tdm-calculator#944]
### Overview
We need to move long conditional logic into variables with meaningful names so that they're less confusing.

### Action Items

- [ ] identify locations of conditional logic which might be appropriate for refactoring
- [ ] document examples with current state and future/proposed state

**Comment by ExperimentsInHonesty** [comment]
Ask Claire if this is CSS, HTML, Javascript, or other

**Comment by fyliu** [comment]
I think this is general code smells.

For expressions like (rules && rules.length !== 0), it should be replaced by a named variable called something like rulesLoaded. This is especially true if the exact condition is repeated several times in the code. The stopping point for this kind of refactoring is not very clear. Maybe until the dev is comfortable that the code is easy to understand.

**Comment by entrotech** [comment]
Need more clarification of the convention proposed.  Is this referring to if..else statements with many else clauses, or does it apply to nested ternary expressions as well?  Please be more specific in the request by including at least some examples

**Comment by Biuwa** [comment]
- #975

**Comment by entrotech** [comment]
Should be closed. The request is apparently some sort of coding convention that Claire was interested in, but did not define well enough to be actionable.
