### ISSUE TITLE
Create a Rules Context

### ISSUE THREAD

**Issue by jackrinjames** [hackforla/tdm-calculator#946]
### Dependency
- [x] BLOCKER: #954 - make sure that there are cypress tests coverage before starting this issue because changes to anything related to rules can be destructive if changed without test coverage to back up the changes

### Overview
We need a rules context so that we don't have to keep passing rules through components -- and so rules are globally available. 

### Action Items
- [ ] Run Cypress Tests

**Comment by KPHowley** [comment]
@nclairesays @fyliu @entrotech  - Add cypress test coverage #954  has been completed. Please review this issue to clarify if there are steps or directions that need to be fleshed out and we will add to the backlog.

**Comment by fyliu** [comment]
I think this is ready for the backlog. The tests are needed to make sure the changes for this issue doesn't break anything. This issue will touch many files.
