### ISSUE TITLE
Bug: Fix sidebar image scaling

### ISSUE THREAD

**Issue by jackrinjames** [hackforla/tdm-calculator#948]
### Overview
Fix sidebar image scaling. For example, on terms and conditions/privacy policy pages, background image is scaled differently depending on contents of page.  

### Action Items
- [x] Figure out how to tile background 

### Resources/Instructions
REPLACE THIS TEXT -If there is a website which has documentation that helps with this issue provide the link(s) here.

**Comment by entrotech** [comment]
![image](https://user-images.githubusercontent.com/9939032/135368975-04a4e4b7-f766-4c02-be3c-3c95d9dd7112.png)

![image](https://user-images.githubusercontent.com/9939032/135369006-fe9c7cb3-10be-498f-85f4-07630e990995.png)

![image](https://user-images.githubusercontent.com/9939032/135369094-7a3c86dd-3acd-4c2f-be1a-516f25c5c281.png)

**Comment by entrotech** [comment]
The scaling seems to be uniform now. The remaining question is whether it is the desired scaling.  The background image is designed such that it tiles seamlessly, so I set the scaling such that it does not repeat horizontally on the wider sidebar for the Calculation Wizard.
