### ISSUE TITLE
Refactor: Convert js files to jsx

### ISSUE THREAD

**Issue by jackrinjames** [hackforla/tdm-calculator#949]
### Overview
Convert js files to jsx because it's the correct technical file format for react

### Action Items

- [ ] add to this action item list all components that needs to be converted

### Resources/Instructions
REPLACE THIS TEXT -If there is a website which has documentation that helps with this issue provide the link(s) here.

**Comment by entrotech** [comment]
Changing file extensions for react component source code is unnecessary and somewhat controversial until/unless we start converting the application to Typscript, in which case the react component code should use an extension of *.tsx. We may re-open this if/when we convert to Typescript.
