### ISSUE TITLE
Display points for each strategy next to the strategy

### ISSUE THREAD

**Issue by entrotech** [hackforla/tdm-calculator#95]
This involves significant work on the calculation engine to link inputs or strategies to a single corresponding calculation, then have the UI group inputs of strategies with their rule to display the immediate consequence (parking spots or TDM points) next to the driver. Some calculations may not have a single driver, and we need to figure out if those should be displayed somewhere as well.

**Comment by nicholaspung** [comment]
Line 4 of [rosemary requirement](https://drive.google.com/open?id=1F03uD-yk9aPuKoc6YuRyCI_kvZRCORwn)

**Comment by ExperimentsInHonesty** [comment]
Kevin review

**Comment by KPHowley** [comment]
List or rules from DOT: https://hackforla.slack.com/files/UKY711H6X/FRHUXRZFY/tdm_pointgeneration_191011.xlsx

**Comment by entrotech** [comment]
Completed

**Comment by KPHowley** [comment]
The points corresponding to each Transportation Demand Strategy is only visible after the measure is selected, can they be made visible before?
