### ISSUE TITLE
Enhancement: Fix Tooltip Label

### ISSUE THREAD

**Issue by jackrinjames** [hackforla/tdm-calculator#950]
### Overview
Fix Tooltip Label to properly be associated with the input (ie: the "id" for the inputs, and label "for" aren't associated correctly)

### Action Items
Review all labels on front end used for tooltips
- [x] Page 1
- [x] Page 2
- [x] Page 3
- [x] Page 4
- [x] Projects page
- [x] [Public Comment](https://tdmdev.azurewebsites.net/publiccomment)
- [x] Login
- [x] Register
- [x] Forgot Password

**Comment by ExperimentsInHonesty** [comment]
Page 1
- [ ] Project Name
- [ ] Address
- [ ] AIN/APN (Assessor’s Identification Number)
- [ ] Alternative #
- [ ] Building Permit #
- [ ] LADOT Case #
- [ ] City Planning Case #
- [ ] Project Description *

Page 2

**Comment by entrotech** [comment]
No changes required. All Form Labels had an htmlFor attribute pointing to the corresponding input tag.
