### ISSUE TITLE
Refactor: remove double project info/description

### ISSUE THREAD

**Issue by jackrinjames** [hackforla/tdm-calculator#952]
### Overview
Get rid of the double description when adding new project. root level and in formInputs

### Action Items

- [ ] Determine best practice if Name should be stored in "forminputs" or in the root level 
- [ ] Make change

### Resources/Instructions

When saving a project, we're currently saving project information (e.g. name, address, description) in both the formInputs object and root level (see example below). We should decide where to save the data so we know where the source of truth is

```
      method: "POST",
      url: "http://localhost:5000/api/projects",
      body: {
        name: "Some Project Hotel",
        address: "12425 Hotel Bl.",
        formInputs:
          '{"PROJECT_NAME":"Some Project Hotel",\
          "PROJECT_ADDRESS":"12425 Victory Bl.",\
          "PROJECT_DESCRIPTION":"80-room four-story hotel.",\
         }',
        calculationId: 1,
        dateCreated: "2020-11-12T00:38:42.763Z",
        dateModified: "2020-11-12T00:39:04.436Z",
        description: "80-room four-story hotel.",
        loginId: 37, 
        firstName: "LA",
        lastName: "DOT",
      },
```

**Comment by entrotech** [comment]
Not a good idea.  The data is stored redundantly on purpose and automatically synced by design. Having this info in separate columns makes it easy to search, filter and view, while also having it in the formInputs allows the JSON for the project to completely represent the project data.
