### ISSUE TITLE
Change Tooltip Icons to LADOT Blue text on green background.

### ISSUE THREAD

**Issue by entrotech** [hackforla/tdm-calculator#956]
### Overview
The current design has white text (question mark) on green background, which does not have enough contrast to read easily. Change Tooltip Icons to LADOT Blue text on green background, wherever it appears in the application.

### Action Items
- [x] Change styling of tooltip icons per above.

### Resources/Instructions

![image](https://user-images.githubusercontent.com/9939032/134446511-50561a3e-a4d8-4002-8196-257ee5955275.png)

**Comment by Jonathanko52** [comment]
Changed all tooltip question mark colors form white to blue. Need to confirm whether this is done with all instances of the tooltip on the app, or strictly for the sidebar.
