### ISSUE TITLE
Enhancement: Create Mockups for New tooltip design 

### ISSUE THREAD

**Issue by jackrinjames** [hackforla/tdm-calculator#957]
### Overview
Create mockups of hover tooltips with dropdown info.

### Action Items
- [x] determine best way to design new tooltips
- [ ] - #972 on pause until 972 is resolved

Key points:
- [x] have info on drop down beneath line item
- [x] add close "x" button on tooltip info
- [x] 10/2 - Put hyperlinks into tooltip

**Comment by mttran234** [comment]
1st mock up showed the arrows and decided the arrows when multiple tooltips are open would be overwhelming visually but in 9/29/21 team meeting, team wants to see the arrows again on the left side 

[TDM Calculator.zip](https://github.com/hackforla/tdm-calculator/files/7270645/TDM.Calculator.zip)

**Comment by mttran234** [comment]
showed 2 iterations of tooltip mockup in 9/29/21 meeting

<img width="556" alt="Screen Shot 2021-10-01 at 8 28 06 PM" src="https://user-images.githubusercontent.com/77904061/135697883-344a13c9-ddbc-471e-81b2-ad551eb969e2.png">


<img width="426" alt="Screen Shot 2021-10-01 at 8 40 44 PM" src="https://user-images.githubusercontent.com/77904061/135698260-4333c255-8212-4b40-8b44-c47fb28ad3ef.png">


Design team is going to show other iterations of the tooltip mockup with multiple tooltips shown. We will be showing the following on 10/2/21 meeting: 
-iteration with arrows on the left hover state
-iteration with bolded hover state

**Comment by KPHowley** [comment]
@mttran234 @Shaeeka  - can we post the most recent designs on this issue?

**Comment by mttran234** [comment]
Screenshoot of all tooltip accordions open<img width="789" alt="Screen Shot 2021-12-15 at 8 59 41 PM" src="https://user-images.githubusercontent.com/77904061/146294117-1eb29af7-c629-4b5a-bea7-0e1172b99949.png">

Prototype Link: https://www.figma.com/proto/nD9QK56Mzq7xNSaSUoeGx0/TDM-Calculator?node-id=4961%3A17[…]width&page-id=4107%3A13052&starting-point-node-id=4898%3A17350

Figma ToolTip Page Link: https://www.figma.com/file/nD9QK56Mzq7xNSaSUoeGx0/TDM-Calculator?node-id=4898%3A17350
