### ISSUE TITLE
Fix strategies row spacing in page 5

### ISSUE THREAD

**Issue by fyliu** [hackforla/tdm-calculator#962]
### Overview
Some strategy rows have more space than others. They should be uniform.

### Action Items
- [x] Make strategy rows display uniform spacing

### Resources/Instructions
Edit RuleStrategy.js
<details>
<summary>Click to expand screenshot to see spacing differences</summary>

![2021-09-26 21 27 19 localhost ebbb375397e5](https://user-images.githubusercontent.com/1160105/134846044-0f4626b8-beda-4068-83e3-fbcbacdadfbe.png)
</details>

**Comment by jahpe777** [comment]
Fixed row spacing #962
