### ISSUE TITLE
Bug: Fix blank screen when creating duplicate project

### ISSUE THREAD

**Issue by jackrinjames** [hackforla/tdm-calculator#965]
### Overview

When duplicating a project, and then "X"ing out, screen goes blank instead of back to project screen. 

### Action Items

- [x] Determine Issue and fix in front end 

### Resources/Instructions

The intended interaction should be the page reloads when a project is saved and the user is simply is brought back to the page and the modal is closed if they "cancel or "x" out of the box. 
 
*Projects page is only visible when logged in.

[video of example](https://nimb.ws/mnlJ3K)

**Comment by jahpe777** [comment]
This also applies to the Delete modal as well.

**Comment by jahpe777** [comment]
Fixed blank screen when creating duplicate and delete project #965
