### ISSUE TITLE
Bug: Fix sidebar background scrolling with main page

### ISSUE THREAD

**Issue by jackrinjames** [hackforla/tdm-calculator#966]
### Overview
Tiled images in side bar scroll with the page instead of staying static. 

### Action Items

- [ ] make tiled sidebar images static

### Resources/Instructions

The background of the tiles should be static:
https://user-images.githubusercontent.com/90736143/141241134-c76df247-2699-42b7-80d3-7d7e402acfa5.mov

**Comment by KPHowley** [comment]
@jackrinjames - Can you flesh this issue out a bit more to make it actionable.

**Comment by jackrinjames** [comment]
The background of the tiles should be static: 
https://user-images.githubusercontent.com/90736143/141241134-c76df247-2699-42b7-80d3-7d7e402acfa5.mov
