### ISSUE TITLE
Create style guide

### ISSUE THREAD

**Issue by jackrinjames** [hackforla/tdm-calculator#972]
### Overview

Create a style guide for consistency across the site

### Action Items

Create detailed information about: 
- [ ] Notifications
- [ ] Popups
- [ ] Errors
- [ ] Close Crosses
- [ ] Tooltips
- [ ] Colors
- [ ] Menus
- [ ] Buttons
- [ ] Fields and Labels
- [ ] Typography
- [ ] Inconcography
- [ ] Margins/Padding
- [ ] Logo
- [ ] .... all other components deemed necessary

### Resources/Instructions

#536 - issue for front end Audit that is linked (not necessarily a dependency though)

**Comment by mojimoh** [comment]
- Merged with #536, action items listed for ease of completion.
