### ISSUE TITLE
Usability Testing 2 Epic

### ISSUE THREAD

**Issue by jackrinjames** [hackforla/tdm-calculator#974]
### Dependency
- Audit the existing materials and make templates #979 - DONE

### Overview
Conduct additional usability testing for side bar and additional UX features like tool tips

### Action Items
 - [x] Review templates
 - [x] Create research plan (defining changes to the materials that will be required) #1084 
 - [x] find participants
 - [x] schedule participants
 - [x] conduct testing
 - [x] summarize and report findings

### Resources/Instructions
Emily from LACP would like to be involved in communications to seem more official.

**Comment by mojimoh** [comment]
Follow up with Jane on the related issues that this identifies in next team meeting

**Comment by mojimoh** [comment]
@Jane4925 
Please provide update
1. Progress: "What is the current status of your project? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"
5. Pictures (if necessary): "Add any pictures that will help illustrate what you are working on."

**Comment by Jane4925** [comment]
Usability testing 2 occurred on Feb, 2022.  We summarized the findings and reported on Jun 2022 with [Journey Map](https://drive.google.com/file/d/1a2mW34N0lcZVnMKWQTfldLQH8dxGycRn/view?usp=share_link) and [Issue Tracker](https://docs.google.com/spreadsheets/d/1SWcf55uRkXV41uCMTp7VLelAslf6rQCGeyCYXfGzbBU/edit?usp=sharing)
