### ISSUE TITLE
Make cypress tests more stable

### ISSUE THREAD

**Issue by fyliu** [hackforla/tdm-calculator#981]
### Overview
We need to have Cypress tests to make sure that if a developer makes changes to the website and there is an error it can be identified as a bug to be fixed.

### Detail
Cypress tests are randomly failing on input fields where inputs aren't loaded or saved correctly. We're currently doing get.type for inputs. I'm thinking adding the "should" will add extra wait time and make the tests more stable. There's a lot of lines to update in the code.

### Action Items
- [ ] Use get.type.should for cypress tests
- [ ] Evaluate if that makes the tests more stable

### Resources/Instructions
See the last line in the code box for an example
https://docs.cypress.io/api/commands/type#Event-Cancellation

**Comment by mojimoh** [comment]
This issue needs an overview

**Comment by entrotech** [comment]
Cypress tests were very fragile, not well maintained, and created more development work than they were worth.
