### ISSUE TITLE
Create a favicon icon for the TDM site

### ISSUE THREAD

**Issue by dddhoang** [hackforla/tdm-calculator#985]
### Overview
A favicon needs to be created for the site that will appear next to the web address link in the address bar. 

### Action Items
- [ ] use the favicon from ladot.lacity.org (attached below)
- [ ] the browser tab/address bar icon should be 16x16px

### Resources/Instructions
PNG for browser tab/address bar icon will be in 16x16px

![image](https://user-images.githubusercontent.com/98936028/176322807-5a603788-f46a-4797-a641-7f0572f133ac.png)

**Comment by ExperimentsInHonesty** [comment]
use the favicon from ladot.lacity.org

**Comment by SMR9220** [comment]
@entrotech does there need to be a development issue created for this?
