### ISSUE TITLE
Update changes to multiple AIN display on final summary page

### ISSUE THREAD

**Issue by dddhoang** [hackforla/tdm-calculator#988]
### Overview
We need to finalize changes to multiple AIN to be displayed on the final summary page (Calculation/6). 

### Action Items
- [x] Adjust final mock-up in Figma for display of multiple AIN on summary page
- [x] Determine display of AIN numbers (separated tags vs. separated number strings, commas/semi-colons, etc.)
- [x] Share UX design options and finalize choice 
- [ ] Create issue for front-end development (PM)

**Comment by cduong5** [comment]
![Frame 9](https://user-images.githubusercontent.com/82553907/143803684-c546a3fa-40cc-49f9-a9c8-74bc09553403.png)
Mockup for AIN/APN summary page. The section will display three AIN/APN numbers at a time be able to expand.

See mockup here: https://www.figma.com/file/nD9QK56Mzq7xNSaSUoeGx0/TDM-Calculator?node-id=4866%3A17408
See prototype here: https://www.figma.com/proto/nD9QK56Mzq7xNSaSUoeGx0/TDM-Calculator?node-id=4866%3A17408&scaling=min-zoom&page-id=4866%3A17408&starting-point-node-id=4866%3A17409

**Comment by cduong5** [comment]
Moved frames here: https://www.figma.com/file/nD9QK56Mzq7xNSaSUoeGx0/TDM-Calculator?node-id=1744%3A3531
