### ISSUE TITLE
Questions came out of UX Audit

### ISSUE THREAD

**Issue by Jane4925** [hackforla/tdm-calculator#996]
### Overview
 Questions came out of the UX Audit need to be answered, see [sheet
](https://docs.google.com/spreadsheets/d/1u0vfSqVFrSuMMAsEvgZNUfIfjNXdzqJ9VurNV1oGpeU/edit#gid=70429136)

### Action Items
For Kevin:
- [x] Walk Jane/Bonnie through the [actual user survey folder](https://lahubcom.maps.arcgis.com/home/content.html?view=table&sortOrder=desc&sortField=modified&folder=tdmux_lahubcom#content) created in ArcGIS
- [x] Figure out why are there 2 documents for survey results
   - [x] Document 1: [Demographic Survey Results as of 3/27/21](https://docs.google.com/spreadsheets/d/1V-TczYvrI6dBqcrJXCn3rOqKPJ56eCsQrALZmXtN-30/edit#gid=428484702)
   - [x] Document 2: [Final Survey Results - 4/13](https://docs.google.com/spreadsheets/d/14hVD2om7ET7dwhTvbi1hoXoupjllyNDcCXvqZpb3WEQ/edit#gid=436638186)
- [x] Create a guide for issue #807
   - [x] How was this setup done, there are no details in the issue
- [x] Ask during stakeholder meeting #888- When are the following 2 forms were used in the planning process
   - [x] Form 1: [Department of City Planning Application](https://planning.lacity.org/odocument/3d913582-d6e7-4375-90e8-3e276b9c28bb/Department%20of%20City%20Planning%20Application.pdf)
   - [x] Form 2:[ Transportation Study Assessment](https://planning.lacity.org/odocument/2cfe7c08-54e2-4d73-8bab-58cc4a6cbe42/Transportation%20Study%20Assessment.pdf)

**Comment by Jane4925** [comment]
- ArcGIS: login tdm account ->survey 123 -> latest draft
- Survey Result: document 1 -> demographic result of all data recollected -> show if sample is representative, document 2 -> streamlined result of actual samples would involved in the interviews -> help determining corresponding project type 
- Forms: both forms target specific groups of people, not generic forms that everyone would need for the process

**Comment by ExperimentsInHonesty** [comment]
@Jane4925 will build the otter.ai guide and then close this issue if no additonal questions
