### ISSUE TITLE
Revise Employer Package with pricing parking TDM strategy and make the packages mutually exclusive

### ISSUE THREAD

**Issue by Dsomers74** [hackforla/tdm-calculator#998]
### Overview
Need to revise the Employment Package to replace the parking strategy to equal 14 points. This is essentially the same as the 'Residential Package'. This includes clarifying text changes and making packages mutually exclusive. 

### Action Items

1. Reassign the parking strategy from ‘Cash-Out’ to ‘Pricing/Unbundling: each parking space is $220/mo’
2. Displace strategy text as '+8 Points for Priced / Unbundled Parking' 
3. In the 'Residential Package', revise the parking strategy text from '+8 Points for Unbundling Parking' to '+8 Points for Priced / Unbundled Parking' 
2. Make the selection of employer, residential, and schools packages mutually exclusive

**Comment by ExperimentsInHonesty** [comment]
## Notes from meeting with Stakeholders: 
### Page 3 two separate boxes for Residential or Employment Package and School Package, and they are NOT mutually exclusive, but you can only earn 1 pt for choosing any or all of the bonus packages.  
### Page 4 Also, we will change where it says 
residential bonus packages 1pt possible / earned
employment bonus packages 1pt possible / earned
to say something like this
Choose any bonus package (Residential or Employment Package and School Packages ) and receive 1 bonus point.

**Comment by entrotech** [comment]
On the Package page, I just changed the Cards to show correct information and point totals for the "Employment or Commercial" and "School" packages.  There are a few design issues that are likely to change the exact wording, and probably get rid of the Packages page entirely.
